chef/automate

components/automate-deployment/pkg/converge/stop_mitigation.go, components/automate-deployment/pkg/depot/garbage_collect.go, components/automate-deployment/pkg/server/restart.go
Right now we use the converger to stop all services. Since the
converger is also where the package garbage collector runs, we were
deleting packages on shutdown, which seems unnecessary and just slows
down the restart.
=> [deployment] Don't run GC when stopping services

components/automate-cli/cmd/chef-automate/applications.go
Visibility into applications (habitat) data is currently alpha quality
and feature-flagged off by default. For architectural reasons, three
different feature toggles must be flipped to fully enable the feature on
the back-end. To make it easier for developers (and eventually users) to
test, this patch adds a CLI subcommand to toggle the feature. The
subcommand is currently hidden; we likely will unhide it in the future
to facilitate an open beta.
* build components/automate-cli
* the default config for the hab studio enables all the feature flags, so you need to run `chef-automate applications disable` first. After running it, the NATS ports should not be listening, for example `netstat -an | grep LISTEN |grep 4222` should not show anything.
* Turn the applications …
=> Add chef-automate subcommands to toggle applications tab features

components/automate-ui/src/app/pages/service-groups/service-groups.component.scss, components/automate-ui/src/app/pipes/service-status-icon.pipe.spec.ts, components/automate-ui/src/app/pipes/service-status-icon.pipe.ts
Quick color and icon fix for the service-groups table:
**Before:**
**After:**
=> [UI] Fixes Unknown service-group status/table

components/compliance-service/ingest/pipeline/processor/reports_project_tagger_test.go, components/compliance-service/ingest/projectupdater/manager.go, components/compliance-service/integration_test/reporting_server_list_reports_test.go, components/compliance-service/integration_test/reporting_server_read_report_test.go, components/compliance-service/integration_test/reports_projects_update_test.go, components/compliance-service/reporting/relaxting/reports.go
Some tangentially related changes I had made in #53 but didn't include for clarity.
* I ran `gofmt -s -w -l` on `compliance-service`. Our linter has simplification turned off for some reason (that's the `-s`), even though `make lint` tells you to run it:
```
reporting/relaxting/reports.go:711: File is not `gofmt`-ed with `-s` (gofmt)
```
* I rearranged some code in the report filtering to make it more clear where some values are used.
* After our meeting this morning I realized I was embedding the special value `*` in some tests, so I replaced that with the constant from `authz_service`
=> List reports cleanup

components/automate-deployment/pkg/server/backup.go
We've taken the lock here, but we return an error without giving it
back.
=> Fix case where we could deadlock

components/compliance-service/ingest/examples/compliance-success-tiny-report.json, components/compliance-service/reporting/relaxting/es_types.go
We don't have `fqdn` in the summary data model. By removing FQDN from the summary struct, we avoid adding a blank value in elasticsearch for every summary document.
I've also added the new fields to the tiny report we use for local dev & test.
=> Remove fqdn from Summary doc struct since we don't have it in the data model

components/compliance-service/compliance.go, components/compliance-service/inspec-agent/remote/remote.go, components/compliance-service/inspec/cli.go
Tested with `chef/inspec/4.1.3/20190417211329`
With this change, we use ENV variable `CHEF_LICENSE=accept-no-persist` to prevent inspec from prompting for chef license acceptance
=> Accept chef license for inspec 4 via ENV variable

components/compliance-service/integration_test/reporting_server_read_report_test.go, components/compliance-service/integration_test/suite_test.go, components/compliance-service/reporting/relaxting/reports.go
Followup to #23 and #53. ~~Branched from #97 so that code is in here as well.~~
This updates the project work the GetReport endpoing in reporting server to handle access to unassigned reports as detailed in #66.
=> Support for unassigned reports in reporting server GetReport endpoint

terraform/test-environments/modules/chef_automate_install/templates/install_chef_automate_cli.sh.tpl
Cleaning up some leftover logging during setting up a new machine in the deployment farm.
A couple lines of extraneous logging removed during buildkite deployments.
Can be viewed in deployment logs.
PR - #78
=> Remove logging that was added for diagnosis

components/applications-service/pkg/generator/config_test.go, components/applications-service/pkg/generator/runner.go
If we are not actively doing load test work, we are probably gonna
forget to update the load generator when we add some new data field to
our habitat events. Add a test that can detect when a new field is added
to the applications.HabService message and we don't add code to the load
generator to fill it in.
Comment out one of the new lines I added in components/applications-service/pkg/generator/runner.go and you should see the test I added fail with a message like:
```
Test:       	TestDefaultProfileIsViable
Error Trace:    config_test.go:95
Error:      	Should not be: ""
Test:       	TestDefaultProfileIsViable
Messages:   	Field "Fqdn" of the HabService message was set to the zero value for its type (string); MessagePrototype.CreateMessage() may need to be updated
```
=> Add a test to ensure load generator code stays updated

.expeditor/create-manifest.rb, .studiorc, components/automate-deployment/habitat/plan.sh, components/automate-deployment/pkg/converge/compiler.go, components/automate-deployment/pkg/target/local_target.go
We hit https://github.com/habitat-sh/habitat/issues/6252 again in our pipeline. This time, we were able to get a stacktrace, but we still don't understand where it's coming from or why it's happening
=> Downgrade hab to 0.69

.expeditor/verify.pipeline.yml, .studio/golang, components/applications-service/.gitignore, components/applications-service/Makefile, components/applications-service/cmd/applications-publisher/main.go, components/applications-service/cmd/applications-service/commands/root.go, components/applications-service/cmd/applications-service/commands/serve.go, components/applications-service/pkg/generator/runner.go, components/applications-service/pkg/nats/nats.go, components/applications-service/pkg/nats/publisher.go, components/applications-service/pkg/storage/postgres/hab_event.go
Changes applications-service to use `Makefile.common_go` stuff, which implies that we start using golangci-lint. That linter found a handful of issues, many of which are real bugs. Previously we were using the studio function `go_component_static_tests` which just runs `gofmt` so isn't very useful. We _could_ change `go_component_static_tests` to run golangci-lint, but the following projects use it:
*  config-mgmt-service
* ingest-service
* secrets-service
The other problem with the studio function is it doesn't have the same customization capabilities as the makefile approach. For example, with the makefile, it's possible to pin golangci-lint to a specific version if you need.
As far as I can tell, most devs are running the linter on their host and not the studio.  As of golangci-lint …
=> Enable additional static tests for apps svc and fix lint issues

components/authz-service/server/v2/policy_test.go, components/authz-service/storage/v2/type.go, components/teams-service/constants/constants.go, components/teams-service/server/v2/server_test.go, components/teams-service/storage/memstore/memstore.go, components/teams-service/storage/postgres/postgres.go
Purely cosmetic cleanup:
* Consolidated use of literal "(unassigned)" into exactly one use per service.
* Lots of indentation cleanup for readability in postgres tests for teams.
* Removed duplicate import in one file.
Everything still works.
=> Minor cleanup in teams and authz services

components/config-mgmt-service/backend/elastic/elastic.go, components/config-mgmt-service/backend/elastic/nodes.go, components/config-mgmt-service/backend/elastic/runs.go, components/config-mgmt-service/backend/elastic/suggestions.go, components/config-mgmt-service/config/service.go, components/config-mgmt-service/grpcserver/cfg_mgmt.go, components/secrets-service/cmd/secrets-service/commands/root.go, components/secrets-service/cmd/secrets-service/commands/serve.go, components/secrets-service/dao/filtering.go, components/secrets-service/dao/secrets.go, components/secrets-service/dao/tags.go, components/secrets-service/server/server.go
These are 2 of the 3 services that don't seem to be using the linter
currently. This applies the linter to those projects which will
hopefully make it a bit easier to transition to having
`go_component_static_tests` run the linter.
`ingest-service` is, I believe, likely the last service that needs to
have the linter applied to it. I have not done it here because there
are a large number of errcheck violations that need to be looked at
carefully.
=> Apply golangci-lint to config-mgmt-service and secrets-service

terraform/test-environments/modules/chef_automate_install/templates/install_chef_automate_cli.sh.tpl
This is untested, but this environment variable is what we use in
other locations to accept the inspec license.
=> [CI] Accept inspec license during terraform install

.expeditor/publish-release-notes.sh
until a date to be decided further in the future, the release notes
should contain a warning and link to our post on the upgrade impact
related to deep filtering index changes. before we forget to add them
I've put them into the automatic release note template that gets
reset on every promotion
=> [release notes] add upgrade impact warning

.expeditor/update_habitat.sh
This allows you to build a deployment-service and manifest with an
upgraded habitat via:
```
NO_GIT=true EXPEDITOR_VERSION=0.79.1 ./.expeditor/update_habitat.sh
./expeditor/create-manifest.rb
build components/automate-deployment
``
=> Make it easier to use update_habitat.sh script locally

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profile/reporting-profile.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profile/reporting-profile.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profile/reporting-profile.component.ts, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profiles/reporting-profiles.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profiles/reporting-profiles.component.ts
Fixes https://github.com/chef/automate/issues/149
On top of adding the scan time under the node name, this PR also changes the `latest_report.end_time` sort order from  ASC(default) to DESC to put the recently scanned nodes at the top of the list.
Result:
=>  Add scan time on Scan Results node lists

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-nodes/reporting-nodes.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-nodes/reporting-nodes.component.ts, components/compliance-service/api/tests/04_stats_spec.rb, components/compliance-service/api/tests/05_stats_summary_spec.rb, components/compliance-service/generator/report/samples/o10-full.json, components/compliance-service/reporting/relaxting/stats_report_level.go
Fixes https://github.com/chef/automate/issues/165
Required a backend change for the `Summary > Node Status` section and UI change for the `Nodes > Control Failures` column value.
=> Fix compliance status inconsistency for skipped node

integration/run_test, integration/services/automate_cluster/a2_setup.sh, integration/services/automate_cluster/init, integration/tests/multi_node.sh
Currently, run's 2 A2 nodes and 2 HA backend nodes
```
EXTERNAL_ONLY=1 HAB_ORIGIN=jaym ./integration/run_test ./integration/tests/multi_node.sh
```
Still todo is a load balancer
=> use test framework to spin up a2 cluster

.expeditor/announce-acceptance.sh, .expeditor/config.yml
The PR automates the weekly internal promotion announcement such that it doesn't need to be run from a local laptop and pasted to Slack.
=> [promotion] automate weekly promotion announcement

components/automate-ui/src/app/app.module.ts, components/automate-ui/src/app/ngrx.effects.ts, components/automate-ui/src/app/ngrx.reducers.ts, components/automate-ui/src/app/page-components/navbar/navbar.component.html, components/automate-ui/src/app/page-components/navbar/navbar.component.spec.ts, components/automate-ui/src/app/page-components/navbar/navbar.component.ts, components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.html, components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.scss, components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.ts, components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.spec.ts, components/automate-ui/src/app/page-components/projects-filter/projects-filter.component.html, components/automate-ui/src/app/page-components/projects-filter/projects-filter.component.scss, components/automate-ui/src/app/page-components/projects-filter/projects-filter.component.ts, components/automate-ui/src/app/page-components/projects-filter/projects-filter.spec.ts, components/automate-ui/src/app/services/projects-filter/projects-filter.actions.ts, components/automate-ui/src/app/services/projects-filter/projects-filter.effects.ts, components/automate-ui/src/app/services/projects-filter/projects-filter.reducer.ts, components/automate-ui/src/app/services/projects-filter/projects-filter.selectors.ts, components/automate-ui/src/app/services/projects-filter/projects-filter.service.ts
Adds some UI components for the global projects filter and wires them up to static placeholder data.
https://chefio.atlassian.net/browse/A2-248
=> [A2-248] Add global projects-filter components

ec2/README.md, ec2/Vagrantfile
With this change, the ec2 Vagrant setup is not restoring EBS volumes by default for the elasticsearch data directory. And can restore any snapshot now.
=> Optional EBS snapshot restore for ec2/vagrant setup

components/applications-service/cmd/applications-load-gen/commands/describe.go, components/applications-service/cmd/applications-service/commands/serve.go, components/applications-service/dev/applications-load-gen/2019-04-results.md, components/applications-service/pkg/generator/config.go, components/applications-service/pkg/generator/runner.go, components/applications-service/pkg/nats/nats.go, components/applications-service/pkg/server/ingest.go, components/applications-service/pkg/storage/postgres/db.go, components/applications-service/pkg/storage/postgres/hab_event.go, components/applications-service/pkg/storage/postgres/service.go, components/applications-service/pkg/storage/postgres/service_groups.go, components/applications-service/pkg/storage/postgres/testing_functions.go, components/automate-prometheus/habitat/config/prometheus.yml, components/event-service/nats/server.go
This patch contains a handful of small-ish items I fixed/changed in the process of load testing the ingestion system:
* Set lower limits on NATS streaming message storage. We've had operational problems with unlimited queues in the past; NATS is not unlimited by default, but the limits are too large for our current performance characteristics. I opted to not do anything too fancy but left a lengthy code comment explaining.
* first step changing ingestion code to a pipeline. We use one goroutine to read messages from NATS and pass them via a go channel to a set of worker goroutines. Since go uses m:n threading we can just spawn a fairly large fixed number of workers.
* Add some rollup stats when describing a load generator configuration so you have a better idea what the generated load …
=> Load Test Fixes

components/automate-cli/cmd/chef-automate/license.go, components/automate-cli/pkg/diagnostics/integration/compliance_report_scan_nodes.go, components/automate-deployment/pkg/server/node_inventory.go, components/automate-deployment/pkg/server/usage.go, lib/grpc/timestamp/timestamp.go, lib/grpc/timestamp/timestamp_test.go
this change adds timestamp strings to scanned nodes in the
`chef-automate license usage` command. the output (taken below from
test data) now looks like the following:
```
"scanned_nodes": [
{
"id": "cd03cf26-7ab3-4b14-87f4-9ef54bbac1c8",
"name": "integration-diagnostic-20190427004524",
"scan_job_id": "7f7a8772-3180-4dc3-9af6-95a463e78388",
"last_seen": "2019-04-27T00:45:26Z"
}
]
```
the key naming `last_seen` was chosed to keep consistency with the
timestamp used in the chef runs section of the output and uses the
same timestamp fomatting for consistency
=> [license usage] add timestamp to scanned nodes

components/nodemanager-service/managers/azure/azure.go, components/nodemanager-service/tests/azure_vm_nodes_integration_test.go
This is a small improvement to improve the experience of filtering nodes when using the Azure vm integration.
In AWS, name is considered a tag, whereas in Azure name is considered a separate field. Given that we only provide search via tags and regions when creating a scan job, this means users using the AWS-ec2 integration were able to search by name while users using the Azure-vm integration were not.   Including the name in the tag search will allow users of the Azure-vm integration to filter nodes by name when creating a scan job, getting us closer to parity between the two integrations.
Name shows up as an available tag when using the Azure-vm integration. Available names are listed as tag values. Nodes are filtered by the name selected.
rebuild nodemanager-service
add an Azure …
=> azure integration: include names in tag search

components/automate-deployment/pkg/backup/runner.go, components/automate-deployment/pkg/server/server.go
Previously, we were not persisting the manifest at the end of the
restore process. This meant that the first converge after an "upgrade
restore" would potentially result in a downgrade if the user had their
upgrade strategy set to none because the converge loop would use the
old manifest.
TODO:
=> [deployment] Persist the backup manifest on restore

components/automate-deployment/pkg/backup/runner.go
Without the TaskComplete() message the DeployStatus grpc request never
finishes server-side. This can lead to the service failing to stop
when sent a TERM.
=> [deployment] Send TaskComplete to event stream during restore

components/compliance-service/docs/adding_test_data.md, components/compliance-service/scripts/create-pg-data.sh
Just adding some notes on how to add data in Automate for compliance reporting, scan jobs, and node integrations.
I've also added a docker test target in the create-pg-data script. I'm not convinced this will actually work from the dev environment, since we're in a vagrant box or docker box and reaching out to a local docker machine isn't realllly possible, but maybe it works for the docker dev env as it is testing itself?anyways, I'm leaving it there for now as having an unreachable node is also good for dummy data.  
This also makes me wonder why we don't allow users to add docker containers for scanning in Automate? I'll look into this more..
Notes on how to add data in dev environment.
=> notes for adding data in automate for compliance, scan jobs, node integrations

components/authz-service/storage/postgres/migration/sql/41_query_roles_with_projects_match.up.sql, components/authz-service/storage/postgres/migration/sql/42_remove_leftover_functions.up.sql, components/authz-service/storage/v2/postgres/postgres_test.go, components/teams-service/storage/postgres/postgres.go
While performing an audit of our code to examine how project filtering is handled amongst all the auth entities, I noticed a few things that needed clean-up.
1. Swapping in `projects_match` in `query_roles` in lieu of the duplicate, inline code.
2. Removing deprecated functions that were still present due to signature changes due to two issues: (a) `create or replace` only replaces if the function signature matches; otherwise it is just `create`. 
(b) the `drop function` command also requires matching signatures; otherwise it fails silently.
3. DB functions in teams-service are a hodgepodge of v1 and v2 code. It is important to delineate which are v1 only so the casual reader does not get alarmed that project-handling is absent from those.
Examine the individual commits for the details. …
=> [A2-787] authz-service and teams-service db cleanup

components/authz-service/storage/v2/postgres/postgres.go
The new integration tests in role_projects.rb ( A2-747 In Development ) showed three failing tests:
The TL;DR is that there is a role containing 2 projects, one that is allowed and one that is denied. The call is authorized correctly: `ProjectsAuthorized` returns the allowed project. The call then proceeds to the authz service to perform a get, update, or delete. There, it invokes a piece of inline SQL to determine if the given role has a project that matches the allowed project that was requested. The SQL was incorrectly saying "no" when it should have said "yes".
This turned out to be a non-deterministic artifact which is why it may have escaped notice until now. In fact, I reproduced the scenario from the `GetRole` integration test on the command line, i.e. running curl instead of …
=> [A2-786] Correct project intersection query for roles

components/compliance-service/reporting/relaxting/profiles.go
When posting a profile to be ingested, we need to take the group information from the profile itself.
=> take group info from profile when parsing

components/automate-ui/src/app/entities/service-groups/service-groups.model.ts, components/automate-ui/src/app/entities/service-groups/service-groups.reducer.ts, components/automate-ui/src/app/page-components/services-sidebar/services-sidebar.component.html, components/automate-ui/src/app/page-components/services-sidebar/services-sidebar.component.ts, components/automate-ui/src/app/pages/service-groups/service-groups.component.html, components/automate-ui/src/app/pages/service-groups/service-groups.component.ts
The health filter bar was commented out with the PR https://github.com/chef/automate/pull/157, this work is to uncomment it and have the bar visible again.
It also fixed the problem found in the above PR where the Redux state was not well initialized.
EXTRA: Fixed more little nitpicks from the codebase. Also used the selected status variable to make it persistent on reload.
=> Revert commented health bar https://github.com/chef/automate/pull/157

components/authz-service/constants/v2/constants.go, components/authz-service/engine/conformance/conformance_v2_test.go, components/authz-service/server/v2/authz.go, components/authz-service/server/v2/authz_test.go, components/authz-service/server/v2/system.go, inspec/a2-iam-v2-integration/controls/base.rb, inspec/a2-iam-v2p1-only-integration/controls/role_projects.rb
follow-up to https://github.com/chef/automate/pull/135 
```
[16][default:/src:0]# chef-automate iam upgrade-to-v2 --beta2.1
Enabling IAM v2.1
Migrating v1 policies...
Creating default teams Editors and Viewers...
Migrating existing teams...
Success: Enabled IAM v2.1
[22][default:/src:0]# curl -H "api-token: $TOK"  -d '{"id": "p1", "name": "project 1"}' https://localhost/apis/iam/v2beta/projects --insecure | jq
{
"project": {
"name": "project 1",
"id": "p1",
"type": "CUSTOM",
"projects": [
"p1"
]
}
}
[18][default:/src:0]# curl -H "api-token: $TOK"  -d '{"id": "team1", "name": "team 1", "projects": ["p1"]}' https://localhost/apis/iam/v2beta/teams --insecure | jq
{
"team": {
"id": "team1",
"name": "team 1",
"projects": [
"p1"
]
}
}
[23][default:/src:0]# curl -H "api-token: $TOK" …
```
=> [A2-771] follow-up ProjectsAuthorized fix

components/ingest-service/backend/chef_action.go, components/ingest-service/backend/client.go, components/ingest-service/backend/elastic/actions.go, components/ingest-service/backend/elastic/mappings/actions.go, components/ingest-service/integration_test/project_update_actions_test.go, components/ingest-service/integration_test/suite_test.go
Adding a Chef Actions project tag updater function. This function takes the authz rule set and creates a painless script that is pushed to elasticsearch. This script walks through each Chef Action and updates their projects based on the rules. 
No demo until Chef actions can be ingested with projects. 
https://github.com/chef/automate/issues/62
This PR is the same work for updating nodes - https://github.com/chef/a2/pull/5301
=> Elasticsearch actions project update

components/ingest-service/backend/chef_action.go, components/ingest-service/backend/elastic/mappings/actions.go, components/ingest-service/pipeline/chef_action.go, components/ingest-service/pipeline/processor/action_project_tagger.go, components/ingest-service/pipeline/processor/action_project_tagger_test.go, components/ingest-service/server/chef.go
Adds RBAC project tagging to the Chef Action ingestion.
1. `build components/ingest-service`
1. `start_all_services`
1. `send_chef_action_example`
1. `curl $ELASTICSEARCH_URL/actions-*/_search | jq . | less`
1. Ensure 'some project name' is in the project array
issue - https://github.com/chef/automate/issues/62
similar PR but for CCRs - https://github.com/chef/a2/pull/5236
=> Action ingestion project tagging

components/event-gateway/integration_test/nats_auth_test.go, components/event-gateway/integration_test/suite_test.go, components/event-gateway/pkg/nats/authenticator.go
Signed-off-by: gpeers <gpeers@chef.io>
This PR furthers the EAS observability initiative by providing the permissions which allow the Habitat client to publish and subscribe to Automate messaging channels.
- Habitat can exchange heartbeat messages with Automate's streaming server, NATS
- Habitat can publish messages regarding Supervisor events to Automate
- Habitat can receive replies and acknowledgements from Automate
There are two ways to test this functionality: one is by exercising the related Automate integration tests in Habitat Studio, and the other is by running the Habitat Supervisor against Automate.
To exercise the Studio integration tests:
Grab the branch and open Studio
Build the `event-gateway` component
Start all services
The services should be on IAMv1; if they're not, run …
=> Enables habitat client permissions on required messaging channels

terraform/test-environments/modules/chef_automate_install/main.tf
This is the missing feature flag: https://github.com/chef/automate/blob/master/api/config/gateway/config_request.proto#L38
I tested this time the change manually on the server to verify it works and after running the installation module from terraform it worked just fine, you can even visualize data in the Applications Tabs:
=> Adds missing feature flag to enable EAS Dashboard

components/compliance-service/inspec-agent/runner/worker.go
Fixes https://github.com/chef/automate/issues/173
=> Don't pass AWS_SESSION_TOKEN when not set. Prevents root creds from working

.expeditor/config.yml
Improve the Expeditor logic to ensure that we're only building one set of packages at a time. 
* Unlock staging area if habitat build fails
* Unlock staging area after promotion if build succeeds
Signed-off-by: Tom Duffield <tom@chef.io>
=> Unlock staging area after hab builds are complete

components/applications-service/integration_test/global_test.go, components/applications-service/integration_test/service_groups_filters_test.go, components/applications-service/integration_test/service_groups_health_counts_test.go, components/applications-service/integration_test/service_groups_test.go, components/applications-service/pkg/params/pagination_test.go, components/applications-service/pkg/storage/postgres/service_groups.go, components/automate-ui/src/app/entities/service-groups/service-groups.model.ts, components/automate-ui/src/app/entities/service-groups/service-groups.reducer.ts, components/automate-ui/src/app/page-components/services-sidebar/services-sidebar.component.html, components/automate-ui/src/app/page-components/services-sidebar/services-sidebar.component.scss, components/automate-ui/src/app/page-components/services-sidebar/services-sidebar.component.ts, components/automate-ui/src/app/pages/service-groups/service-groups.component.html, components/automate-ui/src/app/pages/service-groups/service-groups.component.spec.ts, components/automate-ui/src/app/pages/service-groups/service-groups.component.ts
We had a number of issues with our paginators, this change is fixing them all so that the UI and Backend work as expected.
You can use all Paginators in the Applications Tab. That includes when using the health filters! 🎉 
Start the studio and build the applications-service. Then build and start the automate-ui in your preferred way. Finally, start all services.
```
$ hab studio enter
[1][default:/src:0]# export DEVPROXY_URL=localhost
[2][default:/src:0]# build components/automate-ui-devproxy
[3][default:/src:0]# build components/applications-service 
[4][default:/src:0]# start_automate_ui_background
[5][default:/src:0]# start_all_services
```
Populate the database (by running the helper method `applications_populate_database`) and navigate in your browser to …
=> Fix all paginators from the Applications Tab

terraform/test-environments/modules/chef_automate_install/templates/install_chef_automate_cli.sh.tpl
for our hardened test environment we need to use inspec, and the
latest version of the chef infra packages started shipping without the
inspec-bin gem. instead of relying on that being there, we should now
explicitly install inspec
=> [terraform] install inspec from omnitruck

components/automate-deployment/pkg/backup/runner.go
The backup runner was releasing the lock too early. It ended up
corrupting the backup status, as well as being able to deadlock backups
if they started one right after the other. The finishing backup with
close one of the channels the new backup created which caused the
deadlock
=> Fix backup deadlock

.bldr.toml
The part of the bldr.toml with these typos is not auto-generated.
They probably snuck in during the conversion from the .expeditor.yml.
=> [.bldr.toml] Fix typos in bldr config

.golangci.toml, components/applications-service/integration_test/service_groups_filters_test.go, components/applications-service/integration_test/service_groups_test.go, components/applications-service/integration_test/services_by_sg_test.go, components/applications-service/integration_test/services_test.go, components/applications-service/pkg/generator/runner.go, components/applications-service/pkg/generator/runner_stats.go, components/applications-service/pkg/params/filters_test.go, components/applications-service/pkg/server/server.go, components/applications-service/pkg/storage/postgres/service_internal_test.go, components/authz-service/engine/opa/opa_test.go, components/authz-service/engine/opa/opa_v2_test.go, components/authz-service/engine/opa/policy.bindata.go, components/authz-service/server/v1/server_test.go, components/authz-service/server/v2/migration_internal_test.go, components/authz-service/server/v2/policy_test.go, components/authz-service/server/v2/project_update_manager.go, components/authz-service/server/v2/project_update_manager_test.go, components/authz-service/storage/v2/postgres/postgres_test.go, components/event-gateway/pkg/nats/server.go, components/event-gateway/pkg/nats/tls_test.go
Invokes the simplification provided by `gofmt -s` documented at https://golang.org/cmd/gofmt/#hdr-The_simplify_command
=> Turn on code simplification checker in lint config.

components/automate-ui/src/app/page-components/client-runs-search-bar/client-runs-search-bar.component.ts
Fixed issue for the client_run page search bar shows empty suggestion if the user selects the policy group filter and policy name filter.
https://files.slack.com/files-pri/T03GRS9QS-FHCMEHV5J/download/policy_group_undefined_filter_bug.mov
https://github.com/chef/a2/issues/5420
=> fixed issue for the client run page search bar shows empty suggestion

components/automate-ui/e2e/integrations.e2e-spec.ts, components/automate-ui/src/app/entities/managers/manager.actions.ts, components/automate-ui/src/app/entities/managers/manager.effects.ts, components/automate-ui/src/app/entities/managers/manager.reducer.ts, components/automate-ui/src/app/entities/managers/manager.requests.ts, components/automate-ui/src/app/pages/integrations/detail/integrations-detail.component.html, components/automate-ui/src/app/pages/integrations/detail/integrations-detail.component.scss, components/automate-ui/src/app/pages/integrations/detail/integrations-detail.component.ts
The Automate nodemanager details page designs include a multi-select delete option.
the endpoint for the multi-select delete is: a2-url/api/v0/nodes/delete/ids, which takes a POST msg of form ["123..", "456.."]
Automate nodemanager details page has multi-select delete for nodes.
Signed-off-by: ?
=> automate-ui-150 Initial dev of multi-select delete

components/automate-workflow-web/package.json, components/automate-workflow-web/src/common/auth/session.js
To keep the session alive on A2 token get refreshed every minute. But for the workflow, there is no way to refresh to the session token.
- Include jwt-decode npm library.
- To make the session token consistent for both Automate 2 UI and workflow UI added refresh token logic to Workflow as well.
- Completed https://github.com/chef/a1/tree/rhass/fix-session-logout
* Install Automate 2.0
```
curl https://packages.chef.io/files/current/latest/chef-automate-cli/chef-automate_linux_amd64.zip | gunzip - > chef-automate && chmod +x chef-automate && \
./chef-automate deploy --channel dev --skip-preflight --accept-terms-and-mlsa --enable-chef-server --enable-workflow
```
* Login to Workflow.
* Stay on the dashboard page.
* After about two minutes the session will logout.
Signed-off-by: Vivek Singh …
=> [Workflow] Refresh session token for workflow UI

components/automate-ui/src/app/components/projects-dropdown/projects-dropdown.component.ts, components/automate-ui/src/app/entities/policies/policy.effects.ts, components/automate-ui/src/app/entities/projects/project.model.ts, components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.html, components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.scss, components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.ts, components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.spec.ts, components/automate-ui/src/app/page-components/projects-filter/projects-filter.component.html, components/automate-ui/src/app/services/projects-filter/projects-filter.actions.ts, components/automate-ui/src/app/services/projects-filter/projects-filter.effects.ts, components/automate-ui/src/app/services/projects-filter/projects-filter.reducer.spec.ts, components/automate-ui/src/app/services/projects-filter/projects-filter.reducer.ts, components/automate-ui/src/app/services/projects-filter/projects-filter.selectors.ts, components/automate-ui/src/app/services/projects-filter/projects-filter.service.ts, components/automate-ui/src/app/ui.component.ts
This PR implements remaining bits of the global projects filter.
Essentially the first thing I did was back up the reducer with a comprehensive set of unit tests. 
But I did that using what I call "Extreme TDD": write all the test names first to convert  requirements to code: 
See the full list here:
https://github.com/chef/automate/blob/046fa3f5af0f1a28420aa482423c46f2687217f9/components/automate-ui/src/app/services/projects-filter/projects-filter.reducer.spec.ts#L67
Once those requirements were confirmed, I then fleshed out all the tests.
This allowed me to easily determine what was left to do; the list below shows the failing tests, indicating that the component was not successfully doing what the test purports.
What made the creation of a comprehensive set of unit tests a very …
=> [A2-779] Projects filter refinement

components/nodemanager-service/pgdb/node-managers-process-node.go, components/nodemanager-service/pgdb/node_managers_process_node_integration_test.go, components/nodemanager-service/pgdb/nodes.go
The logic in this file (node-managers-process-node) was hard to follow, so this is my attempt to simplify it.
I also modified the logic that reads the node from the db to use a pointer for target config so that we don't have to worry about always having a value there.
Tests still pass without modification and the code is easier to read.
=> nodes: refactor process node handling to be simpler

components/authz-service/server/v2/policy.go, components/authz-service/server/v2/policy_refresher.go, components/authz-service/storage/v2/memstore/memstore.go, components/authz-service/storage/v2/memstore/policy_change_notifier.go, components/authz-service/storage/v2/postgres/policy_change_notifier.go, components/authz-service/storage/v2/postgres/postgres.go, components/authz-service/storage/v2/postgres/postgres_test.go, components/authz-service/storage/v2/storage.go
This PR uses postgres' LISTEN/NOTIFY feature to notify all authz nodes
to of changes to the policies. This makes the replication start almost
instantaneously, for sure faster that the 10 second anti entropy timer
we have right now.
=> Trigger replication notification of authz policies

.expeditor/publish-release-notes.sh
this change updates the messaging for the weekly release notes to
include the changes applied by the docs team to the most recent
release. this will prevent us from needing to make additional changes
each week
=> [release notes] update messaging w/ docs tweaks

components/compliance-service/inspec-agent/resolver/resolver.go, components/compliance-service/inspec-agent/resolver/resolver_test.go
We do not currently support detect jobs on ssm nodes.  This is functionality we would like to one day support, but it will require a bit more work.  
In one case we were erroneously allowing detect ssm jobs to go through, marking them as "reachable" without ever having tried to reach them, leading to a confusing experience for the user.
In another case we were (again) erroneously allowing detect ssm jobs to go through, but not detecting that the node was ssm, and trying to run a detect on the job, resulting in a cryptic error of type `train ssm plugin missing`.
So this work ensures we skip nodes if they meet two criteria:
- job type is detect
- node backend is ssm
ssm nodes skip detect jobs
build compliance
add aws-ec2 integration (credentialless)
expect to _not_ see nodes be reachable. …
=> do not run detect job if node has ssm backend

README.md
the Chef OSS Practices documentation refers to response time with the
term Response Time Maximum (RTM) instead of Service Level Agreement.
this change reflects that language.
link: https://github.com/chef/chef-oss-practices/blob/master/repo-management/repo-states.md#what-is-the-response-time-maximum
=> [readme] change SLA to RTM per OSS Practices

components/automate-ui/src/app/components/breadcrumb/breadcrumb.component.scss
Removes the link color from the breadcrumb links so they inherit the proper `<a>` tag styles.
Start up the UI and hover on any of the breadcrumb links to make sure they have a hover color.
https://github.com/chef/automate/issues/151
=> Remove color definition from breadcrumb links

components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.ts
The placeholder value for a control in the compliance reporting searchbar currently incorrectly suggests adding a control id. 
The value we actually need there is control title.
This pr updates the placeholder text to specify title instead of id.
Placeholder text for control display title
=> compliance reporting searchbar: placeholder val for control should be title

components/config-mgmt-service/backend/client.go, components/config-mgmt-service/backend/elastic/nodes.go, components/config-mgmt-service/backend/mock/mock.go, components/config-mgmt-service/backend/mock/mock_test.go, components/config-mgmt-service/grpcserver/nodes.go, components/config-mgmt-service/integration_test/nodes_test.go, components/config-mgmt-service/integration_test/runs_test.go, components/ingest-service/integration_test/suite_test.go
Add project filtering for the cfgmgmt.proto GetRuns RPC.
This PR does change the behavior of the GetRuns RPC in that before if the node from the passed in NodeID an error with "Invalid ID" was returned. Now, no error is returned and an empty run list is returned. 
=> Project filter GetRuns

components/automate-ui/e2e/admin.e2e-spec.ts, components/automate-ui/src/app/app-routing.module.ts, components/automate-ui/src/app/entities/users/user.actions.ts, components/automate-ui/src/app/entities/users/user.effects.ts, components/automate-ui/src/app/entities/users/user.model.ts, components/automate-ui/src/app/entities/users/user.reducer.spec.ts, components/automate-ui/src/app/entities/users/user.reducer.ts, components/automate-ui/src/app/entities/users/user.requests.ts, components/automate-ui/src/app/entities/users/user.selectors.ts, components/automate-ui/src/app/entities/users/userself.model.ts, components/automate-ui/src/app/page-components/user-table/user-table.component.html, components/automate-ui/src/app/page-components/user-team-membership-table/user-team-membership-table.component.html, components/automate-ui/src/app/page-components/user-team-membership-table/user-team-membership-table.component.spec.ts, components/automate-ui/src/app/page-components/user-team-membership-table/user-team-membership-table.component.ts, components/automate-ui/src/app/pages/policy/add-members/policy-add-members.component.ts, components/automate-ui/src/app/pages/team-details/team-details.component.spec.ts, components/automate-ui/src/app/pages/team-details/team-details.component.ts, components/automate-ui/src/app/pages/user-details/user-details.component.html, components/automate-ui/src/app/pages/user-details/user-details.component.spec.ts, components/automate-ui/src/app/pages/user-details/user-details.component.ts, components/automate-ui/src/app/pages/user-management/user-management.component.spec.ts, components/automate-ui/src/app/pages/user-management/user-management.component.ts
Replaces all of the UI's internal model of user with the V2 version and keeps all logic around the V1 vs V2 model encapsulated in `user.requests.ts`. Also updates NGRX store to query the V2 endpoints when the IAM V2 is enabled.
=> Update Automate UI to use users V2 model and V2 APIs when beta enabled

.buildkite/hooks/pre-command
We're seeing some weird behavior in habitat builds where we are building
more packages than required. This might be because we're using outdated
tags. This is a debug commit to see if force fetching the tags addresses
the issue.
Signed-off-by: Tom Duffield <tom@chef.io>
=> [releng] Fetch git tags in the pipeline

components/applications-service/pkg/storage/postgres/service_internal_test.go
The unit test in question (TestBuildWhereConstraintsFromFiltersMatrix) was, as @phiggins divined, implicitly depending on the order of a hash which of course means it will fail... unless it happens to succeed. This removes that fun element of non-determinism.
Test always passes.
=> Fix unit test bug in applications-service

components/authz-service/server/v2/authz.go, components/authz-service/server/v2/policy_refresher.go, components/automate-gateway/gateway/middleware/auth_interceptor_internal_test.go, components/automate-ui/src/app/services/http/http-client-auth.interceptor.spec.ts, components/automate-ui/src/app/services/http/http-client-auth.interceptor.ts, components/automate-ui/src/app/services/projects-filter/projects-filter.service.ts, lib/grpc/auth_context/auth_context.go
This sends selected projects along with every API request from the UI.
Projects appear in the HTTP request headers
Select projects from the global projects filter then navigate somewhere in the UI (having self-refresh is in the browser is a separate card).
=> [A2-784] UI http interceptor

components/automate-ui/src/app/app-routing.module.ts, components/automate-ui/src/app/page-components/projects-filter/projects-filter.component.spec.ts, components/automate-ui/src/app/services/projects-filter/projects-filter.service.ts
Before this change, the project filter would only take effect when you navigate to a different page within Automate. Now, when you change the filter, the current page will refresh itself to reflect the new set of projects, too.
Here I have project p2 selected, and nodes in that project display:
When I switch to project p4, which has no nodes, the list becomes empty:
Filters work throughout Automate.
Create some projects and assign them to some entities.
Exercise the global project filter on the appropriate page by selecting new projects and observe the list filtering change (almost) immediately when "Apply Changes" is selected.
=> [A2-783] Wire up  the projects filter "Apply Changes" button

components/automate-cli/cmd/chef-automate/dev.go, components/automate-cli/cmd/chef-automate/start_linux.go, components/automate-deployment/pkg/bootstrap/deployment_service_cmd.go, components/automate-deployment/pkg/gatherlogs/command.go, components/automate-deployment/pkg/server/startup_helpers.go, components/automate-deployment/pkg/target/hab_cmd.go, components/automate-deployment/pkg/target/hab_cmd_test.go, components/automate-deployment/pkg/target/local_target.go, components/automate-deployment/pkg/target/local_target_test.go
This is a first pass at making sure we are calling hab with
HAB_LICENSE=no-accept-persist
Because `hab sup run` also requires a license check currently we also
need to set this in our systemd unit file. Since that is inherited by
all processes in our process tree, we are probably OK if we missed a
hab call or two, but I would rather not depend on that. Further, right
now we don't correctly restart our systemd unit file in all cases, so
this likely won't take effect unless chef/automate#90 is merged first.
=> [deployment] Set HAB_LICENSE=accept-no-persist in a lot of places

components/config-mgmt-service/grpcserver/cfg_mgmt.go, components/config-mgmt-service/integration_test/stats_nodes_counts_test.go
Adding project filtering for the cfgmgmt.proto GetNodesCounts RPC.
=> Adding project filters for GetNodesCounts

components/config-mgmt-service/grpcserver/cfg_mgmt.go, components/config-mgmt-service/integration_test/node_run_test.go
Adding project filtering for the cfgmgmt.proto GetNodeRun RPC.
=> Adding project filters for GetNodeRun

components/compliance-service/integration_test/stats_server_read_summary_test.go, components/compliance-service/integration_test/stats_server_read_trend_test.go
In order to improve test readability and, in case of test failures, to more easily see failure origin, the stats summary tests are being separated into three distinct sections:
1 - reports
2 - nodes
3 - controls
=> break the summary tests into separate tests for nodes, reports and controls

components/authz-service/server/v2/policy.go, components/authz-service/server/v2/policy_refresher.go
Since project rules are stored in OPA alongside policies, we need to ensure that actions that update project rules will also trigger an OPA store update.
The mechanism for this is in place for policies and roles, and is (thanks to @jaym ) already wired for High Availability.
The few changes herein allow the as-yet-to-be-written API calls for project rule handling to tie in to the same mechanism.
Calls for project rules will be able to initiate OPA updates.
1. Add some code into a project handler function (say CreateProject) in authz-service/storage/v2/postgres/postgres.go:
```
err = p.notifyPolicyChange(ctx, tx)
if err != nil {
return nil, p.processError(err)
}
```
You will see that code fragment used for policy and role actions already in place.
2. Adjust the gating regex in …
=> [A2-808] OPA update for project rules

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profile/reporting-profile.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.html, components/automate-ui/src/app/pages/profile-details/profile-details.component.html
Based on feedback from @jonong1972 here: #254 (comment)
I have removed the icons that are in front of the labels.
1. Asset Store > Profiles / Available > SELECT A PROFILE. You will see the icons in the header in front of the labels.
2. Compliance > Profiles > SELECT A PROFILE
3. Compliance > EXPAND Report Metadata section
https://github.com/chef/automate/issues/307
=> added changes to remove compliance label icons

components/automate-deployment/a1-migration/install.rb, components/automate-deployment/basic-a1/install.rb
The most recent habitat now requires license acceptance.
See also: https://github.com/chef/automate/pull/207
=> [CI] Set HAB_LICENSE=accept-no-persist in nightly A1 tests

terraform/test-environments/modules/chef_automate_install/files/a2-sysctl.conf, terraform/test-environments/modules/chef_automate_install/main.tf
recently we've seen a fair share of failures from various fresh
install nodes in our test environments that aren't finding the
a2-sysctl.conf file in /tmp or even after applying them aren't
seeing the results in the system config when running the automate
preflight checks.
this change attempts to stabilize the writing of the chef automate
sysctl config by using the terraform file `content` feature rather
than loading the template from a local file. we've not seen similar
failures recently with the `content` feature, so this eliminates
one potential point of failure.
additionally, the file we write to /etc/sysctl.d has been renamed
from `a2-sysctl.conf` to `60-chef-automate.conf` to prevent any
ambiguity in the sorting or application of the sysctl config files.
Signed-off-by: Stephen …
=> [terraform] attempt to stabilize sysctl templates

components/compliance-service/api/stats/server/server.go, components/compliance-service/integration_test/stats_server_read_failures_test.go
Adding project filtering for the stats.proto ReadFailures RPC.
https://github.com/chef/automate/issues/67
=> project filtering for stats top failures

components/automate-ui/src/app/page-components/job-profiles-form/job-profiles-form.component.html, e2e/cypress/integration/compliance/01_ssh_scan_job.spec.js
It's hard to know if this will help much at all. 
i basically just added a `then(() => {` after the profile selection to ensure we don't try to click next until we've done that, since i found when viewing the failure videos that we were failing to select a profile and the unable to select next after
tests passed when run 4x consecutively against iamv2-inplace-upgrade -- it certainly won't hurt, so it's worth a try.
cypress tests are little less flaky
=> cypress: ensure we click next only after selecting a profile

e2e/cypress/integration/compliance/01_ssh_scan_job.spec.js
@sdelano noticed that when he slowed down the cypress run video, we were selecting the profiles before they loaded. 
this change introduces logic to wait for the profiles to load before clicking.
=> cypress: wait for profiles to load before selecting profiles for scan

components/automate-ui/e2e/event-feed-page.e2e-spec.ts
Fixing a flaky UI e2e test. When selecting the event feed dropdown filter the 'active' attribute should be added. The problem was that the test was checking before that 'active' attribute was added. So, the fix here is to wait until after the click and then check for the 'active' attribute for about a second. The other option was to add a sleep statement and sleeps cause other problems. 
I found a solution thanks to this website https://www.captechconsulting.com/blogs/keep-your-promises-making-the-jump-from-selenium-to-protractor
=> Fixing flaky UI e2e test

components/automate-ui/src/app/page-components/event-feed-guitar-strings/event-feed-guitar-strings.component.scss, components/automate-ui/src/app/page-components/event-feed-select/event-feed-select.component.scss, components/automate-ui/src/app/page-components/event-feed-table/event-feed-table.component.html, components/automate-ui/src/app/page-components/event-feed-table/event-feed-table.component.scss, components/chef-ui-library/src/molecules/chef-select/chef-select.scss
Some minor design tweaks to the event feed. Above screenshot shows the added border to the guitar strings graph, centered select menu title, and focus order (which skips the rows in the event feed table). 
https://chefio.atlassian.net/browse/UI-162
=> Design fixes for event feed

integration/services/ha_backend/htpasswd, integration/services/ha_backend/init, integration/services/ha_backend/setup.sh
This at least gets us back to exercising the current automate-ha-backend packages.
For elasticsearch auth, we are no longer using nginx for elasticsearch auth, and we are generating certs for use with automate-backend-elasticsearch. Also, we are using a recent hab in the backend containers to get the nested config feature added in 0.75.
Signed-off-by: Yvonne Lam <yvonne@chef.io>
=> [deployment] Unpin automate-ha-backend packages.

components/ingest-service/pipeline/processor/action_project_tagger_test.go
When using the goMock library the `Controller. Finish()` needs to be called when using `Times`, `MaxTimes`, or `MinTimes` functions.
=> Fixing the incorrect use of the gomock library

components/nodemanager-service/pgdb/node-managers-cloud.go, components/nodemanager-service/pgdb/node_managers_cloud_integration_test.go
I noticed some nodes were getting added in with no name. 
When we query the Azure node state we get the name of the instance, but when we query aws node state we do not.  So this logic just ensures that if we are adding a node b/c it is new to us, and it does not have a name defined, we use the id as the name, so there's some way to identify the node
nodes discovered via aws instance check have the id as their name
=> cloud integrations: if no name is defined for node when adding, use id

components/automate-ui/src/app/pages/notifications/notifications.component.html, components/automate-ui/src/app/pages/notifications/notifications.component.scss
Currently, when there are no notifications on the Notifications page we show an empty table, instead, we would like to follow the empty state pattern.
New changes screenshot
https://github.com/chef/automate/issues/302
=> new changes for the notifications page empty state

components/automate-ui/src/app/pages/api-token/list/api-token-list.component.html, components/automate-ui/src/app/pages/api-token/list/api-token-list.component.scss
Currently, when there are no api tokens on the API Tokens page we show an empty table, instead, we would like to follow the empty state pattern.
Existing UI
New changes
https://github.com/chef/automate/issues/303
=> added UI changes for API tokens page empty state

components/nodemanager-service/pgdb/filtering.go, components/nodemanager-service/pgdb/nodes.go, components/nodemanager-service/pgdb/nodes_integration_test.go
This work adds support for filtering by:
- last run and last scan end time ranges
- last run and last scan status
- last run and last scan penultimate status
able to filter by above defined criteria on the `api/v0/nodes` endpoint
https://github.com/chef/automate/issues/192
=> add filtering for last scan and last run data on nodes endpoint

components/config-mgmt-service/grpcserver/event_feed.go, components/config-mgmt-service/integration_test/event_counts_test.go, components/config-mgmt-service/integration_test/event_feed_test.go
Adding project filtering for the event_feed.proto GetEventTypeCounts RPC.
https://github.com/chef/automate/issues/69
=> Adding project filter for GetEventTypeCounts

components/config-mgmt-service/grpcserver/event_feed.go, components/config-mgmt-service/integration_test/event_task_counts_test.go
Adding project filtering for the event_feed.proto GetEventTaskCounts RPC.
https://github.com/chef/automate/issues/69
=> Adding project filter for GetEventTaskCounts

components/compliance-service/api/stats/server/server.go, components/compliance-service/integration_test/stats_server_read_profiles_test.go, components/compliance-service/integration_test/suite_test.go, components/compliance-service/reporting/relaxting/profiles.go, components/compliance-service/reporting/relaxting/stats.go
Adding project filtering for the stats.proto ReadProfiles RPC.
https://github.com/chef/automate/issues/67
=> project filtering for stats profiles

components/config-mgmt-service/grpcserver/event_feed.go, components/config-mgmt-service/integration_test/event_strings_test.go
Adding project filtering for the event_feed.proto GetEventStringBuckets RPC.
https://github.com/chef/automate/issues/69
=> Adding project filtering to GetEventStringBuckets

inspec/a2-api-integration/controls/iam_v2.rb
Fills in some missing base level integration testing for IAM V2 users endpoints.
=> [A2-655] Add user V2 API integration testing

components/authz-service/storage/postgres/datamigration/sql/06_v2_roles.up.sql
In a recent migration we used the convenient add-to-array syntax of PSQL:
```
actions = actions || '{ secrets:*:get, secrets:*:list }'
```
Unfortunately, that resulted in duplicates of those entries.
This PR remove the duplicates by resetting the list.
Above actions only appear once in the DB.
In the authz database:
```
SELECT * FROM iam_roles WHERE id = 'viewer';
```
From the command-line:
```
a2 -2 -o roles id viewer
```
or, in long-hand:
```
curl -sSkH "api-token: $TOK" "https://a2-dev.test/apis/iam/v2beta/roles" | \
jq -c '.roles[] | select (.id == "viewer")'
```
=> [A2-839] Remove duplicates from IAM roles table in DB

components/config-mgmt-service/grpcserver/node_export.go, components/config-mgmt-service/integration_test/node_export_test.go
Adding project filtering for the cfgmgmt.proto NodeExport RPCs.
=> Adding project filters for NodeExport

.expeditor/deploy.pipeline.yml
Adding a retry to the cypress tests. We are seeing some compliance tests are randomly failing from timeouts. The guess is that they might be timing out because the servers they are testing on are restarting their services. 
* https://buildkite.com/chef/chef-automate-master-deploy-dev/builds/216#b0f7117e-f8aa-4140-a902-4c29123523df
* https://buildkite.com/chef/chef-automate-master-deploy-dev/builds/217#_
=> Adding a retry to the cypress tests

components/chef-ui-library/src/atoms/chef-input/chef-input.scss, components/chef-ui-library/src/atoms/chef-loading-spinner/chef-loading-spinner.scss, components/chef-ui-library/src/atoms/chef-tooltip/chef-tooltip.scss, components/chef-ui-library/src/global/variables.css, components/chef-ui-library/src/molecules/chef-modal/chef-modal.scss, components/chef-ui-library/src/molecules/chef-status-filter-group/chef-status-filter-group.scss, components/chef-ui-library/src/molecules/chef-toggle/chef-toggle.scss
This commit https://github.com/chef/automate/commit/58632b31856c8fb1dca13f1b323b197cb0dc3d2a#diff-c206cc432a36a0164b93bff1503dc802L30 accidentally changed css variable nesting incorrectly in a few spots from this:
`var(--non-default, var(--default));`
To this improper format:
`var(--non-default), var(--default);`
I've fixed it in all the places I found in that commit.
=> Fix bug where css variable nesting was broken

e2e/cypress/support/commands.js
See if this helps the compliance cypress test to stop timing out. 
* https://buildkite.com/chef/chef-automate-master-deploy-dev/builds/216#b0f7117e-f8aa-4140-a902-4c29123523df
* https://buildkite.com/chef/chef-automate-master-deploy-dev/builds/217#22785621-f911-4b87-87b5-2a9ddc74ebbb
=> cypress: wait for introspect 'some' before moving on

components/compliance-service/api/tests/30_jobs_docker_spec.rb, components/nodemanager-service/pgdb/filtering.go, components/nodemanager-service/pgdb/nodes_integration_test.go
fixes https://github.com/chef/automate/issues/370
When creating a scan job, and filtering by tag values for the Automate node manager, we are currently unable to filter by multiple tags.
Able to filter nodes by multiple tags (Automate nodemanager)
rebuild nodemanager
create some nodes with different tags
create a scan job filtering by those tags
=> nodes: filtering by multiple tags

components/automate-ui/src/app/components/admin-sidebar/admin-sidebar.component.spec.ts, components/automate-ui/src/app/pages/settings-landing/settings-landing.component.ts
Takes care of a "TODO" in SettingsLanding component necessary to making routing fully correct once projects are enabled (with IAM v2.1).
When a user selects the Settings tab, the SettingsLanding component is responsible for taking the user to the first page he/she has permission to visit. The set of possible pages is defined by the admin sidebar, where the order of appearance determines the order of possible landing.
The first couple entries in the admin sidebar are Notifications and Node Integrations. Thus, if the user does not have permission for Notifications, it will be passed over. If the user does have permission for Node Integrations, that page will be visited.
Projects, as it happens, is the very last item in the list, so this change really only covers the case of a user having no …
=> Add projects to permission-based routing of Settings tab

Gopkg.lock, Gopkg.toml, vendor/google.golang.org/grpc/balancer/balancer.go, vendor/google.golang.org/grpc/balancer/base/balancer.go, vendor/google.golang.org/grpc/balancer_conn_wrappers.go, vendor/google.golang.org/grpc/clientconn.go, vendor/google.golang.org/grpc/credentials/credentials.go, vendor/google.golang.org/grpc/dialoptions.go, vendor/google.golang.org/grpc/encoding/encoding.go, vendor/google.golang.org/grpc/grpclog/grpclog.go, vendor/google.golang.org/grpc/internal/balancerload/load.go, vendor/google.golang.org/grpc/internal/envconfig/envconfig.go, vendor/google.golang.org/grpc/internal/syscall/syscall_nonlinux.go, vendor/google.golang.org/grpc/internal/transport/handler_server.go, vendor/google.golang.org/grpc/internal/transport/http2_client.go, vendor/google.golang.org/grpc/internal/transport/http2_server.go, vendor/google.golang.org/grpc/internal/transport/http_util.go, vendor/google.golang.org/grpc/internal/transport/transport.go, vendor/google.golang.org/grpc/picker_wrapper.go, vendor/google.golang.org/grpc/resolver/dns/dns_resolver.go, vendor/google.golang.org/grpc/resolver/passthrough/passthrough.go, vendor/google.golang.org/grpc/resolver/resolver.go, vendor/google.golang.org/grpc/resolver_conn_wrapper.go, vendor/google.golang.org/grpc/server.go, vendor/google.golang.org/grpc/service_config.go, vendor/google.golang.org/grpc/stats/stats.go, vendor/google.golang.org/grpc/stream.go, vendor/google.golang.org/grpc/trace.go, vendor/google.golang.org/grpc/version.go
Looks like we've missed a few releases -- here they are. The interesting release notes are:
- [v1.20.0](https://github.com/grpc/grpc-go/releases/tag/v1.20.0) as it has a few new features and bug fixes
- [v1.19.1](https://github.com/grpc/grpc-go/releases/tag/v1.19.1) has a bug fix for https://github.com/grpc/grpc-go/pull/2669, which could have happened to us as well.
For all the notes, see [the releases page](https://github.com/grpc/grpc-go/releases).
=> deps: bump go-grpc (1.19.0 -> 1.20.0)

components/automate-gateway/gateway/server.go, components/automate-gateway/integration/license_usage_nodes_test.go, components/automate-gateway/integration/nodes_test.go
This was carried over from some ancient grpc-gateway example code[1]; and
we're not exposing the GRPC API that way right now.
Using (*grpc.Server).ServeHTTP has some issues:
1. it's known to be slow, very slow[2]
2. it's seems to be not working with go-grpc >= 1.19 [3]
Furthermore, we're exposing the proper GRPC server (the native go-grpc
one) on a different port. If decide to (finally!) expose our GRPC API,
that's the thing we should expose.
So, since we don't need this multiplexing business, we shouldn't keep
the code around. This is the cleanup.
[1]: https://github.com/philips/grpc-gateway-example/
[2]: https://github.com/grpc/grpc-go/issues/586
[3]: https://github.com/soheilhy/cmux/issues/64#issuecomment-491999193
=> automate-gateway: cleanup GRPC/HTTP multiplexing cruft

components/automate-ui/src/app/pages/+compliance/+credentials/components/credentials-list.html, components/automate-ui/src/app/pages/+compliance/+credentials/components/credentials-list.scss
Currently, when there are no credentials on the Node Credentials page we show an empty table, instead, we would like to follow the empty state pattern.
New changes screenshot
fixes https://github.com/chef/automate/issues/301
=> added changes for node credentials page empty state

e2e/cypress/integration/02_global_filter.spec.js, e2e/cypress/support/commands.js
This test was hitting our precondition that only 6 projects exist-- when we attempted to create data for this test, it collided with 4 existing projects on the `inplace` box.
I don't see those projects being created programmatically in our code, so I'm assuming someone did it manually? 
JIC, we're now blowing away existing projects before running the test. This should be less troublesome when we remove the precondition.
=> Clean up data before test

components/automate-ui/src/app/components/admin-sidebar/admin-sidebar.component.html
Previously, if logged in as an "Editor" on 2.0, we were seeing the "Access Management" title in the sidebar without any subcategories.
With this change, an Editor does not see the title on 2.0. However, on 2.1, the editor can see both the title and "Projects" underneath. 
On 2.0:
On 2.1:
=> [A2-763] Hide "Access Management" on sidebar

components/automate-ui/src/app/pages/client-runs/client-runs.component.html
During usability studies at ChefConf 2019 participants repeatedly clicked on the Node State link on the Client Runs page expecting something to happen. This task removes that link if we add more items to the left-nav of that page in the future we can add it back.
After talking with @jonong1972 this task is only removing the link from the _Client Runs_ landing page, it will still be visible on node detail pages, we can revisit that in the future if necessary.
https://github.com/chef/automate/issues/397
=> remove node state link from client run page

components/automate-chef-io/content/docs/ldap.md
A few link issues in the LDAP docs came up during usability studies at Chef Conf, this fixes them.
=> Link fixes to LDAP docs

api/config/deployment/init_config.go
Automate CLI generates a self-signed SSL certificate for the front-end
load balancer if the user does not provide one.
Previously, this certificate had a hard-coded Serial of 1. This PR
changes it to a random serial to avoid errors in Firefox and
potentially other browsers.
=> [automate-cli] Generate unique serial for self-signed certs

components/automate-gateway/gateway/middleware/auth_interceptor.go
`AuthorizationBypasser` has been removed some time ago.
🧹
=> automate-gateway/middleware: cleanup comment

integration/helpers/testing.sh
The newest version of inspec requires that we accept the license.
=> [integration] Set CHEF_LICENSE when running inspec

components/automate-ui/src/app/entities/service-groups/service-groups.model.ts, components/automate-ui/src/app/page-components/services-sidebar/services-sidebar.component.html, components/automate-ui/src/app/page-components/services-sidebar/services-sidebar.component.scss, components/automate-ui/src/app/page-components/services-sidebar/services-sidebar.component.ts, components/automate-ui/src/app/pages/applications/applications.component.scss, components/automate-ui/src/app/pages/service-groups/service-groups.component.html, components/automate-ui/src/app/pages/service-groups/service-groups.component.scss, components/automate-ui/src/app/pages/service-groups/service-groups.component.ts
Reconfigures the *Applications* view to keep the sidebar permanently visible and to serialize its state to the URL.
- The right hand side bar is persistent. it is visible when you load the apps tab and cannot be hidden
- when I first load the applications tab, the first row on the left side table is selected and the right sidebar is populated with the right data for that row
- persist the state of which row on the left is selected in the URL
- persist the state of which filters are active on the right sidebar in the URL
- persist the state of the pages on the right sidebar in the URL
- when I select a new row on the left table, it resets the state of the sidebar things
- Nav to *Applications* view
- See sidebar remain permanently visible
- See sidebar filter/paging state serialized to URL …
=> Reconfigure EAS dashboard to make sidebar static

components/automate-ui/habitat/plan.sh
Currently master is broken to build Automate UI components.
When trying to build we are getting the following message:
```
> @angular/cli@8.0.0 postinstall /hab/cache/src/automate-ui-2.0.0/chef-ui-library/node_modules/@angular/cli
> node ./bin/postinstall/script.js
? Would you like to share anonymous usage data with the Angular Team at Google under
Google’s Privacy Policy at https://policies.google.com/privacy? (Y/N) 
```
Look at this PR: https://github.com/chef/automate/pull/435
We can build UI components in master.
Start the studio and build a UI package.
N/A
=> [FIX-PIPELINE] Disable Angular Analytics

integration/services/ha_backend/init, integration/services/ha_backend/setup.sh
Signed-off-by: Jeremy J. Miller <jm@chef.io>
This enables SSL mode for PostgreSQL in `ha_data_services` integration tests.
It is in preparation for when this PR lands:
https://github.com/chef/a2-ha-backend/pull/146
The work here has been validated by running:
`HAB_ORIGIN=jeremymv2 ./integration/run_test ./integration/tests/ha_data_services.sh` with custom pkg_idents for the following:
```
postgresql_pkg_ident="jeremymv2/automate-backend-postgresql/0.1.99/20190515201044"
pgleaderchk_pkg_ident="jeremymv2/automate-backend-pgleaderchk/0.1.99/20190515200841"
```
The above `postgresql_pkg_ident` and `pgleaderchk_pkg_ident` pkg_idents were built and validated in https://github.com/chef/a2-ha-backend/pull/146. When that PR merges, the ha_backend integration tests here will pick up the latest …
=> enabling SSL for PostgreSQL in ha_backend integration tests

components/automate-ui/src/app/pages/policy/add-members/policy-add-members.component.html, components/automate-ui/src/app/pages/policy/add-members/policy-add-members.component.ts, components/automate-ui/src/app/pages/policy/details/policy-details.component.html, components/automate-ui/src/app/pages/policy/details/policy-details.component.ts
* Fixed policy member add UI issue where it was incorrectly using local team names instead of IDs to add members to policy. This was resulting in being able to add "Viewers" to the viewers policy already containing the local team "viewers".
* Fixed policy membership table in policy details view to have the correct table column header of ID instead of Name.
* Fixed issue where you could get a console error if policy isn't loaded on time.
* Fixed TODO where we were populating links for local users and teams in policy details membership table.
Working links to local teams and users:
Capital V "Viewers" no longer showing up and properly showing local team IDs instead of Names:
=> Fix a few issues with the policy membership UI

components/automate-deployment/a1-migration/a1-migration-data-full/hooks/install, components/automate-deployment/a1-migration/a1-migration-data-full/plan.sh, components/automate-deployment/a1-migration/load-artifact
The nightly migration tests fail when habitat 0.81 is used to load the a1 data package, due to a workaround we had in place for an intermittent problem starting a habitat supervisor to load the data package so that the run hook could copy the a1 data to the proper locations. We no longer need the workaround because we can use a habitat install hook to put the a1 data in the desired locations.
TODO
=> Fix nightly migration tests

components/notifications-service/server/lib/data/migrations.ex, components/notifications-service/server/lib/data/migrator.ex
Auto upgrade of test and dev environment on acceptance channel showed the follow error
`
May 29 00:00:07 ip-172-18-2-200 hab[2799]: notifications-service.default(O): 00:00:07.343 module=GRPC.Adapter.Cowboy.Handler [error] ** (Protobuf.InvalidError) Notifications.ServiceNowAlert#critical_controls_only is invalid!
May 29 00:00:07 ip-172-18-2-200 hab[2799]: notifications-service.default(O):     (protobuf) lib/protobuf/validator.ex:5: Protobuf.Validator.validate!/1
May 29 00:00:07 ip-172-18-2-200 hab[2799]: notifications-service.default(O):     (protobuf) lib/protobuf/encoder.ex:9: Protobuf.Encoder.encode/2
May 29 00:00:07 ip-172-18-2-200 hab[2799]: notifications-service.default(O):     (protobuf) lib/protobuf/encoder.ex:49: anonymous fn/4 in Protobuf.Encoder.encode_field/3
May 29 00:00:07 …
=> Ensure upgrade sets existing notifications rules critical_controls_only column to false

terraform/test-environments/scenarios/single_local_iamv2_fresh_install.tf, terraform/test-environments/scenarios/single_local_iamv2p1_fresh_install.tf, terraform/test-environments/scenarios/single_local_iamv2p1_inplace_upgrade.tf
Previously I had repurposed the IAM v2 "fresh install" machine in the deployment farm to 2.1 (leaving the "inplace upgrade" at v2). But that "conservation of resources" led to more confusion than savings, so this PR reverts the change on the IAM v2 "fresh install" machine _and_ creates first-class siblings for v2.1, both fresh install and inplace upgrade.
New v2p1 machines are provisioned on each of the dev and acceptance dashboards.
=> Add proper IAMv2p1 machines to deployment farm

components/compliance-service/api/tests/02_nodes_spec.rb, components/compliance-service/generator/dump/audit_reports/2018-03-04_centos(3)-beta-nginx(p)-apache(s)-fake(s)-passed.json, components/compliance-service/reporting/relaxting/reports.go
Adds support for filtering compliance reporting nodes by inspec version 🎉 
_note: this does not include the ui changes needed to make this searchable from ui searchbar_
can filter compliance nodes by inspec version
send some inspec reports in with different inspec versions
use the api to filter by "inspec_version"
https://github.com/chef/automate/issues/431
=> compliance reporting nodes: filter by inspec version (backend)

components/compliance-service/api/tests/08_search_profiles_spec.rb
I wasn't clear on whether or not status filtering on compliance reporting profiles is supported or not, so i added a test. And it is!! 🎉 
Figured we should commit the test, so we know for sure that it's supported
test for filtering by status on compliance reporting profiles
https://github.com/chef/automate/issues/443
=> add a test for filtering by profile status

lib/workflow/backend/backend.go, lib/workflow/integration/schedule_test.go, lib/workflow/postgres/postgres.go, lib/workflow/postgres/sql_schema.go, lib/workflow/recurring_workflow_scheduler.go, lib/workflow/workflow.go, tools/workflow-scaffold/main.go
In a lot of places, we use name, which is ambiguous. This
changes those cases to specifically call out that it is
an instance name. schedule name has also been changed to
instance name as those are the same.
=> Be specific when using instance name

components/automate-ui/src/app/entities/service-groups/service-groups.model.ts, components/automate-ui/src/app/pages/service-groups/service-groups.component.html, components/automate-ui/src/app/pages/service-groups/service-groups.component.scss, components/automate-ui/src/app/pages/service-groups/service-groups.component.ts
- Add app and env columns to the table
- Resize existing columns to fit the new columns
- Sort on app and env
We can visualize the application and environment names of a group of services in the UI. Also, we should be able to sort on them.
_(this process depends on how you do UI development)_ 
- Build the Automate UI
- Start all services. `start_all_services`
- Populate the database. `applications_populate_database`
- Go to the Applications Tab and Test.
Closes Sub-Task: https://chefio.atlassian.net/browse/A2-829
Finishes Epic: https://chefio.atlassian.net/browse/A2-791
=> Add app and env to service-group table

components/automate-deployment/a1-migration/README.md, components/automate-deployment/a1-migration/load-artifact, scripts/nightly_migration.sh
The creds used to test a1 -> a2 migrations in the nightly need to match those generated when the a1 data package was built.
=> Specify creds for the a1 data package used by nightly migration tests

components/automate-gateway/handler/authz.go
Introspection changed some time back,
to return results for every endpoint,
even if all methods were false.
Supervisor log accurately reflects introspection results.
1. rebuild components/automate-gateway
2. Enable debug logging in gateway:
```
chef-automate debug set-log-level automate-gateway debug
```
3. Run `sl | grep Allowed` in hab studio to monitor the log.
4. Navigate around in the browser and observe log lines like these:
```
level=debug msg="Allowed paths: /iam/v2beta/policies[NONE]" ...
level=debug msg="Allowed paths: /retention/nodes/status[Get]" ...
level=debug msg="Allowed paths: /auth/users[Get,Post]" ...
```
=> Re-sync introspection logging with code operation

components/automate-ui/src/app/pages/client-runs/client-runs.component.spec.ts, components/automate-ui/src/app/pages/client-runs/client-runs.component.ts
Removing the 'Error' search bar type for client runs. 
This is being removed because of a problem with updating the elasticsearch 'node-state' mapping. 
https://github.com/chef/automate/pull/415
=> Removing Error search bar type

components/authz-service/server/v2/policy.go
🐛 be gone -- this removes extra work being done that isn't making any difference.
=> authz-service/policy: only update engine store when needed and only do it once

components/compliance-service/reporting/relaxting/util.go
For compliance, we were using one and sometimes many ElasticSearch connection per request.  This PR changes that to one ES connection per compliance-service instance.  This will result in far fewer sockets being managed which will, in turn, eliminate the "could not get elastic connection" errors were seeing.
=> Use the single ElasticSearch Connection object instead of one per request

components/automate-ui/src/app/pages/service-groups/service-groups.component.spec.ts, components/automate-ui/src/app/pages/service-groups/service-groups.component.ts
Set the default sorting field to `percent_ok` for the service-group table.
1) By default, sort by Group Health OK percentage number: from smallest to largest. (0-100) Within the same percentage number sort by level of criticality. When the sorting order is toggled, within the same percentage number, still sort by level of criticality. The level of criticality must always be Critical, Unknown and Warning in that order.
2) Switch the primary sorting criteria with the secondary. That is by default, sort by Level of criticality: The order is Critical, Unknown, Warning and Ok. Within the same level of criticality sort by “group health Ok percentage number”. The group health OK percentage number must always be ordered from 0-100.
- Start all services and build the UI. 
- Populate the …
=> Default sorting by percent_ok for service-groups table

.expeditor/verify_private.pipeline.yml, components/authz-service/engine/conformance/conformance_test.go, components/authz-service/engine/conformance/conformance_v2_test.go, components/authz-service/engine/engine.go, components/authz-service/engine/opa/opa.go, components/authz-service/engine/opa/opa_internal_test.go, components/authz-service/server/v2/policy.go, components/authz-service/server/v2/policy_refresher.go, components/authz-service/server/v2/policy_test.go, components/authz-service/server/v2/system_integration_test.go, components/authz-service/storage/v2/memstore/memstore.go, components/authz-service/storage/v2/postgres/policy_change_notifier.go, integration/tests/upgrade_reset_iam_v2.sh
`authz-service` uses OPA's partial eval feature to save time when authorizing requests by "pre-calculating" everything it can figure out without knowing the (variable) input data. However, that process itself takes time, any change to the relevant data (policies, roles, projects) requires a rebuild of that entire state.
When introducing IAM v2.1, we've taken a bit of a shortcut, and have rebuilt both the v2 and the v2.1 queries' partial eval state. This PR is about fixing that.
The need to fix it arises from the rebuild time, which is dependent on the data it's built with, increasing when the data increases (linearly? haven't checked) -- and it's become noticable, and annoying.
- This PR also expands the current upgrade-to-v2-and-reset-to-v1 tests by going some extra loops through v2.1 as …
=> [A2-798] split partial result update calls for v2 and v2.1

.studio/applications-service, components/applications-service/integration_test/global_test.go, components/applications-service/integration_test/ingestion_benchmark_test.go, components/applications-service/integration_test/service_groups_benchmark_test.go, components/applications-service/integration_test/services_benchmark_test.go
Currently, in the EAS Team, we are struggling a little bit to make decisions
in the backend, that is inside the `applications-service`.
We don't have a way to know the implications of adding or modifying code
and therefore, as engineers, we make lots of theories and deductions of
what "it could happen" based on assumptions.
An example is the following PR that is adding some extra complexity in
the query side of the micro-service. https://github.com/chef/automate/pull/490
This work is the first iteration to introduce benchmarks in our integration
tests to measure two main GRPC functions that we expose to consumers
(endpoints and the UI). These measurements will be recorded in our pipeline
so that we can understand how the system progress or degrades on code
changes.
After this change is …
=> Benchmarks for Applications Service

lib/workflow/postgres/sql_schema.go
Task executors were picking up tasks that didn't belong to them because
of the postgres function parameter being shadowed by a query with the
same column name
=> Fix incorrect shadowing in workflow sql

components/compliance-service/smokin/.kitchen.yml
quick tiny change. need this to be able to run our kitchen yml for test purposes
=> add license acceptance to kitchen yml used for testing

components/authz-service/habitat/hooks/run
We only want the current hart's contents there. Nothing else.
When we had merged two PRs both featuring a migration number 45, we
ended up with two 45_*.up.sql files in pkg.svc_static_path.
Fixing the file names resolved the issue for fresh installs, but our
inplace upgrades still failed -- the old, two, 45 files are still
present. To solve that, and not ever be hit by this `cp -r` bug again,
we'll ensure that svc_static_path never contains any old cruft by
clearing it out first.
(This is the comment I've put into the run hook.)
=> authz-service: plow over old cruft

components/automate-ui/src/app/entities/projects/project.model.ts, components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.scss, components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.ts, components/automate-ui/src/app/services/projects-filter/projects-filter.reducer.spec.ts, components/automate-ui/src/app/services/projects-filter/projects-filter.reducer.ts
Small fry that came up in ChefConf user testing. Please see the individual commit messages.
That said, I'm no UI expert, please review with that in mind 😄 
- deployinate, use `automate-ui-devproxy` or `automate-ui`, use `grpcurl` to trigger different backend conditions:
- create a project:
```
[34][default:/src:0]# chef-automate dev grpcurl authz-service -- -d '{"id": "foo", "name": "foo"}'  chef.automate.domain.authz.v2.Projects/CreateProject
{
"project": {
"name": "foo",
"id": "foo",
"type": "CUSTOM",
"projects": [
"foo"
]
}
}
```
- delete it:
```
[33][default:/src:0]# chef-automate dev grpcurl authz-service -- -d '{"id": "foo"}'  chef.automate.domain.authz.v2.Projects/DeleteProject
{
}
```
- [A2-855](https://chefio.atlassian.net/browse/A2-855)
=> [A2-855] projects filter UI cleanup

components/authz-service/server/v2/policy.go, components/authz-service/server/v2/policy_refresher.go, components/authz-service/server/v2/policy_test.go, components/authz-service/storage/v2/postgres/postgres.go
Since there's two different stores for these now, it matters in a
multi-node setting which version the server is operating under. Since
the version is derived from the migration status, which in turn is
stored in the database, we make a change to that a "policy change
event": any instance that is connected to the database, but hasn't been
the one processing the migration GRPC call, will be informed that it
needs to update its store.
Figuring out which store to update is done by querying the database for
its migration status; it no longer is retrieved from local state of the
server instance.
Note: this does not notify other nodes in unhappy paths, since a failure
to migrate v1 policies should prohibit a switch to v2 (or v2.1).
Stuff still works single-node. -- This is a _best effort_ fix …
=> [A2-798] fix v2.1 upgrade issue for multi-node settings

components/chef-ui-library/src/atoms/chef-progress-bar/chef-progress-bar.e2e.tsx, components/chef-ui-library/src/atoms/chef-progress-bar/chef-progress-bar.scss, components/chef-ui-library/src/atoms/chef-progress-bar/chef-progress-bar.tsx
Adds a progress-bar component to the ui-library. This commit was pulled from this WIP branch that utilizes this progress-bar: https://github.com/chef/automate/pull/511
https://github.com/chef/automate/pull/511
=> Add `chef-progress-bar` component

components/compliance-service/api/tests/03_deep_reports_spec.rb, components/compliance-service/api/tests/03_reports_spec.rb, components/compliance-service/api/tests/08_deep_search_profiles_spec.rb
When we changed our inspec version in one of our test json files, in order to test inspec version filtering, we broke a few tests.  This pr gets them back in line.
=> fix some failing tests that occurred after we started supporting inspec ver filtering

components/authz-service/storage/postgres/datamigration/sql/Makefile, components/authz-service/storage/postgres/migration/sql/Makefile
This is @phiggins idea -- it's _very_ unlikely that two PRs ever touch
the same migration again.
To create a new one, use `make new`. You can also pass a name:
$ cd components/authz-service/storage/postgres/migration/sql/
$ make new
=> 20190607130445_TODO.up.sql
$ make new name=do_foo_things
=> 20190607130452_do_foo_things.up.sql
Of course, it's possible that the migrations of two different PRs do not
commute (i.e., A;B is different from B;A), but that situation has always
been a problem.
The library we use ends up [calling `sort.Sort` on the versions](https://github.com/mattes/migrate/blob/4768a648fbd9e04389a73a21139d14a4ccb1a61a/source/migration.go#L73), casted to integers. So, this is fine.
=> authz-service/{datamigrations,migrations}: add Makefile for timestamp versions

components/automate-cli/cmd/chef-automate/version.go, components/automate-ui/e2e/app.e2e-spec.ts, components/automate-ui/src/app/page-components/profile/profile.component.html, components/automate-ui/src/app/page-components/profile/profile.component.scss, components/automate-ui/src/app/page-components/profile/profile.component.spec.ts, inspec/a2-deploy-integration/controls/base.rb
As noted in https://github.com/chef/automate/issues/432, we have made the decision to include the "major" Automate version (2) where the build number is listed for the Automate product.
This change makes those modifications for the user menu in the Automate ui and the automate cli.
Version: 2 is displayed above build number for the user menu and cli
rebuild ui & cli
chef-automate version
check user menu in ui
=> modify automate cli and ui user menu to include major automate version

components/automate-deployment/pkg/backup/spec.go, components/automate-deployment/pkg/backup/spec_test.go, components/config-mgmt-service/integration_test/nodes_test.go, components/config-mgmt-service/integration_test/suggestions_test.go, components/ingest-service/backend/client.go, components/ingest-service/backend/elastic/elastic.go, components/ingest-service/backend/elastic/mappings/node_state.go, components/ingest-service/grpc/grpc.go, components/ingest-service/migration/a1_migration.go, components/ingest-service/migration/migration.go, inspec/a2-upgrade-from-v1-integration/controls/elastic.rb
This change performs a migration on the node-state index to allow the projects field to be indexed. 
When the projects field was added it had two properties ('index=false' and 'doc_values=false') unintentionally added that prevented it from being index or queriable. 
```
"projects": {
"type": "keyword",
"index": false,
"doc_values": false
},
```
Later an update was made to remove those fields from the node-state mapping to make the 'projects' field look like below. 
```
"projects": {
"type": "keyword"
},
```
When the ingest-service was updated with this change the below error was logged and the mapping was not update. The ingest-service started with no problems. 
```
Error creating index node-state-5 with error: elastic: Error 400 (Bad Request): Mapper for [projects] conflicts with …
```
=> Migration node-state index to allow projects to be indexed

lib/workflow/postgres/postgres.go
Relying on cancel closes the underlying connection. If we
explicitly rollback first, we can use the connection.
=> Rollback dequeue task on error

components/automate-chef-io/content/docs/system-requirements.md
Elasticsearch by default expects at least 65535 potential open files to be available from the kernel through the shell process it starts up in.
=> Avoid ES errors with default shell settings

lib/workflow/backend/backend.go, lib/workflow/integration/counting_workflow_test.go, lib/workflow/postgres/postgres.go, lib/workflow/postgres/sql_schema.go, lib/workflow/workflow.go
The nomenclature here needs some discussion. Perhaps payload/result is the wrong thing and we could just call it state. Then you wouldn't need to check if you're running or not to determine if you should grab the payload or the result.
=> Add ability to complete workflow instance with a result

components/automate-deployment/a1-migration/create_artifact.sh, components/automate-deployment/a1-migration/run_upgrade_from_a1.sh
We install the latest habitat in that test. These changes should fix up
compatibility issues habitat-sh/habitat#6597, which reverts the behavior
of `hab pkg install -b` to what it used to be. For future compatibility,
I've used the `--binlink-dir` flag, which seems to be the new way of
doing things
=> Use binlink-dir in a1 migration nightly tests

terraform/test-environments/modules/chef_automate_install/main.tf
We currently have 8GB of ram on our terraform-managed CI machines.
Let's bump the ES heap size to 1/4th of that. 1gb isn't really an
appropriate default for long-lived installations.
=> Increase CI ES heap size to 2gb

components/ingest-service/backend/client.go, components/ingest-service/backend/elastic/elastic.go, components/ingest-service/migration/migration.go
The migration of the node-state index is timing out on the a2-local-inplace-upgrade-dev.cd.chef.co 
server. This could be timing out because the migration is leaving the connection open while the reindex happens. This PR is performing the reindex async. 
Below is the error seen on the a2-local-inplace-upgrade-dev.cd.chef.co  server:
`Jun 07 19:25:12 a2-local-inplace-upgrade-dev.cd.chef.co hab[6080]: ingest-service.default(O): time="2019-06-07T19:25:12Z" level=fatal msg="Unable to reindex node-state to latest" error="elastic: Error 504 (Gateway Timeout)" type=migration`
This code has been tested locally, but I can not get the migration to take as long as it does on the `a2-local-inplace-upgrade-dev.cd.chef.co` server.
=> Switching ingest migrations to work async

components/automate-ui/src/app/pages/client-runs/client-runs.component.spec.ts, components/automate-ui/src/app/pages/client-runs/client-runs.component.ts
Adding back the error message searching/filtering to the Client Runs page. 
This feature was removed with this PR https://github.com/chef/automate/pull/474 because an Elasticsearch migration had to be performed to fix an existing problem. 
https://github.com/chef/automate/pull/415 is the original PR that added this feature. 
Use the repro steps from this PR https://github.com/chef/automate/pull/415
Original PR - https://github.com/chef/automate/pull/415
PR that removed the feature - https://github.com/chef/automate/pull/474
=> Adding error searching to client runs

components/chef-ui-library/src/molecules/chef-status-filter-group/chef-status-filter-group.scss, components/chef-ui-library/src/molecules/chef-status-filter-group/chef-status-filter-group.tsx
A very quick change to remove the grey outline of the health status filter on hover.
Hover state style update: Remove the grey outlines for the background container for the five filters (total, critical, warning, OK and unknown) above the table and in the sidebar.
Build and start the chef-ui-library.
Then, navigate to http://localhost:3334/molecules/chef-status-filter-group
Jira: https://chefio.atlassian.net/browse/A2-842
Closes https://github.com/chef/automate/issues/472
=> Remove health status filter grey outlines on hover

.expeditor/buildkite/cypress.sh, e2e/cypress/integration/02_global_filter.spec.js, e2e/cypress/support/commands.js
These currently fail when run against an IAM v2.1 env. Looks like they hadn't been adapted when we've merged #546.
You can verify these by running
env CYPRESS_BASE_URL=https://a2-iamv2p1-local-fresh-install-dev.cd.chef.co npm run cypress:open
in the chef vpn (sorry non-chef employees...), and selecting the global filter specs.
If you run them with
CYPRESS_BASE_URL=https://a2-iamv2p1-local-inplace-upgrade-dev.cd.chef.co
you can watch them fail because of the issue fixes in #561.
Note: this will fail if merged _after_ #561.
=> e2e: cypress all the envs

inspec/a2-hardened-security/controls/cis-rhel7-level1-server.rb
We aren't yet sure what changed such that these are failing right now.
The failures are:
```
×  xccdf_org.cisecurity.benchmarks_rule_1.2.3_Ensure_GPG_keys_are_configured: Ensure GPG keys are configured
×  ["gpg-pubkey-352c64e5-52ae6884"] should eq []
expected: []
got: ["gpg-pubkey-352c64e5-52ae6884"]
(compared using ==)
```
```
×  File /home/ec2-user/.pki should be owned by "ec2-user"
expected `File /home/ec2-user/.pki.owned_by?("ec2-user")` to return true, got false
```
=> [CI] Skip 2 controls that are now failing in our hardened environment

components/authz-service/engine/conformance/conformance_v2_test.go, components/authz-service/engine/engine.go, components/authz-service/engine/opa/opa.go, components/authz-service/server/v2/authz.go, components/authz-service/server/v2/authz_test.go, inspec/a2-iam-v2p1-only-integration/controls/introspection.rb, integration/tests/iam_v2.sh, integration/tests/iam_v2_only.sh, integration/tests/iam_v2p1_only.sh
Amongst the ad-hoc OPA queries that were all assigned to specific stores in opa.go,
there was one that was assigned to v2 when it is actually used both by v2 and v2.1.
Added the mechanism to provide the version so it can appropriately version-adjust on the OPA call.
We no longer see the **absence** of the header bar:
This is the set of steps that manifested the issue:
1. Start fresh hab studio and start the world.
2. Upgrade to 2.1: `chef-automate iam upgrade-to-v2 --beta2.1`
3. Login as admin and observe that all tabs are present across the top nav bar.
4. Restart authz-service: `pkill authz-service`
5. Refresh browser. 
Before the fix, all introspection calls now return "deny" so the top nav bar was essentially absent.
Now it is correctly populated.
=> Add neglected version-adjustment for OPA call

.studio/common
Kudos to @phiggins for spotting this when reading code.
=> [studio] build_all should actually skip non-OSS software

scripts/count_retries
We just cannot let this happen. Also freeing two `cat`s in the process.
=> ci: don't wrap emoji jobnames in backticks

.buildkite/hooks/pre-command
This has proven to be buggy, and misleading. When force-pushing a PR
branch, the merge head doesn't get updated reliably, and the CI run thus
builds the wrong thing, old code.
Additionally, the BK UI will claim it was building the correct commit,
which confuses even more.
~This adds an info message with the commit being built, for extra
visibility.~ Now, we're attempting to non-interactively rebase onto what's `origin/master` at _build time_; and warn if it fails. If it fails, we'll run the build job with the PR's HEAD.
If everything's fine rebasing, it'll show
If not, you'll see
*however*, your build will still be executed ([see this for a test run where the rebase fails](https://buildkite.com/chef/chef-automate-master-verify-private/builds/2054))
=> ci: don't build the merge ref, try to rebase ourselves

components/automate-chef-io/content/docs/iam-v2-guide.md, components/automate-chef-io/content/docs/iam-v2-overview.md, components/automate-cli/cmd/chef-automate/iam.go
After exposing this flag to the end user, we also needed to update docs.
I have done this work in accord with the ticket, but I wonder if it would make more sense (at least, eventually) to make skipping policy migration the default behavior (as that is what we recommend) and provide a flag to automatically migrate. 🤷‍♀
=> [A2-861] Expose skip policy migration option to end user

components/automate-elasticsearch/habitat/config/init_ca
ES uses the root cert to talk to the backup gateway. If the root
certificate for the services is regenerated, ES was not reimporting it
and backups were failing. This fixes that.
Fixes #568
I didn't try to delete and import the cert because my bash isn't great and delete returns an error if the alias does not exist and you try to delete it meaning you have to handle errors and because it's java all error codes are probably just `1`
=> Reimport root certificate when restarting Elasticsearch

components/session-service/Makefile, components/session-service/server/server.go, components/session-service/server/server_test.go
Before, the following could happen:
- tab A: get logged out, sent to dex -- relay state 1
- tab B: get logged out, sent to dex -- relay state 2, overwrites relay
state 1
- login in tab A, be sent back to session-service
- relay state 2 != 1, error out
Now, we don't bind a single relay state to the session (which would be
overwritten when a second logout occours), but multiple relay states.
To achieve this, we don't store a string key in the session (with key
"relay_state"), but multiple booleans, with key
"relay_state_<RELAY_STATE>". Since we only need to check whether a state
we get back from dex matches a known relay state, and never need to
retrieve all relay states, that works.
ℹ️Use `chef-automate dev psql chef_session_service -- -c 'delete from sessions'` to kill your session for …
=> session-service: allow for multiple relay states

.buildkite/hooks/pre-command, scripts/count_retries
- `buildkite-agent annotate` for retries: take annotation from pos args, not stdin
- rebase PR: ignore post-merge CI runs (i.e. builds of `master`)
=> ci: misc small buildkite hooks cleanups

components/authz-service/config/config_mgmt.go, components/authz-service/config/config_mgmt_test.go
Has this ever happened to you after running the tests of authz-service`?
```
$ git status
On branch master
Your branch is up to date with 'origin/master'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
components/authz-service/config/.tmp..
nothing added to commit but untracked files present (use "git add" to track)
```
With this PR, it shouldn't happen again 😃
=> cleanup tmp file from running authz service tests

lib/Makefile, lib/workflow/backend/backend.go, lib/workflow/integration/workflow_error_test.go, lib/workflow/postgres/postgres.go, lib/workflow/postgres/sql_schema.go, lib/workflow/workflow.go
This allows you do to:
```
return w.Fail(err)
```
inside a workflow executor callback, which is useful because 
of all the error checking that has to happen around the serialization
and deserialization of the payload and task results.
While here, I cleaned up some SQL that was using various in_val tables
that I don't think are necessary.
=>  Allow workflows to indicate failure 

scripts/a2_collections
1. Rename `a2` bash helper to `authQuery`.
2. Add new `authLoad` helper.
The latter makes it very convenient to copy resources from one machine to another for diagnostic purposes.
You can, for example, now do this on your development machine to copy all tokens from an acceptance machine to your own:
```
$ export TARGET_HOST=https://a2-local-inplace-upgrade-acceptance.cd.chef.co
$ export TOK="r7sDLTujkijLLhwe5L4xyRPkCXY="
$ authQuery --one-line tokens > captures/tokens.out
$ export TARGET_HOST=https://a2-dev.test
$ export TOK="r7sDLTujkijLLhwe5L4xyRPkCXY="
$ authLoad tokens captures/tokens.out
```
This will work for IAM v1 tokens, team, users, and policies.
Will likely work for most IAM v2 resources, but have not needed to try those yet.
See above.
=> Add new bash helper for a2 auth resources

scripts/install_golang, scripts/install_grpcurl, scripts/install_inspec
These scripts are used by the compliance tests to install the correct
versions of dependencies. The hab licensing changes require us to
accept the license.
=> Set HAB_LICENSE in various CI scripts

components/authz-service/README.md, components/authz-service/server/v2/migration.go, components/authz-service/server/v2/migration_internal_test.go, integration/tests/iam_v2.sh
- Three ✅ above.
- `rebuild components/authz-service`
- `chef-automate iam reset-to-v1`
- `export TOK=$(chef-automate admin-token)`
- create a custom `service_groups` v1 policy:
```
curl -kH "api-token: $TOK" https://localhost/api/v0/auth/policies -d '{"action":"*","subjects" ["user:*"],"resource":"service_groups","effect":"allow"}'
```
- upgrade to v2:
```
Upgrading to IAM v2
Migrating v1 policies...
Creating default teams Editors and Viewers...
Skipped: Editors team already exists
Skipped: Viewers team already exists
Migrating existing teams...
Success: Enabled IAM v2
```
☝️ notice that there's none of these errors anymore:
```
Skipped policies:
convert v1 policy "aee14d59-da0b-4974-ba6d-1a018b024874"
unknown "well-known" policy
convert v1 policy "9afdf13e-74ab-4797-8a31-32ece05938b4" …
```
=> [A2-882] authz-service: fix v1 to v2 policy migration issues with applications

api/config/elasticsearch/config_request.go
While we auto-calculate HeapSize during configuration generation on
initial installation, this doesn't apply to existing installs.
Previously, we were hesitant to do this as it will result in an
elasticsearch restart.
=> [elasticsearch] Update default HeapSize on upgrade

components/authz-service/server/v2/project.go, components/authz-service/storage/postgres/migration/sql/47_staged_rules_tables.up.sql, components/authz-service/storage/postgres/migration/sql/README.md, components/authz-service/storage/v2/memstore/memstore.go, components/authz-service/storage/v2/postgres/postgres.go, components/authz-service/storage/v2/postgres/postgres_test.go, components/authz-service/storage/v2/rule.go, components/authz-service/storage/v2/storage.go
Before kicking off a long-running re-indexing of tagged resources, users need to be able to stage changes.  This table is the starting point (along with the function `CreateRule` and `GetStagedOrAppliedRule` for POC). 
NOTE:
Technically, we don't want to trigger a reindex if only the name of a rule/project has changed. We've included it anyway to reduce complexity on this first go, but we will eventually want to handle those differently.
=> [A2-811] Table to stage rule changes

inspec/a2-api-integration/controls/iam_v2.rb
The Rules API is under 🚧 and some of its behavior is changing. Commenting out these tests until their new behavior is finalized
=> inspec: temporarily comment out flaky Rule API tests

components/config-mgmt-service/grpcserver/node_export.go
Adding the error message to the CSV and JSON client runs export. An error message will be included in the export if the node is in a failed state
1. `build components/config-mgmt-service && start_all_services`
1. `send_chef_run_failure_example`
1. Open https://a2-dev.test/client-runs
1. Export the node list as CSV
1. Ensure there is a column labeled 'Error Message' with a message for the exported node
1. Export the node list as JSON
1. Ensure there is a field 'error_message' with a message. 
https://github.com/chef/automate/issues/447
=> Adding error message to csv export

components/compliance-service/integration_test/reporting_server_list_nodes_test.go, components/compliance-service/reporting/relaxting/reports.go
Adding case insensitive wildcard searching/filtering when using the compliance reporting search bar.
1. `build components/compliance-service && start_all_services`
1. Ingest a few InSpec reports with different nodes. Vary the data for all the searchable fields SourceFQDN, ChefTags, Environment, NodeName, OrganizationName, Platform, PolicyGroup, PolicyName, Recipes, Roles, Profiles Titles, and Controls titles. Use the `send_inspec_example` and the `components/compliance-service/ingest/examples/compliance-success-tiny-report.json` file to create the nodes. Create upper and lower case values. 
1. Open the UI https://a2-dev.test/compliance/reports/overview
1. Test each of the search bar types with the '?' and '*' characters.  
https://github.com/chef/automate/issues/325
=> Case Insensitive wildcard searching

components/automate-chef-io/content/docs/api-tokens.md, components/automate-chef-io/content/docs/authorization-overview.md, components/automate-chef-io/content/docs/configuration.md, components/automate-chef-io/content/docs/iam-v2-api-reference.md, components/automate-chef-io/content/docs/teams.md, components/automate-chef-io/content/docs/users.md, components/automate-gateway/gateway/server.go, components/automate-gateway/gateway/services.go, inspec/a2-api-integration/controls/iam_v2.rb
Now, if you query, for example, either one of
https://a2-dev.test/apis/iam/v2beta/policies?pretty
https://a2-dev.test/apis/iam/v2beta/policies?pretty=1
https://a2-dev.test/apis/iam/v2beta/policies?pretty=true
https://a2-dev.test/apis/iam/v2beta/policies?pretty=please
you'll get a pretty-printed JSON response. 
Any handcrafted handlers are _not_ getting this, only the handlers we get from grpc-gateway.
=> automate-gateway: add ?pretty parameter to every grpc-gateway method

components/automate-gateway/gateway/services.go, components/compliance-service/api/reporting/server/server.go, components/compliance-service/api/tests/export_test.go, components/compliance-service/integration_test/reporting_server_export_test.go
As users of the compliance json export endpoint, we need to have properly formed json returned in the response of the request.  
Currently, the response is designed to be made up of a json array of json objects.  The problem is that this array is not surrounded by open/close square braces, and the objects within it are not comma separated; both of which are required in order for a json array to be considered well-formed.
This PR addresses both shortcomings and as a result, the compliance json export is now well-formed.
The json that comes back is well formed.
=> make json well-formed for compliance export

.studio/applications-service
Updates the `applications_populate_database` studio function to trigger a few more UI behaviors we have added since it was first written:
* Create enough service groups so that pagination happens
* Create service groups with no "application," this shows up with a special badge
* Create service groups with no "environment," this shows up with a special badge
* Create service groups with no "channel," this shows up with a special badge (on the right side detail panel)
1. `start_all_services` in the studio
2. `source .studiorc` to load the new studio helper code
3. `applications_populate_database`
4. Visit the UI at a2-dev.test, you should have more than 25 service groups and service groups that are missing application, environment, and channel (different service group for each case)
=> Cover more ui cases with studio helper

components/automate-ui/package-lock.json, components/automate-ui/package.json, components/automate-ui/src/app/services/rules/rules.service.ts, components/automate-ui/tslint.json, components/chef-ui-library/package-lock.json, components/chef-ui-library/package.json, components/release-mgmt-dashboard/tslint.json
Starting to think about an Angular upgrade (Angular 8 just came out and we are still on Angular 6).
Ran into various issues when attempting to upgrade that need more investigation, but this PR is at least a start to tidy up a couple minor things.
Upon upgrading `tslint` a few new linting errors appeared, and this PR resolves them.
1. Error: _Tried to lint *file*.js but found no valid, enabled rules for this file type and file path in the resolved configuration._ The fix for that is to add a `jsRules` section to the tslint.json file, as described here: https://github.com/palantir/tslint/issues/3735
2. The recommended content of the `jsRule` section from that suggested fix--to turn on the "no empty blocks" rule caused, a few instances of, yep (`block is empty`). It turns out that the …
=> Minor UI package maintenance

scripts/a2_collections
This wraps up the final planned segment of the work started in PR #610 (Add new bash helper for a2 auth resources) by adding the final of a triumvirate of functions useful for exercising an A2 system.
This introduces `authGen` that, unlike `authLoad` from the last PR that requires enumerated data to populate a system, generates data on the fly, thus allowing creating arbitrarily large sets of resources.
This supports both creating and deleting such resources. Here's a simple example:
```
Create 500 policies starting with a seed of 101:
$ authGen policies create 500 101
Those policies need these members:
$ authGen tokens create 500 101
Now, just for illustration, delete the last 100 of those 500 policies:
$ authGen policies delete 100 501
```
See above.
NA
PR #610
=> One more bash helper to generate auth resources from scratch

components/automate-ui/src/app/pages/service-groups/service-groups.component.html, components/automate-ui/src/app/pages/service-groups/service-groups.component.spec.ts, components/automate-ui/src/app/pages/service-groups/service-groups.component.ts
If you navigate to `/applications` and have 26+ service groups, you don't see the pagination controls. If you change the status filters, then the pagination controls will appear.
**EXTRA:** Found out that we didn't write tests for the new default sorting field `percent_ok`, so I added them here.
Pagination controls should work on the first load of the Applications Tab page.
1) Run automate-ui unit tests!
2) Build and start the automate-ui and all automate services.
3) Ingest a few services messages by using the studio helper:
```
[3][default:/src:0]# for i in a b c d e f g h i j k l m n o p q r s t u v w x y z; do
applications_publish_supervisor_message --sup-id $(uuidgen) --name $i
done
```
The UI should show the paginator at the end of the page like this:
Jira: …
=> [BugFix] Load pagination controls on component initialization

components/authz-service/storage/postgres/migration/sql/48_remove_deleted_staged_conditions_column.up.sql, components/authz-service/storage/postgres/migration/sql/README.md, components/authz-service/storage/v2/postgres/postgres.go, components/authz-service/storage/v2/postgres/postgres_test.go
Signed-off-by: Tyler Cloke <tylercloke@gmail.com>
Update DeleteRule to work in the staged world. Deleted the staged condition `deleted` column since it was not necessary.
```
[9][default:/src:0]# chef-automate dev psql chef_authz_service
psql (9.6.11)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.
chef_authz_service=# select * from iam_project_rules;
db_id |  id  | project_id |   name    | type
-------+------+------------+-----------+------
2 | test | prod       | test name | node
(1 row)
chef_authz_service=# select * from iam_staged_project_rules;
db_id |  id  | project_id |   name    | type | deleted
-------+------+------------+-----------+------+---------
2 | test | prod       | test name | node | t
(1 row)
``` …
=> [A2-879] Refactor DeleteRule to work with staged rules

components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.ts
on the backend side of things, we are ignoring the start time for the
export endpoint, and simulating the behaviour here, where we say
start time is beg of day of end time. we would like to change this to
respect the provided start time for api users, so we need to adjust the
ui to send start time as beg of day of end time (instead of beg of day
from 10 days ago) so that we can maintain the behaviour of the ui export.
fixes https://github.com/chef/automate/issues/532
start time on export endpoint is beg of day of end time
send some compliance scans in (chef_load_compliance_scans -N5)
rebuild ui
open dev tools
export json/csv
check headers
**this is not quite correct yet. it should have that Z at the end of the start time...help?**
^^ nevermind! got help from @scottopherson and all good …
=> compliance export: set start time to beg of day of end time

components/automate-ui/src/app/page-components/services-sidebar/services-sidebar.component.ts, components/automate-ui/src/app/pages/service-groups/service-groups.component.spec.ts, components/automate-ui/src/app/pages/service-groups/service-groups.component.ts, components/automate-ui/src/app/services/telemetry/telemetry.service.ts
Added track calls for total service groups and service
Added track calls for status filter, pagination for service groups and service
Added track calls for sorting service group table
For status filter and pagination the track call names are shared and an entity
attribute is added so we can see information about both in the same table
Start the UI 
Open up the debug tools and look at the network traffic. 
When you click on sort you should see an event for applicationSort.
When you click on a status filter you should see an event for applicationStatusFilter
Every time the page loads you should see an event for applicationServiceCount
Clicking on a service group to change the services sidebar you should see an event for applicationServiceCount …
=> [A2-858] Add telemetry to EAS apps UI

components/data-feed-service/service/data-feed-service.go
The code is switching on an element from the wrong array. This doesn't appear to cause any issue but needs changed for correctness. I noticed this in development when adding functionality for compliance reports, in which it did cause an issue with the URL.
Can't be reproduced on master.
=> Switch on assetRules rather than rules

components/nodemanager-service/pgdb/nodes.go
Previously `updated` would be nil if the job type or status was not
recognized, leading to a nil pointer dereference later in this
function.
=> [nodemanager] Avoid nil pointer dereference on bad job type

components/compliance-service/api/reporting/server/server.go, components/compliance-service/api/tests/export_test.go
We need to consider start_time as well as end_time when performing export for compliance scans.
Currently, we ignore start_time and, instead, compute it as the [UTC] beginning of day for the same day as that of the end_time.  The rationale for this is that because all other apis for compliance reporting, use this approach to time span, so should export.  We have recently identified a real need to break the exports up into smaller time intervals, necessitating the use of start_time.
Once this PR merges, we will no longer compute start_time from end_time, we will use what is given.  From the UI perspective, nothing will change because now the UI will compute that start_time and send it to us.  The API users will benefit from this new flexibility.
=> use start_time as well as end_time when filtering reports for export

components/authz-service/server/v2/project.go, components/authz-service/storage/errors.go, components/authz-service/storage/postgres/migration/sql/49_update_rule_triggers.up.sql, components/authz-service/storage/postgres/migration/sql/README.md, components/authz-service/storage/postgres/postgres.go, components/authz-service/storage/v2/postgres/postgres.go, components/authz-service/storage/v2/postgres/postgres_test.go, inspec/a2-api-integration/controls/iam_v2.rb
Previously, the UpdateRule API directly updated the rules. Since any rule update takes time to completely apply to ingested resources, we're refactoring the rules API so that all changes to rules are stored in a `staged` rules table (preserving the rules in their current state in the `applied` table). Only when the user calls ApplyRules will the updated rules in the staging table be applied to the `applied` rules table.
UpdateRule now:
1) Creates a new "staged rule" for existing "applied" rule
2) Updates existing "staged rule" if already created
3) Does not update staged rules marked for deletion
TODO: what should memstore implementation look like?
```
build components/authz-service
export TOK=`chef-automate iam token create TEST --admin`
```
1. insert an "applied" rule …
=> [A2-878] Update Rule Refactor

components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.spec.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.ts
As noted in https://github.com/chef/automate/pull/639#issuecomment-504463446, a recent change we made was setting the start time on export to beginning of today, instead of beginning of day of end time.
I discovered we were getting the end time object, but not the value, and so moment was just setting start time to the beginning of today's date.
This change ensures that we're getting the actual value.
start time is set to beg of day of whatever value is the end time
=> ensure we get the actual value for end time when calculating start of day for start_time

components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.ts, components/compliance-service/api/tests/07_suggestions_w_filters_spec.rb, components/compliance-service/ingest/ingestic/mappings/comp-profiles.go, components/compliance-service/ingest/ingestic/mappings/comp-rep-date.go, components/compliance-service/ingest/ingestic/mappings/comp-sum-date.go, components/compliance-service/integration_test/reporting_server_list_nodes_test.go, components/compliance-service/integration_test/reporting_server_list_suggestions_test.go, components/compliance-service/reporting/relaxting/suggestions.go
Adding the InSpec version to the Compliance page search bar. During testing this addition we noticed that for suggestions '.' characters are treated differently. The problem was that the Elasticsearch tokenizer was not including the '.' in the tokens. To fix the problem we have to add the "punctuation" term to the "autocomplete_tokenizer". 
* Without a migration of the existing indexes only the reports ingested after this change will have InSpec Version numbers show up in the search bar suggestions. 
1. `build components/compliance-service && build components/automate-ui && start_all_services`
1. `send_inspec_example`
1. Change the "version" field on this file components/compliance-service/ingest/examples/compliance-success-tiny-report.json
1. Then ingest a report with …
=> Adding InSpec version to Compliance page search bar

.expeditor/verify.pipeline.yml
These tests are not currently running on master:
SKIP: TestDBInterface (0.00s)
exporter_integration_test.go:61:
Skipping exporter integration tests because pg_ctl was not
found on path! To run these tests, you must have PostgreSQL
installed
This has likely been the case since this library was extracted
from the deployment-service.
=> Run pg integration tests in automate lib

.expeditor/verify_private.pipeline.yml, .studio/automate-load-balancer, components/automate-load-balancer/habitat/config/nginx.conf
In @msorens' performance investigations, he observed that some latency is introduced by the fact that a browser only open _n_ TCP connections to one origin (_n=6_ for Chrome, it seems). This is unfortunate, but since HTTP2 solves that, by pipelining multiple requests in a single connection, it seemed worthwhile to give that a try.
And indeed, it seems that the specific delay ("stalled" in the dev tools' details view) goes down significantly when using HTTP2.
So, let's do this 😉 
Note that for the problem at hand here, internal connections don't matter as much -- so this only enables HTTP2 at the edge.
✅ Added a simple test, which outputs nothing on success. But glancing at `sup.log`, we find
```
automate-load-balancer.default [25/Jun/2019:12:47:02 +0000]  "GET / HTTP/2.0" 200 "0.002" …
```
=> automate-load-balancer += http2

components/applications-service/cmd/applications-publisher/main.go, components/applications-service/integration_test/global_test.go, components/applications-service/integration_test/storage_service_timestamp_test.go, components/applications-service/pkg/storage/client.go, components/applications-service/pkg/storage/postgres/db.go, components/applications-service/pkg/storage/postgres/hab_event.go, components/applications-service/pkg/storage/postgres/schema/sql/04_timestamps.up.sql, components/applications-service/pkg/storage/postgres/service.go, components/applications-service/pkg/storage/postgres/service_groups.go
We are adding timestamps to all our tables inside the applications-service.
Every table in the database has `created_at` and `updated_at` timestamps.
Additionally, we will start storing the timestamp of when habitat submitted
the event message. (new column in service table `last_event_occurred_at`)
Build and start the applications-service and run the integration tests,
you can also login to the database and list the data.
https://chefio.atlassian.net/browse/A2-892
=> Add timestamp fields to database tables

components/automate-deployment/pkg/bootstrap/bundle_creator.go, lib/io/fileutils/atomic_write.go
The file creation mode is affected by umask, which is undesirable
in some cases.
=> Add chmod to atomic file writer

components/automate-cli/cmd/chef-automate/bootstrap.go, components/automate-deployment/pkg/bootstrap/bundle_creator.go
Slapped a header on the tar to give us the flexibility to
change it in the future if we need. The extension is
abb (Automate Bootstrap Bundle), similar to the airgap bundle.
=> Give the bootstrap bunde its own file format

components/authz-service/storage/postgres/migration/sql/51_change_project_rules_query.up.sql, components/authz-service/storage/postgres/migration/sql/README.md, components/authz-service/storage/v2/postgres/postgres_test.go, inspec/a2-api-integration/controls/iam_v2.rb
Any user viewing a project's rules should be able to see the latest staged changes to a project. This PR refactors ListRulesForProject to check both the `applied` and `staged` rule tables and ensure that only the most up-to-date version of the rule is returned in the list.
This also means any applied rule that has been staged for deletion will not be returned in this list.
db setup
```
insert into iam_projects (id, name, type, projects) values ('foo-project', 'Foo Project', 'custom', ARRAY['foo-project']);
insert into iam_project_rules (id, project_id, name, type) values ('foo-rule', 'foo-project', 'foorule', 'node');
insert into iam_rule_conditions (rule_db_id, attribute, value, operator) values ((SELECT db_id from iam_project_rules where id='foo-rule'), 'chef-server', ARRAY['foo'], …
```
=> [A2-814] ListRulesForProject returns latest rule updates

components/authn-service/Makefile, components/authn-service/tokens/pg/adapter.go, components/authz-service/storage/v1/postgres/postgres.go, components/authz-service/storage/v2/postgres/postgres.go, components/teams-service/storage/postgres/postgres.go
Thanks to @stevendanna's attention to detail, this makes our auth services do what needs to be done when using `database/sql`'s [`(*Rows).Next`](https://golang.org/pkg/database/sql/#Rows.Next):
> Next prepares the next result row for reading with the Scan method. *It returns true on success, or false if there is no next result row **or an error happened while preparing it**.* Err should be consulted to distinguish between the two cases.
=> auth services: add rows.Err() checks

integration/services/ha_backend/init
Looks like an assumption was being made that openssl was installed
in hab. But we don't seem to use that bit of code anyway, so I
removed it.
=> Delete what appears to be unused code

components/automate-ui/src/app/page-components/license-apply/license-apply.component.spec.ts, components/automate-ui/src/app/page-components/license-lockout/license-lockout.component.spec.ts, components/automate-ui/src/app/services/chef-session/chef-session.service.ts, components/automate-ui/src/app/services/config/config.service.spec.ts, components/automate-ui/src/app/services/http/http-client-auth.interceptor.spec.ts, components/automate-ui/src/app/services/telemetry/telemetry.service.ts
- removed from test specs where it didn't matter
- replaced with error.message where it did matter
- placed a comment on it where I didn't want to change anything
What is this? HTTP/2 doesn't send a "status text". Status text is the last segment after
HTTP/x.y <CODE> <REASON>
in the server response, so, where with HTTP/1.1 we see
HTTP/1.1 401 Unauthorized
with HTTP/2, we see
HTTP/2 401
The corresponding [RFC7540 paragraph][1] is
> HTTP/2 does not define a way to carry the version or reason phrase that is included in an HTTP/1.1 status line.
[1]: https://greenbytes.de/tech/webdav/rfc7540.html#rfc.section.8.1.2.4.p.2
=> automate-ui: cleanup statusText usage

lib/cereal/backend/backend.go, lib/cereal/cereal.go, lib/cereal/integration/schedule_test.go, lib/cereal/postgres/postgres.go
This removes the other "Getters" in favor of a function that returns
the entire schedule to you.
Also, while I was here, I added a missing error check.
=> [cereal] Add GetWorkflowScheduleByName

components/authz-service/engine/opa/opa.go, components/authz-service/server/server.go, components/authz-service/server/v2/policy.go, components/authz-service/server/v2/policy_refresher.go, components/authz-service/server/v2/policy_test.go, components/authz-service/server/v2/project.go, components/authz-service/server/v2/project_test.go, components/authz-service/server/v2/project_update_manager_test.go, components/authz-service/server/v2/rules_property_test.go, components/authz-service/server/v2/system_integration_test.go, components/authz-service/storage/v2/memstore/memstore.go, components/authz-service/storage/v2/postgres/postgres.go, components/authz-service/storage/v2/postgres/postgres_test.go, components/authz-service/storage/v2/storage.go, components/authz-service/testhelpers/testhelpers.go, lib/config/config_mgmt.go
Update `POST /apis/iam/v2beta/apply-rules` to apply all staged project rules and then trigger a `Refresh` of the OPA cache before kicking of the reindex.
Please see the commit titled `[SHAME]` for context around how the `PolicyRefresher` singleton is being routed around.
```
chef-automate iam upgrade-to-v2 --beta2.1
export TOK=`chef-automate iam token create my-token --admin`
chef_load_nodes 100
```
```
```
Everything is still in unassigned because rules are staged only:
```
3
6
```
Can see things staged:
```
chef_authz_service=# select * from iam_project_rules;
db_id | id | project_id | name | type
-------+----+------------+------+------
(0 rows)
chef_authz_service=# select * from iam_staged_project_rules;
db_id |  id   | project_id | …
```
=> [A2-813] Apply Staged Project Rules API

e2e/cypress/integration/compliance/01_ssh_scan_job.spec.js
It seems the checks done by cypress are too cautious -- so, we apply
some force.
Couldn't find a better way; but running this against dev passes the
scanner job specs.
See https://docs.cypress.io/guides/references/error-messages.html#cy-failed-because-the-element-cannot-be-interacted-with
for details.
=> e2e/cypress: disable visibility checking for "Remove Credential"

.studio/common
**Before:** 
```
[1][default:/src:0]# compile_go_protobuf_component bla
ERROR: Component 'bla' not found.
hab-studio: Available components:
* applications-service
* authn-service
* authz-service
* automate-chef-io
* automate-cli
* automate-cs-bookshelf
* automate-cs-nginx
* automate-cs-oc-bifrost
* automate-cs-oc-erchef
* automate-debug
* automate-deployment
* automate-dex
* automate-elasticsearch
* automate-es-gateway
* automate-gateway
* automate-grpc
* automate-load-balancer
* automate-pg-gateway
* automate-platform-tools
* automate-postgresql
* automate-prometheus
* automate-scaffolding
* automate-scaffolding-go
* automate-ui
* automate-ui-devproxy
* automate-workflow-ctl
* automate-workflow-nginx
* automate-workflow-server
* automate-workflow-web
* backup-gateway
* chef-ui-library
* …
```
=> compile_go_protobuf_component recommend only working targets

.expeditor/verify.pipeline.yml, .studio/golang, .studiorc, components/event-feed-service/pkg/grpc/grpc.go, components/event-feed-service/pkg/server/server.go
This project was already very close to being lint clean, so I've
applied the linter to it and added a studio function for running the
linter.
This unfortunately duplicates some of the functionality of we have in
Makefile.common_go, but I didn't want to wade into the task of fixing
the curious blend of Makefiles, shell scripts, and studio functions
that various parts of the repository uses.
We may want to have go_component_static_tests run the linter; however,
I'll defer that until all the projects that use
go_component_static_tests are passing the linter.
=> [event-feed-service] Apply golangci-lint

.bldr.toml, components/event-feed-service/pkg/util/util.go
The only compliance-service dependency was a thin helper function that
has also been copied into this project.
In general I think we should avoid cross-component code dependencies
where possible and this was a simple one to break. It will also
prevent over-building of the event-feed-service.
=> [event-feed-service] Don't depend on compliance-service

components/compliance-service/api/tests/02_nodes_spec.rb, components/compliance-service/api/tests/03_deep_reports_spec.rb, components/compliance-service/api/tests/03_reports_spec.rb, components/compliance-service/api/tests/09_profiles_spec.rb, components/compliance-service/api/tests/20_secrets_spec.rb, components/compliance-service/api/tests/25_nodes_spec.rb, components/compliance-service/api/tests/30_jobs_docker_spec.rb, components/compliance-service/api/tests/50_scheduler_spec.rb, components/compliance-service/api/tests/poll_test.rb, components/compliance-service/api/tests/test_ingest_to_mgr_conn.rb
Thank you @stevendanna for letting me know we still had swapped `actual` & `expected` values in tests.
Hopefully, they are all fixed now with this PR.
=> Compliance: swap around wrong actual and expected asserts

.studio/golang
A bunch of functions use `pkg` as a local variable without the `local`
keyword. Isn't shell fun?
=> [studio] set variable as late as possible

components/compliance-service/integration_test/suite_test.go
Retrying failed attempts at deleting all elasticsearch documents. 
https://github.com/chef/automate/issues/613
=> Flaky test: deleting elasticsearch documents at end of test

.expeditor/buildkite/cypress.sh, e2e/cypress/integration/01_login.spec.js, e2e/cypress/support/commands.js, terraform/test-environments/README.md, terraform/test-environments/modules/chef_automate_install/main.tf, terraform/test-environments/modules/chef_automate_install/variables.tf, terraform/test-environments/scenarios/airgapped_single_local_fresh_install.tf, terraform/test-environments/scenarios/airgapped_single_local_inplace_upgrade.tf, terraform/test-environments/scenarios/chef-server_performance_test_single_local_inplace_upgrade.tf, terraform/test-environments/scenarios/performance_test_single_local_inplace_upgrade.tf, terraform/test-environments/scenarios/single_hardened_local_fresh_install.tf, terraform/test-environments/scenarios/single_local_fresh_install.tf, terraform/test-environments/scenarios/single_local_iamv2_fresh_install.tf, terraform/test-environments/scenarios/single_local_iamv2_inplace_upgrade.tf, terraform/test-environments/scenarios/single_local_iamv2p1_fresh_install.tf, terraform/test-environments/scenarios/single_local_iamv2p1_inplace_upgrade.tf, terraform/test-environments/scenarios/single_local_inplace_upgrade.tf, terraform/test-environments/scenarios/single_local_workflow_fresh_install.tf, terraform/test-environments/scenarios/single_local_workflow_inplace_upgrade.tf
It's gotten confusing that all envs claim to do SAML when just a small subset of them do. (It's got to do with some limitation on Okta, not our code.)
=> dev/acceptance envs: remove saml lies and deal with the fallout

.expeditor/buildkite/cypress.sh, .expeditor/buildkite/inspec.sh, e2e/cypress/support/commands.js, inspec/a2-resource-pack/libraries/automate_api_request.rb
Cleaning up the fall-out of #726. When testing that other PR, 
- I had assumed that the inspec stuff already knew how to deal with single-login method situations.
- Also, I hadn't considered that cypress tests actually attempt to _logout_, spot-checking the specs, I hadn't triggered one that had attempted that.
Well, now, we're good. 😄
=> fix saml in dev and acceptance for inspec and cypress

.expeditor/buildkite/inspec.sh, terraform/test-environments/scenarios/airgapped_single_local_fresh_install.tf
Only scan those machines that have multiple methods, until we've fixed the inspec code for a single login method.
While looking at those machines with a "saml" tag, I've noticed one that had it but didn't deserve it. Fixed.
=> quickfix: inspec and saml login

components/authz-service/server/v2/policy_test.go, components/authz-service/server/v2/project.go, components/authz-service/server/v2/project_test.go, components/authz-service/server/v2/project_update_manager.go, components/authz-service/server/v2/rules_property_test.go, components/authz-service/storage/v2/postgres/postgres.go, components/authz-service/storage/v2/postgres/postgres_test.go, components/authz-service/storage/v2/rule.go, components/authz-service/testhelpers/testhelpers.go
Defining property-based tests for rules, checking real DB operations--particularly including the effect of applying rules--while ignoring the ingest service and policy refresher for this first phase.
I have reduced the number of tests from gopter's default of 100 test runs because these tests are rather slow and caused timeouts in CI.
I have also reduced globally the maximum number of things generated for lists (typically generated via `gen.SliceOf` otherwise `ListRules` tests regularly exceed the capacity of the GRPC message size (4194304). I have even further constrained the maximum number of rule conditions locally to a smaller number of items for the same reason.
Here is the contract that these tests are concerned with. I am particularly focussing on staged vs applied rules in these …
=> [A2-292] Property-based tests for rules

components/notifications-service/habitat/plan.sh
elixir 1.9.0 shipped with a number of changes to how releases
work. This appears to have broken the build. Pinning until we can
sort out the required changes.
=> [notifications-service] Pin elixir to 1.8 for now

components/automate-workflow-nginx/habitat/plan.sh
chef/openresty-noroot is out of date and thus depends on an old
openssl. For automate-workflow-nginx to build we need to depend on
this older curl which depends on the same version of openssl as
openresty-noroot.
See chef/chef-server#1697
=> [workflow-nginx] Pin curl

.expeditor/buildkite/inspec.sh, inspec/a2-resource-pack/libraries/automate_api_request.rb
This finishes #743 and #745.
Now, when run locally against a dev env machine with only one method, it'll pass:
```
[35][default:/src:100]# inspec exec inspec/a2-api-smoke --key-files tmpkey -t ssh://srenatus@a2-local-fresh-install-dev.cd.chef.co
Ignoring `enable_remote_worker` option, the `http` resource
remote worker is enabled by default for remote targets and
cannot be disabled
Ignoring `enable_remote_worker` option, the `http` resource
remote worker is enabled by default for remote targets and
cannot be disabled
Ignoring `enable_remote_worker` option, the `http` resource
remote worker is enabled by default for remote targets and
cannot be disabled
Ignoring `enable_remote_worker` option, the `http` resource
remote worker is enabled by default for remote targets and
cannot be disabled …
```
=> inspec: fix automate_api_request for single-method login

components/automate-deployment/pkg/assets/assets.bindata.go, components/automate-deployment/pkg/services/internal/generated/gen.go, products.meta
The auth collection already had authn-service, so automate
did not need to repeat it. Also, teams-service should belong
under auth.
=> Cleanup auth collection in products.meta

components/automate-deployment/pkg/client/deployer.go
For chef-server only, we don't need the credentials to be written as they wont be used anywhere
=> Don't write out credentials for non automate deploys

components/config-mgmt-service/backend/elastic/nodes.go, components/config-mgmt-service/grpcserver/node_export.go, components/config-mgmt-service/integration_test/node_export_test.go
Preventing the Client Runs page's node export from going into an infinite loop. To cause the infinite loop when using the node export, a user needs to have nodes with the same name that has uppercase characters. This bug is caused by using the Elasticsearch SearchAfter API with non-matching curser values. When requesting the second page of values the last value from the first page's node name is used in the request. For the node-state index, the node name values are matched as lower-case, but the code was sending the values with uppercase. When this happens, SearchAfter API will return the first page again. 
I have not seen that this infinite loop timeout in any way. Therefore a context deadline of one minute was added to prevent this from happening again. 
1. `build …
=> Client Runs page's node export infinite loop

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-nodes/reporting-nodes.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/reporting-overview.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profiles/reporting-profiles.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.spec.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/report-data.service.spec.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/report-data.service.ts, components/automate-ui/src/app/pages/client-runs/client-runs.component.ts
We want to get a better idea of how many client-run and compliance nodes customers are hooking up to automate. This will help us to better understand if licenses are being fully utilized. 
client-run nodes are counted when no filters are applied. IAMv2.1 will
still apply filters but we can take the maximum reported.
compliance stats include filters since start and end time are often employed.
Click on the client-runs tab. Look at the network traffic in the browser tools window and find the event with a payload reporting "clientRunPureCount".
Click on the compliance tab. Look at the network traffic in the browser tools window and find the event with a payload reporting "complianceCountsWithFilters"
=> Add telemetry to count client-run based nodes and compliance stats

components/automate-deployment/a1-migration/install.rb, components/automate-deployment/a1-migration/load-artifact, components/automate-deployment/a1-migration/setup.rb
a1-migration failures started yesterday as a result of the new Chef Server release.  This
PR resolves the following problems:
- 14.04 artifacts no longer available
- chef-server requires license acceptance
a1-migration pipeline passes
=> [CI] Fix nightly a1-migration failures

scripts/verify_build, scripts/verify_setup, scripts/verify_studio_init
Not having these shebang lines makes running shellcheck less useful
and makes it harder to use the script in all contexts.
Note that scripts/copy_hartifacts is being fixed in #758
While touching these files, I've run shellcheck on them and fixed all
of the violations.
=> [scripts] Add more missing shebang lines

components/automate-cs-nginx/habitat/config/chef_https.conf, components/automate-cs-oc-erchef/habitat/config/sys.config
1.  The nginx config has a typo [here](https://github.com/chef/automate/blob/master/components/automate-cs-nginx/habitat/config/chef_https.conf#L119)   (`es` should be `automate`)
2. The behavior for erchef should be to not verify the SSL cert of the external automate unless an automate root CA is supplied.   The second commit moves the if clause to correct that.
Using the instructions from PR #746
=> 2 fixes for chef-server when using an external automate

components/applications-service/integration_test/ingestion_test.go, components/applications-service/pkg/storage/postgres/hab_event.go, components/applications-service/pkg/storage/postgres/schema/sql/07_unique_constraints.up.sql
We allowed non-unique deployments to be inserted, since we ingest in batches this
could end up with duplicates. We applied a uniqueness constraint to prevent duplicates.
Same batches of new service-groups or new deployments are then retried when the unique constraint is hit.
Hard to repro outside of integration tests, but theres a test!
=> [A2-890] Fix race condition in db with deployments

scripts/changed_components.rb
It didn't matter, but when running this on master, the pkg_build_deps
construction would fail for anything that is looking at
`$PLAN_CONTEXT/...` etc.
cat: /../.nvmrc: No such file or directory
core/curl core/coreutils chef/mlsa core/nginx core/jq-static
It didn't matter because the script in question doesn't care for build
deps/
=> scripts/changed_components.rb: fix pkg_deps call

dev-docs/a2-chef-server.md
Internal docs for deploying standalone chef server with automate.
Fixes #719.
=> Internal docs for automate-deployed chef server.

components/automate-cli/cmd/chef-automate/backup.go
The previous help text was inaccurate. The new help text is what we
use for the --yes flag in the `delete` command.
Fixes #790
=> [cli] Fix help message text for --yes

components/automate-ui/src/app/pages/automate-settings/automate-settings.component.html, components/automate-ui/src/app/pages/automate-settings/automate-settings.component.ts
An issue in the UI with the time type options being set back to the original state on refresh.
The config manager on this has changed recently
It looks like it is a problem on the frontend
The backend is updating but the frontend is not showing the change
Select boxes for units should show selected unit values on refresh
Navigate to Settings > Node Lifecycle
Change any of the time type options (minutes, hours, days)
Apply Changes
Refresh the page
Notice that the time type options reset back to what they were
https://github.com/chef/automate/issues/371
=> UI-371-node-lifecycle-bug Signed-Off-By: Tara Black <tblack@chef.io>

.github/CODEOWNERS
updating to ensure we ping ux for review when we
touch the ui, and changing all references to infra-automation-team
and compliance-team to superteam
=> updating codeowners

.expeditor/update_chef_server.sh, components/automate-cs-bookshelf/habitat/plan.sh, components/automate-cs-nginx/habitat/plan.sh, components/automate-cs-oc-bifrost/habitat/plan.sh, components/automate-cs-oc-erchef/habitat/plan.sh, components/automate-workflow-nginx/habitat/plan.sh
This updates all pins for packages published by chef/chef-server and
introduces a script that can be used to update the pins in the
future. The script can be used as follows:
NO_GIT=true ./.expeditor/update_chef_server.sh unstable
and can also be wired into expeditor. We have not added expeditor
configuration for it yet as I think we need to decide what channel we
want to follow. If we want to follow `stable` then the script will
need additional logic to ensure either that:
1) We never roll these pins backwards when currently pinned to
unstable, or
2) Updates all transitive dependencies pins as well.
=> Update all chef-server pins to the latest

.expeditor/nightly.pipeline.yml, .studio/common, scripts/verify_build.sh
We periodically find that components no longer build because of
dependency changes. We typically find out that these components don't
build when developers are doing cleanup or maintenance work such as
updating dependencies. Only finding build problems during such tasks
increases the cost of starting such tasks and means that we discover
the problems long after the change that produced the problem, making
it harder to debug.
Currently, the nightly builds only rebuild whatever changed in the
latest commit to master, using the same changed components logic that
the rest of our verify pipelines use.
This changes the nightlies to build all components, which should allow
us to discover build issues more promptly, divorced from any
particular change.
=> [CI/nightly] Build ALL components during nightly build

.expeditor/config.yml, components/automate-chef-io/data/docs/api_chef_automate/applications/applications.swagger.json
I recently made a change to the script expeditor runs when swagger files are updated (https://github.com/chef/automate/pull/711). The most recent time that script was run was June 28th (https://buildkite.com/chef-oss/chef-automate-master-verify/builds/2629). A PR was merged July 3rd that I would have expected to trigger this script and didn't (https://github.com/chef/automate/pull/713). I think I screwed up by including a leading `/` in the path of the files to monitor for changes in the expeditor config.
=> Fix expeditor swagger syncing

.expeditor/verify_private.pipeline.yml, components/authz-service/storage/postgres/datamigration/datamigration.go, integration/tests/upgrade_reset_iam_v2p1.sh
This [change](https://github.com/chef/automate/blob/c94572e5ab3cfbaec2230af0afdfde7e0bfff145/components/authz-service/storage/postgres/datamigration/datamigration.go) accidentally removed some Reset code that was special to datamigrations. This code resets the data_migrations table when reset to IAM v1 so that on the next upgrade to 2.x the datamigrations get reapplied. This is different than standard migrations since we never undo schema migrations.
Also added regression tests to the pipeline.
=> Revert DRY-ing up of datamigrations that introduced bug

.expeditor/update_chef_server.sh, components/automate-cs-bookshelf/habitat/plan.sh, components/automate-cs-nginx/habitat/plan.sh, components/automate-cs-oc-bifrost/habitat/plan.sh, components/automate-cs-oc-erchef/habitat/plan.sh, components/automate-workflow-nginx/habitat/plan.sh
The day after we decided to stop pinning, core/curl was promoted again
leading to a nightly breakage.  This PR was created by running
NO_GIT=true ./.expeditor/update_chef_server.sh unstable
after running a Chef Server build from Buildkite.
=> [automate-chef-server] Bump automate-cs package for core/curl rebuild

components/automate-pg-gateway/habitat/config/haproxy.conf
When a go process dies because of a signal or a panic, defer'd
database closes may not execute. In this case, HAProxy will keep the
client side connection in CLOSE-WAIT and the server-side connection in
ESTAB. Setting `server-fin` times out the server-side connection
quickly, avoiding a leaked process. Without this, the process would
not close for 5 minutes until the tunnel timeout is hit.
=> [pg-gateway] Set server-fin timeout

components/authz-service/storage/v1/postgres/postgres.go, lib/io/fileutils/fileutils.go
This is a small helper function. It is a bit silly, but I applied it
to one file and I like the cleanup and think it might encourage us to
not ignore this err check more often.
=> [lib/fileutils] Add new LogCloser function

components/automate-deployment/pkg/target/local_target.go
In CI we are seeing systemctl status fail with an exit code 3 but no
useful error message. This function is pretty suspect (string
matching error output), so it is possible that systemd behavior has
change subtly or that this function was always incorrect.
=> [deployment-service] Log stdout from systemctl status command

.expeditor/verify.pipeline.yml, .expeditor/verify_private.pipeline.yml
We know that everything in the `post-build` phase of the pipeline is
an integration test. All this does is make it hard to read what failed.
@srenatus gave me the idea. I think the gain in scan-ability is worth any
downside.
=> [CI] Remove [integration] prefix from some jobs

components/compliance-service/api/tests/03_reports_spec.rb, components/compliance-service/api/tests/30_jobs_docker_spec.rb, components/compliance-service/api/tests/40_jobs_ssh_spec.rb
Fixing random test failure reported by @srenatus 
https://buildkite.com/chef-oss/chef-automate-master-verify/builds/2972#149d2df2-67ef-45df-9f01-fa05428f57fa/148-626
```
1) Failure:
30_jobs_docker_spec.rb#test_0005_works [/var/lib/buildkite-agent/builds/single-use-privileged-i-07adbaf986d5b3195-1/chef-oss/.golang/chef-automate-master-verify/src/github.com/chef/automate/components/compliance-service/api/tests/30_jobs_docker_spec.rb:260]:
expected
actual
@@ -6,6 +6,13 @@
["d141c925-110a-4c99-8530-d8b12af6a106",
"e56cb2be-5c82-4332-ba5b-2f8b70cfe5c7"],
"parentId"=>"123",
+ "results"=>
+  [{"endTime"=>"2019-07-11T13:20:17Z",
+    "nodeId"=>"d141c925-110a-4c99-8530-d8b12af6a106",
+    "result"=>
+     "{\"arch\":\"x86_64\",\"families\":[\"debian\",\"linux\",\"unix\",\"os\"],\"name\":\"debian\", …
```
=>  Protect compliance integration tests against fast completing jobs

components/automate-workflow-server/habitat/plan.sh
core/git has been updated with a new version of core. I've removed
the min rather bumping this pin since it feels like having conflicting
core/curl and core/git packages in stable would be something we want
to raise with the hab team rather than ignore.
=> [automate-workflow-server] Unpin core/git

components/automate-workflow-server/apps/notification/test/notification_hand_test_notification_tests.erl, components/automate-workflow-web/test/e2e/specs/org.spec.js, components/automate-workflow-web/test/e2e/specs/orgs.spec.js, components/notifications-service/server/.iex.exs, tools/credscan/credscan.go
This removes old slack webhook URLs. These webhooks have been
disabled, but to make scanning easier, they've been replaced with fake
data that can be excluded in the credscan tool.
=> Remove disabled webhook URLs from repository completely

integration/helpers/backup.sh
There is currently a bug related to a bad interaction between the
periodic cert check and our shutdown logic. The code is very
entangled and it is going to take some time to sort out safely. For
now, I think modifying the cert generation test may lead us to time
out less frequently.
=> [ci] Restructure tests to work around bug

integration/helpers/testing.sh, integration/tests/airgap_product.sh, integration/tests/backup_s3.sh, integration/tests/product.sh
Based on other work in #90, I think that the stop and start
chef-automate is likely causing a long delay in the tests because at
we effectively have to wait for a timeout to happen before that will
actually complete.
It also looks like verify-packages might occasionally be very slow.
This adds some logging so that we can verify that in the CI logs.
=> [ci] Add a few more log lines

components/automate-deployment/pkg/bootstrapbundle/bundle_creator_test.go
We were appending the wrong array. This probably worked out on
machines where uid's and gid's match up.
=> [deployment-service] Fix small bug in unit tests

components/automate-deployment/pkg/server/server.go
target.Stop() is an asynchronous command because eventually `hab sup
term` will terminate the process itself.  Here, we were passing a
context into Stop that would be cancelled at the end of the function.
In most cases, this meant that `hab sup term` never got a chance to
request that the supervisor terminate and thus the service would not
be shut down until we hit the systemd timeout.
=> [deployment-service] Avoid hang on shutdown

lib/cereal/backend/backend.go, lib/cereal/cereal.go, lib/cereal/postgres/postgres.go, lib/cereal/postgres/sql_schema.go
Was going through TODOs and found this. The task completer keeps the
task ID and that is all we need to complete the task since the
workflow ID for that task lives in the cereal_tasks table.
=> [cereal] Remove unused WorkflowInstanceID from backend.Task

components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.html, components/automate-ui/src/app/helpers/auth/regex.ts, components/automate-ui/src/app/page-components/license-lockout/license-lockout.component.html, components/automate-ui/src/app/pages/api-token/details/api-token-details.component.html, components/automate-ui/src/app/pages/api-token/details/api-token-details.component.ts, components/automate-ui/src/app/pages/api-token/list/api-token-list.component.ts, components/automate-ui/src/app/pages/policy/add-members/policy-add-members.component.html, components/automate-ui/src/app/pages/policy/add-members/policy-add-members.component.ts, components/automate-ui/src/app/pages/project/details/project-details.component.ts, components/automate-ui/src/app/pages/project/list/project-list.component.ts, components/automate-ui/src/app/pages/team-create/team-create.component.html, components/automate-ui/src/app/pages/team-create/team-create.component.ts, components/automate-ui/src/app/pages/team-details/team-details.component.html, components/automate-ui/src/app/pages/team-details/team-details.component.ts, components/automate-ui/src/app/pages/user-details/user-details.component.html, components/automate-ui/src/app/pages/user-management/user-form/user-form.component.html, components/automate-ui/src/app/pages/user-management/user-management.component.ts, components/automate-ui/src/app/pipes/pluralize.pipe.spec.ts, components/automate-ui/src/app/pipes/pluralize.pipe.ts
In the course of acceptance testing, I started noticing some inconsistent wordings, and error triggers. This PR is a general cleanup of a host of little things across policies, projects, users, teams, and tokens (we don't have any forms for roles, so nothing there).
1. Pulled out common validation regexes used in multiple places into a single constants file, helpers/auth/regex.ts.
2. Ensure all error displays do not end in a period.
3. Ensure wording the same for same phrases.
4. Ensure consistent grammar "A team is..." vs. "Team is....".
5. Ensure note for each Validator reminds the developer which template to sync with.
6. Ensure consistent formatting of <chef-error> elements.
7. Ensure "Required" error msg omits the phrase "non-blank" (as it really doesn't add value).
1. …
=> Consistency improvement and minor bug fixes for auth UI pages

components/authz-service/storage/postgres/migration/sql/55_use_project_db_id_in_references_of_project_roles.up.sql, components/authz-service/storage/postgres/migration/sql/README.md, components/authz-service/storage/postgres/postgres.go, components/authz-service/storage/v2/postgres/postgres.go, components/authz-service/storage/v2/postgres/postgres_test.go
✔️ `iam_project_roles` now refers to `iam_projects` using the latter's `db_id` field, not `id`.
#832
=> [part of #832] use db_id between projects and roles

lib/cereal/cereal.go, tools/cereal-scaffold/main.go
This allows users to defer the close to properly shutdown the db.
=> [lib/cereal] manager.Stop() should close backend

api/config/shared/tls.go, integration/helpers/ssl_filters.jq, integration/helpers/ssl_tests.sh, lib/grpc/secureconn/factory.go
- Nginx configuration synced with the most recent "intermediate"
Mozilla advice.
- CBC ciphers disabled in default Go configuration based on recent
advice:
https://blog.qualys.com/technology/2019/04/22/zombie-poodle-and-goldendoodle-vulnerabilities#comment-303227
- Move back to master of testssl
Note that we still aren't configuring TLS ciphers for our elixir or
erlang services. That would be a nice thing to pick up at some point.
=> Remove CBC ciphers from nginx and golang configuration

components/authz-service/storage/postgres/datamigration/sql/01_v2_data_migrations.up.sql, components/authz-service/storage/postgres/migration/sql/56_add_db_id_statements.up.sql, components/authz-service/storage/postgres/migration/sql/README.md, components/authz-service/storage/v2/postgres/postgres.go, components/authz-service/storage/v2/postgres/postgres_test.go
Adds `db_id` _and_ `policy_id` (db_id) to iam_statements, allowing the removal of the superfluous `iam_policy_statements` table. Given that policy: statement is one: many, we didn't need the associations table.
I've left adding the new statement db_id as the new foreign key to `iam_statement_projects` as the PR's tests (and a gnarly, unfortunate rebase) made this PR unwieldy. 
Tests pass. 
Bring up hab studio, rebuild `components/authz-service`, CURL to create, delete, update, get policies with statements:
In ui, create new user coolbean, pw chefautomate
`curl -XPOST -d '{"name":"test", "id":"newpolicy", "members":["user:local:coolbean"], "statements":[{"effect":"ALLOW", "actions":["*"] }]}' -H "api-token: $TOK" https://a2-dev.test/apis/iam/v2beta/policies --insecure`
(Logged in as …
=> [part of 832]/add db id to statements

components/authz-service/storage/postgres/migration/sql/57_use_project_db_id_in_references_of_policies.up.sql, components/authz-service/storage/postgres/migration/sql/README.md, components/authz-service/storage/v2/postgres/postgres.go, components/authz-service/storage/v2/postgres/postgres_test.go
`iam_policies` used to reference `iam_projects` using the latter's `id` column; now it's `db_id`.
Note: this does nothing else; the nearby references that need to be fixed are different subtasks.
~⚠️ branched off of #855; needs to be rebased when that is merged. 👉 [This is what changed over @blakestier's PR](https://github.com/chef/automate/compare/47e9a01e030347b30ab25db31288443027e846cb...sr/issue-832/db_id_for_projects_and_policies)~ ✔️ rebased
Tests pass 😄 References are different.
NA
- #832 
- #855
=> [part of #832] db_id for projects and policies

components/authz-service/server/v2/project.go, components/authz-service/server/v2/rules_property_test.go
This is exploratory code to attempt to measure the size of GRPC messages from ListRules.
I started by adding `dumpRules` into rules_property_test.go, an imperfect place to do it, but it provides the convenience of being able to show output to the console during a test run. I have the request object there, when in fact I want to measure the size of a response object. So I just interpolated the couple missing fields, `Deleted` and `Status`. That essentially provides all the "user facing" fields of the response object. Took a little bit of figuring out on how to size various things in Go. There is a handy `SizeOf` method in the `unsafe` library but that does not really do what one might think; it returns the size of the container rather than its contents, so that was only useful for certain …
=> Gopter and GRPC capacity diagnostics

components/automate-deployment/pkg/converge/compiler.go, components/automate-deployment/pkg/converge/stop_mitigation.go
If deployment service takes down something core like postgres, it first
has to take down all the services that connect to it. Those services
aren't brought up until the end of the run converge part, which was
causing automate-pg-gateway to come up really late in the game. This in
turn causes a bunch of healt checks to fail and causes general slowness
as hab has to service a bunch of services that will just keep dying.
This change will reload any stopped services due to the mitigation when
they are required.
I left the RestartServices at the end. It just call `hab svc start`. I'm
not sure it is needed as we run through the list of services in a
topologically sorted order.
=> Bring up services in the order they are required during mitigation

components/event-feed-service/habitat/hooks/run
We need to add es-gateway to NOPROXY. 
We've discussed a few other solutions to this in the past
- Always adding the system IP to our default no-proxy configuration
- Always adding the system IP to our no-proxy configuration regardless of user config
- Only talking to es-gateway over localhost
But here I have just continued the existing pattern.
=> [event-feed-service] Add es-gateway to NOPROXY

scripts/changed_components.rb, scripts/verify_build.sh
I originally put this in verify_build because I wanted the buildkite
annotation to be different. But, the problem with that implementation
is using file-glob ordering is completely wrong and
changed_components.rb is also the part of the system that produces the
correct dependency-based ordering.
=> [CI] Move BUILD_ALL into changed_components.rb

lib/cereal/backend/backend.go, lib/cereal/postgres/postgres.go, lib/cereal/workflow_scheduler.go
We had two cases with some TODOs around error handling in this
code.
1. We now attempt to disable scheduled workflows with invalid
recurrence rules.
2. I've attempted to comment the existing code to indicate why we
think the current error & sleep logic is correct. Namely, we only
sleep when we think that not sleeping would result in an immediate
retry of the same schedule workflow.
=> [lib/cereal] Handle error cases in scheduler code

components/automate-cli/cmd/chef-automate/airgap.go, components/automate-deployment/pkg/airgap/bundle_creator.go, components/automate-deployment/pkg/airgap/install_bundle_test.go
We've been seeing an increased rate of failed downloads from the
Habitat depot in CI. This PR adds retries with exponential backoff to
the downloads of both Habitat artifacts and keys.
Note, we don't retry the hab binary downloads are other API calls.
=> [automate-cli] Retry hart and key downloads in bundle create

components/automate-deployment/pkg/airgap/bundle_creator.go
If we reuse the io.Writer, then we create a corrupt package, thus the
retries have to happen outside the creation of the io.Writer.
=> [automate-cli] Ensure same writer isn't reused across retries

components/automate-chef-io/content/docs/configuration.md, components/automate-chef-io/content/docs/install.md, components/automate-chef-io/content/docs/log-management.md, components/automate-chef-io/content/docs/telemetry.md, components/automate-chef-io/content/docs/upgrade.md
Document the current tested state of configuring external data stores with Automate.
Fixes #846
=> Document how to configure external data stores.

components/automate-gateway/handler/applications.go
Currently every **"conversion"** done by `proto. CallDomainService()` does a multi conversion from:
```
Protobuf => JSON => Protobuf
```
The icing of the cake is that **[grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway)** does already a conversion from `JSON => Protobuf`, and therefore, we end up with:
```
JSON => Protobuf => JSON => Protobuf
```
Reduction of complexity and increase the speed of RPC functions in the gateway (the ones that belong to the `applications-service`) by avoiding unnecessary conversions.
List of functions:
N/A - All the code should compile and integrations tests should pass as before.
N/A - **Chore**
=> Manual conversion of protobufs in gateway

components/applications-service/pkg/storage/client.go, components/applications-service/pkg/storage/postgres/service_internal_test.go, components/applications-service/pkg/storage/postgres/services.go
Creates a new `composedService` struct to separating the `storage` go
package that holds **only the client interface and its structs** that define
what a storage client should look like, the actual `postgres` implementation 
should NOT have a dependency on `db:"XYZ"` tags.
The `storage` and `postgres` go packages are decoupled.
N/A - Everything should work after this change is merged, build and run tests as usual.
N/A
=> Separate storage client and postgres implementation

integration/base.sh, integration/helpers/build.sh, integration/helpers/testing.sh, integration/tests/airgap_upgrade.sh, integration/tests/backup_repo_permissions.sh, integration/tests/deep_upgrade.sh, integration/tests/migrate_upgrade.sh, integration/tests/upgrade_acceptance_master.sh, integration/tests/upgrade_current_acceptance.sh, integration/tests/upgrade_current_master.sh
This makes a new variable:
`test_diagnostics_pre_upgrade_filters`
which should be used on any diagnostics run on an _old_ version.  The
existing variable
`test_diagnostics_filters`
should be applied to *every* invocation of `diagnostics run`.
I've also removed some uses of skip-for-deep-upgrades that didn't make
sense to me. The tests should show if they are needed.
Finally, it isn't clear to me that we are properly managing the
`~remove-this-tag-after-merge` tag anymore.
=> [integration] Allow users to specify filters that are always used.

.expeditor/config.yml
There is no "complete" event, but we want to unlock the staging area
anytime our build pipeline passes, fails, or is canceled.
Signed-off-by: Tom Duffield <tom@chef.io>
=> Unlock the staging area when the habitat/build pipeline completes

lib/cereal/postgres/sql_schema.go, lib/cereal/postgres/task_cleaner.go, tools/cereal-scaffold/main.go
Currently, the workflow results table grows without bound. This
imposes a limit of 10,000 rows that we attempt to enforce
periodically.
To avoid having to think too hard about the implications of DELETE and
our default transaction level, we take a postgresql advisory lock.
Note that we "over delete" to try to avoid deleting on every
interation once we hit the limit.
=> [cereal] Periodically cleanup workflow results

lib/cereal/backend/backend.go, lib/cereal/cereal.go, lib/cereal/postgres/postgres.go
This removes the unused UpdateWorkflowScheduleByID function. While
here, it also takes care of a TODO to correctly return a not-found
error when attempting to update a non-existent workflow.
=> [lib/cereal] Remove unused UpdateWorkflowScheduleByID

components/automate-cli/pkg/diagnostics/context.go, components/automate-deployment/pkg/server/api_token.go, components/automate-deployment/pkg/server/api_token_test.go
Also:
* diagnostics/context: don't swallow that error
Co-authored-by: Blake Johnson <bstier@chef.io>
Signed-off-by: Stephan Renatus <srenatus@chef.io>
=> deployment-service: try to create admin token using iam v2 if v1 fails

components/automate-deployment/pkg/server/api_token.go, components/automate-deployment/pkg/server/api_token_test.go
This makes me think that we're creating one v1 policy per run of
diagnostics, and never clean them up.
At least in IAM v2, we won't do that, but graciously ignore
"AlreadyExists" errors.
Follow-up to the discussion of #946.
=> diagnostics: don't freak out if admin token v2 policy already exists

components/automate-deployment/pkg/server/api_token.go, components/automate-deployment/pkg/server/api_token_test.go
For reasons that might have disappeared from everyone's memory, the d-s
code was also what drove `chef-automate admin-token`. So, I've removed
any "diagnostics"-related wording from the V2 policy data.
Note that `chef-automate admin-token` first checks if the system uses
v2, so that code path we've recently added for diagnostics should NOT be
executed in that scenario. It still felt cleaner to remove the
"diagnostics" words.
Furthermore, this changes `GenerateAdminToken` so that in the
diagnostics+iam-v2 use case, it can be run twice: once before the
upgrade, once after; without triggering any policy conflicts.
Before this commit, the second run would have not failed completely, but
the already existing policy would not have referenced the proper token
ID. Now, the v2 code is analogous to …
=> deployment-service: reconcile this code with automate-cli usage

components/automate-ui/src/app/pages/+compliance/+reporting/reporting-searchbar/reporting-searchbar.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/reporting-searchbar/reporting-searchbar.component.scss, components/automate-ui/src/app/pages/+compliance/+reporting/reporting-searchbar/reporting-searchbar.component.ts, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.ts
In an effort to drive parity across the app, we'd like to make the compliance search bar be the same as the client runs search bar.
Compliance search bar is the same format as the client runs.
https://github.com/chef/automate/issues/405
=> Implemented new compliance searchbar

components/authz-service/storage/postgres/datamigration/sql/04_v2_set_projects_default.up.sql, components/authz-service/storage/postgres/migration/sql/59_use_db_id_as_primary_key_in_iam_projects.up.sql, components/authz-service/storage/postgres/migration/sql/60_use_db_id_as_primary_key_in_iam_statement_projects.up.sql, components/authz-service/storage/postgres/migration/sql/README.md, components/authz-service/storage/v2/postgres/postgres_test.go, components/authz-service/testhelpers/testhelpers.go
Last step of #832's subtask for `iam_projects` references. ~~Branched-off of #905, and depends on that to go in first.~~
Also rolled in updating iam_statement_projects to use  iam_statements db_id as well.
- #832 
- #905
=> [part of #832] flip primary key for iam projects

.expeditor/config.yml, .expeditor/push-git-tag.sh
Having tags for each release makes it easier to run things like `git
tag --contains SHA` to determine what versions might have a particular
bug or fix.
I've already pushed tags for the previous versions that were released
from this repository:
20190415203801
20190422213145
20190501153509
20190506101326
20190513175357
20190605190944
20190610211245
20190617144820
20190628200755
20190711110747
Right now these are regular tags; however, we may consider changing
them to annotated tags in the future.
=> [CI] Tag git repository on promotion to current

lib/cereal/backend/backend.go, lib/cereal/cereal.go, lib/cereal/postgres/postgres.go, lib/cereal/postgres/sql_schema.go
- Remove the tasks_abandoned workflow event that is no longer used.
- Remove WorkflowEvent.InstanceID
- Remove workflowInstanceImpl.instanceID
- Comment on ID in backend.Schedule
- Cleanup incorrect comments in SQL
- Reformat some of our SQL string constants
=> [lib/cereal] Cleanup unused variables and comments

components/automate-cli/pkg/dev/hab/verify.go, integration/helpers/deployment.sh
This changes the `chef-automate dev verify-packages` such that:
- Missing FILES files is now a handled error, allowing other packages
to be checked.
- The pakcage name is first in the output, making it a little easier
to parse.
With these changes, I've replaced the old shell function that we have
to detect broken packages in the deep_upgrade tests and replaced it
with our verify-packages command. This will hopefully help catch a
broader set of package corruption issues during those tests. [1]
I've also refactored the VerifyError struct into multiple structs to
make it more immediately clear which kind of error you are hoping to
return.
[1] The package corruption issues in those tests are
unavoidable. Those tests exercise upgrades from old versions of
deployment-service. Older versions of …
=> Update `chef-automate dev verify-packages` for use in CI

lib/cereal/backend/backend.go, lib/cereal/cereal.go, lib/cereal/integration/cancel_workflow_test.go, lib/cereal/integration/workflow_postgres_test.go, lib/cereal/postgres/postgres.go, lib/cereal/postgres/postgres_test.go, lib/cereal/postgres/sql_schema.go, lib/cereal/postgres/task_pinger.go
- Added a cancel workflow signal. Workflows can decide how to handle
this
- If a workflow finishes when outstanding tasks, the context for those
tasks will be canceled the next time they try to ping.
- I changed the task ping interval to 15 seconds so canceled tasks exit
earlier
=> [cereal] Wire up workflow cancelation

lib/cereal/cereal.go, lib/cereal/integration/workflow_error_test.go
- Return, thus canceling the transaction and rolling back the workflow
on Enqueue Task failures.
- Fail rather than Complete workflow on jsonify error
- Fail workflow when EnqueueTask and Complete have been called in the
same workflow step.
I wrote tests for 2 out of 3 of these cases. We really need a good way
to inject postgresql failures.
=> [lib/cereal] Handle a few more TODOs

.expeditor/buildkite/cypress.sh, .gitignore, e2e/cypress.json, e2e/cypress/fixtures/converge/avengers1.json, e2e/cypress/fixtures/converge/avengers2.json, e2e/cypress/fixtures/converge/xmen1.json, e2e/cypress/fixtures/converge/xmen2.json, e2e/cypress/index.d.ts, e2e/cypress/integration/api/iam/01_projects_api.spec.ts, e2e/cypress/support/commands.ts, integration/tests/cypress_e2e.sh, terraform/test-environments/scenarios/performance_test_single_local_inplace_upgrade.tf, terraform/test-environments/scenarios/single_local_fresh_install.tf, terraform/test-environments/scenarios/single_local_iamv2_fresh_install.tf, terraform/test-environments/scenarios/single_local_iamv2_inplace_upgrade.tf, terraform/test-environments/scenarios/single_local_iamv2p1_fresh_install.tf, terraform/test-environments/scenarios/single_local_iamv2p1_inplace_upgrade.tf
We've been using inspec for a while to meet our API integration test needs, but it is not always the most ideal tool for such tests.
Since we've had a good experience using Cypress to test the UI so far, we decided to try out Cypress for our API integration test needs, starting with testing out the flow for applying project rules to nodes.
*no longer* be filtered by the deleted rule's project 
TODO:
- run cypress locally by [following these steps](https://github.com/chef/automate/blob/master/e2e/README.md#running-cypress-locally)
=> [automate-867] apply rules integration test

lib/cereal/backend/backend.go, lib/cereal/cereal.go, lib/cereal/postgres/postgres.go
The risk with this error return location and other similar locations
is that by simply returning the error, we will be aborting the
transaction, effectively placing the same workflow event on the queue.
This means that if the error is _not_ a transient error, we are
completely stuck.
Here, I've handled at least one non-transient error. Any other error
will continue to be retries. I think that some of this might be made
easier if we moved away from QueryRowContext since then Scan errors
and other errors wouldn't be intermingled.
=> [lib/cereal] Ignore missing task results

lib/cereal/cereal.go, lib/cereal/cereal_test.go
The processWorkflow event loop has a number of places where errors can
occur. In many cases, the most likely cause of the error is some
transient network problem. In these cases, logging the error, and
retrying may make sense.
Unfortunately, for the case of an unknown workflow event, no amount of
retrying will help. The event types are part of our source code, if we
don't know the event now, we won't know it 10 milliseconds from now
either.
This is especially problematic because it is likely that we'll
continue to select this same workflow event, stopping work on all
other workflows.
This PR attempts to address the problem by temporarily marking such
workflows as "wayward" and removing them from the list of workflows to
select. After some timeout, we start processing them again, in the …
=> [lib/cereal] Temporarily pause processing of wayward workflows

components/compliance-service/profiles/db/store.go
Changing the upload of profiles logging from "Info" level to "Debug". This prevents the logs from filling up each time the compliance-service is restarted. 
Only one line is changed.
=> Hiding excess logging from info

components/automate-deployment/pkg/server/server.go, components/automate-pg-gateway/habitat/config/_a2_platform_external_pg_root_ca.crt
deployment-service was using platform config to get a postgres
connection. For services, this sets up everything to connect to internal
or external postgres correctly. deployment-service doesn't have all the
bits to make that work. I've added a hack to allow it to keep using the
platform config library and correctly get the postgres connection
information.
=> Teach deployment-service how to backup ssl external pg

.studio/automate-gateway, .studio/common, .studio/compliance-service, .studio/debugging, .studio/golang, .studio/secrets-service, scripts/repo_health.sh
- Enables all of shellcheck's "error" level linters for the studio. 
- Fixes SC2068 which was required to enable error level linters
- Fixes SC2155 which looked pretty easy to solve
- Fix a few miscellaneous issues that were in the vicinity of the other issues.
- In files otherwise touched by this change, remove unnecessary `;`s
=> Start linting our studio code

.studio/automate-gateway
I accidentally added an extra newline here when mechanically fixing
various lint violations.
=> Fix typo that snuck in during lint fixes

components/automate-deployment/habitat/plan.sh, integration/run_test, integration/services/common.sh, integration/services/ha_backend/init.sh, integration/services/ha_backend/setup.sh, integration/tests/ha_data_services.sh, lib/platform/pg/exporter.go, lib/platform/pg/exporter_test.go
The HA backend cluster is using postgres 11. The 9.6 tools do not like
this and error out with a version mismatch.
=> Use the postgres11 client tools for backup/restore

api/config/shared/global.go, api/config/shared/global_test.go
Verify config settings for external postgres and elasticsearch.
If external elasticsearch is configured
* basic_auth is also configured,
* either the root cert or a root cert file is specified in the config, and
* elasticsearch node urls are either all http or https.
If external postgres is configured with auth, password auth is configured.
Signed-off-by: Yvonne Lam <yvonne@chef.io>
=> [deployment] Verify config settings for external data stores

components/chef-ui-library/package-lock.json, components/chef-ui-library/package.json, components/chef-ui-library/src/app.tsx, components/chef-ui-library/src/atoms/chef-checkbox/chef-checkbox.tsx, components/chef-ui-library/src/molecules/chef-control-menu/chef-control-menu.tsx, components/chef-ui-library/src/molecules/chef-select/chef-select.tsx
This PR upgrades some outdated `chef-ui-library` deps to their latest versions to stay up-to-date and help address `npm audit` warnings. Deps with breaking changes were left alone and will be addressed in separate PRs.
Next steps:
- Upgrade to the 1.0 releases of Stencil
- https://blog.ionicframework.com/announcing-stencil-one-beta/
- [1.0 breaking changes upgrade guide](https://github.com/ionic-team/stencil/blob/7b7d0725618b2a17181389096ac60de08e1c766f/BREAKING_CHANGES.md)
- Upgrade Jest + Puppeteer
- Requires Stencil upgrade
**Before:**
```
$ npm outdated
Package                   Current   Wanted   Latest  Location
@stencil/core              0.17.0   0.17.2    1.1.7  chef-ui-library
@stencil/redux              0.0.4    0.0.4    0.1.1  chef-ui-library
@stencil/router             0.2.1 …
```
=> Upgrade minor ui-lib dependencies

components/automate-ui/e2e/admin.e2e-spec.ts, components/automate-ui/src/app/app-routing.module.ts, components/automate-ui/src/app/app.module.ts, components/automate-ui/src/app/components/delete-object-modal/delete-object-modal.component.html, components/automate-ui/src/app/entities/rules/rule.actions.ts, components/automate-ui/src/app/entities/rules/rule.effects.ts, components/automate-ui/src/app/entities/rules/rule.model.ts, components/automate-ui/src/app/entities/rules/rule.reducer.ts, components/automate-ui/src/app/entities/rules/rule.requests.ts, components/automate-ui/src/app/entities/rules/rule.selectors.ts, components/automate-ui/src/app/ngrx.effects.ts, components/automate-ui/src/app/ngrx.reducers.ts, components/automate-ui/src/app/pages/project/details/project-details.component.html, components/automate-ui/src/app/pages/project/details/project-details.component.scss, components/automate-ui/src/app/pages/project/details/project-details.component.spec.ts, components/automate-ui/src/app/pages/project/details/project-details.component.ts, components/automate-ui/src/app/pages/project/project.module.ts, components/automate-ui/src/app/pages/project/rules/project-rules.component.html, components/automate-ui/src/app/pages/project/rules/project-rules.component.scss, components/automate-ui/src/app/pages/project/rules/project-rules.component.spec.ts, components/automate-ui/src/app/pages/project/rules/project-rules.component.ts, components/automate-ui/src/app/ui.component.ts, components/chef-ui-library/src/atoms/chef-button/chef-button.tsx, components/chef-ui-library/src/templates/chef-page/chef-page.tsx
**A2-825** makes the visual updates to the projects detail pages. Most data should be mocked until the Auth team can come back and connect it to the backend.
Please leverage the already implemented designs of the full-page designs (A2-827) when adding members to a policy.(Ideally, this should re-use the same component as the create page (A2-826), with a few conditionals or variables to allow it to cover both create and update cases.)
**A2-826** This task makes the visual updates to the project create ingest rule page. Most data should be mocked until the Auth team can come back and connect it to the backend.
**Separate story for the chef-select boxes styling** https://chefio.atlassian.net/browse/A2-826
**PROJECT DETAILS PAGE**:
Empty State
When no ingest rules exist.. display the empty …
=> UI-267 UI-268 Project Rules Signed-Off-By: Tara Black<tblack@chef.io>

.expeditor/verify.pipeline.yml, .gitignore, e2e/cypress/integration/api/iam/01_projects_api.spec.ts, e2e/cypress/integration/ui/01_login.spec.ts, e2e/cypress/integration/ui/02_global_filter.spec.ts, e2e/cypress/integration/ui/compliance/01_ssh_scan_job.spec.ts, e2e/cypress/integration/ui/settings/01_user_mgmt.spec.ts, e2e/cypress/integration/ui/settings/02_team_mgmt.spec.ts, e2e/cypress/support/commands.ts, e2e/package-lock.json, e2e/package.json, e2e/tslint.json
This is a follow-on to the recent conversion of e2e Cypress tests from
JavaScript to TypeScript:
1. Instruments the build to lint all-the-things and fail the build if lint fails.
2. Fix the outstanding 460 lint issues (!) from the initial port.
3. Drive-by: put package-lock.json under source control so that, as with our other UI code,
prevents version inconsistencies between developers.
You can now lint e2e files on the command-line:
```
cd e2e
npm install
npm run lint
```
https://github.com/chef/automate/pull/837
=> Add linting for nascent e2e typescript

integration/base.sh, integration/helpers/build.sh, scripts/verify_build.sh
do_build was messed up
- the build changed components script was using the wrong ruby
- we need to be careful about the umasks we use when calling hab pkg install
=> Fix integration tests to run locally

components/chef-ui-library/src/atoms/chef-clipboard/chef-clipboard.tsx, components/chef-ui-library/src/atoms/chef-option/chef-option.tsx, components/chef-ui-library/src/molecules/chef-select/chef-select.tsx
This PR fixes any remaining deprecation warnings in `chef-ui-library` build output:
This code needs to be updated in order to upgrade to Stencil 1.0: [change doc](https://github.com/ionic-team/stencil/blob/7b7d0725618b2a17181389096ac60de08e1c766f/BREAKING_CHANGES.md#all-void-methods-return-promise-right-now-method-void-is-valid)
> Until Stencil 1.0, public component methods decorated with @Method() could only return Promise<...> or void. Now, only the async methods are supported, meaning that retuning void is not valid.
Requiring all public methods to be async was problematic in `chef-option` since `chef-select`'s `render`+`hostData` methods can only execute synchronously but are calling some `chef-option` methods that must now be executed asynchronously. This person ran into [the same …
=> Fix ui-lib deprecation warnings

tools/danger-delete-ds-certs/main.go
As outlined in
https://discourse.chef.io/t/important-chef-automate-2-internal-certificate-expiration/15624
users may soon be approaching the expiration date of their internal
certificates. For those on most recent versions, the
deployment-service will attempt to regenerate the certificates
automatically, and the chef-automate tool provides tooling to do this
manually.
However, for users on older versions this is not the case.
For versions 20181020020209 or higher, the following alternate
strategy should work:
rm /hab/svc/deployment-service/data/*.crt  /hab/svc/deployment-service/data/*.key /hab/svc/deployment-service/data/*.crl
hab svc status
kill "$DEPLOYMENT_SERVICE_PID"
For versions older than 20181020020209, this will not work. Rather,
the tooling added in this PR will be required:
# …
=> tools: Add danger-delete-ds-certs for emergency cert regen

components/authz-service/server/v2/policy.go, components/authz-service/storage/errors.go, components/authz-service/storage/errors_test.go, components/authz-service/storage/postgres/datamigration/sql/01_v2_data_migrations.up.sql, components/authz-service/storage/postgres/datamigration/sql/02_v2_rename_all_actions.up.sql, components/authz-service/storage/postgres/migration/sql/61_use_role_db_id_in_iam_statements.up.sql, components/authz-service/storage/postgres/migration/sql/README.md, components/authz-service/storage/postgres/postgres.go, components/authz-service/storage/v2/postgres/postgres_test.go, components/authz-service/storage/v2/statement.go, components/automate-cli/pkg/diagnostics/integration/iam_v2.go, inspec/a2-iam-v2-integration/controls/iam_v2.rb
Updated the `iam_statements` table to have a foreign key to role's via `db_id`. Also, since things are now properly relational, if you delete a role, policies will now remove the role from their statement. If removing the role would result in the statement having no role or actions, then the statement is removed. If that results in an empty custom policy, the policy is removed.
I also added a `insertTestStatement` helper and updated the postgres tests to use it.
**Also found and fixed a few bugs:**
* Resources and actions in the iam_statements didn't have `NOT NULL` constraints and could have resulted in null values. I've populated any NULLs with `'{}'` and added `NOT NULL` constraints.
* Fixed a bug where errors on db transactions would cause an infinite loop and crash authz-service.
``` …
```
=> [automate-832] Use role db_id in iam_statements (final part)

components/automate-ui/src/app/entities/jobs/job.requests.ts, components/automate-ui/src/app/entities/managers/manager.requests.ts
Just adding a couple telemetry calls to track:
- node integration type
- scan job creation data
telemetry calls for the two above mentioned items
create node integration, see telemetry call in dev tools
create scan job, see telemetry call in dev tools
=> add telemetry for node integration type and scan job payload

components/automate-ui/src/app/page-components/services-sidebar/services-sidebar.component.ts
I found an unrelated bug when investigating https://github.com/chef/automate/issues/972
We used the 12 hour format `h` in our time wizard time format when it should have been 24 hour `H`. So anything that happened in the afternoon/evening UTC time would show up with the wrong time.
Wait until 13:00 or later UTC. `start_all_services` in the studio, then run `applications_populate_database`. Navigate to the applications page, then hover over the text that's like `Since the service was loaded, 45 minutes 47 seconds ago`, and you will see it says the wrong hour. In my case, it should have said `21` for the hour but it said `09` (because `21 - 12 == 9`). 
Then build automate-ui, wait a bit for it to load and refresh the page, it will say the correct time. …
=> Use correct format strings for 24h instead of 12h

components/authz-service/storage/postgres/migration/sql/62_add_not_null_constraints.up.sql, components/authz-service/storage/postgres/migration/sql/README.md, components/authz-service/storage/v2/postgres/postgres.go, components/authz-service/storage/v2/postgres/postgres_test.go
Follow up to https://github.com/chef/automate/pull/942. Let's update all the places we are missing the `NOT NULL` constraint and delete any data that is invalid that might have snuck in.
Also, add trigger to clean up any statements that are projectless and consequently any custom policies that are statementless.
Lastly, have both triggers (project and role deletion) properly update notify_policy_change since policies changed as a result of the triggers.
=> Add NOT NULL constraints in all the places we are missing it and delete / update any invalid data

components/automate-ui/src/app/components/sidebar-no-shade/sidebar-no-shade.component.scss, components/automate-ui/src/app/components/sidebar/sidebar.component.scss, components/automate-ui/src/app/page-components/navbar/navbar.component.scss, components/automate-ui/src/app/page-components/server-org-filter-sidebar/server-org-filter-sidebar.component.scss
**Overview**
To increase the ease on human eyeballs we want to reduce the number of shadows used in Automate. This task also prepares for the removal of the background gray color on our pages.
**Design Details**
Remove the shadow from the top nav and add a border-bottom: 1px solid #dfe3e5
Remove the shadow from the left nav and add a border-right: 1px solid #dfe3e5
Set the background color of the left-nav to #fff
screenshots of changes
https://github.com/chef/automate/issues/680
=> Remove shadow and add border to top-nav and left nav

components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.ts, components/compliance-service/api/reporting/server/server.go, components/compliance-service/api/tests/07_suggestions_spec.rb, components/compliance-service/api/tests/07_suggestions_w_filters_spec.rb
also modified the field for node name from 'Node' to
to 'Node Name' for parity with client runs and clarity!
- compliance suggestions returns 100 results
- node -> node name
```
build components/compliance-service
chef_load_compliance_scans (more than 10 nodes)
use search bar to search for nodes by name, ensure it says "Node Name", ensure more than 10 results are returned
```
https://github.com/chef/automate/issues/737
=> bump suggestions results in compliance from 10 to 100

components/automate-deployment/pkg/a1upgrade/a1commands.go, integration/tests/a1migration.sh
A1 migration will fail for people with /bin linked to /usr/bin
because we binlink chef-server-ctl into /bin before the migration is
complete. This prevents us from calling the correct chef-server-ctl.
I hope this commit fixes that
=> Use full path to chef-server-ctl during migration

components/automate-deployment/pkg/a1upgrade/a1commands.go, components/automate-deployment/pkg/client/deployer.go
The a1upgrade also calls chef-server-ctl show-secret which needs to
come from the old chef-server-ctl.
An alternative would be to ensure we don't do the binlinking at the
wrong time.
=> a1upgrade: fix more references to chef-server-ctl

.expeditor/verify_private.pipeline.yml, scripts/verify_build.sh
Right now we use the linux executor. We've had semi-regular problems
with the linux executor not giving us the isolation we require during
builds.
Most recently, we've hit a problem where we see artifacts from other
builds in our results folder. We have not fully investigated this
problem. However, our suspicion is that what we are seeing is that
canceled builds are not tearing down the hab-studio, leading to the
builds in those studios continuing to run, and later writing into a
results folder now in use by another build.
We have this suspicion because we've seen this before (private repo,
sorry):
chef/a2@d481491
there we added the --tty flag to influence how signals would interact
with the build.
We could continue down that road. Instead, this PR moves us to the
docker executor as a way …
=> ci: try verify_build in docker for better isolation

components/authz-service/server/v2/policy.go, components/authz-service/storage/errors.go, components/authz-service/storage/errors_test.go, components/authz-service/storage/postgres/datamigration/sql/01_v2_data_migrations.up.sql, components/authz-service/storage/postgres/datamigration/sql/02_v2_rename_all_actions.up.sql, components/authz-service/storage/postgres/migration/sql/63_make_db_id_lookup_functions_strict.up.sql, components/authz-service/storage/postgres/migration/sql/README.md, components/authz-service/storage/postgres/postgres.go, components/authz-service/storage/v2/postgres/postgres.go, components/authz-service/storage/v2/postgres/postgres_test.go
The helper methods are strict now. There's no customer impact besides a bit of warm, fuzzy feeling for our developers knowing their database contents are consistent.
Also refactored some of the error handling, using the foreign key exception to signal missing roles or projects in policy creations etc.
See tests pass.
- #832
=> authz-service/sql: make helper methods strict

components/authz-service/server/v2/system.go, components/authz-service/storage/postgres/migration/sql/64_drop_uuid_of_iam_members.up.sql, components/authz-service/storage/postgres/migration/sql/README.md, components/authz-service/storage/v2/member.go, components/authz-service/storage/v2/postgres/postgres.go, components/authz-service/storage/v2/postgres/postgres_test.go
~Branched off of #1055, use [this view to review](https://github.com/chef/automate/compare/385d0b9fb7852bfaa3aab78ef55b76f8c3571483...sr/cleanup/remove-member-id-column), please.~ ✔️ other PR merged, this one rebased
Since members are now referenced by their `db_id`, we no longer need a UUID for a member. Their names are unique as well. This change drops that column, and deals with the fallout.
See tests pass.
- #832 
- #1055
=> cleanup: remove member id column

components/automate-ui/src/app/pages/+compliance/shared/reporting/suggestions.service.spec.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/suggestions.service.ts
in https://github.com/chef/automate/pull/1065 we did some work to bump the results returned from the compliance api from 10 -> 100, which worked beautifully.
but when testing the change later, i noticed i was only getting 25 results in the ui, despite the api returning 100.
this fixes that!
100 (or as many as available if less than 100) suggestion results returned
```
load 100 compliance nodes (or more than 25)
suggest on node name, expect to see more than 25 nodes
```
=> ensure ui for compliance suggestions is displaying all 100 results

components/automate-ui/src/app/pages/integrations/detail/integrations-detail.component.html, components/automate-ui/src/app/pages/integrations/detail/integrations-detail.component.ts
As noted in https://github.com/chef/automate/issues/735, the Add Nodes button only belongs on the Automate manager details page, as the functionality that button directs to is for adding nodes to the automate node manager.
no add nodes button on automate manager details page
build ui
add an aws, azure. or gcp integration
view details pages for new manager page and automate manager page
only see add nodes button on automate manager page
https://github.com/chef/automate/issues/735
=> only include add nodes button on node integ. detail page for automate mgr

components/compliance-service/api/tests/test_ingest_to_mgr_conn.rb, components/nodemanager-service/api/nodes/server/server.go
Part of the node read code in nodemanager service parses the node target config. Ingested nodes (nodes that were not manually added via node integration or node add) do not have a target config, and an oversight in the code resulted in the service exploding when trying to access a field in the nonexistent target config.
Able to read nodes that were only ingested.
build components/nodemanager-service
ingest some nodes
read ingested nodes
https://github.com/chef/automate/issues/943
=> fix node read for nodes with nil target config

.expeditor/verify_private.pipeline.yml, scripts/verify_build.sh
This moves us back to the linux executor with a docker based studio.
We are moving back because of
https://github.com/buildkite-plugins/docker-buildkite-plugin/issues/127
which is still present in the build that we have.
=> ci: move back to docker-based studio, now with labels

.expeditor/update-compliance-profiles.sh, .expeditor/update-inspec-version.sh
Habitat has multiple architecture targets, all of which will be
promoted on release.  We, however, only care about x86_64-linux
packages.
=> ci: ignore promotion of x86_64-linux-kernel2 packages

e2e/cypress/integration/api/iam/01_projects_api.spec.ts
Includes a small simplification in waitForNodes.
```
1) projects API applying project rules "before all" hook for "new rules get applied to nodes":
AssertionError: expected [] to have a length of 4 but got 0
```
This change should make ☝️ a little less likely. No magic here, just trying longer.
=> e2e/cypress/iam: retry more often

components/authz-service/engine/opa/opa.go, components/authz-service/server/v2/policy.go, components/authz-service/server/v2/project.go, components/authz-service/storage/errors.go, components/authz-service/storage/errors_test.go, components/authz-service/storage/postgres/postgres.go, components/authz-service/storage/v2/postgres/postgres.go, components/authz-service/storage/v2/postgres/postgres_test.go, components/automate-deployment/pkg/certauthority/certauthority.go, components/automate-deployment/pkg/certauthority/certauthority_test.go, components/automate-deployment/pkg/manifest/client/http.go, components/automate-deployment/pkg/manifest/client/http_test.go, components/automate-deployment/pkg/manifest/client/path.go, components/automate-deployment/pkg/manifest/client/path_test.go, components/automate-deployment/pkg/manifest/errors.go, components/automate-deployment/pkg/manifest/parser/parser.go, components/automate-deployment/pkg/manifest/parser/parser_test.go, components/automate-deployment/pkg/server/backup.go, components/automate-deployment/pkg/server/server.go, components/local-user-service/password/password.go
✅ Fixes the return status of Create{Policy, Role} requests containing a project/role which do not exist. These will all now return InvalidArgument, which is translated to HTTP 400.
✅ Ensures we follow the naming convention for error constants vs error types.
- `start_all_services`, `rebuild components/authz-service`
- create project "foo": `chef-automate dev grpcurl authz-service --  -d "$(jq -n '{id: "foo", name: "Foo" }')" chef.automate.domain.authz.v2.Projects.CreateProject`
- create a rule referencing projects "foo" and "bar":
```
[41][default:/src:130]# chef-automate dev grpcurl authz-service --  -d "$(jq -n '{id: "foo2", name: "Foo", projects: ["foo", "bar"], actions: ["svc:type:action"]}')" chef.automate.domain.authz.v2.Policies.CreateRole
ERROR:
Code: InvalidArgument
Message: …
```
=> authz-service: cleanup foreign key error status

components/automate-ui/src/app/page-components/client-runs-search-bar/client-runs-search-bar.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/reporting-searchbar/reporting-searchbar.component.html
The browser has a built-in autocomplete feature that displays over the Automate suggestions. This fix removes the browser built-in autocomplete feature. 
Thank you @scottopherson for pointing out the fix for this. 
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion
The browser's built-in auto-complete feature is not displayed. 
1. `start_all_services`
1. Open https://a2-dev.test/client-runs and click in the search bar. There should be built-in auto-complete suggestion showing up like the image below
1. `build components/automate-ui`
1. Refresh https://a2-dev.test/client-runs and the suggestion should not appear.
=> Removing the browser's built-in autocomplete feature

components/automate-ui/src/app/entities/rules/rule.model.ts, components/automate-ui/src/app/entities/rules/rule.reducer.ts, components/automate-ui/src/app/entities/rules/rule.requests.ts, components/automate-ui/src/app/pages/project/details/project-details.component.html, components/automate-ui/src/app/pages/project/details/project-details.component.scss, components/automate-ui/src/app/pages/project/details/project-details.component.spec.ts, components/automate-ui/src/app/pages/project/details/project-details.component.ts, components/automate-ui/src/app/pages/project/rules/project-rules.component.html, components/automate-ui/src/app/pages/project/rules/project-rules.component.scss, components/automate-ui/src/app/pages/project/rules/project-rules.component.spec.ts, components/automate-ui/src/app/pages/project/rules/project-rules.component.ts
This is a follow-on to PR-736, implementing the suggestions/corrections remaining from that PR, plus other issues uncovered.
_Please follow the commits to understand specific changes._
Broadly, this PR covers some architectural changes and some behavioral changes.
The former are covered with my review comments and commit comments; the latter are summarized here:
1. Add an asterisk on name and type indicating required. 🤔 Don't we need to say somewhere `(*) Indicates required fields` ??
2. Tightened spacing per UX design between labels and input boxes.
3. Change the label in the error pop-up to match the `Rule Name` label.
4. Fix the width of the error pop-up to match the `Rule Name` field.
5. Increase spacing per UX design between fields.
6. Add an error pop-up for the `Resource Type` …
=> Project details and rules completion

Gopkg.lock, Gopkg.toml, vendor/github.com/grpc-ecosystem/grpc-gateway/CHANGELOG.md, vendor/github.com/grpc-ecosystem/grpc-gateway/Makefile, vendor/github.com/grpc-ecosystem/grpc-gateway/examples/gateway/handlers.go, vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/errors.go
⚠️ This time, we've got to expect trouble: the GRPC status
`FailedPreconditon` is now -- correctly, as it seems -- translated to HTTP
status `400 Bad Request`.
I think we might rely on this being translated to `412 Precondition
Failed` in a few places, at least from grepping around.
=> deps: bump grpc-gateway: 1.9.4 -> 1.9.5

.expeditor/verify.pipeline.yml, components/authz-service/engine/opa/policy/Makefile, components/local-user-service/Makefile, scripts/install_hab_pkg.sh
- OPA doesn't need a studio for its tests
- local-user-service doesn't need a studio for its tests, combine static and unit again.
- installing the CLI `opa` in the Makefile is probably not needed
- remove `privileged: true` from some deployment-service steps that don't need them
=> auth-stuff: reduce clutter in pipeline defs

Gopkg.toml
=> Gopkg.toml: remove github.com/robfig/cron

components/automate-chef-io/content/docs/airgapped-installation.md, components/automate-cli/cmd/chef-automate/upgrade.go
Supply a useful error when a user does not provide an airgap bundle when upgrading a deployment that was created with one.
Fixes #955
1.  Build an airgap bundle: `chef-automate airgap bundle create ./today.aib`.
2. Run `chef-automate airgap bundle create ./today.aib` to deploy.
3. Once the deploy has completed successfully, run `chef-automate upgrade run`. This will fail with an error `To upgrade a deployment created with an airgap bundle, use --airgap-bundle to specify a bundle to use for the upgrade.`.
=> [deployment] Add guard rails around upgrading deployments done with airgap bundles

components/applications-service/dev/hab-client/Dockerfile
For the applications view we have a docker-based dev environment we use to test with a real habitat supervisor. Prior to the official release of 0.83.0, we required an RC build from the unstable channel. Now that 0.83.0 is officially released, we want to use that instead.
https://discourse.chef.io/t/chef-habitat-0-83-0-released/15670
Follow the instructions in the readme for the hab client dev environment: https://github.com/chef/automate/blob/master/components/applications-service/dev/hab-client/README.md
After running `./run-hab-sup.sh -t YOUR_TOKEN` you should see two services in the applications view UI.
=> Move apps e2e hab client to 0.83 stable

.bldr.toml, components/applications-service/integration_test/ingestion_test.go, components/applications-service/integration_test/service_groups_filters_test.go, components/applications-service/pkg/storage/postgres/db.go, components/applications-service/pkg/storage/postgres/hab_event.go, components/applications-service/pkg/storage/postgres/schema/sql/09_add_service_group_view_columns.up.sql, components/applications-service/pkg/storage/postgres/service_groups.go
To avoid a query with substring we added a new column for name suffix to service group.
Technically the name suffix is actually the name of the service group, and the alternative
would be to compose the service.service_group name upon query.
App, Env and service group name all result in complete service group returns
this allows us to continue to use the view for these filters.
=> Add support for filtering service groups by app, env and name

components/pg-sidecar-service/cmd/pg-sidecar-service/commands/serve.go, components/pg-sidecar-service/pkg/server/server.go
This fixes some uses of logrus.Fatal inside a function that returns an
error to its caller.
But, this also has the side-effect of rebuilding the package. We
haven't shipped pg-sidecar-service in a while. Because of the bug
fixed in #1111 we think that many installations likely have a small
problem where not all of pg-sidecar-service's dependencies are
installed. Shipping a new version will fix since the update
dependencies will get installed on upgrade.
=> pg-sidecar-service: minor error handling fixes, new build

scripts/verify_build.sh
Before, this would append in an unsatisfying way:
Now, the two annotations are separate.
Also ignores changes to datamigration files. ✔️
=> buildkite: separate changed components/sql files annotations

components/authz-service/server/v2/migration_internal_test.go, components/authz-service/server/v2/policy.go, components/authz-service/server/v2/policy_refresher.go, components/authz-service/server/v2/policy_test.go, components/authz-service/server/v2/system.go, components/authz-service/storage/errors.go, components/authz-service/storage/postgres/migration/sql/66_iam_statements_drop_id_column.up.sql, components/authz-service/storage/postgres/migration/sql/README.md, components/authz-service/storage/v2/postgres/postgres.go, components/authz-service/storage/v2/postgres/postgres_test.go, components/authz-service/storage/v2/statement.go
When moving from `id` to `db_id` for all auth database entities, `id` became superfluous. This PR cleans that up.
Also, please see individual commits for:
✅ Made some often-repeated queries in `postgres_test.go` constants.
✅ ~Made a `storage.Statement`'s `Role` field `sql.NullString` instead of treating `""` as unset~ _some other day..._
#832 
Test pass
`start_all_services`, `rebuild components/authz-service`, create some policies. But really, our tests should have us well covered here 😄
=> authz-service/sql: drop iam_statements' id column

components/teams-service/server/v1/server.go, components/teams-service/server/v2/server.go
There' some decent guidance here: https://github.com/golang/go/wiki/Errors
Error strings should
- start with lowercase
- be specific: if create fails, don't say that create failed
- not end with a period
...because they might be wrapped, as it happens in this case: When this error
bubbles up in the UI, it'll say
> Could not create team: unable to create team: a team with name "..." already exists..
=> teams-service: cut down "create team" error strings

e2e/cypress/integration/ui/settings/03_team_add_users.spec.ts
`deploy/dev` of `automate/master` was broken by a previous merge; where we had assumed that there's only ever two users: the one cypress creates and admin. While this is true for the environment we're using in the pre-merge cypress integration tests, it's not true for either the local dev environment or our AWS nodes. Both use the dev command for creating an `operator` and an `editor` user.
With this change, the semantics of the "add all users to the team" tests are changed to do just that: every user we find is added to the team.
Locally, you can verify this change by running 
```
cd e2e; env CYPRESS_IAM_VERSION=v2.0 CYPRESS_BASE_URL=https://a2-dev.test npm run cypress:open
```
=> e2e: fix cypress for all envs

components/applications-service/habitat/config/config.toml, components/applications-service/habitat/hooks/run, components/authz-service/habitat/config/config.yml, components/authz-service/habitat/hooks/run, components/automate-dex/habitat/config/config.json, components/automate-dex/habitat/hooks/run, components/automate-dex/habitat/templates/config.yml, components/compliance-service/habitat/hooks/run, components/nodemanager-service/habitat/hooks/run, components/secrets-service/habitat/config/config.toml, components/secrets-service/habitat/hooks/run, components/session-service/habitat/config/config.yml, components/session-service/habitat/hooks/run, components/teams-service/habitat/config/config.yml, components/teams-service/habitat/hooks/run
These services were copying files that are only used for reading out
of package path and into the service's static path. No one I talked to
had a reason for why we were doing this.
We think maybe one of the following let us here:
1) permissions problems on files. We now test with a restrictive
default umask and it is unclear to me what permissions problem we
could have hit that the `cp` would have avoided.
2) Following a "rule of thumb" that the service should only depend on
files in `/hab/svc/SERVICE-NAME`. While I think this is a good rule
of thumb, for static data (this data could have been compiled into the
binary), I don't see the harm in reading it directly from the package
path.
Removing the copy comes with the advantage of removing another step
from service startup that could …
=> Remove unnecessary copies from pkg.path

components/compliance-service/Makefile, components/compliance-service/api/profiles/conversion/conversion.go, components/compliance-service/dao/pgdb/filtering.go, components/compliance-service/dao/pgdb/profiles.go, components/compliance-service/reporting/relaxting/profiles.go
This fixes all the prealloc violations and simplifies our LINTERARGS
based on changes to the main linter configuration.
The only remaining differences in compliance-service from the standard
configuration is the nakedret violations. Fixing those looks _mostly_
straightforward but there are a few with some subtle behavior so it is
probably best done as its own PR.
=> compliance-service: prealloc linter

.expeditor/verify_private.pipeline.yml, components/automate-deployment/habitat/hooks/reload, components/automate-dex/habitat/hooks/health-check, components/automate-gateway/habitat/hooks/health-check, components/automate-load-balancer/habitat/hooks/reload, components/automate-ui/habitat/hooks/health-check, components/backup-gateway/habitat/hooks/run, components/compliance-service/habitat/hooks/health-check, components/compliance-service/habitat/hooks/run, components/compliance-service/habitat/plan.sh, components/config-mgmt-service/habitat/hooks/health-check, components/ingest-service/habitat/hooks/health-check, components/ingest-service/habitat/hooks/run, components/nodemanager-service/habitat/hooks/run, components/session-service/habitat/hooks/health-check, integration/tests/shellcheck_rendered_hooks.sh
We have a bunch of bash scripts that are not shellchecked at the moment, because they're habitat templates. This PR introduces shellcheck into that, by shellchecking **the rendered hook scripts**. Naturally, they fail validation, so the findings don't break the build, but are merely reported and ignored.
At some later time, we can remove the `|| return 0` -- when the issues have been resolved.
👉 [These are the current findings](https://buildkite.com/chef/chef-automate-master-verify-private/builds/4052#d9d4e702-f302-49da-94f5-3f87df8e08b1/484)
=> ci: shellcheck rendered hooks

e2e/cypress/integration/ui/settings/03_team_add_users.spec.ts
ℹ️ I've run the offending spec against all envs manually now:
=> e2e/cypress: make 03_team_add_users spec work for more users

.expeditor/publish-release-notes.sh
remove the **Upgrade Impact** section from the release notes template.
the impactful upgrade was from April and does not need to be called
out weekly in release notes.
=> [release notes] update release note template

components/authz-service/server/v2/system.go
_Note: I marked this as "do-not-merge" only because I think it is useful for folks to review PR-1158 before this PR gets merged._
All users should be able to check the appply-rules status:
on the projects list page they should be able to see
the percentage complete on the button if its in progress.
(Soon that will be converted to a global progress message at the bottom of all pages.)
PR - #1158 (Check apply rules only in IAM v2.1)
Requests to check rules status should be fired periodically:
1. Rebuild components/authz-service
2. Create a new user.
3. Login as that user.
4. Open Dev Tools >> Network and observe that calls to check the apply-rules status are occurring--and succeeding!
Different scenarios you can check--assuming PR-1158 has not yet merged--and assuming you are running v2.1: …
=> Update rules-check permission

components/automate-ui/src/app/entities/policies/policy.model.spec.ts, components/automate-ui/src/app/entities/policies/policy.model.ts, components/automate-ui/src/app/entities/teams/team.reducer.spec.ts, components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.ts, components/automate-ui/src/app/pages/policy/list/policy-list.component.spec.ts, components/automate-ui/src/app/pages/project/list/project-list.component.spec.ts, components/automate-ui/src/app/pages/project/rules/project-rules.component.spec.ts, components/automate-ui/src/app/pages/roles/list/roles-list.component.spec.ts, components/automate-ui/src/app/pages/team-details/team-details.component.html, components/automate-ui/src/app/pages/team-details/team-details.component.spec.ts, components/automate-ui/src/app/pages/team-details/team-details.component.ts, components/automate-ui/src/app/pages/team-management/team-management.component.spec.ts, components/automate-ui/src/app/pages/user-details/user-details.component.html, components/automate-ui/src/app/pages/user-details/user-details.component.spec.ts, components/automate-ui/src/app/pages/user-details/user-details.component.ts
On the periphery of some UI work I noticed some type safety anomalies where things that should have been compiler errors (or so I thought) were not flagged as such. Upon refreshing myself on how static typing, type inference, and type assertions actually work in TypeScript I made some surprising discoveries. This PR fixes an assortment of such issues.
They are grouped by commit into several violation categories, so follow the commits!
Here is one startling example: 
After entering an invalid value (`CUSTOMxxx`) for a type, the error is not flagged in VSCode until one **removes** the type assertion:
Alas, these types of potential pitfalls are not going to be noticed by the computer no matter how much linting you do. So I wrote up some slides ("TypeScript Type Traps") to document and …
=> TypeScript Type Traps

e2e/package-lock.json, e2e/package.json
Updates cypress to latest minor version to resolve `npm audit` warnings.
**Before**
```
$ npm audit
found 163 high severity vulnerabilities in 6065 scanned packages
```
**After**
```
$ npm audit
found 0 vulnerabilities in 6065 scanned packages
```
There are no `npm audit` warnings within `/e2e` directory.
=> Update e2e cypress deps to address security warnings

components/chef-ui-library/stencil.config.ts
It seems the latest versions of Stencil compiler no longer copy the entire `assets` directory by default. This was causing the `muli` fonts to be excluded from the ui-lib build output and thus unavailable to the browser.
Only [svg and js files](https://github.com/ionic-team/stencil/blob/ee28dc04678a54e1862c5905c87b30218535f888/src/compiler/config/validate-outputs-dist.ts#L70-L71) are now copied by default (weird default?). This commit ensures everything in `assets` is copied.
https://github.com/chef/automate/pull/1053
`dist/collection` in chef-ui-library build contains `assets` directory identical to `src/assets`.
- `cd chef-ui-library`
- `npm run build`
- see that `dist/collection/assets` matches `src/assets`
=> Ensure ui-lib builds include font assets

components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.html, components/automate-ui/src/app/page-components/create-v1-team-modal/create-v1-team-modal.component.html, components/automate-ui/src/app/pages/policy/add-members/policy-add-members.component.html, components/automate-ui/src/app/pages/policy/add-members/policy-add-members.component.ts, components/automate-ui/src/app/pages/project/rules/project-rules.component.html, components/automate-ui/src/app/pages/project/rules/project-rules.component.ts, components/automate-ui/src/app/pages/team-management/team-management.component.ts, components/automate-ui/src/app/pages/user-details/user-details.component.html, components/automate-ui/src/app/pages/user-details/user-details.component.ts, components/automate-ui/src/app/pages/user-management/user-form/user-form.component.html, components/automate-ui/src/app/pages/user-management/user-management.component.ts
Another sweep of consistency checks for auth UI code covering:
- All required fields are marked with an asterisk--and in an `aria-hidden` span.
- All input fields disallow whitespace-only values.
- Extraneous leading/trailing whitespace automatically trimmed.
- Field name in the error pop-up matches the displayed field name exactly.
N/A
All auth inputs have identical behavior with respect to the items noted above.
rebuild automate-ui
Navigate through the auth pages to see that any and all input fields behave consistently.
=> Auth input field consistency sweep

components/compliance-service/reporting/relaxting/migrations.go, components/compliance-service/reporting/relaxting/migrations_from_a1.go, components/compliance-service/reporting/relaxting/migrations_from_a2_v1.go, components/compliance-service/reporting/relaxting/migrations_from_a2_v2.go, components/compliance-service/reporting/relaxting/migrations_from_a2_v3.go, components/compliance-service/reporting/relaxting/util.go
Switched to async ElasticSearch reindex calls to avoid gateway timeouts on long running reindexes.
=> Run compliance reindex calls async

components/automate-ui/src/app/pages/team-details/team-details.component.html
- #794 
- #1041 
See "After" above.
- `rebuild components/automate-ui-devproxy`
- in another terminal, run `npm run serve:hab` in `components/automate-ui`
- browse to team details, run `chef-automate iam reset-to-v1`, browse to team details again
=> automate-ui/team-details: show name in breadcrumbs

components/compliance-service/reporting/relaxting/util.go
Some Elasticsearch instances do not return task info in the response when checking if a task is complete. This is not an error when this happens. 
Initial PR https://github.com/chef/automate/pull/1175/files
=> Not returning an error when the Task info is nil

components/applications-service/cmd/applications-publisher/main.go, components/applications-service/pkg/storage/client.go, components/applications-service/pkg/storage/client_test.go
Add "UNRECOGNIZED" update strategy to account for some upgrade scenarios
This change accounts for the case where:
1. A new update strategy is added to the habitat supervisor
2. A user upgrades habitat and uses this update strategy
3. But does not upgrade Automate
In this case, Automate will not be able to infer the proper name of the update strategy because the names of the update strategies are hard coded in Automate, and even if we did not hardcode them in the Automate codebase, we would need to infer them from the compiled protocol buffer code, which means that in either case a new version of the applications service needs to be built and upgraded-to before habitat messages referencing the new update strategy can be properly understood.
Should these conditions occur, we want to label …
=> Add "unrecognized" update strategy to applications service backend

components/ingest-service/backend/elastic/migration.go
All Elasticsearch reindexes should be done with async. This change is needed because all elasticsearch requests go through the automate-es-gateway which adds a 60-second timeout. 
#557
The ingest-service does not have any reindexes that are not using the DoAsync function.
=> Updating Elasticsearch reindexes to async

components/automate-deployment/pkg/a1stub/server.go, components/automate-deployment/pkg/a1upgrade/reindex_es2.go
All Elasticsearch reindexes should be done with async. This change is needed because all elasticsearch requests go through the automate-es-gateway which adds a 60-second timeout.
https://github.com/chef/automate/pull/1177
=> Remove non async reindexes

components/automate-ui/src/app/helpers/auth/validator.ts, components/automate-ui/src/app/pages/user-details/user-details.component.ts, components/automate-ui/src/app/pages/user-management/user-form/user-form.component.html, components/automate-ui/src/app/pages/user-management/user-management.component.ts
Recent code changes inadvertently made the error-pop up for the auth password field when creating a user open immediately upon the form opening:
This PR fixes that.
Also did a quick drive-by to DRY up some validator code.
Opening the form does not show that pop-up error.
Go to Settings >> Users >> Create User.
=> Suppress password error upon open

components/automate-load-balancer/habitat/config/render-certs.sh, components/automate-load-balancer/habitat/hooks/reload, components/automate-load-balancer/habitat/hooks/run
We were not rendering the certificates before HUPing nginx. This meant
that any changes to the frontend certificates required the user to
manually restore automate/nginx.
=> Changing frontend certs correctly renders config before reload

lib/cereal/backend/backend.go, lib/cereal/postgres/postgres.go, lib/cereal/postgres/postgres_test.go, lib/cereal/postgres/sql_schema.go, tools/cereal-scaffold/main.go
Added an API to the cereal backend to list workflow instances.
```golang
type Driver interface {
ListWorkflowInstances(ctx context.Context, opts ListWorkflowOpts) ([]*WorkflowInstance, error)
}
type ListWorkflowOpts struct {
WorkflowName *string
InstanceName *string
IsRunning    *bool
}
```
It allows finding a workflow instance by (workflow name, instance name),
or allows listing all workflows, or all workflows of a certain workflow
name, or all running/not running workflows.
Example usages:
```golang
// List all workflow instances
instances, err = b1.ListWorkflowInstances(ctx, backend.ListWorkflowOpts{})
// List all completed workflow instances
isRunning = false
instances, err = b1.ListWorkflowInstances(ctx, backend.ListWorkflowOpts{
IsRunning: &isRunning,
})
// List all running workflow …
```
=> Add API to list workflow instances

components/automate-ui/src/app/pages/policy/details/policy-details.component.html, components/automate-ui/src/app/pages/policy/details/policy-details.component.ts, components/automate-ui/src/app/pages/project/details/project-details.component.html, components/automate-ui/src/app/pages/project/details/project-details.component.spec.ts, components/automate-ui/src/app/pages/project/details/project-details.component.ts, components/automate-ui/src/app/pages/team-details/team-details.component.html, components/automate-ui/src/app/pages/team-details/team-details.component.ts
This adds a bit of functionality so that when you navigate to different tabs within a project, it is reflected in the URL:
While I was in there, I went through the other auth pages that already handle fragments (team-details and policy-details) and made all 3 use the same names, same structure, and same code patterns. (So the first commit did the task at hand; all the remaining commits did an orderly cleanup.)
There's a lot of whitespace changes, as I did some indentation updates, too. So probably easier to see the changes by following the commits.
NA
Selecting a tab updates the URL to show the tab as a fragment.
1. Specifying `#rules` goes to the rules tab.
2. Specifying `#details` goes to the details tab.
3. Specifying no fragment goes to the rules tab (the first tab).
4. Specifying any …
=> [automate-854] Subpage routing for projects

components/cereal-service/integration/domain_test.go, components/cereal-service/integration/integration_test.go, components/cereal-service/pkg/server/server.go, components/cereal-service/pkg/server/server_test.go, lib/cereal/grpc/grpc.go, tools/cereal-scaffold/main.go
Using the grpc backend now requires specifying a domain to namespace workflows and tasks
=> Add domain support to cereal service

components/cereal-service/integration/domain_test.go, components/cereal-service/pkg/server/server.go, lib/cereal/cereal.go, lib/cereal/grpc/grpc.go, lib/cereal/integration/abandon_workflow.go
Task completion wasn't waiting around for the server to confirm that it
processed the task completion messages. This was causing the tests to
fail as they assumed that once the backend function returns (without
error), the data has been persisted.
=> Fix race condition in the grpc cereal backend

components/automate-ui/src/app/entities/users/user.effects.ts
Found that, after a browser refresh, the first time you go into user details generated a run time error:
N/A
Browser error be gone!
Navigate to Settings > Users.
Refresh browser.
Select any user to get to the user details.
Observe no run-time error on the JavaScript console.
=> Correct action filter on getUserFailure effect

components/automate-ui/src/app/components/chef-components.module.ts, components/automate-ui/src/app/components/form-control/form-control.directive.spec.ts, components/automate-ui/src/app/components/form-control/form-control.directive.ts, components/automate-ui/tslint.json
Adds a `FormControlDirective` that matches any form inputs utilizing
`[formControl]` or `[formControlName]` bindings. This directive keeps a reference to the control's initial value and ensures that a dirty control is marked as pristine if/whenever the value changes back to its initial value.
https://github.com/chef/automate/pull/1115
Form controls are marked as pristine whenever its value is equal to its initial value.
=> Add `FormControlDirective ` to track original value of form controls

components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.html, components/automate-ui/src/app/page-components/create-v1-team-modal/create-v1-team-modal.component.html, components/automate-ui/src/app/pages/api-token/details/api-token-details.component.html, components/automate-ui/src/app/pages/policy/add-members/policy-add-members.component.html, components/automate-ui/src/app/pages/project/details/project-details.component.html, components/automate-ui/src/app/pages/project/rules/project-rules.component.html, components/automate-ui/src/app/pages/team-details/team-details.component.html, components/automate-ui/src/app/pages/user-management/user-form/user-form.component.html, components/chef-ui-library/src/atoms/chef-input/chef-input.tsx
1. set `autocomplete="off"` on some more inputs
2. ensure that clicking "edit ID" before having entered a name doesn't make the error pop up
(See the linked issue for details.)
☝️ Fixed the uniqueness error messages, as discussed with @susanev in slack.
- #1185
- a little overlap with #1156, but not too much
NA
💁‍♂ See #1185's repro steps please.
=> [issue 1185] autocomplete="off" and dirty check in id input

components/applications-service/integration_test/service_groups_filters_test.go, components/applications-service/pkg/storage/postgres/schema/sql/10_drop_view.up.sql, components/applications-service/pkg/storage/postgres/service_groups.go
- Filters for service, site, channel, version and buildstamp
- Drop view and compose query inline
- Status filter done outside of inner query
- Still an issue around array agg which results in 2 releases/2 packages
- Counts are accurate for version/origin partial results
=> Add service group filters

components/automate-ui/src/main.ts
Sometime during 1.0-alpha it appears Stencil changed some of their upstream polyfills and how they're loaded. `applyPolyfills` is now required to be called before `defineCustomElements` if you want to support IE11, Edge, and other browsers without full custom element support.
https://github.com/ionic-team/stencil/commit/881c49bb9f2c812341890d3605664405ec455265
https://github.com/ionic-team/stencil-site/commit/6a4d8a5383867a3392e16c3719a685e2b18f1591
**Before - Firefox 60esr**
**After - Firefox 60esr**
=> Apply ui-lib polyfills for older browsers

components/ingest-service/server/job_scheduler_server.go
This bug meant that in some cases we would run one of the cleanup scripts with the wrong threshold.
=> [ingest-service] Use correct threshold for immediately run jobs

components/compliance-service/reporting/relaxting/reports.go
The `"bool": {}` conditions below are useless and this PR removes them. 
```json
"query": {
"bool": {
"must": [
{
"type": {
"value": "_doc"
}
},
{
"bool": {
"should": {
"terms": {
"environment.lower": [
"DevSec Prod Zeta",
"Missing Env"
]
}
}
}
},
{
"bool": {}
},
{
"bool": {}
},
{
"bool": {}
},
{
"bool": {}
},
{
"bool": {}
},
{
"bool": {}
},
{
"bool": {}
},
{
"bool": {}
},
{
"bool": {}
},
{
"bool": {}
},
{
"bool": {}
},
```
=> Avoid adding blank elasticsearch query conditions

.bldr.toml, components/es-sidecar-service/pkg/server/purge.go
This was only being used for a thin wrapper function that didn't
look like it was providing much value.
=> [es-sidecar-service] Remove dependency on config-mgmt-service

components/automate-ui/src/app/pages/client-runs/client-runs.component.scss, components/automate-ui/src/app/pages/event-feed/event-feed.component.scss
The Client Runs page's search bar had the download and share buttons on the next line because the search bar was set at 100%. This was caused by the search bar being rename from app-client-runs-search-bar to app-search-bar. The CSS was not updated with this name. 
https://github.com/chef/automate/pull/1106
The download and share buttons are on the same line as the image below.
=> Fixing the Client Runs page's search bar

components/automate-ui/src/app/app.module.ts, components/automate-ui/src/app/entities/api-tokens/api-token.effects.ts, components/automate-ui/src/app/entities/roles/role.requests.ts, components/automate-ui/src/app/entities/teams/team.effects.ts, components/automate-ui/src/app/entities/userperms/userperms.selectors.ts, components/automate-ui/src/app/entities/users/user.effects.ts, components/automate-ui/src/app/page-components/sidebar-select-list/sidebar-select-list.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+profile/+profile-overview/profile-overview.component.ts, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+scanner/containers/nodes-add/nodes-add.component.ts, components/automate-ui/src/app/pages/+compliance/+scanner/containers/nodes-edit/nodes-edit.component.ts, components/automate-ui/src/app/pages/client-runs/client-runs.component.ts, components/automate-ui/src/app/pages/policy/add-members/policy-add-members.component.ts, components/automate-ui/src/app/pages/project/details/project-details.component.ts, components/automate-ui/src/app/pages/project/rules/project-rules.component.ts, components/automate-ui/src/app/pages/service-groups/service-groups.component.spec.ts, components/automate-ui/src/app/pages/service-groups/service-groups.component.ts, components/automate-ui/src/app/pages/team-add-users/team-add-users.component.ts, components/automate-ui/src/app/pages/team-details/team-details.component.ts, components/automate-ui/src/app/pages/user-details/user-details.component.ts, components/automate-ui/src/app/services/http/http-client-auth.interceptor.spec.ts, components/automate-ui/src/app/services/profiles/upload.service.spec.ts, components/automate-ui/src/app/services/profiles/upload.service.ts, components/automate-ui/src/app/services/projects-filter/projects-filter.effects.ts, components/automate-ui/src/app/services/projects-filter/projects-filter.requests.ts
In an effort to make the upcoming PR for the Angular 8 upgrade smaller, I undertook to clean up many of the deprecation, lint, compiler, and test errors that are due to more stringent checks. So all of the changes herein are compatible with our existing Angular/rxjs/TypeScript versions. Some of them correct errors in the code base that went unreported and, being somewhat innocuous, unnoticed.
Follow the commits if you want to see each type of change in isolation.
However, I have also added pre-review comments on the first occurrence of each category so it is easy to review from the file changes, too.
Compiler, lint, and unit tests all still report no issues.
Run unit tests.
Run lint.
=> Code tightening (prepping for Angular 8)

components/automate-ui/src/app/services/node-details/node-runs.service.spec.ts, components/automate-ui/src/app/services/node-details/node-runs.service.ts
This code was moved to ingest-service's pipeline about 2 years ago. I have always meant to remove it from the UI code. 
Below is a link to where the code moved to in the ingestion pipeline. 
https://github.com/chef/automate/blob/master/components/ingest-service/pipeline/processor/transmogrify_run.go#L107-L112
The PR to move the code to ingestion back on Nov 2017. 
https://github.com/chef/a2/commit/6b6a47187a5634ef8d29b4f6da66bd7f00fb2683#diff-a2c755e72b3d6e6593efd4e5880acdaaR90
=> Removing code that was moved to ingestion

components/automate-ui/src/app/entities/client-runs/client-runs.requests.spec.ts, components/automate-ui/src/app/entities/client-runs/client-runs.requests.ts, components/automate-ui/src/app/page-components/search-bar/search-bar.component.spec.ts, components/automate-ui/src/app/page-components/search-bar/search-bar.component.ts, components/config-mgmt-service/integration_test/suggestions_test.go, components/ingest-service/backend/converge.go
Preventing empty error message suggestions like the one shown below. 
The problem was that the `errorMessage` field was filled with an empty string if there was no error. Therefore the empty string suggestion was correct. The bug was prevented in three places ingestion, request to the API from the UI, and the search bar component. 
https://github.com/chef/automate/pull/1211#issuecomment-520996870
The blank suggestion does not appear in the search bar
1. `build components/ingest-service && build components/automate-ui && start_all_services`
1. Add some nodes with empty errors `chef_load_nodes 100`
1. Open https://a2-dev.test/infrastructure/client-runs
1. Type one letter in the search bar for catagory "Error"
1. Ensure the empty suggestion is not displayed.
=> Preventing empty error message suggestions

scripts/changed_components.rb
In #1226, we've added outputting why components are rebuild. It output can easily go out of hand. An example for this is #1237, where we see a few screenfuls of this:
With the change introduced here, these will be collapsed. What you'll see now is
...and when you're wondering why, say, `automate-cli` is going to be rebuilt, you can open the details thingy:
=> ci: use <details> for files causing rebuilds

components/cereal-service/integration/domain_test.go, components/cereal-service/pkg/server/server.go
The domain was not being stripped from the task name
=> Fix task dequeue in cereal service

.expeditor/verify_private.pipeline.yml
This test breaks every time releng rebuilds the queue. We think adding
this will prevent the breakage in the future.
=> Give s3 backup test the right permissions

components/chef-ui-library/src/molecules/chef-side-panel/chef-side-panel.scss
Changed the shadow to only be visible when the side panel is open.
fixes #679
No more mysterious shadow on the page when the panel is closed
* `scripts/build_chef_ui_lib && npm run copy-ui-lib` from components/automate-ui
* `build components/automate-ui-devproxy`
* `start_all_services`
* `chef_load_actions 300`
* Navigate to _Dashboards_ > _Event Feed_ and open and close the side panel by using any of the buttons that look like links on the page
* Filter by _Event Type_: _Environments_ if you are having trouble finding any of the buttons that look like links
=> fix shadow on chef-side-panel so its only visible when its on-screen

components/applications-service/pkg/server/server.go, components/automate-gateway/handler/license.go, components/session-service/server/server.go, components/trial-license-service/pkg/license/license.go
A new version of Go was recently released that addresses multiple CVEs
in their implementation of HTTP2. This PR makes minor changes to force
a rebuild of the following components:
- applications-service
- automate-gateway
- session-service
- trial-license-service
to ensure that they are rebuilt with the most recent go version.
=> Force rebuild of components using Go net/http

components/cereal-service/integration/domain_test.go, components/cereal-service/integration/integration_test.go, lib/cereal/postgres/postgres.go
Calling cancel() on an uncommitted/rolledback transactions results in
the underlying connection also being closed.
This happens in the common case of the workflow scheduler when there
are no scheduled workflows to run. To avoid log messages for
automate-pg-gateway about the connection close, we explicitly commit
the transaction to avoid it.
=> [lib/cereal] Avoid spurious connection closes

.expeditor/verify_private.pipeline.yml, components/automate-deployment/pkg/backup/spec.go, integration/tests/backup.sh
=> Ensure license-control-database is included in backup spec

components/automate-cli/pkg/diagnostics/integration/license.go
This appeared to be testing the OptOut configuration but really tests
whether the license ID has changed. I've updated the comments,
function name, and API endpoint used to be a bit more honest.
=> diagnostics: fix errant error message and functions names

components/applications-service/cmd/applications-publisher/main.go, components/applications-service/pkg/ingester/v1/ingest.go, components/applications-service/pkg/nats/nats.go, components/applications-service/pkg/nats/publisher.go, components/applications-service/pkg/nats/subscriber.go, components/event-gateway/pkg/nats/authenticator.go
This enables Automate to receive health check events from habitat via "plain" NATS messaging instead of NATS-streaming (though nats-streaming continues to work; this patch makes automate subscribe to messages from both systems).
Messages sent via "plain" NATS messaging are not persisted in transit, so this change increases the possibility that messages will be lost, for example when the event service restarts. While not ideal, this is considered acceptable because the behavior of the overall system is generally convergent: habitat is sending a complete picture of the state of a service as understood by Automate with each health check message, which is sent by default every 30s. Automate does not keep a historical record of service states. Therefore, once Automate's ingestion system …
=> Accept Habitat Healthchecks via "Plain" NATS Messaging

.bldr.toml, components/automate-chef-io/Makefile
It appears that a recent commit increased the number of swagger
conflicts.
=> automate-chef-io: increment an integer

components/automate-ui/src/app/components/sidebar/sidebar.component.scss
The headings in the left nav on Dashboards, Infrastructure, and Compliance are the wrong colors. All of the headings in the left-nav bar should be #6f7878. See Applications or Settings for the correct styles in the left-nav.
fixes https://github.com/chef/automate/issues/688
I have added css for this to change the color.
=> change the color of left nav headings

components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.html, components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.spec.ts, components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.ts, components/automate-ui/src/app/components/projects-dropdown/projects-dropdown.component.html, components/automate-ui/src/app/components/projects-dropdown/projects-dropdown.component.scss, components/automate-ui/src/app/components/projects-dropdown/projects-dropdown.component.ts, components/automate-ui/src/app/entities/projects/project.model.ts, components/automate-ui/src/app/entities/teams/team.reducer.ts, components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.html, components/automate-ui/src/app/pages/component-library/demos/demo-projects-dropdown/demo-projects-dropdown.component.html, components/automate-ui/src/app/pages/component-library/demos/demo-projects-dropdown/demo-projects-dropdown.component.ts, components/automate-ui/src/app/pages/team-details/team-details.component.html, components/automate-ui/src/app/pages/team-details/team-details.component.scss, components/automate-ui/src/app/pages/team-details/team-details.component.spec.ts, components/automate-ui/src/app/pages/team-details/team-details.component.ts, components/automate-ui/src/app/pages/team-management/team-management.component.ts, components/automate-ui/src/app/services/projects-filter/projects-filter.service.ts, e2e/cypress/index.d.ts, e2e/cypress/integration/ui/common/02_global_filter.spec.ts, e2e/cypress/integration/ui/settings/02_team_mgmt.spec.ts, e2e/cypress/integration/ui/settings/03_team_add_users.spec.ts, e2e/cypress/integration/ui/settings/04_team_details.spec.ts, e2e/cypress/support/commands.ts
Added project update to teams. In the dropdown, all projects a team is a member of will start out pre-checked and any additional projects in the project filter will also be avaliable.
Simplified the state that was contained in the projects-dropdown and updated the object-create-modal to reflect those changes.
Cleaned up the cypress tests.
Start the UI in the standard way, create some projects from the UI, create a team, modify its projects.
- https://github.com/chef/automate/issues/809
- [Zeplin Designs](https://app.zeplin.io/project/5ba808703eb54372d860c737?seid=5ca78c9bfe244b013f56f0f6)
=> [automate-809] Update projects for a team

components/automate-ui/src/app/pages/node-details/node-details.component.html, components/automate-ui/src/app/pages/node-details/node-details.component.ts, components/automate-ui/src/app/services/node-details/node-details-resolver.service.spec.ts, components/automate-ui/src/app/services/node-details/node-details-resolver.service.ts
We got a report in success slack of a bug: "Looks like seeing run history is broken in Automate. (I can see run history, but clicking on the specific run takes you back to the main "Infrastructure" (formerly client-runs) page."
Upon investigation, I noticed we missed a navigation rename when going from client-runs to infrastructure/client-runs.
This corrects that.
N/A
Selecting a past item in the run history for a node correctly loads the node details page with that run's information.
chef_load_nodes at least 2 times
rebuild the ui
select an item in the run history, expect to see that run loaded on the node details page
=> bugfix: correct navigation path for run history items

components/applications-service/pkg/storage/postgres/schema/sql/13_delete_normalized_tables.up.sql
Deletes the old tables from the applications database. These are now unused by the application.
#1233 
Most complete version:
1. remove everything from `results/`
2. `start_all_services` in the studio
3. `applications_populate_database`
4. See your services in the UI
5. See the old tables are in the UI: `chef-automate dev psql chef_applications_service` then run `\d` in the interactive Postgres client.
6. `build components/applications-service` and wait for it to get deployed
7. Your services from step 3/4 are still in the UI
8. `chef-automate dev psql chef_applications_service` then run `\d` in the interactive Postgres client. The old tables are gone.
=> Delete now-unused normalized tables for applications

components/cereal-service/Makefile, components/cereal-service/pkg/server/server.go, lib/cereal/cereal.go, lib/cereal/workflow_scheduler.go, tools/cereal-scaffold/main.go
This change allows us to wake up relevant go-routines in the local
process when certain events happens:
- When we enqueue tasks, we wake up the task polling goroutine
- When we finish a task, we wake up the workflow polling goroutine
For each registered task executor we have a "Poller" which wakes up at an interval
or on notification and starts a task worker.  An additional worker will be spawned as 
long as there is more work to do.  When the worker finds that there is no more work to
do it exits.
Note to reviewers: We probably want to think about this worker management strategy.
We could make it more responsive by growing the queue
=> lib/cereal: Use in-process notifications to avoid delays

lib/cereal/backend/backend.go, lib/cereal/cereal.go, lib/cereal/grpc/grpc.go, lib/cereal/integration/abandon_workflow.go, lib/cereal/integration/cancel_workflow.go, lib/cereal/postgres/postgres.go, lib/cereal/postgres/task_cleaner.go, lib/cereal/postgres/task_pinger.go, lib/cereal/workflow_scheduler.go
Now that we have in-process notifications, we think we can push the
default time-based polling interval a bit higher to cut down on
unnecessary database queries.
While I was here, I did some minor cleanups on our logging.
=>  lib/cereal: bump default polling interval to 10 seconds

components/automate-ui/src/app/pages/team-details/team-details.component.ts, e2e/cypress/integration/ui/settings/04_team_details.spec.ts
The dropdown was not becoming properly disabled when saves were in progress, resulting in a race condition that made the tests flaky. Also hardened the cypress tests by adding 'is.not.disabled' assertion so that cypress will actually wait for the dropdown to not be disabled before sending the click event.
=> Fix race condition in disabled status of team details projects dropdown

components/automate-ui/src/app/pages/project/list/project-list.component.ts
Due to flicker, remove polling on projects list page.
No flicker
Set to IAM v2.1.
Go to Settings > Projects
=> Remove polling on projects page due to flicker

components/automate-ui/e2e/admin.e2e-spec.ts, components/automate-ui/src/app/components/form-control/form-control.directive.ts, components/automate-ui/src/app/pages/api-token/details/api-token-details.component.html, components/automate-ui/src/app/pages/api-token/details/api-token-details.component.ts, components/automate-ui/src/app/pages/project/details/project-details.component.html, components/automate-ui/src/app/pages/project/details/project-details.component.scss, components/automate-ui/src/app/pages/project/details/project-details.component.spec.ts, components/automate-ui/src/app/pages/project/details/project-details.component.ts, components/automate-ui/src/app/pages/project/rules/project-rules.component.html, components/automate-ui/src/app/pages/project/rules/project-rules.component.ts, components/automate-ui/src/app/pages/team-details/team-details.component.html, components/automate-ui/src/app/pages/team-details/team-details.component.scss, components/automate-ui/src/app/pages/team-details/team-details.component.spec.ts, components/automate-ui/src/app/pages/team-details/team-details.component.ts, components/automate-ui/src/app/pages/user-details/user-details.component.html, components/automate-ui/src/app/pages/user-details/user-details.component.ts
This PR uses the new functionality embued to `FormControls` to remember their original values and reset themselves to pristine when appropriate.
With that, we can strip out the various ways we have done that manually.
The table shows the state of things auth prior to this PR. Each of the items below needed a bit of tweaking, making them cleaner. 
| Resource | Where to find it | Method |
| --- | --- | --- |
| user name | users >> [user] > edit > name | not checked! |
| team name | teams >> [team] > details > name | manual equality check |
| token name | [token] > details > name | dirty check fueled by manual keyup handler |
| token status | [token] > details > status | not checked! |
| project name | projects >> [project] > details > name | manual equality check |
| rule name | projects >> …
=> Reset for initial inputs

e2e/cypress/integration/api/iam/01_projects_api.spec.ts
This should help make them less flaky since you can only have 6 projects in a single environment at any time. Also prevented the project variables from being global in scope by moving them into the describe block and fixed the tabbing in before.
=> Add cypress prefix to projects and clean them up before and after the projects API tests

lib/cereal/cereal.go, lib/cereal/integration/pattern_single_task_workflow.go, lib/cereal/patterns/singletaskworkflow.go
This workflow executor makes it so you don't have to write a workflow executor if your workflow just needs to run 1 task. You can decide if you want to ignore cancel.
=> Add single task workflow pattern

components/automate-ui/src/app/components/input/input.directive.scss, components/automate-ui/src/app/pages/team-details/team-details.component.ts, e2e/cypress/integration/api/iam/01_projects_api.spec.ts, e2e/cypress/integration/api/iam/02_policies_api.spec.ts, e2e/cypress/integration/ui/settings/02_team_mgmt.spec.ts, e2e/cypress/integration/ui/settings/03_team_add_users.spec.ts, e2e/cypress/integration/ui/settings/04_team_details.spec.ts
If you have a team in the store already, it will populate the team save input before the team is fetched via the API. Since we didn't prevent typing in the input before the team was fetched via the API, cypress would find the input, find that the team name was correct (from the store cache), and then type. However, this would happen so fast the team wasn't fetched yet. When the fetch completed, it overwrote the updated team name cypress typed before save was clicked.
I've added functionality to disable the team name input before the team is fetched and while a save is in progress. The cypress tests should now pass since they are asserting that the input is enabled, preventing the race condition.
Also added base styling for the chefInput directive when disabled. It looks like this:
=> Fix race condition in cypress test by preventing typing in input before team loaded

components/notifications-service/server/lib/config.ex
This is an untested change to set the `depth` config for the ssl app
to 32 to handle the types of certificate chains common at customer
sites.
=> notification: increase cert depth config to 32

components/automate-ui/src/app/services/chef-session/chef-session.service.spec.ts, components/automate-ui/src/app/services/chef-session/chef-session.service.ts, components/session-service/oidc/oidc.go, components/session-service/server/server.go, components/session-service/server/server_functional_test.go
When a user's session cannot be refreshed anymore, they'll be sent to the _Sign In_ page. There, they'll have to select a method to use for Sign In, although we know what they had used before.
With this change, we'll make use of that knowledge, and send them to the right method immediately.
❕*Note*: The `Back` link is a bit wonky: It'll send them back to Automate, but they'll lack an ID token, so they'll be sent back to dex, but since there's no ID token, they'll see the selection. So, it **works**, but in a very odd way. Unfortunately, a proper fix is a bit more involved.
❕ *Note*: For SAML, there's no back button. So, to abort, and get back to the selection once you've used SAML, you'll need to browse to Automate again **manually**.
☑️ Depends on #1243 to get in first, this needs dex …
=> session-service: send the user to dex with their connector selected already

.expeditor/verify_private.pipeline.yml
This will remove the retry for applications-service integration test when they fail. 
=> Remove retry for applications-service

components/applications-service/integration_test/service_groups_filters_test.go, components/applications-service/pkg/storage/postgres/service_groups.go
Previously when searching on something that would narrow origin or version
and result in a partially filtered service group the packages and releases
were not filtered correctly. This adds a filter to the array agg subquery
in order to properly partially filter
=> Filter packages and release based on search parameters

lib/cereal/cereal.go, lib/cereal/integration/counting_workflow.go, lib/cereal/integration/delayed_task.go, lib/cereal/integration/duplicate_workflow_instance.go, lib/cereal/integration/error_task.go, lib/cereal/integration/helpers.go, lib/cereal/integration/pattern_single_task_workflow.go, lib/cereal/integration/schedule.go, lib/cereal/integration/simple_workflow.go, lib/cereal/integration/workflow_error.go
This adds a OnWorkflowComplete callback that the cereal library can
optionally call after it completes workflows in its main loop. This
allows us to add testing or debugging logic at this location.
Here, I've used it to remove a number of sleeps in the tests.
Overall, I think 3 or 4 more similar callbacks placed at various
points in the workflow and task executor flow could help us test
concurrency issues.
=> lib/cereal: Add callback to facilitate testing

.github/ISSUE_TEMPLATE/bug_report.md
Noticed when i was opening a bug report it did not correctly append the bug label - I think because that label has been modified to have an emoji bug in it. 
Hopefully this update will make it all work again!
=> update bug issue to updated bug label

e2e/cypress/integration/ui/compliance/01_ssh_scan_job.spec.ts, e2e/cypress/integration/ui/settings/01_user_mgmt.spec.ts, e2e/cypress/support/commands.ts
We had the user management tests commented out because they were flaky. I made a few tweaks and wanted to see if they'll be more stable now.
Edit: local runs are stable but pipeline runs still need some debugging
-  https://github.com/chef/automate/issues/959
- buildkite tests pass reliably (gonna retry them a few times)
- see buildkite
- [run locally](https://github.com/chef/automate/blob/master/e2e/README.md#running-cypress-locally)
=> Cypress: restore user management tests

lib/cereal/cereal.go, lib/cereal/cereal_test.go, lib/cereal/integration/delayed_task.go
This is one of a couple of changes to reduce the churn in database
connections used by cereal. By default, the Go sql library only keeps
2 idle connections. Thus, when we have a burst of task poller
activity, we start and subsequently close many new connections,
causing log spam from automate-pg-gateway.
One thing we can and will do is bump the number of idle connections.
This PR, however, reduces the "thundering hurd" of task pollers, by
introducing a small jitter into their wakeup time.
=> lib/cereal: jitter the task poller wakeup

components/authz-service/server/v2/policy.go, components/authz-service/server/v2/policy_test.go, components/automate-cli/cmd/chef-automate/iam.go, integration/tests/upgrade_reset_iam_v2.sh
Updated the messaging output for trying to switch to an IAM version you are already on to be consistent. Also updated the reset to v1 GRPC command to return `AlreadyExists` similar to the upgrade to v2 command and not run the reset migration. 
```
```
Upgrade, reset, etc.
=> Unify already on IAM version messaging and only migrate if necessary in IAM v1.0

.expeditor/update_docker_image_version_in_verify_pipeline.sh
We failed to `git add` the nightly.pipeline.yml file. As a result,
part of the update this script performs was being committed directly
to master rather than as part of the PR.
=> ci: don't commit to master in update_docker_image script

components/automate-chef-io/Makefile
The swagger command we use produces conflicts. This number is the
number of allowed conflicts. The number of conflicts has
changed.
This should fix the build, but as this is the second time we've
changed this number without understanding it, we should dig into this.
=> build fix: 45 is clearly better than 48

components/applications-service/integration_test/services_test.go, components/applications-service/pkg/storage/postgres/services.go
Only support filters that result in partial results for a service group.
origin, channel, site, version and buildstamp
The filters app, env, name, group name would result in different service groups
and therefore in the UI you would not see the service group to access the sidebar
=> Filter sidebar services by filters

components/automate-ui/src/app/entities/policies/policy.requests.ts, components/automate-ui/src/app/pages/team-details/team-details.component.html, components/automate-ui/src/app/pages/team-details/team-details.component.spec.ts, components/automate-ui/src/app/pages/team-details/team-details.component.ts, components/automate-ui/src/app/services/projects-filter/projects-filter.reducer.spec.ts
Initially I started to replace the sequence of GetProject (singular) calls
with just one GetProjects (plural) call, to reduce overhead and simplify the code.
Part way through that, though, I realized we do not even need GetProjects;
we already have enough project details from the global projects filter.
So this streamlines the team details code based on the above,
and adds some tests to show it is working.
Also addresses one UX issue:
If someone else deleted a project but the user has not refreshed the browser
lately, the global projects filter will still update periodically, but opening
team details looks like this, and the spinner remains indefinitely. Those projects are reporting errors because they are not amongst those in the current list (see above image).
Now, those deleted …
=> Streamline projects on team details page

components/compliance-service/ingest/pipeline/processor/report.go, components/compliance-service/ingest/pipeline/processor/summary.go, components/compliance-service/ingest/pipeline/publisher/compliance.go, components/compliance-service/integration_test/reporting_server_list_profiles_test.go, components/compliance-service/integration_test/reporting_server_list_suggestions_test.go, components/compliance-service/integration_test/stats_server_read_profiles_test.go, components/compliance-service/integration_test/suite_test.go
These changes prevent the Flaky compliance integration tests. The problem was that when running the project updater on newly created reports, summaries, and profiles the ES documents were not fully created. Add a refresh to the indexes ensures the ES documents are ready for modifications. 
#599
=> Adding ES refreshes to prevent flaky tests

Gopkg.lock, Gopkg.toml, components/session-service/server/server.go, components/session-service/server/server_test.go, vendor/github.com/alexedwards/scs/manager.go, vendor/github.com/alexedwards/scs/options.go, vendor/github.com/alexedwards/scs/session.go, vendor/github.com/alexedwards/scs/stores/memstore/memstore.go, vendor/github.com/alexedwards/scs/stores/pgstore/pgstore.go
When the code->token exchange in session-service's callback handler does not return a refresh_token, and there was a refresh_token stored with the session before, it is now removed instead of left untouched.
- #1352 made this apparent
The above doesn't happen anymore. When playing with #1352, you now never see the local user signin screen.
See #1352, let it refresh for a while.
=> session-service: update and fix stuff

lib/cereal/backend/backend.go, lib/cereal/cereal.go, lib/cereal/postgres/postgres.go, lib/cereal/task_dequeue_pool.go, lib/cereal/task_dequeue_pool_test.go, tools/cereal-scaffold/main.go
For each registered task, we call TaskDequeue every
TaskPoolInterval. For a service with a large number of task executors,
this can cause a large number TaskDequeue calls to be made to the
backend.
Similarly, even with 1 TaskExecutor configured for 10 workers, if
those workers are processing a large number of tasks, each worker will
call TaskDequeue. This may not be the most efficient way to use a
given backend.
This changes adds a small pool that can be used to limit the
concurrency of TaskDequeue calls.
=> lib/cereal limit number of concurrent TaskDequeue calls

.expeditor/create-manifest.rb
We made a build with incorrect packages due to some eventual consistency
issues with building/uploading a package and then later asking depot for
the latest version
Expeditor has the packages that were built. Printing the environment
keys to see if anything in there can help us.
=> Force another build

components/compliance-service/api/tests/02_nodes_spec.rb, components/compliance-service/api/tests/03_reports_spec.rb, components/compliance-service/api/tests/04_stats_spec.rb, components/compliance-service/api/tests/05_stats_summary_spec.rb, components/compliance-service/api/tests/06_stats_trend_spec.rb, components/compliance-service/api/tests/07_suggestions_w_filters_spec.rb, components/compliance-service/api/tests/08_search_profiles_spec.rb, components/compliance-service/reporting/relaxting/reports.go, components/compliance-service/reporting/relaxting/suggestions.go, components/compliance-service/reporting/relaxting/util.go, components/compliance-service/reporting/relaxting/util_test.go, components/compliance-service/test_data/audit_reports/2018-02-09_debian(2)-zeta-linux(f)-apache(p)-failed.json, components/compliance-service/test_data/audit_reports/2018-03-04_centos(3)-beta-nginx(p)-apache(s)-fake(s)-passed.json, components/compliance-service/test_data/audit_reports/2018-03-04_redhat(2)-beta-nginx(f)-apache(s)-failed.json, components/compliance-service/test_data/audit_reports/2018-03-04_windows(1)-zeta-apache(s)-skipped.json
This PR enables `control_tag` filters for the compliance APIs.
I updated test data as well to support integration testing of this new filter.
This is an example where we filter for compliance reports that have at least one control with tagged `scope:nginx` or `scope:apache`, case insensitive:
```
Reporting::ListFilter.new(type: 'control_tag:scope', values: ['nginx', 'apache'])
```
=> Enable control_tag filtering for compliance API calls

.expeditor/create-manifest.rb, components/ingest-service/grpc/grpc.go
Also, fix the spelling in a brave comment in ingest-service.
=> create-manifest.rb: print all available environment variables

.expeditor/generate-automate-api-docs.sh
Followup to #1376.
Since building the automate-chef-io package can (and often does) fail when swagger files are updated, changed swagger files should end up in a PR instead of getting merged directly to master.
=> Open PR for updated swagger files instead of committing directly to master

components/automate-ui/src/app/page-components/profile/profile.component.spec.ts, components/automate-ui/src/app/page-components/profile/profile.component.ts, components/automate-ui/src/app/services/chef-session/chef-session.service.spec.ts, components/automate-ui/src/app/services/chef-session/chef-session.service.ts, components/automate-ui/src/app/services/http/http-client-auth.interceptor.spec.ts, components/automate-ui/src/app/services/http/http-client-auth.interceptor.ts
When a 401 was intercepted by the auth interceptor, and not the periodic call in chef-session, the interceptor would call `logout()` without arguments. This used to have two effects:
1. the user is sent back to `/` (or rather, `/dashboards/event-feed`) after re-signin, regardless of where they were before
2. the user has to select their signin method.
This became apparent most obviously when using IAMv2.1, because it has another peridoc call: checking project rules' apply status. So those calls, when failing, would cause no automatic re-login for SAML users, as desired in #1246.
**Now**, the logic is inverted: If nothing is passed, the signin happens as if it was a re-signin: including the proper state for going back to the page, and skipping signin method selection if possible.
⚠️ The …
=> [#1318] proper logout for intercepted 401s

terraform/test-environments/modules/chef_automate_install/main.tf, terraform/test-environments/modules/chef_automate_install/templates/install_chef_automate_cli.sh.tpl
The data-lifecycle-service is gone now. This removes configuring the deprecated config and replaces it with configuration RPC calls.
=> Remove old data lifecycle config from terraform

components/backup-gateway/habitat/hooks/run
This change adds support for starting up backup-gateway for restore-only operations in disaster recovery setups for Automate where volumes are read-only copies of production backups. Current backup-gateway behavior will be unchanged for everyone but those with read-only volumes that were previously unsupported.
Signed-off-by: Josh Hudson <jhudson@chef.io>
=> Add backup-gateway support for read-only backup volumes

.expeditor/generate-automate-api-docs.sh, .expeditor/update-compliance-profiles.sh, .expeditor/update-inspec-version.sh, .expeditor/update_chef_server.sh, .expeditor/update_habitat.sh
Expeditor by default commits any modified files directly to
master. We currently prefer that expeditor open PRs so that we can
evaluate whether the verify tests have passed and whether we want to
make the given change.
Here, we run `git clean -fxd` to avoid anything getting unexpectedly
committed to master.
=> ci: always git-clean when we expect expeditor to open PRs

.expeditor/create-manifest.rb
In expeditor, we have access to the exact package identifiers that
were included in the build group.  We can use these identifiers to
avoid eventual consistency issues we've seen with the Habitat Depot.
We are currently unsure on the exact cause of the inconsistent manifest
creation.  While we think it is the result of caching in the Depot API,
we have been unable to confirm this.
To facilitate hunting it down, I've also added logging for cases where the expeditor
environment doesn't match what is found in the depot:
```
2019-08-30 11:18:37 +0100 WARN: Found mismatch between sources:
2019-08-30 11:18:37 +0100 WARN:    chef/automate-gateway/0.1.0/20190829202630 from expeditor environment
2019-08-30 11:18:37 +0100 WARN:    chef/automate-gateway/0.1.0/20190829202631 from Habitat Depot …
```
=> ci: use expeditor environment to get package idents

lib/cereal/cereal.go
It might be useful to see how long certain tasks took.
The duration here is the time spend in "user code".
=> lib/cereal: log task execution duration

Gopkg.lock, Gopkg.toml, components/automate-dex/habitat/plan.sh, integration/helpers/ssl_filters.jq, vendor/github.com/dexidp/dex/server/api.go, vendor/github.com/dexidp/dex/server/handlers.go
👉 Release notes are here: https://github.com/dexidp/dex/releases/tag/v2.19.0
ℹ️ We're interested in @stevendanna 's ciphersuite changes. (Note: these don't reflect in the vendored sources -- we're only vendoring parts of dex for some tests; the changes are pulled in via the updated `core/dex` habitat package.)
Fixes #1379.
=> deps: bump dex 2.18.0 -> 2.19.0

lib/scaffolding/shared.sh
As can be seen in #1413 and similar previous fixes, we almost always
forget to call the addNoProxy function when adding a new bind.
At the moment, the ceremony around this is completely unnecessary
since we know that we are running all relevant components on the local
machine.  However, the current approach of each bind separately was
put in place when we thought that different services might be living
on different machines.
Adding sys.ip to NORPOXY in the scaffolding will mean that any service
using the scaffoldings can likely omit adding `addNoProxy` lines for
every service bind.
=> scaffolding: Always add sys.ip to NOPROXY

components/applications-service/habitat/hooks/run, components/authz-service/habitat/hooks/run, components/compliance-service/habitat/hooks/run, components/event-feed-service/habitat/hooks/run, components/ingest-service/habitat/hooks/run
The nightlies failed because the application-service had not added the
cereal-service to their NOPROXY environment variable. Other services
had also forgotten to do this, but already had the relevant IP added
to NOPROXY because of other binds.
=> Add cereal-service to NOPROXY

lib/cereal/cereal.go
We register a number of task executors with a single worker. In this
case, we always hit this warning, which makes it less useful.
=> lib/cereal: Don't log max worker warning if max is 1

components/compliance-service/api/reporting/server/server.go, components/compliance-service/reporting/relaxting/nodes.go
When trying to sort by the platform in the compliance section, the release numbers of any platform do not get properly parsed/sorted
**Expected Results**: Sorting by a platform column will sort correctly
https://github.com/chef/automate/issues/752
I have added one sorting function which can help to sort the platform with name and release version.
please find the attached video link below
https://chef.zoom.us/recording/share/WTWPt3eJlLCcjQXsqaX-Zg-WSgN39E0lvjcHDVL5COewIumekTziMw?startTime=1565259570000
=> added changes for sort the platform with name and release version

Gopkg.toml
Before:
```
Petes-MBP:automate pete$ dep ensure -v
Warning: the following project(s) have [[constraint]] stanzas in Gopkg.toml:
✗  golang.org/x/net
However, these projects are not direct dependencies of the current project:
they are not imported in any .go files, nor are they in the 'required' list in
Gopkg.toml. Dep only applies [[constraint]] rules to direct dependencies, so
these rules will have no effect.
Either import/require packages from these projects so that they become direct
dependencies, or convert each [[constraint]] to an [[override]] to enforce rules
on these projects, if they happen to be transitive dependencies.
Petes-MBP:automate pete$
```
After:
```
Petes-MBP:automate pete$ dep ensure -v
Petes-MBP:automate pete$
```
=> Fix dep warning.

components/authz-service/projectassignment/errors.go, components/authz-service/projectassignment/project_assignment.go, components/authz-service/server/v2/authz.go, components/authz-service/server/v2/migration.go, components/authz-service/server/v2/policy.go, components/authz-service/storage/v2/memstore/memstore.go, components/authz-service/storage/v2/postgres/postgres.go, components/authz-service/storage/v2/postgres/postgres_test.go, components/authz-service/storage/v2/storage.go, e2e/cypress/integration/api/iam/02_policies_api.spec.ts, e2e/cypress/integration/api/iam/03_roles_api.spec.ts
Follow up to https://github.com/chef/automate/pull/1340, which implemented the framework and enforcement for role creation and update.
Setup admin token and some projects:
```
chef-automate iam upgrade-to-v2 --beta2.1
export ADMINTOK=`chef-automate iam token create admin --admin`
curl -H "api-token: $ADMINTOK" -XPOST -d '{"name":"project1", "id":"project1"}' https://a2-dev.test/apis/iam/v2beta/projects --insecure
curl -H "api-token: $ADMINTOK" -XPOST -d '{"name":"project2", "id":"project2"}' https://a2-dev.test/apis/iam/v2beta/projects --insecure
```
Make a non-admin token and grant it access to a single project:
```
export PLEBTOK=`chef-automate iam token create plebtoken`
```
setup-policy.json:
```
{
"name": "token-access-project-1", …
```
=> [AUTH-1256] Enforce project assignment permissions for policy create and update on IAM v2.1

components/automate-ui/src/app/services/projects-filter/projects-filter.effects.ts
There is a periodic `introspect_projects` call to populate the global projects filter--irrespective of the IAM version. This should only be happening for IAM V2p1. This PR adds a guard function based on IAM version to accomplish that.
NA
No `introspect_projects` calls on V1 or V2.
Login.
Try each IAM version successively:
```
```
Open dev tools >> network in your browser and notice that the introspect project calls only occur when on v2p1.
=> Prevent introspect_projects call unless IAM V2p1 or greater

components/automate-deployment/a1-migration/Dockerfile, components/automate-deployment/basic-a1/Dockerfile, scripts/nightly_basic_a1.sh, scripts/nightly_migration.sh
The nightlies failed because we hit the 30 minute timeout set in our
buildkite configuration. The logs showed that various apt-get
operations were suddenly taking much longer to download packages:
```
Fetched 65.1 MB in 6min 54s (157 kB/s)
Fetched 26.3 MB in 9min 48s (44.7 kB/s)
```
compared to previous runs:
```
Fetched 65.1 MB in 1min 44s (620 kB/s)
Fetched 26.3 MB in 23s (1108 kB/s)
```
I didn't do an investigating into the cause of the slow-down, but it
seems prudent to use a repository mirror closer to our CI system.
This PR changes our apt-sources list in the docker build step of these
tests to use the us-west-2 repository mirrors.
Further, it adds logging to make it easier to spot which section of
the job is taking a long time.
We should consider uploading these images to dockerhub …
=> nightlies: Use EC2-based apt mirror, add logging

terraform/test-environments/modules/chef_automate_install/templates/install_chef_automate_cli.sh.tpl
These logs are hard to read, this helps a little.
=> ci: avoid hab progress bars in terraform output

components/automate-ui/src/app/pages/project/list/project-list.component.ts, components/automate-ui/src/app/services/projects-filter/projects-filter.effects.ts
The top-right project filter dropdown **should** display a newly created project immediately.
- #1272 
- start stuff, with the UI rebuilt or using devproxy, upgrade to v2.1beta.
- create a project:
TODO
=> [#1272] refresh global project filter when a new project is created

components/automate-chef-io/content/docs/iam-v2-guide.md
Users may get into trouble if they use deny in custom policies without considering the global impact.
Since we are not expecting DENY in policies to be a common use case, we would like to change up the IAMv2 walkthrough to not center on a DENY example.
Fixes #1121
=> Remove DENY walkthrough examples from IAM v2 Beta documentation

components/applications-service/pkg/server/periodic.go, components/ingest-service/grpc/grpc.go, components/ingest-service/integration_test/suite_test.go, components/ingest-service/server/jobs.go, lib/cereal/cereal.go, lib/cereal/integration/schedule.go, lib/datalifecycle/purge/workflow.go, tools/cereal-scaffold/main.go
This makes it consistent with UpdateWorkflowSchedule and allows the
caller to control any required timeout or cancellation of this create
call.
=> lib/cereal: CreateWorkflowSchedule should take a context

components/automate-chef-io/content/docs/api-tokens.md, components/automate-chef-io/content/docs/authorization-overview.md, components/automate-chef-io/content/docs/configuration.md, components/automate-chef-io/content/docs/iam-v2-api-reference.md, components/automate-chef-io/content/docs/teams.md, components/automate-chef-io/content/docs/users.md
We were using both `TOK` and `TOKEN` throughout the docs, this standardizes to `TOKEN` which is a bit more descriptive.
=> changed TOK to TOKEN in docs

.expeditor/verify.pipeline.yml
The single-use buildkite queue currently has a bug in which machines
are being reused. This poses a problem for some of our jobs since they
run and create files as root. Those files cannot later be cleaned up,
failing the build.
This PR adds a `sudo git clean` step to all such jobs in an attempt to
keep the rate of failures down. `sudo git clean` should clean out the
files that we would fail to clean out on a subsequent run.  We'll want
to pair this with a termination of all existing nodes in the single
use queue.
In the long run, we should consider reworking these tests so that they do
not require the single-use queue or sudo.
=> ci: temporary fix for bug in single-use buildkite queue

components/cereal-service/pkg/server/server.go, lib/cereal/cereal.go, lib/cereal/workflow_scheduler.go
These log messages were getting rather noisy. Let me know if any
particular message seems like it should still be on Info.
=> lib/cereal,cereal-service: Move Info messages to Debug log level

components/automate-cli/cmd/chef-automate/gather-logs.go, components/automate-deployment/habitat/config/config.toml, components/automate-deployment/pkg/gatherlogs/copy.go, components/automate-deployment/pkg/gatherlogs/gatherer.go, components/automate-deployment/pkg/gatherlogs/gatherer_test.go, components/automate-deployment/pkg/server/config.go, components/automate-deployment/pkg/server/gather-logs.go
In server mode, Habitat sets our path for us and we trust that path
elsewhere. In local mode, we think it is likely that the user
has tar, cp, and find on their PATH and that this is causing more harm
than good.
=> deployment-service: stop hard-coding command paths

components/automate-ui/src/styles.scss
Inputs in Automate have a line-height that is causing the descenders of the type to be cut off by a few pixels.
https://app.zenhub.com/workspaces/ui-team-5cba23a3b14fdc05970c8f87/issues/chef/automate/1104
Navigate to a form input
Type in the letter g or something else with a descender and notice that you can't see the full-complete letter
- [x ] Docs added/updated?
=> Add default line-height to input fields

components/automate-ui/src/app/pages/node-noruns-details/node-noruns-details.component.html, components/automate-ui/src/app/pages/node-noruns-details/node-noruns-details.component.scss
The missing-runs page needs the left sidebar updated like the other Client Runs pages.
#1361
The left sidebar on the Client runs missing runs page should match the client runs page (look like below).
1. Add some nodes with chef_load_nodes 10
1. Go to the Client Runs page https://a2-dev.test/infrastructure/client-runs.
1. Select a node.
1. In the URL change the UUID after 'run' to anything. For example https://a2-dev.test/infrastructure/client-runs/d92fbcb5-9ccf-3fed-997f-1f77c2e988b3/runs/incorrect_id
1. Ensure the left sidebar is correct. 
Below is the correct left sidebar
=> Updating client runs missing run date left sidebar

components/automate-ui/src/app/app-routing.module.ts
If a user types in the wrong URL they will be rerouted to the event feed page instead of the client runs page. 
1. Type in an incorrect URL like "https://a2-dev.test/incorrect"
1. Ensure the event feed page opens.
=> Update unknown URL to reroute to event feed page

.studio/applications-service
Our sample data had not been updated since we added application and
environment and was using the service group name to encode this
information (which we recommend against doing) in several places.
The sample data now has an application with serveral services
(mobile-app-api) deployed to two environments which shows how searching
by environment and application can focus the UI on a single deployment.
There are at least two options for all filterable fields in the dataset.
Run `applications_populate_database` in the studio and check out the applications view.
=> Applications sample data more useful for filtering use cases

.expeditor/verify_private.pipeline.yml, e2e/README.md, e2e/cypress/integration/constants.ts, e2e/cypress/integration/ui/compliance/01_ssh_scan_job.spec.ts, e2e/cypress/integration/ui/settings/01_user_mgmt.spec.ts, e2e/cypress/integration/ui/settings/02_team_mgmt.spec.ts, e2e/cypress/integration/ui/settings/03_team_add_users.spec.ts, e2e/cypress/integration/ui/settings/04_team_details.spec.ts, e2e/cypress/integration/ui/settings/05_project_mgmt.spec.ts
Added a conditional itFlaky that will only run tests if CYPRESS_RUN_FLAKY=true is passed when running the cypress tests. Added a set of cypress tasks to run in verify_private that will run the flaky tests in soft_fail mode, while the non-flaky tests are no longer soft_fail.
Will enable in deploy after we are successful in verify_private for a bit.
```
cd e2e
CYPRESS_RUN_FLAKY=true npm run cypress:open
npm run cypress:open
```
=> Re-enable non-flaky cypress tests in verify_private

components/automate-ui/src/app/components/settings-sidebar/settings-sidebar.component.html, components/automate-ui/src/app/components/settings-sidebar/settings-sidebar.component.spec.ts, components/automate-ui/src/app/components/settings-sidebar/settings-sidebar.component.ts, components/automate-ui/src/app/entities/projects/project.effects.ts, components/automate-ui/src/app/page-components/navbar/navbar.component.html, components/automate-ui/src/app/page-components/navbar/navbar.component.spec.ts, components/automate-ui/src/app/page-components/navbar/navbar.component.ts, components/automate-ui/src/app/pages/api-token/list/api-token-list.component.html, components/automate-ui/src/app/pages/api-token/list/api-token-list.component.ts, components/automate-ui/src/app/pages/project/list/project-list.component.html, components/automate-ui/src/app/pages/project/list/project-list.component.spec.ts, components/automate-ui/src/app/pages/project/list/project-list.component.ts, components/automate-ui/src/app/pages/team-add-users/team-add-users.component.ts, components/automate-ui/src/app/pages/team-details/team-details.component.ts, components/automate-ui/src/app/pages/team-management/team-management.component.html, components/automate-ui/src/app/pages/team-management/team-management.component.spec.ts, components/automate-ui/src/app/pages/team-management/team-management.component.ts
This is a cleanup of IAM version selectors in the UI.
A couple recent PRs introduced the new `atLeastV2p1` ngrx/store selector.
Rather than bloat those PRs with unrelated cleanup, though, made all the
rest of it into this separate PR.
1. Uses the new atLeastV2p1 selector in place of the individual
major/minor selectors, bringing the version determination to a
single point of truth, yielding simpler code.
2. Perhaps more importantly, abstracts the notion of "projects enabled"
to all consumers, so that they do not need to care about the specifics of the major and minor versions.
This allows for future version bumps to be much cleaner and simpler.
Now the code has clear distinction between projects
and things that are v1 vs. v2 (e.g. roles, aspects of teams, etc.).
Code looks a little …
=> Clean up IAM v2.1 version checking in UI

.expeditor/verify_private.pipeline.yml
When deploys run a bit slower in Ci this can fail. In a non-scientific
sampling, the last 3 runs of this test suite I've looked at have taken 6.5
minutes, 10 minutes (barely passed before timeout would have kicked in), and
10.5 minutes (failed by timeout).
=> Increase event-gateway test timeout

integration/services/ha_backend/setup.sh
For reasons I'm still investigating, these entries don't exist on my
Docker-for-Mac VMs.
=> ha integration: split out IPv4 sysctls

integration/base.sh, integration/helpers/testing.sh
We already should have inspec via Habitat if we've installed Automate. 
Let's use it from there rather than downloading it again.
=> ci: avoid downloading chefdk

components/automate-ui/src/app/pages/client-runs/client-runs.component.spec.ts, components/automate-ui/src/app/pages/client-runs/client-runs.component.ts
This change allows the client runs page to revert back to the first page of nodes if the page selected does not have nodes. 
This problem was found with the IAM v2 global project filtering feature. When the project filter is updated it refreshes the page. Say the user is on page 2 with 100 nodes per page. If the user updates the project filter to have only 50 nodes then page 2 would be empty. Since the page 2 selection is in the URL after the refresh the user would be left with zero nodes. 
#1341 
The repro steps in issue #1341 are resolved. 
1. Build the changed code and start Automate: `build components/automate-ui && start_all_services`
1. Turn on IAM v2: `chef-automate iam upgrade-to-v2 --beta2.1`
1. Add some nodes to full at least two pages `chef_load_nodes 120`
1. Find the …
=> Client Runs page, detecting bad page selection

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/reporting-overview.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.html
Adding the missing report date in the summary section of the compliance reporting page. Also fixing the interval selection dropbox to display the date range labels. 
This bug was caused in this PR https://github.com/chef/automate/pull/1268
The report date is displayed in the summary section. 
1. `build components/automate-ui` && start_all_services`
1. Go to https://a2-dev.test/compliance/reports/overview
1. Open the summary section and ensure the "Report Date" is shown. 
1. Select to view the "Profile Status" ![Screen Shot 2019-09-11 at 11 40 11 AM](https://user-images.githubusercontent.com/1679247/64725184-ee4a5380-d488-11e9-9ba3-9b4a298326db.png)
1. Ensure the "Control Status Over Time" shows the date interval selection drop box correctly. 
Below shows the problem before this change. …
=> Compliance page: Adding back the report date in the summary

components/automate-ui/src/app/pages/project/rules/project-rules.component.html
There were two primary buttons on this page, _Add Condition_ and _Save Rule_ the ux teams standard is 1 primary button whenever possible. _Add Condition_ is not a primary action, so changing this to a secondary button.
=> changed add condition button to secondary

components/automate-ui/src/app/page-components/date-selector/date-selector.component.html, components/automate-ui/src/app/page-components/date-selector/date-selector.component.ts
Updating the Run History date range closes the right sidebar. to prevent this I have added some code to stop the propagation.
https://github.com/chef/automate/issues/1478
=> prevent to close run history right sidebar

components/compliance-service/api/reporting/server/server.go, components/compliance-service/api/tests/02_nodes_spec.rb, components/compliance-service/api/tests/07_suggestions_control_tags_spec.rb, components/compliance-service/reporting/relaxting/suggestions.go, components/compliance-service/test_data/audit_reports/2018-02-09_debian(2)-zeta-linux(f)-apache(p)-failed.json, components/compliance-service/test_data/audit_reports/2018-03-04_centos(3)-beta-nginx(p)-apache(s)-fake(s)-passed.json
This PR introduces `control_tag_key` and `control_tag_value` compliance API suggestions.
Because of the level of nesting control tags are at, the suggestions happen in two steps:
1. `engram` ElasticSearch query returns a list with all controls that match the text. We get all tags from these controls with a score we can't associate to a particular tag.
2. Tags are then aggregated to reduce duplicates and sorted by score. The `closestmatch` go lib is used to further `engram` search the aggregated tag key or values.
For `control_tag_value` suggestions a `control_tag` filter is required. This will be used to figure out the control tag key for which to do the value suggestions. Example from the tests in this PR:
```
actual_data = GRPC reporting, :list_suggestions, …
```
=> Compliance API suggestion for control tags

components/authz-service/storage/postgres/migration/sql/70_fix_status_for_list_projects.up.sql, components/authz-service/storage/postgres/migration/sql/README.md, components/authz-service/storage/v2/postgres/postgres_test.go, e2e/cypress/integration/api/iam/01_projects_api.spec.ts
Fixing a bug that prevented staged rule deletes from properly modifying the project status to EDITS_PENDING for the ListRules endpoint.
Setup:
```
```
```
{
"projects": [
{
"name": "project1",
"id": "project1",
"type": "CUSTOM",
"status": "NO_RULES"
}
]
}
{
"projects": [
{
"name": "project1",
"id": "project1",
"type": "CUSTOM",
"status": "EDITS_PENDING"
}
]
}
.........
{"state":"not_running","estimated_time_complete":"2019-09-11T17:55:51.121857846Z","percentage_complete":1,"failed":false,"failure_message":""}[12]
{
"projects": [
{
"name": "project1",
"id": "project1",
"type": "CUSTOM",
"status": "RULES_APPLIED"
}
]
}
{
"projects": [
{
"name": "project1",
"id": "project1",
"type": "CUSTOM",
"status": "EDITS_PENDING"
}
]
}
.......
{
"projects": [
{
"name": "project1",
"id": "project1", …
```
=> [AUTH-1501] Rules staged for delete should mark listed projects as EDITS_PENDING

components/automate-ui/src/app/pages/project/list/project-list.component.html, components/automate-ui/src/app/pages/project/list/project-list.component.spec.ts, components/automate-ui/src/app/pages/project/list/project-list.component.ts, e2e/cypress/integration/ui/settings/05_project_mgmt.spec.ts
The rest of the button's behavior should be exactly the same as before.
```
rebuild components/automate-ui-devproxy
```
1. Button is disabled with text `Projects Up-to-date` when no projects
1. Create a project (or multiple)
1. Button still disabled because no pending edits
1. Add a rule to 1 or more projects
1. Button behaves as before
1. Apply projects
1. Button goes back to `Projects Up-to-date` disabled state
=> [AUTH-1477] If there are no projects with pending rule edits, disable the update button with proper text

components/automate-gateway/handler/nodes.go
While investigating #1598 we observed that the creation of a new node
during the diagnostics tests was generating a detect job that always
failed to resolve any nodes.
The incoming node in the case of a Create does not have an ID because
the ID is created after calling the nodemanager service. It is this
newly created ID that should be used to trigger the detect job.  It
appears that BulkCreate already does the right thing. Update also uses
in.ID but in that case I believe the incoming node should already have
an ID set since it is an update.
=> automate-gateway: trigger detect job with newly-created ID

components/automate-chef-io/content/docs/iam-v2-guide.md
Recently, in internal slack we learned about a customer who was on an older version of Automate when they upgraded to iam v2 this caused some bugs we had fixed in later versions. This pr adds a note to the iam v2 docs encouraging users to be on the latest Chef Automate version before upgrading iam.
=> added note about being on the latest automate version before upgrading iam

components/compliance-service/inspec-agent/runner/runner.go
We recently observed the following failure during the diagnostics test suite:
```
[✗] Verifying compliance-scanning
Error Trace:	compliance_report_scan_nodes.go:200
runner.go:50
asm_amd64.s:1337
Error:      	Received unexpected error:
Could not find node 1a728af9-6e92-47fc-8ad2-149ee04e9b4b in usage's list of scanned nodes
github.com/chef/automate/components/automate-cli/pkg/diagnostics/integration.CreateComplianceReportScanNodesDiagnostic.func2.1
/go/src/github.com/chef/automate/components/automate-cli/pkg/diagnostics/integration/compliance_report_scan_nodes.go:195
github.com/chef/automate/components/automate-cli/pkg/diagnostics/integration.Retry
/go/src/github.com/chef/automate/components/automate-cli/pkg/diagnostics/integration/helpers.go:80 …
```
=> compliance-service: increase task executor workers

components/automate-load-balancer/habitat/hooks/reload
=> automate-load-balancer: Don't run reload hook with -x

components/automate-gateway/handler/compliance/reporting.go
This log message can be _very_ large on a machine that reports a lot
of nodes. I don't work in this code often, so I've just moved it to
Debug, but we might consider just logging the count rather then the
full report.
=> automate-gateway: Move license usage log message to debug

components/automate-chef-io/content/docs/configuration.md
Automate now supports external postgres. Remove reference dating to the days when it did not.
Fixes #1539
=> Update docs on configuring external postgres.

Gopkg.lock, Gopkg.toml, vendor/github.com/open-policy-agent/opa/ast/check.go, vendor/github.com/open-policy-agent/opa/ast/compare.go, vendor/github.com/open-policy-agent/opa/ast/compile.go, vendor/github.com/open-policy-agent/opa/ast/fuzz.go, vendor/github.com/open-policy-agent/opa/ast/term.go, vendor/github.com/open-policy-agent/opa/bundle/bundle.go, vendor/github.com/open-policy-agent/opa/bundle/store.go, vendor/github.com/open-policy-agent/opa/internal/file/archive/tarball.go, vendor/github.com/open-policy-agent/opa/internal/file/loader.go, vendor/github.com/open-policy-agent/opa/internal/file/url/url.go, vendor/github.com/open-policy-agent/opa/internal/wasm/encoding/reader.go, vendor/github.com/open-policy-agent/opa/loader/errors.go, vendor/github.com/open-policy-agent/opa/loader/loader.go, vendor/github.com/open-policy-agent/opa/loader/merge.go, vendor/github.com/open-policy-agent/opa/metrics/metrics.go, vendor/github.com/open-policy-agent/opa/rego/rego.go, vendor/github.com/open-policy-agent/opa/topdown/bindings.go, vendor/github.com/open-policy-agent/opa/topdown/builtins.go, vendor/github.com/open-policy-agent/opa/topdown/eval.go, vendor/github.com/open-policy-agent/opa/topdown/query.go, vendor/github.com/open-policy-agent/opa/topdown/tokens.go
We had previously pinned a revision between releases, to get the
performance improvements in quick.
Now, there's been a formal release including those, so let's fix this.
Concretely, these commits are pulled in: https://github.com/open-policy-agent/opa/compare/0d70daa545f5a4bf2e6edf3c1b2d635920299bc9...v0.14.0 -- how the changes affect us code-wise can be gathered from the vendor diff here.
=> deps: bump OPA pre-1.14.0 -> 0.14.0

.expeditor/upload-files.sh
In 54d747bd2ac50e4c158d4dc3d5fd0598cae66e34 we implemented a
mitigation for consistency issues we've seen with the Habitat Depot.
This implements a similar workaround for our uploading automate-cli to
S3.
=> ci: Another workaround for Depot inconsistency

components/automate-deployment/pkg/airgap/bundle_creator.go, components/automate-deployment/pkg/server/restart.go
I noticed this when reading some code. Just a minor style thing.
=> Use 1 << x rather than math.Pow(2.0, float64(x))

components/automate-scaffolding-go/habitat/plan.sh, components/automate-scaffolding/habitat/plan.sh
This should also have the side-effect of rebuilding most
Go services with Go 1.13.
=> Fix pkg_origin for scaffoldings

components/automate-ui/e2e/admin.e2e-spec.ts, components/automate-ui/src/app/entities/userperms/userperms.effects.ts, components/automate-ui/src/app/entities/userperms/userperms.reducer.ts, components/automate-ui/src/app/entities/userperms/userperms.selectors.ts, components/automate-ui/src/app/ui.component.ts, e2e/cypress/support/commands.ts
There are a large number of introspection calls on each page and this continues to grow. That incurs a small--but not negligible--performance penalty. Also, it makes viewing a network trace very cumbersome as there is a lot of "noise" added to the list of network calls. This PR adds some simple caching with time-based degradation to eliminate the vast majority of network traffic but still keep the introspection data in the browser fresh.
N/A
There should be no discernible difference in the exposed UI. However, if you open the network tab of dev tools you can see the effect. In this screen shot I opened Automate on the Dashboards tab. On the very first load, there will be a handful of network calls. (Note that I have filtered the network list to just show introspection calls.)
I then …
=> [Automate-793] Add caching to introspect calls

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-trend/overview-trend.component.scss, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-trend/overview-trend.component.ts, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/reporting-overview.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/reporting-overview.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/reporting-overview.component.ts
Clicking a column on the trend graph selects the focused date. I always have to look down at the trend graph to see where reports are and then go up to the date selector to choose that date. With this change, one does not need to use the date selector. Just click the date on the trend graph. 
#441
Able to update the date selected from clicking the trend graph
1. Load some compliance nodes `chef_load_compliance_scans -N10 -M100 -T10 -D1`
1. Go to https://a2-dev.test/compliance/reports/overview and select dates from the trend graph.
=> Compliance reporting: Select date from the trend graph

components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.ts
Currently, the compliance reports filter search in the UI uses Organization and Chef Tags but this does not align with the names of things in client runs or project ingest rules.
#1498
The compliance reporting search bar has types "Chef Organization" and "Chef Tag"
1. Open https://a2-dev.test/compliance/reports/overview
1. Check the search bar types are correct.
=> Changing compliance reporting search bar type names

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-failures/overview-failures.component.scss, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-failures/overview-failures.component.ts, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/reporting-overview.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/reporting-overview.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/reporting-overview.component.ts
When clicking one of the bubble graphs ("Top Platform Failures", "Top Environment Failures", "Top Profile Failures", and "Top Control Failures") on the compliance reporting overview page
#441
Able to filter from clicking the bubble graph on the compliance reporting overview page. 
1. Load some compliance nodes `chef_load_compliance_scans -N10 -M100 -T10 -D1`
1. Go to https://a2-dev.test/compliance/reports/overview and select a bubble from the four bubble graphs. "Top Platform Failures", "Top Environment Failures", "Top Profile Failures", and "Top Control Failures"
=> Making compliance overview bubble graphs clickable

lib/cereal/cereal.go, lib/cereal/postgres/task_cleaner.go, lib/cereal/postgres/task_pinger.go, lib/cereal/start_guard.go, lib/cereal/task_dequeue_pool.go
We were using WaitGroup to help ensure that we weren't calling Start()
wasn't called twice on various structs that manage long-lived go
routines.
This replaces those uses with a new type, StartGuard, that allows us
to customize the message that users (developers) will get when they
make this mistake.
We could have done this with recover, but this felt a big better.
=> lib/cereal: Add StartGuard to replace WaitGroup-based start checks

components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/report-query.service.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.spec.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.ts
Fixing a bug where the compliance reporting page would not allow the user in UTC+1 view the current day. The problem was the reportQuery state was being changed unintentionally. There was also some sections of code that when converting from moment to date was switching the current hour because of time zones. 
When in timezone UTC+1 the current date can be selected. 
1. Switch your local computer to London time (UTC+1)
1. Open the https://a2-dev.test/compliance/reports/overview
1. Ensure today's UTC date is selected. 
1. Ensure the date can be switched to yesterday back to today.
=> Fixing time zone problems

components/automate-ui/src/app/pages/+compliance/+scanner/containers/nodes-list/nodes-list.component.scss
It looks that currently, we are utilizing the side drawer only for the Error message on this Nodes view. Since that is the only thing we are doing on this page, we may be able to just word wrap the whole message, and we can cover the whole side drawer with the message.
I have added CSS changes for word warp the error message. 
1. `rebuild components/automate-ui-devproxy`
1. inside studio `CHEF_USERNAME=username scripts/get_secrets.sh` if you haven't in a while
1. outside of studio `source dev/secrets-env.sh`
1. outside of studio `A2_URL='https://a2-dev.test' A2_TOKEN='token_val' components/compliance-service/scripts/create-pg-data.sh`
https://github.com/chef/automate/issues/285
Node connectivity error is easier to read
=> word wrap the connectivity error message for node

components/automate-ui/src/app/page-components/user-table/user-table.component.html, components/automate-ui/src/app/pages/user-management/user-management.component.html, e2e/README.md, e2e/cypress/integration/ui/compliance/01_ssh_scan_job.spec.ts, e2e/cypress/integration/ui/settings/01_user_mgmt.spec.ts, e2e/cypress/support/commands.ts
1) Attempting to use a cy bind to make the test less flaky. Theory is other instances of 'Create User' on the page might be causing flakiness. Also added a comment about paying attention to how you use data-cy in re-useable components. We should never be using the component in question in the same page twice so we should be fine here but a good thing to be aware of.
2) Also added a check to make sure both global and parameterized introspection calls return as part of login helper.
3) Marked the remainder of the ssh scan job tests as flaky since they've been flaking :(
=> Use a cypress bind to make user mgmt test less flaky

components/automate-ui/src/app/entities/service-groups/service-groups.effects.ts, components/automate-ui/src/app/entities/service-groups/service-groups.model.ts, components/automate-ui/src/app/entities/service-groups/service-groups.requests.ts, components/automate-ui/src/app/pages/service-groups/service-groups.component.ts
1531
When filters are applied through the search bar,
update the count in the health status filters above the table
update the pagination under the table
1296
When using the filter bar, we want to only show matching services on the right side detail panel. This should help users focus on only the services they are actually interested in; for example, when filtering on site, users only wish to see services from the given site.
https://app.zenhub.com/workspaces/ui-team-5cba23a3b14fdc05970c8f87/issues/chef/automate/1296
https://app.zenhub.com/workspaces/ui-team-5cba23a3b14fdc05970c8f87/issues/chef/automate/1531
1296
A service group where all services match the given criteria is shown unchanged compared to the unfiltered view, and all of its services appear in the right-side panel;
A service …
=> Automate 1531, 1296 Pass filters

tools/cereal-scaffold/echo_workflow.go, tools/cereal-scaffold/main.go
This heavily commented workflow serves as a bit of
documentation-by-example of how to use cereal. I've replaced the
existing simple-workflow since they mostly overlapped.
You can run this with:
```
~/go/src/github.com/chef/automate > cd lib
~/go/src/github.com/chef/automate/lib > make setup_docker_pg
~/go/src/github.com/chef/automate/lib > export PG_URL="postgresql://postgres@127.0.0.1:5432/cereal_test?sslmode=disable&timezone=UTC"
~/go/src/github.com/chef/automate/lib > export PG_ADMIN_URL="postgresql://postgres@127.0.0.1:5432/template1?sslmode=disable&timezone=UTC"
~/go/src/github.com/chef/automate > cd ..
~/go/src/github.com/chef/automate > go build ./tools/cereal-scaffold
~/go/src/github.com/chef/automate > ./cereal-scaffold reset-db cereal_test
~/go/src/github.com/chef/automate > …
```
=> cereal-scaffold: Use heavily-commented Echo workflow

components/automate-ui/README.md
The current version being return from .nvmrc is 10.15.2. Updated requirements section to reflect.  Also updated the NVM link to route to the most current NVM github page.
=> Update Node and NPM version in README.md

components/automate-ui/src/app/entities/projects/project.reducer.ts, components/automate-ui/src/app/entities/rules/rule.selectors.ts, components/automate-ui/src/app/pages/project/details/project-details.component.html, components/automate-ui/src/app/pages/project/details/project-details.component.scss, components/automate-ui/src/app/pages/project/details/project-details.component.spec.ts, components/automate-ui/src/app/pages/project/details/project-details.component.ts, e2e/cypress/integration/ui/settings/05_project_mgmt.spec.ts
Also added a message for the empty rules UI in the case that there are deletes pending (needs Susan's review)
1)Create two rules in a new projects
2)Apply both rules
3) Go to project and delete one rule, see `Edits are pending...`
4) Delete second rule, see empty UI case and see `Deleted rules are pending...`
@susanev Added a case into the no rules UI. If there are no rules but there are staged deleted rules, it will have the extra message below:
=> [AUTH-1501] Updated project details page to display pending edits message when rule deletes are staged

.expeditor/verify_private.pipeline.yml, components/automate-chef-io/Makefile, components/automate-chef-io/scripts/clone_hugo.sh, scripts/verify_build.sh
I'm seeing Ci failures like this for the `lint Hugo site` job:
```
git clone https://v1.d3b2785e6371bcc6d4637cb5a26cd4363ab8e8f2@github.com/chef/chef-hugo-theme.git themes/chef
--
  | Cloning into 'themes/chef'...
  | Password for 'https://v1.d3b2785e6371bcc6d4637cb5a26cd4363ab8e8f2@github.com': # Received cancellation signal, interrupting
  | 🚨 Error: The command exited with status -1
```
can lint the Hugo site in Ci
=> Weird Ci Failures.... U Hate 2 See it

components/automate-gateway/handler/authz.go, components/automate-gateway/handler/authz_test.go, components/automate-ui/src/app/entities/userperms/userperms.effects.ts
The recent PR that introduced introspection caching introduced a bug that caused permission-based routing to fail for non-admin users.
This manifested as a mostly blank screen when navigating to settings:
There were actually two problems:
First, this revealed a bug in `IntrospectAll`. Some time ago all introspection methods were changed to allegedly return all requested endpoints, whether they had any permissions on them or not. This worked for `Introspect(One)` and `IntrospectSome` but it turns out not for `IntrospectAll`.
The `LandingComponent`, which does permission-based routing to the first page amongst a set of pages for which the user has permission, waits until all of the pages on its list are accounted for in the ngrx store, but because of the bug in `IntrospectAll` that never …
=> Introspection fixes for perm-based routing

components/automate-ui/src/app/components/calendar/calendar.component.html, components/automate-ui/src/app/components/calendar/calendar.component.scss, components/automate-ui/src/app/components/calendar/calendar.component.spec.ts, components/automate-ui/src/app/components/calendar/calendar.component.ts, components/automate-ui/src/app/pages/+compliance/+reporting/reporting-searchbar/reporting-searchbar.component.ts, components/automate-ui/src/app/pages/component-library/demos/demo-calendar/demo-calendar.component.ts
This change fixes the problem on the compliance page if you attempt to change the date using the Calendar popup it takes you to the wrong date when clicking on one of the grey'd out days for the previous or next month. 
#1469
The calendar selects the correct date when days for the previous and next month are selected. 
1. Go to https://a2-dev.test/compliance/reports/overview and select dates in the search bar. 
Before
After
As you can see below what was also add is the highting and curser change.
=> Fix selecting a date outside current month

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-trend/overview-trend.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-trend/overview-trend.component.ts
The problem this PR is trying to fix is, when a user has their local timezone set to any time larger that UTC the trend graph shifts each column one day ahead. This can be seen better in the screenshot below. 
This problem was caused by a timezone shift. The data sent from the API has the dates like this '2019-09-14T23:59:59Z'. When this time was parse into a date object it would be '2019-09-15T00:59:59GMT+01:00'. Therefore the 15th would be displayed and not the 14th. 
Similar timezone problems. 
https://github.com/chef/automate/pull/1624
When a user has local timezone UTC +1 the trend graph does not shift the columns one day ahead. 
1. Switch your local computer time to UTC +1 (London)
1. Add some compliance nodes with …
=> Fixing wrong trend graph date with time zone + UTC

components/automate-ui/src/app/components/projects-dropdown/projects-dropdown.component.spec.ts, components/automate-ui/src/app/components/projects-dropdown/projects-dropdown.component.ts
This change updates the default sorting of the projects dropdown component so that when a user views their projects in a dropdown, they see them sorted Normally.  This matches our tables as well as the sorting we use in some of our other components.
[[A2-338] fix admin UI list sorting](https://github.com/chef/a2/pull/4434)
The dropdown is sorted Normally.  First by numbers, and then Alphabetically.
Visually -
1. `build components/automate-ui-devproxy && start_all_services`
2. Navigate to https://a2-dev.test/settings/tokens
3. Create an API Token
4. Navigate to https://a2-dev.test/settings/projects
5. Create several projects
6. Navigate to https://a2-dev.test/settings/tokens/ your-api-token
7. Click on the projects dropdown to see your projects sorted normally.
Using the specfile
1. Run …
=> Projects in dropdown should be Normally sorted

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profile/reporting-profile.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profile/reporting-profile.component.ts
Fixing the 'getNodes' function to add filters correctly. With the 1268 PR filters changed from an array of 'any' to a defined interface 'ReportQuery'. 
PR that introduced the bug - https://github.com/chef/automate/pull/1268
https://github.com/chef/automate/issues/1648
Nodes are loaded in the right sidebar from the profile's page. 
1. Add some compliance nodes `chef_load_compliance_scans -N100 -D10 -M1 -T1000`
1. Go to https://a2-dev.test/compliance/reports/profiles.
1. Click on the "Scan Results" button for one of the profiles. 
1. Ensure a list of nodes appears in the right sidebar
=> Fixing get nodes to concat filters on correctly

components/applications-service/integration_test/services_by_sg_test.go, components/applications-service/integration_test/services_test.go, components/applications-service/pkg/server/server.go, components/applications-service/pkg/storage/postgres/services.go
Services can be filtered by disconnected status. This will support filtering services on the right side detail panel by disconnectedness in a future UI update.
Also, the count of disconnected services is included in the health counts part of the `GetServicesBySG` response; this number will be shown on the filter button for disconnected services in the UI.
#1191 
Build applications service, start all services, run `applications_populate_database` to create sample data.
Run this to show the disconnected services in the given service group:
```
export T=$(get_admin_token)
curl -k -H "api-token: $T" https://a2-dev.test/apis/beta/applications/service-groups/9162d5b1ca807573a74f635a881f120d699512f6620a1c758217886147e2aa27?filter=disconnectedStatus:disconnected |jq
```
It should initially be …
=> Filter services by disconnected status

components/automate-chef-io/Makefile, components/automate-chef-io/README.md, components/automate-chef-io/habitat/plan.sh
Building the docs with the latest version of `go-swagger` fails. Anyone doing `brew install go-swagger` today will get a different version than I used initially and that wasn't specified anywhere, so I added the version we're expecting to the README.
=> Depend on latest version of go-swagger.

components/authn-service/tokens/mock/erroronly.go, components/authn-service/tokens/mock/mock.go, components/authn-service/tokens/pg/adapter.go, components/authn-service/tokens/pg/pg_test.go, components/authn-service/tokens/types/types.go, components/teams-service/storage/conformance/conformance_test.go, components/teams-service/storage/memstore/memstore.go, components/teams-service/storage/postgres/postgres.go, components/teams-service/storage/storage.go
Implements the database functions for teams and tokens to purge a project from any entry
Will be used in [this branch](https://github.com/chef/automate/compare/auth-1471/project-deletion-from-domains?expand=1) soon. For now, just running the database tests.
=> PurgeProject for teams and tokens

.expeditor/build.habitat.yml, .expeditor/verify_private.pipeline.yml, components/automate-chef-io/scripts/clone_hugo.sh
In the previous fix I was under the mistaken impression that only App
tokens supported the x-access-token prefix, but I've now tested this
with personal access tokens as well and it appears they both work with
that as the username. Using this single method will hopefully keep us
a bit more consistent.
This hopefully also fixes the build issues as the core problem was
that I forgot to rename the environment variable in that pipeline.
> There may be times when we are powerless to prevent injustice, but
> there must never be a time when we fail to protest.
>
> -Elie Wiesel
=> More github access token fixes

components/compliance-service/test_data/audit_reports/send_to_data_collector.sh
```bash
cd automate/components/compliance-service/test_data/audit_reports/
./send_to_data_collector.sh https://my-automate.example.com hJueQcP-6RXYD0ocrGDBJ7EoROY=
```
Will send all compliance reports from `audit_reports` to the  data collector of the specified Automate server, modifying the date of the reports to fit the date range displayed by Automate.
=> Add script to send test audit reports to automate endpoint

.expeditor/buildkite/cypress.sh, .expeditor/verify_private.pipeline.yml, e2e/README.md, e2e/cypress.json, e2e/cypress/fixtures/converge/avengers1.json, e2e/cypress/fixtures/converge/xmen1.json, e2e/cypress/fixtures/converge/xmen2.json, e2e/cypress/index.d.ts, e2e/cypress/integration/api/iam/01_projects_api.spec.ts, e2e/cypress/integration/api/iam/02_policies_api.spec.ts, e2e/cypress/integration/api/iam/03_roles_api.spec.ts, e2e/cypress/integration/api/iam/04_teams_api.spec.ts, e2e/cypress/integration/api/iam/05_iam_integration.spec.ts, e2e/cypress/integration/constants.ts, e2e/cypress/integration/ui/settings/01_user_mgmt.spec.ts, e2e/cypress/integration/ui/settings/02_team_mgmt.spec.ts, e2e/cypress/integration/ui/settings/03_team_add_users.spec.ts, e2e/cypress/integration/ui/settings/04_team_details.spec.ts, e2e/cypress/integration/ui/settings/05_project_mgmt.spec.ts, e2e/cypress/support/commands.ts, e2e/package-lock.json, e2e/tsconfig.json, integration/tests/cypress_e2e.sh
Added some extra due diligence tests to ensure ingest project rules get correctly applied to infra nodes for each available attribute.
EDIT: starting with [this commit](https://github.com/chef/automate/pull/1659/commits/33ac8baa0e09daf1daa613b0f29cd72a8c7d83a0), I also refactored our API-only tests so they don't have to open the browser to log in. That should save some test run time!
follow-up issue adds Compliance node and Event test coverage: https://github.com/chef/automate/issues/1594
- tests pass
[how to run cypress tests locally](https://github.com/chef/automate/blob/master/e2e/README.md#running-cypress-locally)
=> [automate-1618] expand ingest rule integration tests + refactor tokens in API-only tests

api/config/deployment/automate_config.go, api/config/deployment/automate_config_test.go
We've previously deprecated some configuration values, however they are still persisted internally in order to migrate the values after upgrade. This change redacts their values from showing up when a user does `chef-automate config show`, allowing users to more easily `chef-automate config show` and `chef-automate config set` without having to remove deprecated keys manually.
=> [config] redact deprecated configuration

.studio/license-control-service
The recent High-Availability changes included changing the implementation of how licenses are handled but the hab studio helper was missed. This brings `remove_dev_license` up-to-date.
NA
In hab studio, you can use `remove_dev_license` to remove a developer license for testing.
Either restart hab studio or just source the changed file directly (`. .studio/license-control-service`).
Invoke `remove_dev_license`.
Then in the browser login or refresh and you should get a licensing prompt.
=> Update hab helper remove_dev_license

components/compliance-service/docs/adding_test_data.md
Updated the Readme for adding data.  Previously adding Node credentials required sending `beta` to the browser.  This is no longer necessary.
=> Remove 'beta' requirement where no longer needed

components/automate-ui/src/app/pages/+compliance/+reporting/reporting-searchbar/reporting-searchbar.component.ts, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.ts
Fix a bug where the calendar selects the day before. 
The two PR that caused the problem
https://github.com/chef/automate/pull/1638
https://github.com/chef/automate/pull/1610
1. Open https://a2-dev.test/compliance/reports/overview
1. Test that the calendar selects the date that is clicked. 
Below is showing the bug. When the 24th is clicked the 23 will be selected.
=> Passing date as a string

components/authz-service/storage/postgres/migration/sql/71_sync_query_projects_with_query_project.up.sql, components/authz-service/storage/postgres/migration/sql/README.md
Mirror recent changes to `query_project` (singular) back to `query_projects` (plural) for consistency, (while still fresh).
NA
Everything should still work.
=> Resync query_projects function

.expeditor/verify_private.pipeline.yml, components/automate-cli/cmd/chef-automate/diagnostics.go, components/automate-cli/pkg/diagnostics/context.go, components/automate-cli/pkg/diagnostics/integration/cfgmgmt_actions.go, components/automate-cli/pkg/diagnostics/integration/cfgmgmt_ccr.go, components/automate-cli/pkg/diagnostics/integration/compliance_report.go, components/automate-cli/pkg/diagnostics/option.go, components/es-sidecar-service/pkg/elastic/snapshot.go, integration/base.sh, integration/helpers/testing.sh, integration/tests/backup.sh
Restores seem to fail if you have too many indices. This is an attempt to find alternatives / skip calls that put indexes in the URL
=> Restore with many indices

api/config/deployment/automate_config.go
These missing nil checks could cause panics.
=> automate-cli: nil-check config before redacting it

components/automate-chef-io/layouts/shortcodes/danger.html, components/automate-chef-io/layouts/shortcodes/info.html, components/automate-chef-io/layouts/shortcodes/success.html, components/automate-chef-io/layouts/shortcodes/tip.html, components/automate-chef-io/layouts/shortcodes/warning.html
Content within warnings, tips, and other content blocks highlighted by hugo shortcodes was not displaying the proper format. For example, words were not being italicized within a warning block, but instead showing underscores (`_two_`). Hyperlinks were also not properly displaying. Research found that adding markdownify allowed for the content to be rendered properly within the shortcodes, so all shortcode files were updated.
N/A
If it builds, 🆗 !
Spin this PR up with `make serve`!
- [ x ] Docs added/updated?
=> Docs Website Formatting Fix

components/automate-ui/src/app/pages/+compliance/+reporting/reporting-searchbar/reporting-searchbar.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/reporting-searchbar/reporting-searchbar.component.ts, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.ts
InSpec provides a mechanism that can be used for 'grouping' controls across profiles (tags)
Users would like to filter their set of nodes being scanned in Automate by selecting a control tag, so they can narrow their query to a group of controls across several profiles.
https://github.com/chef/automate/issues/1311
Can search (get suggestions and filter on) control tags in Automate
chef_load_compliance_scans -N20
=> Add control_tag filters to reports search bar 

scripts/git_difference_expression.rb
This makes it possible to do something like:
GIT_DIFF_BASE=20190904132002 ./scripts/changed_components.rb
which can come in handy.
=> Add ability to set base ref for git_difference_expression

.expeditor/publish-release-notes.sh
This change is required now that we execute all GitHub actions with the chef-expeditor GitHub App. More details at:
https://chefio.slack.com/archives/C09U1TA1Z/p1568905267009200
=> Clone Release Notes wiki with correct GitHub Auth

components/compliance-service/api/tests/07_suggestions_control_tags_spec.rb, components/compliance-service/reporting/relaxting/suggestions.go
Fixes @vjeffrey 's reported bug:
=> For control_tag value suggestions, prefer control tag keys without values

components/compliance-service/compliance.go, components/event-feed-service/pkg/grpc/grpc.go, components/event-feed-service/pkg/server/jobs.go, components/ingest-service/server/jobs.go, components/ingest-service/server/purge.go, lib/datalifecycle/purge/workflow.go
A recent CI failure revealed we were not correctly purging data. This
was the result of registering our workflow executor under the wrong
name. We were registering the workflow executor under the name of the
"workflow instance" rather than the "workflow".
This fix should result in the purge operation running as expected
again.
As follow up work we need to add a test for purge operations and make
it much harder to make this mistake.
=> datalifecycle: register correct workflow executor

components/authz-service/constants/v2/constants.go, components/authz-service/server/v2/system.go, components/authz-service/storage/postgres/datamigration/sql/11_remove_iam-members-viewer_role.up.sql, components/authz-service/storage/postgres/datamigration/sql/README.md, inspec/a2-iam-v2-integration/controls/base.rb, inspec/a2-iam-v2p1-only-integration/controls/role_projects.rb
Removing `iam-members-viewer` role as it has already been accounted for in the `project-owner` role and is no longer needed.
See https://github.com/chef/automate/issues/1722 for details.
`iam-members-viewer` no longer shows up in the list of roles in the UI.
```
```
View the roles page in the UI (Settings >> Roles).
=> [automate-1722] Delete iam-members-viewer role

components/automate-deployment/pkg/converge/converger.go
We increased this timeout from 30s to 60s. However, for the
deployment-service, almost all reconfigure requests go through this
code path because most of our configuration is not written to habitat
templates.
=> deployment-service: Only wait 30 seconds for HUP

api/config/scripts/grpc.sh, components/automate-deployment/scripts/grpc.sh
This bumps the protoc version guard to the latest available via
Habitat.  Rebuilding all protos with the version produced no changes.
=> protos: bump guard for protoc version

components/automate-cli/cmd/chef-automate/gather-logs.go, components/automate-deployment/pkg/gatherlogs/copy.go, components/automate-deployment/pkg/gatherlogs/gatherer.go, components/automate-deployment/pkg/server/gather-logs.go
Fixes:
- Go through es gateway for elasticsearch logs
- limit log lines for `/var/log/messages` and `/var/log/syslog`
- We shouldn't gather anaconda logs (these were happening because they had syslog and messages)
Fixes #611
Fixes #1530
=> Gatherlogs fixes

components/applications-service/integration_test/disconnected_services_job_test.go, components/applications-service/integration_test/suite_test.go, components/applications-service/pkg/server/periodic.go
We have seen some flakey tests around disconnected services within
the applications service, it is suspected that the periodic job that always
runs is interfereing with the tests every once in a while.
The mark disconnected services periodic job is a mandatory job,
but we can turn it off before and after running integration tests during the
suite setup. Then we turn it on for testing the periodic jobs again.
There is no way to test this, we just keep an eye out for failing tests over the next week or so.
=> Turn off periodic test during integration test to reduce flakiness

lib/datalifecycle/purge/workflow.go
=> lib/datalifecycle: w.Fail always needs to be returned

components/es-sidecar-service/Makefile
These don't appear to be necessary and removing them helps us keep the
various projects a bit more consistent.
=> es-sidecar-service: remove custom linter args

components/compliance-service/reporting/relaxting/depth.go
This change fixes funcs with naked returns which, at times, shadow the variables before returning
=> fix funcs so that they don't shadow variables that are returned

components/compliance-service/Makefile, components/compliance-service/api/reporting/server/server.go, components/compliance-service/dao/pgdb/jobs.go, components/compliance-service/reporting/relaxting/depth.go
This removes most of the findings of the nakedret linter which was the
last custom lint configuration for the compliance-service. The one
case that I ignored requires someone more familiar with the compliance
service to decide what to do with some of the error cases.
=> compliance-service: remove most nakedret findings

components/event-service/cmd/event-service/commands/send-test.go, components/event-service/cmd/event-service/commands/serve.go, components/event-service/nats/server.go
This service doesn't have any unit/static tests so I haven't
integrated the linter, but I noticed that there were only a couple of
violations using our current linter configuration and they were mostly
in test code so they were pretty low risk to fix.
=> event-service: fix minor lint violations

components/automate-ui/src/app/pages/+compliance/+scanner/containers/nodes-list/nodes-list.component.html, components/automate-ui/src/app/pages/+compliance/+scanner/containers/nodes-list/nodes-list.component.ts
A now unnecessary API call was being made when a user looked at their failed
node information in the sidebar.  Now that the information is already available
we can snag that same information from an object that already exists on initialization of the component.
A new public variable was added to store the selected failed node information when the user clicks on the `Error` button from the Scan Jobs List.  The Sidebar now reads information from this failed node variable instead.
Extra API Call removed from UI when looking at failed node information.
1. build components/automate-ui-devproxy
2. Navigate to https://a2-dev.test/compliance/scan-jobs/nodes?page=1
( You may need to Add Nodes to scan - any basic bad info will do)
3. Open devtools and inspect the network tab.
4. Click on `Error` …
=> Reconfigure node sidebar to cut out API call

integration/tests/manual_upgrade.sh
This test suite downloads the manifest from a special test scaffolding
that pretends to be packages.chef.io. Since we don't have access to
the key (and don't want access to the key) we can't sign the manifest
in this test.
Manifest verification was already disabled for deployment-service in
this test suite, this disables it for automate-cli.
=> ci: don't verify manifest in manual upgrade test

lib/cereal/cereal.go
Commit 677ddc94774df0c406bdc6642d653d8139094992 converted ingest
service to using the cereal library's SingleTaskWorkflow. This
resulted in us seeing the following error in the application log:
ingest-service.default(O): time="2019-10-08T19:24:30Z" level=error
msg="failed to get task result" error="unexpected end of JSON
input"
The task executors return a nil result in the case of success. The
json module does not expect to unmarshal from empty byte slices.
While we had a nil check in our Get() method for TaskResultData, we
did not account for a non-nil but empty slice.
=> cereal: allow empty task result in SingleTaskWorkflow

.expeditor/coverage/automate-ui.sh
Code coverage fails to run if ui-lib assets are not installed.
(This same issue was fixed for the main build previously
on commit b4042b3d1923c15f1262ef60ac1cc6d60454c041.)
The pipeline failure first occurred here, with the Angular upgrade:
https://buildkite.com/chef/chef-automate-master-code-coverage/builds/1007#58d2bc39-f9dc-49d4-bcf1-2f41db8ed235
Error Text:
```
ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--15-3!./src/styles.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Failed to find 'assets/chef-ui-library/chef/chef.css'
in [
/workdir/components/automate-ui/src
]
at …
```
=> Code coverage fix due to Angular upgrade

.expeditor/coverage/automate-ui.sh
My previous attempt replaced a line when I should have added a line. This reinstates that needed line.
https://github.com/chef/automate/pull/1824
code_coverage pipeline reports no errors
=> Fix to code_coverage pipeline

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-controls/reporting-controls.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-controls/reporting-controls.component.scss, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-controls/reporting-controls.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-controls/reporting-controls.component.ts, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-controls/reporting-controls.module.ts, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-controls/reporting-controls.routing.ts, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.routing.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/report-data.service.spec.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/report-data.service.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.spec.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.ts
Add controls list tab to the compliance reporting view.
https://github.com/chef/automate/issues/1310
A controls tab is available at `https://a2-dev.test/compliance/reports/controls` that displays a filterable list of controls.
1. Navigate to https://a2-dev.test/compliance/reports/controls.
2. See list of controls.
3. Modify report filters via searchbar and/or other filter controls in reporting view.
4. See list of controls update accordingly.
=> Add controls list tab to compliance reporting view

components/automate-ui/src/app/components/settings-sidebar/settings-sidebar.component.html
Before, logged in as `editor`:
After, logged in as `editor`:
- log in as editor, see `Access Management` heading on settings page
=> Fix Access Management heading render

.expeditor/buildkite/cypress.sh, e2e/README.md, e2e/cypress.json, e2e/cypress/index.d.ts, e2e/cypress/integration/api/iam/01_projects_api.spec.ts, e2e/cypress/integration/api/iam/02_policies_api.spec.ts, e2e/cypress/integration/api/iam/03_roles_api.spec.ts, e2e/cypress/integration/api/iam/04_teams_api.spec.ts, e2e/cypress/integration/api/iam/05_iam_integration.spec.ts, e2e/cypress/integration/constants.ts, e2e/cypress/integration/ui/common/01_login.spec.ts, e2e/cypress/integration/ui/common/02_global_filter.spec.ts, e2e/cypress/support/commands.ts, e2e/cypress/support/index.ts
Mission: get cypress running on the deploy pipeline again. 
These tests stopped running after I added a dependency on the environment variable `CYPRESS_ADMIN_TOKEN` and mistakenly assumed I could use `chef-automate` in the deploy pipeline script to get that token. 😩 
Now I've added a before block that always runs before all of the Cypress tests. It checks to see if the admin token was provided in the env, and if not, generates one.
to run locally without passing an admin token: 
```
cd e2e
CYPRESS_IAM_VERSION=v2.1 CYPRESS_BASE_URL=https://a2-dev.test npm run cypress:open
```
=> [cypress] fix cypress tests in deploy pipeline

components/authz-service/server/v2/policy.go, components/authz-service/server/v2/policy_test.go, components/authz-service/storage/v2/memstore/memstore.go
We want installs on IAM v2.0 to be auto-upgraded to IAM v2.1. That will now happen on authz server restart.
IAM v1.0 will not be affected.
Need to rebase on this before integration tests will pass:
https://github.com/chef/automate/pull/1861
This change is bit easier to test before we rebase on this PR https://github.com/chef/automate/pull/1861 since we can still use the CLI to get into v2.0 mode:
Auto-upgrades from v2.0 to v2.1
```
IAM v2.0
...
IAM v2.1
```
Doesn't auto-upgrade on v1.0 but does on v2.0:
```
Resetting to IAM v1.0 (with pre-upgrade v1 policies)...
IAM v1.0
IAM v1.0
IAM v2.0
IAM v2.1
```
=> Auto-upgrade installs on 2.0 to 2.1 on authz server startup

components/es-sidecar-service/pkg/elastic/snapshot.go
This seems to cause problems in large clusters (#1871) and shouldn't
affect any internal ES use cases as there is nowhere to relocate to
=> Don't wait for shards to relocate

.bldr.toml, components/nodemanager-service/api/manager/server/server.go, components/nodemanager-service/api/nodes/server/server.go, components/nodemanager-service/pgdb/filtering.go, components/nodemanager-service/pgdb/nodes.go, components/nodemanager-service/pgdb/nodes_integration_test.go, components/nodemanager-service/tests/project_filtering_test.go, components/nodemanager-service/tests/project_requests_test.go
Adding project filtering to the "api/v0/nodes/search"/List RPC function. This is needed before IAMv2 GA because the nodemanager stores both ingested nodes and manually added nodes. These changes filter the ingested nodes only. The manually added nodes will not be filtered by the project tags in the context object. 
#1894
All ingested client run and compliance nodes are filtered by projects. 
1. `build components/nodemanager-service && start_all_services`
1. Turn on IAMv2.1 `chef-automate iam upgrade-to-v2 --beta2.1`
1. Ingest some client run nodes with `chef_load_nodes 10`
1. Ingest some compliance nodes with `chef_load_compliance_nodes 10`
1. ...
=> nodemanager project filtering

.expeditor/generate-automate-api-docs.sh
When #1412 was merged, (I think) this script failed because in the course of working on the docs I had already synced the files that this script is supposed to sync, so there was nothing update in git. In this PR I've modified the script to avoid trying to do any git work if the syncing has already occurred, which is going to be a more likely scenario now.
=> Skip docs sync PR with no changes.

components/automate-deployment/pkg/converge/compiler.go
This code was looking at the wrong environment variable. This means if
we failed to restart our systemd unit, we would not correctly retry
that restart on the next converge.
=> deployment: Look at HAB_LAUNCH_BINARY not HAB_LAUNCH_BIN

components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.spec.ts
We wrote a test that will fail specifically on today LOL. Let's put the magical day it will fail in the past so that we can punish our past selves instead of the other way around for once.
=> Don't let our unit tests fail specifically on 2019-10-23 xD

components/automate-ui/src/app/helpers/auth/regex.ts
The validation for member expressions that disallowed a `*` when mixed with text also disallowed hypens `-`.
This branch is a small fix to the regex that handles the NO_MIXED_WILDCARDS validation by allowing users to input hyphens.
https://github.com/chef/automate/pull/1757
Name/ID input in member expressions allows the use of hypens.  Mixed `*` is still not allowed
i.e. 
passes:  `ui-team-5`
fails: `ui-team-5*`
2. navigate to https://a2-dev.test/settings/policies/editor-access/add-members
3. click "add member expression" button in bottom left
4. in dropdown, select Type -> user
5. in next dropdown, select Identity Provider -> local
6. in typeable input, type a phrase with hyphens `-` -> it should pass
7. try typing a phrase …
=> Update NO_MIXED_WILDCARD to include hypens

components/automate-chef-io/content/docs/default-policies.md, components/automate-chef-io/layouts/shortcodes/table.html
Signed-off-by: Shadae <sholmes@chef.io>
On the default policies page in the docs the left-nav sometimes overlaps the content. Specifically, if you scroll down to a wide table and then scroll left you will notice that the left-nav overlaps the content.
Added a shortcode which is just a simple div, that will wrap the table (as long as you add {{% table %}}{{% /table %}} around the table markdown) and keep the table contained the same visual way other text and code snippets are contained within the rest of the documentation. 
Before: 
https://app.zenhub.com/workspaces/ui-team-5cba23a3b14fdc05970c8f87/issues/chef/automate/1625
After:
=> Table Overlap w/ Sidebar Bug in Docs

components/automate-ui/src/app/page-components/json-tree/vendor/json-tree.js
In client run history, the node attributes JSON we are displaying went disappearing.  This was the result of a variable not being declared and throwing an error while building the tree. 
Fix: The necessary variable is now being declared in the JSON tree template.
#fixes #1955 
Attributes JSON tree is back in the client run history attributes tab and is able to be manipulated (expanded/collapsed) as expected.
2. navigate to https://a2-dev.test/infrastructure/client-runs and click on any node in the list
3. click on the 'attributes' tab
4. click across various filters (All, Default, Normal, Override, Automatic)
5. View JSON beneath any filters that contain data
Before:
After:
=> Declare moreContentEl variable in json-tree

components/automate-ui/src/app/entities/license/license.model.ts, components/automate-ui/src/app/page-components/run-history/run-history.component.ts, components/automate-ui/src/app/pages/+compliance/+credentials/components/credentials-list-row.ts, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-trend/overview-trend.component.ts, components/automate-ui/src/app/pipes/datetime.pipe.ts
Problem: Time across the site (not just run history drawer) is showing in local time instead of UTC as desired.
For times converted in our HTML, I've added a `.utc()` to our datetime pipe, which uses moment.js.  this will return UTC instead of local time.
For times requested where the conversion is done in component.ts files, i've added `.utc()` to the moment conversion.
https://github.com/chef/automate/issues/1678
https://github.com/chef/automate/issues/1679
https://github.com/chef/automate/issues/1705
fixes #1938 
Time is being displayed in UTC where labeled as such
- liscense lockoutcomponents
- node scan results and scan history
- compliance run results and drawer
License Lockout modal
1. chef-automate dev psql …
=> Update Timestamps to use UTC

components/automate-deployment/pkg/preflight/checks.go
These ports were previously unchecked. They were automatically
included in the preflight checks when we moved to dynamic port
checking; however, they need to be skipped during the a1 migration
because they are also used by A1.
Note, that while we could move port 9611, I'm not sure we can move 8989
as this is also used in the people's git-remote configuration.
Further note that automate-workflow-nginx's ports are currently
hard-coded and not included as part of the dynamic check.
=> preflight: skip workflow ports in check during a1migration

components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.html, components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.ts
If a user has access to zero projects, the global project filter should be hidden from the top-nav. Currently, they are shown an all projects dropdown with a count of zero, that does not open because there are zero projects.
fixes #1274
If a user logged in and if the project count is `0` then the project dropdown is hidden on the dashboard.
logged in as non-admin user navigate to the dashboard.
=> hide global projects filter if zero projects

components/automate-ui/src/app/components/projects-dropdown/projects-dropdown.component.scss, components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.scss
We will soon be allowing folks to configure the project limit, which means we need to allow the two project dropdowns to be scrollable so they are still usable.
Added CSS changes for project dropdowns.
fixes #1956
In existing project dropdown is not scrolling if we add multiple projects, so I have added CSS for the `chef-dropdown`  for project filters.
For the test, need to rebuild the `automate-ui`
=> added css changes to make project dropdowns scrollable

components/compliance-service/api/stats/server/server.go, components/data-feed-service/server/server.go, components/nodemanager-service/api/manager/server/server.go, components/nodemanager-service/api/nodes/server/server.go, lib/errorutils/error_utils.go
Our standard Logrus setup already logs the timestamp. Additionally,
systemd will typically also log a timestamp. Including a timestamp
here meant that we were logging 3 timestamps for this message.
I've also done some minor formatting cleanups on our error returns
that I found when looking at callers to this function.
=> error_utils: Don't log time into message

.expeditor/create-manifest.rb, .expeditor/update_habitat.sh, .expeditor/verify_private.pipeline.yml, components/automate-deployment/pkg/server/server.go, components/automate-deployment/pkg/server/startup_helpers.go, integration/base.sh, integration/tests/upgrade_current_master_habdev.sh, scripts/verify_build.sh
We would like to be able to upgrade to the latest version to hab much
more quickly than we currently do. One issue that causes delay is that
we often don't test the latest version of Habitat until after it is
released. If we find an issue that we need to address upstream in
Habitat, this delays our upgrade as we need to submit the fix, wait
for the release, and then re-test.
The goal of this change is to get us continuously testing the dev
builds in unstable so we can catch issues or confirm fixes before the
release of Hab.
=> ci: Add test for deploying with the unstable Habitat build

components/automate-ui/src/app/page-components/license-apply/license-apply.component.spec.ts, components/automate-ui/src/app/page-components/license-lockout/license-lockout.component.spec.ts
Some locale-dependent spec failures snuck through Buildkite:
```
HeadlessChrome 77.0.3865 (Mac OS X 10.14.5) LicenseLockoutComponent GetLicenseStatus Action reflects current license FAILED
Error: Expected 'Tue, 24 Dec 2019 22:53:06 UTC' to equal 'Tue, 24 Dec 2019 15:53:06 UTC'.
HeadlessChrome 77.0.3865 (Mac OS X 10.14.5) LicenseApplyComponent ApplyLicense Action reflects successfully applied license FAILED
Error: Expected 'Tue, 24 Dec 2019 22:53:31 UTC' to equal 'Tue, 24 Dec 2019 15:53:31 UTC'.
```
Resolved by updating the specs to use expected UTC date objects:  https://github.com/chef/automate/pull/1944/commits/aa4bbb47aa666f9842cb1aad72a568f7e3810fb7
=> Fix time locale-dependent spec failures

components/compliance-service/Makefile, components/compliance-service/compliance.go
Until we integrate cereal-service into compliance's test setup, having
these turned on means we get constant spamming of errors in the logs,
making it harder to debug problems.
=> compliance: turn off cereal-service based managers in test mode

components/automate-scaffolding-go/lib/scaffolding-go.sh
This meant no Go things were getting built.
=> ci: don't exit 0 in check function
