chef/automate

- components/automate-cs-bookshelf/habitat/plan.sh
- components/automate-cs-nginx/habitat/plan.sh
- components/automate-cs-oc-bifrost/habitat/plan.sh
- components/automate-cs-oc-erchef/habitat/plan.sh
- components/automate-workflow-nginx/habitat/plan.sh
chef-server has been rebuilt to include the latest core/ruby.
This PR is the result of:
NO_GIT=true .expeditor/update_chef_server.sh unstable
> Update chef-server to latest

- components/automate-chef-io/README.md
* Updates the docs for go-swagger 0.21.x
* Adds jq to the install instructions.
> Update deps in docs site readme

- components/compliance-service/api/tests/50_scheduler_spec.rb
Just trying to address flakiness we've recently seen. pete awesomely modified the file so we could see what was failing, and this seems to be one of the common failures
N/A
scanner tests less flaky
> make scheduler scanner job less flaky

- components/nodemanager-service/pgdb/project_update.go
- components/nodemanager-service/tests/project_update_test.go
this is a bit of an "overly cautious" change.
-whenever a node report is ingested, we send a msg to nodemanager about it
-the project update manager ensures that when project updates are made, we update those nodemanager node references to be accurate
-this change ensures we're only grabbing non-managed nodes (ingested nodes). non-ingested nodes shouldn't ever have any "projects_data", so this is probably overly cautious, but it doesn't hurt, and the where clause should make the loop of nodes we go through smaller, which is good!
https://github.com/chef/automate/issues/1863
making extra sure only ingested nodes get project updates
N/A -- you could go through building it all and doing all the steps, but it's kinda overkill in this case.
> ensure only nodes with no manager (ingested nodes) are updated by project mgr

- components/compliance-service/api/tests/02_nodes_spec.rb
- components/compliance-service/reporting/relaxting/reports.go
- components/compliance-service/test_data/audit_reports/2018-03-04_windows(1)-zeta-apache(s)-skipped.json
Fixes https://github.com/chef/automate/issues/1868  and enables https://github.com/chef/automate/issues/1713 to provide a filter for a control tag that has key but no values.
> Add compliance option to filter by control tag with no value

- components/compliance-service/ingest/ingestic/ingestic.go
- components/compliance-service/integration_test/reports_projects_update_test.go
- components/ingest-service/backend/elastic/elastic.go
- components/ingest-service/backend/elastic/nodes.go
- components/ingest-service/integration_test/project_update_test.go
- e2e/cypress/integration/api/iam/01_projects_api.spec.ts
When running a project update with a chef tag project rule the compliance-service would fail to update. The problem is that the array field is sometimes stored as "null" and not an empty array. The solution is to check if the field is null before using it. 
Client runs had the same problem which is fixed in the PR also. 
#1494
Able to successfully run a project update with a project with chef tag ingest rules when there are compliance reports with empty chef tags. 
1. `build components/compliance-service && start_all_services`
1. Add some compliance nodes with `chef_load_compliance_nodes 100`
1. Open the compliance page https://a2-dev.test/compliance/reports/nodes
1. Copy one of the node's environment, its displayed in the list view
- or use the environment filter at the top of the page …
> Project update for compliance and client runs elasticsearch bug

- components/automate-chef-io/config.toml
Sadly, a controversial decision because the download button redirects us to the docs. But I hope we will fix the download page separately.
Staying with the use of "Downloads" in the header to redirect to the downloads page is consistent (I think) with how we use "Downloads" in the header in our products.
> Downloads goes to downloads page

- components/authz-service/Makefile
Add a convenience function to the authz-service makefile.
So instead of having to do this:
```
go test -v -p 1 --parallel=1 -count=1 \
github.com/chef/automate/components/authz-service/server/v2 \
-run TestIntegrationValidateProjectAssignment
```
you will be able to drill down to be very targeted in the directory tree and in the specific set of tests:
NA
Now we have these testing targets available:
```
test                    - runs all authz-service tests; no db
test/%                  - runs authz-service tests with any subpath and name; no db 
test_with_db            - runs all authz-service tests
test_properties_with_db - runs all authz-service tests with Properties in the name
test_with_db/%          - runs authz-service tests with any subpath and name fragment
```
Navigate to the …
> Authz makefile enhancement

- components/compliance-service/scripts/grpc.sh
Supersedes #2045. 
This script was always exiting 1 after some recent changes. I also fixed a case where this script wouldn't necessarily fail when proto compilation failed.
On master when proto compilation succeeds:
```
[17][default:/src:0]# compile_go_protobuf_component compliance-service ; echo $?
src/components/compliance-service/api: warning: directory does not exist.
GEN: components/compliance-service/ingest/ingest/compliance.proto
src/components/compliance-service/api: warning: directory does not exist.
GEN: components/compliance-service/ingest/events/inspec/inspec.proto
src/components/compliance-service/api: warning: directory does not exist.
GEN: components/compliance-service/ingest/events/compliance/compliance.proto
src/components/compliance-service/api: warning: directory does …
```
> Fix compliance proto compilation script exit code problems.

- .expeditor/verify.pipeline.yml
Trying to track down why compliance tests keep dying
> Upload nodemanager logs

- components/automate-chef-io/content/docs/data-collection.md
Update the docs to include the minimum version of Chef-Server that supports the data-collector.  
The data-collector was added to Chef-Server in version 12.8.0.  Users will need to make sure they are running at least that version before they can configure the data-collector.
> Add min CS version that supports the data collector

- components/applications-service/integration_test/disconnected_services_test.go
- components/applications-service/pkg/storage/postgres/hab_event.go
After a service is disconnected, it should reconnect after receiving
a new health check message. The issue was cause by our reliance on pg
to set the disconnected status to false when first recieved. We now explicitly
set the disconnected flag to false when receiving a health check message
> Fix bug where disconnected services aren't reconnecting

- components/automate-deployment/pkg/habpkg/habpkg.go
- components/automate-deployment/pkg/habpkg/habpkg_test.go
- components/automate-deployment/pkg/habpkg/hartifact.go
- components/automate-deployment/pkg/habpkg/hartifact_test.go
- components/automate-deployment/pkg/habpkg/semverish.go
- components/automate-deployment/pkg/habpkg/semverish_test.go
- components/automate-deployment/pkg/target/hab_sup.go
- components/automate-deployment/pkg/target/hab_sup_test.go
It is possible we get to hab-sup 0.100.0 soon, which would break the
string-based comparison we were previously doing.
I've implemented a small semver-ish version parser. It doesn't handle
all the rules about pre-release version sorting.
```
> go test -bench=. -benchmem ./pkg/habpkg/
goos: linux
goarch: amd64
pkg: github.com/chef/automate/components/automate-deployment/pkg/habpkg
BenchmarkParseSemverishVerionBasic-8    15147255                74.5 ns/op            32 B/op          1 allocs/op
BenchmarkParseSemverishVerionAll-8      11580704               103 ns/op              38 B/op          1 allocs/op
BenchmarkCompareBasic-8                 188691100                6.11 ns/op            0 B/op          0 allocs/op
PASS
ok …
```
> deployment: use semver-style comparison for hab-sup versions

- api/config/compliance/config_request.go
The default of 10 workers can easily overwhelm a system with a small
number of CPUs. This sets the default the numCPUs + 2, clamped to [2,
10].
> compliance: worker count default based on CPU count

- .bldr.toml
- HABITAT_PACKAGES
- components/data-lifecycle-service/README
- components/data-lifecycle-service/habitat/plan.sh
We create an empty build because deployment-service cannot continue if we
remove a service from the manifest. The empty package is the least  bad of
our options because it has no dependencies, so it wont cause us to install
in data-lifecycle-service's old deps.
This will be a 2 part PR. We'll pin data-lifecycle-service in
products.meta once its built.
Fixes #2058
> Build empty data lifecycle service

- Makefile.common_go
- lib/Makefile
Many of our tests are downloading go dependencies because they use the
make targets directly rather than using the studio.
> set GOFLAGS in Makefile.common_go

- .bldr.toml
- HABITAT_PACKAGES
- products.meta
The version we'll use has no dependencies. This will prevent us from
instaling old versions of things that aren't even going to be used
Actually fixes #2058
> Replace data-lifecycle-service version

- components/automate-ui/package-lock.json
New audit alerts popped up. All could be fixed by running `npm audit fix`.
```
$ npm audit
found 10 high severity vulnerabilities in 18004 scanned packages
run `npm audit fix` to fix 10 of them.
```
```
$ npm audit fix
added 3 packages from 2 contributors and updated 6 packages in 8.601s
fixed 10 of 10 vulnerabilities in 18004 scanned packages
```
```
$ npm audit
found 0 vulnerabilities in 18004 scanned packages
```
> Audit fix UI security alerts

- components/automate-ui/src/app/pages/+compliance/+reporting/reporting-searchbar/reporting-searchbar.component.scss
This commit fixes issue where the border around compliance searchbar would render incorrectly in Firefox.
Before
After
> Fix incorrect border around compliance search

- terraform/test-environments/modules/chef_automate_install/main.tf
This story makes the project limit configurable. I've bumped the project limit on our dev/acceptance envs so we can have more freedom to make projects for testing, without running into the limit and causing Cypress tests to fail (they create a few projects then delete them on each run).
https://github.com/chef/automate/pull/2029
following the next deploy, we should be able to create up to 50 projects on:
- https://a2-iamv2p1-local-inplace-upgrade-acceptance.cd.chef.co/
- https://a2-iamv2p1-local-fresh-install-acceptance.cd.chef.co/
- https://a2-iamv2p1-local-inplace-upgrade-dev.cd.chef.co/
- https://a2-iamv2p1-local-fresh-install-dev.cd.chef.co/
> [automate-1840] bump the project limit on dev/acceptance environments

- components/automate-ui/src/app/helpers/datetime/datetime.ts
- components/automate-ui/src/app/page-components/run-history/run-history.component.ts
- components/automate-ui/src/app/pages/client-runs/client-runs.component.ts
This commit updates the filenames of report downloads to use UTC datetime in 
`YYYY-MM-DD-HHmmss` format.
`2019-09-24-09:59:05.csv`
`2019-12-03-17:03:26.json`
fixes #1972
Filenames for client-runs and compliance report downloads use `YYYY-MM-DD-HHmmss` format.
1. Nav to `/infrastructure/client-runs`
2. Select download button and select json or csv
3. Nav to `/compliance/reports/overview`
4. Select download button and select json or csv
> Update format for report export filenames

- .expeditor/verify_private.pipeline.yml
- .studio/event-gateway
- .studio/event-service
- components/applications-service/Makefile
- components/automate-cli/Makefile
- components/automate-deployment/Makefile
- components/automate-gateway/Makefile
- components/automate-gateway/integration/license_usage_nodes_test.go
- components/automate-gateway/integration/nodes_test.go
- components/cereal-service/Makefile
- components/compliance-service/Makefile
- components/data-feed-service/Makefile
- components/es-sidecar-service/Makefile
- components/event-gateway/Makefile
- components/event-gateway/integration_test/nats_auth_test.go
- components/event-gateway/integration_test/suite_test.go
- components/event-service/Makefile
- components/event-service/integration_test/global_test.go
- components/event-service/integration_test/publish_test.go
- components/event-service/integration_test/suite_test.go
- components/nodemanager-service/Makefile
We've seen CI failures that indicate that we are still not using
-mod=vendor everywhere.  This PR accounts for uses of `go list`.
At the heart of this change is the fact that doing:
export GOFLAGS = -mod=vendor
in a Makefile does not affect commands started with `$(shell
CMD)` (see http://savannah.gnu.org/bugs/?10593 for details).
To account for this, I've take the following strategies:
- Remove unnecessary uses of `$(shell go list)`. Most go commands can
take package list directly.
- Replacing some uses of `go list | grep -v some_package` with build
tags.
- Adding GOFLAGS='$(GOFLAGS)' to `go list` invocations that appeared
harder to replace.
In addition to this I've
- Removed explicit `go vet` Make targets since we also run govet as
part of golangci-lint.
- Replaced a custom …
> Account for -mod=vendor in `go list` usages

- .studio/common
- api/config/builder_api/config_request.pb.a2svc.go
- api/config/builder_api_proxy/config_request.pb.a2svc.go
- api/config/builder_memcached/config_request.pb.a2svc.go
- api/config/minio/config_request.pb.a2svc.go
- integration/helpers/ssl_filters.jq
- integration/tests/security.sh
This CI task was changed in #1837 from being specified inline in the buildkite config:
https://github.com/chef/automate/blob/6f05b7a037f2457852ee540bfc5b9439c3581035/.expeditor/verify.pipeline.yml#L13-L20
to being a bash function:
https://github.com/chef/automate/blob/91329cbb7d6093152eacbc8053bc5cfde163cb2f/.studio/common#L116-L132
My guess is that this if statement does not do the correct thing, the `if !` is two bash commands so one of them must change the exit code before the `return $?` statement.
The first commit changes the code buildkite runs, so it failed as expected because there are proto differences between what's checked in on master and what is generated by compiling the protos.
The second commit adds the proto file changes that are missing, so it should pass.
> Fix proto compilation generated file CI task

- vendor/github.com/grpc-ecosystem/grpc-gateway/go.mod
`go mod verify` does not verify the vendored copies of
dependencies:
https://github.com/golang/go/issues/27348
As such, it seems that this change snuck in. This commit is the result
of commit the all changes produced by `make revendor` on master.
> fix change to vendored files

- Makefile
This should help people who try to run on this make target on OSX. We
don't currently believe it was needed.
> remove GNU-only option from `make revendor`

- .expeditor/verify_private.pipeline.yml
- e2e/cypress/integration/bldr-smoke/smoke.spec.ts
- integration/fixtures/test_plan/plan.sh
- integration/tests/bldr_smoke.sh
These tests deploy builder. Then they log in with the admin user, create a token, and create a random origin all through the web ui.  The token and origin are saved a file in the process and used to build and upload a package to the depot.
Fixes #2106
> Add smoke tests for builder

- .buildkite/hooks/pre-exit
- integration/base.sh
- integration/helpers/build.sh
- integration/run_test
This change allows us to test proxy setups directly
in the integration test framework.
A test can declare that it wants to test proxies with:
```bash
test_proxy=true
```
This will setup a container running squid. The container running
automate will have access to the squid container, but not the internet.
The squid proxy will have access to the internet.
do_setup exports the HTTP(S)_PROXY environment variables.
I tested this with our product suite running diagnostics. Everything is fine until the `cert_auth_tests` function is run. I suspect they need to set no_proxy
> Allow proxy setup in integration test framework

- components/automate-cli/cmd/chef-automate/applications.go
Since we have a periodic job to cover this, remove the cli command
that runs once to make things less confusing for the user.
> Remove delete disconnected service CLI command

- .studiorc
- components/authz-service/README.md
- components/authz-service/engine/opa/opa.go
- components/authz-service/server/v2/policy.go
- components/authz-service/server/v2/policy_refresher.go
- components/authz-service/server/v2/policy_test.go
- components/authz-service/storage/v2/postgres/postgres.go
- components/authz-service/storage/v2/postgres/postgres_test.go
- components/automate-cli/cmd/chef-automate/iam.go
- components/automate-gateway/gateway/middleware/authv2/authv2.go
- components/automate-gateway/handler/iam/v2beta/policy/policy.go
- terraform/test-environments/modules/chef_automate_install/templates/install_chef_automate_cli.sh.tpl
Now that `upgrade-to-v2` upgrades Automate to `IAM v2.1`, all of our v2.0-specific comments and come is no longer needed. Automate users can now only be on `v1` or `v2.1`; `v2.0` doesn't exist any more on the customer-side
This PR updates or removes comments referring specifically to `v2.0`, removes uses of `--beta2.1`, and cleans up a few other v2.0 references
- https://github.com/chef/automate/pull/2042
- #2090 
- tests still pass
the only real code changes is adding projects into the authz error response on v2:
```
$ export TOK=`chef-automate iam token create non-admin`
$ export TARGET_HOST=https://a2-dev.test
$ rebuild components/automate-gateway
$ curl -kH "api-token: $TOK" -d '{"id": "foofoo", "name": "foo foo" }' -H "projects: lala" $TARGET_HOST/apis/iam/v2beta/projects | jq
{ …
```
> [automate-1877] miscellaneous IAM v2.0 cleanup

- components/automate-ui/src/app/pages/policy/details/policy-details.component.ts
- components/automate-ui/src/app/pages/team-details/team-details.component.ts
Updating the policy details and team details pages to not request data when the page's internal tabs are changed. This solution combines two observers that are triggered off URL updates. Added the "distinctUntilChanged" filter to prevent extra data request when the internal tabs are changed. The "distinctUntilChanged" filter prevents multiple events from being sent when the data has not changed. 
https://github.com/chef/automate/issues/2104
The data on the policy details and team details pages is only requested once when the page is first loaded. Changing the page's internal tabs does not re-request data. 
1. Open the Teams detail page for the admin https://a2-dev.test/settings/teams/admins
1. Open the Chrome inspect tool then select …
> Removing Duplicate requests for details pages

- .studio/compliance-service
- components/compliance-service/test_data/audit_reports/send_to_data_collector.sh
just wanted to add a studio function to make it easier to load the data in audit_reports. this data is what we use in testing and has control tags, roles, environments -- more diverse data. 
this came up in slack when a developer was trying to work on control tags but didn't have data to populate the control tags with the existing commands in the studio.
https://github.com/chef/automate/issues/1713#issuecomment-547622738
can load reports with control tags easily in the studio
> load more compliance reports

- Makefile
This reverts commit fa722408560224ebdd41337a01c7cd2116b7a233.
This is a bit of a bummer since it won't work on OSX again. But, without this
we will fail on permissions problems trying to remove read-only files in the grpc-gateway
directory.
> Revert "remove GNU-only option from `make revendor` (#2110)"

- components/automate-ui/src/app/entities/entities.ts
- components/automate-ui/src/app/pages/policy/add-members/policy-add-members.component.html
- components/automate-ui/src/app/pages/policy/add-members/policy-add-members.component.ts
- components/automate-ui/src/app/pages/policy/details/policy-details.component.ts
- components/automate-ui/src/app/pages/team-add-users/team-add-users.component.html
- components/automate-ui/src/app/pages/team-add-users/team-add-users.component.ts
- components/automate-ui/src/app/pages/team-details/team-details.component.html
- components/automate-ui/src/app/pages/team-details/team-details.component.spec.ts
- components/automate-ui/src/app/pages/team-details/team-details.component.ts
- components/automate-ui/src/app/route.selectors.ts
Removing duplicate API requests from the policy and team pages. When loading the pages the observable subscribe functions were being called multiple times for with the same data. This caused the page's data to be requested each time.
#2104
All of the auth pages do not perform multiple requests for page data. 
1. Open the Teams detail page for the admin https://a2-dev.test/settings/teams/admins
1. Open the Chrome inspect tool then select the network tab. 
1. Ensure each API request is only called once.
1. Do the same thing for the team add user page, policy details page, and policy add member page.
> Removing duplicate requests

- components/automate-ui/src/app/entities/entities.ts
- components/automate-ui/src/app/entities/policies/policy.reducer.ts
- components/automate-ui/src/app/entities/projects/project.reducer.ts
- components/automate-ui/src/app/entities/roles/role.reducer.ts
- components/automate-ui/src/app/entities/rules/rule.reducer.ts
- components/automate-ui/src/app/pages/policy/details/policy-details.component.html
- components/automate-ui/src/app/pages/policy/details/policy-details.component.ts
- components/automate-ui/src/app/pages/project/details/project-details.component.ts
- components/automate-ui/src/app/pages/roles/details/role-details.component.ts
When calls to `GET` and `GET_ALL` happen in the store, clear the store of the object in question and refetch so that we always have the latest data.
Also updated all the subscriptions to filter until the fetch is completed to avoid flickering and other undesirable side effects of hitting the subscribe code multiple times.
Spin up UI. Go to a role, policy, and project from both the list view and by refreshing from the details page. Everything should function correctly.
> [AUTOMATE-2138] Always refetch latest data in UI for projects, policies, and roles

- components/automate-gateway/gateway/datacollector_bench_test.go
- components/automate-gateway/gateway/datacollector_internal_test.go
- components/automate-gateway/gateway/datacollector_test.go
- components/automate-gateway/gateway/helpers_internal_test.go
- components/automate-gateway/gateway_mocks/Makefile
- components/automate-gateway/gateway_mocks/mock_gateway/clients_mock.go
This fixes a chicken-and-egg problem that we hit when trying to add a
service since the package the code-generator reflects on also requires
that the generated code is already correctly generated.
Note the change in clients_mock.go is likely from the fact that this
file was hand-edited in the past.
I've also removed a Make target which simply didn't work because the
relevant files didn't exist.
Further, I noticed that running `make` produces files in
mock_compliance_events/
which are not currently in source control. I haven't added them here
as as I wasn't sure if this was intentional.
In short, mock generation is a big mess still and needs to be cleaned
up, but at least now `make` works again.
Signed-off-by: Vivek Singh …
> gateway: quick fix for mockgen Make targets

- components/automate-ui/src/app/entities/service-groups/service-groups.facade.ts
Effect: 
numbers on sidebar were missing because an error was occuring.
services cards appeared blank if they were rendered after a service that had switched health statuses.
The error was due to scoping of `this` when calling another function in the class. `this` was not in the scope when the function was called from the html page, so it couldn't find the function also in the class. 
Fix: 
Removed the function by pulling in simple logic into the same method. 
There is probably a better way to do this if you are a level 8+ javascript wizard. 
The error that occured was
ServicesSidebarComponent.html:74 ERROR TypeError: this.formatHealthStatusForTimewizard is not a function
at ServicesSidebarComponent.timewizardMessage (service-groups.facade.ts:92)
This error occurred after a service …
> Fix error related to timewizard formatting.

- components/release-mgmt-dashboard/src/app/app.component.html
`here` links are a poor experience
this removes the here link from our release dashboards
[accessibility and link text](https://webaim.org/techniques/hypertext/link_text)
> removed here link text on release dashboards

- components/automate-deployment/pkg/airgap/bundle_creator.go
- components/automate-deployment/pkg/airgap/bundle_creator_test.go
- components/automate-deployment/pkg/habpkg/semverish.go
- components/automate-deployment/tools/upgrade-test-scaffold/upgrade-test-scaffold.go
The tarballs of the hab binary is now hosted on packages.chef.io
rather than bintray.
NB: Once we update to the newest version of hab, we can potentially
remove bintray from our preflight checks and documentation.
> airgap: download new hab binary from packages.chef.io

- .expeditor/config.yml
- .expeditor/update_habitat.sh
The Habitat release process has changed. They now publish a manifest
with all relevant package versions.
By default the script will pull from the latest stable release, but
TARGET_VERSION can be set to an exact version for local testing or
manually setting the pin.
The workload I've subscribed to was taken from:
https://github.com/habitat-sh/homebrew-habitat/pull/28
The script has been testing locally, but unfortunately we don't have a
great way to confirm that it will work in the context of expeditor.
> ci: update automation of habitat version bumping

- components/compliance-service/api/profiles/server/pgserver.go
- components/compliance-service/profiles/db/store.go
This code is extracted from another branch I had going with experiments to speed up the available profile list page in the app. The logic to decide which SQL query to run was spread across many functions that felt redundant and convoluted, so I consolidated from 8 functions to 2. This also removes a few redundant log messages.
> Refactor profile list code

- components/automate-ui/src/app/pages/+compliance/+profile/+profile-overview/profile-overview.component.scss
Currently, both the global projects filter rand the user dropdowns display behind the loading overlay
Repro
chef-automate iam upgrade-to-v2 --beta2.1 note: after the 2.1 release you should not need the beta flag
visit compliance/profiles
open the project's dropdown and user menu and notice they display behind the overlay.
fixes #2012
> CSS changes to display dropdown on top of loading overlay

- components/automate-chef-io/content/docs/data-collection.md
Automate requires at least TLSv1.2 for web connections and Chef-Server 12.11.0 is the first version with OpenSSL 1.0.2 that includes TLSv1.2 support needed for the data-collector proxy to work.
Chef Server 12.11.0 is also needed to use proxying Inspec profiles to Automate `profile['root_url']`
You can configure the data-collector with 12.8.0 but the `profile` config option will throw an error.
> Increase min chef-server version to 12.11

- components/automate-ui/src/app/modules/team/team-details/team-details.component.scss
- components/automate-ui/src/app/modules/team/team-details/team-details.component.ts
A bug was recently introduced that caused a field caption for team details
to disappear:
Caption now appears on V2:
Caption now appears on V1:
rebuild automate-ui
Navigate to Settings >> Teams >> [team] >> Details
Try on both v1 and v2
> [automate-2216] Supply missing field caption for team details

- components/automate-ui/src/app/entities/entities.ts
- components/automate-ui/src/app/modules/token/token-details/api-token-details.component.ts
- components/automate-ui/src/app/modules/token/token-list/api-token-list.component.ts
Per the items noted in the [spreadsheet for subscription fixes](https://docs.google.com/spreadsheets/d/17n8G693ChnCjz9pfie5Gmj6q6hfs-0v-T7R557tYgzU/edit#gid=0) this PR cleans up subscriptions for tokens (token list and token details):
-- adds missing Observable completion
-- removes nested subscriptions
-- removes conditional completion on several Observables
#2162 (Find Nested Subs and Subs Not Completed)
Creating a token from the token list page and editing a token from the token details page function as before. In the case of creating a token, this includes either successfully creating a new token or failing to create one due to id conflicts.
Navigate to Settings >> API Tokens >> Create Token
Attempt to create a token with an already used ID. Error pop-up within the …
> [automate-2181] Fix token subscriptions

- components/automate-ui/src/app/entities/api-tokens/api-token.reducer.ts
- components/automate-ui/src/app/entities/teams/team.reducer.ts
- components/automate-ui/src/app/entities/users/user.effects.ts
- components/automate-ui/src/app/entities/users/user.reducer.spec.ts
- components/automate-ui/src/app/entities/users/user.reducer.ts
- components/automate-ui/src/app/entities/users/user.selectors.ts
- components/automate-ui/src/app/modules/policy/add-members/policy-add-members.component.ts
- components/automate-ui/src/app/modules/team/team-add-users/team-add-users.component.ts
- components/automate-ui/src/app/modules/team/team-details/team-details.component.html
- components/automate-ui/src/app/modules/team/team-details/team-details.component.scss
- components/automate-ui/src/app/modules/team/team-details/team-details.component.ts
- components/automate-ui/src/app/modules/token/token-details/api-token-details.component.ts
- components/automate-ui/src/app/modules/user/user-details/user-details.component.html
- components/automate-ui/src/app/modules/user/user-details/user-details.component.scss
- components/automate-ui/src/app/modules/user/user-details/user-details.component.ts
- components/automate-ui/src/app/modules/user/user-management/user-management.component.ts
We have some data leakage issues between the auth list and details pages. If you navigate to the list page and then go to one of the details pages, the data still exists in the store and gets loaded on the details page. This is a problem in cases when a user might have List permission but not Get permission.
- follow-up: https://github.com/chef/automate/issues/2138
- in the future we may rethink what data our List and Get APIs should be returning
```
$ export TOK=`chef-automate iam token create adm --admin`
$ echo '{
"name": "testing",
"id": "test1",
"members": [
"user:local:coolbean"
],
"statements": [
{
"effect": "ALLOW",
"actions": ["iam:*:list"],
"projects": [
"*"
]
}
],
"projects": []
}' >> pol.json
$ curl -kH "api-token: $TOK" -X POST -d @pol.json …
```
> [automate-2104] reset items in ngrx/store between GET requests

- components/automate-ui/src/app/modules/policy/add-members/policy-add-members.component.ts
Per the items noted in the [spreadsheet for subscription fixes](https://docs.google.com/spreadsheets/d/17n8G693ChnCjz9pfie5Gmj6q6hfs-0v-T7R557tYgzU/edit#gid=0) this PR cleans up subscriptions for policies:
-- removes nested subscription
-- removes conditional completion on an Observable
#2162 (Find Nested Subs and Subs Not Completed)
Adding members successfully or not successfully does the right thing, as indicated below.
Navigate to `Settings >> Policies >> [policy] >> Add Members`
Add a member successfully and the view should auto-navigate back to the members tab of the policy details page.
Add a member unsuccessfully and the add-members should remain open with an error (note the formatting of that error is being reviewed by UX).
One way to force the add-member …
> [automate-2180] Fix policy subscriptions

- components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.ts
- components/automate-ui/src/app/modules/team/team-add-users/team-add-users.component.ts
- components/automate-ui/src/app/modules/team/team-details/team-details.component.ts
- components/automate-ui/src/app/modules/team/team-management/team-management.component.spec.ts
- components/automate-ui/src/app/modules/team/team-management/team-management.component.ts
- components/automate-ui/src/app/modules/token/token-list/api-token-list.component.ts
- components/automate-ui/src/app/pages/project/list/project-list.component.ts
In the interest of improving performance across auth pages, we're auditing how we're handling subscriptions to ensure the following: 
1. all subscriptions are destroyed when the user moves away from the page
2. no nested subscriptions exist 
This PR cleans up the teams pages:
- team-details.component.ts
- team-management.component.ts
- team-add-users.component.ts
sub-task of https://github.com/chef/automate/issues/2162
depends on: https://github.com/chef/automate/pull/2188 **(this must be merged first)**
- refactored pages work as they did before (modal closes when appropriate, errors display as expected)
- start the UI and navigate to https://a2-dev.test/settings/teams
- create a team and see the team table update with that team
- create a team with the same id and see a conflict error …
> [automate-2177] clean up team pages subscriptions

- components/automate-deployment/pkg/services/internal/generated/gen.go
- products.meta
Currently, builder users will need access to the automate-ui to manage users.
We'll temporarily force people to deploy automate when deploying builder
to get access to those management features.
Helps with #2248
> Force deployment of automate with builder

- components/automate-ui/src/app/helpers/datetime/datetime.ts
- components/automate-ui/src/app/page-components/event-feed-guitar-strings/event-feed-guitar-strings.component.html
- components/automate-ui/src/app/page-components/event-feed-guitar-strings/event-feed-guitar-strings.component.spec.ts
- components/automate-ui/src/app/page-components/event-feed-guitar-strings/event-feed-guitar-strings.component.ts
- components/automate-ui/src/app/page-components/event-feed-table/event-feed-table.component.html
- components/automate-ui/src/app/page-components/event-feed-table/event-feed-table.component.spec.ts
- components/automate-ui/src/app/page-components/event-feed-table/event-feed-table.component.ts
This commit updates the displayed datetimes within event-feed graph and table to use datetime formats specified in fixes #1977
**Before**
**After**
> Update display formats for event feed datetimes

- components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.html
- components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.ts
- components/automate-ui/src/app/pages/project/list/project-list.component.html
- components/automate-ui/src/app/pages/project/list/project-list.component.spec.ts
Need to only show the "Create policies for project" when creating project. Should never show in v1.
Before:
After:
> Only show auto create msg for project modal

- components/automate-ui/src/app/modules/license/license-lockout/license-lockout.component.html
- components/automate-ui/src/app/modules/license/license-lockout/license-lockout.component.scss
Signed-off-by: Sachin Bachhav <sbachhav@chef.io>
If a user signs in as a non-admin user before a license is applied, they will get a license popup that they can't get past as only the admin can apply a license. They also can't get to the log out button to re-login as admin.
The current workaround is opening an incognito window or using the CLI to set a license key.
so as fix added sign out functionality along with some design changes.
fixes #1484 
Added Sign out functionality in license lockout modal
`build components/automate-ui`
1. Set up environment
2. Log in as admin user
3. Create a non-admin user
4. Log out as admin user
5. Remove license in studio using remove_dev_license
6. Log in as non-admin user
> license lockout modal design changes and add sign out functionality

- components/automate-ui/src/app/modules/user/user-details/user-details.component.html
- components/automate-ui/src/app/modules/user/user-details/user-details.component.ts
- components/automate-ui/src/app/modules/user/user-management/user-management.component.html
- components/automate-ui/src/app/modules/user/user-management/user-management.component.ts
In the interest of improving performance across auth pages, we're auditing how we're handling subscriptions to ensure the following:
1. all subscriptions are destroyed when the user moves away from the page
2. no nested subscriptions exist
This PR cleans up the users pages:
- user-details.component.ts
- user-management.component.ts
- depends on https://github.com/chef/automate/pull/2130
and https://github.com/chef/automate/pull/2188
- refactored pages work as they did before (modal closes when appropriate, errors display as expected)
- each page subscribes to each data stream only once and closes the subscription when the component is destroyed
1. start the UI and navigate to https://a2-dev.test/settings/users
2. create a user and see the user table update with that user
3. navigate to …
> [automate-2176] clean up user pages subscriptions

- terraform/test-environments/modules/chef_automate_install/main.tf
- terraform/test-environments/modules/chef_automate_install/variables.tf
we are no longer using the `enable_*` things, so to enable builder we will need to go through the products array
a step towards finishing #1792
> Change terraform environments to use product config

- .expeditor/verify_private.pipeline.yml
- e2e/README.md
- e2e/cypress/integration/constants.ts
- e2e/cypress/support/index.ts
- e2e/package.json
- integration/run_test
- integration/tests/cypress_e2e.sh
- Changed CYPRESS_RUN_FLAKY to 'yes', 'no', from a boolean, because there is no way to tell the difference between false being passed and the env var not being passed at all
- Added a test to assert that the IAM version returned via the API matches what you passed in via CYPRESS_IAM_VERSION
- Also fixes bug where the flaky tests weren't actually running in the flaky pipelines 😓 
I did not do `CYPRESS_BASE_URL` because cypress itself will throw a fit if that isn't set to a valid address.
```
CYPRESS_IAM_VERSION="x" CYPRESS_RUN_FLAKY="x" npm run cypress:open
```
with various missing and incorrect values for the env vars.
> [AUTOMATE-2143] Throw error if all cypress environment variables are not set

- components/automate-workflow-server/habitat/plan.sh
I don't think we need these at runtime.  Let's see.
> automate-workflow-server: Remove some runtime dependencies

- terraform/test-environments/scenarios/single_local_all_fresh_install.tf
- terraform/test-environments/scenarios/single_local_all_inplace_upgrade.tf
We're not deleting the old workflow one just yet because it currently
requires manually hacking up the terraform state file
> Deploy all the products with terraform

- components/automate-chef-io/content/docs/backup.md
A couple of users have mentioned that it would be helpful to be able to restore using the latest backup without having to string together *nix commands to find the correct backup ID. It turns out that running `chef-automate backup restore </path/to/backup/bucket>` with no backup ID will restore using the latest backup. I added documentation to that effect.
Reference: idea A2-I-51 in Aha.
> Document that `chef-automate backup restore` without ID uses the latest backup

- components/pg-sidecar-service/habitat/plan.sh
`core/postgresql`, `core/postgresql-client` and `core/sqitch_pg` were
recently updated. As our `automate-postgresql` package is pinned to an
older version we need to also pin to older versions in the `pg-sidecar-service`
until we decide to upgrade `automate-postgresql`.
Fixes https://buildkite.com/chef/chef-automate-master-habitat-build/builds/1132
> [pg-sidecar-service] pin core postgres deps

- components/automate-chef-io/content/docs/iam-v2-guide.md
- components/automate-chef-io/content/docs/iam-v2-overview.md
We now allow customers to modify the maximum number of projects that can be created. This documents the steps to do so.
> Auth 2184/project limit config docs

- components/automate-ui/src/app/modules/policy/details/policy-details.component.scss
- components/automate-ui/src/app/pages/project/details/project-details.component.scss
- components/automate-ui/src/app/pages/project/details/project-details.component.ts
- components/automate-ui/src/app/pages/project/list/project-list.component.spec.ts
- components/automate-ui/src/app/pages/project/list/project-list.component.ts
- components/automate-ui/src/app/pages/project/rules/project-rules.component.html
- components/automate-ui/src/app/pages/project/rules/project-rules.component.spec.ts
- components/automate-ui/src/app/pages/project/rules/project-rules.component.ts
In the interest of improving performance across auth pages, we're auditing how we're handling subscriptions to ensure the following:
1. all subscriptions are destroyed when the user moves away from the page
2. no nested subscriptions exist
This PR cleans up the project pages:
- project-details.component.ts
- project-list.component.ts
- project-rules.component.ts
- refactored pages work as they did before (modal closes when appropriate, errors display as expected)
- each page subscribes to each data stream only once and closes the subscription when the component is destroyed
1. start the UI and navigate to https://a2-dev.test/settings/projects
2. create a project and see the project table update with that project
3. navigate to your new project, select the Details tab
4. update the project …
> [automate-2179] clean up project subscriptions

- components/compliance-service/ingest/ingestic/ingestic.go
- components/event-feed-service/pkg/persistence/feed-elastic.go
- components/ingest-service/backend/elastic/actions.go
- components/ingest-service/backend/elastic/elastic.go
- components/ingest-service/backend/elastic/nodes.go
We recently observed the following panic during a CI failure:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xffaeab]
goroutine 2840 [running]:
github.com/chef/automate/components/compliance-service/ingest/ingestic.(*ESClient).UpdateReportProjectsTags(0xc0000b3cf0, 0x161b660, 0xc0096e22c0, 0xc00b3f8180, 0x1, 0x161b660, 0xc0096e22c0, 0x141ef5e)
/src/components/compliance-service/ingest/ingestic/ingestic.go:350 +0x4ab
github.com/chef/automate/components/compliance-service/ingest/ingestic.(*ESClient).UpdateProjectTags(0xc0000b3cf0, 0x161b660, 0xc0096e22c0, 0xc00b3f8180, 0x0, 0x0, 0x0, 0xc00b40e420, 0x0)
/src/components/compliance-service/ingest/ingestic/ingestic.go:197 +0xbb …
> compliance-service: fix nil pointer dereference

- lib/scaffolding/support/proxy.sh
`no_proxy` might be undefined, causing this to fail if the calling
hook is running with `set -u`.
> scaffolding: make proxy.sh work under `set -u`

- components/automate-workflow-web/src/components/navbar/navbar.js
- components/automate-workflow-web/test/e2e/specs/navbar.spec.js
- components/automate-workflow-web/test/unit/specs/components/navbar.spec.js
I don't know what this is for. But, I do know that we always return
404 to this endpoint as it is hard-coded into the nginx
configuration. Thus, all this ever does is produce an extra request
that gets rejected.
> workflow-web: remove /status/console calls

- components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.html
- components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.ts
- components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.spec.ts
- components/automate-ui/src/app/page-components/projects-filter/projects-filter.component.html
- components/automate-ui/src/app/services/projects-filter/projects-filter.reducer.spec.ts
- components/automate-ui/src/app/services/projects-filter/projects-filter.reducer.ts
- components/automate-ui/src/app/services/projects-filter/projects-filter.selectors.ts
- components/automate-ui/src/app/services/projects-filter/projects-filter.service.ts
Users were confused by the `(unassigned)` label in the dropdown when it was the only "project" to which they had access.
All these scenarios are true:
Bring up the UI and sign in as users with varying project permissions (one project, one project + unassigned, only unassigned, no projects) and ensure that the above scenarios render correctly.
> Auth 2304/hide unassigned if only one allowed

- components/automate-ui/src/app/modules/policy/add-members/policy-add-members.component.scss
on the policy-add-members page, when a user chooses to add a member to a policy, a full screen modal is opened.  With the modal open, it appeared that the buttons near the bottom of the screen were not rendering.  After scrolling down we could see the buttons were rendered properly but they were hiding behind a footer.
To fix, changed the position of the chef-page that held this content to fixed, so that it show above the rest of the contnet.
fixes #2253
Policy add members renders as intended, full screen with access to all content it contains.
2. navigate to https://a2-dev.test/settings/policies/administrator-access#members, click `add members` -> see full screen modal
3. navigate to directly …
> Change position of chef-page to fixed on policy add members component

- components/compliance-service/profiles/db/store.go
* I'm changing the behavior and signature of ListProfilesMetadata for #2258 so I wanted to avoid calling it here.
* This code was pulling a bunch of stuff from the database, parsing json, etc when it didn't need to.
> Refactor latestVersion to avoid calling heavyweight codepath.

- .expeditor/deploy.pipeline.yml
- components/automate-builder-api/habitat/plan.sh
The default container cant seem to do a hab pkg build
because of mount issues
> Try using a privileged container for builder test

- components/es-sidecar-service/pkg/server/purge.go
- lib/datalifecycle/purge/policies.go
Always log purge workflows and ElasticSearch sidecar purge operations.
> [purge] always log purge actions

- components/automate-ui/src/app/page-components/job-nodes-form/job-nodes-form.component.scss
The styling in https://a2-local-inplace-upgrade-dev.cd.chef.co/jobs/add is out of wack in the `Add Nodes` portion of the form.  Specifically elements are laid out inline.  Turned out that the styling for the labels was missing.  I've replaced the label styling and now they are back to normal.
fixes #2240
Form elements are stacking on top of each other, as they are in acceptance.
2. navigate to https://a2-dev.test/jobs/add#add-nodes, see that the form elements match the acceptance image below or here https://a2-local-inplace-upgrade-acceptance.cd.chef.co/jobs/add
Dev - broken
Acceptance - correct
This Branch
> Add styles to labels in scan jobs form

- tools/print-ds-config/main.go
This tool allows us to print the TOML configuration directly from a
copy of the bolt-db database. Example usage:
```
cp /var/opt/chef-automate/backups/BACKUP_ID/deployment-service/bolt/bolt.db ./bolt.db 
./print-ds-config ./bolt.db 
```
> tools: add print-ds-config

- components/automate-ui/src/app/page-components/event-feed-table/event-feed-table.component.html
- components/automate-ui/src/app/page-components/event-feed-table/event-feed-table.component.ts
When using the buttons that look like links on the event feed the panel on the right does not open.
https://app.zenhub.com/workspaces/ui-team-5cba23a3b14fdc05970c8f87/issues/chef/automate/2237
fixes #2237
Event feeds side panel opens
Create some events (get a few profiles, or something else)
Navigate to the event feed
Use a button that looks like a link
Notice the right panel does not open
> Event feed right panel does not open

- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.html
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profile/reporting-profile.component.html
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profiles/reporting-profiles.component.html
- components/automate-ui/src/app/pages/+compliance/+scanner/containers/jobs-list/jobs-list.component.html
- components/automate-ui/src/app/pages/+compliance/+scanner/containers/nodes-list/nodes-list.component.html
I can scroll right on the Scan Jobs page to see a hidden panel
https://app.zenhub.com/workspaces/ui-team-5cba23a3b14fdc05970c8f87/issues/chef/automate/2264
fixes #2264
Can't scroll to right and see right panel
navigate to /compliance/scan-jobs/jobs
try to scroll to the right of the page
> Can see hidden Scan Jobs panel when scrolling right

- components/nodemanager-service/api/nodes/server/server.go
- components/nodemanager-service/tests/project_filtering_test.go
Adding project filtering to the "api/v0/nodes/<id>"/Read RPC function. This is needed because the nodemanager stores both ingested nodes and manually added nodes. These changes filter the ingested nodes only. The manually added nodes will not be filtered by the project tags in the context object.
If the ingested node is not allowed by the passed in projects in the request a 404 will be returned. 
#2350
All ingested client runs and compliance nodes are filtered by projects on the Read RPC. 
1. `build components/nodemanager-service && start_all_services`
1. Ingest some client run nodes with `send_chef_run_example`
1. Go to https://a2-dev.test/infrastructure/client-runs and copy the node ID for the new node created. 
1. Ensure the node can be retrieved with unassigned by running this command …
> nodemanager Read RPC project filtering

- components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.ts
When attempting to remove all filters using the `clear all` button on the Compliance page, the function would not remove filters that include the `control_tag` filter.  This is because `control_tag`s have 3rd level filter available to them which incorporates a `:` delimiter and the initial function doesn't know how to handle them.
Since we are clearing all filters, it would make sense to use an empty object, instead of looping through all the filters.
the `clear all` button now removes all filters applied on compliance pages.
2. you may need to run `load_compliance_reports` in hab studio to have reports to filter by
3. Navigate to https://a2-dev.test/compliance/reports/overview
4. filter by anything involving `control tag`
5. …
> Remove all applied search query filters when user clicks `clear all` button

- components/automate-ui/src/app/helpers/auth/regex.ts
- components/automate-ui/src/app/modules/policy/add-members/policy-add-members.component.html
- components/automate-ui/src/app/modules/policy/add-members/policy-add-members.component.ts
This branch updates the regex validation used in the member expression modal so that users can use whatever characters they use, with the exception of `:` and `;`
Users can now use special characters.  The use of `*` along with other characters is still disallowed.
2. navigate to https://a2-dev.test/settings/policies/administrator-access/add-members
3. click on `Add Member Expression` on the bottom left
4. set Type => Team, Identity Provider => LDAP
5. in Name => type special characters and see them allowed
6. in Name => add a `*` to any text, see that it is disallowed.
> Update member expression regex to include special characters

- components/automate-ui/e2e/helpers/browser_expectations.ts
- components/automate-ui/src/app/entities/layout/layout.actions.ts
- components/automate-ui/src/app/entities/layout/layout.facade.ts
- components/automate-ui/src/app/entities/layout/layout.reducer.ts
- components/automate-ui/src/app/entities/layout/layout.selectors.ts
- components/automate-ui/src/app/modules/policy/list/policy-list.component.html
- components/automate-ui/src/app/modules/policy/list/policy-list.component.ts
- components/automate-ui/src/app/modules/roles/list/roles-list.component.html
- components/automate-ui/src/app/modules/roles/list/roles-list.component.ts
- components/automate-ui/src/app/modules/team/team-management/team-management.component.html
- components/automate-ui/src/app/modules/team/team-management/team-management.component.ts
- components/automate-ui/src/app/modules/token/token-list/api-token-list.component.html
- components/automate-ui/src/app/modules/token/token-list/api-token-list.component.ts
- components/automate-ui/src/app/modules/user/user-management/user-management.component.html
- components/automate-ui/src/app/modules/user/user-management/user-management.component.ts
- components/automate-ui/src/app/pages/+compliance/+profile/+profile-details/profile-details.component.html
- components/automate-ui/src/app/pages/+compliance/+profile/+profile-details/profile-details.component.ts
- components/automate-ui/src/app/pages/+compliance/+profile/+profile-overview/profile-overview.component.html
- components/automate-ui/src/app/pages/+compliance/+profile/+profile-overview/profile-overview.component.ts
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.html
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.ts
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profile/reporting-profile.component.html
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profile/reporting-profile.component.ts
- components/automate-ui/src/app/pages/+compliance/+scanner/containers/scanner/scanner.component.html
- components/automate-ui/src/app/pages/+compliance/+scanner/containers/scanner/scanner.component.ts
- components/automate-ui/src/app/pages/project/list/project-list.component.ts
- components/automate-ui/src/app/ui.component.html
- components/automate-ui/src/app/ui.component.scss
Loading overlay should be over the full page content (excluding top and left navigation). It seems to not be extending to the bottom of the page. Note: many pages use the loading overlay.
https://app.zenhub.com/workspaces/ui-team-5cba23a3b14fdc05970c8f87/issues/chef/automate/2263
fixes #2263
Loading overlay should extend to the bottom of the page.
navigate to compliance/compliance-profiles (only cause its the slowest loading page)
notice the loading overlay stops short and does not extend to the bottom of the page
> Loading Overlay Size Issue

- components/automate-ui/src/app/entities/layout/layout.facade.ts
- components/automate-ui/src/app/page-components/event-feed-table/event-feed-table.component.html
- components/automate-ui/src/app/page-components/resources/resources.component.html
- components/automate-ui/src/app/page-components/resources/resources.component.scss
- components/automate-ui/src/app/page-components/run-history/run-history.component.scss
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.html
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profile/reporting-profile.component.html
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profiles/reporting-profiles.component.html
- components/automate-ui/src/app/pages/+compliance/+scanner/containers/jobs-list/jobs-list.component.html
- components/automate-ui/src/app/pages/+compliance/+scanner/containers/nodes-list/nodes-list.component.html
- components/automate-ui/src/app/pages/node-details/node-details.component.html
- components/automate-ui/src/app/ui.component.html
- components/automate-ui/src/styles.scss
The run history panel, compliance/scan-job error panel, and compliance/reports scan results panel are not positioned correctly. They seem to not correctly take up the right space vertically.
https://app.zenhub.com/workspaces/ui-team-5cba23a3b14fdc05970c8f87/issues/chef/automate/2238
fixes #2238
Run history panel is not cut off on top and does extend to the bottom of page.
navigate to infrastructure/client-runs and go to a node detail page
scroll down
then open the run history panel
notice that the top is cut off
> Right panel positioning issue

- components/automate-ui/src/app/modules/policy/add-members/policy-add-members.component.scss
- components/automate-ui/src/app/pages/project/rules/project-rules.component.scss
- components/chef-ui-library/src/templates/chef-page/chef-page.scss
Notifications left around from previous actions at the top of the screen were forcing the footer of chef-page off page.  Realized that since chef-pages are all full screen, we can make the footer of chef-page fixed so that content can never force it off screen.
fixes #2374
Notifications do not affect our ability to see the save or cancel buttons on chef-page components
_you may also need to run make update-ui-lib from automate-ui folder_
Create a project
Quickly click Create Rule
You will see the full screen create rule modal correctly display the notification for a bit with the rest of the modal rendered properly
After the notification times out or is removed, the buttons rendered in the bottom of the modal will remain in the …
> Make footer on chef-page fixed

- components/automate-chef-io/content/docs/node-integrations.md
- components/automate-ui/src/app/pages/integrations/add/integrations-add.component.ts
- components/automate-ui/src/app/pages/integrations/aws-form/aws-form.component.html
- components/compliance-service/inspec-agent/resolver/resolver.go
- components/nodemanager-service/api/manager/server/server.go
- components/nodemanager-service/managers/awsec2/awsec2.go
- components/nodemanager-service/managers/awsec2/awsec2_test.go
- components/nodemanager-service/managers/managers.go
When accessing the AWS api, a region value is required. We've been defaulting to the value of env var "AWS_REGION" and using "us-east-1" when the env var is not set.
This change modifies the code to also accept (and prefer) a region value by credential.
That means that a user can now add an integration with the following api body:
```
'{"name":"test (fake) aws-api integration","type":"aws-api","credential_data":[{"key":"AWS_ACCESS_KEY_ID","value":"test"},{"key":"AWS_SECRET_ACCESS_KEY","value":"test"},{"key":"AWS_REGION","value":"us-gov-west-1"}],"instance_credentials":[]}'
```
If the region is included in the api call, we use that value. If it is not specified, we go back to the original code path of looking for the env var and then falling back to us-east-1 as a default. …
> allow user to include region when creating aws mgr

- components/compliance-service/reporting/util/csv.go
- components/compliance-service/reporting/util/csv_test.go
small quick one! @teknofire let us know that excel chokes on cells with over 32k characters, which can sometimes happen with unruly controls. this change ensures that we check the character count on result messages and code descriptions for controls, returning a truncated message if it is 32k or more characters.
didn't open an issue for this, so nothing to link to here.
items with more than 32k characters are truncated
i did the manual hacky way of testing this, which is basically just inserting a string that is over 32k characters long into the maxCharLimit function. 
- [n/a ] Docs added/updated?
> csv export: truncate responses with more than 32k characters

- components/automate-ui/e2e/admin.e2e-spec.ts
- components/automate-ui/src/app/entities/roles/role.actions.ts
- components/automate-ui/src/app/entities/roles/role.effects.ts
- components/automate-ui/src/app/entities/roles/role.reducer.ts
- components/automate-ui/src/app/entities/roles/role.requests.ts
- components/automate-ui/src/app/entities/roles/role.selectors.ts
- components/automate-ui/src/app/modules/roles/list/roles-list.component.html
- components/automate-ui/src/app/modules/roles/list/roles-list.component.scss
- components/automate-ui/src/app/modules/roles/list/roles-list.component.spec.ts
- components/automate-ui/src/app/modules/roles/list/roles-list.component.ts
**Overview**
In the roles list view in the UI, all custom roles should have the control menu with a delete option. On delete, a confirmation modal should be displayed.
**Design Details**
Add control (3-dot) menu to the roles list view on custom roles
Add confirmation modal
I have added new changes to delete the custom created roles using the delete confirmation modal popup.
fixes #1692
Previously delete functionality is not available from UI side to delete the custom created roles, I have added new changes for this functionality.
1. `build components/automate-ui`
1. add a custom role `curl -XPOST -d '{"name": "Test", "id": "test", "actions": ["infra:*","compliance:*","teams:*","users:*"],"projects": []}' -H "api-token: $token" https://a2-dev.test/apis/iam/v2beta/roles?pretty --insecure` …
> Delete functionality for custom created roles

- components/automate-cli/cmd/chef-automate/backup.go
Previously, if you passed `/path/to/backupid/` to restore,
it would interpret that in a way that didn't make sense.
Only /path/to/backupid was allowed. Since restore with a
argument can only mean path to a specific backup, we now
trim any extra "/"
> Allow restores of the form `/path/to/backupid/`

- terraform/test-environments/modules/chef_automate_install/templates/install_chef_automate_cli.sh.tpl
We've upgraded Hab to a version that requires license acceptance.
> terraform: accept hab license

- components/automate-deployment/pkg/target/local_target.go
The newest version of install.sh doesn't support passing the release,
only the version.
This is a quick-fix for the problem, but we will follow up by
completely removing the need for install.sh.
> deployment: don't pass release to install.sh

- .expeditor/buildkite/inspec.sh
This script requires us to accept the hab license because we are
calling `hab` from inside the tests.
> buildkite: accept the hab license in another place

- components/automate-ui/src/app/modules/policy/list/policy-list.component.html
- components/automate-ui/src/app/modules/roles/list/roles-list.component.html
- components/automate-ui/src/app/modules/team/team-management/team-management.component.html
- components/automate-ui/src/app/modules/token/token-list/api-token-list.component.html
- components/automate-ui/src/app/modules/token/token-list/api-token-list.component.scss
- components/automate-ui/src/app/modules/user/user-table/user-table.component.html
- components/automate-ui/src/app/pages/project/list/project-list.component.html
This PR removes introspection around the control menu on each project for the time being due to two issues.
1. Parameterized introspection is not yet set up for projects.
2. A back-end call for each resource is too much overhead.
N/A
Network calls to the introspect endpoint do not occur for each project in the projects list.
Watch in the network tab when you reload the projects page that introspect calls on each specific project do not occur.
> [automate-2366] Remove introspection from individual projects on list page

- components/automate-builder-api/habitat/plan.sh
We need to pin curl in automate-builder-api until builder-api gets
rebuilt
> Pin curl in builder-api

- components/nodemanager-service/Makefile
noticed while working on a thing locally that a test i expected to fail was not failing.
started looking into it and noticed a "no test files" msg being printed.
checked on buildkite and saw the same:
```
* NodeManager Service is running, moving on...
make[1]: Leaving directory `/var/lib/buildkite-agent/builds/single-use-privileged-i-0ec9b0c7d6c74c73c-1/chef-oss/.golang/chef-automate-master-verify/src/github.com/chef/automate/components/nodemanager-service'
===> Running db integration tests with PG6
make[1]: Entering directory `/var/lib/buildkite-agent/builds/single-use-privileged-i-0ec9b0c7d6c74c73c-1/chef-oss/.golang/chef-automate-master-verify/src/github.com/chef/automate/components/nodemanager-service'
?   	github.com/chef/automate/components/nodemanager-service	[no test files] …
```
> makefile: ensure the db tests for nodemanager actually run

- components/automate-openjdk/habitat/plan.sh
Build didn't get published because we were supposed to manually create a tag for the package first
> Force jdk rebuild

- components/automate-deployment/pkg/target/local_target.go
Users on SLES have seen Automate fails to start with with:
Error: Failed to start service: Failed to load service chef/automate-load-balancer/0.1.0/20191031214341
Output:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
: exit status 101
Deploy failed
DeployError: Unable to install, configure and start the service: deploy failed
and with the following in `dmesg`:
[ 814.796021] cgroup: fork rejected by pids controller in
/system.slice/chef-automate.service
Support tracked this down to the fact that SLES ships a low
DefaultMaxTasks. Setting it to infinity in our unit file should leave
us unconstrained by their …
> deployment: set TasksMax=infinity in unit file

- components/chef-ui-library/src/atoms/chef-loading-spinner/chef-loading-spinner.scss
The Project and Profile dropdowns were hidden behind the chef-loading-spinner.  The simplest adjustments was to back the z-index of the chef-loading-spinner down a little.
https://github.com/chef/automate/pull/2227
https://github.com/chef/automate/issues/2012
Overlay no longer hiding dropdowns
1. build components/automate-ui-devproxy
2. navigate to https://a2-dev.test/compliance/compliance-profiles
3. while profiles are loading, click on the projects and/or user dropdowns, they should sit over the top of the overlay.
Before
After
> Back z-index down a notch

- components/automate-cs-nginx/habitat/plan.sh
We are still pinned to an older version of automate-cs until we finish
up an investigation of why we are seeing test failures on the latest
build.  To avoid dependency conflicts, this means that any deps that
are shared with the automate-cs-* packages need to be pinned.
> automate-cs-nginx: pin curl to address build failure

- lib/platform/pg/exporter.go
- lib/platform/pg/exporter_test.go
We do not currently globally accept the license for `hab` and have
rather opted to pass the HAB_LICENSE environment variable in various
locations. We forgot to pass the variable here.
We should consider calling `hab license accept` for the user somewhere
to avoid this game of wack-a-mole.
> a1upgrade: set HAB_LICENSE when calling hab commands

- components/automate-cli/cmd/chef-automate/chef-automate.go
- components/automate-deployment/cmd/deployment-service/deployment-service.go
- components/automate-deployment/pkg/a1upgrade/filemover.go
We now set HAB_LICENSE=accept-no-persist at the startup of
deployment-service and automate-cli. This will hopefully help end the
wack-a-mole.
> deployment/automate-cli: set HAB_LICENSE at startup

- components/compliance-service/api/tests/01_market_spec.rb
- components/compliance-service/dao/pgdb/migration/sql/40_denormalize_profiles_columns.down.sql
- components/compliance-service/dao/pgdb/migration/sql/40_denormalize_profiles_columns.up.sql
- components/compliance-service/profiles/db/store.go
While working on #2367 I noticed that despite the profiles database table having indexes on it, they weren't being used.
```
chef_compliance_service=# \d store_profiles
Table "public.store_profiles"
Column | Type  | Collation | Nullable | Default
--------+-------+-----------+----------+---------
sha256 | text  |           | not null |
tar    | bytea |           | not null |
info   | jsonb |           | not null |
Indexes:
"store_profiles_pkey" PRIMARY KEY, btree (sha256)
"idxprofileinfoname" btree ((info ->> 'name'::text))
"idxprofileinfoversion" btree ((info ->> 'version'::text))
Check constraints:
"store_profiles_sha256_check" CHECK (sha256 <> ''::text)
Referenced by:
TABLE "store_market" CONSTRAINT "store_market_sha256_fkey" FOREIGN KEY (sha256) REFERENCES store_profiles(sha256)
TABLE …
```
> Add indexes for profile list queries

- components/automate-ui/src/app/entities/projects/project.reducer.ts
- components/automate-ui/src/app/pages/project/list/project-list.component.ts
Reset the project update status state in the store when we kick off the project update and also fix some small issues with the update logic.
Boot up the UI and run some project updates. You should no longer briefly see 100% get returned. This was because it was getting back 100% complete due to race condition between project update kickoff API request and status endpoint.
> [AUTOMATE-1654] Reset the project update state on update and properly render state

- Vagrantfile
The new install.sh doesn't support passing the release, so now we pull
out just the version.
> studio: pull out just the hab version from manifest

- components/automate-chef-io/Makefile
Previously, not having go-swagger installed would prevent the API docs from being built but it was not always obvious that this was an error:
```
Petes-MacBook-Pro:automate-chef-io pete$ make generate_swagger ; echo $?
swagger mixin -c=0 data/docs/api-static//00-meta.swagger.json data/docs/api-static//01-reporting-export.swagger.json data/docs/api-static//02-meta-description.yaml data/docs/api-static//03-tags.swagger.json data/docs/api_chef_automate/license/license.swagger.json data/docs/api_chef_automate/event_feed/response/event.swagger.json data/docs/api_chef_automate/event_feed/response/eventstrings.swagger.json data/docs/api_chef_automate/event_feed/event_feed.swagger.json data/docs/api_chef_automate/event_feed/request/event.swagger.json …
```
> Make missing go-swagger command an explicit error when building API docs

- components/automate-ui/src/app/pages/service-groups/service-groups.component.ts
Fixes a bug in the Apps tab UI where selecting a service filter with zero services would cause a new service group to be selected. I think the logic that caused this was intended only be triggered when the user applied a filter via the textual filter bar that filtered all the services in the selected service group; that behavior has been maintained.
#2073 
With automate running and data populated in the apps tab:
* select a service group that has zero services in one of the health statuses (e.g., a service group with all services critical works)
* click one of the filters on the right side services panel for which there are zero services (e.g., if all services are critical then click the "warning," "OK," or "unknown" filters.
* without this patch the UI will pick the first service group …
> Apps tab: don't focus new service group when clicking a service filter that filters all the services

- ec2/Vagrantfile
This is the same fix that was put into the Vagrantfile at root of this repo in pr #2431.
This same sort of change needed to also be in ec2 Vagrantfile
The new install.sh doesn't support passing the release, so now we pull out just the version.
> for ec2 Vagrantfile, pull out just the hab version from manifest

- components/automate-ui/src/app/pages/service-groups/service-groups.component.ts
On the apps tab, when a status filter is selected, the user's selection for current service group, status filter for services, and current page on the services list are reset. These should only be reset if the selected filter excludes the selected service group. For example, if the selected service group contains services in the critical state and the user selects the critical health filter, the currently selected service group matches so we shouldn't reset these selections. If the user clicks the warning filter, then the selected service group doesn't match so we _should_ reset the selection. To get this behavior fully correct with pagination would be really complicated so I've implemented a compromise where the service group selection gets reset when the service group content loads and …
> Apps Tab: don't reset service group selection and related state until service group no longer listed

- components/automate-ui/src/app/entities/service-groups/service-groups.facade.ts
The apps tab gets current and previous status switched when generating timewizard messages. This PR flips them to the correct order.
Chef software employees can see a customer screenshot of the bug in action in the a2-eas-beta channel.
> Fix backwards timewizard message in apps tab

- .studio/applications-service
Update the data generator for the apps tab to trigger more features and allow you to check more edge cases in development.
* trigger the timewizard in sample data
* add a multisite service group to help test some edge cases
Also add helpers for database access
`source .studio/applications-service` in the studio and run the new things.
> Add more cases to apps tab sample data

- components/compliance-service/api/tests/test_ingest_to_mgr_conn.rb
- components/nodemanager-service/api/nodes/server/server.go
- components/nodemanager-service/tests/aws_ec2_nodes_integration_test.go
this change prevents users from updating the name or tags on ingested nodes (nodes with no manager)
users may update other fields, such as the credential id for the node or backend, port, host information.
the name and tags are collected at ingestion time from the chef-client and inspec reports.
also made the inability to update aws-ec2 or azure-vm node names, tags, and host more obvious.
n/a
user not allowed to update name or tags on ingested node
rebuild nodemanager
ingest some nodes
try to update name of ingested node
> do not allow users to update name or tags of ingested nodes

- components/compliance-service/api/tests/02_deep_nodes_spec.rb
- components/compliance-service/reporting/relaxting/depth.go
- components/compliance-service/reporting/relaxting/nodes.go
- components/compliance-service/reporting/relaxting/reports.go
- components/compliance-service/reporting/relaxting/stats_control_level.go
- components/compliance-service/reporting/relaxting/stats_profile_level.go
This change sets waiver sums for control as well as profile level depths for support of deep filtering in stats node api
> control and profile level waivers for nodes

- components/automate-chef-io/data/docs/api-static/02-meta-description.yaml
- components/automate-chef-io/data/docs/api-static/04-meta-auth.json
In order for consumers of the OpenAPI documentation to easily authenticate with our API, we have documented the authentication header according to the [OpenAPI specs for security definitions objects](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#security-definitions-object). 
- fixes #2140
```
make serve
```
navigate to http://localhost:1313/docs/api/#section/Authentication
> [automate-2140] API Documentation: Auth Security Definitions

- components/notifications-service/habitat/hooks/run
Modern versions of systemd seem to export this as an environment
variable. This confuses distillery which thinks it is to write to that
file.
We should probably do this for all the services
> Unset PIDFILE in notifications-service

- Makefile
- lib/io/fileutils/atomic_write.go
- scripts/revendor.sh
This fixes two problems that led to `revendor` not working correctly.
Previously, we were copying files from grpc-ecosystem/grpc-gateway
manually into our vendor directory. However, to determine the path to
copy from, we needed to look up the the path after installation. But,
because of some confusion about how `$(eval)` works, this did not work
on systems where that go module was not already installed.
To fix this, I've moved this logic to a shell script since I think
more people will be able to reason about the behavior of the shell
script.
Additionally, we now ignore EINVAL from directory syncs in the atomic
writer. Vboxfs and potentially other filesystems don't support calling
sync on a directory, returning EINVAL. This has been a recurring
source of confusion. Other bits of code turn …
> fix revendor target and ignore EINVAL in atomic writer

- components/automate-builder-memcached/habitat/hooks/run
This was being set twice, once to an incorrect value
> automate-builder-memcached: remove extra ssl_key flag

- components/automate-builder-api/habitat/default.toml
This shouldn't get used in general, but that matches
what automate will set it as
> Set default log level to error for builder-api

- components/automate-cli/cmd/chef-automate/upgrade.go
- integration/tests/manual_upgrade.sh
This change allows users to run
chef-automate upgrade run --version RELEASE
to upgrade to a specific version of Chef Automate. It does not allow
downgrades and does not allow specific version upgrades when in airgap
mode.
> support `chef-automate upgrade run --version VERSION`

- components/automate-ui/src/app/modules/team/team-add-users/team-add-users.component.ts
- components/automate-ui/src/app/modules/team/team-details/team-details.component.html
- components/automate-ui/src/app/modules/team/team-details/team-details.component.ts
This includes fixes for 3 browser console errors:
Repro steps:
Teams > (team) > users > add users
Note this issue surfaced after (1) was fixed, so you will not see it on master.
Repro steps:
Teams > (team) > users > add users > (close)
Repro steps:
Teams > (team) > (browser refresh)
N/A
None of the errors above appear in the browser console log.
- Rebuild automate-ui
- Open dev tools (<kbd>cmd</kbd> + <kbd>opt</kbd> + <kbd>i</kbd>)
- Follow the repro steps noted above.
> Assorted ui display bug fixes

- .expeditor/nightly.pipeline.yml
This test is broken in multiple ways. The most egregious are:
- backups are taken before the modified configuration is applied
- the backup location is incorrectly deteremined by the restore
command
We are working on a series of changes to address this.  For now, this
unblocks the nightlies.
> ci: temporarily disable "backups repo permissions" test

- e2e/cypress/index.d.ts
- e2e/cypress/integration/api/iam/01_projects_api.spec.ts
- e2e/cypress/integration/api/iam/10_projects_api_action_update.spec.ts
- e2e/cypress/integration/api/iam/11_projects_api_action_ingestion.spec.ts
- e2e/cypress/integration/api/iam/12_projects_api_node_ingestion.spec.ts
- e2e/cypress/integration/api/iam/13_projects_api_node_update.spec.ts
- e2e/cypress/integration/api/iam/14_projects_delete_api.spec.ts
- e2e/cypress/support/commands.ts
Add integration tests for the cases preventing project delete. 
A user can not delete a project when:
* The project has applied rules
* The project has staged rules
* The project has deleted applied rules
#2449 
Look at the cypress test in buildkite
> Adding project delete integration tests

- components/data-feed-service/service/data-feed-aggregate-task.go
- components/data-feed-service/service/data-feed-poll-task.go
- components/data-feed-service/service/data-feed-service.go
- components/data-feed-service/service/data-feed-workflow.go
The DataFeedWorkflowParams have been refactored. These are no longer shared with the poll and aggregate tasks, these now have their own params 
DataFeedPollTaskParams
DataFeedAggregateTaskParams
I also moved the scheduling update into the workflow as it updates the workflow params which are no longer passed to the poll task.
Also removed the tasksComplete from the payload and it is now a local variable.
> Code review: refactor the workflow and tasks parameters

- components/automate-deployment/pkg/backup/event_handler.go
- components/automate-deployment/pkg/backup/event_handler_test.go
- components/automate-deployment/pkg/backup/executor.go
- components/automate-deployment/pkg/backup/executor_test.go
- components/automate-deployment/pkg/backup/runner.go
- components/automate-deployment/pkg/backup/runner_test.go
- components/automate-deployment/pkg/backup/spec.go
- components/automate-deployment/pkg/backup/spec_test.go
Currently, we do not use any async operations so these should be safe
to remove. This is one in a number of steps we want to take to reduce
the scope of the backup/restore code.
> backup: Remove async operations

- components/automate-chef-io/layouts/404.html
This adds a 404 page to automate.chef.io. 
n/a
Users see a proper 404 page if they navigate to a page that doesn't exist.
`make serve` then navigate to `localhost:1313/404.html`
Unfortunately you [can't test](https://discourse.gohugo.io/t/how-to-test-404-html-on-local-server/681) if the 404 page works locally.
> Add 404 page to automate-chef-io

- components/config-mgmt-service/backend/client.go
- components/config-mgmt-service/backend/elastic/elastic.go
- components/config-mgmt-service/backend/elastic/nodes.go
- components/config-mgmt-service/backend/elastic/runs.go
- components/config-mgmt-service/backend/mock/mock.go
- components/config-mgmt-service/grpcserver/cfg_mgmt.go
- components/config-mgmt-service/grpcserver/node_export.go
- components/config-mgmt-service/grpcserver/report_export.go
- components/config-mgmt-service/integration_test/node_export_test.go
- components/config-mgmt-service/params/parameters.go
- components/config-mgmt-service/params/parameters_test.go
Attempted fix for #2284.
Sorting on the client runs export endpoint was being done case sensitively, and this made it so that the paginated could be incomplete with a large number of similarly named nodes. I believe this happened because the pagination for this endpoint works by remembering that last position in the list and searching for matching elements after that one; when lots of the nodes had similar names differing in case, this made it so finding the last element when fetching the next page was unreliable. This PR contains a fix for the incomplete data issue, but it necessarily includes a behavior change because it's unclear whether we can support a case sensitive sort with the way pagination is implemented.
Before the sorting changes in this PR, the test would reliably fail with …
> Fix client runs export incomplete data bug

- components/automate-ui/src/app/app-routing.module.ts
- components/automate-ui/src/app/entities/layout/layout-sidebar.service.ts
- components/automate-ui/src/app/entities/service-groups/service-groups.facade.ts
- components/automate-ui/src/app/entities/service-groups/service-groups.model.ts
- components/automate-ui/src/app/entities/service-groups/service-groups.reducer.ts
- components/automate-ui/src/app/page-components/navbar/navbar.component.html
- components/automate-ui/src/app/page-components/services-sidebar/services-sidebar.component.ts
- components/automate-ui/src/app/pages/service-groups/service-groups.component.ts
Updates the URLs in the apps tab as specified in #1884
Removes services view state from the URL; instead it is managed in the application memory. This makes sense architecturally because a particular service group can come and go from a set of service group filters over time. For example, if the critical status filter is selected, and the services within a service group all change status to `OK`, then the URL `/applications/service-groups?status=critical&sgId=<the id>` no longer refers to the same content in the same way.
This change means that when users share URLs they won't have the same service group selection state, though if a user wishes to construct a URL that shows just a particular service group, they can still do so with the filtering functionality we have.
Making this change …
> Remove services view state from URL and update service groups URL

- components/automate-elasticsearch/habitat/config/init_keystore
It's possible that ElasticSearch will leave a temporary keystore file
around when the service is stopped. Upon restart the temporary keyfile
will prevent the service from starting:
automate-elasticsearch.default(O): Exception in thread "main"
org.elasticsearch.bootstrap.BootstrapException:
java.nio.file.FileAlreadyExistsException:
/hab/svc/automate-elasticsearch/config/elasticsearch.keystore.tmp
Here, we automatically detect and remove the old temporary file when
initializing the keystore during startup.
> [automate-elasticsearch] Remove stale keystore file when starting service

- components/config-mgmt-service/integration_test/README.md
* `enter_go_workspace` is apparently no longer necessary. If I try to do that in my local env I see this error, but all the other commands work fine without it:
```
[1][default:/src:0]# enter_go_workspace
ERROR: Unable to setup Go Workspace.
ERROR: setup_go_workspace: requires the 'pkg_scaffolding' variable to exist in your plan.sh
```
* Starting elasticsearch without appending `--with-deps` to the command will make it so the command doesn't start and the service health check will fail.
> Update config-mgmt integration test instructions

- components/automate-chef-io/content/docs/backup.md
The instructions did not include what to backup if you're not using S3
and the 'automate-elasticsearch-data' was a crucial component. Restoring
appears to currently require being in the default backup directory.
Signed-off-by: Matt Ray <matthewhray@gmail.com>
> Add instructions for creating and restoring airgapped offline backups

- components/automate-ui/src/app/entities/service-groups/service-groups.facade.ts
- components/automate-ui/src/app/page-components/services-sidebar/services-sidebar.component.html
- components/automate-ui/src/app/page-components/services-sidebar/services-sidebar.component.scss
- components/automate-ui/src/app/pages/service-groups/service-groups.component.html
- components/automate-ui/src/app/pages/service-groups/service-groups.component.scss
- components/automate-ui/src/app/pages/service-groups/service-groups.component.ts
Users want to know which services are disconnected from automate so they can remediate problems. We currently have badges for disconnected services but no way to filter for them.
#1780 
Build:
* `build components/automate-ui`
* `start_all_services`
Sample Data:
Generating the sample data is time-sensitive since the data generator doesn't create health check messages with timestamps in the past. What I did was:
* run `applications_populate_database`
* Wait 5m
* run it again
Then within the next 5 minutes:
* Filter for `environment: production`, this reduces the data down to 5 service groups
* Click the service groups disconnected status filter, there should be only 4 matching service groups (the group `wizrd.default` should be filtered out and not visible)
* All the service groups visible …
> Filter service groups and services by disconnected status

- .expeditor/generate-automate-cli-docs.sh
Expeditor needs to be bumped go 1.13 for building the automate-cli.
> Bumping expeditor to go 1.13

- components/automate-ui/src/app/components/settings-sidebar/settings-sidebar.component.spec.ts
- components/automate-ui/src/app/components/sidebar/sidebar.component.spec.ts
- components/automate-ui/src/app/modules/license/license-notifications/license-notifications.component.spec.ts
- components/automate-ui/src/app/modules/policy/list/policy-list.component.spec.ts
- components/automate-ui/src/app/ngrx.reducers.ts
- components/automate-ui/src/app/pages/+compliance/+scanner/containers/jobs-list/jobs-list.component.spec.ts
- components/automate-ui/src/app/pages/job-add/job-add.component.spec.ts
- components/automate-ui/src/app/pages/job-edit/job-edit.component.spec.ts
- components/automate-ui/src/app/pages/notifications/notifications.component.spec.ts
- cspell.json
Trying to resolve a lot of noise being generated by UI unit tests (see #2486)
was causing compilation errors. It turns out that the new work of #2486 (automate unit test noise) was exposing a hidden bug in the unit test setup that had been recently introduced from #1485 (moving the license banner)--some calls to `StoreModule.forRoot` were passing incorrect arguments.  That bug in turn was masking one more bug: two properties in the `defaultInitialState` used by ngrx store were defined incorrectly.
This PR corrects both of those issues.
Here's the signature for [forRoot](https://ngrx.io/api/store/StoreModule):
And here is the [RootStoreConfig](https://ngrx.io/api/store/RootStoreConfig) interface:
Notice that `RootStoreConfig` has an `initialState` property, which is where the …
> [Automate-2593] fix unit test ngrx setup

- components/compliance-service/reporting/relaxting/indices.go
- components/compliance-service/reporting/relaxting/indices_test.go
This change fixes a bug that occurs when selecting Dec 31 as end_time for api calls on compliance reporting
> fix bug new years too many indices bug

- components/automate-ui/tsconfig.json
Lately, every time opening TS files in the automate-ui project in VSCode, one gets a balloon warning:
Besides that warning I have also been seeing a lot of **false** TypeScript errors showing up upon opening TypeScript files for editing, starting with calling out many of the import statements and "could not find...". Those, of course, cascaded many other errors in the files. This seemed to occur randomly--no particular files for any particular reason, and not all the time.
Anecdotally, this patch seems to have resolved that as well. 🤞 
Per [this post](https://github.com/Microsoft/vscode/issues/31188#issuecomment-317588447) I enabled TypeScript server logging to identify large directories that are generated files rather than working code: the `dist` and `assets` dirs. So those are being …
> [automate-2587] Exclude non-working ts files

- components/automate-gateway/gateway/middleware/authv2/authv2.go
- components/event-gateway/pkg/nats/authenticator.go
When we changed nomenclature from "subject" to "members" for IAM v2, we missed a couple error messages.
This PR changes this...
```
unauthorized: subjects ["token:t1"] cannot perform action "iam:users:list"
on resource "iam:users" filtered by projects []
```
to this...
```
unauthorized: members ["token:t1"] cannot perform action "iam:users:list"
on resource "iam:users" filtered by projects []
```
Also identified a similar message in event-gateway so I updated that; not sure how to evoke that from the API.
NA
"Members" appears in error messages.
Rebuild
```
```
Create a token and use it to query most any endpoint:
```
$ curl -sSkH "api-token: <your-token-here>" https://a2-dev.test/apis/iam/v2beta/users?pretty
{
"error": "unauthorized: members [\"token:t1\"] cannot perform action …
```
> [automate-2560] Change "subjects" to "members" for IAM v2

- components/automate-ui/src/app/helpers/auth/id-mapper.spec.ts
- components/automate-ui/src/app/helpers/auth/id-mapper.ts
**Note: I was so tempted to make this the smallest PR on record -- a single character -- but I would not be able to face myself in the morning if I did not apply TDD and do the tests first. Sigh.**
Back in PR #1172 (allow underscore IDs in IAM resources) we expanded the allowable character set for IAM IDs to include an underscore character. However, one spot that was missed was the auto-generated IDs in the UI, specifically in the `CreateObjectModalComponent` that is (at present) used for creating new teams, tokens, and projects.
PR #1172 (allow underscore IDs in IAM resources)
When entering a name for a team, token, or project in the UI, the auto-generated ID that appears preserves any underscores that are typed (along with hyphens, digits, and alphabetic characters).
Rebuild …
> [automate-2570] preserve underscores in auto-generated IAM ids

- components/automate-chef-io/data/docs/api-static/01-reporting-export.swagger.json
- components/automate-gateway/api/compliance/reporting/reporting.pb.go
- components/automate-gateway/api/compliance/reporting/reporting.proto
- components/automate-gateway/api/compliance/reporting/reporting.swagger.json
- components/automate-gateway/api/compliance_reporting_reporting.pb.swagger.go
- components/compliance-service/api/reporting/server/server.go
- components/compliance-service/api/tests/export_test.go
- components/compliance-service/reporting/relaxting/reports.go
This code change addresses two issues:
- when a single control filter is applied on export (and no profile filter is included), the report should be filtered by that control (only that control is returned)
- allow filtering by multiple controls
https://github.com/chef/automate/issues/2255
filtering by a single control filter returns a report with only that control
filtering by multiple control filters returns reports with only those controls included
filter by a single control, no profile
expect exported report/viewed report to only include that one control
filter by a multiple controls, no profile
expect exported report/viewed report to only include specified controls
> specifying multiple control filters on export returns only those controls

- e2e/package-lock.json
The recent version bump for node to v12.13.1 (https://github.com/chef/automate/pull/2579) omitted doing a package update in the automate-ui/e2e directory. This PR addresses that.
NA
`npm install` shows no changes to package.json or package-lock.json.
```
cd e2e
npm install
```
> cypress package updates

- components/automate-chef-io/content/docs/iam-v1-overview.md
The below command was missing the "team:ldap:ops" from the subjects. 
`curl -s -H "api-token: $TOKEN" -H "Content-Type: application/json" -d '{"subjects":["user:local:user@example.com"], "action":"read", "resource":"cfgmgmt:nodes:*"}' https://automate.example.com/api/v0/auth/policies?pretty`
https://automate.chef.io/docs/iam-v1-overview/#structure
Below is what the docs look like after the correction.
> Correcting a Command on the IAMv1 Docs

- components/automate-cli/cmd/chef-automate/cert.go
Command takes --file and --hostname as args
Supports multiple certificates if there is more than one
This command makes it easier for a user to retrieve the frontend_tls certificate that
is configured for automate, which will make it easier to set up encrypted comms with habitat
Added a new automate cli command 'external-cert show'
build components/automate-cli
`chef-automate external-cert show -h` to see help information
`chef-automate external-cert show` should print out the certifcate
`chef-automate external-cert show -f automate.crt` should save the cert to automate.crt file with 0644 permissions. 
Testing hostname arguments: 
Hostname is not set by default in the frontend_tls block. It can be added under the key …
> Add chef-automate external-cert show command to automate-cli

- components/automate-ui/src/app/components/sidebar-no-shade/sidebar-no-shade.component.scss
- components/automate-ui/src/app/components/sidebar/sidebar.component.scss
- components/automate-ui/src/app/modules/license/license-notifications/license-notifications.component.scss
- components/automate-ui/src/app/page-components/feature-flags/feature-flags.component.html
- components/automate-ui/src/app/page-components/feature-flags/feature-flags.component.scss
- components/automate-ui/src/app/page-components/feature-flags/feature-flags.component.ts
- components/automate-ui/src/app/page-components/json-tree/json-tree.component.scss
- components/automate-ui/src/app/pages/project/rules/project-rules.component.scss
@jyan-chef recently worked with legal to refine the feature flag text for Workstation; this pr updates that text to match in Automate too.. yay for consistency! i also made a few style changes to get this modal a bit closer to the rest of the modals in Automate. Note: those toggles prolly need to be updated too, to the angular material component, but will leave those as-is for now.
(from legal)
"The warranties and indemnities in your license agreement do not apply to experimental features. Experimental features are provided "as is" with no warranties of any kind, express or implied. Chef disclaims any and all liability related in any way to the experimental features or any related documentation."
Feature flag text is refined and the feature flag modal still works as before.
1. `rebuild …
> updates to feature flag text + styles

- .expeditor/generate-automate-cli-docs.sh
In 3cc632ce6fab8aa346de7b83e0177b27811c804a we modified the script that builds the CLI docs so it upgrades go to 1.13 in the expeditor environment. However, we didn't use `--force` to overwrite existing binlinks. We are now seeing builds fail where `.expeditor/generate-automate-cli-docs.sh` is stuck with a too-old version of go, and in the logs for those builds, we see 
```
Â» Binlinking go from core/go/1.13.5/20191212163200 into /bin
Â» Binlinking gofmt from core/go/1.13.5/20191212163200 into /bin
Ã˜ Skipping binlink because go already exists at /bin/go. Use --force to overwrite
Ã˜ Skipping binlink because gofmt already exists at /bin/gofmt. Use --force to overwrite
```
Here we add `--force` so that we get the desired effect of upgrading go.
Chef employees can log into the VPN to see …
> update binlinks when upgrading go in expeditor environment

- components/automate-chef-io/content/docs/iam-v2-api-reference.md
- components/automate-chef-io/content/docs/iam-v2-overview.md
- components/automate-chef-io/content/docs/monitoring.md
Added do-not-merge label, because this should be merged **after** the other sub-tasks in epic #2464.
NA
No references to v2beta in the docs.
> [automate-2517] Update v2beta -> v2 in docs

- .github/PULL_REQUEST_TEMPLATE.md
Updating this PR template to fix the "CONTRIBUTING document" link to point to https://github.com/chef/automate/blob/master/CONTRIBUTING.md. 
Create a new PR after this one is merged then ensure the link to the CONTRIBUTING document is correct.
> updating a link in the PR template

- e2e/cypress.json
Cypress started failing recently on every test--
but only on some local machines (Brenna and Michael)
and not others (Tyler) and not buildkite.
Isolated it to this line of code:
https://github.com/chef/automate/blob/04edc6fc9930ab6d2d0c2b9fabb3842a5dc4a8ef/e2e/cypress/support/index.ts#L53
Trials by all auth team members could not conclusively isolate what environmental settings caused it to fail or not, but this at least seems to fix it on those having problems.
Let's see if this holds muster for everyone and buildkite.
- Fix came from [this StackOverflow post](https://stackoverflow.com/a/57933501)
- Documentation for [modifyObstructiveCode](https://docs.cypress.io/guides/references/configuration.html#modifyObstructiveCode)
- A related [story of …
> Deactivate modifyObstructiveCode cypress flag

- components/automate-ui/src/app/entities/users/user.effects.ts
- components/automate-ui/src/app/modules/user/user-table/user-table.component.html
Change user notification on the creation of user to display "Created user: <user's username>." Where <user's username> is the user's ID.  Also, update the column header to "Display Name". 
https://github.com/chef/automate/issues/2623
The notification banner displays the user's ID after a user is created. 
1. `build components/autoate-ui && start_all_services`
1. Open https://a2-dev.test/settings/users
1. Ensure the column header is "Display Name" and not "Name"
1. Create a new user. 
1. Ensure after the user is created ensure the notification banner displays "Created user: <user's username>." like the image below.
> Update the create user notification banner

- components/compliance-service/api/tests/01_market_spec.rb
- components/compliance-service/profiles/db/store.go
As we discovered in #2616, using 0 to represent the first page of paginated results is not necessarily as intuitive as I had originally thought. Given that using 1 for the first page is [somewhat of a convention in automate](https://github.com/chef/automate/blob/d8f6e7482050126e83906d242f56c6c69dbdc7c9/components/applications-service/pkg/params/pagination.go#L10) and is [also used in popular pagination libraries](https://github.com/kaminari/kaminari/blob/master/README.md#the-page-scope), it seems like a good idea to change this.
> Use 1 for the first page of paginated profile results.

- .studio/applications-service
- components/automate-ui/src/app/entities/service-groups/service-groups.facade.ts
- components/automate-ui/src/app/entities/service-groups/service-groups.model.ts
- components/automate-ui/src/app/page-components/services-sidebar/services-sidebar.component.html
- components/automate-ui/src/app/page-components/services-sidebar/services-sidebar.component.scss
Display services' health check messages in the applications tab UI. This enables expedited troubleshooting of problems when users emit helpful information from their health check scripts.
#2554
NOTE: this doesn't include the show more/show less accordion for long messages. That will be done later.
Build:
* `build components/automate-ui`
Test data:
There are some improvements to the sample data to show all of the different UI cases. Either restart the studio or `source .studio/applications-service`. Then `applications_populate_database`.
Verify Behavior:
* Filter for service name `pos-terminal`
* The four `pos-terminal.default` service groups show each of the following cases:
* (production-us-west environment) no health check messages at all: shows informational message with link to …
> Show Services' Health Check Messages

- components/automate-chef-io/content/docs/ldap.md
- components/automate-chef-io/content/docs/saml.md
- dev-docs/auth.md
We want to document a list of our most commonly used IdP configurations for reference. 
I've also added some internal documentation on some known issues.
```
make serve
```
> [automate-2530] document supported LDAP/SAML configurations

- components/automate-cli/pkg/diagnostics/integration/iam_v2.go
- integration/tests/airgap_ow_upgrade.sh
- integration/tests/ha_data_services_migrate.sh
- integration/tests/manual_upgrade.sh
- integration/tests/reset_admin_access_v1.sh
- integration/tests/upgrade_current_master.sh
- integration/tests/upgrade_current_master_habdev.sh
Follow-up to https://github.com/chef/automate/pull/2564, rolls back diagnostic test change.
We cannot update the diagnostic test path to the non-beta path `iam/v2/policy_version` yet because these diagnostics always starts on an older version of Automate (20190501), as a way to ensure any instance that old can still upgrade to latest.
Depending on the outcome of our discussion on v1 backwards compatibility, we may want to leave these tests as is and leave the beta path in place or change these diagnostic tests.
> roll back diagnostics test change

- e2e/cypress/integration/ui/settings/06_token_mgmt.spec.ts
- scripts/auth_collections.sh
Follow-on to https://github.com/chef/automate/pull/2533/; found a couple stragglers of "v2beta".
Also switches defaults in auth_collections to v2 instead of v1.
```
$ authQuery -s users
..."https://a2-iamv2p1-local-inplace-upgrade-acceptance.cd.chef.co/apis/iam/v2/users"
$ authQuery -s -1 users
..."https://a2-iamv2p1-local-inplace-upgrade-acceptance.cd.chef.co/api/v0/auth/users" 
```
Source the scripts/auth_collections.sh script and execute `authQuery` as above (need to provide `$TOK` and `$TARGET_HOST` shell variables).
> Update remaining v2beta stragglers

- components/automate-ui/src/app/page-components/create-v1-team-modal/create-v1-team-modal.component.html
The changed component creates a modal dialog on the teams list page, specifically for v1. But there is also a modal dialog for v2, and both use the same `name-input` id. That is a violation of HTML so the simplest solution is just to delete the V1 `id` as it is not used.
Here's the violation as it appears in the browser console when you load the teams list page:
No browser warning
rebuild automate-ui; navigate to teams list page
> Remove unneeded `id` attribute

- components/automate-ui/src/app/modules/user/user-details/user-details.component.ts
When on a team's detail page, someone clicks the link to view a user and am navigated to that user's details page. In order to see the team again, I use the browser's <-- (back button). I am navigated back to the team details page, but I see a "User Not Found" error banner.
fixes #1700
I have added some changes to fix this issue.
> Fixed back button prompts Not Found error

- api/config/load_balancer/config_request.go
I've bumped this to 2g to account for builder so that the defaults
allow you to slurp up all the core packages
> Bump max body size for automate load balancer

- .expeditor/publish-release-notes.sh
The applications tab is going GA whenever the next dev->acceptance->current promotion cycle is completed (by default next Monday the 27th). Removing it from the "Beta Features" section of the default release notes.
> Remove "applications" from beta features list in release notes

- components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.html
- components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.ts
- components/automate-ui/src/app/entities/users/user.effects.ts
- components/automate-ui/src/app/entities/users/user.reducer.spec.ts
- components/automate-ui/src/app/entities/users/user.reducer.ts
- components/automate-ui/src/app/entities/users/user.selectors.ts
- components/automate-ui/src/app/helpers/auth/username-mapper.spec.ts
- components/automate-ui/src/app/helpers/auth/username-mapper.ts
- components/automate-ui/src/app/modules/user/user-management/user-form/user-form.component.html
- components/automate-ui/src/app/modules/user/user-management/user-form/user-form.component.scss
- components/automate-ui/src/app/modules/user/user-management/user-form/user-form.component.spec.ts
- components/automate-ui/src/app/modules/user/user-management/user-form/user-form.component.ts
- components/automate-ui/src/app/modules/user/user-management/user-management.component.html
- components/automate-ui/src/app/modules/user/user-management/user-management.component.scss
- components/automate-ui/src/app/modules/user/user-management/user-management.component.spec.ts
- components/automate-ui/src/app/modules/user/user-management/user-management.component.ts
- e2e/cypress/integration/ui/settings/01_user_mgmt.spec.ts
When did this...
Become hotter than this???
This PR updates the user creation modal to be consistent with the token/team/project creation modals.
Instead of making the `create-object-modal` fit with the special case of users, we decided to keep the user modal a part of the `user-management` component. We decided it would over-complicate the `create-object-modal` to add special casing for the user modal (extra password fields, rename Name and ID fields to Display Name and Username). This decision resulted in some duplicated code which we should probably extract into a common helper library once we add another creation modal.
There is some potential to refactor the `create-object-modal` so that we can slot any form we need into it. We might consider this when we get to adding a role …
> [auth-2624] user modal update

- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-controls/reporting-controls.component.html
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-nodes/reporting-nodes.component.html
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profiles/reporting-profiles.component.html
- components/automate-ui/src/app/pages/data-feed/data-feed.component.html
- components/automate-ui/src/app/pages/notifications/notifications.component.html
All tables that use the control menu need to add three-dot-column to last column (which is the one containing our new control menu).  Some of those were initially missed.  This branch adds those classes where needed.
https://github.com/chef/automate/pull/2283
All control menus are right aligned within their column
make serve
All control menus should now be right aligned within their containing column
> Add three-dot-column class to any columns using control menu

- components/automate-gateway/handler/iam/v2/users/users.go
- components/automate-gateway/handler/users.go
- components/automate-ui/src/app/modules/user/user-details/user-details.component.html
- components/automate-ui/src/app/modules/user/user-details/user-details.component.ts
- components/local-user-service/server/grpc.go
- components/local-user-service/server/grpc_test.go
To prevent problems with API users we have decided to use the word "previous" instead of "old" for the user current password. This is used when a user changes their password. This PR is reverting some of the changes from this PR https://github.com/chef/automate/pull/2652. 
https://github.com/chef/automate/pull/2652
* The API reverts back to using the error message of "previous password does not match". 
* The user's profile page is changed to have the "Previous Password" label instead of "Old Password". 
1. Start the UI and go to https://a2-dev.test/user-details/admin#password
1. Ensure the first text field has the label of "Previous Password". 
1. Update the password with the incorrect previous password and ensure the error message in the banner displays "Could not update user: previous …
> Updating wording from old password to previous password

- components/automate-chef-io/config.toml
This updates the config so that Hugo will generate the automate site using Goldmark instead of Blackfriday. See [here](https://gohugo.io/news/0.60.0-relnotes/) and [here](https://gohugo.io/getting-started/configuration-markup#goldmark) for more info.
All of these are Hugo's defaults except for `style = "emacs"`.
Things to be aware of:
-  `autoHeadingIDType = "github"` could change heading IDs after the version of Hugo is bumped to 0.62 which could break links. See **autoHeadingIDType** below [here](https://gohugo.io/getting-started/configuration-markup#goldmark).
- `unsafe = false` will prevent Goldmark from rendering any HTML elements inside markdown pages. As far as I can tell there aren't any so it shouldn't be a problem.
`make serve`
> Update config on automate-chef-io for Hugo 0.61 and Goldmark

- components/automate-ui/src/app/pages/service-groups/service-groups.component.html
The message that appears when a user visits the applications tab but has no applications data is updated to link to the getting started documentation for the apps tab.
#2677 
Build automate-ui, start all services and then visit the apps tab. The link is not expected to work until the next time we promote acceptance to current. Chef Software employees can view the acceptance version of the page over VPN at https://a2-docs-acceptance.cd.chef.co/docs/applications-setup/
> Show a docs link when apps tab is empty

- .expeditor/config.yml
We recently made some fixes to the script that generates CLI docs but this did not trigger a rebuild of the CLI docs so the docs content got stale and we had to manually update it.
https://github.com/chef/automate/pull/2683
https://github.com/chef/automate/pull/2632
> Rebuild CLI docs when generator script changes

- components/automate-ui/src/app/components/projects-dropdown/projects-dropdown.component.html
- components/automate-ui/src/app/components/projects-dropdown/projects-dropdown.component.scss
- components/automate-ui/src/app/components/projects-dropdown/projects-dropdown.component.spec.ts
- components/automate-ui/src/app/components/projects-dropdown/projects-dropdown.component.ts
- components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.html
- components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.spec.ts
This branch adds the capability to filter projects in the dropdown list that sits inside Settings > Teams > Details where a user can be assigned projects.
Note: In the interest of time, this branch does not use a redux pattern and should be updated after release.
fixes #1842
A user can click on the project dropdown, and type to filter their projects
To Build:
make serve
To Test:
Navigate to https://a2-dev.test/settings/teams/admins#details
please note, it is necessary to have several projects created
click on the projects dropdown
type in the input to filter the project selection
> adding filtering to project assignment dropdown

- api/config/authz/config_request.go
- authz.toml
- components/authz-service/constants/v2/constants.go
- components/authz-service/server/v2/project_test.go
- components/authz-service/server/v2/rules_property_test.go
- components/authz-service/storage/v2/memstore/memstore.go
- components/authz-service/testhelpers/testhelpers.go
- components/automate-chef-io/content/docs/iam-v2-guide.md
- components/automate-chef-io/content/docs/iam-v2-overview.md
- integration/tests/cypress_e2e.sh
- scripts/auth_collections.sh
- terraform/test-environments/modules/chef_automate_install/main.tf
With the IAM release, we are now supporting up to 300 projects. 
Customers using the default limit of 6 will have their limit automatically increased. Customers who have increased their limit will still have that limit applied.
`cat /hab/svc/authz-service/config/config.yml` will show you the current limit of 6
`rebuild components/automate-deployment
rebuild components/authz-service`
`cat /hab/svc/authz-service/config/config.yml` will show you the new limit of 300
Try creating 301 projects-- you should get an error on the 301st.
per @msorens on quick project creation:
> 
> You can easily generate (or remove) hundreds of projects from the command-line with these commands:
> 
> ### Generate 500 starting with id 101
> authGen projects create 500 …
> Increase project limit default to 300

- api/interservice/deployment/override_config.go
- api/interservice/deployment/override_config_test.go
- integration/tests/ha_data_services_migrate.sh
It seems to have broken in #2344
Basically, in most cases, the code ends up discarding the requested
patch config because it returns early. The only case when this doesn't
happen is if you're doing backups to S3
> Fix broken patch config during restore

- api/external/applications/applications.pb.go
- api/external/applications/applications.proto
- api/external/applications/applications.swagger.json
- components/automate-gateway/api/applications.pb.swagger.go
The `filters` fields in the Applications API are free-form text at the protobuf level but then are validated like an enum inside the applications service. We need to tell users what the valid values are and what they mean so they can use the API without having to reverse engineer it from the browser.
#2635
#2622
> Document Apps API filter parameters

- components/automate-ui/src/app/modules/user/user-table/user-table.component.html
- components/automate-ui/src/app/modules/user/user-table/user-table.component.ts
Upon removing a user, we were getting two notifications in the UI:
This is due to the fact that the actual delete operation was dispatched twice, not that the response was posted twice.
Technical details:
The problem here with "onSelectionChange" is that when you select a new option, it both selects the new option and then deselects the old one. So you get one event with the new option and a second event with the old option.
The fix: Check for the new option selection only, the one with `isUserInput` being true.
Reference: https://github.com/angular/components/issues/4094
Only one dispatch, and thus one notification in the UI.
Navigate to Users
Using the control menu for any user in the list, select <kbd>Remove User</kbd>.
> Two notifications received when removing a user from a team

- components/license-control-service/pkg/server/server.go
Wanted to change this error message when applying an expired license--notice the reported date on the last line:
```
root@a2-iamv2p1-local-fresh-install-acceptance:~# chef-automate license apply temp.txt 
Reading token data from file: temp.txt
DeploymentServiceCallError: A request to the deployment-service failed:
Request to apply license failed: rpc error: code = InvalidArgument
desc = Rejecting license ID 9121bf7b-c10b-47db-aa65-faba6bc126b8,
expired at seconds:1525219199 ; set force=true to override
```
to this:
```
root@a2-iamv2p1-local-fresh-install-acceptance:~# chef-automate license apply temp.txt 
Reading token data from file: temp.txt
DeploymentServiceCallError: A request to the deployment-service failed:
Request to apply license failed: rpc error: code = InvalidArgument
desc = …
```
> Make date user-friendly in licensing error message

- components/automate-workflow-ctl/habitat/plan.sh
- components/automate-workflow-server/habitat/plan.sh
Pin ruby debs to a version that avoids LGPL dep.
Workaround (but not a fix!) for #2733
License scout passes.
watch Ci
> Pin ruby to avoid LGPL dep for now

- .expeditor/verify.pipeline.yml
- components/compliance-service/Makefile
- scripts/install_inspec_master.sh
In order to have better awareness of breaking changes in the integration of automate and inspec, this PR adds a buildkite task to build the latest inspec from master and use that to run the inspec focused tests.
> Run compliance scanner tests against inspec master

- components/automate-ui/src/app/pages/notification-form/notification-form.component.ts
- components/automate-ui/src/app/pages/notifications/notifications.component.ts
- components/automate-ui/src/app/pages/notifications/rule.ts
- components/data-feed-service/service/data-feed-aggregate-task.go
- components/data-feed-service/service/data-feed-service.go
The 'Assets' notification type was to support the early development of the datafeed service. Notifications are no longer needed for the datafeed service and the Assets type is no longer relevant.
This PR removes the Assets type from the dropdown on the UI, reverting back to the previous notifications functionality.
> Remove references to Asset from ServiceNow notifications UI

- components/automate-ui/src/app/components/settings-sidebar/settings-sidebar.component.html
- components/automate-ui/src/app/entities/layout/layout-sidebar.service.ts
- components/automate-ui/src/app/pages/data-feed/data-feed.component.html
The new data feed page needs to be updated to be consistent with the rest of Automate.
**Design Details**: 
**Empty state**
- change data feeds left-nav icon to assignment
- change h1 to Data Feeds
- change empty message to Create a data feed to get started!
- change the primary button to Create Data Feed
- change only column header to Name
fixes #2745
I have added some UI changes for the data feeds page.
youll need to turn on the service now CMDB feature flag to see the left nav item, type `feat` anywhere in the ui
> Data feeds page UI changes - general with empty state

- components/automate-ui/src/app/modules/user/user-details/user-details.component.html
- components/automate-ui/src/app/modules/user/user-details/user-details.component.ts
- components/automate-ui/src/app/page-components/create-user-modal/create-user-modal.component.html
- components/automate-ui/src/app/page-components/create-user-modal/create-user-modal.component.ts
- e2e/cypress/integration/ui/settings/user_mgmt.spec.ts
Fixes when the `password must match` error shows up
branched off: https://github.com/chef/automate/pull/2704 (merged and rebased)
on both the user create modal and user details page:
Create User Modal
1. Sign in as admin
2. Navigate to Settings > Users
3. Use the Create User button
4. Enter a password, and a matching password in the confirm password box
5. Now go back to the first password box and add/delete a letter
6. Keep changing the password and confirm password fields until they match and the save button is enabled
User Details/User Profile Page
1. Click on a user to view their details page and click on the Reset Pasword tab (or click on the Profile link in the top right)
2. Enter in a password
3. Enter the identical password with one extra character on the end
4. You will see the …
> [automate-1523] fix password match error

- components/automate-chef-io/content/docs/airgapped-installation.md
Recently, in an [internal slack convo](https://chefio.slack.com/archives/CARK1CBNX/p1579826191009200) it came up that the wording in the license information for an air-gapped install was a bit confusing, and that it might be helpful to include a contact link. This pr addresses these things.
> added contact link to airgapped install docs

- .expeditor/publish-release-notes.sh
We are about to make iam v2 generally available so we no longer need the beta section.
> removing beta section from release notes template

- components/automate-cs-nginx/habitat/config/chef_https.conf
When automate is used to deploy chef-server, its possible to configure
an automate data collector endpoint for it to talk to. This change
allows you to configure the proxy_ssl_verify_depth for such cases.
Fixes #2243
> Make proxy_ssl_verify_depth configurable for external autoamte

- components/automate-ui/src/app/modules/team/team-add-users/team-add-users.component.html
Fixes a tiny issue I noticed while acceptance testing. As a project owner, I'm allowed to add users to teams in my project. However, I can't create users. On the team-add-users modal, once all users are added to a team, we show a button to create new users. But as a project owner, I get a 403 error when I try to create a user because I don't have permission to.
This PR adds an app-authorized guard to the `Create User` buttons on the team-add-users modal so a project owner (or any user without create user permissions) can't see them.
It also slightly changes the message the non-permissioned user will see.
- start Automate + UI
- create a project
- add some user to the auto-generated `<project name> Project Owners` policy
- create a team inside that project
- log in as the project-owner …
> team-add-users: add app-authorized guards

- .expeditor/verify_private.pipeline.yml
- api/config/elasticsearch/config_request.go
- api/config/es_sidecar/config_request.go
- api/config/es_sidecar/config_request_test.go
- integration/base.sh
- integration/helpers/s3.sh
- integration/helpers/setup.sh
- integration/run_test
- integration/tests/backup_external_es_s3.sh
- integration/tests/backup_s3.sh
* Add new external es with s3 integration test
* Rewrite SetGlobalConfig() for the es-sidecar-service
* Add unit tests for the various external, global and es-sidecar level
configuration combinations
* Extract common s3 integration test functions into helpers
* Update the external Es to 6.8.3 to match what is currently deployed
* Add and configure repository-s3 for external es integration tests
Fixes #2520
> [automate-2520] support S3 snapshots when using external elasticsearch

- components/automate-ui/src/app/entities/projects/project.effects.spec.ts
- components/automate-ui/src/app/entities/projects/project.effects.ts
Adding a new action to the project delete effect to refresh the global filter. 
https://github.com/chef/automate/issues/1756
Global project filter updates immediately upon adding and deleting projects.
1. Start the UI. 
1. Create a project
1. Ensure the new project is in the global filter
1. Delete the project
1. Ensure the project is removed from the global filter.
> Global filter refresh on project delete

- components/automate-ui/src/app/components/table/table-body/table-body.component.scss
- components/automate-ui/src/app/components/table/table-body/table-body.component.ts
- components/automate-ui/src/app/components/table/table-cell/table-cell.component.scss
- components/automate-ui/src/app/components/table/table-header-cell/table-header-cell.component.scss
- components/automate-ui/src/app/components/table/table-header/table-header.component.scss
- components/automate-ui/src/app/components/table/table-header/table-header.component.ts
- components/automate-ui/src/app/components/table/table-row/table-row.component.scss
- components/automate-ui/src/app/components/table/table.component.scss
- components/automate-ui/src/app/modules/token/token-list/api-token-list.component.scss
- components/automate-ui/src/app/pages/+compliance/+profile/+profile-overview/profile-overview.component.scss
- components/automate-ui/src/app/pages/project/details/project-details.component.html
- components/automate-ui/src/app/pages/project/details/project-details.component.scss
Recently, we started using a new table component on the auth tables. The styles on this new table used border-spacing which is pretty inflexible and caused an additional 8px to be added to the top of the table. To address this, I changed the component to use flex instead.
I also considered removing the bottom margin from the buttons in the toolbar but since this new table component has not replaced all tables yet that would cause the pages with the chef ui library table component to have zero space between the toolbar buttons and the table.
#2717
tables and toolbar buttons are 8px away from each other
rebuild components/automate-ui-devproxy
> changing angular table component to use flex

- components/automate-ui/src/app/modules/license/license-apply/license-apply.component.spec.ts
- components/automate-ui/src/app/modules/license/license-apply/license-apply.component.ts
- components/automate-ui/src/app/modules/license/license-lockout/license-lockout.component.spec.ts
- components/automate-ui/src/app/modules/license/license-lockout/license-lockout.component.ts
Whether getting a new trial license (in which case a license notification banner should appear) or applying a full license (in which case the banner should disappear), that banner change should occur immediately, not at the next polling interval.
fixes #1509
I have added some changes to reflect the license notification banner immediately. 
> Applying license should immediately be reflected in license notification banner

- components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.html
- components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.ts
- components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.spec.ts
The Global Projects Dropdown filter was built using a two way binding, ngModel pattern, however we would prefer to not use ngModel.  This branch removes the use of ngModel.
https://github.com/chef/automate/pull/2671
ngModel is gone from the global project dropdown
To build:
2. make serve
To test:
1. if you do not have projects, go to https://a2-dev.test/settings/projects and create several projects
2. Click on the top right dropdown that will read something like "All Projects"
3.  In the dropdown, type some letters and watch your projects filter.
> Remove ngmodel without ngrx

- terraform/test-environments/modules/chef_load_instance/main.tf
- terraform/test-environments/modules/chef_load_instance/templates/applications_load_gen.toml.tpl
- terraform/test-environments/modules/chef_load_instance/variables.tf
In https://github.com/chef/automate/pull/2776 we created the applications-load-gen service. Now we want to run it against the automate instances in the pipeline. The primary goal is to make the acceptance environments useful for UI testing/demonstration but having a baseline load test will be welcome also.
> Add applications load generation to chef-load machines

- terraform/test-environments/modules/chef_load_instance/main.tf
Fix mistake in terraform to setup applications load generator
> Fix typos in apps load gen for pipeline

- terraform/test-environments/modules/chef_load_instance/main.tf
- terraform/test-environments/modules/chef_load_instance/templates/hab-sup-exec-start.conf.tpl
Adds end-to-end coverage of real habitat supervisor connecting to Automate applications feature.
> Connect chef-load hab sup to automate EAS apps

- terraform/test-environments/modules/chef_load_instance/main.tf
Copied the wrong file when setting up systemd overrides
> copy correct file in chef load setup

- terraform/test-environments/modules/chef_load_instance/variables.tf
20k services plus compliance and infra is too much for the dev perf test machines
> Reduce base load for applications service

- terraform/test-environments/modules/chef_load_instance/main.tf
At some point in the past, habitat service load/unload commands became async, which means that an unload followed by a load can fail if the unload isn't finished in time. Add a poll for the unload so we don't try to load until it's safe.
> Poll to check for unload to finish when reloading services

- components/automate-chef-io/content/docs/configuration.md
- components/automate-chef-io/content/docs/migrate.md
- components/automate-chef-io/content/docs/upgrade.md
When a user provides a config file to Automate during deployment, they must specify any proxy settings needed within that config file. `chef-automate deploy config.toml` will *not* respect proxy environment variables.
Fixes #2688.
> Clarify when Automate respects proxy environment variables.

- terraform/test-environments/modules/chef_load_instance/main.tf
terraform: If a hab upgrade doesn't complete all the way we can end up with newer hab but without having accepted the license. Add the license accepting env VAR in more places to catch this case.
> Add more defensive hab license accepting

- components/automate-ui/src/app/components/notifications/notifications.component.ts
Small fix for notifications logic on displaying license banner.
https://app.zenhub.com/workspaces/ui-team-5cba23a3b14fdc05970c8f87/issues/chef/automate/835
License banner only shows when there's a license notification
hab studio enter 
export DEVPROXY_URL=localhost
start_automate_ui_background |  stop_automate_ui_background
chef-automate dev psql chef_license_control_service -- -c "UPDATE licenses SET active=NULL"
> Fix notifications license display logic

- .license_scout.yml
- components/automate-workflow-ctl/habitat/plan.sh
- components/automate-workflow-server/habitat/plan.sh
The core/ruby package depends on nss-myhostname at runtime. This library is LGPL 2.1+ and fails license scout checks. This patch adds an exception for the library. DO NOT MERGE unless/until approved by legal.
The library in question is described in it's documentation this way:
> nss-myhostname is a plugin for the GNU Name Service Switch (NSS)
> functionality of the GNU C Library (glibc) providing host name
> resolution for the locally configured system hostname as returned by
> gethostname(2).
Therefore the "work that uses the library" (which is subject to LGPL requirements) in this case is glibc, which is already packaged with Automate and excepted by legal.
* https://github.com/chef/automate/issues/2733
* https://github.com/chef/automate/pull/2734
* …
> Request legal exception for LGPL nss-myhostname

- components/automate-ui/src/main.ts
With an update to Chrome version 80, we started getting browser console errors on many pages with modals--here is just one example from the Users list page:
```
CreateUserModalComponent.html:4 ERROR Error: Cannot find control with name: 'displayName'
at _throwError (forms.js:3357)
at setUpControl (forms.js:3181)
at FormGroupDirective.addControl (forms.js:7345)
at FormControlName._setUpControl (forms.js:8070)
at FormControlName.ngOnChanges (forms.js:7993)
at checkAndUpdateDirectiveInline (core.js:31906)
at checkAndUpdateNodeInline (core.js:44367)
at checkAndUpdateNode (core.js:44306)
at debugCheckAndUpdateNode (core.js:45328)
at debugCheckDirectivesFn (core.js:45271)
CreateUserModalComponent.html:9 ERROR TypeError: Cannot read property 'pipe' of null
at FormControlDirective.ngOnInit …
```
> [Automate-2823] chrome 80 workaround

- components/ingest-service/pipeline/chef_run.go
- components/ingest-service/pipeline/processor/corrections_run.go
- components/ingest-service/pipeline/processor/transmogrify_run.go
- components/ingest-service/pipeline/processor/validator_run.go
- components/ingest-service/pipeline/processor/validator_run_internal_test.go
Validating the CCR message at the beginning of the ingestion pipeline. Users were seeing that if the CCR was missing the "entity_uuid" it could fail other CCR requests from successfully ingesting because of the bundling of messages. 
https://github.com/chef/automate/issues/2309
Fail a CCR request that is missing a value for "entity_uuid" before bundling the message with other requests. 
1. `build components/ingest-service && start_all_services`
1. Add debug level logging to the ingest service `chef-automate debug set-log-level ingest-service debug`
1. Follow the logs with `sl | grep "ingest-service.default" | grep -v "Worker" &`
1. Open the components/ingest-service/examples/converge-success-report.json file and remove the "entity_uuid" field.
1. Send the CCR to the data collector. `curl …
> Adding run message validation to the ingest pipeline

- components/automate-chef-io/layouts/_default/data-api.html
To fix problems with the API docs not behaving properly with Chrome 80 we need to track the latest release of redoc. The problem is described in #2828.
We were already attempting to track the latest release but for some reason were one behind so this is not really a change in the desired behavior. We should probably be more explicit about the version of redoc used but that is another discussion.
> Track latest redoc release in API docs

- components/compliance-service/api/profiles/server/migrate.go
- components/compliance-service/profiles/market/market.go
Fix for #2615. 
Steps to reproduce:
* Download the bad profile into the `automate/` directory so it is visible in the studio.
* Enter the hab studio.
* Make the legacy profile store directory: `[8][default:/src:130]# mkdir -p /hab/svc/compliance-service/data/profiles/admin`
* Copy the bad profile into the profile store: `[8][default:/src:130]# cp crashing_profile-0.1.0.tar.gz /hab/svc/compliance-service/data/profiles/admin/`
* Start automate and view the logs.
Before this PR, the logs looked like this:
```
[2020-02-07T21:24:06+00:00] compliance-service.default(O): time="2020-02-07T21:24:06Z" level=info msg="Migrations running (4/41) Profiles: Migrating profiles from disk, if any..."
[2020-02-07T21:24:06+00:00] compliance-service.default(O): time="2020-02-07T21:24:06Z" level=info …
```
> Fix for incompatible profiles breaking A1 to A2 migration

- components/authz-service/server/v2/system.go
- components/automate-ui/src/app/entities/layout/layout.facade.ts
Just treating v1 as a problem; V2 behavior is sufficient as is--without this commit, to wit:
viewer, editor, or better will not see an error, and will see projects status banner
user with no permissions will see an error--but that's OK. It is not a real use case (at most, a user is just in the process of being set up)
Initially, this surfaced as a v1 issue but it turns out it affects both v1 and v2, though differently.
_Actual (prior to this PR):_
Only admin users (or users explicitly given permission) could access `ListProjects`; other users would see an error banner.
_Desired (with this PR):_
All users need to see the projects status bar when projects are not up to date (though only folks with permission to update should see the <kbd>update projects</kbd> and <kbd>stop update</kbd> …
> Correcting disposition of ListProjects for IAM v1

- components/applications-service/habitat/default.toml
- components/applications-service/pkg/config/service.go
- components/applications-service/pkg/storage/postgres/db.go
We're seing the applications create and destroy a lot
of db connections in the perf environment. This should
hopefully fix it
> Limit database connections in applications service

- components/applications-service/habitat/plan.sh
This will make it possible for us to debug in the perf test environment.
That environment is showing 7k and growing goroutines, but we cannot
analyze the core dump with debug symbols
> Don't strip applications service binary

- components/automate-cli/pkg/diagnostics/context.go
Some endpoints return various levels of 500 when they're not completely ready. These should all be retryable
> Retry all 5xx in diagnostics

- components/compliance-service/api/tests/25_nodes_spec.rb
- components/compliance-service/api/tests/26_bulk_nodes_spec.rb
- components/compliance-service/api/tests/run.rb
- components/nodemanager-service/pgdb/nodes.go
- components/nodemanager-service/pgdb/nodes_integration_test.go
Fix for #2348.
As far as I can tell, this bug was caused by the [sql query that fetches nodes](https://github.com/chef/automate/blob/master/components/nodemanager-service/pgdb/nodes.go#L40-L76) doing multiple joins and aggregations at once. I initially solved this by changing the query to do each aggregation separately and joining against teh result, but some of the code we use for filtering depends on the query doing the joins how it is currently done, and redoing that did not seem like a great use of time.
Using `DISTINCT` like I did in this PR solves the immediate issue, but from what I've gathered this is sort of a big hammer that only papers over the original problem. Using `DISTINCT` like this has the following downsides:
* The query is bigger and more complicated than it needs to …
> Prevent duplicate data from aggregated data when fetching nodes

- components/automate-ui/src/app/components/pending-edits-bar/pending-edits-bar.component.scss
- components/automate-ui/src/app/components/process-progress-bar/process-progress-bar.component.scss
- components/automate-ui/src/app/entities/layout/layout.facade.ts
- components/automate-ui/src/styles/_colors.scss
- components/automate-ui/src/styles/_variables.scss
- components/chef-ui-library/src/global/variables.css
> project update banner style updates

- components/automate-ui/src/app/components/process-progress-bar/process-progress-bar.component.spec.ts
- components/automate-ui/src/app/components/process-progress-bar/process-progress-bar.component.ts
- components/automate-ui/src/app/entities/projects/project.reducer.ts
We were displaying a fractional percentage, this fixes it.
The percentage format that is displayed in stop modal matches the one displayed in the banner.
- `rebuild components/automate-ui-devproxy`
- load 500 nodes with either `chef_load_nodes 500` or `chef_load_compliance_nodes 500`
- create a project
- add an ingest rule to it, it doesnt matter the content of the ingest rule
- run a project update
- note: if you only ever see 0% or 100% youll need to add more nodes
> fix project update progress percentage

- components/automate-ui/src/app/page-components/navbar/navbar.component.html
We need to remove the Applications link from navigation when the user does not have permissions to see the applications tab.  This branch adds an app authorized container around Applications using introspection to check if the user has permission or not.
When a user does not have permission to use the Applications tab, it is not accessible
make serve
In order to test this properly, you'll need to:
1. log in as admin
2. create a new user
3. create a policy that does not allow a user to view applications
4. assign your new user that policy
5. log out of admin
6. log in as the user you created.
If you're testing this, please let me know if you see the applications tab when you expect not to. - thank you!
> Add app-authorized to applications nav link

- components/automate-chef-io/layouts/_default/data-api.html
The API docs are on an outside site and getting back to docs was a pretty bad experience. I added a "return to docs" button on the API page. 
There are limitations to styling the API pages. Even so, this button could be prettier. 
https://github.com/chef/automate/pull/2890
Checkout this branch
Build the API docs by running the following all-in-one command from the top-level automate directory:
```
hab studio run "source .studiorc && compile_all_protobuf_components" && pushd components/automate-chef-io/ && make sync_swagger_files generate_swagger && make serve || popd
```
Review the API docs in your browser:
http://localhost:1313/docs/api
> Add button for back to docs

- components/automate-ui/src/app/entities/api-tokens/api-token.reducer.ts
- components/automate-ui/src/app/entities/orgs/org.reducer.ts
- components/automate-ui/src/app/entities/policies/policy.reducer.ts
- components/automate-ui/src/app/entities/projects/project.reducer.ts
- components/automate-ui/src/app/entities/roles/role.reducer.ts
- components/automate-ui/src/app/entities/rules/rule.reducer.ts
- components/automate-ui/src/app/entities/servers/server.reducer.ts
- components/automate-ui/src/app/entities/teams/team.reducer.ts
- components/automate-ui/src/app/entities/users/user.reducer.ts
Closely tied to #2703, during that project update--if you were on the projects list page, notice that the background behind the spinner shows there are no projects.
(Weird! Unable to load the image here.)
That is due to the list of projects being erased at the start of the project fetch that is coincident with a Project Update.
That list should not have actually been erased--we may have been a bit over-eager in state clearing in a couple
earlier PRs, notably https://github.com/chef/automate/pull/2158.
I think it still makes sense for individual "get" calls to do some state clearning,
but "get all" does not need it; when the result is returned and
added to the state with an `addAll` call, that completely replaces
the section of state at hand.
Reference: …
> [automate-2904] Remove state-clearing upon initiating "get all"

- components/automate-ui/src/app/components/pending-edits-bar/pending-edits-bar.component.html
- components/automate-ui/src/app/components/pending-edits-bar/pending-edits-bar.component.spec.ts
- components/automate-ui/src/app/components/pending-edits-bar/pending-edits-bar.component.ts
- components/automate-ui/src/app/entities/layout/layout.facade.ts
Images are still broken in github (along with some other github issues): This is a picture showing both the pending edits bar and the project update progress bar. It should only ever show one, so when the project update progress bar is present the pending edits bar should not be.
NA
When there are pending edits, the pending edits bar will appear.
An admin or other designated user will then at some point begin a project update,
causing the project update progress bar to appear and the pending edits bar to disappear.
While that is running, users are free to make further project changes that will be pending for the next cycle.
However, while the project update progress bar is active, the pending edits bar will stay hidden.
As soon as the project update completes, the pending edits bar will …
> [Automate-2889] Suppress pending banner if progress banner active

- dev-docs/ui-development.md
Today in ui team meeting it was mentioned that this wasn't documented yet, so adding details around signing in as a `editor` or `viewer`.
> adding more sign in details to dev docs

- components/automate-deployment/pkg/a1upgrade/a1upgrade_compat.go
- components/automate-deployment/pkg/preflight/checks.go
habitat is now fetched from packages.chef.io in most cases
Testing for bintray now exposes us to false positives in the preflight checker.
> Remove bintray from preflight checks

- components/automate-ui/src/app/components/notifications/notifications.component.html
- components/automate-ui/src/app/entities/notifications/notification.model.ts
Noticed some redundancy while investigating a related issue.
Info and error notifications still work the same way (directly affected by this change).
License notifications still work the same way (not affected by this change)
Logged in as admin, create a new user, e.g.. "bob".
Upon successful creation you should see a "created user" message lasting for 8 seconds.
Logout and login as "bob".
Attempt to visit the policies page via URL (https://a2-dev.test/settings/policies). You should see an error lasting for 30 seconds:
> Streamline notifications (cosmetic)

- components/automate-chef-io/.gitignore
- components/automate-chef-io/Makefile
- components/automate-chef-io/habitat/plan.sh
- components/automate-chef-io/layouts/_default/data-api.html
Fix for #2855.
I had originally planned to use [redoc-cli](https://github.com/Redocly/redoc/blob/master/cli/README.md) to package the docs, but that had a few downsides:
* The combined HTML + js file didn't work with hugo the way we're doing things currently, and I don't understand hugo enough to rework things to get this to work.
* This would have added npm to the docs development process and package building, which seems a bit onerous.
* While trying to get this going there was work done that would have conflicted and needed to be redone (#2902).
* Some other smaller concerns that can basically be summed up as redoc-cli doesn't do much to justify depending on it.
This still relies on the CDN, but would move potential failures to package build time rather than when a customer views the …
> Fetch ReDoc js file when building hab package rather than rely on CDN.

- components/automate-ui/src/app/components/confirm-apply-stop-modal/confirm-apply-stop-modal.component.html
- components/automate-ui/src/app/components/confirm-apply-stop-modal/confirm-apply-stop-modal.component.spec.ts
- components/automate-ui/src/app/components/confirm-apply-stop-modal/confirm-apply-stop-modal.component.ts
Changes from PR #2891 caused a couple rendering issues:
This PR remedies those: key points are indicated.
PR #2891 fix project update progress percentage
1. Stop Update bar characteristics match progress update banner
2. Percentages are shown in whole numbers
3. Bar coloration reflects percentages
(rebuild automate-ui if needed; should be automatic)
- load lots of nodes, e.g. `chef_load_nodes 500` or `chef_load_compliance_nodes 500`
- create one or more projects
- create one or more rules
- run a project update
- note: if you only ever see 0% or 100% try again or add more nodes!
> Progress bar fix

- scripts/install_inspec_master.sh
This is to address the following error:
```
Gem::RuntimeRequirementNotMetError: chef-zero requires Ruby version >= 2.6. The
current ruby version is 2.5.0.
An error occurred while installing chef-zero (15.0.0), and Bundler
cannot continue.
Make sure that `gem install chef-zero -v '15.0.0' --source
'https://rubygems.org/'` succeeds before bundling.
In Gemfile:
berkshelf was resolved to 7.0.9, which depends on
chef was resolved to 14.14.29, which depends on
chef-zero
```
We might also consider not installing all of the bundle groups in
these tests.
> ci: use ruby26 in inspec-from-master tests

- .studio/common
Occasionally we hit problems with mockgen either caused by an outdated
mockgen binary in the go binary cache or other problems. Often, these
problems are made more confusing by the fact that the failure does not
halt the generation process.
> studio: fail immediately if mockgen fails

- .expeditor/verify.pipeline.yml
This test is an `soft_fail: true` test so I missed that this was
failing during my last PR.
Hopefully this gets us passing again.
> ci: more fallout of moving to ruby26

- .studio/deployment-service
- .studio/golang
- .studio/tooling
- .studiorc
The binaries we build and put in /src/bin are typically dependent on
the state of our vendored modules. This sets up GOBIN to be based on
the hash of `vendor/modules.txt` to help ensure we don't see errors
caused by old binaries.
We don't clean up the old bin directories by default, but we do warn
devs as they enter the studio.
> studio: use vendor-state specific directory for GOBIN

- components/automate-chef-io/content/docs/data-lifecycle.md
- components/automate-chef-io/content/docs/node-lifecycle.md
Today in the feedback session @teknofire mentioned that he had some customers struggle to find the retention related documentation using search. This attempts to add the word `retention` to both related docs pages so they are easier to find.
> add retention to make searching the docs easier

- components/automate-chef-io/content/docs/migrate.md
Note that A2 cannot function as an A2 SAML proxy for Chef Manage
Signed-off-by: Sean Horn <sean_horn@chef.io>
> Chef Manage A2 SAML auth caveat

- components/event-gateway/integration_test/nats_auth_test.go
- components/event-gateway/integration_test/suite_test.go
Event gateway now green:
https://buildkite.com/chef/chef-automate-master-verify-private/builds/9622#8b9e70e0-b2d8-4705-aef9-186c32e33c98
```
rebuild components/authz-service/ && rebuild components/automate-gateway/ && rebuild components/automate-cli/
event_gateway_integration
```
> [automate-2930] Fix NATS gateway test errors related to v2 force upgrade

- dev-docs/DEV_ENVIRONMENT.md
- dev-docs/ui-development.md
Recently, added this to the ui dev docs, but noticed that this page mentions signing in as well so adding details for how to sign in as viewer or editor.
> adding viewer and editor to sign in docs 

- components/authz-service/storage/postgres/migration/migration.go
- components/authz-service/storage/v1/postgres/postgres.go
- components/authz-service/storage/v2/postgres/postgres.go
Additional logging could prove useful in the event of
(a) customer issues once the force upgrade is released, and 
(b) helping us to make sure it is working as expected before release
PR #2793 Forced migration upgrade
Supervisor log shows something like the output below.
Got rid of the "bracketing" notion; not enough value added.
```
"applying database migrations from /hab/pkgs/msorens/authz-service/0.1.0/20200224202924/migrations"
"Initializing DB migrations..."
"Current schema version: 73"
"Migrating schema from version 73 to 74"
"Setting up IAM data basics..."
"Checking for data migrations..."
"Checking for remaining schema migrations..."
"DB initialization complete at version 74"
```
Notice that the logging is instrumented as brackets. The "open bracket" has the form `x...` and the …
> Add some logging around forced migration

- .studio/infra-proxy-service
- dev-docs/adding-data/adding_test_data.md
- Infra views feature has been added recently, so it would nice to populate sample data.
- Add hab studio script to populate the dummy data for the infra servers & orgs.
- In order to fetch dummy data for the cookbooks, roles, etc required mocking which we will decide further.
[MSYS-1251](https://chefio.atlassian.net/browse/MSYS-1251)
Ease to add sample data for the infra views testing.
- From hab studio `source .studio/infra-proxy-service` file to load the script.
-  Start `infra-proxy-service` service by running `start_infra_proxy_service` or `start_all_services`
- Hit `infra_service_load_sample_data` will populate 50 records by default.
- For more detail ref `dev-docs/adding-data/adding_test_data.md`
> instructions for adding sample data to the infra views

- .bldr.toml
- components/authn-service/server/server.go
- components/authn-service/server/server_test.go
This PR switches the authn-service to use a teams V2 client instead of a teams V1 client.
NA
Everything still works
rebuild components/authn-service/
> [automate-2861] Update authn service to teams v2 client

- components/config-mgmt-service/grpcserver/node_export.go
- components/config-mgmt-service/integration_test/node_export_test.go
Fix for https://github.com/chef/customer-bugs/issues/70.
The problem with the exported JSON was that each page of results from elasticsearch was being streamed as a fully formed document. The go stdlib's json streaming parser is apparently lenient enough to interpret this as one big collection of objects, but the document parser is not. the solution ended up being changing the existing integration test to be more strict in the output allowed, then adding `[`, `]`, and `,` in the appropriate places to create one big document.
> Fix client-runs export breaking on page barrier

- go.sum
- scripts/repo_health.sh
The go.sum change was produced by running
go mod tidy -v
from the root of the repo. To try to avoid letting this drift in the
future, we now also run go mod tidy in our repo_health script.
> go.sum: go mod tidy

- components/authz-service/README.md
`generate_supertoken` used earlier in order to generate admin token for dev env, which was replaced with `get_admin_token` but still we have documented in authz-service README.md need to updated.
NA
NA
Signed-off-by: Vivek Singh <vsingh@chef.io>
> [authz-service] update get_admin_token in README.md

- components/automate-chef-io/content/docs/applications-dashboard.md
The routing for Automate is a bit confusing, but these two endpoints
are only available at `/api/v1` or `/api/v0`. Not `/apis`.
> docs: correct URL in example curl commands

- components/automate-chef-io/content/docs/on-prem-builder.md
With the completion of incremental backup and restore, on-prem Bldr is
mature to roll out to customers and support at a GA level. This commit
removes the pre-production / active development warnings from the
documentation.
> On-Prem Bldr Docs: remove in-development warnings

- components/automate-ui/src/app/entities/layout/layout.facade.ts
The line removed in this change was fetching the projects for a user
before checking if the install was on IAMv1 or v2. Projects are not
a concept in IAMv1 and we were displaying an error if you logged in as
a non-admin user.
To test: sign in as a *non* admin user.
Fixes: #3004
> automate-ui: don't fetch projects on iamv1

- components/automate-ui/src/app/entities/layout/layout-sidebar.service.ts
chef servers is missing from left nav of infrastructure.
https://github.com/chef/automate/issues/3021
chef servers is showing from left nav of infrastructure.
sign in with admin/chefautomate
navigate to infrastructure
turn on feature flag for chef servers by typing feat
refresh page
notice that there is no chef servers left nav item
> getFeatureStatus for server

- components/automate-ui/src/app/page-components/run-summary/run-summary.component.scss
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.scss
Text content with long continuous characters like guids and such were causing columns to grow wider than intended by the flex layout settings.
Before
After
> Ensure content within info columns wrap w/ the column width

- components/automate-ui/src/app/entities/layout/layout-sidebar.service.ts
- components/automate-ui/src/app/pages/+compliance/+scanner/containers/jobs-list/jobs-list.component.html
- components/automate-ui/src/app/pages/job-list/job-list.component.html
A user having the Viewer role should be able to access the scan jobs page.
Previously, an admin user would see the screen below, specifically both the "Scan Jobs" entry in the left navigation bar, and the <kbd>Create new Job</kbd> button.
But if you logged in as the default `viewer` the left navigation entry was not showing due to an incorrect authorization guard around that entry, fixed in this PR. That authorization guard has not been removed though; it has been tightened up, so it is now around the <kbd>Create new Job</kbd> button itself, yielding this for the `viewer` user (observe the left nav entry is present but the row with the button is gone):
Behind the scenes, though, here is the proof that the guard is in place. Using the Web Developer Tools in Chrome, notice that when I …
> [Automate-2960] Adjust scan jobs permissions

- .expeditor/build.habitat.yml
- .expeditor/verify_private.pipeline.yml
Previous `accounts: github` worked because of a configuration file
that was on disk in our CI environment. This configuration file was
removed, leading to the following error when our CI tooling attempts
to place the requested secret in the environment:
```
panic: no account name provided, and no default account set for github
goroutine 1 [running]:
github.com/chef/ci-studio-common/lib.Check(...)
/Users/tom/code/chef/ci-studio-common/lib/utils.go:11
github.com/chef/ci-studio-common/vault-util/cmd.fetchSecret(0xc000136510, 0xc0001364e0, 0xc00012fd00)
/Users/tom/code/chef/ci-studio-common/vault-util/cmd/fetch-secret-env.go:87 +0x3c2
github.com/chef/ci-studio-common/vault-util/cmd.printSecrets(0xdaf460, 0xdd5700, 0x0, 0x0)
/Users/tom/code/chef/ci-studio-common/vault-util/cmd/fetch-secret-env. …
```
> ci: use fully qualified account names

- components/authz-service/server/v2/project_update_manager.go
- components/authz-service/server/v2/project_update_manager_test.go
- components/authz-service/server/v2/testdata/running_workflow_01/params.json
- components/authz-service/server/v2/testdata/running_workflow_01/payload.json
- lib/cereal/patterns/chain.go
nodemanager doesn't report an estimated completion, and the ES bits were
waiting until an entire index had been updated. This should now report
as soon as ES has processed at least 1 document.
> Report estimated completion time sooner for project update

- components/automate-elasticsearch/habitat/hooks/init
- components/automate-elasticsearch/habitat/hooks/run
Remove the post-run sentinel file in init before the service is started.
This fixes a race where the post-run hook could touch the sentinel
before the run hook could delete it.
Fixes: https://buildkite.com/chef/chef-automate-master-nightly/builds/365#5c0180b9-8a97-4a14-8be9-77d304b7d248
>  [elasticsearch] remove post-run sentinel in the init hook

- components/automate-ui/src/app/app-routing.module.ts
- components/automate-ui/src/app/app.module.ts
- components/automate-ui/src/app/entities/cookbooks/cookbook.actions.ts
- components/automate-ui/src/app/entities/cookbooks/cookbook.effects.ts
- components/automate-ui/src/app/entities/cookbooks/cookbook.model.ts
- components/automate-ui/src/app/entities/cookbooks/cookbook.reducer.ts
- components/automate-ui/src/app/entities/cookbooks/cookbook.requests.ts
- components/automate-ui/src/app/entities/cookbooks/cookbook.selectors.ts
- components/automate-ui/src/app/entities/layout/layout-sidebar.service.ts
- components/automate-ui/src/app/entities/orgs/org.selectors.ts
- components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.html
- components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.scss
- components/automate-ui/src/app/modules/infra-proxy/chef-servers-list/chef-servers-list.component.scss
- components/automate-ui/src/app/modules/infra-proxy/chef-servers-list/chef-servers-list.component.ts
- components/automate-ui/src/app/modules/infra-proxy/cookbook-list/cookbooks-list.component.html
- components/automate-ui/src/app/modules/infra-proxy/cookbook-list/cookbooks-list.component.scss
- components/automate-ui/src/app/modules/infra-proxy/cookbook-list/cookbooks-list.component.spec.ts
- components/automate-ui/src/app/modules/infra-proxy/cookbook-list/cookbooks-list.component.ts
- components/automate-ui/src/app/modules/infra-proxy/create-chef-server-modal/create-chef-server-modal.component.html
- components/automate-ui/src/app/modules/infra-proxy/create-chef-server-modal/create-chef-server-modal.component.scss
- components/automate-ui/src/app/modules/infra-proxy/create-org-modal/create-org-modal.component.html
- components/automate-ui/src/app/modules/infra-proxy/infra-proxy.module.ts
- components/automate-ui/src/app/ngrx.effects.ts
- components/automate-ui/src/app/ngrx.reducers.ts
- tools/credscan/credscan.go
Code changes for the introduction of infra proxy cookbook list component in infra proxy module to make automate-ui a single source of truth for chef infra cookbook data here
In this PR following points we have covered:
1. Created cookbook-list component in infra-proxy module to show cookbook list of specific Org
Designed infra proxy cookbook-list UI flows and used Infra-proxy-service
2. Fixed chef-sever left side navbar option issue for non accessible policy 
Refered Wireframes: https://chef.invisionapp.com/share/3JVLVFMASDZ#/screens/401258847 
For feature description refer: #1544
1. Added cookbook-list component in infra proxy module 
2.  Fixed chef-sever left side navbar option issue for non accessible policy 
1. Unable chef server side nav option under …
> automate infra proxy cookbook list UI

- terraform/test-environments/modules/chef_automate_install/main.tf
Several integration instances were recently rebooted to update them to more economical and recent instance sizes. After the reboot, journald started logging to syslog, which doesn't have a max file limit configured so we ran out of disk space before logrotate could purge the old syslog file. There's no reason to forward journald to syslog so we'll disable it.
> [terraform] don't forward journald to syslog

- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.ts
- components/automate-ui/src/app/pages/+compliance/shared/reporting/report-query.service.ts
Currently, when you navigate to a compliance report by clicking on a node's name in the table, the UI specifies a date range limit based on what you selected in the trend graph drop-down. The performance of the query to fetch the report is inversely related to to how wide the date range is, because the report is stored in a date-named index in elasticsearch. Using the date range from the trend graph drop down is silly because we already got a list of compliance reports with dates to populate the "scan history" popover.
This change uses the known timestamp of the report we are fetching to hint the API to the index it should use to fetch the report.
https://github.com/chef/automate/pull/3037
* build automate-ui, start all services
* create sample data going back in time, I used: …
> Optimize time range when fetching a node's compliance report

- components/automate-chef-io/content/docs/backup.md
- tools/credscan/credscan.go
Cover user questions raised around restoring Automate in several scenarios:
1. Restore to a host on which Automate is already installed.
2. Restore to a host with a different FQDN than the one on which the backup was taken.
3. Restore in an airgapped environment.
> Expand restore docs to cover questions raised by users

- .expeditor/deploy.pipeline.yml
- .expeditor/verify_private.pipeline.yml
bumps all cypress bk timeouts to 35 to avoid OOM crashes
> Give cypress flakey tests more time

- components/authz-service/server/v2/project_update_manager_test.go
- components/authz-service/server/v2/testdata/running_workflow_01/payload.json
The `StartTime` and `LastUpdated` in `payload.json` times were just some hard-coded dates grabbed from the perf env. Once those dates passed, the project_update helper `FindSlowestJobStatus` started returning null time and failing the test. 
This fixes the issue by turning `payload.json` into a template and setting `StartTime` and `LastUpdated`, respectively, to the current time and current time + 1 min.
> fix failing project update test

- components/authz-service/server/v2/project.go
- components/authz-service/server/v2/project_update_manager_test.go
- components/authz-service/server/v2/testdata/running_workflow_01/payload.json
- components/automate-ui/src/app/components/pending-edits-bar/pending-edits-bar.component.html
- components/automate-ui/src/app/components/pending-edits-bar/pending-edits-bar.component.scss
- components/automate-ui/src/app/components/pending-edits-bar/pending-edits-bar.component.spec.ts
- components/automate-ui/src/app/components/pending-edits-bar/pending-edits-bar.component.ts
- components/automate-ui/src/app/entities/projects/project.reducer.ts
- components/automate-ui/src/styles/_colors.scss
- components/automate-ui/src/styles/_variables.scss
When a project update fails, we want to make that much more apparent to the user.
This replaces the standard "edits pending" message with an error message (and coloring) that makes it evident to the user.
The illustration shows the two possible states of the pending edits bar, showing both wording and color change, along with the subtle color change of the button itself when hovering or focusing it.
NA
Here is the contract as defined by unit tests. Most of these were already in place. The new tests are after the `-----` divider.
```
update-start-confirmation modal...
when it emits a cancellation, hides the modal
when it emits a confirmation, hides the modal
when it emits a confirmation, the projectService starts the rule updates
pending edits bar...
is hidden if no project has changes
is …
```
> [automate-3030] Enhance edits pending bar to show failure

- api/external/compliance/profiles/profiles.pb.go
- api/external/compliance/profiles/profiles.proto
- api/external/compliance/profiles/profiles.swagger.json
- components/automate-chef-io/data/docs/api-static/03-tags.swagger.json
- components/automate-chef-io/data/docs/api_chef_automate/compliance/profiles/profiles.swagger.json
- components/automate-chef-io/data/docs/api_chef_automate/infra_proxy/infra_proxy.swagger.json
- components/automate-gateway/api/profiles.pb.swagger.go
API docs for the profiles endpoints!
https://github.com/chef/automate/issues/2356
Profiles endpoints documented
**NOTE: this does not currently document the streaming profiles endpoints.** 
pull the branch down
run make serve from components/automate-chef-io
visit localhost:1313/docs/api
look at the docs!
- [n/a] Tests added/updated?
> profiles API docs

- components/compliance-service/ingest/ingestic/project_update.go
- components/ingest-service/backend/elastic/project_update.go
We ran into this case after it was running for days. It seems ES can
tell you a task is complete but not have the result.
> Don't fail project update if ES doesn't give back a response

- components/automate-chef-io/content/docs/client-runs.md
- components/automate-chef-io/content/docs/data-collection.md
- components/automate-chef-io/content/docs/migrate.md
- components/automate-chef-io/content/docs/runners.md
- components/automate-chef-io/content/docs/servicenow-integration-install.md
- components/automate-chef-io/content/docs/workflow_install.md
Fix links to docs.chef.io:
- pages now have pretty urls, so no `.html` suffix
- resource pages are now in the `resources` subdirectory
- replaced one circular link that linked to docs.chef.io and redirected back to automate.chef.io/docs/
- fix a couple links to headings that don't exist
> Update links to docs.chef.io

- .expeditor/buildkite/cypress.sh
- e2e/cypress.json
- e2e/cypress/integration/ui/settings/token_mgmt.spec.ts
- e2e/cypress/integration/ui/settings/user_mgmt.spec.ts
- e2e/package-lock.json
- e2e/package.json
Cypress tests have been failing for a while in the [deploy pipeline](https://buildkite.com/chef/chef-automate-master-deploy-acceptance/builds/82#5a3cf97b-c9ed-4007-9681-8cb83a78dc5c/95-131)
After some digging, I found out we aren't pinning the Cypress version. So the docker image we're running the test on is [installing the latest version (v4.1.0)](https://github.com/chef/release-engineering/blob/master/components/dockerfiles/chefes/releng-base/Dockerfile#L191), but our tests expect v3.1.4.
> upgrade cypress to latest version

- components/automate-ui/src/app/components/pending-edits-bar/pending-edits-bar.component.spec.ts
- components/automate-ui/src/app/components/process-progress-bar/process-progress-bar.component.spec.ts
- components/automate-ui/src/app/entities/layout/layout-sidebar.service.ts
- components/automate-ui/src/app/entities/layout/layout.facade.ts
- components/automate-ui/src/app/entities/policies/policy.selectors.ts
- components/automate-ui/src/app/modules/token/token-list/api-token-list.component.spec.ts
- components/automate-ui/src/app/pages/+compliance/+profile/+profile-details/profile-details.component.spec.ts
- components/automate-ui/src/app/pages/+compliance/+profile/+profile-overview/profile-overview.component.spec.ts
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.spec.ts
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profile/reporting-profile.component.spec.ts
- components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.spec.ts
- components/automate-ui/src/app/pages/+compliance/+scanner/containers/nodes-add/nodes-add.component.spec.ts
- components/automate-ui/src/app/pages/client-runs/client-runs.component.spec.ts
- components/automate-ui/src/app/pages/data-feed-form/data-feed-form.component.spec.ts
- components/automate-ui/src/app/pages/data-feed/data-feed.component.spec.ts
- components/automate-ui/src/app/pages/integrations/list/integrations-list.component.spec.ts
- components/automate-ui/src/app/pages/node-details/node-details.component.spec.ts
- components/automate-ui/src/app/pages/notification-form/notification-form.component.spec.ts
- components/automate-ui/src/app/pages/project/details/project-details.component.spec.ts
- components/automate-ui/src/app/pages/project/list/project-list.component.spec.ts
- components/automate-ui/src/app/pages/project/rules/project-rules.component.spec.ts
We need the pending edits bar to be present promptly upon page refresh or upon login. Before this fix, it would only start appearing upon visiting selected pages (e.g. project list page), which is any page that did a `GetProjects` call. There was seemingly a call to `GetProjects` in the LayoutFacadeService but therein lies the problem! That call was in an `ngOnInit` function but that `ngOnInit` hook was never being called! That is because LayoutFacadeService is neither a Component nor a Directive (reference: Reference: https://angular.io/guide/lifecycle-hooks). Moving that to the constructor made the code actually run, resolving the issue.
The `noOnDestroy` hook code was never used either, for the same reason, so that is removed here as well.
Finally, the very same things were true of the …
> [automate-3031] Show pending edits bar promptly upon login

- components/automate-ui/src/app/components/process-progress-bar/process-progress-bar.component.ts
- components/automate-ui/src/app/modules/roles/list/roles-list.component.ts
- components/automate-ui/src/app/page-components/event-feed-guitar-strings/event-feed-guitar-strings.component.ts
- components/automate-ui/src/app/page-components/event-feed-table/event-feed-table.component.ts
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.ts
- components/automate-ui/src/app/pages/job-add/job-add.component.ts
- components/automate-ui/src/app/pages/job-edit/job-edit.component.ts
In another issue, I was diagnosing why the pending edits bar was not showing up promptly upon login; rather, it required visiting any among a group of select pages (like project-list) then it would remain persistent.
The root cause turned out to be incorrectly applied lifecycle hooks on a class that did not pay attention to them. That got me thinking about other classes of violations, which led to this PR.
`wwo` (pronounced "wa-wo" and meaning _with-and-with-out_) is the workhorse that finds files containing the first argument but not containing the second argument:
```
wwo() {
rg --files-without-match "$2" $(rg --files-with-matches "$1") 
}
```
The `rg` tool in there is a `grep` alternative that @stevendanna put me on to that really proved its worth here (install on mac with `brew …
> Fixes from auditing Angular lifecycle hooks

- components/automate-ui/src/app/entities/layout/layout-sidebar.service.ts
The teams entry in the left navigation panel had vanished on the `forceUpgrade` branch.
NA
"Teams" is back.
Log in as admin and navigate to Settings.
> Vanished teams on force-upgrade

- components/automate-chef-io/content/docs/data-lifecycle.md
This info would be valuable for the two following scenarios
* Non auto-updating installs
* Airgap installs
In the same vein as these issues
https://github.com/chef/automate/issues/2141
https://github.com/chef/automate/issues/2136
The data retention docs need to be versioned, so that customers can find the old docs to use with old installs.
A completely different set of commands are used for Automate 2
versions < 20191129172405 compared to versions afterward.
These include the status command, the configs for setting retention
length and job schedule, showing the config, and a command to manually run the retention process outside of the schedule using the retention level currently set.
Maybe make a link to the old docs from the new, like this.
Signed-off-by: Sean Horn <sean_horn@chef.io>
> Point to older docs for use with static installs

- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-status/overview-status.component.html
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-status/overview-status.component.scss
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/reporting-overview.component.spec.ts
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/reporting-overview.component.ts
- components/automate-ui/src/styles/_colors.scss
- components/automate-ui/src/styles/_variables.scss
As an Automate User, I will use this work when I want to easily identify any waived nodes or controls in a summary view.
https://github.com/chef/automate/issues/2561
In the compliance reporting overview tab:
A user can see the node count of waived nodes
A user can see the history of nodes that have been waived
A user can see the count of controls that have been waived
A user can see the history of controls that have been waived
load data by using the load_compliance_reports command from your studio dev env
> Automate-2561 Waivers

- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profiles/reporting-profiles.component.html
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profiles/reporting-profiles.component.scss
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profiles/reporting-profiles.component.spec.ts
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profiles/reporting-profiles.component.ts
- components/automate-ui/src/styles.scss
As an Automate User, I will use this work when I want to drill down to the control and see which control was waived.
https://github.com/chef/automate/issues/2561
A user can click on "Scan Results" on the Profile list page, and then choose a node - which will then show controls that have been waived.
Waived control will be displayed at the bottom of the control list.
load data by using the load_compliance_reports command from your studio dev env
> Automate 2546 Waiver

- components/automate-chef-io/config.toml
- components/automate-chef-io/content/docs/api-tokens.md
- components/automate-chef-io/content/docs/iam-v1-overview.md
- components/automate-chef-io/content/docs/iam-v2-guide.md
- components/automate-chef-io/content/docs/iam-v2-overview.md
- components/automate-chef-io/content/docs/ldap.md
- components/automate-chef-io/content/docs/on-prem-builder.md
- components/automate-chef-io/content/docs/policies.md
- components/automate-chef-io/content/docs/roles.md
- components/automate-chef-io/content/docs/saml.md
- components/automate-chef-io/content/docs/teams.md
- components/automate-chef-io/content/docs/users.md
This PR makes the IAM v1 deprecation more robust. The intention is two-fold: To guide users to the correct IAM documentation with ease, and to reduce future docs work. 
* Strengthens deprecation notices
* Adds (Deprecated) to the v1 title
* Renames "IAM v2 Overview" to  "IAM Overview" 
* Renames "IAM v2 Guide" to "IAM Guide"
* Fix references to these pages 
* Fixes a few broken links that I discovered along the way
The pages are retitled, but the urls are unchanged.
> Robust Deprecation of IAM v1

- api/external/secrets/secrets.pb.go
- api/external/secrets/secrets.proto
- api/external/secrets/secrets.swagger.json
- components/automate-chef-io/data/docs/api-static/03-tags.swagger.json
- components/automate-chef-io/data/docs/api_chef_automate/secrets/secrets.swagger.json
- components/automate-gateway/api/secrets.pb.swagger.go
documenting the secrets service 
https://github.com/chef/automate/issues/2357
secrets service is documented!
check out the branch
run `make serve` from components/automate-chef-io
http://localhost:1313/docs/api/
> api docs: secrets service

- components/compliance-service/inspec-agent/resolver/resolver.go
- components/compliance-service/inspec-agent/resolver/resolver_test.go
I noticed there was a bug with ssm jobs during some acceptance testing -- all nodes showed up nameless after an ssm scan.
Figured out we had some faulty logic in resolver.go -- we were looking for a key value to determine the name and completely ignoring the name of the instance as we had discovered it.
This code change fixes that!
https://github.com/chef/automate/issues/2640
Cloud scans of ec2 result in nodes with names!
run an ssm scan of the nodes (via aws or azure)
* this requires running the automate instance in aws, or having azure creds
> bugfix: ensure node name is correctly assigned when running ssm scan

- components/automate-chef-io/config.toml
- components/automate-chef-io/scripts/clone_hugo.sh
This will run automate.chef.io off the `old_hugo_theme` branch of the chef-hugo-theme repo. 
This will allow us to update the chef-hugo-theme repo with the new hugo theme that is currently on chef-web-docs, but still run the automate site with the older hugo theme.
chef/release-engineering#983
> Run automate site on old Hugo theme

- components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.scss
- components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.ts
I was reviewing some waivers work when i noticed that we hadn't yet made a card for overall status.
I spoke with @jonong1972 -- he brought up that when a fleet's entire status is waived, that is equivalent to compliant/passing. So this is a small code change to make that happen
waived overall status == compliant
rebuild ui
send in reports with `load_compliance_reports`
apply a filter on a waived profile
> when fleet status is waived; show compliant overall status

- components/authz-service/storage/postgres/migration/legacy/iam_migration_test.go
Adds the fixes applied to master in this branch to the new iam force-upgrade tests
https://github.com/chef/automate/pull/3047
> Fix authz tests locally

- components/automate-ui/src/app/components/form-control/form-control.directive.spec.ts
- components/automate-ui/src/app/components/form-control/form-control.directive.ts
The purpose of the `FormControlDirective` is to notice when a field's value matches its original value, thereby allowing a form to recognize that the value has not changed and take an appropriate action, typically contributing to disabling the <kbd>Save</kbd> button. 
I discovered a case where this was not working correctly. If one loads a page containing an `<input>` element governed by `FormControlDirective`,
the initial "original value" will be set to null. (In other words, the directive is being triggered too soon.) This PR allows capturing the slightly delayed "original value" so the control works more reasonably, recognizing as the "original value" the first non-empty value.
This worked fine if you were navigating within the app, which would be occurring most of the time. The fix …
> FormControlDirective fix

- components/automate-ui/src/app/pages/project/details/project-details.component.ts
If you are on the Projects List page and invoke a Project Update, the projects marked "pending" get promptly updated to "applied" because we re-fetch the projects in a timely fashion. The same thing should happen if you happen to be on the Ingest Rules tab of a project details page at the time you invoke a Project Update. Prior to thi PR, you had to do either a page refresh or re-navigate to the rules page to instigate that update. 
NA
Upon invoking "Update Projects" when displaying an edited list of project rules, the status promptly changes from "pending" to "applied".
Create a project.
Create a rule.
Upon creating the rule you should be sitting back on the list of rules page for the project.
Invoke "Update Projects".
Observe that the page updates the status of the …
> Refetch rules when project becomes applied

- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-status/overview-status.component.scss
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profile/reporting-profile.component.html
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profile/reporting-profile.component.scss
- components/automate-ui/src/styles.scss
- components/automate-ui/src/styles/_colors.scss
- components/automate-ui/src/styles/_variables.scss
As an Automate User, I will use this work when I want to look at the waived controls of a profile.
https://github.com/chef/automate/issues/2558
- A user can go to a Reports Profile detail page and see which controls where waived
- A user can see on the report profile detail page how many nodes where affected by a waived control
- A user can filter by Waived controls
load data with load_compliance_reports
> Automate 2558

- integration/services/ha_backend/init.sh
- integration/services/ha_backend/setup.sh
- lib/platform/config/config.go
The existing code that we have to parse the platform config and generate postgresql connection strings contains a bug that results in unparseable URL strings when the password contains a `%` character.
The cause of this is that we generate the bulk of the URL connection string (user, password, ip, port, options) and then run `fmt.Sprintf()` on THAT string to insert the database name later on.
This change uses a function pointer to make the `fmt.Sprintf` call only once with all of the data.
> Make sure passwords with percent work

- components/automate-ui/src/app/components/confirm-apply-start-modal/confirm-apply-start-modal.component.html
We did some testing in our perf acceptance environment and a project update took approximately 6 days, this updates the modal text to better communicate that.
```
Updating projects will apply all pending edits and move ingested resources into the correct projects. This background process can take a few minutes for systems with a limited number of nodes, and <strong>several days</strong> for systems with a large number of nodes.
```
everything still works
text is different
> adjust project update modal text 

- components/data-feed-service/dao/migration/sql/02_destinations.up.sql
Enforcing conditions on the data_feed_service database destinations table. Constraints added to name and url fields so they are not empty.
Try creating or updating a destination through the UI or API with empty name, url fields. These should error. Otherwise destinations should be created and updated as normal.
> enforce non empty conditions on name and url for in destinations table

- components/automate-ui/src/app/modules/policy/add-members/policy-add-members.component.ts
This branch adds a type description for the animation changes in the add-members component.
Errors showing here related to policy-add-members.component are gone
```
src/app/modules/policy/add-members/policy-add-members.component.html:43:46
src/app/modules/policy/add-members/policy-add-members.component.html:66:46
error TS2339: Property 'triggerValue' does not exist on type 'PolicyAddMembersComponent'.
[@dropInAnimation]="{ value: triggerValue, params: { height: 88.2422 }}" >
```
make serve
> Add types for animation in policy-add-members

- components/automate-gateway/integration/nodes_test.go
- components/compliance-service/api/tests/30_jobs_docker_spec.rb
- components/compliance-service/inspec/cli.go
- components/compliance-service/inspec/cli_test.go
- components/compliance-service/scanner/db.go
- added error msg to error saved as "connection error" on node object
- added winrm auth error to inspec errors list
- added original err msg to returned inspec error on scans
https://github.com/chef/automate/issues/3149
inspec errors returned are more verbose
get a box to test against
add node with incorrect credential
note error msg after adding node
press rerun on node
see better error msg
before:
after:
> return more verbose error msgs for detect and exec scans

- components/automate-chef-io/Makefile
Specify `old-hugo-theme` branch in Makefile sync.
This should have been in #3131
automate.chef.io builds using the `old_hugo_theme` branch from the **chef-hugo-theme** repo.
`make sync` or `make serve`
> Update chef-hugo-theme branch in makefile

- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.html
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.scss
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.spec.ts
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.ts
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-nodes/reporting-nodes.component.html
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-nodes/reporting-nodes.component.scss
- components/automate-ui/src/app/pages/+compliance/shared/reporting/report-data.service.ts
- components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.spec.ts
- components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.ts
- Adds `waived` status filter to reporting nodes list view
- Adds `waived` status filter to reporting node detail view
https://github.com/chef/automate/issues/2574
https://github.com/chef/automate/issues/2557
> Add `waived` status to reporting nodes list and node detail

- components/compliance-service/inspec-agent/resolver/resolver.go
- components/nodemanager-service/managers/managers.go
- components/nodemanager-service/managers/managers_test.go
- components/nodemanager-service/tests/scanjob_aws_api_integration_test.go
this issue was reported in slack
a user found that all controls for the aws profile had results like "region value is not set/missing". they also noticed the env value was being set to gcp-api
this change fixes the env region to be the correct "aws-api" and ensures that the region gets set when calling the awscreds function
aws api scans working
add a node integration for aws (https://github.com/chef/automate/blob/master/components/compliance-service/scripts/create-pg-data.sh#L144)
run a scan job on it, see the error about missing region
rebuild compliance and nodemanager
run scan again, no region error, just normal results
> ensure region is always set for aws api integration

- components/automate-ui/src/app/entities/projects/project.effects.ts
The prior fix (#3100) made "pending edits" status appear promptly for a newly logged-in user, but neglected to handle if edits _become_ pending while a user is logged in.
This modifies the rules status polling to also include a project fetch, which is used to determine whether edits are pending.
Also changing the interval from 1 to 2 minutes just to keep overhead to a minimum.
PR #3100 Show pending edits bar promptly on login.
If rules are modified by another user, either in the UI or command line,
all other users are notified within 2 minutes.
1. rebuild automate-ui
2. login and create a project. Let's call this browser A. Just to show there's nothing up the sleeve, navigate to some innocuous page (e.g. Compliance) that has nothing to do with projects or rules per se.
3. make sure no …
> Make pending edits apply to multi-user environment

- components/compliance-service/inspec-agent/resolver/resolver.go
- components/compliance-service/inspec-agent/resolver/resolver_test.go
- components/nodemanager-service/pgdb/node-managers-cloud.go
- components/nodemanager-service/pgdb/node_managers_cloud_integration_test.go
- components/nodemanager-service/server/manager/server.go
follow up to https://github.com/chef/automate/pull/3194
that one fixed the case for aws api integrations that use credentials.
it unfortunately missed the case for when we read creds from cloud env
> ensure the region is set for credentialless node integrations

- components/data-feed-service/config/config.go
- components/data-feed-service/habitat/config/config.toml
- components/data-feed-service/habitat/default.toml
- components/data-feed-service/service/data-feed-poll-task.go
- components/data-feed-service/service/data-feed-poll-task_test.go
- components/data-feed-service/service/data-feed-service.go
Two new configuration options with defaults
disable_cidr_filter = true
cidr_filter = "0.0.0.0/0"
disable_cidr_filter: true/false
cidr_filter: string of csv CIDRS e.g: "172.18.2.120/29,172.18.2.128/29,172.18.2.140/30,172.18.2.144/30,172.18.2.148/31,172.18.2.150/32"
Thus Allowing a user to configure the data-feed-service for a restricted number of nodes using a CIDR block or a number of CIDR blocks.  
The poll task will only include nodes whose ip address is in the defined CIDR ranges, thus only those nodes will be reported in the data feed
Update the config manually and restart the service to test CIDR ranges
> Add CIDR filtering to restrict data-feed to certain nodes

- components/automate-chef-io/content/docs/infra-server.md
This adds a warning about deploying Infra Server with Chef Manage and A2.
> Add warning about running Manage with Server and A2

- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profiles/reporting-profiles.component.html
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profiles/reporting-profiles.component.scss
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profiles/reporting-profiles.component.ts
- components/automate-ui/src/app/pages/+compliance/shared/reporting/report-data.service.ts
- components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.spec.ts
- components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.ts
As an Automate User, I will use this work when I want to see which profiles have been waived.
In the rare case, if a profile has all waived controls within it, we need to show that the profile itself has been waived.
https://github.com/chef/automate/issues/2545
1. A user can see if a Profile is waived based on the new status that the API returns for a profile
2. A user can filter by status of Waived
load data by using the `load_compliance_reports` command from your studio dev env
> Automate-2545 Profile List Waivers

- components/automate-load-balancer/habitat/config/nginx.conf
- integration/helpers/cert_auth_tests.sh
We had originally set up *client* cert checking at the load balancer as part of a research spike for service auth for the automate-deployed Chef Infra server. This was not user-configurable, and since we went in a different direction for service auth, has not been used. We are taking it out now because it's causing ssl handshake issues for some libressl users.
Replaces #2979.
Fixes #2968
> Turn off client cert checking at the load balancer

- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-controls/reporting-controls.component.html
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-controls/reporting-controls.component.scss
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-controls/reporting-controls.component.ts
As an Automate User, I will use this work when I want to more details about the waived controls.
We need a way to show the Reason why a waiver was set, the (if applicable) the expiration date, and (if ran) the status of nodes that were waived.
Sometimes, there may be multiple waivers used with the same control and we need a way to reflect that.
https://github.com/chef/automate/issues/2544
https://github.com/chef/automate/issues/2543
- We need a way to show the Reason why a waiver was set, the (if applicable) the expiration date, and (if ran) the status of nodes that were waived.
- Sometimes, there may be multiple waivers used with the same control and we need a way to reflect that.
A user can go to the Control List view, hover over the waived icon on any control that was waived and view …
> Automate 2544 2543 Control List Waived

- .studio/tooling
- dev-docs/a2-manifest-urls.md
I need one of these URLs at least once a week. Sometimes I can
remember them, but more often I have to grep through the code base to
remember the one I want. Now, they are in one place and we have some
studio tooling for the most commonly needed ones.
> studio/dev-docs: Document locations of manifest URLs

- components/automate-ui/src/app/components/confirm-apply-stop-modal/confirm-apply-stop-modal.component.spec.ts
- components/automate-ui/src/app/components/confirm-apply-stop-modal/confirm-apply-stop-modal.component.ts
- components/automate-ui/src/app/components/process-progress-bar/process-progress-bar.component.html
- components/automate-ui/src/app/components/process-progress-bar/process-progress-bar.component.ts
Added labels for the 0 and 100 cases.
```  
chef_load_nodes 500
```
Add a rule and update projects to see new labels.
> [automate-2912] Add labels for 0 and 100 percent to project upgrade

- .studiorc
A recent PR made the `bin` directory in hab studio sensitive to changes in the vendored files that would affect the tools there, but it would also help to include files that are in our interface to some of those tools, specifically the `protoc-gen-policy` component.
PR #2911 studio: use vendor-state specific directory for GOBIN
You get a new subdir of `bin` with changes to the `protoc-gen-policy` component.
If you have not refreshed your studio lately:
```
[27][default:/src:0]# ls bin
8291598b482a8f2e
[27][default:/src:0]# source .studiorc
. . .
[27][default:/src:0]# ls bin
0e6386b8aa91af26  8291598b482a8f2e
```
If you have a new studio up, just make any edit to one of the newly referenced files in this PR, then run `source .studiorc` (or `setup_gobin`) to see a similar result.
> studio: add other factors for adjusting GOBIN

- components/automate-ui/src/app/modules/team/team-management/team-management.component.html
- components/automate-ui/src/app/modules/team/team-management/team-management.component.spec.ts
- components/automate-ui/src/app/modules/user/user-table/user-table.component.html
- components/automate-ui/src/app/pages/project/list/project-list.component.spec.ts
- e2e/cypress/integration/ui/common/global_filter.spec.ts
Follow-up to #2722, removes the last vestiges of v1 and v2 in the UI.
Review by following the commits for specifics.
#2722 
No more v1 and v2 in the UI. Really.
No changes in functionality.
Also no changes in tests really; just one test deleted.
So the only way to test the change is to grep v1 and v2... and then sort through the barrage of output.
> Remove v1/v2 vestiges in ui

- components/automate-chef-io/content/docs/airgapped-installation.md
- components/automate-cli/cmd/chef-automate/airgap.go
- components/automate-deployment/pkg/airgap/bundle_creator.go
The `--version` flag allows the user to create an airgap bundle for a
specific version. Currently, an airgap bundle is the preferred way for
users to install a specific version of Chef Automate. The addition of
this flag makes it a bit easier to do so.
> [cli] Add --version flag to airgap bundle create

- components/automate-ui/src/app/entities/desktop/desktop.actions.ts
- components/automate-ui/src/app/entities/desktop/desktop.effects.ts
- components/automate-ui/src/app/entities/desktop/desktop.model.ts
- components/automate-ui/src/app/entities/desktop/desktop.reducer.ts
- components/automate-ui/src/app/entities/desktop/desktop.requests.ts
- components/automate-ui/src/app/entities/desktop/desktop.selectors.ts
- components/automate-ui/src/app/modules/desktop/check-in-time-series/check-in-time-series.component.html
- components/automate-ui/src/app/modules/desktop/daily-check-in/daily-check-in.component.html
- components/automate-ui/src/app/modules/desktop/dashboard/dashboard.component.html
- components/automate-ui/src/app/modules/desktop/dashboard/dashboard.component.ts
- components/automate-ui/src/app/modules/desktop/desktop.module.ts
- components/automate-ui/src/app/modules/desktop/top-errors/top-errors.component.html
- components/automate-ui/src/app/modules/desktop/top-errors/top-errors.component.scss
- components/automate-ui/src/app/modules/desktop/top-errors/top-errors.component.ts
Adding the top desktop errors to the skeleton UI page. 
https://github.com/chef/automate/issues/3107
1. Start up the automate-ui locally with build component/automate-ui or the dev way with https://github.com/chef/automate/blob/master/dev-docs/ui-development.md. 
1. Go to https://a2-dev.test/dashboards/desktop
> Top desktop errors on skeleton UI

- .expeditor/buildkite/cypress.sh
fixes this failure: https://buildkite.com/chef/chef-automate-master-deploy-dev/builds/1462#42cdc38f-929b-4df6-9b3a-d29efee315a4
we weren't passing the `CYPRESS_RUN_FLAKY=no`
> fix cypress in deploy pipeline

- components/chef-ui-library/src/molecules/chef-modal/chef-modal.tsx
in chrome the focus of our chef modals was displaying super weird
i also noticed that we were putting focus on a non-interactive element (div)
this changes the focus to be on the first interactive element (close button)
which also resolves the weird focus outline issue
... and i forgot about the locked modals
so added a case for that, if anyone has a better way to do that please let me know
fixes #2371
no more weird focus outline
everything still works
`make update-ui-lib` from `components/automate-ui`
this is just one example, it was happening on all the chef modals
> fix weird focus outline on chef modals

- .studio/compliance-service
- dev-docs/adding-data/add_scanjobs.go
- dev-docs/adding-data/adding_test_data.md
adding an easy way to create scan jobs in dev env
```
[246][default:/src:0]# load_scan_jobs
setting up clients
INFO[0000] certs dir is /hab/svc/deployment-service/data
INFO[0000] Dialing                                       metrics=false secure=true service=deployment-service target="10.0.2.15:10160"
INFO[0000] Dialing                                       metrics=false secure=true service=notifications-service target="10.0.2.15:10125"
INFO[0000] Dialing                                       metrics=false secure=true service=infra-proxy-service target="10.0.2.15:10153"
INFO[0000] Dialing                                       metrics=true secure=true service=ingest-service target="10.0.2.15:10122"
INFO[0000] Dialing …
```
> dev env: add command for creating scan jobs: load_scan_jobs

- components/automate-ui/src/app/helpers/datetime/datetime.ts
- components/automate-ui/src/app/pages/+compliance/+scanner/containers/job-scans-list/job-scans-list.component.html
- components/automate-ui/src/app/pages/+compliance/+scanner/containers/job-scans-list/job-scans-list.component.ts
- components/automate-ui/src/app/pages/+compliance/+scanner/containers/jobs-list/jobs-list.component.ts
Navigating to compliance reporting page with job id filter set was broken from the job scans list (scans from a scheduled job).
I stole the function we use on the jobs list and make the job scans list use it.
I just copied it bc i didn't know where i should put it for sharing - pls advise!
https://github.com/chef/automate/issues/3210
can navigate to compliance reporting from the scans list of a recurring job
rebuild automate ui
create a recurring scan job
try to click the report button on one of the scans
> bugfix: use job id and end time to navigate to compliance reporting from job scans

- api/interservice/teams/v2/teams.pb.go
- api/interservice/teams/v2/teams.pb.mock.go
- api/interservice/teams/v2/teams.proto
- components/authn-service/server/server.go
- components/authn-service/server/server_test.go
- components/automate-deployment/pkg/usermgmt/client/client.go
- components/automate-deployment/pkg/usermgmt/client/client_test.go
- components/automate-gateway/gateway/clients.go
- components/automate-gateway/gateway_mocks/mock_gateway/clients_mock.go
- components/automate-gateway/handler/iam/v2/teams/teams.go
- components/automate-gateway/pkg/nullbackend/backend.go
- components/local-user-service/server/grpc_test.go
- components/local-user-service/server/server.go
- components/local-user-service/server/server_test.go
- components/teams-service/server/server.go
- components/teams-service/server/v2/server_test.go
Part of vetting for force-upgrade release revealed these few vestiges of "V2" use with respect to teams.
NA
No occurrences of "TeamsV2" in the code base.
Nothing to see; a clean buildkite report says all is well.
> Cleanup teams v2 designation

- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-nodes/reporting-nodes.component.html
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-nodes/reporting-nodes.component.spec.ts
- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-nodes/reporting-nodes.component.ts
i noticed the waived profiles were showing up as skipped when viewing scan results from nodes list -- i think i missed making a card for that at some point so i just fixed it real quick.
before:
after:
waived profiles have waived icon on nodes list scan results
rebuild ui
go to nodes list
select waived node scan results
see profile is waived
> ensure waived profiles get the waived icon on nodes list scan results

- components/automate-ui/src/app/services/projects-filter/projects-filter.actions.ts
- components/automate-ui/src/app/services/projects-filter/projects-filter.effects.ts
- components/automate-ui/src/app/services/projects-filter/projects-filter.reducer.ts
- components/automate-ui/src/app/services/projects-filter/projects-filter.service.ts
The original issue scenario is shown in the console trace below:
"Create a project. Tag a single team with the project (leave others unassigned). Select the project from the projects filter. A single team will correctly show up. Hit refresh. ~All the teams will show up.~ _Just the correct team will show up._"
1. The interceptor (the conduit for all back-end requests) early on gets notified of... no projects.
2. Thus, very early requests at this point have no projects in the header.
3. As components are instantiated, the layout facade is starting to build. That kicks off a back-end request for projects.
4. But we already have the project selections in local storage, so we just activate those immediately while waiting for the latest projects list updates, if any, to return from the …
> [Automate-2971] fill project filter before backend calls

- integration/tests/airgap_ow_upgrade.sh
- integration/tests/backup.sh
Adds some IAM inspec testing to our test scenario that backs up Automate on an old version then upgrades/restores the same instance.
> [automate-3165] verify force upgrade in backup restore scenarios

- .studio/automate-gateway
making the command dan added last week for loading a bunch of chef-client reports with custom data configurable for non-dev-env url and token
https://github.com/chef/automate/pull/3213
can use the command to load data in dev env or another env
```
source .studio/automate-gateway
local dev env:
for _ in {1..500} ; do   m=$((RANDOM % 4));   n=$((RANDOM % 25));   generate_chef_run_failure_example |     jq --arg msg "Error $n occurred" --arg type "Chef::ExampleError$m" '.error.message = $msg | .error.class = $type' |     send_chef_data_raw; done
other env:
for _ in {1..500} ; do   m=$((RANDOM % 4));   n=$((RANDOM % 25));   generate_chef_run_failure_example |     jq --arg msg "Error $n occurred" --arg type "Chef::ExampleError$m" …
```
> make send raw chef run configurable

- components/automate-ui/src/app/entities/desktop/desktop.model.ts
- components/automate-ui/src/app/entities/desktop/desktop.reducer.ts
- components/automate-ui/src/app/entities/desktop/desktop.requests.ts
- components/automate-ui/src/app/modules/desktop/check-in-time-series/check-in-time-series.component.html
- components/automate-ui/src/app/modules/desktop/check-in-time-series/check-in-time-series.component.scss
- components/automate-ui/src/app/modules/desktop/check-in-time-series/check-in-time-series.component.ts
- components/automate-ui/src/app/modules/desktop/daily-check-in/daily-check-in.component.html
- components/automate-ui/src/app/modules/desktop/daily-check-in/daily-check-in.component.scss
- components/automate-ui/src/app/modules/desktop/daily-check-in/daily-check-in.component.ts
- components/automate-ui/src/app/modules/desktop/dashboard/dashboard.component.html
- components/automate-ui/src/app/modules/desktop/dashboard/dashboard.component.ts
- components/automate-ui/src/app/modules/desktop/desktop.module.ts
- components/automate-ui/src/app/modules/desktop/top-errors/top-errors.component.html
- components/automate-ui/src/app/modules/desktop/top-errors/top-errors.component.scss
- components/automate-ui/src/app/modules/desktop/top-errors/top-errors.component.ts
Adding to the desktop offering controls the relative time from when it was updated. For each response from the API a timestamp is placed on the data. This timestamp is passed to the controls. Each control starts a timer that updates the relative time to this timestamp ever minute.
https://github.com/chef/automate/issues/3107
All of the desktop offering controls display the relative time they were last updated. 
1. Start up the automate-ui locally with build component/automate-ui or the dev way with https://github.com/chef/automate/blob/master/dev-docs/ui-development.md. 
1. Go to https://a2-dev.test/dashboards/desktop
> Desktop UI: lasted updated message

- components/infra-proxy-service/server/orgs_test.go
- components/infra-proxy-service/server/servers.go
- components/infra-proxy-service/server/servers_test.go
Infra proxy service's servers CRUD operations have been implemented but the test cases were remaining. Added test cases `TestServers` for infra servers functionalities.
NA
- Cover the test cases for `CreateServer`, `GetServers`, `GetServer`, `DeleteServer` and `UpdateServer`.
- Minor code cleanup and good to have changes
- Goto dir `cd components/infra-proxy-service`
- `make setup_docker_pg`
- `make test`
This PR added the test cases for existing `servers` functionalities no need for the build.
> Add test cases for infra servers

- components/data-feed-service/dao/destination.go
- components/data-feed-service/server/server.go
Failed API calls to the data-feed-service were returning 500 in all error cases, I have updated the API to return 404 for update, get, delete operations with an id that doesn't correspond to a datafeed destination record
> Improved errors for data-feed-service API

- components/automate-ui/tsconfig.json
We recently activated what I refer to as "level one" type checking via `fullTemplateTypeCheck` (see PR #3230). This PR starts to address "level two", which would include the single check `strictInjectionParameters` (not clear why this one is separate 🤷‍♂ ) and `strictTemplates`, which comprises a group of checks. We are not yet ready for `strictTemplates` because it reports quite a lot of issues to address, so instead I have itemized its components in the config file and this PR turns on all the ones that are already clean in the code base, requiring no code fixes.
- [fullTemplateTypeCheck](https://angular.io/guide/angular-compiler-options#fulltemplatetypecheck)
- [strictInjectionParameters](https://angular.io/guide/angular-compiler-options#strictinjectionparameters)
- [all other check …
> Turn on strict Angular checks that pass

- components/automate-chef-io/content/docs/iam-v1-overview.md
- components/automate-chef-io/content/docs/iam-v2-guide.md
- components/automate-chef-io/content/docs/iam-v2-overview.md
- components/automate-chef-io/content/docs/projects.md
Recently, in [internal slack](https://chefio.slack.com/archives/C08K8CD9Q/p1585691037001500?thread_ts=1585690965.000800&cid=C08K8CD9Q), someone asked if their tokens became invalidated after restoring admin access and reviewing the docs i noticed that we included a weird reference to admin tokens which is where i think the confusion came from. so i removed that section, its already documented on the tokens docs page, and in the api token docs.
also fixed a bunch of broken links and few other incorrect things.
things are less broken and less confusing
> removed admin token section of restore admin docs and other iam cleanup

- components/compliance-service/api/tests/02_nodes_spec.rb
- components/compliance-service/api/tests/08_deep_search_profiles_spec.rb
- components/compliance-service/api/tests/08_search_profiles_spec.rb
- components/compliance-service/reporting/relaxting/nodes.go
- components/compliance-service/reporting/relaxting/profiles_control_level.go
- components/compliance-service/reporting/relaxting/profiles_profile_level.go
- components/compliance-service/reporting/relaxting/profiles_report_level.go
When we send it status as a filter for nodes or profiles lists, do not apply the status filter to the actual summary counts.  If we apply the status filter to the counts then we won't be able to subsequently choose them in the UI
> ignore status for chicklets

- components/automate-ui/src/app/components/pending-edits-bar/pending-edits-bar.component.spec.ts
- components/automate-ui/src/app/components/pending-edits-bar/pending-edits-bar.component.ts
- components/automate-ui/src/app/entities/layout/layout.facade.ts
- components/automate-ui/src/app/entities/projects/project.effects.ts
- components/automate-ui/src/app/helpers/auth/authorized.ts
We want to improve the user experience for the case of creating a brand new user that has not yet been placed into any teams or policies. Previously, you would immediately see one error bar like that shown, and at times, they could cascade down the page.
So we are applying introspection to determine if we can make the GetProjects call at all.
Points addressed:
1. **Initial login or page refresh.** The page is constructed and, during initialization, it makes a call to GetProjects to be able to determine whether there are any edits pending and thus whether the <kbd>edits pending</kbd> bar should be displayed.
2. **Periodically to keep up-to-date.** As Automate is a multi-user application, actions of one user may affect what other users do. Specifically, if one user edits a project or rule, …
> [Automate-2843] introspect get projects to improve UX

- components/automate-ui/src/app/pages/job-add/job-add.component.ts
- components/automate-ui/src/app/pages/job-edit/job-edit.component.ts
When editing a scan job schedule, the previously scheduled time was coming back different than prior.  This branch makes sure that the datetime is being populated as UTC before being sent as a request.
After Creating a new scan job, when a user returns to edit, they should see the previously scheduled time.
make serve
To Test
Navigate to https://a2-dev.test/compliance/scan-jobs/jobs
Create a New Scan Job, and add a schedule to it -> click save
Investigate the network tab, under then name `jobs` you can check the headers and check that the DateTime was formatted properly.
Return to https://a2-dev.test/compliance/scan-jobs/jobs
Click on the `edit` button to the scan job you just created.  The previously scheduled times should be the default display …
> Bug in UTC dateTime job scheduler

- components/automate-ui/src/app/pages/automate-settings/automate-settings.component.spec.ts
- components/automate-ui/src/app/pages/automate-settings/automate-settings.component.ts
The mark nodes are missing and delete runs after x amount of days fields were switched. 
1. Start the UI with the code from this PR. 
1. Open data lifecycle page https://a2-dev.test/settings/data-lifecycle
1. Ensure that the default value for the "Remove data for Chef Client runs after" control is 30 days. Ensure the default value for the "When no Chef Client run data has been received from a node in" field is 1 day. 
1. This can also be tested by updating the disabling control for the mark missing and saving. Then check the parameters to ensure the "missing_nodes" "disabled" is true.
> Swapping mark missing and delete runs controls

- components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.html
- components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.ts
- components/automate-ui/src/app/modules/infra-proxy/cookbook-list/cookbooks-list.component.html
- components/automate-ui/src/app/modules/infra-proxy/cookbook-list/cookbooks-list.component.ts
this PR cleans up subscriptions for server and org update subscription in infra module :
-- removes Leaking subscriptions
#3270 
Updating Server and Org details successfully as before 
- start the UI and navigate to https://a2-dev.test/infrastructure/chef-servers
- Create a server and org with chef manage credentials or with mock data 
- Click on server from the list >>> Click on details tab and update server details and click on save
- Click on org >>> click on details tab and update org details and click on save (Note : Feature is still in progress).
> Clean up Infra Server and Org update subscriptions

- components/compliance-service/api/tests/30_jobs_docker_spec.rb
Avoids [this](https://buildkite.com/chef-oss/chef-automate-master-verify/builds/10717#beb6af87-6c2d-4892-b485-428ac06ae488) sort of test failure: 
```
expected
actual
@@ -8,9 +8,9 @@
" +
"
" +
-     "STDERR: /hab/pkgs/chef/inspec/4.18.51/20191211220937/lib/gems/docker-api-1.34.2/lib/docker/connection.rb:46:in `rescue in request': No such container: cc_pggggggggg (Docker::Error::NotFoundError)
+     "STDERR: /hab/pkgs/core/ruby26/2.6.5/20191007205438/lib/ruby/gems/2.6.0/gems/docker-api-1.34.2/lib/docker/connection.rb:46:in `rescue in request': No such container: cc_pggggggggg (Docker::Error::NotFoundError)
" +
-     "\tfrom /hab/pkgs/chef/inspec/4.18.51/2019121122093 [truncated for length]",
+     "\tfrom /hab/pkgs/core/ruby26/2.6.5/2 [truncated for length]", …
```
> Be less specific about the conn error being expected

- components/automate-cli/cmd/chef-automate/deprecated.go
Add the command back in hidden with a message about how to create an admin token in IAM V2 so anyone who runs it out of habit or in a script knows how to fix for V2.
```
...
Error: The admin-token command was an IAM V1 command and is now deprecated. To make an admin token in IAM V2, run:
chef-automate iam token create testname --admin
1
```
> Add admin-token back in as a hidden command and give deprecation error

- api/config/platform/config.pb.go
- api/config/shared/global.pb.go
- api/config/shared/tls.pb.go
- api/external/habitat/event.pb.go
- api/external/ingest/chef.pb.go
- api/external/nodes/nodes.pb.go
- go.mod
- go.sum
- vendor/github.com/golang/protobuf/protoc-gen-go/descriptor/descriptor.pb.go
- vendor/github.com/golang/protobuf/protoc-gen-go/descriptor/descriptor.proto
- vendor/github.com/golang/protobuf/protoc-gen-go/generator/generator.go
- vendor/github.com/golang/protobuf/ptypes/any/any.pb.go
- vendor/github.com/golang/protobuf/ptypes/any/any.proto
- vendor/github.com/golang/protobuf/ptypes/duration/duration.pb.go
- vendor/github.com/golang/protobuf/ptypes/duration/duration.proto
- vendor/github.com/golang/protobuf/ptypes/empty/empty.pb.go
- vendor/github.com/golang/protobuf/ptypes/struct/struct.pb.go
- vendor/github.com/golang/protobuf/ptypes/struct/struct.proto
- vendor/github.com/golang/protobuf/ptypes/timestamp/timestamp.pb.go
- vendor/github.com/golang/protobuf/ptypes/timestamp/timestamp.proto
- vendor/github.com/golang/protobuf/ptypes/wrappers/wrappers.pb.go
- vendor/github.com/golang/protobuf/ptypes/wrappers/wrappers.proto
- vendor/modules.txt
Library update from 1.3.3 to 1.3.5. (Review details in the individual commits.)
Outside of hab studio:
```
$ GOFLAGS="" go get -u github.com/golang/protobuf
```
Inside hab studio:
Note--before doing this, it is a good idea to move unrelated, large directories out of the way (e.g. node_modules). 
```
```
Re-enter hab studio to check if regeneration caused any changes:
```
```
https://github.com/golang/protobuf/releases/tag/v1.3.5
All things build.
Check buildkite
> Bump golang/protobuf to 1.3.5

- components/automate-chef-io/content/docs/install.md
The configuration in the docs is wrong. `basic_auth` needs to be under `auth`
ref: [success slack question](https://chef-success.slack.com/archives/C071VQUP5/p1586353834046000)
> Fix external ES docs

- components/automate-builder-api/habitat/plan.sh
We released this version to Live on 04/07/2020. 
Signed-off-by: Jeremy J. Miller <jm@chef.io>
> updating builder-api service pin to the release from 04-07-2020

- .expeditor/announce-release.sh
The Discourse API has recently changed it's authentication method and the underlying issue was fixed in Expeditor's `post_discourse_release_announcement` helper function: https://github.com/chef/expeditor/pull/1240
> Use Expeditor's built in Bash helper to post release announcement

- .studio/common
- components/automate-gateway/habitat/plan.sh
- components/automate-platform-tools/habitat/plan.sh
- components/event-feed-service/habitat/plan.sh
- components/event-feed-service/pkg/integration_test/feed_timeline_test.go
The platform tools are all statically compiled go binaries so we don't
need to depend on glibc.
* remove core/glibc dep in automate-platform-tools
* explicity add a dep on core/glibc in packages that were previously
getting it transitively
* Normalize an event-feed-service test that was failing due to missing
zoneinfo before the explicit dep was added
* Allow specifying the HAB_BLDR_CHANNEL in the studio
> [automate-platform-tools] drop dep on core/glibc

- components/config-mgmt-service/backend/parameters.go
- components/config-mgmt-service/integration_test/nodes_test.go
- components/config-mgmt-service/params/parameters.go
This change is adding the "error_type" as a filter for the GetNodes request. 
#3219 
1. Build and start the change with `build components/config-mgmt-service && start_all_services`
1. Add some failed nodes with error messages and error types with the below
```
for _ in {1..100} ; do
m=$((RANDOM % 4))
n=$((RANDOM % 4))
generate_chef_run_failure_example | \
jq --arg msg "Error $n occurred" --arg type "Chef::ExampleError$m" '.error.message = $msg | .error.class = $type' | \
send_chef_data_raw
done
```
1. Open the Desktop UI page https://a2-dev.test/dashboards/desktop
1. Click on one of the error message names in the "Top 10 Errors" control.
1. The Insights control should appear. 
1. Click on the "error_message" filter to remove it. Ensure note the total number of desktops
1. Click on the …
> Config mgmt Adding Error Message filter to GetNodes request. 

- components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.spec.ts
- components/automate-ui/src/app/modules/infra-proxy/cookbook-list/cookbooks-list.component.spec.ts
- components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.html
- components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.scss
- components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.ts
- components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.spec.ts
1. Previously "Clear Selection" would clear the list in the filter, close the filter, and apply those changes, perhaps inadvertantly wiping out a lot of work for a user. Now, it just clears the filter but leaves it open and does not apply the changes. Thus, if it was done accidentally, one need only close the filter then re-open it to get back the current list of checked projects. Bonus: clearing means clearing only from those visible, i.e. those rendered by the filter!
2. Add a count to the button, maxing out at "99+".
3. Hide the button if the count is zero.
Note: Browse by commit for easy digestion.
NA
1. Selecting <kbd>Clear Changes</kbd> no longer auto-applies changes.
2. Button shows count of filtered and selected items.
3. Button auto-hides if no items in current filtered view or …
> [Automate-3249] adjust clear selection in project filter

- components/automate-ui/src/app/entities/teams/team.reducer.spec.ts
- components/automate-ui/src/app/entities/teams/team.reducer.ts
- components/automate-ui/src/app/modules/team/team-details/team-details.component.ts
When removing a user from a team in the UI, the user is correctly deleted on the back-end, but on-screen it completes by replacing the list of users with the single deleted user, rather than the list of users sans the deleted one.
Note that it is a mirage; if you navigate away then back, or just refresh the page, you see the correct team membership.
This peculiar behavior was only affecting team user management. Every other resource list in the system returns the single deleted resource from the back-end so on the front-end that single user returned in the payload is just removed from the ngrx store. For deleting users from teams, however, the payload returns the entire, correct membership list of the team, so can just replace the ngrx store contents.
NA
Deleting a user in the UI results …
> [Automate-3327] fix delete user from team

- components/automate-load-balancer/habitat/config/automate-cs-nginx-location.conf
Supporting the infra server's `/version` endpoint enables using `knife ec backup` to backup the data from an infra server installed from an omnibus package and using `knife ec restore` to restore the data to an automate-deployed infra server.
Fixes #3301 
1. In `automate/components/automate-deployment`, run `vagrant up` to bring up a minimal vagrant box. Use `vagrant ssh` to login, and go to the `/a2/ directory. 
1. Install a [standalone infra server](https://docs.chef.io/install_server/).
1. As root, install chefdk (`dpkg -i chefdk_4.7.113-1_amd64.deb`) and the knife-ec-backup plugin (`apt-get install ruby-dev g++ libpq-dev; chef gem install knife-ec-backup`).
1. As root, run `knife fetch ssl` to make the infra server's SSL certs available to knife.
1. As root, backup the infra server: …
> Support the infra server's `/version` endpoint in the automate-deployed infra server

- components/automate-ui/src/app/pages/+compliance/+profile/+profile-overview/profile-overview.component.spec.ts
- components/automate-ui/src/app/pages/+compliance/+profile/+profile-overview/profile-overview.component.ts
A bug was discovered that if a user navigated away from the compliance/profiles screen prior to it being finished loading, the loader screen stayed present until the user did a hard refresh.
This branch kills the loading screen in the onDestroy, so that when a user navigates away from compliance/profiles while loading, the loader is removed as well. 
fixes: https://github.com/chef/automate/issues/3342
The loading screen goes away when the user exits the page.
build component/automate-ui-devproxy && start_all_services
make serve
navigate to compliance/compliance-profiles
navigate to another page in the top nav before it finishes loading
view the loading screen close upon navigation and the application is usable
> Kill loading screen in ondestroy and add test associated

- api/external/cfgmgmt/cfgmgmt.pb.go
- api/external/cfgmgmt/cfgmgmt.proto
- api/external/cfgmgmt/cfgmgmt.swagger.json
- components/automate-chef-io/content/docs/client-runs.md
- components/automate-chef-io/content/docs/data-collection.md
- components/automate-chef-io/content/docs/data-lifecycle.md
- components/automate-chef-io/content/docs/delivery_build_cookbook.md
- components/automate-chef-io/content/docs/delivery_truck.md
- components/automate-chef-io/content/docs/migrate.md
- components/automate-chef-io/content/docs/notifications.md
- components/automate-chef-io/content/docs/runners.md
- components/automate-chef-io/content/docs/servicenow-integration-install.md
- components/automate-gateway/api/cfgmgmt.pb.swagger.go
- components/automate-ui/src/app/page-components/converge-radial-graph/converge-radial-graph.component.html
- components/automate-ui/src/app/page-components/run-summary/run-summary.component.html
- components/automate-ui/src/app/pages/automate-settings/automate-settings.component.html
- components/automate-ui/src/app/pages/client-runs/client-runs.component.html
- components/automate-ui/src/app/pages/client-runs/client-runs.component.ts
- components/automate-ui/src/app/pages/notifications/notifications.component.html
- components/automate-ui/src/app/pages/notifications/rule.ts
Automate is behind on the branding for Chef Infra Client, we need to update all labels to reflect current branding.
Fix it in all these places...
fixes #3346 
everything still works but the branding is updated
`make serve` from components/automate-chef-io
> Fix UI + doc branding: "Chef Client" -> "Chef Infra Client"

- components/authz-service/storage/postgres/migration/legacy/iam.go
- components/authz-service/storage/postgres/migration/legacy/iam_migration_test.go
A customer ran into an issue that broke authz-service when they tried to migrate a policy with the resource `cfgmgmt` to v2. This PR fixes that bug and ensures we skip migrating any v1 policies with single term resources that don't directly correspond to an existing API's policy annotations. Those policies were not enforcing any permissions in v1 anyway.
The exceptions to this skip-single-term-resource rule are:
- [nodes](https://github.com/chef/automate/blob/master/api/external/nodes/nodes.proto#L53)
- [events](https://github.com/chef/automate/blob/master/components/automate-gateway/api/event_feed/event_feed.proto#L21)
- [license](https://github.com/chef/automate/blob/master/components/automate-gateway/api/license/license.proto#L18)
- …
> fix IAM v2 migration of policies with single-term resource

- .studio/common
- components/automate-grpc/scripts/bootstrap_protoc.sh
- components/automate-grpc/scripts/grpc.sh
- components/notifications-client/api/health.pb.go
- components/notifications-client/api/notifications.pb.go
- components/notifications-client/api/rules.pb.go
- components/notifications-client/api/server.pb.go
- components/notifications-client/scripts/grpc.sh
- lib/license/license.pb.go
- lib/license/scripts/grpc.sh
Whilst dealing with some rebase woes recently, I found that I was unable to fully rebuild our compiled protobuf code and decided to fix it. So this PR does the following:
* Add studio function to delete all the compiled `*pb*go` files
* Add studio function to bootstrap the custom `protoc-gen-*` tools used in the main protobuf builds
* Add `scripts/grpc.sh` where it was missing, and adjust `compile_all_protobuf_components` accordingly for a "weird" one
* Rebuild all of the protobufs and update ones that have changed a bit
* Update the pipeline to do a full bootstrap rebuild when it tests the protos. The pipeline can now catch issues like a `.proto` file getting removed but the corresponding compiled file remaining, or protos getting added without being correctly integrated in our build …
> Full Protobuf Rebuilds

- components/automate-chef-io/content/docs/infra-server.md
Describe how to set up `knife` for use with the Automate-deployed Infra Server. Users coming to the Automate-deployed Infra Server from using Automate + Infra Server on Opsworks or Infra Server with Manage (deprecated) are used to a different setup model.
> Describe setting up `knife` for use with Automate-deployed Infra Server

- components/automate-chef-io/content/docs/ldap.md
- components/automate-chef-io/content/docs/saml.md
- components/automate-chef-io/content/docs/users.md
we often get questions about what it means to have an active session, this attempts to make it more clear
none.
stuff is maybe more clear
> adjusting active session language

- components/authz-service/storage/postgres/migration/sql/76_compliance_roles_pols.up.sql
- components/authz-service/storage/postgres/migration/sql/README.md
- components/automate-chef-io/content/docs/iam-v2-guide.md
- components/automate-chef-io/content/docs/iam-v2-overview.md
- components/automate-chef-io/content/docs/policies.md
- components/automate-chef-io/content/docs/roles.md
- e2e/cypress/integration/api/iam/policies_api.spec.ts
This PR adds several "helper" roles/policies for IAMv2 users who want to restrict/allow use of compliance resources. Unlike other policies/roles we define, these can be deleted.
Enter studio, rebuild authz.
You should now have 
```
{
"name": "Compliance Editor",
"id": "compliance-editor",
"actions": [
"compliance:*"
],
"projects": []
}
```
```
{
"name": "Compliance Viewer",
"id": "compliance-viewer",
"actions": [
"compliance:*:get",
"compliance:*:list"
],
"projects": []
}
```
```
{
"name": "Compliance Editors",
"id": "compliance-editor-access",
"projects": [],
"members": [],
"statements": [
{
"effect": "ALLOW",
"role": "compliance-editor",
"projects": ["*"]
}
]
}
```
```
{
"name": "Compliance Viewers",
"id": "compliance-viewers",
"projects": …
```
> [automate-2648] add compliance policies

- components/automate-ui/src/app/entities/api-tokens/api-token.effects.ts
- components/automate-ui/src/app/entities/api-tokens/api-token.requests.ts
Recent PR tightening up API parameters caused a break in the toggleToken call.
PR #3197 Add missing "required" field constraints
Toggling token status inactive/active works
Create a token
From the control menu, select <kbd>Toggle Token</kbd>.
> Include now-required name field for toggle token

- components/automate-ui/src/app/page-components/event-feed-guitar-strings/event-feed-guitar-strings.component.spec.ts
- components/automate-ui/src/app/types/types.ts
In the event feed guitar strings on the event feed dashboard, the word 'policy' was getting pluralized to 'policys' - this corrects pluralization to 'policies'
fixes https://github.com/chef/automate/issues/2892
Tooltips no longer show the work "policys" when they are plural, and now reflect the correct. "policies"
build component/automate-ui-devproxy && start_all_services
make serve
in hab studio run the following a few times:
`cat components/ingest-service/examples/actions/policy_update.json | jq --arg date "$(date +%FT%TZ -d '1 day ago')" '.recorded_at = $date' | send_chef_data_raw lb`
navigate to https://a2-dev.test/dashboards/event-feed
Hover over the guitar string icons in the following photo until you see the tooltip pop up.
Wherever there has been an update to a policy, we should …
> Patch for policies value and added test

- components/automate-cli/Makefile
This should fix stale CLI docs of removed commands sticking around.
The removed yamls aren't included in this PR, merging it should show us
if it works, or if there's state somewhere else that needs to be reset.
Running this in the dev env with `env CHEF_DEV_ENVIRONMENT=false make docs`
yields the following deleted files:
deleted:    components/automate-chef-io/data/docs/cli_chef_automate/chef-automate_uninstall.yaml
deleted:    components/automate-chef-io/data/docs/cli_chef_automate/commands/chef-automate_airgap_bundle_unpack.yaml
deleted:    components/automate-chef-io/data/docs/cli_chef_automate/commands/chef-automate_debug.yaml
deleted:    components/automate-chef-io/data/docs/cli_chef_automate/commands/chef-automate_debug_get-version.yaml
deleted: …
> automate-cli/Makefile: attempt to fix CLI docs issue around removed commands

- components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.spec.ts
- components/automate-ui/src/app/pages/project/list/project-list.component.spec.ts
Actually all unit tests were passing. But both the regular test runner and Wallaby test runner reported "console" errors. (Wallaby actually told me the tests where the errors emanated from.)
Output from `make unit` before the fix:
```
16 04 2020 14:34:38.763:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
16 04 2020 14:34:38.925:INFO [launcher]: Starting browser ChromeHeadless
16 04 2020 14:35:10.202:INFO [HeadlessChrome 80.0.3987 (Mac OS X 10.14.6)]: Connected on socket gDVUDuz1Fz_zVJoTAAAA with id 32456407
................................................................................
................................................................................
................................................................................ …
```
> Fix unit test "failures"

- .expeditor/config.yml
- components/automate-cli/Makefile
The make target is used in the script that's watched. So it makes sense
to include it in the watched files.
I would have done that in #3403 had I not forgotten about it. The change
to the Makefile in this PR is silly.
> automate-chef-io: trigger rebuild of automate-cli docs

- components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.scss
in acceptance testing we noticed a weird focus outline, this fixes it.
zero.
everything still works.
focus outline isn't weird anymore.
> fix focus outline on global project filter checkboxes

- components/automate-chef-io/data/docs/api-static/00-meta.swagger.json
Removes `http` from the schema.
> Only HTTPS on API

- components/automate-chef-io/layouts/_default/data-api.html
the lack of margin on the logo has literally been driving me wild
this fixes it
if you want me to fix it a different way just let me know, happy to adjust
zero.
the logo has a margin
everything else is still the same
> fix margin on chef automate logo in api docs

- components/automate-chef-io/data/docs/api-static/00-meta.swagger.json
This is the quick-fix, until we sort out API versioning in the front-end.
> Add `v0` to API path

- components/automate-chef-io/layouts/_default/data-api.html
Previously, there were a few usability concerns with the return to docs button. (1) the left-nav would not scroll all the way to the bottom until you forced it, which hid content (2) you could only ever access the button when you were at the very top of the page.
This pr attempts to address both of those issues. The solution uses the `scroll-y-offset` option provided by redoc to offset the left nav, fixes the button to the page, and also improves the visual style of the button.
I am open to feedback if anyone has concerns, my motivations are to improve the usability.
None.
The user experience of the return to docs button on the api docs is improved.
_Note: The logo is fixed in #3422 so what you see prolly wont match the screenshot until that merges._ 
`make serve` from …
> fix usability of return to docs button for api docs

- components/infra-proxy-service/server/orgs.go
- components/infra-proxy-service/server/orgs_test.go
- components/infra-proxy-service/server/servers.go
- components/infra-proxy-service/server/servers_test.go
- components/infra-proxy-service/service/service.go
- components/infra-proxy-service/storage/postgres/postgres.go
- components/infra-proxy-service/storage/storage.go
- Add ErrCannotDelete & ErrForeignKeyViolation custom errors.
- In order to deal with foreign_key_violation error for invalid & delete cascade partial string match with error object detail.
- Earlier only error code name was used to distinguish between errors but it was returning same for both the cases like invalid foreign key and delete parent record if child exists.
- https://github.com/chef/automate/issues/3297
- https://github.com/chef/automate/issues/3294
- If a user attempts to delete a chef server and if it has orgs now it raises the error:
```
"cannot delete server _<server-guid>_ because it still has organizations attached"
```
- If non-existed server ID is provided while creating the organization now it raises an error:
```
"no server found with ID _<server-guid>_"
```
Steps to …
> [infra-proxy-service] More specific foreign_key_violation  error messages.

- components/automate-ui/src/app/app-routing.module.ts
- components/automate-ui/src/app/entities/layout/layout.facade.ts
- components/automate-ui/src/app/modules/desktop/dashboard/dashboard.component.ts
- Moved `/dashboards/desktop` to `/desktop`. Desktop dashboard will be a top-level route with its own link in the top-level navbar.
- Removed the sidebar in desktop dashboard view. Desktop dashboard will be a full-width view.
Before
After
> Move desktop dashboard to top-level route

- components/automate-ui/package.json
- components/automate-ui/scripts/unit-tests.sh
With unit test warnings not causing build failures, it is easy to either postpone fixing them indefinitely or possibly not even notice them in the first place. This somewhat complex machination adjusts the unit test run so that not only _errors_ but _warnings_ will now also generate a non-zero exit code.
Chances are there is a flag or switch somewhere to "treat warnings as errors" but I could not find it with angular or karma or jasmine... so I went with what I knew would work, because I have used it before.
#3397 Fix unit test "failures"
Unit test warnings return a non-zero exit code, forcing a build failure.
Pay particular attention to the very last line of output:
```
0 ✓ (1m17s) 18:54:33 automate-ui (master) $ npm run test
> automate-ui@0.0.0 test2 …
```
> Treat UI unit test warnings as errors

- components/compliance-service/compliance.go
- components/compliance-service/inspec-agent/remote/remote.go
we now have to add a token to an ingest policy after creation for that token to be a valid ingest token; this change makes that happen
https://github.com/chef/automate/issues/3394
tokens created for ssm jobs work
to truly test this, you need to bring up the dev env in aws and create an ec2 node integration, then try scanning some ssm nodes
the other way to test locally is to call the runssmjob function from the regular scan job path, log the token, and then ensure the token works for sending in a report and fetching a profile
>  fix ssm jobs

- components/authz-service/server/v2/system.go
- components/compliance-service/inspec-agent/remote/remote.go
i had changed the value to compliance service based on some pr
feedback but it seems that it does not work when compliance is referenced:
```
["tls:service:compliance-service:internal"] subject is missing iam:projects:assign
on this project: ["(unassigned)"]
```
my bad, i should have retested after making the change; i didnt realize compliance would be unauthorized for this?
https://github.com/chef/automate/pull/3421
> add compliance service to the universal access policy

- .bldr.toml
- components/automate-cli/pkg/diagnostics/context.go
- components/automate-cli/pkg/diagnostics/integration/helpers.go
- components/automate-cli/pkg/diagnostics/integration/iam_projects.go
- components/automate-cli/pkg/diagnostics/integration/iam_roles.go
- components/automate-cli/pkg/diagnostics/integration/iam_teams.go
- components/automate-cli/pkg/diagnostics/integration/iam_tokens.go
- components/automate-cli/pkg/diagnostics/integration/iam_users.go
- components/automate-cli/pkg/diagnostics/integration/iam_v1_policies.go
- components/automate-cli/pkg/diagnostics/integration/iam_v2_policies.go
- components/automate-cli/pkg/diagnostics/lbrequest/lbrequest.go
We had a bug or two in our diagnostics code that caused projects and rules to stick around after a successful run. Please see the first commit for the fix. The rest of the PR is fixing other occurrences, and minor issues.
⚠️ This doesn't fix these left-overs:
- Token `This token was generated by the chef-automate diagnostic tool. It has admin level access on the entire Automate API.`
- Policy `admin policy for token 1735392e-b4cf-42eb-bf58-611b17e28241`
They are created using a different code-flow and hence their removal can be tackled separately.
- #3332 
- Fixes #3445 
Run diagnostics, see the project **not** left over.
- `rebuild components/automate-cli`
- `chef-automate diagnostics run iam`
- observe existing projects
> Part of #3332: fix diagnostics left overs -- projects and rules

- components/automate-chef-io/data/docs/api-static/01-reporting-export.swagger.json
- components/automate-chef-io/data/docs/api-static/05-node-export.swagger.json
fix the quoting on the examples so that we use single quotes on outside and double inside
> api docs: fix examples to use correct quoting

- components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.ts
- components/automate-ui/src/app/pages/project/list/project-list.component.html
- components/automate-ui/src/app/pages/project/list/project-list.component.spec.ts
- components/automate-ui/src/app/pages/project/list/project-list.component.ts
PR #3314 recently introduced an optional `resetCheckboxEvent` parameter to `CreateObjectModalComponent`, but assumed it was always defined. That was true on the projects list page but not on the teams or tokens list pages (the other consumers of CreateObjectModalComponent). Thus, these browser errors occurred whenever visiting those pages:
Commits show the play-by-play.
PR #3314 Allow skipping policy creation on project creation
Browser errors are gone.
Visit teams or tokens pages and observe no error.
Visit projects page and create projects with and without the policies checkbox checked, to confirm that it still works.
> Squelch browser error regarding undefined pipe

- components/teams-service/server/v2/server.go
- components/teams-service/server/v2/server_test.go
- components/teams-service/storage/conformance/conformance_test.go
- components/teams-service/storage/memstore/memstore.go
- components/teams-service/storage/postgres/postgres.go
- components/teams-service/storage/storage.go
doin' this TODO:
```
// TODO (tc): Get the updated set of user membership for the team since	
// that is not what is returned from AddUsers for some reason	
// (can refactor on V1 deprecation).
```
follows: https://github.com/chef/automate/pull/3361
- `rebuild components/teams-service`
- add and remove users from the API or UI. everything should work as usual
> [automate-3112] refactor team member APIs in storage layer

- components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.html
- components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.ts
- components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.spec.ts
- components/automate-ui/tsconfig.json
Currently when using the global projects filter, if a user makes selections, and then reverses those selections, they are still allowed to apply changes, even though no changes are present.
This branch disables the `apply changes` button when there are not "new" changes present.
Fixes: https://github.com/chef/automate/issues/3413
Users see a disabled `apply changes` button until they have made true changes to the filter selections.
make serve
In the UI, create a handful of projects at https://a2-dev.test/settings/projects
in the top right of any page, click on the global projects dropdown
check some of the projects, see the `apply changes` button activate
uncheck those projects, see the `apply changes` button deactivate
check …
> Global Projects Filter: Disable Apply Changes when No changes are present

- components/automate-workflow-ctl/habitat/plan.sh
I'm unsure what changed, but these won't build for me locally without
more specific paths.
> Fix automate-workflow-ctl habitat plan paths

- api/external/secrets/secrets.go
- api/external/secrets/secrets_test.go
- components/infra-proxy-service/server/orgs.go
- components/infra-proxy-service/server/orgs_test.go
- components/infra-proxy-service/server/servers_test.go
Earlier admin key added in `secrets-service` with type `ssh` but seems it getting populated on `node-credentials` setting page. In order to prevent this, it required to add a new secret type `chef-server`.
https://github.com/chef/automate/issues/3309
- Added secret type `chef-server` to `secrets-service` to store the chef organization admin key.
- `rebuild components/infra-proxy-service`
- `rebuild components/secrets-service`
Steps to test:
1. Valid request
```
chef-automate dev grpcurl secrets-service chef.automate.api.secrets.SecretsService.Create -- -d '{"name": "test-key", "type": "chef-server", "data": [{"key": "key", "value": "--KEY--"}]}'
Response:
{
"id": "f970da44-5ec7-4085-82d4-65586edd71d0"
}
```
2. Invalid request
``` …
```
> [infra-proxy-service] Add secrets-service credential type `chef-server`

- components/compliance-service/inspec-agent/remote/remote.go
using job id creates a token conflict since many nodes can be assigned
to a single job. using node id resolves that!
i hadnt realized this bc i was testing against a single ssm instance 🤦‍♀️ 
https://github.com/chef/automate/pull/3421
can scan more than one ssm instance per scan job
see 3421
> ssm jobs: use  node id instead of job id for token creation

- components/chef-ui-library/src/atoms/chef-snippet/chef-snippet.e2e.tsx
- components/chef-ui-library/src/atoms/chef-snippet/chef-snippet.tsx
Currently, `chef-snippet` will log an error if the syntax grammar rules for the language it's asked to render are unavailable.
Instead, this commit modifies the code highlighter to silently render code blocks as uncolored plain text in this scenario. This makes downstream usage easier for consumers like `chef-markdown`.
https://github.com/PrismJS/prism/issues/344#issuecomment-53880549
Fixes https://github.com/chef/automate/issues/3462
`chef-snippet` doesn't throw error if asked to render an unsupported language.
Render a `chef-snippet` element with any `lang` value specified, see rendered snippet with no errors in console.
> Handle languages unrecognized by chef-snippet

- components/infra-proxy-service/Makefile
- components/infra-proxy-service/server/orgs_test.go
- components/infra-proxy-service/server/root_test.go
- components/infra-proxy-service/server/server_test.go
- components/infra-proxy-service/server/servers_test.go
- components/infra-proxy-service/storage/postgres/resetter.go
- components/infra-proxy-service/test/test.go
- Observed minor refactoring while setting up an infra server for the test environment.
- if any failures occur in test cases, the next run raises error due to existed records.
- Left with test DB resetter interface implementation. 
NA
- DRY some of the test helpers code.
- Added test DB resetter.
- Navigate to `cd components/infra-proxy-service`
- `make setup_docker_pg`
- `make test`
> [infra-proxy-service] Add test resetter implementation

- components/compliance-service/api/jobs/server/server.go
- components/compliance-service/api/jobs/server/server_test.go
a customer recently had a problem with scan jobs
they were using the api, and they had specified the profile without including the version.
as a result of leaving out the version, we skipped the profile, and sent a report into compliance ingestion that just had no data, bc we couldnt find the profile
this pr adds validation to the api so that users dont create scan jobs with bad profile urls
profiles urls are validated before creating the job. 
update compliance
try creating a scan job with a malformed profile url: 
```
{
"name": "scan",
"tags": [],
"type": "exec",
"nodes": ["node-id"],
"profiles": ["compliance://admin/linux-baseline"],
"retries": 1
}
```
> validate format of profile urls at scan job creation time

- .studio/compliance-service
this just adds some chef infra reports to the load_compliance_reports command.
helps with getting sample data for chef infra and compliance that has matching node id - just like it would if it was going through audit cookbook 
load_compliance_reports also sends node reports into chef infra with same name/id
source .studio/compliance-service
> amend load_compliance_reports command: send in matching chef infra reports

- components/automate-ui/src/app/app-routing.module.ts
- components/automate-ui/src/app/app.module.ts
- components/automate-ui/src/app/entities/nodes/nodes.actions.ts
- components/automate-ui/src/app/entities/nodes/nodes.effects.ts
- components/automate-ui/src/app/entities/nodes/nodes.model.ts
- components/automate-ui/src/app/entities/nodes/nodes.reducer.ts
- components/automate-ui/src/app/entities/nodes/nodes.requests.ts
- components/automate-ui/src/app/entities/nodes/nodes.selectors.ts
- components/automate-ui/src/app/modules/nodes/nodes-list/nodes-list.component.html
- components/automate-ui/src/app/modules/nodes/nodes-list/nodes-list.component.scss
- components/automate-ui/src/app/modules/nodes/nodes-list/nodes-list.component.ts
- components/automate-ui/src/app/modules/nodes/nodes-routing.module.ts
- components/automate-ui/src/app/modules/nodes/nodes.module.ts
- components/automate-ui/src/app/ngrx.effects.ts
- components/automate-ui/src/app/ngrx.reducers.ts
lots of folks are chatting about the need for a "one node view" (again)
we've had a good bit of the api work to support that view ready for a while now, so this is a skeleton ui page we can use to see the gaps we have in the data, find holes, etc.
it's a hidden page (not accessible from anywhere in the ui, not being advertised in release notes or anything) - just for testing things out and letting ppl play with the data. the sorting isnt all wired up yet, nor is filtering. this is just for initial test and see the data kind of purposes.
thank you @tarablack01 for the help!!
hidden skeleton one node view page
rebuild ui, go to dev-env/nodes
chef_load_nodes
also see https://github.com/chef/automate/pull/3508
- [n/a] Tests added/updated?
> one node view skeleton

- .expeditor/verify.pipeline.yml
- .expeditor/verify_private.pipeline.yml
- .license_scout.yml
- components/automate-builder-api-proxy/habitat/plan.sh
- components/automate-builder-api/habitat/plan.sh
- components/automate-cs-bookshelf/habitat/plan.sh
- components/automate-cs-nginx/habitat/plan.sh
- components/automate-cs-oc-bifrost/habitat/plan.sh
- components/automate-cs-oc-erchef/habitat/plan.sh
- components/automate-workflow-nginx/habitat/plan.sh
- components/automate-workflow-web/habitat/plan.sh
- components/compliance-service/api/tests/11_wonky_profiles_spec.rb
- components/compliance-service/habitat/plan.sh
- scripts/install_grpcurl.sh
- scripts/install_inspec_master.sh
:warning: DO NOT MERGE until the refresh-2020q1-008 hab channel has been promoted to stable :warning: 
This change updates the hardcoded pins in Chef Automate to use versions in the refresh-2020q1-008 core plan refresh channel. It has been tested against refresh-2020q1-008 channel:
* https://buildkite.com/chef-oss/chef-automate-master-verify/builds/11382
* https://buildkite.com/chef/chef-automate-master-verify-private/builds/11761
We use expeditors `smart_build` option so we'll need to trigger a build job manually to rebuild all the things. If we don't rebuild everything our airgap bundles will include multiple universes of packages.
> [hab] update pins for core plan refresh

- components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.ts
The filters for compliance scans were incorrectly checking for waived values.  With guidance from Superteam, this branch corrects the check for waived values, so that the number matches the amount of reports displayed in all column.
fixes https://github.com/chef/automate/issues/3277
Counts on the top of each of the compliance reports columns matches the number or reports shown.
build component/automate-ui-devproxy && start_all_services
make serve
run `load_compliance_reports` in hab studio
navigate to https://a2-dev.test/compliance/reports/nodes
click on one of the nodes that has a lot of runs to see the detail view
filter by waived controls
the number on the top of waived controls column should match how many are in the filtered display
> Add new function for checking if waived.

- components/automate-chef-io/content/docs/iam-actions.md
- components/automate-chef-io/content/docs/roles.md
To meet a documentation need for support and customers, we're adding a chart of IAM Actions, their end points, and their associated UI page to the Chef Automate docs site.
https://github.com/chef/release-engineering/issues/1064
PR should be done when the details of this current chart are filled out as much as possible. @mjingle still needs to do a second run-through.
To view the docs change, pull in this PR and follow the [instructions](https://github.com/chef/automate/blob/master/components/automate-chef-io/README.md#development) for `make serve`.
> Adding IAM Actions doc

- components/automate-ui/src/app/modules/token/token-list/api-token-list.component.spec.ts
- components/automate-ui/src/app/modules/token/token-list/api-token-list.component.ts
This fixes a browser console error "cannot read property 'forEach' of null" if no policies are selected when creating a token.
NA
No browser console error
Go to Settings >> Tokens >> Create Token
Attempt to create a token without specifying any policies to attach to.
> Only dispatch for policies during token creation if some specified

- components/automate-ui/src/app/entities/servers/server.model.ts
- components/automate-ui/src/app/modules/infra-proxy/chef-servers-list/chef-servers-list.component.html
- components/automate-ui/src/app/modules/infra-proxy/chef-servers-list/chef-servers-list.component.spec.ts
- components/automate-ui/src/app/modules/infra-proxy/chef-servers-list/chef-servers-list.component.ts
User should NOT be allowed to delete a chef server if it has orgs, so added message window for the same.
#3294 
- Added message window on delete a chef server if it has and organisation attached to it 
1. `git fetch origin Sachin/infra-cookbook-details`
2. `build components/automate-ui` 
3. Go to `Chef Servers` option which is under `Infrastructure` tab and its under `Chef-Server` feature flag.
4. Add chef server and one organisation under it.
5. Add one more just chef server with no organisation. 
6. Now try to delete both chef server one by one you will able to see the delete and message window as shown in attached screen shots
> Deleting chef server message modal window

- components/config-mgmt-service/integration_test/count_missing_node_durations_test.go
Setting the month two back in go with `AddDate(0, -2, 0)` is not the same as elasticsearch "is it greater than 2 months" with "2M" https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/date-math-expressions.html
Below is an example of the test failing
https://buildkite.com/chef/chef-automate-master-verify-private/builds/11948#7b326a6c-f32a-4026-aa77-ff3cf5dd62cd
Ensure the private config-mgmt-service buildkite is passing.
> Fixing flaky config-mgmt-service test

- components/automate-ui/src/app/services/http/http-client-auth.interceptor.spec.ts
- components/automate-ui/src/app/services/http/http-client-auth.interceptor.ts
- components/automate-ui/src/app/services/telemetry/telemetry.service.ts
Now, we don't have a bunch of exceptions related to that header and CORS
in the browser console, and the requests flow again:
However, it gets us a new warning:
This is less bad. So let's iterate from here 😉 
- Fixes #3130 
✅ No console exception
✅ Telemetry stuff is fired way
- Rebuild UI, open browser with console open. Notice `api_keys`, `events`, and `t` requests succeeding.
> automate-ui/telemetry: don't send projects header

- components/automate-ui/src/app/entities/teams/team.effects.ts
Assuming that the UI knows the current state of team membership, this
change will fix the wrong notification:
For a team with n users, having added another k users, the notification
would have read
"Added k+n users to team."
Now, we'll just say
"Added k users to team."
Note that this may or may not be true: if another actor (using the UI or
the API) had changed team memberships at the same time, it might now be
accurate. But since this problem always exists, I think it's also
acceptible here.
- #3521 
✅ When adding one user to a team of two the notification reads "Added 1 user." not "Added 3 users."
- UI-only change: rebuild automate-ui from the branch,
- go to a teams page, add a user, observe the notification
> automate-ui/teams/add-users: feed payload into success action

- components/ingest-service/chef-load-data/chef-load.toml
Fixing the hab studio hab studio chef load commands like the `chef_load_nodes 10`. The problem was that the URL was updated in the PR #3474, but it was not update for chef load in the studio. 
https://github.com/chef/automate/pull/3474
Be able to run `chef_load_nodes 10`. 
1. run start_all_services then `chef_load_nodes 10`.
1. got to https://a2-dev.test/infrastructure/client-runs
1. Ensure you see some nodes.
> Hab studio chef load updating url path

- components/automate-ui/src/app/pages/+compliance/+credentials/containers/credentials-add-edit-screen.ts
"Add a new credential" has confusing required fields for type "SSH"
https://app.zenhub.com/workspaces/ui-team-5cba23a3b14fdc05970c8f87/issues/chef/automate/3432
Display the error message that is returned from the api.
When a user adds a credential, and adds values into both the SSH password and RSA key you'll see a generic error message that doesn't convey the problem.
- [X ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ X] Tests added/updated?
- [ X] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).
> Add a new credential error message fixed

- components/automate-ui/src/app/pages/integrations/detail/integrations-detail.component.scss
There was a layout issue where the first column on node integrations takes up too much space. 
This updates that column to take up an appropriate amount of space.
make serve
Navigate to https://a2-dev.test/settings/node-integrations
create a node integration through the UI if you do not have one
click to the detail view of the node
view the updated table as seen in the screenshots below
Before:
After:
> update table spacing

- components/applications-service/pkg/storage/postgres/schema/sql/16_service_full_bigint_id.up.sql
A customer recently had an outage after exhausting all the 2 billion integers for the service IDs. This should only happen if creating and deleting services at a high rate, since the steady state total is usually in the 10s of thousands of services range, but since we do know it happens we might as well use a bigint to give ourselves some more room.
> Use bigint for services table

- components/automate-ui/src/app/components/sidebar/sidebar.component.spec.ts
- components/automate-ui/src/app/entities/layout/layout-sidebar.service.ts
- components/automate-ui/src/app/entities/layout/layout.facade.ts
- components/automate-ui/src/app/pages/compliance-landing/compliance-landing.component.ts
- components/automate-ui/src/app/pages/settings-landing/settings-landing.component.ts
The sidebar architecture was changed recently (#2467) and there was a follow-up PR to remove all the old, no longer used bits (#3341). What I missed in that first cleanup, though, is included in this PR: the meta-unit tests that ensure consistency between *LandingComponents and the actual sidebar contents.
Those tests are important, because, once I re-activated them, they confirmed a bug that I had found, to wit: the SettingsLandingComponent data order differed from the actual sidebar order.
very small
the order in SettingsLandingComponent is the order pages are checked for permission, and the user will land on the first page that they have permission for. Since those were out of order, someone with very specific permissions would land on a different page than the sidebar order would …
> [automate-ui] Reinstate some meta-unit tests

- integration/helpers/ssl_tests.sh
> [ssl-tests] disable rating as it always fails due to hostname mismatch

- components/authn-service/server/server.go
Add legacy token into ingest policy if one has been configured on authn startup. If GRPC request fails, log an actionable error.
```
[auth_n.v1.sys.service]
a1_data_collector_token = "mytesttoken"
```
Verify that token exists but it is not in the ingest policy.
```
rebuild components/authn-service
```
Verify that token is now in ingest policy.
> Add legacy token to ingest policy

- components/automate-ui/e2e/admin.e2e-spec.ts
- components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.spec.ts
- components/automate-ui/src/app/entities/policies/policy.model.spec.ts
- components/automate-ui/src/app/entities/policies/policy.model.ts
- components/automate-ui/src/app/modules/policy/details/policy-details.component.ts
* omit `["*"]` from display when that's the only resources (see #3331 )
* attempt to fix the ordering of the JSON properties of a policy
* use the same ordering and the same spacing for the "Copy Definition" functionality
So far, this seems to work, but I'm uncertain about the approach -- I'm not sure the object construction ordering is guaranteed, I believe it might *not* be.
👉 Some random person says it's safe! 🎊 https://www.stefanjudis.com/today-i-learned/property-order-is-predictable-in-javascript-objects-since-es2015/ (@chef/ui-team you would know, wouldn't you? 😃)
#3331.
See above. Resources that are not `"*"` are displayed, empty resources arrays (including those with only one, removed, `"*"` element) are not.
UI-only change.
- Use your favorite way to spin up the UI,
- go to …
> #3331: remove '*' from non legacy policies' resources in ui

- components/automate-ui/src/app/modules/token/token-list/api-token-list.component.spec.ts
- components/automate-ui/src/app/modules/token/token-list/api-token-list.component.ts
The initial pass introducing adding a token to policies during token creation made the two actions concurrent: creating the token and adding it to policies. That strategy only works well, though, if the token creation succeeds. If it fails due to an id conflict--a token of the same name already exists--then it is inappropriate for the policy assignment to still be done.
This PR sequences those so that the policy assignment is initiated iff the token creation is successful.
Let us also consider the flip side--what if token creation succeeds but the policy assignment fails? Should the two operations be done transactionally so that both must succeed otherwise neither does? I would suggest no, it is OK to create the token regardless, and if the policy assignments failed they could be retried …
> [Automate-3537] Sequence addPolicyMembers from createToken

- e2e/cypress/integration/ui/settings/team_add_users.spec.ts
Deflaking some teams add users tests.
Refreshing the store is causing the modal to continue to pop up, so hiding the modal "fixed" the flakiness. Seems like there should be another way to ensure that all the things are present without the storage changes, but none were obvious to me. 
We were also passing a malformed request to delete the users after the fact.
These tests passed CI on 4 separate builds . . . is that enough?
Run the tests?
> [automate-2699] deflake team add users

- components/automate-chef-io/content/docs/iam-v2-overview.md
- components/automate-chef-io/content/docs/roles.md
In the force upgrade this content was removed by way of the api reference, but never added into the api docs. Adding it back into the roles page.
fixes #3572 
folks have more information
Zero.
> adding back in iam v2 role content

- components/automate-chef-io/content/docs/api-tokens.md
In #3511 we added ui functionality to assign policies to a token when they were created but we failed to add docs. This adds those docs.
#3511
fixes #3570
docs have more information
Zero.
> add docs for assigning policy on token creation

- inspec/a2-api-integration/files/fixtures/converge/converge-failure-report_with_ignored_failure_run_converge.json
Two of the e2e InSpec tests were ingesting runs with the same UUID. This data is not deleted after the test, therefore the second test was failing when it requested data from that run.
One example of the test failing
https://buildkite.com/chef/chef-automate-master-verify-private/builds/11816#6cbb0244-bf01-49b8-8bb5-26d900bd3d37/498-1169
The test is not flaky anymore. 
Check buildkite.
> Fixing InSpec e2e flaky test

- components/automate-ui/src/app/modules/nodes/nodes-list/nodes-list.component.ts
Recent PR #3510 (one node skeleton view) did not quite set up the subscription management to prevent leaks. Inserting standard code to do that.
#3510 
Subscription completes when the component is destroyed.
NA
- [] Docs added/updated?
> [automate-3510 amendment] Correct leaky subscription

- e2e/cypress/integration/ui/common/global_filter.spec.ts
- e2e/cypress/integration/ui/settings/project_mgmt.spec.ts
- e2e/cypress/integration/ui/settings/project_rule_mgmt.spec.ts
Stabilized existing tests and marked them unflaky.
Also broke up `project_mgmt` into `project_mgmt`, testing just Projects CRUD, and `project_rule_mgmt`, testing just Rules CRUD.
This we have Cypress coverage for the [Projects GUI section  and most of the Project Rules flow](https://docs.google.com/spreadsheets/d/1mV8dAARhBFxxMZR6gEm1yDXnPqHb9U2mPhZ-zhHLajw/edit#gid=218075547).
What's missing is testing the project update in the UI. I'd like to make that it's own test, since it will involve a lot of moving parts: adding some resources to projects, loading some nodes that we'll write rules for, granting a new user project permissions and then having them log in to verify permissions. I've created a [new tech debt card](https://github.com/chef/automate/issues/3594) for that work.
To run …
> [automate-2697] stabilize project mgmt tests

- components/automate-deployment/pkg/usermgmt/client/client_test.go
- components/automate-ui/src/app/services/projects-filter/projects-filter.effects.ts
- components/automate-ui/src/app/services/projects-filter/projects-filter.service.ts
If a project got deleted by someone besides the active UI user, they could persist in localstorage. Now when we fetch the project list on app start, intersect localstorage with that list so there are no zombies 👻.
* Create project `test` in the UI.
* Check it in projects dropdown.
* See that it shows up in local storage.
* Delete the project via the API:
```curl -H "api-token: $TOK" -XDELETE  https://localhost/apis/iam/v2/projects/test --insecure```
* Refresh the app and see that it no longer exists in localstorage and that the dropdown goes away since now there is only the default project.
> On project list fetch, remove any projects that no longer exist

- components/ingest-service/backend/chef_client_run.go
- components/ingest-service/pipeline/message/chef_run.go
- components/ingest-service/pipeline/processor/transmogrify_run.go
- components/ingest-service/pipeline/publisher/node_manager_publisher.go
> Passing the base platform name to the nodemanager

- components/automate-ui/src/app/entities/projects/project.model.ts
- components/automate-ui/src/app/modules/team/team-details/team-details.component.html
- components/automate-ui/src/app/modules/team/team-details/team-details.component.spec.ts
- components/automate-ui/src/app/modules/team/team-details/team-details.component.ts
- components/automate-ui/src/app/modules/token/token-details/api-token-details.component.spec.ts
- components/automate-ui/src/app/modules/token/token-details/api-token-details.component.ts
Since working on #3385 (allow optional assign to policy on create token modal), I was mulling over the use of projects in team and token detail components, and realized a simplification was in order.
Also needed to add a couple tests for the new functionality in both team and token detail components, essentially using the same two sets of tests for both.
PR #3385 
Simplicity.
Exercise updating teams and tokens on their respective detail pages.
1. You can add or remove projects and those are correctly reflected when you save the team/token.
2. This preserves the enable-save-iff-entity-changed paradigm: if you change projects and close the dropdown then <kbd>Save</kbd> becomes enabled, but if you then go back and change to the original set of projects and close the …
> [automate-3385 followup] Simplify projects

- .expeditor/nightly.pipeline.yml
- .expeditor/verify_private.pipeline.yml
- integration/tests/a1_legacy_token.sh
- integration/tests/backup_repo_permissions.sh
Adding the test now since I've just been messing with this for acceptance testing.
> add a1 legacy token integration test

- components/compliance-service/api/tests/25_nodes_spec.rb
- components/compliance-service/ingest/pipeline/publisher/node_manager_publisher.go
- components/compliance-service/ingest/pipeline/publisher/node_manager_publisher_test.go
- components/ingest-service/backend/chef_client_run.go
- components/ingest-service/pipeline/message/chef_run.go
- components/ingest-service/pipeline/processor/transmogrify_run.go
- components/ingest-service/pipeline/publisher/node_manager_publisher.go
- components/ingest-service/pipeline/publisher/node_manager_publisher_test.go
- components/nodemanager-service/pgdb/nodes.go
- components/nodemanager-service/pgdb/nodes_integration_test.go
a few issues:
- platform version was showing up twice in the nodemanager nodes: this is bc we were mistakenly sending the full platform field + the version, instead of either just sending the full field or jsut sending the family and version. i switched to used family for now, for consistency with the compliance side of things, but we may want to come back and just have everything send the full field? not sure yet. should discuss how customers would want to filter that data.
- tags: added environment value as a tag to the node, and also modified the compliance bits to include chef tags in the tags information sent to nodemanager
- state: we did not previously allow sorting by state; we should!
https://github.com/chef/automate/issues/3515
platform information doesn't double up. tags are …
> nodemanager nodes: fix platform and tags info, add state to possible sort options

- .studio/automate-gateway
- .studio/automate-load-balancer
Left-over from #3606 (broken in #3474): add integration test coverage for the status endpoint
There are so many places where these could be put -- I've chosen the Bash place.
> automate-{gateway,load-balancer} integration: add test for /api/v0/status

- components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.ts
- components/automate-ui/src/app/modules/policy/details/policy-details.component.ts
- components/automate-ui/src/app/modules/policy/list/policy-list.component.ts
- components/automate-ui/src/app/modules/roles/list/roles-list.component.ts
- components/automate-ui/src/app/modules/team/team-management/team-management.component.spec.ts
- components/automate-ui/src/app/modules/team/team-management/team-management.component.ts
- components/automate-ui/src/app/modules/token/token-list/api-token-list.component.ts
- components/automate-ui/src/app/modules/user/user-table/user-table.component.ts
- components/automate-ui/src/app/pages/data-feed/data-feed.component.ts
- components/automate-ui/src/app/pages/integrations/list/integrations-list.component.ts
- components/automate-ui/src/app/pages/project/list/project-list.component.spec.ts
- components/automate-ui/src/app/pages/project/list/project-list.component.ts
- components/automate-ui/src/app/types/material-types.ts
- components/automate-ui/tsconfig.json
Follow-on to Angular 9 template type checking enablement, this throws the switch on one more check--and fixes the problems it reveals.
PR #3268 Turn on strict Angular checks
`ng build` is clean with an additional check activated
Run `ng build`
> Light up an additional typescript template check

- components/automate-chef-io/content/docs/event-feed.md
- components/automate-chef-io/content/docs/iam-actions.md
- components/automate-ui/Makefile
- components/automate-ui/e2e/app.e2e-spec.ts
- components/automate-ui/e2e/signin.e2e-spec.ts
- components/automate-ui/src/app/app-routing.module.ts
- components/automate-ui/src/app/app.module.ts
- components/automate-ui/src/app/components/authorized/authorized.component.ts
- components/automate-ui/src/app/components/landing/landing.component.spec.ts
- components/automate-ui/src/app/components/landing/landing.component.ts
- components/automate-ui/src/app/entities/layout/layout-sidebar.service.ts
- components/automate-ui/src/app/entities/layout/layout.facade.ts
- components/automate-ui/src/app/page-components/navbar/navbar.component.html
- components/automate-ui/src/app/pages/client-runs/client-runs.component.html
- components/automate-ui/src/app/pages/client-runs/client-runs.component.ts
- components/automate-ui/src/app/pages/compliance-landing/compliance-landing.component.ts
- components/automate-ui/src/app/pages/event-feed/event-feed.component.html
- components/automate-ui/src/app/pages/event-feed/event-feed.component.ts
- components/automate-ui/src/app/pages/notifications/notifications.component.html
- components/automate-ui/src/app/pages/notifications/notifications.component.ts
- components/automate-ui/src/app/pages/settings-landing/settings-landing.component.ts
- components/automate-ui/src/app/pages/top-nav-landing/top-nav-landing.component.html
- components/automate-ui/src/app/pages/top-nav-landing/top-nav-landing.component.scss
- components/automate-ui/src/app/pages/top-nav-landing/top-nav-landing.component.spec.ts
- components/automate-ui/src/app/pages/top-nav-landing/top-nav-landing.component.ts
- components/automate-ui/src/styles.scss
- components/chef-ui-library/src/molecules/chef-status-filter-group/chef-status-filter-group.scss
- components/release-mgmt-dashboard/src/styles.css
This PR applies the permission-based routing scheme (previously in use just for the sidebar navigation panel) to the top navigation bar.
1. Adds an introspection guard to the one unguarded element, `Dashboards`. Now, each of the top navigation choices will appear only when the user has permission to access it.
2. Changes from static routing to dynamic (permission-based routing): upon navigating to the root level URL (e.g. `https://a2-dev.test/` or `https://a2-local-inplace-upgrade-acceptance.cd.chef.co/`), previously one landed just on the first listed element, `Dashboards` -- whether or not having had permission to access it. Now, the set of top-level navigation choices are examined in turn; the user lands on the first one that they have permission to access, and the URL in the browser …
> [Automate-1044] Permission-based routing for top nav bar

- .expeditor/verify.pipeline.yml
- .studio/common
- components/automate-workflow-server/package.meta
If you don't know about package.meta, it takes a long time to learn the hard way. Anything using postgres will fail to work correctly in HA without it.
This Ci build did not have the second commit that fixes the package.meta for automate-workflow-server, and it failed the repo health job: You can see that the checker works in this build: https://buildkite.com/chef-oss/chef-automate-master-verify/builds/11874
To run locally, enter the studio and `source .studio/common` if necessary. Then:
- `run_studio_repo_health_checks` should print some output and exit 0 with a clean repo
- edit `components/config-mgmt-service/package.meta` by removing `"uses_platform_scaffolding": true` from it. Now `run_studio_repo_health_checks` should fail
- delete `components/config-mgmt-service/package.meta` …
> Require packages using pg-helper to have package.meta

- components/automate-ui/src/app/helpers/datetime/datetime.ts
The Event feed date is UTC, but was not clear to users because there was no label.   This adds UTC to all of the event feed date labels on the side of the event feed list.
Fixes: https://github.com/chef/automate/issues/3400
The event feed now has UTC in its time label
make serve
If you need data in your event feed, this should put one item in:
`cat components/ingest-service/examples/actions/policy_update.json | jq --arg date "$(date +%FT%TZ -d '1 day ago')" '.recorded_at = $date' | send_chef_data_raw lb`
navigate to: https://a2-dev.test/dashboards/event-feed
See `UTC` labeled alongside date as shown in Screenshot below
AFTER:
> Update date in Event Feed label to include UTC

- components/automate-cs-nginx/habitat/plan.sh
This PR pins All dependencies shared between this package and the
chef-server-* packages to the versions required by the chef-server-*
packages.
Currently, the chef-server-* packages we are pinned to were hand-built
and any update to any of these three dependencies will require them to
be re-built.
We cannot follow the latest chef-server-* packages until the
following issue is resolved:
https://github.com/chef/automate/pull/2002#issuecomment-600343881
> [automate-cs-nginx] Pin shared habitat dependencies

- components/automate-ui/src/app/entities/orgs/org.actions.ts
- components/automate-ui/src/app/entities/orgs/org.effects.ts
- components/automate-ui/src/app/entities/servers/server.actions.ts
- components/automate-ui/src/app/entities/servers/server.model.ts
- components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.html
- components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.spec.ts
- components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.ts
- components/automate-ui/src/app/modules/infra-proxy/chef-servers-list/chef-servers-list.component.html
- components/automate-ui/src/app/modules/infra-proxy/chef-servers-list/chef-servers-list.component.spec.ts
- components/automate-ui/src/app/modules/infra-proxy/chef-servers-list/chef-servers-list.component.ts
- components/automate-ui/src/app/modules/infra-proxy/create-chef-server-modal/create-chef-server-modal.component.html
- components/automate-ui/src/app/modules/infra-proxy/create-chef-server-modal/create-chef-server-modal.component.scss
- components/automate-ui/src/app/modules/infra-proxy/create-chef-server-modal/create-chef-server-modal.component.ts
- components/automate-ui/src/app/modules/infra-proxy/create-org-modal/create-org-modal.component.html
- components/automate-ui/src/app/modules/infra-proxy/create-org-modal/create-org-modal.component.scss
- components/automate-ui/src/app/modules/infra-proxy/create-org-modal/create-org-modal.component.ts
- tools/credscan/credscan.go
Previously Chef Server & Orgs model doesn't have an editable ID field so we have added for both models.
Scope of works:
**Chef Infra Servers**
Update the servers modal so that the user can construct the human-readable ids.
servers table has a name(unique) and description columns. consider Name as Id and description as Name similar to team services.
**Chef organizations**
Update the org modal so that the user can construct the human-readable ids.
https://github.com/chef/automate/issues/3240
I have added changes for the model popup to add an editable ID and some UI changes 
```
STEP 1
STEP 2 …
```
> Updated Infra server and org modal UI to construct human readable Id

- components/automate-ui/src/app/modules/infra-proxy/cookbooks/cookbooks.component.html
- components/automate-ui/src/app/modules/infra-proxy/cookbooks/cookbooks.component.scss
- components/automate-ui/src/app/modules/infra-proxy/cookbooks/cookbooks.component.spec.ts
- components/automate-ui/src/app/modules/infra-proxy/cookbooks/cookbooks.component.ts
- components/automate-ui/src/app/modules/infra-proxy/infra-proxy.module.ts
- components/automate-ui/src/app/modules/infra-proxy/infra-roles/infra-roles.component.html
- components/automate-ui/src/app/modules/infra-proxy/infra-roles/infra-roles.component.scss
- components/automate-ui/src/app/modules/infra-proxy/infra-roles/infra-roles.component.spec.ts
- components/automate-ui/src/app/modules/infra-proxy/infra-roles/infra-roles.component.ts
- components/automate-ui/src/app/modules/infra-proxy/org-details/org-details.component.html
- components/automate-ui/src/app/modules/infra-proxy/org-details/org-details.component.scss
- components/automate-ui/src/app/modules/infra-proxy/org-details/org-details.component.spec.ts
- components/automate-ui/src/app/modules/infra-proxy/org-details/org-details.component.ts
- components/automate-ui/src/app/modules/infra-proxy/org-edit/org-edit.component.html
- components/automate-ui/src/app/modules/infra-proxy/org-edit/org-edit.component.scss
- components/automate-ui/src/app/modules/infra-proxy/org-edit/org-edit.component.spec.ts
- components/automate-ui/src/app/modules/infra-proxy/org-edit/org-edit.component.ts
- tools/credscan/credscan.go
Org details page has different tabs, when we click to a particular tab then all API's calling parallel, on this page we are going to add more tabs so we have to manage like if we click to particular tab then only related API will calling.
I have added changes to separate the API calls, now if we click to particular tab then only specific API is called.
https://github.com/chef/automate/issues/3410
we have separated the API calls now only specific tabs related API is calling when we clicking to a particular tab.
```
STEP 1
STEP 2
$ cd …
```
> Fixed the parallel API calling for the org details tabs(Cookbooks, Roles and Org edit tabs)

- components/automate-ui/package-lock.json
- components/automate-ui/package.json
- components/automate-ui/src/styles.scss
This commit adds the [carbon grid](https://www.carbondesignsystem.com/guidelines/2x-grid/implementation/) scss package to the project. The grid classNames (`.bx--row`, `.bx--col`, etc) are globally available across the app's templates. Components that need access to the grid system variables and mixins need to import them from where they are stored in `@carbon/layout`:
```scss
@import "@carbon/layout/scss/layout";
:host {
margin: $carbon--grid-gutter;
@include carbon--breakpoint(lg) {
margin: 0;
}
}
```
> Add carbon grid system

- components/chef-ui-library/package-lock.json
All npm registry entries should use `https`.
Two of these were just broken in 97cf9d832671e614d45ffb606423defc0c7b82a3 merged today.
The third was actually done several months back.
Some relevant links (the second one has a suggested way to clean it up):
npm/npm#20719
https://npm.community/t/npm-install-changes-package-lock-json-resolve-from-http-to-https/6899
NA
All entries in package-lock.json use `https`
NA
> Restore correct https protocol

- components/automate-ui/src/app/entities/nodes/nodes.model.ts
- components/automate-ui/src/app/pages/+compliance/+scanner/containers/jobs-list/jobs-list.component.html
- components/automate-ui/src/app/pages/+compliance/+scanner/containers/jobs-list/jobs-list.component.scss
- components/automate-ui/src/app/pages/+compliance/+scanner/containers/nodes-list/nodes-list.component.html
- components/automate-ui/src/app/pages/+compliance/+scanner/containers/nodes-list/nodes-list.component.scss
- components/automate-ui/src/app/pages/+compliance/+scanner/containers/nodes-list/nodes-list.component.ts
- components/automate-ui/src/app/pages/+compliance/+scanner/containers/scanner/scanner.component.html
I have added some changes for compliance/scan-jobs page so it aligns with the rest of the design patterns in Automate.
fixes #2437
I have added some UI changes for the scan job and nodes tab.
**compliance/scan-jobs tabs**
- change the tab labels to hide the count when it is 0
- change Scan jobs to Scan Jobs
- change Nodes added to Nodes Added
Empty State
- hide the table when there are no scan jobs
- add the empty state pattern
- message: Create the first scan job to get started!
- primary button: Create Scan Job
**compliance/scan-jobs/nodes**
- remove the table row with a message and the primary button
- move the primary button to the top of the table
- change the label to Add Nodes
Empty State
- hide the table when there are no nodes added
- add …
> Changes for scan jobs consistency fixes

- components/automate-ui/src/app/components/resource-dropdown/resource-dropdown.component.ts
`toggleDropdown` was calling `closeDropdown`, which set `active` to false, but then `toggleDropdown` flipped the value of `active `for both the open and close case, incorrectly setting `active` back to true after `closeDropdown` was called.
Create a project then go to a multi-select dropdown (say in teams create modal).
Click on the dropdown and it will open.
Now, do any of the following and it should close properly:
* click outside the dropdown.
* click the dropdown header again.
* press enter.
> Fix logic error that prevented multi-select dropdowns from closing properly

- components/automate-ui/src/app/pages/automate-settings/automate-settings.component.spec.ts
- components/automate-ui/src/app/pages/automate-settings/automate-settings.component.ts
The data going out for converge history and missing_nodes_for_deletion
was swapped, which sent the wrong data to the wrong areas in the api
while looking correct.
This branch alters the mapping so that the correct data is placed.
This is part 1 of https://github.com/chef/automate/issues/3651.  It does not yet handle the non-activation of save button when nodes labeled as missing input is switched to days.
in hab studio: `build components/automate-ui-devproxy && start_all_services`
cd into components/automate-ui and run `make serve`
navigate to https://a2-dev.test/settings/data-lifecycle
change data in all of the client runs section and save
check that the data is the same after a refresh
> Map outgoing and incoming data to opposite inputs in client runs

- components/automate-ui/.sass-lint.yml
- components/automate-ui/src/app/components/sidebar-entry/sidebar-entry.component.html
- components/automate-ui/src/app/components/sidebar-entry/sidebar-entry.component.scss
- components/automate-ui/src/app/components/sidebar-entry/sidebar-entry.component.ts
- components/automate-ui/src/app/components/sidebar/sidebar.component.html
- components/automate-ui/src/app/components/sidebar/sidebar.component.scss
- components/automate-ui/src/app/page-components/navbar/navbar.component.html
- components/automate-ui/src/app/page-components/navbar/navbar.component.scss
- components/automate-ui/src/app/page-components/profile/profile.component.scss
- components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.scss
- components/automate-ui/src/styles.scss
- components/automate-ui/src/styles/_variables.scss
Until a more permanent solution is implemented, this commit retrofits the main navbar and sidebar styles to better handle smaller viewport sizes. The bulk of this diff is tweaks to paddings and font-sizes within Carbon grid breakpoints. The largest visual change is the main navbar collapsing to two rows within smaller viewports.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> Tweak navbar and sidebar styles to handle smaller viewports

- integration/tests/a1_legacy_token.sh
Verified that this works here: https://buildkite.com/chef/chef-automate-master-verify-private/builds/12380#d964062c-54bb-4f3c-bd84-f771176a672e/440-441 -- but it'll keep being run from nightlies.
> ci: fix nightly a1 legacy token test

- components/automate-ui/src/app/modules/token/token-list/api-token-list.component.scss
user cannot delete the last token in the table. The last option in the control menu is cut off. This is not a problem on any of the other auth pages since they all only have one control menu option.
I have added CSS changes to fix this issue.
fixes #2798
I have added `mat-select-penal` CSS to fix for last element of table list.
```
STEP 1
STEP 2
```
1. old behavior
2. after fix
> Fixed the delete last token from API token table list

- components/automate-ui/src/app/modules/infra-proxy/cookbook-details/cookbook-details.component.html
- components/automate-ui/src/app/modules/infra-proxy/cookbooks/cookbooks.component.html
- components/automate-ui/src/app/modules/infra-proxy/infra-role-details/infra-role-details.component.html
- components/automate-ui/src/app/modules/infra-proxy/infra-roles/infra-roles.component.html
- components/automate-ui/src/app/modules/infra-proxy/tree-table/component/tree-table.component.html
- components/automate-ui/src/app/modules/infra-proxy/tree-table/component/tree-table.component.scss
- components/automate-ui/src/app/modules/infra-proxy/tree-table/component/tree-table.component.ts
I have added some UI changes for the roles list and role details page. 
https://github.com/chef/automate/issues/3646
- Fixed hiding Name attribute on role's run-list page detail. Need better UX.
- Fixed default run list in expanded state bit should be in collapse state.
- Fixed On Role's detail page "Roles" breadcrumb directed to cookbooks tab it should be on the respective tab ie.(Roles).
- Fixed blank role's description "NA" should be represented using "...".
```
STEP 1
STEP 2
```
> Automate infra views roles UI changes

- components/automate-ui/src/app/app.module.ts
- components/automate-ui/src/app/entities/data-bags/data-bags.action.ts
- components/automate-ui/src/app/entities/data-bags/data-bags.effects.ts
- components/automate-ui/src/app/entities/data-bags/data-bags.model.ts
- components/automate-ui/src/app/entities/data-bags/data-bags.reducer.ts
- components/automate-ui/src/app/entities/data-bags/data-bags.requests.ts
- components/automate-ui/src/app/entities/data-bags/data-bags.selectors.ts
- components/automate-ui/src/app/modules/infra-proxy/data-bags-list/data-bags-list.component.html
- components/automate-ui/src/app/modules/infra-proxy/data-bags-list/data-bags-list.component.scss
- components/automate-ui/src/app/modules/infra-proxy/data-bags-list/data-bags-list.component.spec.ts
- components/automate-ui/src/app/modules/infra-proxy/data-bags-list/data-bags-list.component.ts
- components/automate-ui/src/app/modules/infra-proxy/infra-proxy.module.ts
- components/automate-ui/src/app/modules/infra-proxy/org-details/org-details.component.html
- components/automate-ui/src/app/modules/infra-proxy/org-details/org-details.component.ts
- components/automate-ui/src/app/ngrx.effects.ts
- components/automate-ui/src/app/ngrx.reducers.ts
Introduced Data Bags list view tab on the organisation details page.
#3370 
Data Bags tab in organisation details page of infra view where we are display the data bags list.
1. git fetch origin Sachin/infra-view-databags-list
2. build components/automate-ui
3. To add data https://github.com/chef/automate/blob/master/dev-docs/adding-data/adding_test_data.md#adding-data-to-infra-views
4. Go to Infrastructure tab >> Chef Servers its under Chef-Server feature flag.
5. Click on `Server list` >> `Organisation list` >> `Data Bags Tab`
> Data Bags tab in infra view

- components/compliance-service/cmd/compliance-service/cmd/run.go
- components/compliance-service/compliance.go
- components/compliance-service/config/types.go
- components/compliance-service/inspec-agent/runner/runner.go
- components/compliance-service/inspec-agent/runner/runner_test.go
- components/compliance-service/inspec/cli.go
- components/compliance-service/inspec/types.go
- components/compliance-service/scripts/grpcurl_it.sh
This PR makes use of the latest inspec `reporter_backtrace_inclusion` and `reporter_message_truncation` [options](https://github.com/inspec/inspec/pull/4994) when triggering Compliance scans from Automate.
It also truncates the controls to maximum 50 (default) results per control before sending the report through ingestion. This is to prevent reports that exceed 4MB which are not allowed through grpc.
^ To tests this, you have to trigger a scan with a control that has a loop inside and generates lots of describe blocks.
> Add the new inspec truncation options

- components/automate-ui/src/app/helpers/auth/regex.ts
- components/automate-ui/src/app/pages/create-data-feed-modal/create-data-feed-modal.component.html
- components/automate-ui/src/app/pages/data-feed-details/data-feed-details.component.html
- components/automate-ui/src/app/pages/data-feed-details/data-feed-details.component.ts
- components/automate-ui/src/app/pages/data-feed/data-feed.component.spec.ts
- components/automate-ui/src/app/pages/data-feed/data-feed.component.ts
folks need to be able to provide items other than standard urls
fixes #3691 
customers are able to create data feeds again
1. `rebuild components/automate-ui-devproxy`
1. navigate to settings > data feeds
1. use the create data feed button
1. provide an IP for the url, make sure it allows you to create it
1. also confirm that entering all whitespace is still disallowed, as is an empty field
1. Editing a data feed URL has the same changes
> remove frontend validation for data feed urls

- components/automate-ui/src/app/modules/desktop/check-in-time-series/check-in-time-series.component.html
- components/automate-ui/src/app/modules/desktop/check-in-time-series/check-in-time-series.component.scss
- components/automate-ui/src/app/modules/desktop/daily-check-in/daily-check-in.component.html
- components/automate-ui/src/app/modules/desktop/daily-check-in/daily-check-in.component.scss
- components/automate-ui/src/app/modules/desktop/dashboard/dashboard.component.html
- components/automate-ui/src/app/modules/desktop/dashboard/dashboard.component.scss
- components/automate-ui/src/app/modules/desktop/dashboard/dashboard.component.ts
- components/automate-ui/src/app/modules/desktop/desktop-detail/desktop-detail.component.html
- components/automate-ui/src/app/modules/desktop/desktop-detail/desktop-detail.component.scss
- components/automate-ui/src/app/modules/desktop/desktop-detail/desktop-detail.component.ts
- components/automate-ui/src/app/modules/desktop/desktop.module.ts
- components/automate-ui/src/app/modules/desktop/insight/insight.component.html
- components/automate-ui/src/app/modules/desktop/insight/insight.component.scss
- components/automate-ui/src/app/modules/desktop/insight/insight.component.ts
- components/automate-ui/src/app/modules/desktop/top-errors/top-errors.component.html
- components/automate-ui/src/app/modules/desktop/top-errors/top-errors.component.scss
- components/automate-ui/src/app/modules/desktop/top-errors/top-errors.component.ts
- components/automate-ui/src/app/modules/desktop/unknown-desktop-duration-counts/unknown-desktop-duration-counts.component.html
- components/automate-ui/src/app/modules/desktop/unknown-desktop-duration-counts/unknown-desktop-duration-counts.component.scss
- components/automate-ui/src/app/modules/desktop/unknown-desktop-duration-counts/unknown-desktop-duration-counts.component.ts
- components/automate-ui/src/app/page-components/navbar/navbar.component.scss
This commit contains an incremental style update to the layout skeleton of the Desktop dashboard view and to the components displayed within it. It utilizes the Carbon grid system and some generic components already available within Automate to bring the functionality and styling of this view a little bit closer to the final production implementation.
<details>
<summary><strong>More screenshots</strong></summary>
</details>
https://github.com/chef/chef-design-system/issues/11
https://github.com/chef/automate/issues/3517
- `npm install` if you haven't updated from master recently to get new Carbon grid dep
- Have some data to look at in the dashboard:
```
for _ in {1..50}; do m=$((RANDOM % 4)); n=$((RANDOM % 4)); generate_chef_run_failure_example | jq --arg msg "Error $n occurred" --arg …
```
> Updates to desktop dashboard grid layout

- .expeditor/nightly.pipeline.yml
We're hitting the 30 min limit
> Give chef server backup nightly test more time

- .studio/ingest-service
- dev-docs/adding-data/adding_test_data.md
- dev-docs/adding-data/sample-reports/desktop-report-1.json
- dev-docs/adding-data/sample-reports/desktop-report-2.json
- dev-docs/adding-data/sample-reports/desktop-report-3.json
added command for all the desktop needs
- loads a few nodes then sets their last check in time to a long ago
- loads a few desktop reports, that should have all those special fields we need for the views
- loads some errored runs
source .studio/ingest-service
load_desktop_reports
visit a2-url/desktop, see data
> add load_desktop_reports command

- components/automate-ui/src/app/components/table/table-cell/table-cell.component.scss
- components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.scss
- components/automate-ui/src/styles.scss
After the recent notification cleanup, the notifications were sitting over the global dropdowns when displayed.  This branch raises the z-index on the global dropdowns and bumps the notifications down.
Small update to the table cell while I was in here so that long, no spaced words are broken to fit in the column as requested by UX.
Fixes: https://github.com/chef/automate/issues/3677
Notifications are now beneath the global dropdown when displaying at the same time.
in hab studio: build components/automate-ui-devproxy && start_all_services
in terminal: cd into components/automate-ui and run `make serve`
Navigate to any page that displays a notification ribbon as a result of an activity.  (i.e. settings -> api tokens, create team, create users, etc.) Complete the action and while the …
> Display Menus over notifications and table cell wrapping cleanup

- components/compliance-service/cmd/compliance-service/cmd/run.go
- components/compliance-service/compliance.go
- components/compliance-service/config/types.go
- components/compliance-service/inspec-agent/runner/runner.go
- components/compliance-service/inspec-agent/runner/runner_test.go
This is the Automate equivalent change for this audit cookbook report reducing approach: https://github.com/chef-cookbooks/audit/pull/418
It will strip profile metadata from reports when the compliance-profile index already has the metadata.
> Added RunTimeLimit option and runner code to strip profiles metadata

- .studio/automate-gateway
- .studiorc
- components/automate-gateway/api/iam/v2/request/rules.pb.go
- components/automate-gateway/api/iam/v2/request/rules.proto
- components/automate-gateway/api/iam/v2/rules.swagger.json
- components/automate-gateway/api/iam_v2_rules.pb.swagger.go
- components/automate-gateway/gateway/server.go
- components/automate-gateway/gateway/services.go
- components/automate-ui/src/app/services/http/http-client-auth.interceptor.spec.ts
- components/automate-ui/src/app/services/http/http-client-auth.interceptor.ts
- e2e/cypress/integration/api/iam/iam_integration.spec.ts
- inspec/a2-api-integration/controls/iam/iam_apis.rb
- inspec/a2-api-integration/controls/iam/project_filtering.rb
- inspec/a2-iam-legacy-integration/controls/legacy_access.rb
It's a trap to accept unknown fields in an API. Users may send a request, everything looks great, but really half of what they had intended didn't work.
So this change enables strict validation of request payloads for grpc-gateway-provided endpoints, with the following exception:
**If the header `Content-Type: application/json+lax` is set**, the API will ignore unknown fields.
1. For `/api/v0/ingest/events/chef/*`, this header is automatically applied.
2. All requests made by automate-ui to the backend apply this header, too.
From what I understand, (1.) is required, and inherent to our mode of operation -- we don't know all the fields we may get.
(2.) is a shortcut. I don't think the UI should need this, but test-driving this change showed me that we depend on this "feature" in enough …
> automate-gateway: disallow unknown fields (with exceptions)

- terraform/test-environments/modules/chef_automate_install/templates/install_chef_automate_cli.sh.tpl
- Add function configure_automate_infra_views.
- if enable_chef_server is enabled the add entry in servers using infra-proxy-service.
Fixes https://github.com/chef/automate/issues/3585
- `dev` and `acceptance` environments have the pre-populated entry of terraform locally deployed chef servers.
> [infra-proxy-service] Auto populate terraform deployed chef servers.

- .expeditor/verify_private.pipeline.yml
- .studio/applications-service
- components/applications-service/pkg/storage/client.go
- components/applications-service/pkg/storage/postgres/services.go
In #3560 we fixed ingestion of services when the sequence generator for IDs had exceeded the max size of a 32 bit integer. There is some code used to generate the dashboard that's still expecting 32 bit integers for the IDs, it needs to be updated for 64 bit.
> Apps tab: Correctly support 64bit IDs in all the code

- components/automate-chef-io/content/docs/data-lifecycle.md
Try to help users who will reasonably try to feed the lifecycle settings output (`status` endpoint) back into the system to change settings on the `config` endpoint. Unfortunately, those two formats are not quite compatible. We need to fix this, certainly, but in the meantime, this at least cautions folks about it.
Docs update
NA
> Add clarification to lifecycle docs

- terraform/test-environments/modules/chef_automate_install/templates/install_chef_automate_cli.sh.tpl
Commenting out the code that was added in this PR 4 hours ago
https://github.com/chef/automate/pull/3592.
This is getting the below error on each server.
```
data.template_file.install_chef_automate_cli: failed to render :
<template_file>:132,123-132: Unknown variable; There is no variable
named "server_id"., and 9 other diagnostic(s)
```
The problem is on this line https://github.com/chef/automate/blob/b508fa482a287056c177b8ff6eb92aceb7c84d8a/terraform/test-environments/modules/chef_automate_install/templates/install_chef_automate_cli.sh.tpl#L132.
Below is a link to the failure in buildkite
https://buildkite.com/chef/chef-automate-master-deploy-dev/builds/1681#c27b949b-cbd5-4536-b262-124809eadb55
> Fixing the deploy/dev pipeline

- terraform/test-environments/modules/chef_automate_install/templates/install_chef_automate_cli.sh.tpl
Terraform templating should acknowledge both `$(server_id)` and `$server_id` but somehow it not, so changing local var access using `$VAR`
Broken PR https://github.com/chef/automate/pull/3592
- Change `$(server_id)` to `$server_id` and other local variable refactored.
> [infra-proxy-service] Update terraform server_id missing variable.

- components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.html
- components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.ts
- e2e/cypress/integration/ui/settings/team_mgmt.spec.ts
- e2e/cypress/support/commands.ts
These rascals are flaky no more 🎊 
Also fixes a minor bug with the Create Object Modal in which the projects dropdown did not reset between modal openings.
[Make sure prereqs installed](https://github.com/chef/automate/tree/master/e2e#running-cypress-locally)
Opens Cypress test runner with `runFlaky=no`
```
cd e2e
```
> [automate-2700] stabilize team_mgmt cypress tests

- components/automate-ui/src/app/components/sidebar/sidebar.component.html
This commit fixes https://github.com/chef/automate/issues/3726. `chef-sidebar-entry` was setup to have its icon rotations configurable but this setting wasn't being utilized.
> Ensure sidebar entries receive icon rotation

- components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.html
- components/automate-ui/src/app/components/resource-dropdown/resource-dropdown.component.html
- components/automate-ui/src/app/components/resource-dropdown/resource-dropdown.component.spec.ts
- components/automate-ui/src/app/components/resource-dropdown/resource-dropdown.component.ts
The mechanism for auto-closing a dropdown when the user clicked anywhere outside its boundaries proved insufficient when putting two dropdowns in the same view.
This PR adds the necessary support.
The issue was exposed in the CreateObjectModalComponent when used for creating a token specifically, as that is where two dropdowns appear (one for policies, one for projects).
Those two dropdowns _almost_ co-existed peacefully. 
✅ If you opened either one, interacted with it, and closed it that worked.
✅ If you opened either one, and clicked elsewhere on static space in the modal, the dropdown closed.
✅ If you opened either one, and clicked even in an active input field, the dropdown closed.
❌ If however, you opened projects (1), then opened policies (2), it failed to close the projects …
> Automate 3533/multiple dropdowns

- dev/config.toml
Fixing a bug that the dev environment defaults to Desktop mode. The dev/config.toml is the default configuration for developers. The `products = ["desktop"]` in the config.toml simulates an Automate Desktop install. This was accidentally checked in.
> Fixing a bug that the dev environment defaults to Desktop mode

- terraform/test-environments/scenarios/single_local_all_inplace_upgrade.tf
It seems like this wasn't set up in our Okta, so let's just remove it.
> single_local_all_inplace_upgrade: remove SAML flag

- components/automate-gateway/gateway/services.go
- components/compliance-service/api/profiles/server/pgserver.go
with the changes introduced in https://github.com/chef/automate/pull/3690, we now use the lax header on the endpoint for profile create - meaning we needed to update the code that looks at the header to accept the new "application/json+lax"
can install a profile by clicking "get" on an "available" profile
rebuild compliance and gateway
install profile from "available" tab
> compliance profiles: accept application/json+lax header

- components/automate-ui/src/app/pages/client-runs/client-runs.component.html
- components/automate-ui/src/app/pages/client-runs/client-runs.component.scss
When on any page that has the loading overlay and enough content to allow scroll users are still able to scroll which makes the overlay look broken since it only stays in the top portion.
I have added changes to lock the screen when a page the loading.
https://github.com/chef/automate/issues/2925
[Repro Image](https://images.zenhubusercontent.com/5d24fdf9dc67db59a676ebc6/cd57d5a4-0efd-4419-9450-1dea064824cf)
- Artificially slow down your connection, in Chrome... Dev Tools > Network > Change Online to Slow 3G
- Navigate to infrastructure/client-runs
- Scroll while the page is loading
Added changes to fix the spinner scrolling when a page data is loading.
```
STEP 1 …
```
> fixed lock scrolling when page loading 

- components/data-feed-service/service/data-feed-aggregate-task.go
- components/data-feed-service/service/data-feed-service.go
Compliance reports for nodes without infra data in automate were being skipped when config setting update_nodes_only = false
Updated the code not to skip in this case.
See issue #3756
> #3756 never skip the report if there is no infra data

- .studio/ingest-service
Updating the habitat studio "load_desktop_reports" command to load Desktop Fake Data. Below is what the Desktop page looks like after running the command.
> Updating the habitat studio command to load Desktop Fake Data

- components/automate-ui/src/app/app.module.ts
- components/automate-ui/src/app/page-components/navbar/navbar.component.html
- components/automate-ui/src/app/page-components/navbar/navbar.component.spec.ts
- components/automate-ui/src/app/page-components/navbar/navbar.component.ts
- components/automate-ui/src/app/pages/top-nav-landing/top-nav-landing.component.spec.ts
- components/automate-ui/src/app/pages/top-nav-landing/top-nav-landing.component.ts
- components/automate-ui/src/app/services/product-deployed/product-deployed.service.ts
Display the Desktop nav on the top of the Automate page only when the Desktop in install. Added the desktop page to be the second page (after the event feed) to default to based on the user's permissions. 
#3244 
1. `start_all_services && start_automate_ui_background && ui_logs`
1. Open https://a2-dev.test/ and ensure the "Desktop" nav is not displayed. 
1. `enable_desktop` Wait about 10 seconds for it to apply
1. Open https://a2-dev.test/ and ensure the "Desktop" nav is displayed. 
Below shows the "Desktop" nav link.
> Desktop deployment UI

- components/automate-ui/src/app/pages/automate-settings/automate-settings.component.html
- components/automate-ui/src/app/pages/automate-settings/automate-settings.component.spec.ts
- components/automate-ui/src/app/pages/automate-settings/automate-settings.component.ts
Desktop: Disable the mark node missing and delete missing node controls
#3244 
1. Start all service and run the automate UI locally. `build components/automate-ui-devproxy/ && start_all_services && start_automate_ui_background && ui_logs`
1. Enable Desktop view with the `enable_desktop` command
1. Go to the https://a2-dev.test/settings/data-lifecycle page
1. Ensure the control with "When no Chef Infra Client run data has been received from a node in" and "Remove nodes labeled as missing after" are disabled like the image below.
> Desktop: Disable the mark node missing and delete missing node controls

- components/automate-ui/src/app/page-components/services-sidebar/services-sidebar.component.html
- components/automate-ui/src/app/page-components/services-sidebar/services-sidebar.component.scss
- components/automate-ui/src/app/pages/service-groups/service-groups.component.scss
When users reduce the window width on the service group page, data that exceed the max-width of the text field becomes incomplete.
I have added some changes to fix this.
https://github.com/chef/automate/issues/2150
I have added some CSS class for the right side bar and now its showing as expected.
```
STEP 1
STEP 2
```
1. existing 
2. after fix
> Fixed words not wrapping when exceeding the max width

- e2e/cypress/integration/api/profiles/profiles.spec.ts
adding a cypress api test for installing an "available" profile
https://github.com/chef/automate/pull/3752
test running in CI for profile install from http call (we already have internal tests for this, but they don't go through the http layer)
run the cypress test! see e2e/readme
> add cypress api test for installing profile

- components/automate-deployment/pkg/services/services.go
- components/automate-deployment/pkg/services/services_test.go
We no longer require specifying dependent products and just include them
by default. services.go did not consider this rule change
> Automate should be considered as a dependency of desktop

- components/automate-deployment/pkg/deployment/deployment.go
- components/automate-deployment/pkg/services/services.go
- components/automate-deployment/pkg/services/services_test.go
Instead of the ui getting [desktop], such a thing
will expand into [automate, desktop]
> Expand product deps before configuring services

- .license_scout.yml
license scout is no longer detecting the this is BSD clause 2
> Force ruby unf gem license

- components/infra-proxy-service/server/clients.go
- components/infra-proxy-service/server/cookbooks.go
- components/infra-proxy-service/server/databags.go
- components/infra-proxy-service/server/environments.go
- components/infra-proxy-service/server/nodes.go
- components/infra-proxy-service/server/policyfiles.go
- components/infra-proxy-service/server/proxy.go
- components/infra-proxy-service/server/roles.go
- go.mod
- go.sum
- vendor/github.com/go-chef/chef/http.go
- vendor/github.com/go-chef/chef/reader.go
- vendor/github.com/go-chef/chef/search.go
- vendor/modules.txt
At present go-chef lib not populating the error message from API response. Added better user-readable error messages based on the error response code.
Fixes https://github.com/chef/automate/issues/3754
- Better user-readable message for chef-server API error responses.
- `rebuild components/infra-proxy-service`
Steps to test:
- Use the latest chef-server test environment detail from channel pined message.
- Invalid org admin key detail.
```
curl -sSkH "api-token: $(get_admin_token)"  https://a2-dev.test/api/v0/infra/servers/test/orgs/chef-org/cookbooks?pretty
{
"error": "The user or client who made the request could not be authenticated. Verify the user/client name, and that the correct key was used to sign the request.",
"code": 2,
"message": "The …
```
> [infra-proxy-service] formalise chef server error response to user-readable message.

- components/automate-ui/src/app/modules/infra-proxy/create-chef-server-modal/create-chef-server-modal.component.html
- components/automate-ui/src/app/modules/infra-proxy/create-chef-server-modal/create-chef-server-modal.component.ts
This was a copy/paste error, bringing in a variable that was never fulfilled here. Yet, that variable was part of the page rendering, so it is a user-facing bug.
We see "server" instead of empty string in three places.
(1) shows the incorrect empty string in one place. (2), (3), and (4) show the corrected text with the word "server" inserted.
1. rebuild automate-ui
2. navigate to Infrastructure >> Chef Servers >> Add Chef Server; you will see (2) in the illustration immediately.
3. Select "edit ID" to expose (4) above.
4. Enter an already used id to expose (3) above.
> Chef servers list fix

- components/automate-ui/src/app/page-components/deletable-node-control/deletable-node-control.component.html
- components/automate-ui/src/app/pages/client-runs/client-runs.component.ts
- e2e/cypress/integration/ui/client-runs/delete_missing_node.spec.ts
Fixing a bug where admin users were not provided the checkboxes to delete missing nodes. The problem was the API path used was incorrect. The incorrect path that was being used was "/ingest/events/chef/node-multiple-deletes", but it was correct path is "/api/v0/ingest/events/chef/node-multiple-deletes".
#3802
1. `build components/automate-ui-devproxy && start_all_services && start_automate_ui_background`
1. Add a older node with `send_chef_run_example`
1. Watch the UI logs for the UI to start up. `ui_logs`
1. Mark the node missing by changing the mark node missing job. 
1. Go to https://a2-dev.test/settings/data-lifecycle
1. Update the "When no Chef Infra Client run data has been received from a node in" to 0. 
1. Go to https://a2-dev.test/infrastructure/client-runs
1. Ensure the …
> Client Runs Delete check boxes not showing up. 

- components/chef-ui-library/src/atoms/chef-tooltip/chef-tooltip.scss
- components/chef-ui-library/src/atoms/chef-tooltip/chef-tooltip.tsx
This commit allows `chef-tooltips` to be made interactable by adding an `interactable` attribute. Fixes https://github.com/chef/automate/issues/3791
> Allow tooltips to be configured for interaction

- components/automate-ui/src/app/modules/desktop/daily-check-in/daily-check-in.component.html
- components/chef-ui-library/src/molecules/chef-phat-radio/chef-phat-radio.e2e.tsx
- components/chef-ui-library/src/molecules/chef-phat-radio/chef-phat-radio.tsx
Our work on desktop required the ability to Deselect options in chef-phat-radio group.  The branch adds the ability to pass an optional `deselectable` prop to chef-phat-radio which causes two things to happen by default.
1. The user can deselect the group by clicking on the currently active option.
2. No Option is selected by default unless the option is specifically passed as a value prop.
User can now deselect options in this group.
All other chef-phat-radio groups have no changes to their current behavior.  Currently these exist on:
https://a2-dev.test/desktop --> has option to deselect
https://a2-dev.test/compliance/reports/nodes
https://a2-dev.test/compliance/reports/nodes/{filtered-node}
https://a2-dev.test/compliance/reports/profiles
https://a2-dev.test/compliance/scan-jobs/nodes …
> Update chef-phat-radio to take optional canDeselect attribute

- components/automate-ui/src/app/page-components/simple-line-graph/simple-line-graph.component.html
- components/automate-ui/src/app/page-components/simple-line-graph/simple-line-graph.component.scss
The top-level `ng-deep`selector was causing some styles to leak out of the `simple-line-graph`'s scoped styles and affecting other charts. This commit fixes this by moving the deep selector block into `:host` block.
> Ensure simple-line-graph styles remain scoped

- components/automate-ui/src/app/entities/service-groups/service-groups.reducer.ts
- components/automate-ui/src/app/page-components/services-sidebar/services-sidebar.component.html
- components/automate-ui/src/app/pages/service-groups/service-groups.component.ts
When moving between "OK" and "Disconnected" nodes, the UI moves from the loading spinner, to the old data, to the new data, with a visible redraw when the new data is finally shown.
fixes #3081
Smooth as butter, no flicker.
export DEVPROXY_URL=localhost
applications_populate_database
Steps to reproduce the behavior:
Go to Application Tab
Select "OK" filter
Select "Disconnected" filter.
Note I am very far from this A2 server, so high-network latency may help reproduce it.
> automate-3081 ui flicker on applications tab

- components/automate-ui/src/app/entities/desktop/desktop.actions.ts
- components/automate-ui/src/app/entities/desktop/desktop.effects.ts
- components/automate-ui/src/app/entities/desktop/desktop.model.ts
- components/automate-ui/src/app/entities/desktop/desktop.reducer.ts
- components/automate-ui/src/app/entities/desktop/desktop.requests.ts
- components/automate-ui/src/app/entities/desktop/desktop.selectors.ts
- components/automate-ui/src/app/modules/desktop/dashboard/dashboard.component.ts
- components/automate-ui/src/app/modules/desktop/desktop-detail/desktop-detail.component.html
- components/automate-ui/src/app/modules/desktop/desktop-detail/desktop-detail.component.scss
- components/automate-ui/src/app/modules/desktop/desktop-detail/desktop-detail.component.ts
- components/automate-ui/src/styles/_colors.scss
- components/automate-ui/src/styles/_variables.scss
For a desktop that is unknown or has errors, IT managers would like to look at its check-in history in the past and understand how the status has changed across two or four weeks. They would also like to dive deep into the individual run details to further investigate the root cause.
https://app.zenhub.com/workspaces/ui-team-5cba23a3b14fdc05970c8f87/issues/chef/automate/3459
1. Display the daily check-in status for the current desktop across small, medium, large, and x-large sizes.
2. Users can change the history length from the default two weeks to four weeks.
3. Every status icon in the check-in history reflects the most meaningful client run status on that day.
4. When hovering over the status icon, show a tooltip with links to the run details page under
export …
> automate-3459 Visualize the check-in history of individual desktop

- components/automate-ui/src/app/page-components/navbar/navbar.component.html
- components/automate-ui/src/app/page-components/navbar/navbar.component.scss
before we had empty link, and no alt text on the logo which resulted in accessibility failures 🚫 . this pr brings the image into the HTML and adds alt text.
fixes #3816 
everything still looks the same but now the logo is accessible, yay!
everything should look the same
> make our chef automate logo acessible

- components/automate-chef-io/content/docs/backup.md
Describe the use of `chef-automate backup restore --patch-config <patch.toml>` to restore to a host with a different FQDN than the host on which the backup was taken. Also:
* Fix links broken by a change to a header name.
* Move the Prerequisite section to the correct location.
* Tighten up commands/description around restore scenarios.
* Add References section with a link to CLI docs.
Signed-off-by: Yvonne Lam <yvonne@chef.io>
> [documentation] Describe use of `--patch-config` option during restore

- components/automate-ui/src/app/components/notification/notification.component.html
- components/automate-ui/src/app/components/notification/notification.component.scss
This commit adjusts the notification styling to ensure notification icons and text remain vertically aligned.
**Before**
**After**
> Ensure notification content aligns vertically

- components/automate-ui/src/app/pages/automate-settings/automate-settings.component.html
- components/automate-ui/src/app/pages/automate-settings/automate-settings.component.spec.ts
- components/automate-ui/src/app/pages/automate-settings/automate-settings.component.ts
On the data lifecycle page, users were prevented from selecting "days" as an option in Client Runs : label node as missing, if they hadn't already altered something on the page.
This branch adds the `resetOrigin` property to the formControl inputs, as well as updates them on save, so that the user can save as many times as they want and the formControl will remember their last known value.
Fixes part 2 of: https://github.com/chef/automate/issues/3651
Users can change the values to whatever they like.  If the value is different than before, the 'Save Changes' button will activate.  If the value is the changed back to its previous value prior to saving changes, the 'Save Changes' button will deactivate.
in hab studio `build components/automate-ui-devproxy && start_all_services`
cd into …
> Add change origin to assist form control directive

- components/automate-ui/src/app/modules/policy/details/policy-details.component.ts
Removes a type declaration that actually is already a builtin type.
See https://www.typescriptlang.org/docs/handbook/utility-types.html#omittk
Tests pass.
Don't. 😉
> automate-ui: Omit<T,K> is builtin

- components/automate-ui/src/app/modules/license/license-apply/license-apply.component.html
- components/automate-ui/src/app/modules/license/license-lockout/license-lockout.component.html
- components/automate-ui/src/app/pages/+compliance/+credentials/components/credentials-form.html
Quick scan of the code base revealed just these few
that were not using the accessibility-friendly
"aria-hidden" on the required marker (*).
Quoting the MDN [web docs on accessibility](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-hidden_attribute):
> Adding aria-hidden="true" to an element removes that element and all of its children from the accessibility tree. This can improve the experience for assistive technology users by hiding:
> 
> purely decorative content, such as icons or images
> duplicated content, such as repeated text
> offscreen or collapsed content, such as menus
> 
NA
All uses of the asterisk to indicate a required field are wrapped in an element specifying `aria-hidden="true"` in the UI templates.
No visible changes.
> Standardize remaining "required" indicators in UI

- components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.html
- components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.scss
- components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.spec.ts
- components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.ts
- components/automate-ui/src/app/entities/teams/team.effects.ts
- components/automate-ui/src/app/entities/users/user.effects.ts
- components/automate-ui/src/app/pages/project/list/project-list.component.ts
- e2e/cypress/integration/ui/settings/project_mgmt.spec.ts
- e2e/cypress/integration/ui/settings/user_mgmt.spec.ts
Optionally add project teams if checkbox selected.
We should be good on length violation concerns since teams have super non-restrictive IDs atm:
https://github.com/chef/automate/blob/master/api/interservice/teams/teams.proto#L16-L20
If one of the team creation requests fail, it still creates the project:
Resulting teams created:
Modal style changes:
> [automate-1882] Optionally add project teams if checkbox selected

- components/compliance-service/api/tests/30_jobs_docker_spec.rb
- components/compliance-service/ingest/pipeline/publisher/node_manager_publisher.go
- components/compliance-service/ingest/pipeline/publisher/node_manager_publisher_test.go
- components/nodemanager-service/pgdb/filtering.go
- components/nodemanager-service/pgdb/project_update.go
- components/nodemanager-service/tests/project_filtering_test.go
- components/nodemanager-service/tests/project_update_test.go
a few weeks ago we introduced the ability to use project filtering
on manually added nodes by supporting the environment tag on those nodes
and appropriately applying it on the node reports.
what we did not do at that time is also apply the project filtering
on the nodemanager nodes, which affects the list present at scan jobs/nodes
and integration/nodes.
this change ensures that we apply the project filtering to the
nodemanager nodes as well.
At this point, nodes will not be "project filtered" until they are ingested at least once.
nodemanager nodes respect project filtering
1-rebuild nodemanager, compliance
2- create a project, rule of environment: test-env
apply the rules
3-run load_scan_jobs, wait for it to complete
3-go to compliance report nodes, see 3 nodes.
filter by project, see …
> enable project filtering on nodemanager nodes

- components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.html
- components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.spec.ts
- components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.ts
- components/automate-ui/src/app/components/projects-dropdown/projects-dropdown.component.spec.ts
- components/automate-ui/src/app/components/projects-dropdown/projects-dropdown.component.ts
- components/automate-ui/src/app/components/resource-dropdown/resource-dropdown.component.html
- components/automate-ui/src/app/components/resource-dropdown/resource-dropdown.component.scss
- components/automate-ui/src/app/components/resource-dropdown/resource-dropdown.component.spec.ts
- components/automate-ui/src/app/components/resource-dropdown/resource-dropdown.component.ts
- components/automate-ui/src/app/entities/policies/policy.model.ts
- components/automate-ui/src/app/entities/projects/project.model.ts
- components/automate-ui/tsconfig.json
To improve the UX for creating tokens, this PR enhances the generic dropdown component to accommodate multiple sections. With these changes, the projects dropdown continues to use only a single section, but the policies dropdown is now separated into chef-managed and custom sections. Furthermore, everything is sorted, except that the chef-managed `ingest-access` policy is positioned at the top of the list since that is the one that will usually be needed.
The video shows the full contents of the dropdown and how it behaves:
And this set of unit tests (new tests highlighted) reveals the requirements that were implemented. 
- The yellow items are related to ordering. The generic dropdown component (ResourceDropdownComponent) no longer sorts its inputs, allowing its consumers …
> [Automate-3439] Add sections to the policies dropdown

- components/automate-ui/src/app/app.module.ts
- components/automate-ui/src/app/entities/policy-files/policy-file.action.ts
- components/automate-ui/src/app/entities/policy-files/policy-file.effects.ts
- components/automate-ui/src/app/entities/policy-files/policy-file.model.ts
- components/automate-ui/src/app/entities/policy-files/policy-file.reducer.ts
- components/automate-ui/src/app/entities/policy-files/policy-file.requests.ts
- components/automate-ui/src/app/entities/policy-files/policy-file.selectors.ts
- components/automate-ui/src/app/modules/infra-proxy/infra-proxy.module.ts
- components/automate-ui/src/app/modules/infra-proxy/org-details/org-details.component.html
- components/automate-ui/src/app/modules/infra-proxy/org-details/org-details.component.ts
- components/automate-ui/src/app/modules/infra-proxy/policy-files/policy-files.component.html
- components/automate-ui/src/app/modules/infra-proxy/policy-files/policy-files.component.scss
- components/automate-ui/src/app/modules/infra-proxy/policy-files/policy-files.component.spec.ts
- components/automate-ui/src/app/modules/infra-proxy/policy-files/policy-files.component.ts
- components/automate-ui/src/app/ngrx.effects.ts
- components/automate-ui/src/app/ngrx.reducers.ts
Added Infra Policy file tab on the org details page.
https://github.com/chef/automate/issues/3406
Added Policy file tab on the org details page where we are displaying the  Policy file lists.
-  When User clicks on the Policy file tab it will show the list of policy files that have Policy Name, Policy Group as it's headings.
```
STEP 1
STEP 2
$npm run serve:hab
```
1. git fetch origin Amol/policy_files_list
2. build components/automate-ui [Above steps for reference.]
3. To add data https://github.com/chef/automate/blob/master/dev-docs/adding-d …
> Policy files list view tab on org details page

- components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.html
show results of a control in the ui even if waived
https://github.com/chef/automate/issues/3852
waived results in ui - node detail page
rebuild ui
see results on waived controls on reporting node detail page
- [] Tests added/updated?
> reporting node detail: show waived control results in ui

- components/automate-ui/src/app/page-components/navbar/navbar.component.html
- components/automate-ui/src/app/page-components/profile/profile.component.html
- components/automate-ui/src/app/page-components/projects-filter-dropdown/projects-filter-dropdown.component.html
the aria-menu in the top right of the nav was broken, now its not
the projects filter isn't really a menu, though it is a menu item of the top nav, so made it a menuitem
made the user menu its own menu, with all the menu items, menuitems
i have no idea if im doing this the best way, if anyone has better ideas pls share. or feel free to adopt.
fixes #3842 
everything works and now the aria menu isn't broken
zero.
> fix broken aria menu

- components/automate-ui/src/app/page-components/delta-viewer/delta-viewer.component.scss
- components/automate-ui/src/app/page-components/event-feed-table/event-feed-table.component.html
- components/automate-ui/src/app/page-components/event-feed-table/event-feed-table.component.scss
- components/automate-ui/src/app/page-components/resource-item/resource-item.component.scss
- components/automate-ui/src/app/page-components/search-bar/search-bar.component.html
- components/automate-ui/src/app/pages/service-groups/service-groups.component.scss
we had some pages with text that was smaller than 11px which causes a11y assessments to fail. this fixes it.
fixes #3844
text size is all at least 11px
> fix too small text a11y

- .expeditor/deploy.pipeline.yml
These tests have not passed for a considerable amount of time. Fixing
them is in the backlog, but until that happens, lets reclaim 30
minutes of our lives.
> [CI] Remove cypress tests from deploy pipeline

- components/automate-ui/src/app/pages/+compliance/+profile/+profile-overview/profile-overview.component.html
- components/automate-ui/src/app/pages/+compliance/+profile/+profile-overview/profile-overview.component.scss
- components/automate-ui/src/app/pages/+compliance/+profile/+profile-overview/profile-overview.component.spec.ts
- components/automate-ui/src/app/pages/+compliance/+profile/+profile-overview/profile-overview.component.ts
Update the Compliance Profile page to include the case of the Desktop Offering is installed. This also updates wording and style for other cases. We want to hide and show the search bar, "X Profiles" "X Available" tabs, profile table, upload button, and text depending on if the Desktop Offering is installed, one or more profiles are installed, and the user has permissions to upload a profile. 
#3749
All the below cases look correct. 
1. `build components/automate-ui-devproxy && start_all_services && start_automate_ui_background && ui_logs`
1. Open https://a2-dev.test/compliance/compliance-profiles and ensure it looks like the below first case labeled "Non-Desktop, zero profiles, can upload profiles."
1. Select the "X Available" tab and …
> Desktop Compliance Profiles Page Update

- components/automate-ui/README.md
- components/automate-ui/package.json
- components/automate-ui/tsconfig.json
Found what seems like [a reliable reference](https://stackoverflow.com/a/59787575/115690) for properly setting key tsconfig options.
While getting this to work, also came across [this reference](https://stackoverflow.com/a/49299180/115690) indicating
it is better not to include the `@types/node` package, so removed that here as well.
NA
UI builds and lints without error
`npm install` to update your node_modules directory with the `@types/node` package deletion. You should see no changes to package.json or package-lock.json after this step.
`ng build` or `make serve` works without errors or warnings
`make lint` reports no errors or warnings
`make unit` reports no errors or warnings
> [automate-ui] tsconfig update

- e2e/cypress/integration/ui/settings/project_mgmt.spec.ts
Needed to pass multiple to the notification dismissal cypress code since there are three notifications for this case to dismiss.
> Fix race condition where cypress test only passed if other two notifications had already timed out

- components/compliance-service/inspec-agent/runner/runner.go
- components/compliance-service/inspec/cli.go
- components/compliance-service/inspec/cli_test.go
gcp project id is required as an input to the exec command; this change adds it
i'm looking into testing
https://github.com/chef/automate/issues/3851
gcp scans work again
go to https://chef.okta.com/app/UserHome
open last pass, search for creds with `GCP creds`
you should see `GCP creds (compliance)` in the shared-allyalls
copy the json creds
go to automate/settings/node-integrations
select gcp
add the json creds and create the integration
go to available profiles and "get" the `CIS Google Cloud Platform Foundation Benchmark Level 1` profile
run scan job against gcp integration using gcp profile
> include input of gcp_project_id for gcp scans

- components/automate-ui/src/app/components/resource-dropdown/resource-dropdown.component.html
- components/automate-ui/src/app/pages/automate-settings/automate-settings.component.html
Added back an inadvertently dropped `chefInput` to restore missing formatting on the filter box control in dropdowns:
PR #3841 Add missing labels to inputs
Formatting restored
Navigate to Settings >> Tokens >> Create Token >> _open dropdown_
> [Automate-3869] filter box formatting fix

- .studio/applications-service
- components/applications-service/pkg/storage/postgres/service_groups.go
- components/applications-service/pkg/storage/postgres/service_internal_test.go
- components/applications-service/pkg/storage/postgres/services.go
Fixes a few bugs in the applications tab database logic:
- Code that converts filters from the application layer to SQL `WHERE` clauses specified the `service_group_name_suffix` column name incorrectly (looks like an incomplete refactoring)
- search suggestions for service name and group name are not correct when there's already one suggestion; added some translation between the names of the fields in filters vs. search bar to prevent "over filtering" in the database layer.
- Use parens to enforce desired grouping of `WHERE` clauses; previously the generated code did not take into account the lexical precedence of the `OR` operator, leading to incorrect query results being returned.
- In the service groups query, apply all relevant filters to the query part that computes service group …
> Apps Tab: Filter Bar APIs Bug Bonanza

- components/ingest-service/backend/chef_client_run.go
- components/ingest-service/backend/chef_client_run_test.go
- components/ingest-service/backend/converge.go
- components/ingest-service/backend/elastic/mappings/node_state.go
- components/ingest-service/test/chef_run_node_state.js
This is in service of the rollouts/change tracking dashboard, where we
want to give the user success/failure statistics grouped by policyfile
versions; in this scenario we need to keep the "old" CCR-based status
around even after a node becomes missing.
Part of #3688 
* Build the ingest service
* start all services (probably only need a subset but I started them all)
* use the `send_chef_run_example` helper to send a CCR report (repeat a few times if you like)
* use the `send_chef_run_failure_example` to send a CCR failure report
* Query Elasticsearch with: `curl -Ss -k -X GET http://localhost:10144/node-state/_search -H 'Content-Type: application/json' -d '{"size": 10}' | jq . | less` 
* search with `/status`, you should see stuff like:
```
"status": "failure",
"chef_run_status": …
```
> Keep CCR status in node-state regardless of missing-ness

- components/automate-gateway/integration/nodes_test.go
- components/compliance-service/api/tests/25_nodes_spec.rb
- components/nodemanager-service/pgdb/nodes.go
the string agg was resulting in mixups where a double quote
inside a tag would cause the entire nodes search api call to fail
bc it couldn't parse the tag.
https://github.com/chef/automate/issues/3724
can add a node with a tag that has a double quote in it and still read the nodes list
rebuild nodemanager
navigate to scan jobs/nodes - add node
add a node with a bad tag like `Dot.Comma,Big;\"Trouble`
make sure scan jobs nodes list is still readable
> use json_build_object instead of string_agg for pg nodes

- components/automate-ui/src/app/modules/license/license-lockout/license-lockout.component.scss
A recent PR added the accessibility annotation for the asterisks in the form but they were not formatted correctly. (Other pages in that PR are rendering correctly.)
It turns out that for this particular form `<span>` elements had some block-like formatting, yet that was quite obsolete as there were no other `<span>` elements on the page(!), so just removed it.
PR #3825
Form is corrected:
In hab studio, find your current license:
```
chef-automate dev psql chef_license_control_service -- -c \
"select db_id, active from licenses;"
```
There should be one row showing active as `t`. (There may likely be only one row total.) Remember the corresponding `db_id` for that row so you can restore it after.
Now deactivate the license...
```
chef-automate dev psql chef_license_control_service -- -c \ …
```
> Fix rendering of license form

- components/compliance-service/api/tests/02_deep_nodes_spec.rb
- components/compliance-service/reporting/relaxting/nodes.go
this was first reported by a customer, conveyed to the team via slack (https://chefio.slack.com/archives/CARK1CBNX/p1591285512151700)
can also see it in acceptance, 
navigate to: https://a2-local-inplace-upgrade-acceptance.cd.chef.co/compliance/reports/nodes?profile_id=1adea07f55a844017c8da6ce7055a93418646bd0eb9040cef38fefd5e11b94d2&control_id=au-export&status=failed
click on failed nodes, see the list of not-failed-nodes there
none
nodes in the node list match the requested status filter
load a bunch of inspec scans
(load_compliance_reports, load_compliance_scans, chef_load_compliance_nodes)
go to compliance - reports - controls list
pick a control that has results across at least two statuses
filter by that control
go to the compliance - reports - nodes list and …
> ensure nodes returned match filter status when in "deep filtering" mode

- components/automate-ui/src/app/modules/roles/details/role-details.component.ts
When copying the definition of a policy, the result is "pretty", i.e., contains
line breaks and indentation. This was done in #3551.
The Role's "Copy Definition" string wasn't adapted to this.
#3331 + #3551 
When clicking "Copy Definiton", the copied string is pretty, too.
Rebuild the ui, go to a role's details page, click "Copy Definition".
Paste the result somewhere.
> automate-ui/role-details: pretty role JSON in "Copy Definition"

- .expeditor/cleanup-abandoned-a2-instances.sh
- .expeditor/config.yml
This just terminates any a2 fresh-install test instances from our dev/acceptance pipelines that can be left abandoned after a failed deploy.
> Cleanup abandoned a2 instances nightly

- .expeditor/verify.pipeline.yml
- .studio/common
- components/automate-deployment/pkg/services/internal/generated/gen.go
- dev/config.toml
- integration/tests/security.sh
Removing the automate-cds service from the "automate" product. The automate-cds service as unintentionally added to the "automate" product by updating the products.meta file and not running the "deployment_generate" command. This is also adding a test so that does not happen again. 
The automate-cds service does not start on normally Automate installs. 
1. Remove the `products = ["automate-dev"]` line from the dev/config.toml file. 
1. Run `start_all_services`
1. Ensure the automate-cds is not running.
> Removing the automate-cds service from the automate product

- components/automate-ui/src/app/app.module.ts
- components/automate-ui/src/app/entities/orgs/org.model.ts
- components/automate-ui/src/app/entities/reset-admin-key/reset-admin-key.actions.ts
- components/automate-ui/src/app/entities/reset-admin-key/reset-admin-key.effects.ts
- components/automate-ui/src/app/entities/reset-admin-key/reset-admin-key.model.ts
- components/automate-ui/src/app/entities/reset-admin-key/reset-admin-key.reducer.ts
- components/automate-ui/src/app/entities/reset-admin-key/reset-admin-key.requests.ts
- components/automate-ui/src/app/entities/reset-admin-key/reset-admin-key.selectors.ts
- components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.spec.ts
- components/automate-ui/src/app/modules/infra-proxy/infra-proxy.module.ts
- components/automate-ui/src/app/modules/infra-proxy/org-details/org-details.component.html
- components/automate-ui/src/app/modules/infra-proxy/org-details/org-details.component.ts
- components/automate-ui/src/app/modules/infra-proxy/org-edit/org-edit.component.html
- components/automate-ui/src/app/modules/infra-proxy/org-edit/org-edit.component.ts
- components/automate-ui/src/app/modules/infra-proxy/reset-admin-key/reset-admin-key.component.html
- components/automate-ui/src/app/modules/infra-proxy/reset-admin-key/reset-admin-key.component.scss
- components/automate-ui/src/app/modules/infra-proxy/reset-admin-key/reset-admin-key.component.spec.ts
- components/automate-ui/src/app/modules/infra-proxy/reset-admin-key/reset-admin-key.component.ts
- components/automate-ui/src/app/ngrx.effects.ts
- components/automate-ui/src/app/ngrx.reducers.ts
- tools/credscan/credscan.go
Added Infra proxy Reset Admin Key tab on the org details page.
fixes #3450 
Updated the ux consistency for reset admin key flow .
1. git fetch origin Amol/reset_admin_key
2. build components/automate-ui
3. To add data https://github.com/chef/automate/blob/master/dev-docs/adding-data/adding_test_data.md#adding-data-to-infra-views
4. Go to Infrastructure tab >> Chef Servers it's under Chef-Server feature flag.
5. Click on `Server list` >> `Organisation list` >> `Reset Admin key ` Tab.
- When User clicks on the Reset Admin Key Tab in which it has form field to add a New Admin key.
- Added validators in the form field.
- After the user clicks on the Reset admin key button, it saved successfully and it shows success notification.
> Reset admin key

- components/automate-ui/src/app/entities/users/userself.effects.ts
- components/automate-ui/src/app/pages/signin/signin.component.spec.ts
- components/automate-ui/src/app/pages/signin/signin.component.ts
- components/automate-ui/src/app/services/chef-session/chef-session.service.ts
- components/automate-ui/src/app/testing/mock-chef-session.service.ts
Connect to a box with SAML (LDAP boxes would exhibit the problem, too).
Login with SAML (LDAP). Note that the dev environment is configured to use SAML so you could do this on your local machine.
Assuming you have appropriate permission to fetch users, previously you would have seen this error:
Without permission from a policy, you would still see the same root error ("Could not get logged in user") but it would be greyed out and indicate no permissions:
ngrx dispatch to the `SetUserSelfID` action in ChefSessionService.
PR 3725, merged 14 days ago, changed the flow slightly as to where `tryInitializeSession` was being called. The timing used to be such that the `SetUserSelfID` dispatch was not being run and with PR 3725 it was.
Looking into what `SetUserSelfID` was doing:
(a) set the ID …
> Fix error banner appearing for non-local users on login

- components/automate-ui/src/app/modules/desktop/top-errors/top-errors.component.html
- components/automate-ui/src/app/modules/desktop/top-errors/top-errors.component.scss
fixes: https://github.com/chef/automate/issues/3861
Long error messages in top errors section are single line only and apply an ellipses as seen in before and after images.
make serve
navigate to https://a2-dev.test/desktop
View top 10 errors screen
when errors are NOT long, they should appear as full error message
When errors are too long for container, an ellipses is applied and message is shortened (if there are no pending long errors, you can see this apply to some errors by slowly narrowing your browser window)
Non Ellipsed:
Ellipsis applied:
> Contain in div and add ellipsis css

- components/automate-ui/src/app/modules/desktop/insight/insight.component.html
- components/automate-ui/src/app/modules/desktop/insight/insight.component.scss
- components/automate-ui/src/app/modules/desktop/insight/insight.component.ts
Allow users to download the filtered desktop data in the current view in a JSON or CSV format.
https://app.zenhub.com/workspaces/ui-team-5cba23a3b14fdc05970c8f87/issues/chef/automate/3503
Allow users to download the filtered desktop data in the current view in a JSON or CSV format.
export DEVPROXY_URL=localhost
load_desktop_reports
> [Desktop UI] Download filtered list of desktop data as JSON or CSV

- components/automate-ui/src/app/modules/nodes/nodes-list/nodes-list.component.html
- components/automate-ui/src/app/modules/nodes/nodes-list/nodes-list.component.scss
- components/automate-ui/src/app/modules/nodes/nodes-list/nodes-list.component.ts
- components/nodemanager-service/pgdb/nodes.go
- set default sort on page load to be last contact, desc
- added tooltip (with help from @SEAjamieD, thank you!) to the infra and inspec run status hover
- fixed up the filtering logic in the ui code to handle daterange filters
- added "missing" as valid node state filter value
nodes page is sorted by last contact, desc on initial page load
tooltip on status that links to client run/inspec scan details
handle timerange filters in the ui code
rebuild nodemanager-service and ui
go to a2-dev.test/nodes
check the sorting (last contact, desc)
try to filter by a time in last contact, expect it to return all nodes that had a last contact on that day
hover over a run or scan status and see the tooltip, follow the link to client run or inspec scan details
> experimental one node view: various fixes

- components/automate-builder-api-proxy/habitat/plan.sh
- components/automate-builder-api/habitat/plan.sh
This updates the version pins for `builder-api` and `builder-api-proxy` to the versions released on 2020.06.16
Signed-off-by: Scott Macfarlane <smacfarlane@chef.io>
> Update builder pins to version released on 2020.06.16

- components/automate-chef-io/content/docs/notifications.md
Signed-off-by: James Massardo <jmassardo@chef.io>
Added examples of a `converge_failure` and a `compliance_failure` webhook notification.
this change was motivated by a convo in [success slack](https://chef-success.slack.com/archives/C071VQUP5/p1590683420355300)
None.
Documentation change
None needed.
> add webhook payload examples

- components/automate-ui/src/app/pages/+compliance/+scanner/containers/jobs-list/jobs-list.component.html
the link to job scans for a recurring scanjob was broken.
this fixes it.
can go to a list of scans for a single recurring job
rebuild ui
create recurring scan job
go to scans list
> fix the router link from scan jobs list to single job scans list

- components/applications-service/integration_test/disconnected_services_job_test.go
- components/applications-service/pkg/server/periodic.go
It appears the disconnected services job was sometimes disabled in a test and the "enabled-ness" was not reset, which caused a later test to fail. It probably should have been failing consistently but passed most of the time due to a race condition. So now we make the job run twice to be sure it's really working.
> Make periodic job enabledness reset with the Reset call

- components/automate-ui/src/app/modules/license/license-apply/license-apply.component.ts
- components/automate-ui/src/app/modules/license/license-lockout/license-lockout.component.ts
When a license is active and it reaches expiry (or is in any other way removed), all current users of the web-app will be asynchronously notified within 5 minutes that there is no valid license, popping up the license lockout modal. That's well and good, but only half the job.
Previously, if the admin then applies a new license, all other users with the license-lockout modal (or license-apply modal) showing will not see the new license status asynchronously (meaning the license-lockout modal or license-apply modal will **not** self-close). One had to manually refresh the browser to make that modal go away. Now, with this PR, either license modal will self-close within 5 minutes.
NA
License modals self-close within 5 minutes of a valid license being applied.
- Reduce the polling interval …
> [automate-3918] Close modal if valid license is detected

- components/automate-ui/src/app/entities/automate-settings/automate-settings.reducer.ts
- components/automate-ui/src/app/entities/client-runs/client-runs.reducer.ts
- components/automate-ui/src/app/entities/desktop/desktop.reducer.ts
- components/automate-ui/src/app/entities/jobs/job.reducer.ts
- components/automate-ui/src/app/entities/managers/manager.reducer.ts
- components/automate-ui/src/app/entities/nodes/nodes.reducer.ts
- components/automate-ui/src/app/entities/profiles/profile.reducer.ts
- components/automate-ui/src/app/entities/roles/role.reducer.ts
- components/automate-ui/src/app/entities/service-groups/service-groups.reducer.ts
- components/automate-ui/src/app/entities/users/user.reducer.ts
- components/automate-ui/src/app/entities/users/userself.reducer.ts
- components/automate-ui/src/app/modules/user/user-details/user-details.component.spec.ts
- components/automate-ui/src/app/pages/integrations/add/integration-add.reducer.ts
- components/automate-ui/src/app/pages/integrations/detail/integrations-detail.reducer.ts
- components/automate-ui/src/app/pages/integrations/edit/integrations-edit.reducer.ts
- components/automate-ui/src/app/pages/job-add/job-add.reducer.ts
- components/automate-ui/src/app/pages/job-edit/job-edit.reducer.ts
- components/automate-ui/src/app/pages/job-list/job-list.reducer.ts
While reviewing PR #3812, I noticed an unexpected construct--explicitly typing a constant as `any`:
```
const newState: any = desktopEntityReducer(initialState, action);
```
That led me down this not terribly deep rabbit hole to discover--and fix--all the reducers that do not declare a return type. A nice side effect is that this revealed a couple tests that were not properly defining the ngrx state for testing purposes. Looking at it from another perspective, though, it revealed that almost all the existing tests were fine.
NA
All reducer functions are explicitly typed to return their respective states.
Nothing to see, I fear. As long as tests pass, we should be good.
> [automate-ui] Fix reducer signatures

- components/automate-gateway/gateway/clients.go
- components/automate-gateway/gateway/services.go
Previous logic relied on environment variable. It might be better to
just say this is optional for now
> automate gateway should not crash if cds functionality not enabled

- components/chef-ui-library/src/molecules/chef-phat-radio/chef-phat-radio.tsx
This commit fixes an issue where `chef-phat-radio` would throw an error if you clicked on the component, but not directly within a `chef-option` child, such as between the gutters surrounding the `chef-option` elements.
**Before**
**After**
> Fix click error that can occur in `chef-phat-radio`

- components/config-mgmt-service/integration_test/event_feed_test.go
- components/config-mgmt-service/params/parameters.go
Fixing event feed chef-server filtering. The problem was that the UI was using the term 'chef_server' but the only valid terms were ''source_fqdn' or 'service_hostname'. The solution was to add 'chef_server' as an alias. 
Filtering the event feed with a chef-server works. 
1. `build components/config-mgmt-service && start_all_servcies`
1. `chef_load_nodes 100`
1. `chef_load_actions 100`
1. Go to https://a2-dev.test/dashboards/event-feed and add a chef-server filter.
> Fixing Event Feed chef server filter bug

- components/automate-ui/src/app/pages/event-feed/event-feed.component.ts
Fixing event feed policy file filtering. In the UI the event type term for a policy file was incorrect. 
Filtering by policy file event type works in the UI. 
1. `build components/automate-ui-devproxy && start_all_services && start_automate_ui_background && ui_logs`
1. After the UI finish loading, create a policy file event with these two commands. 
1. `rfc_time=$(date --rfc-3339=seconds  -d "$((RANDOM % 144)) hour ago" | sed 's/ /T/' | sed 's/\+.*/Z/');`
1. `cat components/ingest-service/examples/actions/policy_update.json | jq --arg rfc_time "$rfc_time" '.recorded_at = $rfc_time' | send_chef_data_raw lb`, 
1. Go to https://a2-dev.test/dashboards/event-feed and filter by the policy file event type.
> Updating the policy file term

- components/automate-chef-io/content/docs/data-collection.md
- components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.html
recently, in a [community slack convo](https://chefcommunity.slack.com/archives/CAZSL536K/p1592595733202400) there were some questions around what policy to add the api token to in the data collection docs, this specifies that folks should use the ingest policy.
zero.
docs still work but are more clear
zero.
> add ingest policy info to data collection docs

- components/automate-ui/src/app/modules/token/token-details/api-token-details.component.ts
Once you save a token as Inactive, you could not reactivate it. The system always thought "Active" was the saved state, so switching to Active actually _disables_ the "Save" button instead of _enabling_ it.
Cause: The default state of the radio button was being initialized to true, regardless of its actual value, thereby rendering the mechanism that recognizes a change ineffective.
NA
You can reactivate an Inactive token in the UI.
Navigate to Settings >> Tokens >> (token) >> Details
Use a token that is inactive. If you do not have one, open the details, make it inactive, save, then go back to the token list, and re-open the details.
> Remove default initialization of radio button

- .studio/common
- components/automate-ui/src/app/components/guitar-string-collection/guitar-string-item/guitar-string-item.component.ts
- components/automate-ui/src/app/page-components/event-feed-table/event-feed-table.component.ts
- components/automate-ui/src/app/page-components/event-icon/event-icon.component.ts
- components/automate-ui/src/app/services/event-feed/event-feed.service.spec.ts
- components/automate-ui/src/app/services/event-feed/event-feed.service.ts
The event feed was not displaying or filtering all cookbook events correctly. Cookbook chef-server action comes in as three different types "cookbook", "cookbook_artifact_version", and "version". 
When we are filtering for cookbooks we want all three types to be returned. Also, the "cookbook_artifact_version" type should display the cookbook icon. 
1. `build components/automate-ui-devproxy && start_all_services && start_automate_ui_background && ui_logs`
1. Add a few cookbook events with the below commands
1. `rfc_time=$(date --rfc-3339=seconds  -d "$((RANDOM % 144)) hour ago" | sed 's/ /T/' | sed 's/\+.*/Z/');`
1. `cat components/ingest-service/examples/actions/version_cookbook_create.json | jq --arg rfc_time "$rfc_time" '.recorded_at = $rfc_time' | send_chef_data_raw lb`
1. …
> Adding the cookbook_artifact_version event type to the event feed

- components/automate-ui/src/app/pages/notifications/notifications.component.ts
- components/automate-ui/src/app/types/types.ts
Before it being used as up/down, which then sets the toggles arrows out of sync with the actual sort direction. So Updated the code and added default case scenario in Notification list table.
https://github.com/chef/automate/issues/3837
Updated The toggle arrows to stay in sync with the sort direction.
```
STEP 1
STEP 2
$npm run serve:hab
```
1. git fetch origin Amol/chef_sort_toggle
2. build components/automate-ui [Above steps for reference.]
3. Go to Settings tab >> Notification Tab.
4. Click on `Notification list` >> Create Notification >> …
> Updated toggle sort in Notification table.

- components/automate-ui/src/app/entities/layout/layout.facade.ts
- components/automate-ui/src/app/page-components/event-feed-table/event-feed-table.component.scss
- components/automate-ui/src/app/ui.component.html
- components/automate-ui/src/styles.scss
when a project update is in progress it takes up a 54 px at the bottom of the screen. We've got a few right panel issues with this panel.
https://app.zenhub.com/workspaces/ui-team-5cba23a3b14fdc05970c8f87/issues/chef/automate/3576
hides information, we should either add a scroll bar or some extra space to the bottom of those panels so folks can access all of the information.
export DEVPROXY_URL=localhost
load compliance data
start a project update
navigate to compliance > reports > nodes > some node > scan history
notice you cannot scroll all the way to the bottom
> Automate-3576 right panel + bottom project banner issues

- components/data-feed-service/server/server.go
- components/data-feed-service/service/data-feed-service.go
- components/data-feed-service/service/data-feed-service_test.go
#3954 
Conservative code added to prevent panic when casting nil from interfaces when building the node data for the data-feed. Node data generated by chef-load is not fully populated, as a result there were some panics when casting nil values when the data-feed tries to build data for the node. Code has been updated and unit tests added to prevent such a panic.
Also tested using a chef-load configuration similar to #3954, just less nodes and no panic occurred.
> The data feed service breaks when used with chef-load and compliance only data #3954

- components/compliance-service/ingest/pipeline/compliance.go
- components/compliance-service/ingest/pipeline/processor/profile.go
- components/compliance-service/ingest/pipeline/processor/report.go
- components/compliance-service/ingest/server/compliance.go
notifications service was receiving reports with values missing, such
as impact. we realized hte reason for this is that when we added logic to allow
for smaller, more compact reports to be ingested, we forgot to move the call
to notifications client further down the process to after we glue all
the information back together again.
https://github.com/chef/automate/issues/3994
running a scan job with critical control failures triggers the critical control failure notification
set up a notification in automate for inspec control failures
get a vanilla vm going
run a scan job on it (use linux sec baseline), see the notification
> send reports to notifications after we have glued them back together

- components/config-mgmt-service/docs/rollout-metadata-collection-design.md
Adds a design/ADR type doc I have shared internally to the repo so we can reference it in pull requests/issues/etc.
#3695
> Add design doc for metadata collection to config mgmt repo

- components/compliance-service/reporting/relaxting/reports.go
- components/compliance-service/reporting/relaxting/reports_test.go
from the customer: "When using the 'Control Tag' filter in the Compliance tab of Automate, no output is generated when exporting to .csv."
https://getchef.zendesk.com/agent/tickets/25517
After some investigation I realized this was the case only for tags that used the "no value" option (or empty string) for the values. We were incorrectly matching when the values were empty and since no matches were found, only returning profile/node info from the report and no controls.
This fixes that issue by resolving the matching of null value for the tag key in es with the record of the empty string value for the tag val in the api
https://getchef.zendesk.com/agent/tickets/25517
https://github.com/chef/customer-bugs/issues/205
filtering the reports …
> fix tag filter matching logic to recognize null val

- .studio/tooling
Add the oldest date tag that contains a commit to the output of `channel_contains_commit. The output is (see last line)
```
[68][default:/src:0]# channel_contains_commit 57577936c94209bb787d8e6e7012b76ec108c79b
fatal: Not a valid commit name 277666461ff0e196bee3f81dad31b858309c06b5
dev: ✗
acceptance: ✓
current: ✓
Oldest tag containing commit: 20200408145843
```
If no tag contains the commit, we don't print the last line.
1. checkout this branch
1. either start a new hab studio or run `source /src/.studio/tooling` in an existing one
1. run `channel_contains_commit` against a commit that is included in a tag and note that the output contains the tag in the last line, e.g.
```
[68][default:/src:0]# channel_contains_commit 57577936c94209bb787d8e6e7012b76ec108c79b
fatal: Not a valid commit …
```
> Supply oldest date tag in `channel_contains_commit` output

- components/automate-chef-io/content/docs/on-prem-builder.md
- integration/tests/product_dev.sh
Make it explicit that the on-prem Builder API endpoint to use with the Habitat command-line tools is `/bldr/v1`.
> Specify the on-prem Builder API endpoint

- components/automate-chef-io/content/docs/on-prem-builder.md
When copying the cert file the extention was misspelled to "/hab/cache/ssl/{{< example_fqdn "automate" >}}.crt".
> Adding missing 'e' to the On-prem setup

- api/config/erchef/config_request.go
- components/automate-cli/cmd/chef-automate/migrate_from_v1.go
- components/automate-deployment/a1-migration/docker-compose-services.yml
- components/automate-deployment/pkg/a1upgrade/a1config.go
- components/automate-deployment/pkg/a1upgrade/a1config_test.go
- components/automate-deployment/pkg/a1upgrade/a1upgrade.go
- components/automate-deployment/pkg/a1upgrade/generate_cfg.go
- components/automate-deployment/pkg/a1upgrade/generate_cfg_test.go
- components/automate-deployment/pkg/a1upgrade/testdata/chef-server-running.json
- components/automate-gateway/gateway/clients.go
- components/automate-gateway/gateway/services.go
- components/automate-gateway/pkg/nullbackend/backend.go
- tools/credscan/credscan.go
Customers migrating from Automate 1 with an embedded Chef Infra Server noticed that configuration options they had previously set did not get migrated.
This change migrates relevant Chef Infra Server configuration.
> [a1-upgrade] migrate infra server config

- components/automate-ui/tsconfig.json
Follow-on to Angular 9 template type checking enablement, this throws the switch on one more check.
This was an easy win--no collateral to fix after turning it on!
PR #3268 Turn on strict Angular checks
PR #3158 Light up an additional typescript template check
`ng build` reports no errors or warnings
NA
> Light up typescript check: strictDomLocalRefTypes

- .expeditor/verify.pipeline.yml
- components/automate-cds/server/root.go
Adding the automate-cds service's unit and static tests to buildkite.
https://github.com/chef/automate/issues/3913
Check that the unit tests are in buildkite.
> Automate CDS adding unit test to buildkite

- components/automate-ui/src/app/entities/desktop/desktop.actions.ts
- components/automate-ui/src/app/entities/desktop/desktop.effects.ts
- components/automate-ui/src/app/entities/desktop/desktop.model.ts
- components/automate-ui/src/app/entities/desktop/desktop.reducer.ts
- components/automate-ui/src/app/entities/desktop/desktop.requests.ts
- components/automate-ui/src/app/entities/desktop/desktop.selectors.ts
- components/automate-ui/src/app/modules/desktop/daily-check-in/daily-check-in.component.html
- components/automate-ui/src/app/modules/desktop/daily-check-in/daily-check-in.component.ts
- components/automate-ui/src/app/modules/desktop/dashboard/dashboard.component.html
- components/automate-ui/src/app/modules/desktop/dashboard/dashboard.component.ts
- components/automate-ui/src/app/modules/desktop/desktop-detail/desktop-detail.component.html
- components/automate-ui/src/app/modules/desktop/desktop-detail/desktop-detail.component.scss
- components/automate-ui/src/app/modules/desktop/desktop-detail/desktop-detail.component.ts
- components/automate-ui/src/app/modules/desktop/insight/insight.component.html
- components/automate-ui/src/app/modules/desktop/insight/insight.component.scss
- components/automate-ui/src/app/modules/desktop/insight/insight.component.ts
- components/automate-ui/src/app/modules/desktop/top-errors/top-errors.component.html
- components/automate-ui/src/app/modules/desktop/top-errors/top-errors.component.scss
- components/automate-ui/src/app/modules/desktop/top-errors/top-errors.component.ts
- components/automate-ui/src/app/modules/desktop/unknown-desktop-duration-counts/unknown-desktop-duration-counts.component.html
- components/automate-ui/src/app/modules/desktop/unknown-desktop-duration-counts/unknown-desktop-duration-counts.component.scss
- components/automate-ui/src/app/modules/desktop/unknown-desktop-duration-counts/unknown-desktop-duration-counts.component.ts
This commit wires up the dashboard desktop filtering controls to the cfgmgmt API.
https://github.com/chef/automate/issues/3639
- All desktop dashboard widgets properly link to desktop list subview.
- Filter/counts at top of desktop list subview display correct info and updates desktop list when toggled.
- Start all services and UI
- Have some data to look at in the dashboard:
```
for _ in {1..50}; do m=$((RANDOM % 4)); n=$((RANDOM % 4)); generate_chef_run_failure_example | jq --arg msg "Error $n occurred" --arg type "Chef::ExampleError$m" '.error.message = $msg | .error.class = $type' | send_chef_data_raw; done
```
- Navigate to `a2-dev.test/desktop`
> Add desktop filtering to desktop managment view

- components/automate-builder-api/habitat/plan.sh
We released a new version of `habitat/builder-api` to the stable channel on 2020-07-07.
This change pins the version. No changes to `builder-api-proxy`.
Signed-off-by: Jeremy J. Miller <jm@chef.io>
> bumping habitat/builder-api pin due to new release

- .expeditor/config.yml
- CHANGELOG.md
This reverts commit 37598f60ef225d49b63415e4861a9b998b9082b9.
Having a VERSION file with semantic versioning is required even
for the basic changelog management workflow, so unfortunately we
will not be able to use as-is.
I will coordinate with releng to see if there is a workaround,
reverting to unblock.
> Revert "add a changelog to the repo using expeditor (#4053)"

- components/automate-elasticsearch/habitat/config/elasticsearch.yml
- components/automate-elasticsearch/habitat/plan.sh
We ship elasticsearch with xpack. While we disable it, it still seems to
run some of the binaries (maybe enough to know that its disabled?). We
can just remove the plugins entirely.
> Remove xpack plugins from elasticsearch

- .expeditor/create-manifest.rb
The new build no longer brings in any xpack stuff
> Update Elasticsearch pin

- components/automate-ui/src/app/entities/cookbooks/cookbook-details.model.ts
- components/automate-ui/src/app/helpers/infra-proxy/collapsible-list-mapper.ts
- components/automate-ui/src/app/modules/infra-proxy/cookbook-details/cookbook-details.component.html
- components/automate-ui/src/app/modules/infra-proxy/cookbook-details/cookbook-details.component.scss
- components/automate-ui/src/app/modules/infra-proxy/cookbook-details/cookbook-details.component.spec.ts
- components/automate-ui/src/app/modules/infra-proxy/cookbook-details/cookbook-details.component.ts
Introduced Content tab on cookbook details page view.
Mock up : https://www.sketch.com/s/f20922a3-b546-4ef0-8031-6f7f02394ea9/a/rvvbkP
Fixes: #3735 
In Cookbook details page of infra view we have introduced content tab where content details are shown using collapsible tree UI
1. build components/automate-ui
2. To add data https://github.com/chef/automate/blob/master/dev-docs/adding-data/adding_test_data.md#adding-data-to-infra-views
3. Go to Infrastructure tab >> Chef Servers its under Chef-Server feature flag.
4. Click on `Server list` >> `Organisation list` >> `Cookbooks` >> then click on any of the data bag list item >> `Content`
> Cookbook details content tab

- components/automate-chef-io/data/docs/api-static/03-tags.swagger.json
- components/automate-chef-io/data/docs/api_chef_automate/event_feed/event_feed.swagger.json
- components/automate-gateway/api/event_feed/event_feed.pb.go
- components/automate-gateway/api/event_feed/event_feed.proto
- components/automate-gateway/api/event_feed/event_feed.swagger.json
- components/automate-gateway/api/event_feed/request/event.pb.go
- components/automate-gateway/api/event_feed/request/event.proto
- components/automate-gateway/api/event_feed/request/eventstrings.pb.go
- components/automate-gateway/api/event_feed/request/eventstrings.proto
- components/automate-gateway/api/event_feed/response/event.pb.go
- components/automate-gateway/api/event_feed/response/event.proto
- components/automate-gateway/api/event_feed_event_feed.pb.swagger.go
Adding api docs for event feed bits.
n/a
event feed api calls are documented
```
make serve
http://localhost:1313/docs/api/#operation/GetEventFeed
```
> api docs: add docs for event feed

- components/automate-chef-io/content/docs/backup.md
- components/automate-chef-io/content/docs/install.md
- components/automate-chef-io/content/docs/restore.md
- tools/credscan/credscan.go
Address assorted issues where users are either not finding information that is in the backup/restore docs, or expecting information to be there that is not.
1. Split the backup & restore page into a page for backup and a page for
restore. I have a wild theory, based on questions we were seeing, that people were getting tired of reading by the time they got to the restore section of the original single page doc. If someone has evidence for or against, I would be happy to hear it.
2. Signpost the external elasticsearch backup configuration docs as
being for backing up external elasticsearch, as distinct from backing up
all of Automate.
3. Add words around questions that come up frequently enough to seem
worth mentioning: the Automate backup mechanism creates a backup of all
data in all …
> Reorganize backup and restore pages

- components/automate-chef-io/content/docs/infra-server.md
Signed-off-by: Sean Horn <sean_horn@chef.io>
Update the standard installs that can be changed to reflect the 4MB GRPC limit.
This max report size applies to the allowable chef-client and Compliance profile reports proxied through a Chef Infra Server.
Proactively prevent 413/429 problems during report sending.
> 4MB report size limit for A2-installed Chef Infra Server

- components/automate-ui/src/app/entities/environments/environment.model.ts
- components/automate-ui/src/app/modules/infra-proxy/environment-details/environment-details.component.html
- components/automate-ui/src/app/modules/infra-proxy/environment-details/environment-details.component.ts
on the environment details page cookbook constraint tab data is not showing I have fixed the UI for this.
https://github.com/chef/automate/issues/4003
I have added some changes to fix this page UI to show the cookbook constraint tab where we can show the list of cookbooks with name, operator and version.
```
STEP 1
STEP 2
Go to Infrastructure tab >> Chef …
```
> Fixed Environment detail page UI to show cookbook constraints

- components/automate-minio/habitat/config/secrets
- components/automate-minio/habitat/hooks/run
- components/automate-minio/habitat/plan.sh
- integration/tests/backup_ontop.sh
If you were to take a backup of builder, then on another machine, install automate + builder, and restore the backup, it would fail because we'd change the minio secret. Minio doesn't like this because it encrypts config with that secret now. We don't actually care about that config, so this PR detects that case and blows away the config
> Fix ontop backups for builder

- components/event-feed-service/pkg/integration_test/feed_counts_test.go
- components/event-feed-service/pkg/integration_test/feed_test.go
- components/event-feed-service/pkg/persistence/feed-elastic.go
- components/event-feed-service/pkg/server/feed.go
- components/event-feed-service/pkg/server/server.go
Adding project filtering for the GetFeedSummary endpoint for the event-feed-service. This is the second of the three endpoints remaining that need project filtering. Project filtering is only used for chef-server events which are not added yet.
#444 
1. `build components/event-feed-service && start_all_services`
1. Add a project named "project9"
1. Add a project named "project3"
1. Add a chef-server event tagged with "project9" run `event_feed_add_event` 
1. Create a profile event by adding a profile from the "Available" section here https://a2-dev.test/compliance/compliance-profiles
1. Go to the event feed page and filter for project3 only. Ensure that the "Total events" is 1 like below.
1. Then filter for projects9 only. Ensure the "Total events" is 2.
> Event-feed GetFeedSummary project filtering

- components/event-feed-service/pkg/integration_test/feed_timeline_test.go
- components/event-feed-service/pkg/persistence/feed-elastic.go
- components/event-feed-service/pkg/persistence/store.go
- components/event-feed-service/pkg/server/feed.go
- components/event-feed-service/pkg/server/server.go
Adding project filtering for the GetFeedTimeline endpoint for the event-feed-service. This is the last of the three endpoints that need project filtering. Project filtering is only used for chef-server events which are not added yet.
#444 
1. `build components/event-feed-service && start_all_services`
1. Add a project named "project9"
1. Add a project named "project3"
1. Add a chef-server event tagged with "project9" run `event_feed_add_event` 
1. Create a profile event by adding a profile from the "Available" section here https://a2-dev.test/compliance/compliance-profiles
1. Go to the event feed page and filter for project3 only. Ensure that only the profile "create" icon is on the event feed guitar string like below. 
1. Then filter for projects9 only. Ensure the both events are …
> Event Feed timeline project filtering

- api/config/erchef/config_request.go
- components/automate-chef-io/content/docs/infra-server.md
- components/automate-cs-oc-erchef/habitat/default.toml
Set the default max report size for chef-client and compliance profile reports proxied through an infra server to match the 4MB GRPC limit.
> Increase default max report size for infra server

- .studio/event-feed-service
- components/event-feed-service/pkg/feed/feed.go
- components/event-feed-service/pkg/integration_test/feed_test.go
- components/event-feed-service/pkg/persistence/feed-elastic.go
- components/event-feed-service/pkg/persistence/store.go
- components/event-feed-service/pkg/server/feed.go
Adding Chef Infra Server and Chef Infra Server Organization fields to the event-feed-service. This allows these fields to be set from an event. This also allows these fields to be filtered on.  
#444
1. `build components/event_feed_service && start_all_services`
1. Add an event with Chef Infra Server "chef.example.com" and Chef Organization "1st Ranger Battalion" with `event_feed_add_event`
1. Add a profile event by going to https://a2-dev.test/compliance/compliance-profiles and adding one of the available profiles. 
1. Go to https://a2-dev.test/dashboards/event-feed and ensure there are two events. 
1. To test the Chef server filter go to https://a2-dev.test/dashboards/event-feed?chef_server=chef.example.com. Ensure only the environment event is shown not the profile event.
1. To test …
> Adding chef server and orgs from events

- components/automate-deployment/pkg/target/local_target.go
Our current code assumes hab user and group are local and does not work
if those existed in say ldap.
Your way of making it work is exporting the
`CHEF_AUTOMATE_SKIP_HAB_USER` environment variable.
```
CHEF_AUTOMATE_SKIP_HAB_USER=true chef-automate deploy
```
> Add way to skip hab user/group creation

- components/automate-elasticsearch/habitat/config/elasticsearch.yml
- components/automate-elasticsearch/habitat/plan.sh
We were bringing in core/elasticsearch and it had binaries that were
pointing at the wrong versiosn of things. This was fixed by removing
xpack in #4051, however doing that breaks the deprecated elasticsearch
clustering.
This PR undoes #4051 and instead creates a ES package with working
binaries.
> Build ES package in our plan.sh

- .expeditor/announce-acceptance.sh
only announce acceptance promotion in a2-release-coordinate
> only announce acceptance promotion in a2-release-coordinate

- .expeditor/upload-files.sh
- components/automate-deployment/README.md
This reverts commit 372a272ecda24e78451a2b988718de942929a627.
reverting this as promised. we want license scout running
> Revert "Disable license scout in upload-files.sh (#4100)"

- .expeditor/license_scout.sh
- components/automate-deployment/README.md
This reverts commit e8684cce1a1d02e95ea9429896f9793d56a37b53.
We think we know what the problem is. Don't need the extra
logging anymore
> Revert "verbose logging `npm install` in license_scout.sh (#4097)"

- components/automate-chef-io/content/docs/node-integrations.md
- components/automate-chef-io/content/docs/profiles.md
- components/automate-chef-io/content/docs/reports.md
The InSpec docs have migrated from inspec.io/docs. This updates links to InSpec docs to `docs.chef.io/inspec/<page>`
> Update links to inspec docs

- components/backup-gateway/habitat/hooks/run
minio uses the access and secret key to encrypt its config. We do
not need this. We work around this by storing those values in our
tmp directory that gets put in the folder.
Then, when we start up the backup gateway, we can check for that
file. If it exists, we tell backup-gateway that it should use those
values.
If we were not to do this, then it would be impossible to have 2
automates looking at a shared network drive.
This is a best effort thing. If the Invalid credential persists,
the best thing that can be done is to turn automate off, remove the
.tmp directory in the backups, and turn automate back on.
> Fix Invalid credential in backup gateway

- components/automate-chef-io/layouts/_default/data-cli.html
Fixes the "See Also" relative links in the data-cli.html template.
`make serve`
Go to localhost:1313/docs/cli-chef-automate/
> Fix "See Also" links in chef-automate CLI page

- components/automate-ui/src/app/modules/infra-proxy/org-details/org-details.component.html
Official spelling of `Policy Files` is actually `Policyfiles` so as per that convention changed tab label.
Fixes: #4084 
Changed `Policyfiles` tab label in infra view ui
make serve
Navigate to Infrastructure >>> Chef Servers >>> Click on one of server from list >>> Click on one of the Organization from the list >>> check the `Policyfiles` tab label.
- [ x ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ x ] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).
> Policyfiles label change

- .expeditor/generate-automate-cli-docs.sh
We should no longer require building from something that looks like a
GOPATH. We are removing this to reduce the number of possible causes
of the build system issues we are investigating.
> ci: don't setup GOPATH in generate-automate-cli-docs.sh
