chef/automate

components/automate-builder-api-proxy/habitat/plan.sh, components/automate-cs-nginx/habitat/plan.sh, components/automate-elasticsearch/habitat/plan.sh, components/automate-es-gateway/habitat/plan.sh, components/automate-postgresql/habitat/plan.sh, components/automate-ui/habitat/plan.sh, components/compliance-service/habitat/plan.sh, integration/tests/ldap_hab_user.sh
Be explicit about dependencies on coreutils
We want to depend on coreutils as it will be able correctly look up UIDs
and GIDs when it comes to LDAP.
Don't use busybox
Follow up to #4110
Fixes #4105
=> Be explicit about dependencies on coreutils

.expeditor/generate-automate-api-docs.sh, components/automate-chef-io/.gitignore, components/automate-chef-io/Makefile, components/automate-chef-io/static/api-docs/all-apis.swagger.json
This will commit the all-apis.swagger.json file instead of generating it when Hugo builds the automate site. It also updates the expeditor config to add future changes to that file.
I'm migrating the automate documentation from `automate.chef.io` to `docs.chef.io`. It will be much easier for me to grab the all-apis swagger file from the `chef/automate` repo than it will to grab several swagger files and then generate the all-apis swagger file when Hugo builds the docs site from `chef-web-docs`.
=> Add docs api swagger file

components/automate-ui/src/app/services/run-history-store/run-history.store.ts
Seems date filters `startDate` and `endDate` updated the list items as well as status count. Its required to add a status type filter to also update its count. 
Fixes: #995
- Run status filter now gets updated when it clicked.
Steps to build
- `build components/automate-ui-devproxy`
- `cd components/automate-ui`
- `make serve`
Steps to test:
- Configure chef server over data collector.
- Bootstrap a node.
- Go to Dashboard -> Client Runs -> Node details > Run History  
- Run chef-client on node multiple times.
- Click on Count filter.
Before fix:
After fix:
=> [client-runs] Fix run history counts issue

.expeditor/config.yml
I moved this to the post-promote pipeline. For some reason when I did
this I thought this was running post-build already, but I think I just
confused myself. Anyway, it should be fine wherever.
=> ci: don't run code_coverage post merge

components/automate-deployment/pkg/bootstrapbundle/bundle_creator.go, integration/tests/ldap_hab_user.sh
When creating the abb, we use the golang tar library. It could fail to determine the user and group names for a file if those are not local users. This PR uses our user library to do the UID/GID -> name translation if the tar library is unable to
=> Manually lookup user and group when creating abb

.expeditor/nightly.pipeline.yml, .expeditor/verify_private.pipeline.yml
This brings us from 114 to 107 jobs between verify and
verify_private. It is barely a dent. But, it is a start I suppose.
=> ci: move more things to the nightlies

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profile/reporting-profile.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profile/reporting-profile.component.scss
Numbers were stacking vertically due to insufficient space in the compliance reports profile table, this branch addresses this problem by accommodating for more space.
Fixes: https://github.com/chef/automate/issues/4107
Large numbers are accomodated for in compliance profile table
make serve
navigate to: https://a2-dev.test/compliance/reports/profiles
note: if you do not have any compliance profiles - run `load_compliance_reports` in hab studio.
click on an individual profile
you may need to manually plug in large numbers in order to see that the numbers fit.
=> Accomodate more space for numbers

.expeditor/config.yml
The old way has been deprecated. This is the new way.
=> ci: use subscription to promote workload

.expeditor/config.yml
in https://github.com/chef/automate/pull/4146/files @stevendanna did some work to transition us to the subscription model. it looks like this requires a couple more changes to get it all the way transitioned. we need to get the promotion from dev -> acceptance through so we've decided to try to roll with the backwards compatible "actions" instead of trying to transition to the subscription model right away. we'll circle back around after.
=> ci: try using actions for expeditor promote

.expeditor/promote-hab-pkgs-and-cli.sh
Add habitat auth token to use when promoting habitat packages to the correct channel.
Signed-off-by: Nathaniel Kierpiec <nkierpiec@chef.io>
`HAB_AUTH_TOKEN` does not by default get exported by expeditor. Need to go get that so we can promote habitat packages.
- [x ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [x ] All commits have been signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).
=> Add habitat auth token to use when promoting habitat packages to the correct channel.

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.scss, ec2/Vagrantfile
This is MVP UI change for this backend improvement: https://github.com/chef/automate/pull/4131
@jonong1972 is working into some designs to bring this together with the failure `status_message` fields when profiles inside a report fail.
To test, rebuild `components/automate-ui` and ingest a report, like the one from the tests of https://github.com/chef/automate/pull/4131 
I left the boxes with the zero control counts to further highlight that this report is empty/abnormal and needs investigation.
Screenshot of the error div here:
=> Compliance UI make use of root status_message

api/config/scripts/grpc.sh, components/automate-deployment/scripts/grpc.sh
The protobuf available in Habitat was just upgraded. This bumps the
version we expect in these scripts to match.
I've test this with a complete regen locally and it didn't produce any
changes.
=> protos: bump protoc to 3.12.3

components/automate-ui/src/app/app-routing.module.ts, components/automate-ui/src/app/entities/cookbooks/cookbook-details.selectors.ts, components/automate-ui/src/app/entities/cookbooks/cookbook-versions.selectors.ts, components/automate-ui/src/app/entities/orgs/org.selectors.ts, components/automate-ui/src/app/modules/infra-proxy/cookbook-details/cookbook-details.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/cookbook-details/cookbook-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/data-bags-details/data-bags-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/environment-details/environment-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/infra-role-details/infra-role-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/org-details/org-details.component.ts
To follow consistent route param pattern through out the application. Added some changes for infra proxy routes.
Fixes: #3924 
Infra proxy route inconsistency resolved. `orgid` is replaced with `org-id` and `cookbook_name`  is replaced with `cookbook-name`. 
make serve
navigate to https://a2-dev.test/infrastructure/chef-servers
=> Infra proxy route consistency

components/automate-ui/src/app/entities/desktop/desktop.model.ts, components/automate-ui/src/app/modules/desktop/check-in-time-series/check-in-time-series.component.html, components/automate-ui/src/app/modules/desktop/check-in-time-series/check-in-time-series.component.spec.ts, components/automate-ui/src/app/modules/desktop/check-in-time-series/check-in-time-series.component.ts, components/automate-ui/src/app/modules/desktop/daily-check-in/daily-check-in.component.html, components/automate-ui/src/app/modules/desktop/daily-check-in/daily-check-in.component.spec.ts, components/automate-ui/src/app/modules/desktop/daily-check-in/daily-check-in.component.ts, components/automate-ui/src/app/modules/desktop/dashboard/dashboard.component.ts, components/automate-ui/src/app/modules/desktop/desktop.module.ts, components/automate-ui/src/app/modules/desktop/empty-data/empty-data.component.html, components/automate-ui/src/app/modules/desktop/empty-data/empty-data.component.scss, components/automate-ui/src/app/modules/desktop/empty-data/empty-data.component.spec.ts, components/automate-ui/src/app/modules/desktop/empty-data/empty-data.component.ts, components/automate-ui/src/app/modules/desktop/top-errors/top-errors.component.html, components/automate-ui/src/app/modules/desktop/top-errors/top-errors.component.spec.ts, components/automate-ui/src/app/modules/desktop/top-errors/top-errors.component.ts, components/automate-ui/src/app/modules/desktop/unknown-desktop-duration-counts/unknown-desktop-duration-counts.component.html, components/automate-ui/src/app/modules/desktop/unknown-desktop-duration-counts/unknown-desktop-duration-counts.component.spec.ts, components/automate-ui/src/app/modules/desktop/unknown-desktop-duration-counts/unknown-desktop-duration-counts.component.ts, components/automate-ui/src/assets/img/chart.svg
These commits add an 'empty data' state to the desktop dashboard components for when desktop API data is not available.
Closes https://github.com/chef/automate/issues/3335
Desktop empty states display when desktop API endpoints return no data.
- Have a fresh install of Automate with no client runs being reported yet
- Start all services and UI
- Navigate to `a2-dev.test/desktop`
=> Add empty data states to desktop dashboard

components/automate-chef-io/content/docs/saml.md
Some of our customers have been using this for a while now. I've verified that the instructions work, and added it, together with an emphasis on manual signing certificate management, to the docs.
#2887 
There's docs describing how to use Azure AD's SAML with A2.
- `cd docs; make serve` and `open http://localhost:1313/docs/saml/` given that you've gotten all the docs tools installed.
=> docs/content/saml: add Azure AD section

components/automate-ui/src/app/pages/automate-settings/automate-settings.component.html, components/automate-ui/src/app/pages/automate-settings/automate-settings.component.scss, components/automate-ui/src/app/pages/automate-settings/automate-settings.component.ts
By default, the number inputs on data-lifecycle were only large enough to show two digits.  We will now auto update the width of the input upon typing so that the entire number is always visible.
Fixes: https://github.com/chef/automate/issues/4040
Data Lifecycle input values are always visible to the user, regardless of how long.
make serve
navigate to https://a2-dev.test/settings/data-lifecycle
In any/all of the type-able number inputs, type as many valid numbers as you wish and view the input expand/shrink as necessary.
=> Auto update widths of inputs on type

components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.html, components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.scss, components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.spec.ts, components/automate-ui/src/app/components/create-object-modal/create-object-modal.component.ts, components/automate-ui/src/app/pages/project/list/project-list.component.ts, e2e/cypress/integration/ui/settings/project_mgmt.spec.ts
Because teams is a separate service that is dependent on auth,
tying these created teams to policies in the most readable,
maintainable way requires significant effort (using cereal or merging teams into authz), so we are
removing the option for now.
Enter the studio and bring up the UI-- Navigate to "Settings" in the UI, then "Projects". Click "Create Project":
-- there should not be an option to automatically create teams
-- when project is created, there should be no associated teams
=> Removes option to add teams for new project

components/automate-ui/src/app/modules/token/token-list/api-token-list.component.scss
The control menu text in project files was getting ellipsed seemingly randomly.  @susanev hunted down the cause, and it turned out a css selector was leaking from the api-tokens page.
The fix in this branch encapsulates those selectors so they no longer leak.
Fixes: https://github.com/chef/automate/issues/3983
Text inside control menus is not longer being cut off and ellipsed.
make serve
on a clean branch to repro the issue
- navigate to api tokens
- create a token
- open the token control menu
- navigate to projects
- create a project
- open that menu and it will have the `...`
hard refresh, open projects again notice no `...`
then repeat above and it should show the `...` again
on this branch
Run through the repro sets and you …
=> Prevent ellipsis-ing of control menu text

components/automate-ui/src/app/app-routing.module.ts, components/automate-ui/src/app/app.module.ts, components/automate-ui/src/app/pages/node-noruns-details/node-noruns-details.component.html, components/automate-ui/src/app/services/node-details/node-norunid-resolver.service.spec.ts, components/automate-ui/src/app/services/node-details/node-norunid-resolver.service.ts, components/automate-ui/src/app/services/node-details/node-runs.service.ts
Navigate to client node detail page only with node-id by making run-id as optional, added route for node-id and its resolver service, now in route resolver service we have find out `run-id` of specific `node-id` if run-id exists then redirect to node details route if not then redirect to missing run page.
Fixes: #3261 
1. Route created  for `node-id` with optional `run-id`
2. Breadcrumb redirection issue fixed in missing run page
make serve
Navigate to Infrastructure >>> Client Runs >>> now add existing node-id in route ( a2-dev.test/infrastructure/client-runs/`node-id` )
expectations if `run-id` exists for node then it will redirect to node-details else it will redirect to missing-runs route.
=> Client runs node detail with optional run-id

components/data-feed-service/server/server.go, components/data-feed-service/service/credentials.go, components/data-feed-service/service/credentials_test.go, components/data-feed-service/service/data-feed-aggregate-task.go, components/data-feed-service/service/data-feed-poll-task.go, components/data-feed-service/service/data-feed-poll-task_test.go, components/data-feed-service/service/data-feed-service.go, components/data-feed-service/service/data-feed-service_test.go
The datafeed primary method of correlating infra node and compliance node data uses ip address.
Cloud resources may not have an ip address or any corresponding node data. Thus the ip address is "" in the code for a cloud resource, since this is used as a key in a map all cloud compliance reports map to the same key which means only a single report, the last aggregated is included in the feed.
For cloud resources the node_id can be used to identify reports for different nodes. This update uses a resourceId which can be the ip address or the node_id for a compliance report. The resourceId is resolved as ip address, then node_id.
For cloud resources the "node" section in the feed is irrelevant and has been dropped. this is only for cloud resources.
All other functionality remains the same. …
=> Support compliance reporting for cloud resources

components/applications-service/cmd/applications-service/commands/serve.go, components/applications-service/integration_test/suite_test.go, components/applications-service/pkg/storage/postgres/db.go, components/config-mgmt-service/backend/postgres/schema/sql/02_add_rollouts.up.sql, components/config-mgmt-service/backend/postgres/schema/sql/03_add_rollouts_author_initiator.up.sql, components/config-mgmt-service/backend/postgres/schema/sql/04_rollouts_unique_exclude_constraint.up.sql, components/config-mgmt-service/backend/postgres/test_helpers.go, lib/db/migrator/migrator.go
In https://github.com/chef/automate/pull/4183 we fixed an error in the migrator that was re-running migrations in multiple front-end cluster topologies, but we still try to forcibly redo migrations if they fail and leave a dirty schema state. So it's best if our migrations are able to re-run. This PR adds a function to our migrator library which drops all the data in the database, then runs a service's migrations all the way through twice. In addition to checking that migrations are idempotent, this approach makes it convenient to develop new migrations, you can keep re-running the integration tests and any bad state created by mistakes gets cleaned up.
I only modified the two services I know well in this pass, it should be pretty easy to add to others if we like. …
=> Test for Idempotent Schema Migration

.expeditor/buildkite/cypress.sh, scripts/get_secrets.sh
the cypress tests that run for each pull request use the `cypress:run`
command instead of `cypress:record`. the difference between the two is
that `record` sends the artifacts to the cypress.io cloud dashboard
and run only saves them locally. our test logic already saves the
artifacts to buildkite in the event of a failure, where everybody has
access to the recording.
note: the deploy tests are currently turned off until we can fix them
and this change will only effect these runs once they're re-enabled.
=> cypress: store deploy recordings only in buildkite

components/nodemanager-service/tests/mgrtesthelpers/mgr-test-helpers.go, components/nodemanager-service/tests/nodes_integration_test.go, components/nodemanager-service/tests/unfinished/nodes_integration_test.go
the nodemanager functionality started out as part of scan jobs,
and we still have some nodemanager tests under the compliance service
api tests. this work moves those to nodemanager, translating them to go
along the way, so all our nodemanager tests can be in one place, easy to find and
execute.
https://github.com/chef/automate/issues/4215
tests found in 25 and 26 nodes spec 
are transferred to nodemanager test suite
=> move ruby nodemanager tests out of compliance and translate to go

.studio/common, buf.yaml
This PR integrates `buf check lint` into our protobuf build. For now, `buf` is compelled to pass by configuring it to ignore a lot of rules, many of which we want to enforce. I will get to that in one or more follow-up PRs.
#4203
* Enter the studio
* `lint_all_protobuf_components`
To see it fail, you can modify `buf.yaml` and comment out some of the ignore directives. 
Also, I made #4222 to verify that lint failures fail PR builds.
=> Lint Protos with Buf (part 1)

.bldr.toml, components/ingest-service/grpc/grpc.go, components/ingest-service/migration/migration.go
For ingest-service elasticsearch migrations, we added PostgreSQL lock to prevent Automate HA frontend with multiple ingest-services from running the same migration at the same time.
#4201 
1. `start_all_services`
1. While automate is starting, change this line from "false" to "true". https://github.com/chef/automate/blob/c0a74e9df9db459d2d5b2fa9f8b74ca1d0c2386d/components/ingest-service/migration/migration.go#L200
1. Add the below code to here https://github.com/chef/automate/blob/c0a74e9df9db459d2d5b2fa9f8b74ca1d0c2386d/components/ingest-service/migration/migration.go#L153
```
log.Info("Starting migration")
time.Sleep(time.Minute)
log.Info("Finished Migration")
```
1. Setup tmux with 
```
cat > /root/.profile <<'endmsg'
if [ -f /tmp/tmux ]; then
source /src/.studiorc
fi
touch /tmp/tmux …
```
=> Ingest service Elasticsearch migration lock

components/automate-ui/src/app/helpers/auth/regex.ts, components/automate-ui/src/app/modules/policy/add-members/policy-add-members.component.html
The regex we are using to constrain entries for policy members (`\w`) includes letters and digits--and the underscore. Just updating the text and code to note this.
The illustration shows the error pop-up upon entering an illegal character--an exclamation mark. But note that earlier in the same input is an underscore, which is legal, so it should be mentioned in the message.
NA
Corrected error message.
Navigate to Settings >> Policy >> (specific policy) >> Members >> <kbd>Add Members</kbd> >> <kbd>Add Member Expression</kbd>
Select `Team`
Select `Local`
Type a name with an underscore and note there is no error.
Type a name with an exclamation point and note the revised error text.
=> Correct error message for adding policy members

components/automate-ui/src/app/pages/+compliance/+profile/+profile-overview/profile-overview.component.html, components/automate-ui/src/app/pages/+compliance/+profile/+profile-overview/profile-overview.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+profile/+profile-overview/profile-overview.component.ts
Signed-off-by: samshinde <ashinde@chef.io>
Fixed UI error message when a user is not authorized to create a profile
https://github.com/chef/automate/issues/3216
Updated the error message from  `Failed to install profile. Please try again later.` to  `You are not authorized to create compliance profiles.` only if we got the Unauthorized response.
- Sign in as `viewer` with the password `chefautomate`
- Navigate to compliance/profiles, then the available tab
- Use one of the get buttons, and notice the error
- api response is `subject ["team:local:viewers" "user:local:viewer"] is not authorized to "compliance:profiles:create" resource "compliance:profiles:viewer"`
- The updated UI error message is: `You are not authorized to create compliance profiles.` only if we got the Unauthorized …
=> Updated error message when user is not authorized to create profile.

scripts/auth_resources.sh, scripts/user_policies.sh
Original version of this script was presented on the Chef blog, but I think it makes sense to have it generally available, since I have been updating it "off the record".
https://blog.chef.io/now-what-were-those-permissions-for-this-user-again/
1. Source the file (`source scripts/auth_resources.sh`).
2. Define env vars for token and target host. The host could be your local machine (`https://a2-dev.test` or some acceptance box):
```
export TARGET_HOST=https://a2-local-inplace-upgrade-acceptance.cd.chef.co
export TOK=<token value here>
```
There are several small shell functions available: a2policies, a2teams, a2userid, and a2rules.
To see a short summary of what each of those does, invoke the script (rather than source it) with the `-h`option:
```
./scripts/auth_resources -h
```
Here is a …
=> Helper for listing policies for local user

components/automate-ui/src/app/entities/cookbooks/cookbook-details.requests.ts, components/automate-ui/src/app/entities/cookbooks/cookbook-versions.requests.ts, components/automate-ui/src/app/entities/cookbooks/cookbook.requests.ts, components/automate-ui/src/app/modules/infra-proxy/cookbooks/cookbooks.component.ts, components/automate-ui/src/app/modules/infra-proxy/data-bags-list/data-bags-list.component.html, components/automate-ui/src/app/modules/infra-proxy/org-details/org-details.component.ts, components/automate-ui/src/app/services/http/http-client-auth.interceptor.ts
For module like automate infra view we are communicating with chef servers API's that is external API's in that case we don't want session gets expired on getting 401 error, instead of that we need to show user a error notification so that user can take a preventive action for error so we have introduced a `skip-interceptor` header for external API's to ignore chef session logout loop in auth interceptor service on getting 401 error from server.
Fixes: #4137 , #4180 
Shown a authentication error notification on getting 401 error raised from chef servers API's please refer attached screenshot for the same. 
Call infra proxy API which gives 401 error.
=> Chef session logout issue on 401 error raised from chef servers API

components/docs-chef-io/content/automate/infra_server.md
Remove references to max report size in the Infra Server docs; the underlying issue was addressed in https://github.com/chef/automate/pull/4069, and I removed the config settings from the docs but not the references.
=> Remove references to max report size in the docs for the infra server

components/docs-chef-io/content/automate/migrate.md
Broken link on https://automate.chef.io/docs/migrate/ needed fixing. Added a few quick formatting fixes, and a comma or two. This PR corrects content in the correct docs location of `components/docs-chef-io`.
https://github.com/chef/automate/pull/4236
🟢  means go.
`make serve`
Go to: `localhost:1313/automate/`
=> Link fix for Migrate doc

components/chef-ui-library/package-lock.json
A recent PR inadvertently changed from `https` to `http` for a single package in the chef-ui-library.
This reverts that change, as all packages should use `https`.
PR #3940 
All packages in package-lock.json use https.
NA
=> Revert protocol change to es6-promisify package

integration/services/ha_backend/init.sh
The argument parsing in Habitat has changed such that the command we
were using to create the database user actually displayed the
help (because of our use of the `-h` flag intended to be passed to
`psql` but now parsed by hab).  The help output returns an exit code
of 0, meaning that the user went uncreated without an error being
returned by our setup script.
=> ci: fix ha cluster test failures

components/docs-chef-io/content/automate/infra_server.md
Document the configuration to set up data collection for an Automate-deployed Infra Server pointing at an externally-deployed Automate installation.
Fixes #4239.
=> Document data collection from an Automate-deployed Infra Server to an externally-deployed Automate

components/docs-chef-io/content/automate/on_prem_builder.md
Provide an example of specifying an auth token for builder as a bearer token. The question has come up a couple of times recently in internal Slack, so it seems like a good thing to have in docs
For context, see
https://chefio.slack.com/archives/CB31Z9ZT8/p1598035405010400
https://chefio.slack.com/archives/CB31Z9ZT8/p1596475217166300
https://chefio.slack.com/archives/CB31Z9ZT8/p1597511362251800?thread_ts=1596653132.194900&cid=CB31Z9ZT8
=> Document how to access on-prem builder's REST API

components/docs-chef-io/content/automate/saml.md
This tries to add a useful hint to avoid people stumbling over this, as has happened in a recent customer issue.
I'm finding it difficult to describe the Azure UI succinctly; the dropdown that matters is this one:
=> docs: add Azure AD note on SAML NameID setting and transformations

components/automate-ui/src/app/components/resource-dropdown/resource-dropdown.component.scss
Long values in dropdowns should be wrapped, this will occur wherever the dropdown is used, both in a details page and in a create modal.
https://github.com/chef/automate/issues/3916
visit the Settings >> projects/policies
create project or policy - if you have no data then add a project or policy entries with the long name using the create modal.
check the wrapped value in a dropdown - for check this you can go to  Settings >> API tokens then click to `create API token` 
a modal popup will be open and you can see the dropdown values also you can check any API token details page to see a dropdown with long value.
```
STEP 1
[default:/src:0]# …
```
=> Changes to fix long names in drop-down components should be wrapped

components/automate-cs-oc-erchef/habitat/config/sys.config
The verify depth is the maximum number of non-self-issued intermediate
certificates that can follow the peer certificate in a valid
certification path.
By default the depth in Erlang 20.2 is 1 which isn't enough for some common TLS configurations.
The default depth limit in OpenSSL 1.0.2 and 1.1.1 is 100 according to
https://www.openssl.org/docs/man1.0.2/man3/SSL_CTX_set_verify_depth.html
https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_verify_depth.html
Here, we set a depth of 32 which should be more than enough for all
reasonable cases and is in line with what we've set for external
postgresql.
=> erchef: set verify depth for external automate to 32

components/automate-cs-bookshelf/habitat/plan.sh, components/automate-cs-nginx/habitat/plan.sh, components/automate-cs-oc-bifrost/habitat/plan.sh, components/automate-cs-oc-erchef/habitat/config/sys.config, components/automate-cs-oc-erchef/habitat/plan.sh, components/automate-workflow-nginx/habitat/plan.sh
This pulls in a workaround for TLS issues with external automate. The
workaround requires some new configuration with restores the old
behavior where we validate the certificate against the configured CA
but ignore hostname mismatches.
Our hope is to have full hostname checking support when Chef Server
upgrades to Erlang 22.
=> Bump chef-server versions

components/compliance-service/reporting/relaxting/indices.go, components/compliance-service/reporting/relaxting/indices_test.go
There was an edge case in our esIndex computation where, if we had exactly one full year (nothing more, nothing less), we were computing the esIndices to be queried to be an empty string, which would yield not search results.
this pr fixes that.
All original tests pass and new test that tests one full year also passes
=> fix esIndex computation for exactly one fully year selection

components/docs-chef-io/content/automate/restore.md
If you happen to restore to a machine with less memory, your restore will fail unless you adjust Elasticsearch's settings
Signed-off-by: Matt Ray <github@mattray.dev>
=> Adjust RAM settings for Elasticsearch when changing machines docs

.expeditor/generate-automate-api-docs.sh
The last run of this docs script failed with:
```
+++ Action Set Output
[2020-08-31 23:29:32 +0000] action bash:.expeditor/generate-automate-api-docs.sh started
Downloading .expeditor/generate-automate-api-docs.sh from chef/automate:master
fatal: A branch named 'expeditor/generate-automate-api-docs' already exists.
```
The help for `git checkout` says:
```
git checkout -b|-B <new_branch> [<start point>]
Specifying -b causes a new branch to be created as if git-branch(1) were called and then checked out. In this case you can use the --track or --no-track options, which will be passed to git branch. As a
convenience, --track without -b implies branch creation; see the description of --track below.
If -B is given, <new_branch> is created if it doesn't exist; otherwise, it is reset. This is …
```
=> Fix failure of `git checkout -b` running docs gen script

components/automate-ui/src/app/modules/desktop/desktop-detail/desktop-detail.component.html
This commit replaces a hardcoded value that got left in the desktop detail template.
`source_fqdn` is the field used based on https://docs.chef.io/automate/api/#operation/GetNodeRun docs.
=> Replace 'chef server' hardcoded desktop value

.studio/protobuf, buf.yaml
Enables the breaking change detector for protobufs 🎉 
For now, the guidance if we need to sneak a change past is to configure that file as ignored and then revert the config in a later PR.
buf's docs:
* https://buf.build/docs/breaking-overview
* https://buf.build/docs/breaking-configuration
* https://buf.build/docs/breaking-checkers
Breaking change fails in Ci. I'll make a demo PR of this soon. Locally, you can try making breaking changes in api/external protos and `compile_all_protobuf_components` should fail.
=> Enable protobuf breaking change detection

components/automate-ui/src/app/page-components/profile/profile.component.html
This commit adds a Chef patents link to the user profile dropdown menu.
Closes: https://github.com/chef/automate/issues/4220
Aha! Link: https://chef.aha.io/features/SH-231
=> Add Chef patents link

.expeditor/verify_private.pipeline.yml, .studio/data-feed-service, components/data-feed-service/integration_test/api_test.go, components/data-feed-service/integration_test/global_test.go, components/data-feed-service/integration_test/ingest_test.go, components/data-feed-service/integration_test/patch.toml, components/data-feed-service/integration_test/suite_test.go
Adding integration tests for data-feed-service
Initial tests cover the data-feed-service API
=> Initial integration testing for data-feed-service

lib/platform/config/config.go
The previous code produced log messages such as:
pg-sidecar-service.default(O): time="2020-08-24T22:26:00Z" level=error msg="failed to create database" action=create_db
conn_info="postgresql://admin@<readacted>:%!d(string=172.17.0.5)/%!s(int=10145)?<database>%!(EXTRA string=sslmode=verify-ca&sslrootcert=/hab/svc/pg-sidecar-service/config/_a2_platform_external_pg_root_ca.crt)"
db=dex db_database=postgres error="pq: role \"dbuser\" does not exist" role=dbuser user=admin
=> lib/platform: fix bad format string in externalConnURIRenderer

integration/helpers/ssl_filters.jq
The SSL Tester is now asserting that certs should be valid for less than 398 days. The constraints of our internal CA are much different than for normal web use, so we are disabling this check for the internal CA.
=> Dont ssl check cert validity period for internal CA

components/automate-ui/src/app/helpers/auth/authorized.spec.ts, components/automate-ui/src/app/helpers/auth/authorized.ts, components/automate-ui/src/app/pages/project/rules/project-rules.component.html, components/automate-ui/src/app/pages/project/rules/project-rules.component.spec.ts, components/automate-ui/src/app/pages/project/rules/project-rules.component.ts
Users who do not have permission to update projects (`iam:projects:update`) should not be able to see the <kbd>Add Condition</kbd> or <kbd>Save Rule</kbd> buttons on the rule detail view. This PR adds the appropriate introspection guard to those two buttons.
It is guarding the same endpoint (`[/apis/iam/v2/projects/{project_id}/rules/{id}, PUT]`) but done differently for each because of limitations of the architecture. The <kbd>Save Rule</kbd> button is within the `<chef-page>` stencil component. Rather than increase the surface area of that interface, I just leveraged an existing capability: if the button label is empty then the button bar is not displayed. So the `<app-authorized>` functionality is done in code for the <kbd>Save Rule</kbd> button, using the `AuthorizedChecker` …
=> [auth-4300] Add  guards to Save Rule and Add Condition

components/automate-gateway/handler/iam/v2/introspect/introspect.go, components/automate-gateway/handler/iam/v2/introspect/introspect_test.go, components/automate-ui/src/app/pages/project/details/project-details.component.html
Users who have `iam:projects:update` permissions were unable to see the <kbd>Create Rule</kbd> button on the project details page becuase of this incorrect guard:
```
<app-authorized [allOf]="['/apis/iam/v2/projects', 'post']">
```
This PR corrects the guard to this:
```
<app-authorized [allOf]="['/apis/iam/v2/projects/{project_id}/rules', 'post', project?.id]"
```
But that is only a small part of the story of this PR. It turns out that just making that guard change did not do the job--in fact, the <kbd>Create Rule</kbd> button was not showing up at all! This change exposed that automate-gateway was not supporting this introspection call. 
And when I say "this", I mean this single, solitary, unique endpoint. _Any other endpoint would have been fine!_ Go figure...
This could be viewed as …
=> [auth-4300] Correct guard for "Create Rule" button

components/docs-chef-io/content/automate/backup.md, components/docs-chef-io/content/automate/restore.md
* Point links to the (optional) restore config to the restore page instead of the backup page.
* Change the title formerly known as "Backup & Restore" to Backup because Restore is now a separate page.
* Add descriptive section headers for content about setting up/configuring backups under various circumstances.
* Move links to restore sections to the intro.
=> Assorted cleanup to backup and restore pages

components/automate-ui/src/app/modules/infra-proxy/cookbooks/cookbooks.component.html, components/automate-ui/src/app/modules/infra-proxy/cookbooks/cookbooks.component.scss, components/automate-ui/src/app/modules/infra-proxy/cookbooks/cookbooks.component.ts, components/automate-ui/src/app/modules/infra-proxy/org-details/org-details.component.html, components/automate-ui/src/app/modules/infra-proxy/org-details/org-details.component.ts
Introduced a UI of empty state for cookbooks when the admin key is invalid, before empty state UI we were showing empty cookbook list table. As a UX improvement we have introduced a UI for empty cookbooks state and redirection link for `Reset Admin Key` tab.
Fixes: #4244 
Used a common pattern for empty state UI with message and redirection link for `Reset Admin Key` tab, please refer the screenshots for the same.
Call infra proxy API which gives 401 error.
- Before
- After
=> UI for empty state of cookbook when admin key invalid

components/applications-service/pkg/storage/postgres/schema/sql/11_add_denormalized_services_table.up.sql, components/applications-service/pkg/storage/postgres/schema/sql/12_artificial_ids_for_service_groups.up.sql
In 6f8b8332d62cc158471ec55ec2d212a79cbdd177 we modified the applications service integration tests to run the service's schema migrations twice. This is intended to ensure we can rerun a migration if it's stopped by a transient failure. Though I tested it at the time (perhaps I was not testing what I thought I was testing?), I am now seeing new failures that I did not see originally (and have not appeared in Ci).
You can run the following without seeing a failure in the schema migration: 
```
start_applications_service
applications_integration
```
In the studio (no need to build): 
```
start_applications_service
applications_integration
```
=> Fix applications migrations to run correctly twice

components/compliance-service/api/reporting/server/server.go, components/compliance-service/api/tests/07_suggestions_control_tags_spec.rb, components/compliance-service/api/tests/07_suggestions_spec.rb, components/compliance-service/reporting/relaxting/suggestions.go
For controls and control-tags suggestions, we were retrieving 10 suggestions, and then, when "size" was passed into the API call, we were returning the first "size" results.  This was causing some results to come back that seemed imperfect with respect to text string being passed in.  Now we set the search size to the exact amount specified in request and return that amount, yeilding a more predictable result.
=> fix size of contros and contol tags suggestions

components/applications-service/integration_test/services_test.go, components/applications-service/pkg/storage/postgres/services.go
[Apps tab] A customer has requested to be able to filter on only connected services. They want to see if all supervisors that are expected to upgrade have indeed upgraded. Their estate includes systems distributed over sometimes unreliable WAN links, which can become disconnected and not expected to update. Therefore it will be helpful to filter out these disconnected systems to show only the connected ones.
This PR implements filtering by `status:connected` when listing services.
UI Card: #4343
You can filter for only connected services in the Automate API
```
hab pkg install -bf core/curl
hab pkg install -bf core/jq-static
build components/applications-service
applications_populate_database
```
At first all the services are connected, so nothing is filtered out. You …
=> Connected Services Filter (API only)

api/external/secrets/secrets.pb.go, api/external/secrets/secrets.proto, api/external/secrets/secrets.swagger.json, components/automate-gateway/api/secrets.pb.swagger.go, components/secrets-service/dao/secrets.go, components/secrets-service/integration_test/list_secret_test.go
Added filtering by name to the ListSecrets API to help with data-feed-service integration tests.
=> Add name filtering to ListSecrets API

components/automate-ui/src/app/modules/team/team-add-users/team-add-users.component.scss
Signed-off-by: samshinde <ashinde@chef.io>
The `Add Users` button overlaps with the user table on the add-users-to-team modal and changed the height of the table to get a space between them.
#2752 
Add user button overlaps with the user table so added space between them.
1. start Automate + UI
2. navigate to https://a2-dev.test/settings/users and create several users
3. navigate to https://a2-dev.test/settings/teams/editors/add-users
4. you should be able to see the overlap of the buttons with the last row of users 
```
STEP 1
STEP 2
```
=> Resolved Add Users button overlaps with the user table.

components/automate-ui/src/app/ui.component.ts
Console error: hasUserNotifications does not change from its default value until you get projects in an "edits pending" state.
https://github.com/chef/automate/issues/4320
Steps to reproduce the behavior:
Login as admin.
Create a project.
Add a rule to the project.
Observe that the "edits pending" notification bar appears at the bottom of the screen.
Add or edit a rule so that it shows updates pending.
Navigate back to the Projects list (Settings > Projects).
Open the project details for the project.
Observe this error appears in the browser:
`ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: 
Expression has changed after it was checked. 
Previous value for 'attr.hasUserNotifications': 'true'. Current value: 'null'.`
=> Automate-4302 Console error in project notifications

components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.scss
This commit fixes styling bug where the report summary table was growing outside of its parent container and causing a horizontal scrollbar.
**Before**
**After**
=> Fix compliance report summary style bug

components/automate-ui/src/app/entities/rules/rule.effects.ts, e2e/cypress/integration/ui/settings/project_rule_mgmt.spec.ts
Signed-off-by: samshinde <ashinde@chef.io>
After creating a rule, In the Notification bar, it shows the id of the particular rule, not the name so changed it to name.
#1130 
Rule name displayed in the notification instead of the id.
1. visit the Settings >>Projects page
2. create Projects >> create Rule in a particular projects
```
STEP 1
STEP 2
```
=> Added rule name in the notification instead of the id.

components/docs-chef-io/layouts/_default/data-api.html
Using the Hugo asset pipeline could help with 
`Error: Error building site: failed to render pages: render of "page" failed: "/chef-web-docs/_vendor/github.com/chef/automate/components/docs-chef-io/layouts/_default/data-api.html:14:35": execute of template failed: template: _default/data-api.html:14:35: executing "_default/data-api.html" at <"js/vendor/redoc.standalone.js">: nil pointer evaluating resource.Resource.Permalink
make: *** [serve] Error 255`
Consideration:
Slow. Possibly even slower than the original. We may need to call it earlier and minifiy, or something similar.
https://gohugo.io/hugo-pipes/
=> Use Hugo asset pipeline for API docs

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profile/reporting-profile.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profile/reporting-profile.component.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/scan-results.service.ts
This commit fixes https://github.com/chef/automate/issues/4333
The scan results expansion items were not being correctly mapped to the nodes they belong to.
=> Fix incorrect reporting-profile sidebar expansion content

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.html
This branch updates the Compliance Reports node detail view to show a message when no tests were run on that specific node.
Addresses: https://github.com/chef/automate/issues/1761
A message is displayed when there are no results to show on the compliance report detail view
`build components/automate-ui-devproxy`
`make serve`
1. Download profile that will have no test outcome: https://github.com/chef/automate/issues/1761#issuecomment-694437000
2. Upload profile into automate
3. Navigate to https://a2-dev.test/compliance/compliance-profiles and upload the profile downloaded in step 1
4. Navigate to https://a2-dev.test/compliance/scan-jobs/jobs and create a scan job with this profile
5. Navigate to https://a2-dev.test/compliance/reports/nodes and find the node you scanned with the profile …
=> Display message when no tests were run

components/applications-service/pkg/storage/postgres/services.go
Fixes health filtering in the apps tab sidebar, which currently causes data validation failures in the API.
In #4339 we changed the status filters in the API supporting the apps tab sidebar to support filtering for connected services. Changes to the logic made the filter input for health status case-sensitive, where it had been case insensitive before. The UI sends lowercase filters, which are being rejected as "unknown" values.
* `applications_populate_database`
* visit the apps tab, select any service group, then click the filters in the sidebar. You will always see 0 results and "None of the services returned <your selection>"
* build applications service, wait for it to deploy
* visit the apps tab, select any service group, then click the filters in the sidebar. …
=> Make health filters case insensitive

integration/helpers/ssl_filters.jq
We already put in a filter to ignore this check in
3a2e03b6e9e57bae4cd6fcf12c38fb153453cc11 but it appears that
drwetter/testssl.sh#1741 changed the name of the check.
=> tests: don't check cert validity period for internal CA

.expeditor/verify.pipeline.yml, Makefile.common_go, components/automate-ui/Makefile, components/automate-ui/src/app/components/authorized/authorized.component.ts, components/automate-ui/src/app/components/form-control/form-control.directive.ts, components/automate-ui/src/app/components/landing/landing.component.ts, components/automate-ui/src/app/helpers/auth/authorized.ts, components/automate-ui/src/app/modules/infra-proxy/cookbooks/cookbooks.component.ts, components/automate-ui/src/app/modules/infra-proxy/data-bags-details/data-bags-details.component.ts, components/automate-ui/src/app/modules/license/license-notifications/license-notifications.component.ts, components/automate-ui/src/app/pages/client-runs/client-runs.component.ts, semgrep/rxjs-subscription.yaml, semgrep/rxjs-syntax.yaml
Semgrep provides security validation via published rulesets for a variety of languages, including Go and soon TypeScript (now in alpha); see https://semgrep.dev/ for current offerings and ruleset browsing. It also allows writing arbitrary language validation rules, i.e. non-specific to security concerns, but rather to enforce conventions or patterns that the team views as "best practice".
This PR introduces custom semgrep rules focussing on **rxjs lifecycle management**. The patterns required to properly manage rxjs subscriptions are both "best practice" and necessary, yet cannot be enforced by the compiler. Semgrep, though, provides just the mechanism to enforce these patterns.
Here are the rules I have introduced, separated into two files a la the single responsibility principle. All …
=> Introduce semgrep security/language validation

.expeditor/verify.pipeline.yml, Makefile.common_go, api/config/cs_nginx/config_request.go, components/automate-deployment/pkg/airgap/bundle_creator.go, components/automate-deployment/pkg/backup/artifact_repo.go, components/automate-deployment/pkg/server/server.go, components/automate-gateway/pkg/nullbackend/backend.go, components/cereal-service/cmd/cereal-service/cmd.go, components/compliance-service/reporting/util/zip.go, lib/grpc/secureconn/factory.go, tools/cereal-scaffold/main.go
This is a follow-on to "Introduce semgrep security/language validation" (PR #4395). That first PR added a buildkite task for running custom validation rules--rules that we write--to validate whatever conventions we want. This PR adds a second buildkite task for using published rulesets (that focus mainly on security validations).
**TO DO: I have added the validation that reports the failures, but I have not addressed some of the fixes. The associated issue has prior discussion over these with suggestions on what is needed. Looking for team collaboration to address these.**
Our starting point was 12 findings but only 3 types of errors there:
A. go.lang.security.audit.crypto.bad_imports.insecure-module-used: Insecure module used.
B. …
=> Add semgrep buildkite task for published rules

semgrep/rxjs-subscription.yaml
One must take care when writing semgrep rules that the actual matched pattern is as concise as possible. Before the change in this commit, the pattern was matching a class, so the entire class is output by semgrep:
```
severity:error rule:Users.msorens.code.go.src.github.com.chef.automate.semgrep.ngOnDestroy-missing-complete: ngOnDestroy missing this.isDestroyed.complete()
17:export class ProjectsDropdownComponent implements OnInit, OnDestroy, OnChanges {
18:
... omitting 60 or so lines here!!
79:  onProjectDropdownClosing(ids: string[]): void {
80:    this.onDropdownClosing.emit(ids);
81:  }
82:
83:}
```
With the change to the pattern, the output is now just this single line:
```
severity:error rule:Users.msorens.code.go.src.github.com.chef.automate.semgrep.ngOnDestroy-missing-complete: …
```
=> Refine semgrep rules to have cleaner output

.expeditor/create-manifest.rb, components/automate-elasticsearch/habitat/plan.sh
The complete list of CVEs this will address is hard to compile as many
of the issues are in libraries used inside ES or the s3-repository
plugin we download.
For example, the jackson-databind dependency, was at version 2.8.11.3 previously:
/hab/pkgs/chef/automate-elasticsearch/6.8.3/20201015010521/es/modules/ingest-geoip/jackson-databind-2.8.11.3.jar
/hab/pkgs/chef/automate-elasticsearch/6.8.3/20201015010521/es/plugins/repository-s3/jackson-databind-2.8.11.3.jar
and should now be at 2.8.11.6
/hab/pkgs/chef/automate-elasticsearch/6.8.12/20201016121850/es/modules/ingest-geoip/jackson-databind-2.8.11.6.jar
/hab/pkgs/chef/automate-elasticsearch/6.8.12/20201016121850/es/plugins/repository-s3/jackson-databind-2.8.11.6.jar
The changelog for this library claims the following CVEs have been …
=> automate-elasticsearch update to 6.8.12

components/automate-gateway/third_party/swagger-ui/index.html
This got reset by re-vendoring the dependency.
=> automate-gateway: use correct swagger configuration

api/config/dex/config_request.go, api/config/dex/config_request_test.go, components/automate-dex/habitat/templates/config.yml
If unset, it's still going to be 24hrs when SAML is used. However, it can now be
overridden if desired.
If it's set to something too small, like one minute, you'll end up in a sign-in
loop.
`rebuild components/automate-dex` and play with the existing id_token expiry setting, e.g.
```toml
[dex.v1.sys.expiry]
id_tokens = "10m"
[dex.v1.sys.connectors]
disable_local_users = true
```
sign in using saml, wait for 10 minutes, see what happens ✨
=> automate-dex: don't hardcode 24hrs expiry for saml, make it configurable

components/automate-ui/src/app/page-components/client-runs-table/client-runs-table.component.scss, components/automate-ui/src/app/pages/client-runs/client-runs.component.html, components/automate-ui/src/app/pages/client-runs/client-runs.component.scss, components/automate-ui/src/app/pages/client-runs/client-runs.component.ts
As a user, when i'm on the client runs page I want to be able to smoothly filter my client runs while maintaining my scroll depth on the page.
I have added some changes to preventing jump to top of screen
https://github.com/chef/automate/issues/3759
I have added one function which can find existing height of the component and again set the existing height after changing the tab.
```
STEP 1
STEP 2
navigate to `https://a2-dev.test/infrastructure/client-runs`
add some sample data …
```
=> added changes to prevent scrolling on client runs page tabs change

components/automate-ui/src/app/pages/+compliance/+reporting/reporting-searchbar/reporting-searchbar.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/reporting-searchbar/reporting-searchbar.component.scss
Depending on the browser viewport size, the compliance calendar picker would render underneath the compliance tab menu. This commit adds a zindex to the calendar picker dropdown to correct this issue.
Before:
After:
=> Fix incorrect compliance calendar picker zindex

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.scss
Add a little breathing room around the newly returned pagination component in scan history.
Before:
After:
=> Give pagination some breathing room in reporting node

.expeditor/verify.pipeline.yml, components/automate-ui/Makefile, components/automate-ui/src/app/entities/projects/project.effects.spec.ts, components/automate-ui/src/app/pages/+compliance/+scanner/containers/nodes-add/nodes-add.component.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/report-data.service.ts, components/automate-ui/src/app/types/types.ts, semgrep/general.yaml, semgrep/rxjs-subscription.yaml, semgrep/rxjs-syntax.yaml
_Semgrep adds checking beyond what the compiler and linter can do;
custom rules can validate Chef conventions, best practices, and the like!_
(A) Adds a few new rules shown below and applies a couple fixes stemming from them.
(B) Removes workaround from rule "combineLatest-not-combining" as bug was fixed in semgrep 0.29.0.
(C) A bit of general semgrep refinement.
**Category:** general syntax
**Rule ids:** verbose-booleans
**Detail:** returning exhaustive booleans should just return the expression instead
**Category:** rxjs subscriptions
**Rule ids:** onDestroy-not-implemented-in-class
**Detail:** subscriptions never complete because class does not implement OnDestroy Lifecycle hook
**Category:** rxjs syntax
**Rule ids:** observables-from-select-or-pipe-not-ending-with-dollar-sign, …
=> Additional semgrep validation

.expeditor/verify.pipeline.yml, components/automate-ui/src/app/entities/userperms/userperms.effects.ts
Looks like a fresh release of semgrep 0.30.0 introduced a bug that flagged this line incorrectly:
```
/go/src/github.com/chef/automate/components/automate-ui/src/app/entities/userperms/userperms.effects.ts
severity:error rule:go.src.github.com.chef.automate.semgrep.observables-from-select-or-pipe-not-ending-with-dollar-sign: Observable variable should end with a dollar sign.
81:action: GetUserParamPerms) => this.requests.fetchParameterized(action.payload).pipe
```
The prior version of semgrep worked fine with that, so just pinning that version for now, and reverting the well-meaning change @lancewf put in today to get unblocked. (Thanks, @lancewf, and sorry for the inconvenience!)
https://github.com/chef/automate/pull/4424
Semgrep passes in buildkite 
Just check "Custom" semgrep task in …
=> Pin semgrep for custom rules

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/reporting-overview.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profile/reporting-profile.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+reporting/reporting-searchbar/reporting-searchbar.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/reporting-searchbar/reporting-searchbar.component.scss, components/automate-ui/src/app/pages/+compliance/+reporting/reporting-searchbar/reporting-searchbar.component.ts, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/report-data.service.spec.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/report-query.service.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.spec.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/suggestions.service.spec.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/suggestions.service.ts, components/compliance-service/api/tests/30_jobs_docker_spec.rb
WIP: depends on https://github.com/chef/automate/pull/4310
This commit adds the option to view the last 24h of compliance data. Compliance API endpoints were [recently updated](https://github.com/chef/automate/pull/4310) to return last 24h window of data if `start_time` and `end_time` are excluded from requests.
https://github.com/chef/automate/issues/4263
https://github.com/chef/automate/pull/4310
=> Add option to select last 24h compliance report

components/automate-ui/package-lock.json, components/automate-ui/package.json, components/automate-ui/src/app/modules/team/team-details/team-details.component.ts, components/automate-ui/src/app/ui.component.ts, components/automate-ui/src/main.ts
rxjs-spy is a debugging library for RxJS, which is pervasive in our UI. This provides some infrastructure so you might be able to get away from a plethora of `console.log` statements when trying to diagnose an errant behavior.
With rxjs-spy you can add a simple tag to any observable in your code, then in the browser you can watch any or all tagged observables receiving values, being subscribed, and being unsubscribed.
Project: https://github.com/cartant/rxjs-spy
More Details: https://ncjamieson.com/debugging-rxjs-part-1-tooling/
rxjs-spy is available for use in development (not production).
1. Load the new package dependency on your machine: `npm install`.
2. Launch automate-ui using your method of choice (e.g. `make serve`).
3. Open automate-ui in your browser (https://a2-dev.test/).
4. …
=> Introduce rxjs-spy diagnostic tool to UI

components/automate-workflow-server/rebar.config
The current code on master for the https://github.com/rustyio/sync.git
project is failing with "Dependency not available" for the
{git,"https://github.com/synrc/fs",{tag,"6.1"}} dependency.
This change pins the dependency to a working version.
=> Dependency problem with rustyio/sync

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-trend/overview-trend.component.ts
After merging https://github.com/chef/automate/pull/4358 some users might get confused between local time selections (`Last 24 hours`) and the places where we select/show a day which is UTC.
As can be seen in the below screenshots, I added `(UTC)` suffixes in the trend graphs.
=> Add UTC label in compliance trend graphs

components/automate-ui/src/app/pages/+compliance/+reporting/reporting-searchbar/reporting-searchbar.component.html
After merging #4358 some users might get confused between local time selections (`Last 24 hours`) and the places where we select/show a day which is UTC.
As can be seen in the below git that Scott uploaded in the UI pull request:
In the same dropdown the user can choose between `Last 24 hours` in the local timezone to a DAY, without any hint that this day is not in their timezone, but in UTC.
In an effort to make this UTC aspect more clear, I'm submitting this PR with two changes as can be seen in the screenshots below:
---
---
=> Add UTC label in the date picker

components/ingest-service/pipeline/publisher/msg_distributor.go
When all the Elasticsearch publishers are full the log message should be an error and not a warning.
https://github.com/chef/automate/issues/3152
The log message when all the Elasticsearch publishers are full is an error, not a warning.
=> Elasticsearch Publishers Full warning

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-trend/overview-trend.component.scss, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-trend/overview-trend.component.ts
To show the waived nodes and profile data on the compliance graph.
OFFR-E-10 #4382
Changes should be for both node status and profile status tab.
There should be a new waved line in the graph
Waived data should show up in the tooltip on compliance graph. 
The intersection dots should accommodate the new waived circle.
Add some waived data. You can see the new line and numbers in the tooltip.
=> ui-tooltip and circle changes made in graph for waived nodes and profiles

.expeditor/verify_private.pipeline.yml, .semgrep/general.yaml, .semgrep/rxjs-subscription.yaml, Makefile, components/automate-ui/src/app/page-components/event-feed-table/event-feed-table.component.ts
1. Adding some new syntax checking rules.
2. Adding targets to global makefile so one can run semgrep on the entire codebase (in addition to the  individual targets on a per project basis introduced earlier), with a variation to run it differentially the way CI now does, per the next bullet.
3. Switching semgrep-agent to run in differential mode--it will check only the files in the current PR, providing several benefits:
(a) Checks only changes in each PR in Buildkite.
(b) Much faster run time.
(c) Newly introduced rules from the vendor cannot break the build on master.
(d) Reports in the web UI do not keep repeating pre-existing issues in the rest of the code base.
NA
Globally:
- `make semgrep` from the repo root to run differentially, the way buildkite does
- `make semgrep-all` from the …
=> Activate semgrep differential mode and other refinements

.expeditor/verify_private.pipeline.yml
We are seeing this test timeout on master. Bumping the timeout to see
if it would eventualy pass.
=> ci: bump timeout from 20 to 25 minutes

.studio/chef-server-collection, dev-docs/adding-data/adding_test_data.md
Adding a new studio functions `push_example_policyfile` and `converge_policyfile_chef_client` that create a CCR with an example policyfile. This is useful when testing policyfiles with Infra nodes or the event feed. The `converge_policyfile_chef_client` function first calls the `push_example_policyfile` function to create the example policyfile and upload it to Chef-Server.
1. From the Automate hab studio run `start_all_services`
1. To start the Automate chef infra server run `start_chef_server`
1. To create a CCR with an example policyfile run `converge_policyfile_chef_client`. This function first creates the example policyfile by calling the `push_example_policyfile` function. 
1. Goto the event feed in the UI to see the new events https://a2-dev.test/dashboards/event-feed (image below) …
=> Studio function to create an example Policyfile

components/automate-ui/src/app/page-components/event-feed-table/event-feed-table.component.spec.ts, components/automate-ui/src/app/page-components/event-feed-table/event-feed-table.component.ts
This change fixes the situation where the event feed does not display the name of policyfile cookbook updates. 
1. From the Automate hab studio run `start_all_services`
1. To start the Automate chef infra server run `start_chef_server`
1. To update the changes in the UI run `build components/automate-ui-devproxy/` and `start_automate_ui_background`
1. Create an example policyfile by running the `push_example_policyfile` function. 
1. Goto the event feed in the UI to see the new cookbook events https://a2-dev.test/dashboards/event-feed (image below)
Single cookbook
Grouped cookbooks
=> Policyfile cookbooks display name in event feed

components/automate-deployment/pkg/server/server.go, integration/helpers/deployment.sh
During upgrades from old versions, we may require a deployment-service
certificate regeneration. If the chef-automate command line tool
attempts to read the deployment-service certificate during this
regeneration, it may receive a FileAccessError such as:
FileAccessError: Unable to access the file or directory: Failed to
read deployment-service TLS certificates: Could not read the
service cert: open
/hab/svc/deployment-service/data/deployment-service.crt: no such
file or directory
Since we expect this error to be transient, we now retry this error in
the wait_for_upgrade loop in CI. We also log a bit more information
about the deployment-service certificate regen.
=> deployment-service/ci: retry file-access errors when waiting for upgrade

.license_scout.yml
This license has been fully approved by the Chef/Progress legal team.
=> Add 0BSD as an allowed open source license

components/docs-chef-io/content/automate/infra_server.md
This page's link to the knife setup docs is currently broken. I took a random guess at where it should be linking to so feel free to correct me if this is incorrect.
=> Fix broken link to Knife setup docs

components/docs-chef-io/content/automate/infra_server.md
Documentation should use relref links when referring to other pages on docs.chef.io. This PR updates the internal links in infra_server.md to use relref links.
🟢  means go!
Use the Netlify link to test these doc changes.
=> Incorporate relref links in Chef Infra Server with Chef Automate docs

components/docs-chef-io/content/automate/on_prem_builder.md
This PR incorporates the Chef Habitat Builder On-prem documentation changes proposed in PR https://github.com/chef/automate/pull/4387 by @ericcalabretta.
🟢  should mean go.
Use Netlify to see documentation changes.
=> Update On-prem Builder Authentication Docs

.studio/config-mgmt-service
In #4255 we enabled the `ENUM_VALUE_PREFIX` lint rule in [buf](https://docs.buf.build). Because the rollout APIs are beta instead of final, we made the breaking change to conform the protos to the new lint rule instead of excepting them from the rule. This meant that callers of the API needed to changes to use the new enum values, but we didn't make that change in the studio helpers, so they broke. The base rollout document we use needs to be updated for the new enum values of the `scm_type` and `scm_web_type` fields.
#4255
`config_mgmt_rollout_json | config_mgmt_send_to_create_rollout_pretty` and any similar usage, e.g., `config_mgmt_populate_rollouts` works.
* restart your studio clean, or source the config-mgmt-service code
* `config_mgmt_populate_rollouts`
* …
=> Fix rollout helpers for proto linting changes

.buildkite/hooks/pre-command, .expeditor/verify_private.pipeline.yml
While this was useful to have during periods of heavy development, the PR traffic is now much reduced so it is OK to change this back to the way almost every other Chef repo works.
The motivation for this was for tools (like semgrep) that want to tie notifications to specific commit links and that could not be done with the on-the-fly rebase.
NA
(a) Build still runs fine.
(b) Slack notifications for semgrep have active links to the github commit pinpointing the failure.
Easier just to show it:
Buildkite fails the semgrep task, that produces a notification in slack, and clicking on the SHA opens up a window in GitHub:
=> Remove rebase-on-the-fly in PRs

components/automate-ui/src/app/app.module.ts, components/automate-ui/src/app/ngrx.reducers.ts
Before this patch, ReduxDevTools in the browser (Chrome or Firefox) would crash very soon after launching the Automate UI. Sometimes it would actually mention that it was going to be slow and consume a huge amount of memory.
To see this: install the Redux Dev Tools browser extension, enable it, navigate to a2-dev.test in your browser, open the browser Dev Tools (<kbd>cmd</kbd> + <kbd>opt</kbd> + <kbd>i</kbd>), and open the Redux tab in the browser Dev Tools.
Depending on your timing, you might see an initial few actions like this...
... but it will stop updating and eventually crash.
You can see that it is consuming huge amounts of memory via Activity Monitor, htop, or other process monitor. In the illustration I have filtered by chrome's helpers and sorted descending. The topmost "Google …
=> Resolve redux devtools crashing

components/docs-chef-io/content/automate/install.md, components/docs-chef-io/static/automate-api-docs/all-apis.swagger.json
The PR here https://github.com/chef/automate/pull/4486 allows automate to now resolve the Postgres cluster and Elasticsearch nodes using resolvers. The resolvers can be set in the `config.toml` by the users.
The changes document how to configure resolvers in case of external PG or ES.
Updated install.md file to add sections:
1. ADDING RESOLVERS FOR ELASTICSEARCH
2. ADDING RESOLVERS FOR POSTGRESQL DATABASE
The document should have the sections mentioned above with the details of the configuration.
1. Pull the code
2. `make serve`
3. The updated document should be shown in http://localhost:1313/automate/install/
=> Doc update on how to add resolvers for PG and ES gateways

.expeditor/post-promote.pipeline.yml
ruby dependencies themselves are > 7 minutes so increasing from default of 10 minutes here
NA
Retries not needed for post-promote in buildkite.
NA
=> Increasing timeout for post-promote pipeline

api/config/deployment/automate_config.go, api/config/deployment/automate_config_test.go
PopulateSecretsFromEnvironment will attempt to read any missing config that are sercret from environment variables. These will eventually be removed from the config and stored in an encrypted place
=> Add PopulateSecretsFromEnvironment for loading config

.expeditor/config.yml
Prior to this, the only time the staging area got unlocked was upon completion of the habitat build.
However, as we saw in December, the habitat build stalled completely (it never ran) for about 4 weeks.
NA
Staging area is always unlocked once per day in case other pipelines get stalled.
?? Not sure
=> Unlock staging area nightly in case of stall

components/automate-cli/cmd/chef-automate/bootstrap.go, components/automate-deployment/habitat/plan.sh, lib/secrets/encrypt.go, lib/secrets/encrypt_test.go, lib/secrets/secrets.go, lib/secrets/secrets_helpers_test.go, lib/secrets/secrets_test.go
This modifies the secrets store/secrets helper utilities to encrypt secrets that are stored on disk. Any existing secret data will not be encrypted unless it is modified. This is fine, as all existing data is generated and uses the secret helpers to share that data between services.
The reason we are doing this is be able to store customer provided secrets in non plaintext. We will take the secrets that are provided in the config and place them in the secret store encrypted.
This is not a user facing change.
This does not provide any sort of security, as the key is stored on next to the secrets on disk.
=> Encrypt secrets that are put in the secrets store

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-trend/overview-trend.component.ts
The page used to crash when we select the option **Last year/Last 3 month** from the dropdown present in the trend graph, every time we call `this.trendData` it uses to loop through each data present in `this.data`
In `get trendData()` we try to convert time which is in type string (**2020-09-21T23:59:59Z**) to type object (**Mon Sep 21 2020 00:00:00 GMT+0530 (India Standard Time)**)
Eg:- To draw a graph in d3 we are calling trendData 377 time’s ( I saw this when I console log in get tendData() ) for 10 day’s graph call is **377 * 10 = 3,770** and for one year data is **377 * 366 = 1,37,982** 
When we select 10 days in option
When we select 1 year in option
https://github.com/chef/automate/issues/4353 
We try to loop only once and Cache in trendDataCache
So that we don’t have to loop once …
=> page crash on trend graph on selecting 3 month/1 year data

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-failures/overview-failures.component.ts, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/overview-trend/overview-trend.component.ts
- Clicking on a date in trend graph is not loading data for that date.
- Clicking on the pie chart does not open the reports page
Issue was caused due to the recent changes in d3 version from 5.16.0 to 6.3.1
According to the migration guide [click here](https://observablehq.com/@d3/d3v6-migration-guide)
``` ts
// any pattern like this
selection.on("click", function(d, i, e) {
console.log(d, i, e);
})
// should be replaced by:
selection.on("click", function(event, d) {
const e = selection.nodes();
const i = e.indexOf(this);
console.log(d, i, e);
})
```
I have made the changes in overview-failure component and overview-trend component.
Could not find any other places this pattern was not followed.
#4515 
- open the compliance tab
- clicking on a date in the trend chart should load data for …
=> fixed issue in trend graph and pie chart

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.ts
Signed-off-by: Shaik Mudassir <47217471+shaik80@users.noreply.github.com>
Added a button to download historical reports on compliance node details with file format option
https://github.com/chef/automate/issues/4344
Added download report button including option(JSON and CSV) plus  pop-up downloading Status model and also written unit test for download report function
```
STEP 1
STEP 2
and run the command make serve
```
Before testing please follow steps from https://github.com/chef/automate/pull/2378
open automate-ui in browser goto **Compliance -> Report -> …
=> added download button to get full details report of particular node

components/automate-ui/src/app/page-components/services-sidebar/services-sidebar.component.html
The page-picker component was breaking out of its container when longer than 5 pages.  This branch constrains the number of pages to 5 pages max displayed at a time.
Fixes: https://github.com/chef/automate/issues/4504
The page picker no longer breaks out of its container
in Automate root: `hab studio enter` then `build components/automate-ui-devproxy && start_all_services`
in automate-ui: 'make serve'
in hab studio run 
```
for i in {1..3}; do applications_populate_database; done
```
... which will take ~30 seconds to complete.
Navigate to https://a2-dev.test/applications/service-groups
In the Filter Bar, Filter on application: demo
Click on the first result in the list so that it displays in the sidebar
scroll sidebar to bottom so that you can see the page-picker component
Before:
After:
=> In Services sidebar, Limit page-picker to 5 pages max displayed at once

components/docs-chef-io/content/automate/install.md
Fix tabbing for example text so the numbers are generated correctly
The example for the enabling postgresql system dns should specify `true` instead of `false` 
Signed-off-by: Will Fisher <wfisher@chef.io>
=> Fix postgres/elasticsearch dns resolver config examples

api/config/deployment/automate_config.go, api/config/deployment/automate_config_test.go, components/automate-deployment/pkg/deployment/deployment.go, components/automate-deployment/pkg/server/automate_config.go, components/automate-deployment/pkg/server/server.go, components/automate-deployment/pkg/server/server_test.go, components/automate-dex/habitat/config/ldap_bind_password, components/automate-dex/habitat/config/run_environment.sh, components/automate-dex/habitat/hooks/run, components/automate-platform-tools/cmd/secrets-helper/secrets-helper.go, components/automate-platform-tools/cmd/secrets-helper/secrets_helper_test.go, lib/secrets/secrets.go
Move secrets stored in the config to the secret store.
Added a watch mode the secrets-helper exec. When run with this flag, the
we run the requested executable as a child process. If any of the
watched secrets change, the child process is killed. This will make sure changes
to secrets still get picked up automatically. I've kept it simple for now. It polls the secrets
instead of using anything like inotify.
To run this:
- rebuild components/automate-platform-tools
- export local_platform_tools_origin=YOURORIGIN
- rebuild components/automate-deployment
- rebuild components/automate-dex
You can use the following config to patch automate:
```
[dex.v1.sys.connectors.ldap]
host = "ldap.localhost"
bind_dn = "uid=service_account,dc=example,dc=local"
bind_password = "testpassword3" …
```
=> Move secrets from config to secret store

.expeditor/verify_private.pipeline.yml, .semgrepignore, Makefile, Makefile.common_go, components/automate-deployment/pkg/airgap/bundle_creator.go, components/automate-deployment/pkg/backup/artifact_repo.go, components/automate-ui/Makefile, components/compliance-service/reporting/util/zip.go, lib/cereal/postgres/postgres.go
(1) Updated root-level makefile tasks for semgrep:
* `semgrep` -- runs differential mode (checks only the files in the current PR)
* `semgrep-all` -- runs full scan but filters out inconsequential (legacy) issues
* `semgrep-legacy` -- same as `semgrep-all` but reveals legacy issues
(2) Refined the list of files to scan; ignoring more generated files.
(3) Muted a few findings (issue reported but safe in our code base).
(4) Semgrep should now run in differential mode during the merge-to-master buildkite run as well.
#4395 -- introduce semgrep
#4430 -- migrate to semgrep-agent
(1) semgrep, semgrep-all, and semgrep-legacy targets now available for root-level `make`.
(2) Generated files do not show findings.
(3) A few previously reported findings are no longer reported (see individual …
=> Update makefile and buildkite semgrep tasks

.expeditor/verify_private.pipeline.yml
Straightened out the details and the messaging for the three possible build scenarios.
Also, in my last PR (#4596) I was testing the behavior when merging to master, and that worked as expected, so now removing the soft-fail safe guard.
This is an explicitly created build via the "New Build" button in Buildkite, outside of a PR.
In our environment, this should almost always be on a working branch that derived from master; we rely on that fact to set the base branch to "master" for the differential semgrep scan (1). Points (2) and (3) show the differential scan in action--it picks up only the 9 files in the 7 commits on the target branch.
This is the same run inside a PR, kicked off automatically by Buildkite, as you can tell from (1).
This will actually accommodate PRs derived from any …
=> Clarify three Buildkite scenarios for semgrep

docs
docs symlink was pointing at a folder that didn't exist. Looks like things have been moved to components/docs-chef-io
=> Fix docs symlink

.expeditor/nightly.pipeline.yml
Adding in a full run of semgrep in the evening run. During PRs, semgrep does only a differential scan, reviewing just the files in the current PR. This is just a way to keep tabs on any on-going technical debt.
NA
New Buildkite task for semgrep in the nightly build.
NA
NA
=> Wire up full semgrep to run nightly

.expeditor/verify_private.pipeline.yml, integration/tests/ha_chef_server.sh
the chef server tests are now passing the port as part of the host header. When erchef is configured to use the host header, it doesn't strip out the port if its passed via the host header even if its a default port. This change tells pedant to expect the port in the response URIs.
=> Enable HA Chef Server test

components/automate-deployment/pkg/deployment/deployment.go, components/automate-deployment/pkg/deployment/deployment_test.go, components/automate-deployment/pkg/server/server.go
Users who have secrets configured prior to last release (20210116...)
are stuck in a crash loop for deployment-service. The issue is that the
secrets store is being initialized too late in the process. This change
initializes it sooner. If a nil secrets store is provided, the code now
ignores it and moves on.
The release plan:
Deployment service will not be able to fix itself in this case. Customers who have already upgraded will need to follow the following steps after we promote the fix:
```
hab pkg install chef/deployment-service/0.1.0/$NEW_VERSION
sed -i -e 's|chef/deployment-service/0.1.0/20210116174651|chef/deployment-service/0.1.0/$NEW_VERSION|g' /hab/sup/default/specs/deployment-service.spec
chef-automate upgrade run
```
=> Fix segfault during migration of secrets

components/automate-ui/src/app/modules/infra-proxy/cookbook-details/cookbook-details.component.html, components/automate-ui/src/app/modules/infra-proxy/cookbook-details/cookbook-details.component.ts
While click on content tab getting console error
https://github.com/chef/automate/issues/4631
I have added changes to fix the console error for the cookbook details content tab. 
```
go to >> infrastructure tab >> click on Chef server on left side navigation bar >> click to any server where you can see the list of orgs >> click to any of org >> where you can see the multiple tabs (the first tab is cookbooks) >> see the list of cookbooks >> click to any of cookbook >> you can see the 2 tabs content tab and details tab >> click to the content tab and open the browser console.
```
=> [infra-proxy-read-only] fixed the console error on cookbook details content tab

components/automate-ui/src/app/modules/infra-proxy/create-org-modal/create-org-modal.component.html, components/automate-ui/src/app/modules/infra-proxy/create-org-modal/create-org-modal.component.scss
Create org modal scroll bar is the same as other modal scroll bars.
https://github.com/chef/automate/issues/4623
I have added CSS changes to fix the create org modal scroll bar.
To load sample data:
- Load data into the infra views using `infra_service_load_sample_data` in hab studio (ref: [adding_test_data](https://github.com/chef/automate/blob/master/dev-docs/adding-data/adding_test_data.md))
- Enable the Chef Infra Server Views in the magic menu by typing **feat** anywhere in the automate ui
if you have sample data for the infra servers than 
go to >>  infrastructure tab >> click on Chef server on left side navigation bar >> click to any server where you can see the button `add chef organization` 
**before fix** 
**after fix**
=> [infra-proxy-read-only] fixed the scroll bar for the infra create org modal

integration/tests/deep_upgrade_backup_restore.sh
Added ldap config to the deep upgrade test to ensure that automate can correctly update to a version where secrets are encrypted
=> Add ldap config to deep upgrade test

.expeditor/announce-acceptance.sh
Previously an acceptance notification (in the `#a2-release-notification` slack channel) looked like this:
This PR makes the following changes:
(1) Besides showing the commits in the release it also shows the PRs in the release. This is the view directly used by developers to tag PRs with acceptance testing status.
(2) Previously the only action item listed was to update release notes; this PR has expanded that to the three required action items.
Learn a technique for testing something that is inherently difficult to test or testable only indirectly by using "masking commits".
NA
Not sure if there is a way to actually trigger the slack notification for testing purposes, so I am stating this from a "raw" perspective, examining output of the affected script directly.
This is the "raw" …
=> Update notification for acceptance promotion

.expeditor/announce-acceptance.sh
The revised acceptance-announcement script is almost working--but the URL comes out wrong due to the date formats. Need to convert, e.g., "2021-01-27T10:16:58+00:00" to "2021-01-27T10:16:58%2B00:00".
#4600 
Upon promoting to acceptance the slack message reads like this, with the plus sign in the dates URL-encodeed.
```
@here Automate has been promoted from dev to acceptance :successful:
List of changes by commit: https://github.com/chef/automate/compare/76612f53b101daffb1badb252b6de186594dbcba...3b5a3ab507b37f5b44f7da548f27f9a901776020
List of changes by PR: https://github.com/chef/automate/pulls?q=is%3Apr+is%3Amerged+sort%3Acreated-asc+closed%3A2021-01-27T10:16:58%2B00:00..2021-01-29T16:11:07%2B0000
. . .
```
Need the automate repo present on a Linux box, then change the final line to …
=> Update notification for acceptance promotion/pass 2

components/automate-ui/e2e/admin.e2e-spec.ts, components/automate-ui/src/app/modules/policy/list/policy-list.component.html, components/automate-ui/src/app/modules/roles/list/roles-list.component.html
Signed-off-by: samshinde <ashinde@chef.io>
In the Roles and policy list tables added a column for ID.
#4036 
Added a column for ID on the policy list and role list pages.
```
STEP 1
STEP 2
and run the command ```
=> Added Ids column in Policies and Roles List

components/automate-ui/src/app/entities/servers/server.effects.ts
When the user updating the server details then a success notification on the top section does not appear.
https://github.com/chef/automate/issues/4639
I have added changes to show the success notification on top
go to >> infrastructure tab >> click on Chef server on left side navigation bar >> click to any server where you can see the second tab details
If the user trying to update the details then a success notification is showing.
=> [infra-proxy-read-only] On server update show the top notification

.expeditor/buildkite/semgrep.sh, .expeditor/nightly.pipeline.yml, .expeditor/verify_private.pipeline.yml, Makefile
Two days ago semgrep reported a finding (via slack notification) for 2 different PRs regarding an error in the same file (components/automate-deployment/pkg/server/reconfigure_handler.go). Since semgrep runs in differential mode--scanning files only in the current PR--this was quite surprising, because that file was touched in neither of those PRs!
The finding was this:
```
chef/automate – 1 new issues
4d668b0 Use search query interface
err-todo from dgryski.semgrep-go
– components/automate-deployment/pkg/server/reconfigure_handler.go:33
Scanned yesterday at 7:53 PM
```
The finding would be perfectly valid if that file was included in the PR but, as I said, it was not. What made that more peculiar was that if I were to run a full (non-differential) scan, that particular rule will report …
=> Adjust merge base point for semgrep differential scan

components/automate-workflow-server/rebar.config
Looks like erlang 18 is no longer supported by parse_trans since
https://github.com/uwiger/parse_trans/commit/91f02431e0205df21c2cbfa2de5881b522ef3ff5
=> Fix workflow build

api/config/erchef/config_request.go, api/config/erchef/config_request_test.go, integration/tests/chef_server_only.sh
Currently chef-server will not come up if automate is disabled in the dev vm.
This happens because data-collector is set to true(enable) by default. This change makes it such that data-collector will be enabled only if external or internal automate are enabled.
Co-authored-by: Jay Mundrawala <jmundrawala@chef.io>
=> Set data_collector to true only if external automate or local automate is enabled.

components/automate-cs-nginx/habitat/config/chef_https.conf, components/automate-cs-nginx/habitat/config/nginx.conf
Also, the resolver config reads the resolvers from /etc/resolve and
queries every few minutes. I checked with wireshark to make sure it
doesn't happen for every request.
resolves: https://github.com/chef/chef-server/issues/2181
Co-authored-by: Prajakta Purohit <prajakta@chef.io>
=> Allow nginx to start even if external automate upstream fails to resolve

.studio/notifications-service, components/notifications-service/integration_test/notification_receiver_test.go, components/notifications-service/integration_test/notification_test.go, components/notifications-service/integration_test/rules_crud_test.go, components/notifications-service/integration_test/service_test.go, components/notifications-service/integration_test/suite_test.go, components/notifications-service/integration_test/webhook_validator_test.go
Create a full integration test suite for the notifications service in go. Everything is tested via external interface. This enables reimplementing the notifications-service while maintaining API stability.
NOTE: click the "Load Large Diff" button for `components/notifications-service/integration_test/notification_test.go`, that's most of the action in this PR.
No work is done to run this test suite in Ci yet. It will make sense to do so once we've created the reimplementation of the notifications-service.
This suite will probably need some adaption to work against the new implementation of the notifications-service. That will be done when there is a new implementation to adapt to.
In a fresh studio (if not fresh, source the `.studio` files):
* run …
=> Add Integration Testing for the Notifications Service

components/notifications-service2/.gitignore, components/notifications-service2/cmd/notifications-service/commands/root.go, components/notifications-service2/cmd/notifications-service/commands/serve.go, components/notifications-service2/cmd/notifications-service/notifications-service.go, components/notifications-service2/habitat/config/config.toml, components/notifications-service2/habitat/config/init_proxy, components/notifications-service2/habitat/default.toml, components/notifications-service2/habitat/hooks/init, components/notifications-service2/habitat/hooks/run, components/notifications-service2/habitat/plan.sh, components/notifications-service2/package.meta, components/notifications-service2/pkg/config/service.go, components/notifications-service2/pkg/config/service_test.go, components/notifications-service2/pkg/storage/postgres/schema/sql/01_one_dot_zero_migrations.up.sql
We are rewriting the notifications service in go to align better with our engineering capabilities.
This change creates a `notifications-service2` component in the source tree. It can be compiled and packaged manually, but is hidden from pipeline builds using the `dev_only` option in the habitat `plan.sh` (the `automate-ui-devproxy` uses the same mechanism).
The `notifications-service2` is missing most of the functionality that it will eventually have/need. Currently it only implements configuration file loading. When run as a service it prints its config to the logs in a loop. This is a first step towards implementing the infrastructural components of the new notifications service.
In a fresh habitat studio, `start_all_services`. Then run `build components/notifications-service2/ && sl`. …
=> Notifications Rewrite: Service Stub

components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.html, components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.scss, components/automate-ui/src/app/modules/infra-proxy/chef-servers-list/chef-servers-list.component.html, components/automate-ui/src/app/modules/infra-proxy/chef-servers-list/chef-servers-list.component.scss, components/automate-ui/src/app/modules/infra-proxy/chef-servers-list/chef-servers-list.component.ts
new UI for the Server and Orgs list pages for read-only views 
#4713 
1. Removed the border of the Server and org List Table.
2. Added the background colour for Active option.
3. Increased the height of the selected Active Blue Line.
4. Aligned Create Buttons to Right of Server and org.
=> Added UI improvements for server and org list.

terraform/test-environments/modules/chef_automate_install/main.tf
The AD servers listed do not seem to exist. These new IPs reflect the current AD servers. Hopefully this will fix the issue where the chef-ci user can not SSH into the airgapped environments.
=> Update iptables configuration to point to "correct" AD servers

components/docs-chef-io/content/automate/data_lifecycle.md, components/docs-chef-io/content/automate/install.md
We fixed a few issues that used to be tricky. This PR removes advice to contact customer support from the Automate docs, except for in the doc about migrating from A1 to A2.
=> Remove advice to call CS

.semgrepignore, Makefile, components/automate-ui/Makefile
Add convenience target for semgrep for exploring new rulesets before integrating with CI. Ruleset choices come from https://semgrep.dev/explore. 
Usage is:
```
make semgrep-test/<ruleset-name>
```
Example:
```
make semgrep-test/rc2-bug-scan
```
Can run `make semgrep-test/<ruleset-name>` from the repo root.
Can run `make semgrep-test/rc2-bug-scan` (or any other ruleset) from the Automate repo root.
NA
=> Add convenience target for semgrep

components/automate-cs-nginx/habitat/config/chef_https.conf
resolves: https://github.com/chef/chef-server/issues/1862
Co-authored-by: Jay Mundrawala <jmundrawala@chef.io>
=> [nginx] data-collector and compliance if configured should forward to the automate instance instead of localhost

components/docs-chef-io/content/automate/_index.md
This adds product metadata to every page in docs.chef.io/automate/
We can use the [cascade parameter](https://gohugo.io/content-management/front-matter#front-matter-cascade) key in `content/automate/_index.md` to add a product value to every page docs.chef.io/automate/ so we can facet search results by that product
chef/chef-web-docs#2878
=> add metadata to every page in docs.chef.io/automate

components/compliance-service/habitat/plan.sh
The compliance profile needs to be reverted from 20210210220805 to 20210113170230
The compliance profile should have the profiles associated only for 20210113170230
Deploy Automate 
Click on the profiles tab and check the profiles list available.
=> revert compliance profiles to 20210113170230

lib/platform/pg/exporter.go, lib/platform/pg/exporter_test.go
A customer is experiencing errors attempting to restore a postures database using AWS RDS. The pertinent part of the error is like this (there are other errors for other extensions) `could not execute query: ERROR:  must be owner of extension pgcrypto\n    Command was: COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';`.
This error happens because in AWS RDS, the superuser is actually quite limited. If you start an interactive database session manually with an RDS instance, you can see that `COMMENT ON EXTENSION ...` commands won't work.
To fix the restore issue, we want to avoid attempting to restore these comments, as they do not affect functionality. [`pg_dump` version 12.x](https://www.postgresql.org/docs/12/app-pgdump.html) and [`pg_restore` version …
=> PG: Ignore comments on extensions when restoring

scripts/get_secrets.sh
Several weeks ago the releng team migrated to a new vault enterprise cluster, but that was a breaking change that needs the changes in this PR for the `get-secrets` script (for internal developer use) to function.
NA
* get-secrets does not report an authentication error.
* get-secrets populates three files (see script) with data from the vault.
Connect to the VPN.
Run `CHEF_USERNAME=msorens ./scripts/get_secrets.sh` substituting your Chef username instead of mine.
=> Resync secrets script with releng vault changes

components/nodemanager-service/tests/mgrtesthelpers/mgr-test-helpers.go
Apparently AWS has added a new region, which broke our integration tests.
```
TestAWSEC2SearchNodeFields: aws_ec2_nodes_integration_test.go:103: 
Error Trace:	aws_ec2_nodes_integration_test.go:103
Error:      	Not equal: 
expected: []string{"ap-northeast-1", "ap-northeast-2", "ap-south-1", "ap-southeast-1", "ap-southeast-2", "ca-central-1", "eu-central-1", "eu-north-1", "eu-west-1", "eu-west-2", "eu-west-3", "sa-east-1", "us-east-1", "us-east-2", "us-west-1", "us-west-2"}
actual  : []string{"ap-northeast-1", "ap-northeast-2", "ap-northeast-3", "ap-south-1", "ap-southeast-1", "ap-southeast-2", "ca-central-1", "eu-central-1", "eu-north-1", "eu-west-1", "eu-west-2", "eu-west-3", "sa-east-1", "us-east-1", "us-east-2", "us-west-1", "us-west-2"}
Diff:
--- Expected
+++ Actual
@@ -1,4 +1,5 @@ …
```
=> Re-sync with changes to AWS region list

components/config-mgmt-service/integration_test/count_missing_node_durations_test.go
Fix failing integration test:
```
FAIL: TestMissingNodeRangeCounts (0.72s)
--- FAIL: TestMissingNodeRangeCounts/normal_case (0.14s)
count_missing_node_durations_test.go:343:
Error Trace:	count_missing_node_durations_test.go:343
Error:      	Not equal:
expected: 2
actual  : 3
Test:       	TestMissingNodeRangeCounts/normal_case
```
I am not able to test locally, so I will see shortly if my theory is correct after Buildkite runs.
The gist of the "normal case" test is to collect some node checkins into various time buckets specified by this set of expectations:
```
expectedResponse: []*response.CountedDuration{
{ Duration: "3d", Count:    11, },
{ Duration: "1w", Count:    8, },
{ Duration: "2w", Count:    6, },
{ Duration: "1M", Count:    2, },
{ Duration: "3M", Count:    1, },
},
```
Each …
=> Fix test anomaly due to February

.expeditor/verify.pipeline.yml
The merge of PR https://github.com/chef/automate/pull/4425 (commit 21371a8e)
re-materialized code that was deleted in the prior commit (84333a19).
This deletes that code... again.
(FYI: It has migrated over to verify_private.pipeline.yml).
Noted above. 
Semgrep no longer appears on https://buildkite.com/chef-oss/chef-automate-master-verify
Just check the buildkite page above.
NA
=> Correct previous bad merge

components/automate-es-gateway/habitat/config/nginx.conf, components/automate-es-gateway/habitat/plan.sh
[nginx_upstream_jdomain](https://github.com/nicholaschiasson/ngx_upstream_jdomain) was introduced in `20201230192246` release to handle dynamic resolution of the hostnames based on the local `/etc/resolv.conf`.
This helps in resolving and connecting to nodes in ES cluster managed by cloud providers where change of IP address because of change of a parameter in a cluster is expected.
A very common such use case is with AWS ES.
Although the change worked for such a cluster with master nodes but it failed to resolve IP in case of clusters with no master nodes and only data nodes. 
This results in Automate Compliance/Infrastructure pages returning no data or unresponsive.
This is because the nginx jdomain module added has a bug which stops it …
=> Modify nginx_jdomain repo

components/docs-chef-io/content/automate/install.md
We have seen off late customer trying to use cloud provided ElasticSearch services like AWS ES which tends to fail.
Such deployments are not tested and documented anywhere so we need to call it out in the documentation to make sure it is known to the user beforehand.
The Automate document should show up the text 
"Please note that Chef Automate does not support Elastic Search services. Automate is not tested against Elasticsearch services provide by cloud provides like AWS Elasticsearch Service."
```
make serve
```
Open up http://localhost:1313 and check the "Install Guide" section in Automate doc under the sub section "Configuring External Elasticsearch"
=> Add the comment in docs to notify non support of AWS ES

buf.yaml
In order to get breaking protobuf changes through Buildkite, we need to make an exception in the buf.yaml config file. But then we need to take those exceptions out again in a follow-up PR. This is that follow-up PR.
Buildkite passes now with those protobuf changes locked in.
Observe Buildkite
=> Cleanup recent buf exceptions

components/automate-gateway/handler/infra_proxy/environments.go, components/infra-proxy-service/integration_test/databags_test.go, components/infra-proxy-service/integration_test/environments_test.go, components/infra-proxy-service/server/environments.go
- For UPDATE, DELETE and CREATE API response only contains the environment name irespective of environment contains the attributes or not.
```
{
"name": "chef-environment-887549700",
"chef_type": "",
"description": "",
"json_class": "",
"cookbook_versions": {
},
"default_attributes": "{}",
"override_attributes": "{}"
}
```
Changes requested for PR: https://github.com/chef/automate/issues/4545
- Make uniform environment response object, earlier it was returning environment name for DELETE, CREATE and UPDATE APIs.
- it will return the attributes if exists.
- `rebuild components/infra-proxy-service`
- Create Environment API
```
curl -sSkH "api-token: $(get_admin_token)" -X POST https://a2-dev.test/api/v0/infra/servers/chef-server-dev-test/orgs/chef-org- …
```
=> Updates Environment the response attributes for Delete, Create and Update API

components/automate-gateway/handler/infra_proxy/databags.go, components/infra-proxy-service/integration_test/databags_test.go, components/infra-proxy-service/server/databags.go
- Create data bag item required to return the id of the item, but as of now, API does not return it, so wrapping request attribute in the response.
NA
- Create data bag item response with having an id attribute.
-  `rebuild components/infra-proxy-service`
-  To add data using 3rd internal steps https://github.com/chef/automate/blob/master/dev-docs/adding-data/adding_test_data.md#adding-data-to-infra-views
- Data bag item API with the empty data ID
```
curl -sSkH "api-token: $(get_admin_token)" -X POST https://a2-dev.test/api/v0/infra/servers/chef-server-dev-test/orgs/chef-org-dev/data_bags/colors?pretty -d '{"data": {"code": "777777", "id": ""}}'
{
"error": "databag item is required and must contain at least one non-whitespace character",
"code": 3, …
```
=> [infra-proxy-service] Update data bag item create response attribute

.expeditor/nightly.pipeline.yml, .expeditor/verify_private.pipeline.yml
Fixed failing verify_private and nightly pipeline
Due to ha services test failures in verify_private and nightly pipeline. We have added soft_fail: true so that the pipeline does not fail entirely.
verify_private and nightly pipeline should not fail anymore
=> added soft_fail: true to flaky tests in verify_private and nightly pipeline

.studio/infra-proxy-service, components/infra-proxy-service/integration_test/clients_test.go, components/infra-proxy-service/integration_test/databags_test.go, components/infra-proxy-service/integration_test/environments_test.go, components/infra-proxy-service/integration_test/global_test.go, components/infra-proxy-service/integration_test/nodes_test.go, components/infra-proxy-service/integration_test/roles_test.go, components/infra-proxy-service/integration_test/suite_test.go, terraform/test-environments/modules/chef_automate_install/templates/install_chef_automate_cli.sh.tpl
- Cover more integration tests.
- Add `infra_service_load_test_data  -N records -S SERVER_ID -O ORG_ID` to put data into provided chef-server.  
Fixes: https://github.com/chef/automate/issues/4775
- Added the `infra_service_load_test_data` command to load the data into provided chef infra server detail.
- `source .studio/infra-proxy-service`
- Add existing chef-server detail To add data using 3rd internal steps https://github.com/chef/automate/blob/master/dev-docs/adding-data/adding_test_data.md#adding-data-to-infra-views
OR
run `infra_service_load_chef_repo` to spinup and setup the local chef-server.(it also load some data using knife upload)
- Load data using  `infra_service_load_test_data  -N records -S SERVER_ID -O ORG_ID`
=> Fixes test failure and hab infra_server_load_test_data

components/automate-ui/src/app/components/resource-dropdown/resource-dropdown.component.spec.ts
This shows an example of composing a unit test closer to the browser rather than manipulating component internals. Using the `TestHostComponent` strategy we are able to actually create components in the DOM and interact with their controls. In this case, it is a dropdown component that we open with the `Click` method.
NA
All unit tests pass.
cd automate-ui
make unit
NA
=> Add unit tests with TestHostComponent

components/automate-ui/src/app/components/sidebar/sidebar.component.spec.ts, components/automate-ui/src/app/pages/settings-landing/settings-landing.component.ts
Sometimes when we write code, it either reflects some data from elsewhere in the code base or requires certain structure or annotation that other parts of the system depend on. A canonical example of this is protobuf source files. Each such file is, in essence, reflected in a revised format in one or more *.pb.go files in our system. We have a number of meta-tests that ensure the generated files are consistent with the source files as well as checking for required annotations unique to Automate -- see [How Automate Ensures Integrity of Protobuf Files](https://github.com/chef/automate/blob/master/components/automate-gateway/docs/proto-integrity.md).
Similarly in the UI, there are some meta-tests that ensure appropriate consistency and constraints; this PR deals with one such set of tests. …
=> Reinstate sidebar tests to have a safety net

components/automate-ui/src/app/modules/infra-proxy/clients/clients.component.scss, components/automate-ui/src/app/modules/infra-proxy/data-bags-list/data-bags-list.component.html, components/automate-ui/src/app/modules/infra-proxy/data-bags-list/data-bags-list.component.scss, components/automate-ui/src/app/modules/infra-proxy/data-bags-list/data-bags-list.component.ts, components/automate-ui/src/app/modules/infra-proxy/environment-details/environment-details.component.html, components/automate-ui/src/app/modules/infra-proxy/environment-details/environment-details.component.scss, components/automate-ui/src/app/modules/infra-proxy/environment-details/environment-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/environments/environments.component.html, components/automate-ui/src/app/modules/infra-proxy/environments/environments.component.scss
… UI changes
We need to remove the feature flag for the data bag and add some minor UI changes.
https://github.com/chef/automate/issues/4870
I have added changes to remove the feature flag for the data bag and added some minor changes for the UI.
```
STEP 1
STEP 2
navigate to `https://a2-dev.test/infrastructure/client-runs`
```
To add data https://github.com/chef/automate/blob/master/dev-docs/adding-data/adding_test_d …
=> Remove feature flag for the data bag + some minor UI changes

.expeditor/verify_private.pipeline.yml
We are finding consistent failures of the security taskin verify_private pipeline with the error:
```
Local problem: ./bin/openssl.Linux.x86_64 doesn't support "s_client -tls1_3"
```
This seems to be because of there is a breaking change merged to an upstream repository:
https://github.com/drwetter/testssl.sh
By the time, we get a proper commit and fix this, I am keeping this behind soft_fail
Buildkite pipeline should be green.
=> Soft fail security pipeline

components/automate-ui/src/app/helpers/auth/regex.ts, components/automate-ui/src/app/modules/infra-proxy/create-chef-server-modal/create-chef-server-modal.component.spec.ts
Currently, our FQDN validation caps a the top level domain to 5 characters max.  This was an arbitrary decision from when the validation was originally made that should not prevent us from updating.  This particular branch updates that arbitrary number to 25 characters.
#4891 
When entering an FQDN, a user may now use a word longer than 5 letters
Navigate to https://a2-dev.test/infrastructure/chef-servers
Click "Add Chef Server"
in Name field: Enter a name of you choice
in FQDN field: enter `chef-internal`
in IP field, enter any valid IP i.e. `1.2.3.4`
Submit the form by clicking on "Add Chef Server"
Observe a blue successful creation of server ribbon.
All PRs **from Progress …
=> Bump FQDN regex to allow for 25 characters

components/automate-ui/src/app/modules/infra-proxy/create-environment-modal/create-environment-modal.component.html, components/automate-ui/src/app/modules/infra-proxy/create-environment-modal/create-environment-modal.component.scss, components/automate-ui/src/app/modules/infra-proxy/create-environment-modal/create-environment-modal.component.ts, components/automate-ui/src/app/modules/infra-proxy/data-bags-details/data-bags-details.component.html, components/automate-ui/src/app/modules/infra-proxy/data-bags-details/data-bags-details.component.scss, components/automate-ui/src/app/modules/infra-proxy/edit-data-bag-item-modal/edit-data-bag-item-modal.component.scss
we need to fix the below-mentioned points 
- In the Environment list/ Databag list/ client list page height of the search icon is overlapping the search bar border.
- CSS of create and edit pop-up of Databag as it overrides all other pop-ups CSS.
- Search buttons are not keyboard accessible.
- In Create Environment, disable create button if a name already exists.
- In create Environment, change the border color of the text-field when focused.
- Edit databag item -> open item details -> cursor is always pointer
https://github.com/chef/automate/issues/4873
I have added some changes for the UI improvements.
```
STEP 1 …
```
=> Infra proxy edit mode - added some UI improvements

components/compliance-service/reporting/relaxting/util_test.go
Bug fix in the unit test for Index generation for ES.
The test used to fail for the 31st of any month.
Unit Test : TestGetEsIndexNoTimeLast24h should pass on 31st of any Month.
Outside Hab studio.
Go to Automate Repo directory
```bash
cd components/compliance-service/
make lint test-unit
```
All test should pass.
Then change your local system date to 2021-03-31.
Now, again run the tests, this will confirm the test works.
=> fix unittest for esIndex generator, case for 31st of month handled

components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.html, components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.scss, components/automate-ui/src/app/modules/infra-proxy/infra_shared/shared.scss, components/automate-ui/src/app/modules/infra-proxy/org-edit/org-edit.component.html, components/automate-ui/src/app/modules/infra-proxy/org-edit/org-edit.component.scss, components/automate-ui/src/app/modules/infra-proxy/org-edit/org-edit.component.ts, components/automate-ui/src/app/modules/infra-proxy/reset-admin-key/reset-admin-key.component.html, components/automate-ui/src/app/modules/infra-proxy/reset-admin-key/reset-admin-key.component.scss, components/automate-ui/src/app/modules/infra-proxy/reset-admin-key/reset-admin-key.component.ts
Add changes for chef server save button which is expanding when a chef server is renamed.
#4935 
Added the common CSS for the save button in the infra shared folder which we are also using in reset admin key and org details.
Also removed the  ```All changes saved``` because of this we are getting button label as ```SaveSaving..```(for this refer to screenshot).
In chef server details page removed the ```All changes saved``` and added 
**PFA for video**
```
STEP 1
STEP 2 …
```
=> Added server, org, reset admin key update button css changes.

components/automate-ui/src/app/modules/infra-proxy/create-environment-modal/create-environment-modal.component.html, components/automate-ui/src/app/modules/infra-proxy/create-environment-modal/create-environment-modal.component.scss, components/automate-ui/src/app/modules/infra-proxy/create-environment-modal/create-environment-modal.component.ts, components/automate-ui/src/app/modules/infra-proxy/edit-environment-attribute-modal/edit-environment-attribute-modal.component.html, components/automate-ui/src/app/modules/infra-proxy/edit-environment-attribute-modal/edit-environment-attribute-modal.component.scss, components/automate-ui/src/app/modules/infra-proxy/edit-environment-attribute-modal/edit-environment-attribute-modal.component.ts, components/automate-ui/src/app/modules/infra-proxy/environment-details/environment-details.component.html, components/automate-ui/src/app/modules/infra-proxy/environment-details/environment-details.component.scss, components/automate-ui/src/app/modules/infra-proxy/environment-details/environment-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/environments/environments.component.scss, components/automate-ui/src/app/modules/infra-proxy/infra-environment-constraint/infra-environment-constraint.component.html, components/automate-ui/src/app/modules/infra-proxy/infra-environment-constraint/infra-environment-constraint.component.scss, components/automate-ui/src/app/modules/infra-proxy/infra-environment-constraint/infra-environment-constraint.component.ts, components/automate-ui/src/styles/_colors.scss, components/automate-ui/src/styles/_variables.scss
Added Environment related changes: 
- Add no preview image in attributes tab if no JSON available
- Change border-size of details box 1px.
- When we click the button of edit or expand we have to click twice then the pop-up visible. need to update this.
- Edit, Expand, collapse buttons are not keyboard accessible.
[4873](https://github.com/chef/automate/issues/4873)
- Added No preview Images for attributes tab if no JSON available.
- Some border style changes.
- Removed double click on Edit button.
- Added code to Edit, Expand, collapse buttons for keyboard accessible.
- Added validation on Edit modal Save button.
- Edit Cookbook Constraints modal, you can see data in name column.
STEP 1
[default:/src:0]# build …
=> Added Improvement code for Edit Mode

components/config-mgmt-service/grpcserver/node_export.go, components/config-mgmt-service/grpcserver/report_export.go, components/event-feed-service/pkg/server/event_export.go
Signed-off-by: Collin McNeese <cmcneese@chef.io>
Increases the deadline for export functions on nodes, reports and events to 5 minutes from current 1 minute to allow for larger data-sets or less-performant environments.
This is to address #4944 
=> Increases report export deadlines to 5 minutes from 1 minute

components/automate-ui/src/app/app.module.ts, components/automate-ui/src/app/entities/infra-nodes/infra-nodes.actions.ts, components/automate-ui/src/app/entities/infra-nodes/infra-nodes.effects.ts, components/automate-ui/src/app/entities/infra-nodes/infra-nodes.model.ts, components/automate-ui/src/app/entities/infra-nodes/infra-nodes.reducer.ts, components/automate-ui/src/app/entities/infra-nodes/infra-nodes.requests.ts, components/automate-ui/src/app/entities/infra-nodes/infra-nodes.selectors.ts, components/automate-ui/src/app/entities/infra-roles/infra-role.requests.ts, components/automate-ui/src/app/modules/infra-proxy/infra-nodes/infra-nodes.component.html, components/automate-ui/src/app/modules/infra-proxy/infra-nodes/infra-nodes.component.scss, components/automate-ui/src/app/modules/infra-proxy/infra-nodes/infra-nodes.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/infra-nodes/infra-nodes.component.ts, components/automate-ui/src/app/modules/infra-proxy/infra-proxy.module.ts, components/automate-ui/src/app/modules/infra-proxy/infra-search-bar/infra-search-bar.component.html, components/automate-ui/src/app/modules/infra-proxy/org-details/org-details.component.html, components/automate-ui/src/app/modules/infra-proxy/org-details/org-details.component.ts, components/automate-ui/src/app/ngrx.effects.ts, components/automate-ui/src/app/ngrx.reducers.ts, e2e/cypress/integration/ui/infra-proxy/infra-node-list.spec.ts, e2e/cypress/integration/ui/infra-proxy/infra-role-details.spec.ts, e2e/cypress/integration/ui/infra-proxy/infra-roles.spec.ts
We need to add the read-only node list page UI with the search and pagination.
https://github.com/chef/automate/issues/4371
I have added the new UI for the infra node list page UI (read-only), I have covered below mentioned points.
- Infra node list page
- Infra node list with pagination
- Search infra nodes
- Cypress specs
```
STEP 1
STEP 2
```
To add data …
=> [Read only] Infra node list page UI with search and pagination.

.expeditor/nightly.pipeline.yml
In buildKite nightly pipeline is failing in **a1 to a2 migration (dev channel)**, so I have added soft fail to pass the pipeline  
Nightly  pipeline should pass this time
Go to **buildkite** -> **Chef / [chef/automate:master] nightly** -> click on **new bulid** select branch **soft_fail_A1_to_A2_migration**
now **nightly** pipeline will run on branch **soft_fail_A1_to_A2_migration**
=> Soft fail a1 to a2 migration

components/automate-ui/src/app/modules/infra-proxy/cookbooks/cookbooks.component.html, e2e/cypress/integration/ui/infra-proxy/chef-organization-details.spec.ts
Signed-off-by:  Chaitali Mane cmane@progress.com
we need to add the cypress specs for the infra proxy, I have covered the Chef organization details page in this PR.
I have added specs for the organization details page and all tab[Cookbooks, Roles, Environments, Data Bags, Clients]
[4906](https://github.com/chef/automate/issues/4906)
I have added specs for the organization details page and all tab with different scenarios.
Please follow this link to run on your local environment.
=> [Infra-proxy] Cypress specs for the Chef organization details page

components/automate-ui/src/app/helpers/auth/regex.ts, components/automate-ui/src/app/modules/infra-proxy/clients/clients.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/clients/clients.component.ts, components/automate-ui/src/app/modules/infra-proxy/create-client-modal/create-client-modal.component.html, components/automate-ui/src/app/modules/infra-proxy/create-client-modal/create-client-modal.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/create-client-modal/create-client-modal.component.ts, components/automate-ui/src/app/modules/infra-proxy/create-data-bag-modal/create-data-bag-modal.component.html, components/automate-ui/src/app/modules/infra-proxy/create-data-bag-modal/create-data-bag-modal.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/create-data-bag-modal/create-data-bag-modal.component.ts, components/automate-ui/src/app/modules/infra-proxy/create-databag-item-modal/create-databag-item-modal.component.html, components/automate-ui/src/app/modules/infra-proxy/create-databag-item-modal/create-databag-item-modal.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/create-databag-item-modal/create-databag-item-modal.component.ts, components/automate-ui/src/app/modules/infra-proxy/create-environment-modal/create-environment-modal.component.html, components/automate-ui/src/app/modules/infra-proxy/create-environment-modal/create-environment-modal.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/create-environment-modal/create-environment-modal.component.ts, components/automate-ui/src/app/modules/infra-proxy/create-infra-role-modal/create-infra-role-modal.component.html, components/automate-ui/src/app/modules/infra-proxy/create-infra-role-modal/create-infra-role-modal.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/create-infra-role-modal/create-infra-role-modal.component.ts, components/automate-ui/src/app/modules/infra-proxy/data-bags-details/data-bags-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/environments/environments.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/environments/environments.component.ts, components/automate-ui/src/app/modules/infra-proxy/infra-roles/infra-roles.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/infra-roles/infra-roles.component.ts, components/automate-ui/src/app/modules/infra-proxy/infra-search-bar/infra-search-bar.component.html, components/automate-ui/src/app/modules/infra-proxy/infra-search-bar/infra-search-bar.component.scss, components/automate-ui/src/app/modules/infra-proxy/infra-search-bar/infra-search-bar.component.ts, components/automate-ui/src/app/modules/infra-proxy/select-box/src/lib/select-box.component.html, components/automate-ui/src/app/modules/infra-proxy/select-box/src/lib/select-box.component.scss, components/automate-ui/src/app/modules/infra-proxy/select-box/src/lib/select-box.component.ts
- Add validation on name field for the create pop-up of Role/ Data bag / Data bag item/ Client/ Environment Tabs.
- Add validation on search box for  Role/ Data bag item/ Client/ Environment Tabs.
- Add unit testcase for Validate of Role/ Data bag item/ Client/ Environment Tabs.
- Add validation on Run list search bar
#4960 
**VALDATION:-**   Added validation that name can only contain ```alphabets``` **a-z, A-Z**, ```numbers``` **0-9**, ```Underscore```  **_**, ```Hyphen```  **-**.
- Added this above validation on  name/id field for the create pop-up of Role/ Data bag / Data bag item/ Client/ Environment Tabs.
- Added this above validation on search box for  Role/ Data bag item/ Client/ Environment Tabs.
- Added unit testcase for …
=> Added validation on create pop-up, search bar inside org details

components/automate-cs-oc-erchef/habitat/config/sys.config, components/automate-cs-oc-erchef/habitat/default.toml
Not the same as used in the EOL oc_actions product.
resolves #5047
=> This actions config is used by erchef data_collector to send data to automate

components/automate-ui/package-lock.json, components/automate-ui/package.json, components/automate-ui/src/app/app-routing.module.ts, components/automate-ui/src/app/entities/infra-nodes/infra-nodes.actions.ts, components/automate-ui/src/app/entities/infra-nodes/infra-nodes.effects.ts, components/automate-ui/src/app/entities/infra-nodes/infra-nodes.model.ts, components/automate-ui/src/app/entities/infra-nodes/infra-nodes.reducer.ts, components/automate-ui/src/app/entities/infra-nodes/infra-nodes.requests.ts, components/automate-ui/src/app/entities/infra-nodes/infra-nodes.selectors.ts, components/automate-ui/src/app/modules/infra-proxy/infra-node-details/infra-node-details.component.html, components/automate-ui/src/app/modules/infra-proxy/infra-node-details/infra-node-details.component.scss, components/automate-ui/src/app/modules/infra-proxy/infra-node-details/infra-node-details.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/infra-node-details/infra-node-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/infra-nodes/infra-nodes.component.html, components/automate-ui/src/app/modules/infra-proxy/infra-nodes/infra-nodes.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/infra-proxy.module.ts, components/automate-ui/src/app/modules/infra-proxy/org-details/org-details.component.ts, components/automate-ui/src/styles.scss, e2e/cypress/integration/ui/infra-proxy/infra-node-details.spec.ts
we need to create the UI for the infra server node details page, also we need to show the available tags with add/remove tags functionality and update the environment functionality.
https://github.com/chef/automate/issues/4548
I have added the below changes to the node details page.
- show node details
- update environment
- add tags functionality
- remove functionality
- Cypress specs
```
STEP 1
STEP 2
add some sample data and then test the changes using tab …
```
=> Infra node details page UI 

.github/workflows/build.yml, sonar-project.properties
Signed-off-by: PratyakshaSinha <email_address@domain.com>
=> Sonarcloudsetup

components/automate-ui/src/app/modules/infra-proxy/create-data-bag-modal/create-data-bag-modal.component.html, components/automate-ui/src/app/modules/infra-proxy/data-bags-list/data-bags-list.component.html, components/automate-ui/src/app/modules/infra-proxy/data-bags-list/data-bags-list.component.scss, components/automate-ui/src/app/modules/infra-proxy/data-bags-list/data-bags-list.component.ts, e2e/cypress/integration/ui/infra-proxy/infra-databags.spec.ts
Need to add search bar for databags list UI.
[4657](https://github.com/chef/automate/issues/4657)
I have added changes for the databags list page by adding search bar.
STEP 1
STEP 2
navigate to https://a2-dev.test/infrastructure/client-runs
Go to the infrastructure tab from the top navigation …
=> Added search bar for Data Bags list page

.expeditor/verify_private.pipeline.yml
As the cypress test in the pipeline was  flaky.
This will ensure automatic retry 2 times before declaring the pipeline as failure.
=> increased cypress test retry limit to 2

components/automate-ui/src/app/modules/infra-proxy/environment-details/environment-details.component.scss
Chef environment cookbook pins have the first letter of the cookbook automatically capitalized. The desired outcome is to have case processing on the cookbook names as created.
https://github.com/chef/automate/issues/5079
I have added some minor changes to fix this.
```
STEP 1
STEP 2
```
To add data …
=> Fixed Chef Environment Cookbooks constraints capitalisation

components/compliance-service/reporting/relaxting/util_test.go
Unit Test again failed due to 31st day of the month issue.
No change in the index name creation, just the unit test is modified to consider comp-7-s-2021.05.3*
=> Fix unittest for 31st day of month of ES index

components/automate-ui/src/app/modules/infra-proxy/infra-role-details/infra-role-details.component.html, components/automate-ui/src/app/modules/infra-proxy/infra-role-details/infra-role-details.component.ts
Add edit button must be disabled if the environment is not _default.
[5022](https://github.com/chef/automate/issues/5022)
Added disabled edit button if the environment is not _default.
```
STEP 1
STEP 2
```
To add data
https://github.com/chef/automate/blob/master/dev-docs/adding-data/adding_test_data.md#adding-data-to-infra-views
Steps for Role tab:
- Go To Infrastructure -> Chef Servers -> click server name-> click org name -> Go to Role tab
- click role name -> select …
=> Added disable edit button functionality in Infra-Role

.expeditor/nightly.pipeline.yml, .expeditor/verify_private.pipeline.yml, components/automate-cs-bookshelf/habitat/plan.sh, components/automate-cs-nginx/habitat/plan.sh, components/automate-cs-oc-bifrost/habitat/plan.sh, components/automate-cs-oc-erchef/habitat/plan.sh, components/automate-workflow-nginx/habitat/plan.sh, e2e/cypress/integration/ui/infra-proxy/infra-node-details.spec.ts, integration/tests/a1migration.sh, integration/tests/chef_server.sh, integration/tests/chef_server_only.sh
Update Infra Server from 14.1.0 to 14.4.4
This change includes the following:
- Add support for external Elasticsearch 7.0 for new versions of
Automate
- Includes some security related updates
- Adds an omnibus configurable for HSTS max age
More details can be found at: https://docs.chef.io/release_notes_server/
=> Praj+vinay/update chef server to 14.4.4

components/automate-ui/src/app/modules/infra-proxy/environment-details/environment-details.component.scss
Attributes on the environment details page are now displayed in the correct case that came back from the server.
https://github.com/chef/automate/issues/5204
It matches the data you'd see if you ran `knife environment show foo`
????
=> Don't capitalize the attributes in the environment details

integration/tests/chef_server_backup.sh, integration/tests/chef_server_upgrade.sh, integration/tests/ha_chef_server.sh
The `ha_chef_server` scenario fails in the pipeline because of the status test.
The status test requires a file which is not available in the automate environment. The status test is part of the smoke test tag in the pedant. It needs to be skipped everywhere we run `chef-server-ctl test`.
Changes - Skipping the status test while running `chef-server-ctl test`. 
Signed-off-by: Vinay Satish <vinay.satish@progress.com>
=> Fixing ha_chef_server failure

components/automate-ui/src/app/modules/infra-proxy/data-bags-details/data-bags-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/edit-data-bag-item-modal/edit-data-bag-item-modal.component.scss, e2e/cypress/integration/ui/infra-proxy/infra-node-details.spec.ts
In the Data bag item, the id is editable and getting API error so removed the id.
#5024 
Removed the ID from the details page of data bag item and inside edit pop-up
```
STEP 1
STEP 2
```
Steps for Databag Item tab:
-  Go To  Infrastructure -> Chef Servers -> click server name->  click org name -> Go to Databag tab 
- Click any data bag -> click …
=> removed id from details page and edit data bag pop-up.

components/automate-ui/src/app/modules/infra-proxy/client-details/client-details.component.scss, components/automate-ui/src/app/modules/infra-proxy/clients/clients.component.scss, components/automate-ui/src/app/modules/infra-proxy/create-chef-server-modal/create-chef-server-modal.component.html, components/automate-ui/src/app/modules/infra-proxy/create-client-modal/create-client-modal.component.html, components/automate-ui/src/app/modules/infra-proxy/create-data-bag-modal/create-data-bag-modal.component.html, components/automate-ui/src/app/modules/infra-proxy/create-databag-item-modal/create-databag-item-modal.component.html, components/automate-ui/src/app/modules/infra-proxy/create-environment-modal/create-environment-modal.component.html, components/automate-ui/src/app/modules/infra-proxy/create-infra-role-modal/create-infra-role-modal.component.html, components/automate-ui/src/app/modules/infra-proxy/create-org-modal/create-org-modal.component.html, components/automate-ui/src/app/modules/infra-proxy/data-bags-details/data-bags-details.component.html, components/automate-ui/src/app/modules/infra-proxy/data-bags-details/data-bags-details.component.scss, components/automate-ui/src/app/modules/infra-proxy/data-bags-list/data-bags-list.component.scss, components/automate-ui/src/app/modules/infra-proxy/edit-data-bag-item-modal/edit-data-bag-item-modal.component.html, components/automate-ui/src/app/modules/infra-proxy/edit-environment-attribute-modal/edit-environment-attribute-modal.component.html, components/automate-ui/src/app/modules/infra-proxy/edit-environment-attribute-modal/edit-environment-attribute-modal.component.scss, components/automate-ui/src/app/modules/infra-proxy/edit-infra-node-attribute-modal/edit-infra-node-attribute-modal.component.html, components/automate-ui/src/app/modules/infra-proxy/edit-infra-node-modal/edit-infra-node-modal.component.html, components/automate-ui/src/app/modules/infra-proxy/edit-infra-role-modal/edit-infra-role-modal.component.html, components/automate-ui/src/app/modules/infra-proxy/edit-infra-role-modal/edit-infra-role-modal.component.scss, components/automate-ui/src/app/modules/infra-proxy/environment-details/environment-details.component.html, components/automate-ui/src/app/modules/infra-proxy/environment-details/environment-details.component.scss, components/automate-ui/src/app/modules/infra-proxy/environments/environments.component.scss, components/automate-ui/src/app/modules/infra-proxy/infra-roles/infra-roles.component.scss, components/automate-ui/src/app/modules/infra-proxy/reset-client-key/reset-client-key.component.html, components/automate-ui/src/app/modules/infra-proxy/reset-client-key/reset-client-key.component.scss
Signed-off-by: chaitali-mane [cmane@progress.com](cmane@progress.com)
- Infra Server object classes Removed from Environment tab no need to show user that data.
- Aligned create Button is not vertically through all Infra chef servers tabs
- Reduced the margin between search box and list in Data bag details tab
- Removed border on Reset key button after button click in Client detail page only show hover effect
- Added mouse hover styles on buttons in data bag details page and Environment tab, for expand collapse buttons
- Disable feature on create, save button when they are in progress state to all tabs as not able to cancel request.
#4995 
#5000
https://github.com/chef/automate/issues/5001
https://github.com/chef/automate/issues/5014
https://github.com/chef/automate/issues/5017
#5023
- …
=> Added UI improvements

terraform/test-environments/modules/chef_automate_install/main.tf
We are removing the chef-client module from our dev/acceptance pipelines. 
* Our cookbooks are pinned to an older (unsupported) version of Chef Infra Client
* These cookbooks are no longer required (or functional) now that we are under Progress
=> Remove chef-client management from pipeline instances

components/docs-chef-io/content/automate/node_credentials.md
Documentation for setting up windows node. Earlier windows node configuration documentation was not clear and we faced issues setting up windows node for initiating scans from automate.
Windows node setup prerequisites like ports, firewall and WinRM settings must be clear.
Check the docs netlify link
=> Documentation for windows machine configuration

components/automate-ui/src/app/modules/infra-proxy/policy-files/policy-files.component.html, components/automate-ui/src/app/modules/infra-proxy/policy-files/policy-files.component.scss, components/automate-ui/src/app/modules/infra-proxy/policy-files/policy-files.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/policy-files/policy-files.component.ts, e2e/cypress/integration/ui/infra-proxy/infra-policy-file-list.spec.ts
Signed-off-by: Chaitali Mane [cmane@progress.com](cmane@progress.com)
We need search functionality in policy files list
https://github.com/chef/automate/issues/5240
Added search bar functionality for policy files
```
STEP 1
STEP 2
```
Steps for Policyfiles tab:
Go To Infrastructure -> Chef Servers -> click server name-> click on org name -> Policyfiles.
For cypress Build
With occasional exceptions, all PRs **from Progress employees** must tick …
=> Added search bar in policy files

components/docs-chef-io/content/automate/reports.md
Signed-off-by: Rick Marry <rick.marry@gmail.com>
Just added a little verbiage to describe why we require one profile_id and/or one control of said profile id for deep filtering
addresses ambiguities pointed out in issue: #5090
=> add some more verbage to describe requirements for deep filtering

components/automate-deployment/a1-migration/install.rb, components/automate-deployment/basic-a1/install.rb, components/automate-deployment/pkg/airgap/bundle_creator.go, components/automate-deployment/pkg/target/local_target.go, components/automate-deployment/pkg/target/local_target_test.go
`Bintray` has been deprecated. As communicated in https://github.com/chef/release-engineering/issues/1498.
The older versions are moved to `packages.chef.io` as part of https://github.com/habitat-sh/habitat/issues/7312.
https://github.com/chef/release-engineering/issues/1498
- `hab studio enter` 
- `rebuild components/automate-deployment`
- `rebuild components/automate-cli`
- cd to the automate-cli folder like `cd /hab/pkgs/chef/automate-cli/0.1.0/20210618075758/bin/` 
- `./chef-automate airgap bundle create --version VERSION` use version `20180326145220`
*Please …
=> Removed bintray dependencies from deployment

components/automate-ui/src/app/entities/policy-files/policy-file.action.ts, components/automate-ui/src/app/entities/policy-files/policy-file.effects.ts, components/automate-ui/src/app/entities/policy-files/policy-file.reducer.ts, components/automate-ui/src/app/entities/policy-files/policy-file.requests.ts, components/automate-ui/src/app/entities/policy-files/policy-file.selectors.ts, components/automate-ui/src/app/modules/infra-proxy/policy-files/policy-files.component.html, components/automate-ui/src/app/modules/infra-proxy/policy-files/policy-files.component.scss, components/automate-ui/src/app/modules/infra-proxy/policy-files/policy-files.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/policy-files/policy-files.component.ts, e2e/cypress/integration/ui/infra-proxy/infra-policy-file-list.spec.ts
User can delete individual policy file from policy files list. 
https://github.com/chef/automate/issues/5241
Added delete option to each policy file.
```
STEP 1
STEP 2
```
Steps for Policyfiles tab:
Go To Infrastructure -> Chef Servers -> click server name-> click on org name -> Policyfiles.
For cypress Build
All PRs …
=> Added delete option in policy files

components/automate-load-balancer/habitat/config/nginx.conf
Showing blank screen after login into saml.
https://github.com/chef/customer-bugs/issues/438
Added hash key in content-security-policy in Response header.
Goto saml signin page --> click the signin button --> see the saml's login form. If login form shown and able to login to see the dashboard page then it is working as expected.
=> CHEF Automate SAML - Blank Screen 

components/automate-ui/src/app/app-routing.module.ts, components/automate-ui/src/app/entities/policy-files/policy-file-details.reducer.ts, components/automate-ui/src/app/entities/policy-files/policy-file-details.selectors.ts, components/automate-ui/src/app/entities/policy-files/policy-file.action.ts, components/automate-ui/src/app/entities/policy-files/policy-file.effects.ts, components/automate-ui/src/app/entities/policy-files/policy-file.model.ts, components/automate-ui/src/app/entities/policy-files/policy-file.requests.ts, components/automate-ui/src/app/entities/policy-files/policy-file.selectors.ts, components/automate-ui/src/app/modules/infra-proxy/infra-proxy.module.ts, components/automate-ui/src/app/modules/infra-proxy/policy-file-details/policy-file-details.component.html, components/automate-ui/src/app/modules/infra-proxy/policy-file-details/policy-file-details.component.scss, components/automate-ui/src/app/modules/infra-proxy/policy-file-details/policy-file-details.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/policy-file-details/policy-file-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/policy-files/policy-files.component.html, components/automate-ui/src/app/ngrx.reducers.ts, e2e/cypress/integration/ui/infra-proxy/infra-policy-file-details.spec.ts
- Add Policy details page
- Added content tab
- Added Included Policy locks and run list accordion.
#5244 
#5245 
- Added UI for the Policy details page.
- Added UI for  Policy file content tab
- Added cypress test cases for the detail page. 
**PFA Video**
```
STEP 1
STEP 2
```
Steps for policy file  tab: 
1. Go To  Infrastructure -> Chef Servers …
=> Added Policy file details Page.

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-nodes/reporting-nodes.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-nodes/reporting-nodes.component.ts, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profiles/reporting-profiles.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profiles/reporting-profiles.component.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/report-data.service.spec.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/report-data.service.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.ts
Pagination is not updating when user apply any filter.
https://github.com/chef/automate/issues/5322
Added code for updating pagination when filter applied in reports on nodes and profiles.
```
STEP 1
STEP 2
```
Steps for Policyfiles tab:
Go To Compliance -> click Reports -> click Nodes/ Profiles -> click on any filter 
All PRs **from Progress employees** should tick …
=> Updated pagination in Compliance reports

components/automate-dex/habitat/templates/config.yml, components/automate-dex/web/templates/login.html, components/automate-dex/web/templates/password.html, components/automate-dex/web/theme/styles.css
For a user who does not have SAML login setup, the landing page is not setup.
The user is shown the login page directly. 
This change will make sure that every type of user is shown the landing page first
By landing page I mean this page:
https://github.com/chef/automate/issues/5379
- `hab studio enter`
- `rebuild components\automate-dex`
- remove the saml portion of the config in `dev/config.toml`
- The landing page should be shown when you go to `https://a2-dev.test`
- Open `dev/patch.toml`
- make `show = true` for `[global.v1.disclosure]`
- make `show = true` for `[global.v1.banner]`
- `chef-automate config patch dev/patch.toml`
- The disclosure message should be shown on the landing page
- Test the changes in Chrome, …
=> Show Landing screen every time

components/session-service/server/server.go
https://github.com/chef/automate/issues/4853
- Added SameSite=Lax  to cookie
- Pull changes from ```abdul/session_cookie```
- rebuild components/session-service
- check for cookie SameSite flag in browser console -> Application -> Cookies -> session -> Check for sameSite flag is set to "Lax"
=> added sameSite_lax in cookie

components/automate-ui/src/app/app.module.ts, components/automate-ui/src/app/entities/revisions/revision.action.ts, components/automate-ui/src/app/entities/revisions/revision.effects.ts, components/automate-ui/src/app/entities/revisions/revision.model.ts, components/automate-ui/src/app/entities/revisions/revision.reducer.ts, components/automate-ui/src/app/entities/revisions/revision.requests.ts, components/automate-ui/src/app/entities/revisions/revision.selectors.ts, components/automate-ui/src/app/modules/infra-proxy/infra-nodes/infra-nodes.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/infra-proxy.module.ts, components/automate-ui/src/app/modules/infra-proxy/infra_shared/slide-panel.scss, components/automate-ui/src/app/modules/infra-proxy/policy-file-details/policy-file-details.component.html, components/automate-ui/src/app/modules/infra-proxy/policy-file-details/policy-file-details.component.scss, components/automate-ui/src/app/modules/infra-proxy/policy-file-details/policy-file-details.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/policy-file-details/policy-file-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/policy-files/policy-files.component.html, components/automate-ui/src/app/modules/infra-proxy/policy-files/policy-files.component.scss, components/automate-ui/src/app/modules/infra-proxy/policy-files/policy-files.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/policy-files/policy-files.component.ts, components/automate-ui/src/app/modules/infra-proxy/revision-id/revision-id.component.html, components/automate-ui/src/app/modules/infra-proxy/revision-id/revision-id.component.scss, components/automate-ui/src/app/modules/infra-proxy/revision-id/revision-id.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/revision-id/revision-id.component.ts, components/automate-ui/src/app/ngrx.effects.ts, components/automate-ui/src/app/ngrx.reducers.ts, e2e/cypress/integration/ui/infra-proxy/infra-policy-file-details.spec.ts, e2e/cypress/integration/ui/infra-proxy/infra-policy-file-list.spec.ts
- Add Revision Id list on policy file list page
- Add slider panel component
- Add Revision Id button on policy file details page
#5242 
- Added UI for the revision id slider on the list and details page.
- Added cypress test cases for the revision slider page. 
**PFA Video**
```
STEP 1
STEP 2
```
Steps for policy file  tab: 
1. Go To …
=> Added revision id for policy file.

components/automate-ui/src/app/entities/policy-files/policy-file.reducer.ts, components/automate-ui/src/app/modules/infra-proxy/included-policies-details/included-policies-details.component.html, components/automate-ui/src/app/modules/infra-proxy/included-policies-details/included-policies-details.component.scss, components/automate-ui/src/app/modules/infra-proxy/included-policies-details/included-policies-details.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/included-policies-details/included-policies-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/infra-proxy.module.ts, components/automate-ui/src/app/modules/infra-proxy/policy-file-details/policy-file-details.component.html, components/automate-ui/src/app/modules/infra-proxy/policy-file-details/policy-file-details.component.scss, components/automate-ui/src/app/modules/infra-proxy/policy-file-details/policy-file-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/revision-id/revision-id.component.html, components/automate-ui/src/app/modules/infra-proxy/revision-id/revision-id.component.ts, components/automate-ui/src/styles/_colors.scss, components/automate-ui/src/styles/_variables.scss, e2e/cypress/integration/ui/infra-proxy/infra-policy-file-details.spec.ts
- Add included Policy file details page
- Add revision button on included policy file slider
#5246 
- Added included Policy file details page in slider and ```Go to policyfile details page``` button
- Added revision button on included policy file slider
- Added cypress test cases for the detail page. 
**PFA Video**
```
STEP 1
STEP 2
```
Steps for …
=> Added included policyfile details info.

components/automate-ui/src/app/modules/infra-proxy/policy-file-details/policy-file-details.component.html, e2e/cypress/integration/ui/infra-proxy/infra-policy-file-details.spec.ts
Policyfiles is Chef Infra term. They are not files containing policies.
They are a very specific feature that we need to get the name right for.
See that Policyfiles shows up as a single word when you browse them in the UI.
=> Policyfiles is a single word

.expeditor/config.yml
Removed some custom logic that would force the staging area to unlock every day at 2am. This was actually dangerous because it could prematurely unlock the staging area. To avoid this, Expeditor will now automatically unlock staging areas after 24hrs. 
=> Remove custom staging area unlock logic

components/nodemanager-service/managers/azure/azure.go, components/nodemanager-service/managers/azure/azure_test.go
While filtering nodes in Search Nodes API. Name and region was not getting filtered properly. 
- When we searched for a resource by name it used to return everything in the resource group for that particular resource.
- When we filtered by region it used to return resources in other region as well
The code changes apply a filter just before returning the data from the Search Nodes API. This helps us to get only the desired result. Due to the limitation in azure API where we cannot search for Virtual Machines, we had to introduce this filtering at our end.
https://github.com/chef/automate/issues/5315
- Searching for name should return only that node which matches its name
- Filtering by region should return resources belonging to that …
=> Fix for search nodes api in azure

components/automate-ui/src/app/modules/infra-proxy/policy-groups-list/policy-groups-list.component.html, components/automate-ui/src/app/modules/infra-proxy/policy-groups-list/policy-groups-list.component.ts, components/automate-ui/src/app/modules/infra-proxy/policy-groups/policy-groups.component.html, components/automate-ui/src/app/modules/infra-proxy/policy-groups/policy-groups.component.scss, components/automate-ui/src/app/modules/infra-proxy/policy-groups/policy-groups.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/policy-groups/policy-groups.component.ts, e2e/cypress/integration/ui/infra-proxy/infra-policy-groups-list.spec.ts
We need to add search functionality for Policy groups.
https://github.com/chef/automate/issues/5389
Added search bar UI and search functionality for Policy groups.
```
STEP 1
STEP 2
```
Go To Infrastructure -> Chef Servers -> click server name-> click on org name -> Policy Groups tab
Where you can see the search bar UI for a list of groups.
For cypress Build
With …
=> Added search functionality in policy group

components/chef-ui-library/package-lock.json, components/chef-ui-library/package.json
file name: …/chef-ui-library/package-lock.json
Upgrade tar to version 3.2.3 or later. For example:
```
"dependencies": {
"tar": ">=3.2.3"
}
```
or…
```
"devDependencies": {
"tar": ">=3.2.3"
}
```
Vulnerable versions: < 3.2.3
Patched version: 3.2.3
https://github.com/chef/automate/issues/5429
I have upgrade the tar version to 3.2.3
=> Upgrade the tar version to 3.2.3  -  chef-ui-library

components/data-feed-service/service/data-feed-aggregate-task.go, components/data-feed-service/service/data-feed-service.go, components/data-feed-service/service/data-feed-service_test.go
We get the Serial Number in this json path: 
`attributes` -> `automatic` -> `dmi` -> `system` -> `serial_number`
Which is used by Chef Automate 2 to populate `node` -> `serial_number`
Earlier Chef Automate 2 reads value for Windows Platform from this location : 
`attributes` -> `automatic` -> `kernel` -> `os_info` -> `serial_number` 
which contains windows os installation disk serial number. 
And this is used to populate `node` -> `serial_number`.
For case of Chef Infra Client version 12.x, it doesn't have `attributes` -> `automatic` -> `dmi` data populated, then we should not populate any value for serial number in this location: `node` -> `serial_number` and keep it empty ("").
https://github.com/chef/automate/issues/5430
Chef …
=> Change serial number mapping for windows

terraform/test-environments/modules/chef_automate_install/templates/install_chef_automate_cli.sh.tpl
Post Merge is failing because chef-ci cannot log into the VM  due to ssh being configured with AllowUsers and not included chef-ci user.
=> Fix hardened  image to allow chef-ci to login

.studio/compliance-service, components/compliance-service/reporting/relaxting/profiles.go, components/compliance-service/test_data/audit_reports_one/2018-02-09_debian(2)-zeta-linux(f)-apache(p)-failed.json, components/compliance-service/test_data/audit_reports_one/send_to_data_collector.sh
Signed-off-by: Rick Marry <rick.marry@gmail.com>
this fixes bug #5399
This PR fixes a bug where control tags are not making in with the profile as it's stored in elasticsearch
In order for this bug fix to work, the profiles that are currently in elasticsearch need to be removed and compliance-service needs to be restarted.  The removal and restart will cause the profiles to be re-ingested into elastic and the control tags will now be present.  From that point forward, any inspec reports that are sent up to automate will carry with them, the control tags for each respective profile.
*N.B.  already ingested reports will not ever have the tags for the controls as they are decorated with them upon ingestion which has already happened prior to this fix
From within hab studio:
`rebuild …
=> fix tags so that they are rendered to string directly from struct

components/automate-ui/src/app/modules/infra-proxy/client-details/client-details.component.html
The breadcrumbs are all capitalized except for clients, which is kinda
weird.
Before: 
It's consistent
=> Capitalize clients to match other breadcrumbs

components/automate-ui/src/app/modules/infra-proxy/included-policies-details/included-policies-details.component.html, components/automate-ui/src/app/modules/infra-proxy/policy-file-details/policy-file-details.component.html, e2e/cypress/integration/ui/infra-proxy/infra-policy-file-details.spec.ts
The Policyfiles detail page incorrectly has POLICY FILE. This fixes it to POLICYFILE
Before:
Correct branding in the UI
Great question
=> Fix another place where Policyfile needs to be a single word

components/automate-ui/src/app/modules/infra-proxy/included-policies-details/included-policies-details.component.html, components/automate-ui/src/app/modules/infra-proxy/policy-file-details/policy-file-details.component.html
Make sure we use Chef Infra instead of Chef in some Policyfiles details pages.
Before:
Branding for products is correct.
???
=> Fix Chef Server -> Chef Infra Server branding

components/user-settings-service/pkg/storage/postgres/schema/sql/02_user_settings.up.sql
Signed-off-by: Rick Marry <rick.marry@gmail.com>
**from hab:**
`rebuild components/user-settings-service`
`chef-automate dev psql postgres`
**then from psql:**
`\c chef_user_settings_service`
`select * from user_settings;`
_default val should be:_
`"default_value": "ddd, DD MMM YYYY HH:mm:ss [UTC]",`
_value should be:_
`"value": "ddd, DD MMM YYYY HH:mm:ss [UTC]",`
=> change default setting for time format for user settings

.buildkite/hooks/pre-command, .expeditor/buildkite/semgrep.sh
Modifying some pipeline scripts to account for new "main" branch
master branch was renamed to main today
=> Modifying some pipeline scripts to account for new "main" branch

components/automate-workflow-server/rebar.config
Buildkite is failing to build the workflow server package since some of the dependencies maintained by chef have moved from master to main
- Tried  running the build on buildkite for the branch and it build successfully. 
https://buildkite.com/chef/chef-automate-main-habitat-build/builds?branch=kallol%2Ffix_git_dependency_workflow
=> Moving the chef repo dependencies of workflow server from master to main

components/infra-proxy-service/server/servers.go, components/infra-proxy-service/server/servers_test.go
User can able to add the server using FQDN or IP address, means one of these fields can be used to add the server with infra chef server API.
https://github.com/chef/automate/issues/5585
I have added some changes for the add server API, and allow users to add the server using only the FQDN or IP address.
```
```
using the postman API tool you can user pass the only FQDN or IP address to add the server.
=> Adding chef server using FQDN or IP address

components/infra-proxy-service/server/roles.go
Update Role even if the description field is blank.
#5317 
Updated Role even if the description field is blank.
```
```
Steps to test:
1. Ensure Chef Infra Server is running. If it is not start it with ```start_chef_server```
2. Create a role using ```knife create role test1```
3. Go to Roles tab -> click ```test1``` role -> edit runlist or attribute and updating successfully if description is null.
*Please add a note next to any checkbox above if you are NOT ticking …
=> [infra-proxy-service]Removed validation for description field while update role.

components/automate-ui/src/app/pages/data-feed-create/data-feed-create.component.scss
=> Css fix for gap between flex children in Safari

components/automate-load-balancer/habitat/config/automate-host-header-validation.conf, components/automate-load-balancer/habitat/config/nginx.conf, components/automate-ui/src/app/entities/destinations/destination.actions.ts
Signed-off-by: Mansoor <mchengat@msystechnologies.com>
Attackers can use DNS Rebinding to bypass any IP or firewall based access restrictions that may be in place, by proxying through their target's browser. 
https://github.com/chef/automate/issues/4850
Added validation of  Host HTTP header for  the incoming requests. 
* Clone the PR changes
* Enter hab studio using hab studio enter
* rebuild components/automate-load-balancer
* Add multiple hostnames to /etc/hosts file and try sending a request to 80/443.
=> Adding arbitrary host header check for Http connection

components/infra-proxy-service/storage/postgres/migration/sql/05_user_management.down.sql, components/infra-proxy-service/storage/postgres/migration/sql/05_user_management.up.sql
I have added the script for table 'org_users'
https://github.com/chef/automate/issues/5715
I have added script for the table 'org_users' in user management to map the users with organisation in automate
=> Script added for table 'org_users'

components/automate-ui/src/app/entities/servers/server.effects.ts, components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.html, components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.scss, components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/chef-servers-list/chef-servers-list.component.html, components/automate-ui/src/app/modules/infra-proxy/chef-servers-list/chef-servers-list.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/chef-servers-list/chef-servers-list.component.ts, components/automate-ui/src/app/modules/infra-proxy/create-chef-server-modal/create-chef-server-modal.component.html, components/automate-ui/src/app/modules/infra-proxy/create-chef-server-modal/create-chef-server-modal.component.scss, components/automate-ui/src/app/modules/infra-proxy/create-chef-server-modal/create-chef-server-modal.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/create-chef-server-modal/create-chef-server-modal.component.ts, components/automate-ui/src/app/types/types.ts, e2e/cypress/integration/ui/infra-proxy/chef-server-details.spec.ts, e2e/cypress/integration/ui/infra-proxy/chef-servers.spec.ts
We currently require both the FQDN and the IP address of the chef server. We need to change and make it optional so add a dropdown in which the user can select any option of FQDN or IP address
#4945 #4998 
Added a dropdown in which the user can select any option of FQDN or IP address
```
STEP 1
STEP 2
```
Steps for policy file  tab: 
1. Go To …
=> Added dropdown for fqdn and ip address.

.studio/common
this is a follow up to pr 5741 where for hab package refresh, we need to set one env var to dev but just for builds.. we do so by making it a local var
=> set the HAB_BLDR_CHANNEL to dev just for builds

components/automate-ui/src/app/modules/infra-proxy/data-bags-details/data-bags-details.component.html, components/automate-ui/src/app/modules/infra-proxy/data-bags-details/data-bags-details.component.ts
Need to disable the edit button if we have data bag item as encrypted 
#5045 
Disabled edit button if we have data bag item as encrypted 
```
STEP 1
STEP 2
```
To add encrypted databag : 
1. inside hab studio run local dev server: 
-  start_chef_server
- infra_service_load_chef_repo
- converge_policyfile_chef_client
2. inside chef-workstation:
go …
=> Disabled edit button if databag item is encrypted.

components/automate-ui/src/app/entities/destinations/destination.model.ts, components/automate-ui/src/app/entities/destinations/destination.requests.ts, components/automate-ui/src/app/pages/data-feed-create/data-feed-create.component.html, components/automate-ui/src/app/pages/data-feed-create/data-feed-create.component.scss, components/automate-ui/src/app/pages/data-feed-create/data-feed-create.component.spec.ts, components/automate-ui/src/app/pages/data-feed-create/data-feed-create.component.ts, components/automate-ui/src/app/pages/data-feed/data-feed.component.spec.ts, components/automate-ui/src/app/pages/data-feed/data-feed.component.ts, e2e/cypress/integration/ui/settings/data-feed/data-feed-create.spec.ts
Amazon S3 is enabled. The modal that pops up helps us to test connection to any S3 bucket as well as enable us to save that in the data feed table.
Data Feeds UI: S9: New S3 Integration Overlay  #5581 
- Amazon S3 options is shown
- Form should open on clicking S3  integration
- Test connection should be working
- Save integration should be working
```
STEP 1
STEP 2
make serve
To run cypress test
cd e2e
Type feat to enable data-feed
Navigate to settings/data-feeds
``` …
=> Amazon S3 Integration UI #5581

components/automate-ui/src/app/modules/infra-proxy/policy-file-details/policy-file-details.component.html, components/automate-ui/src/app/modules/infra-proxy/policy-files/policy-files.component.html
Improve Policyfiles text in Infra Views
1. Make Policyfiles a single capitalized word. It's a product term.
2. When there are no included policyfiles dont' say "no policy files available". That makes it sound like an error. There's just nothing included.
Proper branding for Policyfiles and proper message when no Policyfile is included.
=> Improve Policyfile text in Infra Views

components/automate-ui/src/app/entities/servers/server.actions.ts, components/automate-ui/src/app/entities/servers/server.effects.ts, components/automate-ui/src/app/entities/servers/server.model.ts, components/automate-ui/src/app/entities/servers/server.reducer.ts, components/automate-ui/src/app/entities/servers/server.requests.ts, components/automate-ui/src/app/entities/servers/server.selectors.ts, components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.html, components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.scss, components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.ts
Need to add users tab for server users in server details page.
Need to update layout for metadata.
https://github.com/chef/automate/issues/5559
Added users tab for server users in server details page.
Updated layout for metadata.
```
STEP 1
STEP 2
```
Go To Infrastructure -> Chef Servers -> Click on any Chef Infra Server -> on details will see changes.
With occasional exceptions, all PRs **from Progress employees** must …
=> Added users tab in server details page

.studio/infra-proxy-service
Command to add the sample data of automate infra server users
https://github.com/chef/automate/issues/5773
I have added changes to load the sample data of infra server users, using command we can add the sample users.
You need to enter the hab studio then check the services are running.
To start the services you can use ```start_infra_proxy_service``` or ```start_all_services```
Then run ```infra_service_load_sample_users```
Option:
-N: Number of records, default 50
Example:
```infra_service_load_sample_users -N 100```
=> Command to add the sample automate infra server users

components/license-control-service/migrations/001_deployment.up.sql, components/license-control-service/pkg/server/grpc.go, components/license-control-service/pkg/storage/storage.go
Store the unique id for every deployment in DB
https://github.com/chef/automate/issues/5613
I have added changes to store the deployment id in DB at the start of license control service
```
rebuild components/license-control-service
```
Steps to test:
1. To start the services use, ```start_all_services```
2. Check the deployment id entry in ```deployment``` table of ```chef_license_control_service``` database
3. For the next start of license control service, this entry will be updated with unique id
=> Store the unique id for every deployment in DB

components/automate-cli/cmd/chef-automate/automateConstants.go, components/automate-cli/cmd/chef-automate/config.go
config patch-command mapping
to patch automate config in A2HA mode, we need to have config patch command mapping
**chef-automate config patch </path/to/autoamte-config.toml>**
https://app.zenhub.com/workspaces/the-delta-quadrant-5fc7c4c3922dc10021323fa6/issues/chef/automate/5708
Dev Done, Dev Tested
rebuild/build component/automate-cli
=> Config Patch command mapping 

components/automate-ui/src/app/helpers/auth/regex.ts, components/automate-ui/src/app/modules/infra-proxy/infra-environment-constraint/infra-environment-constraint.component.html, components/automate-ui/src/app/modules/infra-proxy/infra-environment-constraint/infra-environment-constraint.component.scss, components/automate-ui/src/app/modules/infra-proxy/infra-node-details/infra-node-details.component.html, components/automate-ui/src/app/modules/infra-proxy/infra-node-details/infra-node-details.component.scss, components/automate-ui/src/app/modules/infra-proxy/infra-nodes/infra-nodes.component.spec.ts, e2e/cypress/integration/ui/infra-proxy/infra-node-details.spec.ts, e2e/cypress/integration/ui/infra-proxy/infra-role-details.spec.ts
When the spinner loading, the user should not able to click add/ delete button.
The cookbook constraint window input appears to require x.y.z format, but this is not required for versions in a constraint. ~> 2.0 is entirely valid.
https://github.com/chef/automate/issues/5190
https://github.com/chef/automate/issues/4992
Updated code for when the spinner loading, the user should not able to click add/ delete button.
The cookbook constraint window input appears to require x.y.z format, but this is not required for versions in a constraint. ~> 2.0 is entirely valid.
```
STEP 1
STEP 2 …
```
=> Infra server UI improvements

components/docs-chef-io/content/automate/_index.md
Signed-off-by: Kimberly Garmoe <kgarmoe@chef.io>
Users should be able to start Automate in the quickstart.
You really can't start Automate with 4GB. Changes the doc to 8.
=> Increase RAM in quickstart demo

components/automate-ui/src/app/pages/+compliance/+node-credentials/node-credentials-list/node-credential-list.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+node-credentials/node-credentials-list/node-credential-list.component.ts, components/automate-ui/src/app/pages/+compliance/+node-credentials/node-credentials.routing.ts, components/automate-ui/src/app/pages/+compliance/+scanner/containers/nodes-add/nodes-add.component.html, components/automate-ui/src/app/pages/+compliance/+scanner/containers/nodes-edit/nodes-edit.component.html, e2e/cypress/integration/ui/compliance/scan_job/add_update_node.spec.ts
Through this Pr now it is possible to open add new credential from scan job
#6069 
```
STEP 1
STEP 2
```
https://user-images.githubusercontent.com/47217471/140911630-52655b37-fa6a-4402-beea-61a786b19438.mov
=> open add new credential from scan job

components/automate-cluster-ctl/libexec/cluster-deploy, scripts/bundle_creation.sh, terraform/a2ha-terraform/deployment-makefile/Makefile
This Pr will add --dev flag in automate-cluster-ctl which will help us to download dev channel manifest and create airgap bundle for that packages.
This will only available for testing dev packages 
automate-cluster-ctl deploy --dev
=> adding dev channel support for deployment

components/automate-backend-elasticsearch/habitat/cert.sh, components/automate-backend-elasticsearch/habitat/plan.sh, components/automate-backend-pgleaderchk/habitat/hooks/run, components/automate-backend-postgresql/habitat/cert.sh, components/automate-backend-postgresql/habitat/plan.sh
automate-backend-elasticsearch and automate-backend-postgresql certificate path changes 
In RootCA cert , key file was used instead of pem file and there were pinned some dependencies.
=> automate-backend-elasticsearch and automate-backend-postgresql certificate path changes

components/automate-es-gateway/habitat/plan.sh, components/automate-load-balancer/habitat/plan.sh, components/automate-openjdk/habitat/plan.sh
Signed-off-by: Bartłomiej Wesołowski <bartlomiej.wesolowski@relativity.com>
- Updated Nginx version in automate-es-gateway and automate-load-balancer from 1.19.2 to 1.21.3 to fix security vulnerability
- Updated OpenJDK version in automate-openjdk from 11.0.10 to 11.0.12 to fix security vulnerability
Vulnerability ticket for Nginx: [CVE-2021-23017](https://nvd.nist.gov/vuln/detail/CVE-2021-23017)
Vulnerability tickets for OpenJDK: [CVE-2021-2161](https://nvd.nist.gov/vuln/detail/CVE-2021-2161), [CVE-2021-2163](https://nvd.nist.gov/vuln/detail/CVE-2021-2163)
Fix for #5087 
Partial fix for #4703 
*Please add a …
=> Update Nginx and OpenJDK versions

components/automate-ui/src/app/pages/notification-details/notification-details.component.html
On the notification details page, the webhook Type and the Failure Type were not shown properly.
On page load users should see selected data in the dropdown list instead they were seeing empty data or the first item from the dropdown list
#6140 
Now user should see the selected webhook Type and Failure Type on the page reload or shifting from the current page to the previous page
```
STEP 1
STEP 2
```
Uploading Screen Recording 2021-11-16 at 2.31.39 PM.mov… …
=> Selected type in dropdown is not shown properly in notification details page

.expeditor/verify_private.pipeline.yml, integration/tests/manual_upgrade.sh
Manual upgrade integration test in private pipeline was breaking due to golang not supporting common name feild anymore in ssl certificate. We had to add GODEBUG=x509ignoreCN=0 to enable support for that field
=> fixed manual upgrade private pipeline

components/automate-ui/src/app/pages/+compliance/+node-credentials/node-credential-details/node-credential-details.component.html, components/automate-ui/src/app/pages/+compliance/+node-credentials/node-credential-details/node-credential-details.component.scss, components/automate-ui/src/app/pages/+compliance/+node-credentials/node-credential-details/node-credential-details.component.ts
Signed-off-by: Shivangi Singh <shisingh@progress.com>
Bug : 1. Save button for 'Reset credentials' for the node credential tab should work fine for all -: sudo, ssh and winrm.
2.Save button css should be changed.
fix button issue and loading when we change cred for second time in node credential tab : #6078 
1. Save button for 'Reset credentials' for the node credential tab should work fine for all -: sudo, ssh and winrm.
2.Save button css for reset credentials should be corrected.
```
STEP 1
STEP 2
``` …
=> Node credential button fix

components/automate-cli/cmd/chef-automate/automateClusterCtlUtil.go, components/automate-cli/cmd/chef-automate/automateHAAwsDeployment.go, components/automate-cli/cmd/chef-automate/automateHADeployExistingInfra.go, components/automate-cli/cmd/chef-automate/gather-logs.go, components/automate-cli/cmd/chef-automate/genA2haRbTmpl.go, components/automate-cli/cmd/chef-automate/info-ha.go, components/automate-cli/cmd/chef-automate/initConfigHa.go, components/automate-cli/cmd/chef-automate/initConfigHaTmpl.go, components/automate-cli/cmd/chef-automate/provisionInfraHa.go, components/automate-cli/cmd/chef-automate/secretsHa.go, components/automate-cli/cmd/chef-automate/sshAutomateHA.go, components/automate-cli/cmd/chef-automate/testHA.go, components/automate-cli/cmd/chef-automate/workspaceHa.go, components/automate-cluster-ctl/lib/cluster/secrets.rb, components/automate-cluster-ctl/libexec/cluster-info, components/automate-cluster-ctl/libexec/cluster-secrets, components/automate-cluster-ctl/libexec/cluster-status, terraform/a2ha-terraform/reference_architectures/aws/outputs.tf
Exit message once deployment or provisioning completed,
Showing Spinner for long waiting tail log refresh
Showing Spinner for each command execution
Take user confirmation on Secrets init
Take user Password or input for Secrets Set sudo_password/ fe_sudo_password, be_sudo_password
Fixes formating issue for status command
Fixes formating issue for info command
=> Exit message on deployment completion, Secrets issue fixes, Info & status formatting issue fixes

components/automate-dex/habitat/plan.sh
There is a need to validate the request id before we query the DB.
This requires us to make the changes in dex code base which is a third party code. 
The process to make the change in the third party code and getting a merge approval can be troublesome and time consuming. 
Hence the repo is forked and the changes are made in a branch on dex 2.27 version. 
https://github.com/chef/dex-1/tree/add_request_validators
This PR is to make changes in the plan file to pull the code from the branch and build it.
- The PR needs to be approved though not merged https://github.com/chef/dex-1/pull/4
- The dex should invalidate requests with invalid auth code 
- `hab studio enter`
- rebuild components/automate-dex
- Check the UI or make dex api calls as …
=> Build forked dex in the plan file

components/automate-cli/cmd/chef-automate/automateClusterCtlUtil.go
fixes for double time output print
Some of command mapping were showing output for double time, It is fixed now
Dev done, Dev tested
build component/automate-cli
=> Fixes for double time output

components/automate-cli/cmd/chef-automate/automateConstants.go, components/automate-cli/cmd/chef-automate/automateHAAwsDeployment.go, components/automate-cli/cmd/chef-automate/deployHa.go, components/automate-cli/cmd/chef-automate/info-ha.go, components/automate-cli/cmd/chef-automate/secretsHa.go, components/automate-cli/cmd/chef-automate/sshAutomateHA.go, components/automate-cli/cmd/chef-automate/testHA.go, components/automate-cli/cmd/chef-automate/workspaceHa.go
As all mapped HA command is part of automate, sometime user might try to run automate HA command in non HA env, we have to show graceful error instead of system failure error.
Dev tested, Dev done
=> show graceful error for invalid bastion

terraform/a2ha-terraform/reference_architectures/existing_nodes/outputs.tf
terraform output for exiting node for ssh
Terraform output in existing infra deployment don't contain ssh info for following servers...
chef-server
automate
postgersql
due to this chef-automate ssh is also failing as it use terraform.tfstate file
https://app.zenhub.com/workspaces/the-delta-quadrant-5fc7c4c3922dc10021323fa6/issues/chef/automate/6261
Dev Done
build automate-backend-deployment
=> terraform output for exiting node for ssh

components/automate-ui/src/app/entities/download-reports/download-reports.service.ts, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.scss, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.spec.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.ts, components/automate-ui/src/environments/environment.no_auth.ts, components/automate-ui/src/environments/environment.prod.ts, components/automate-ui/src/environments/environment.ts
Add open report menu item in download-dropdown button and show list of download-reports with its status in the Report panel when you click the open report.
#6191, #6193
Fetched the dowload-reports with its status and shown in the report panel(side panel) when you click open report menu. 
inside hab,
- rebuild components/automate-ui
- rebuild components/automate-gateway/
- rebuild components/automate-deployment/
- rebuild components/report-manager-minio-gateway/
- rebuild components/report-manager-service/
- rebuild components/compliance-service/
- rebuild components/automate-gateway/
- …
=> Show list of Reports in the Report panel

components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.scss
Align the tool-tip properly to show the entire message without missing any part of it.
#6321
Aligned the tool-tip properly to show the entire message in the report panel.
inside hab, …
=> Align the tooltip missing part in report panel (LCR)

components/automate-elasticsearch/habitat/plan.sh, components/automate-openjdk/habitat/plan.sh
1. ElasticSearch version upgraded from 6.8.14 to 6.8.21
2. AdoptOpenJDK version upgraded from 11.0.12+7 to 11.0.13+8
3. Fixed some CVE issues appearing in log4j
[ElasticSearch 6.8.21 Release Notes](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/release-notes-6.8.21.html)
[Adoptium OpenJDK Release](https://adoptium.net/release_notes.html)
All things are building correctly and running fine.
`hab studio enter`
`start_all_services`
```
rebuild components/automate-openjdk
rebuild components/automate-elasticsearch
rebuild components/config-mgmt-service
rebuild components/deployment-service
rebuild components/nodemanager-service
rebuild …
```
=> ES upgrade to 6.8.21, AdoptOpenJDK version 11.0.13+8

components/automate-ui/src/app/modules/infra-proxy/infra-node-details/infra-node-details.component.scss
on infra views node details page have `Run list` tab, UI is not same as another tab, some extra side space is there, we need to remove this extra space.
https://github.com/chef/automate/issues/5256
I have added some CSS changes to fix this.
- Go to Node tab
- From node list click any node
- click on Run list tab
- where you see side space is extra
- ### :white_check_mark: Checklist
=> Removed extra space in Node Run list tab

components/automate-ui/src/app/modules/infra-proxy/create-client-modal/create-client-modal.component.scss, components/automate-ui/src/app/modules/infra-proxy/reset-client-key/reset-client-key.component.html, components/automate-ui/src/app/modules/infra-proxy/reset-client-key/reset-client-key.component.scss
on the client details page, we have 2 modal popups, the first is for reset confirmation and the second is for resetting the key, we need to set the different widths for both the modals.
https://github.com/chef/automate/issues/5288
I have added CSS changes to set different widths for both of the modals.
Steps for Client tab:
- Go To Infrastructure -> Chef Servers -> click server name-> click org name -> Go to Client tab --> click on create client button
- Go To Infrastructure -> Chef Servers -> click server name-> click org name -> Go to Client tab --> click on any client --> click on reset Key button --> in modal reset key
All PRs …
=> Fixed reset client modal width on scroll

components/automate-elasticsearch/habitat/plan.sh
1. ElasticSearch version upgraded from 6.8.21 to 6.8.22
3. Fixed some CVE issues appearing in log4j
[ElasticSearch 6.8.22 Release Notes](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/release-notes-6.8.22.html)
All things are building correctly and running fine.
`hab studio enter`
`start_all_services`
```
rebuild components/automate-elasticsearch
rebuild components/config-mgmt-service
rebuild components/deployment-service
rebuild components/nodemanager-service
rebuild components/ingest-service
rebuild components/data-feed-service
rebuild components/event-feed-service
```
Wait for some time and then check if all services are up and running …
=> ES upgrade to 6.8.22

components/automate-ui/src/app/modules/infra-proxy/chef-servers-list/chef-servers-list.component.ts, components/automate-ui/src/app/modules/infra-proxy/create-chef-server-slider/create-chef-server-slider.component.html, components/automate-ui/src/app/modules/infra-proxy/create-chef-server-slider/create-chef-server-slider.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/policy-groups-list/policy-groups-list.component.html, e2e/cypress/integration/api/iam/infra_clients_actions.spec.ts, e2e/cypress/integration/api/iam/node_actions.spec.ts
Need to add a code for the WebUI key in the create the chef-server slider.
https://github.com/chef/automate/issues/6350
Add a code for the WebUI key in the create the chef-server slider.
```
STEP 1
STEP 2
```
Go To Infrastructure -> Chef Servers -> Click on 'Add Chef Infra Server' -> slider will open.
All PRs **from Progress employees** …
=> UI-API integration for web UI key

components/automate-ui/src/app/entities/download-reports/download-reports.service.ts, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.ts
Show loader when you click on download link inside open reports panel.
#6429
loader popup shown when you click on download link inside open reports panel.
inside hab, …
=> show loader when click on download link

components/automate-ui/src/app/modules/infra-proxy/create-chef-server-slider/create-chef-server-slider.component.html, components/infra-proxy-service/server/proxy.go
we need to add the changes in infra proxy APIs to use WebUI key instead of admin private key.
https://github.com/chef/automate/issues/6280
I have added the changes in infra proxy APIs to use WebUI key instead of admin private key for the followings:
- Cookbooks
- Policy Files
- Policy Groups
- Clients
```
```
Steps to test:
1. Ensure Chef Infra Server is running. If it is not start it with ```start_chef_server```
2. Add the chef-server test environment credentials and extract the SERVER IDs
3. Test all the APIs of cookbooks, Policy Files, Policy Groups,Clients
4. If web ui key is available with server then APIs should use it.
5. In case it's not available then use org admin key.
With occasional exceptions, …
=> Changes to use web ui key in all the Infra Proxy APIs for Cookbooks, Policy Files, Policy Groups, Clients 

.expeditor/verify_private.pipeline.yml, .license_scout.yml, components/automate-cs-bookshelf/habitat/plan.sh, components/automate-cs-nginx/habitat/plan.sh, components/automate-cs-oc-bifrost/habitat/plan.sh, components/automate-cs-oc-erchef/habitat/hooks/run, components/automate-cs-oc-erchef/habitat/plan.sh, integration/tests/a1migration.sh, integration/tests/chef_server.sh, integration/tests/chef_server_backup.sh, integration/tests/chef_server_only.sh, integration/tests/chef_server_upgrade.sh, integration/tests/ha_chef_server.sh
Upgrading the chef server to latest version - 14.11.36.
=> Upgrading chef server components with the latest version

components/automate-deployment/habitat/plan.sh, lib/platform/pg/exporter.go, lib/platform/pg/exporter_test.go
Due to issues with Backup failure on postgresql13 version we needed the client library to be upgraded in automate
#6490 6490
=> Upgrading postgres client library to postgresql13-client

components/infra-proxy-service/storage/postgres/migration/sql/07_migration.down.sql, components/infra-proxy-service/storage/postgres/migration/sql/07_migration.up.sql, components/infra-proxy-service/storage/postgres/migration/sql/README.md
Signed-off-by: sonali wale <sonali.wale@progress.com>
Database scripts for migration tables
https://github.com/chef/automate/issues/6348
I have added script to store the migration status for a chef server.
Tables as ```migration```,```migration_status``` and ```migration_type```.
=> Database script for migration tables

components/infra-proxy-service/cmd/infra-proxy-service/commands/serve.go, components/infra-proxy-service/config/service.go, components/infra-proxy-service/server/orgs.go, components/infra-proxy-service/service/service.go, components/infra-proxy-service/test/test.go
When a organisation is migrated from the chef server to automate, an IAM project needs to be linked with it. 
So added the call to project create service to create the project with the name of serverId_orgID, every time the organisation is stored in the database the project is created with the name having all the policies as editors, viewer, owner.
Similar changes as https://github.com/chef/automate/pull/6518
https://github.com/chef/automate/issues/6380
Project is created and stored in database at the time of migration
```
```
Steps to test:
1. Ensure Chef Infra Server is running. If it is not start it with ```start_chef_server```
2. Add the chef-server test environment credentials and extract the …
=> Associate Project with every organisation

components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.html, components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.scss, e2e/cypress/integration/api/iam/infra_server_actions_integration.spec.ts
Need to add a button for 'sync organization and users' for the new flow and need to change metadata UI.
https://github.com/chef/automate/issues/6556
Added a button for sync organization and users for the new flow.
Changed UI for metadata.
```STEP 1
STEP 2
```
Go To Infrastructure -> Chef Servers -> Click on any Chef Infra Server -> you can see changed metadata UI and new button added.
With occasional exceptions, all PRs …
=> Added sync organization and user button

components/infra-proxy-service/server/orgs.go, components/infra-proxy-service/storage/postgres/migration/sql/07_migration.down.sql, components/infra-proxy-service/storage/postgres/migration/sql/07_migration.up.sql, components/infra-proxy-service/storage/postgres/migrations.go, components/infra-proxy-service/storage/postgres/postgres.go, components/infra-proxy-service/storage/storage.go
Script and storage function for the migration stages
https://github.com/chef/automate/issues/6377
I have added the PostgreSQL script and storage function for the migration stage related to parsed data.
```
```
=> Storage functions and script for the migration stage

components/automate-ui/e2e/signin.e2e-spec.ts, components/automate-ui/src/app/services/chef-session/chef-session.service.spec.ts, components/automate-ui/src/app/services/chef-session/chef-session.service.ts
Add telemetry preference in localStorage if it is not exist.
Added telemetry preference in localStorage.
Login into automate-ui -> righ click on browser and select inspect the element -> click Application tab in inspect window -> clear the local storage -> reload the page -> then you can see telemetry preference is enabled by default.
local storage key name -->  "******-telemetry-enabled"
=> Add telemetry preference in localStorage if not exist

components/notifications-service/habitat/plan.sh
Notification service is not able to connect to external services like Slack and Webhook.
This is because erlang version is bumped to v23.2 from earlier v21.0
This PR is pinning the version to v21.3
#6634
#6597 
- Test the changes by testing with other external endpoints
- `rebuild components/notification-servce`
- Open automate ui and navigate to settings tab
- Open Notifications
- Test webhook by hitting https://enq65ijsovsf8.x.pipedream.net
- Test slack by hitting `https://hooks.slack.com/services/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`
-  …
=> Pin erlang version to v21.3

.bldr.toml, components/automate-cs-nginx/cmd/chef-server-ctl/ctl.go, lib/platform/config/config.go
Earlier automate-cs-nginx had hardcoded erchef and bifrost db uri in its codebase. Now we are dynamically creating the connection string to support both external and embedded database. We have also given options to pass custom connection string and custom service path.
https://github.com/chef/automate/issues/4285
All chef-server-ctl commands should work properly
```
chef-server-ctl cleanup-bifrost
chef-server-ctl grant-server-admin-permissions admin
```
- patch an external postgres database
- rebuild components/automate-cs-nginx
- Check if below commands are working:
```
chef-server-ctl user-create -f /tmp/admin.pem admin Admin User admin@example.com password;
chef-server-ctl cleanup-bifrost
chef-server-ctl grant-server-admin-permissions admin
```
With …
=> Chef server ctl external database support

components/docs-chef-io/content/automate/api_tokens.md, components/docs-chef-io/content/automate/desktop.md, components/docs-chef-io/content/automate/iam_actions.md, components/docs-chef-io/content/automate/iam_v2_guide.md, components/docs-chef-io/content/automate/iam_v2_overview.md, components/docs-chef-io/content/automate/ldap.md, components/docs-chef-io/content/automate/policies.md, components/docs-chef-io/content/automate/roles.md, components/docs-chef-io/content/automate/saml.md, components/docs-chef-io/content/automate/teams.md, components/docs-chef-io/content/automate/users.md, components/docs-chef-io/static/automate-api-docs/all-apis.swagger.json
Signed-off-by: kagarmoe <kgarmoe@progress.com>
This configures files for a 'Users' heading in the top-level of the product. The work came out of conversations with the field on the difficulty of quickly finding Auth, SAML, LDAP, Users, and Group/Org content in our docs.
=> Add 'Users' nav entry for user managment

components/automate-ui/src/app/services/telemetry/telemetry.service.ts, components/compliance-service/ingest/ingestic/mappings/mappings.go, components/compliance-service/ingest/pipeline/publisher/compliance.go, components/compliance-service/reporting/relaxting/stats.go
Compliance count for global telemetry was reporting the total report id instead of the uniq node/target id.
- The count of resources should be returned when a fresh inspec report is ingested
- The count should not change when the inspec reports from the same node is ingested again
- `rebuild components/automate-ui`
- `rebuild components/compliance-service`
- `./linux_build -url <url> -token <token>  -numberOfElement=20 -concurrency=10 -data=node -i=100_comp_node_list.json -status=success`
- Check the count of nodes.
- The event reported should be `complianceTargetCountsGlobal`
- `/linux_build -url <url> -token <token> -numberOfElement=20 -concurrency=10 -data=node -o=100_comp_node_list.json -status=success`
- Check the count of nodes. The node count should be same. …
=> Fix compliance telemetry

components/automate-cli/cmd/chef-automate/upgrade.go, components/automate-deployment/pkg/server/server.go, components/automate-deployment/pkg/server/server_test.go, components/automate-deployment/pkg/server/upgrade_status.go
PR for: https://chefio.atlassian.net/browse/KINETICS-4
=> airgap bundle upgrade

components/infra-proxy-service/storage/postgres/automate_infra_server_users.go, components/infra-proxy-service/storage/postgres/migration/sql/06_user_management.up.sql, components/infra-proxy-service/storage/storage.go
Storage function for org users association
https://chefio.atlassian.net/jira/software/c/projects/STALWART/boards/361?modal=detail&selectedIssue=STALWART-56
I have added storage function for the org users association in org_users table and also some constraints in the same table
```
```
=> Storage functions for org users association

components/authn-service/server/authenticators.go, components/automate-gateway/gateway/services.go
Signed-off-by: Yashvi Jain <Yashvi.jain@progress.com>
Loggers and error statements are added for investigation of a customer-bug. 617 
https://github.com/chef/customer-bugs/issues/617
Loggers added.
```
curl -k -s -H "api-token:${api-token}" -X POST "https://${automate-url}/api/v0/compliance/profiles?contentType=application/x-gzip&owner=admin" -F file=@"file-path" -v
```
=> Adding loggers for create profile handler

api/config/esgateway/config_request.go, components/automate-cli/cmd/chef-automate/backup.go, components/automate-deployment/pkg/backup/context.go, components/automate-deployment/pkg/backup/operations.go, components/automate-deployment/pkg/backup/runner.go, components/es-sidecar-service/pkg/elastic/snapshot.go
* Backup deletions fail after 10 minutes when ES snapshots are large even with -t 43200
* Backup creates fail after 2hrs when ES indices are large (>1TB) even with -t 43200
* Metadata writes (`metadata.json`, `checksums.json`) fail if they take longer than 5 sec
When a large customer in EMEA can successfully manage backups on a system with 75K nodes, 90 days retention and large (~4MB) compliance reports.
- [Y] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [Y] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).
- …
=> Fix various backup timeout problems for large EMEA customer

components/automate-ui/src/app/modules/infra-proxy/create-data-bag-modal/create-data-bag-modal.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/create-data-bag-modal/create-data-bag-modal.component.ts, components/automate-ui/src/app/modules/infra-proxy/create-databag-item-modal/create-databag-item-modal.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/create-databag-item-modal/create-databag-item-modal.component.ts, components/automate-ui/src/app/modules/infra-proxy/data-bags-details/data-bags-details.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/data-bags-details/data-bags-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/data-bags-list/data-bags-list.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/data-bags-list/data-bags-list.component.ts, components/automate-ui/src/app/modules/infra-proxy/edit-data-bag-item-modal/edit-data-bag-item-modal.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/edit-data-bag-item-modal/edit-data-bag-item-modal.component.ts
Track the Infra-server databags actions using telemetry track event. The following actions should be tracked:- search, create, delete and edit databags.
https://chefio.atlassian.net/browse/KINETICS-33
Infra-server databags actions are tracked using telemetry track event.
STEP 2
Go To Infrastructure -> Chef Servers -> Click on any Chef Infra Server -> Click on Orgs name -> select Databags tab -> you can search, create, edit and …
=> Telemetry coverage for Chef Infra Server Databags tab

components/automate-cli/cmd/chef-automate/initConfigHaTmpl.go
Signed-off-by: ArvinthC3000 <arvinth.chandrasekaran@progress.com>
As an Automate HA user, the user needs to see a clean config.toml file with no unused/commented config keys in it. Unused config keys are removed from both the AWS and existing infra config templates. Also added a comment for users mentioning not to modify the value of the `backup_mount` key in the config file.
https://chefio.atlassian.net/browse/MADROX-80
$ build components/automate-cli
$ hab pkg install -bf results/punitmundra-automate-cli-0.1.0-<PACKAGE_TIME_STAMP>-linux.hart
$ chef-automate init-config-ha [aws/existing_infra] …
=> removed unused config keys

.license_scout.yml
Issue: https://chefio.atlassian.net/browse/KINETICS-58
=> Fixing License Scout

.expeditor/nightly.pipeline.yml
Automate nightly pipeline has been failing for sometime now for the A1 to A2 migration 
Since A1 is pretty old and should be end of support, moving this to soft fail
- All the pipelines should be green
- Run the nightly main pipeline 
- The pipeline should be green and this pipeline should be skipped
=> Soft fail A1 to A2 upgrade

components/automate-ui/src/app/pages/create-notification-modal/create-notification-modal.component.spec.ts, components/automate-ui/src/app/pages/create-notification-modal/create-notification-modal.component.ts, components/automate-ui/src/app/pages/notification-details/notification-details.component.spec.ts, components/automate-ui/src/app/pages/notification-details/notification-details.component.ts, components/automate-ui/src/app/pages/notifications/notifications.component.ts
Track the Notifications actions using telemetry track event.
https://chefio.atlassian.net/browse/KINETICS-50
Notifications actions are tracked using telemetry track event.
STEP 2
Go To Settings -> Notifications -> you can create, delete, view list of notifications -> For each actions, you can observe the telemetry track event in Network tab(inspect the element window).
API URL - https://telemetry-acceptance.chef.io/events
**All …
=> Telemetry Coverage for Notifications page under settings tab 

components/automate-ui/src/app/app.module.ts, components/automate-ui/src/app/entities/org-users/org-users.action.ts, components/automate-ui/src/app/entities/org-users/org-users.effects.ts, components/automate-ui/src/app/entities/org-users/org-users.model.ts, components/automate-ui/src/app/entities/org-users/org-users.reducer.ts, components/automate-ui/src/app/entities/org-users/org-users.requests.ts, components/automate-ui/src/app/entities/org-users/org-users.selectors.ts, components/automate-ui/src/app/modules/infra-proxy/org-users/org-users.component.html, components/automate-ui/src/app/modules/infra-proxy/org-users/org-users.component.ts, components/automate-ui/src/app/ngrx.effects.ts, components/automate-ui/src/app/ngrx.reducers.ts, e2e/cypress/integration/ui/infra-proxy/infra-orgUsers.spec.ts
Signed-off-by: chaitali-mane [cmane@progress.com](mailto:cmane@progress.com)
Need to Automate org details UI should have users tab
https://chefio.atlassian.net/browse/STALWART-76
Added automate org details UI should have users tab
```
STEP 2
```
=> Added org user API integration

components/automate-ui/src/app/ui.component.ts
On a freshly provisioned server, you get a notice saying that your license is about to expire. So we should remove the license-exp-notification message from showing on every time signin even if user's license are not expired.
customer ticket - https://getchef.zendesk.com/agent/tickets/30268
Removed the license-exp-notification message
Log into chef-automate-ui,
You can see there is no notification message - ('License Update: your current license is expiring soon.' ) shown for fresh users. 
*Please add a note next to any checkbox above if you …
=> On a freshly provisioned server, you get a notice saying that your license is about to expire.

components/automate-deployment/pkg/majorupgradechecklist/checklist_manager.go, components/automate-deployment/pkg/server/server.go
when you are upgrading automate, the upgrade_metadata.json file should create before services are up
=> create json before services are up

components/automate-cli/cmd/chef-automate/migration_pg.go, lib/platform/sys/darwin.go, lib/platform/sys/linux.go, scripts/pgdata.sh
In this PR force flag is added to migrate pg and the upgrade_metadata.json file is updated if pg migrated.
https://chefio.atlassian.net/browse/SHIELD-16?atlOrigin=eyJpIjoiODUwMmQ1YjYwZmY3NGVmZjk4OWIzOTJlYzIyYzRhZTQiLCJwIjoiaiJ9
1. It should update JSON file if  pg migrate cmd is executed 
2. It should check pg migrate cmd is executed or not, if it is executed prompt message to force execute (Y/N)
3. To avoid prompt message -f flag can be used
```
automate ✗   hab studio enter
[20][default:/src:0]# start_all_services 
[20][default:/src:0]# rebuild components/automate-deployment/
[20][default:/src:0]# rebuild components/automate-cli
[20][default:/src:0]# chef-automate upgrade run --major
[20][default:/src:0]# chef-automate upgrade status …
```
=> added force flag and update upgrade_metadata json file 

components/infra-proxy-service/storage/postgres/migration/sql/06_user_management.up.sql
Signed-off-by: sonali wale <sonali.wale@progress.com>
Fixes for the synced infra server deletion issue.
https://chefio.atlassian.net/jira/software/c/projects/STALWART/boards/361?modal=detail&selectedIssue=STALWART-96
I have added the script changes in the users table for infra server deletion issue.
```rebuild components/infra-proxy-service/```
After deleting all the orgs from server, the server should be deleted.
=> Synced infra server deletion issue fix

components/automate-ui/src/app/helpers/auth/regex.ts, components/automate-ui/src/app/services/http/http-client-auth.interceptor.ts
Editor users are able to delete objects for an org so we passed one project name in header
Run the following commands
- cd components/automate-ui
- make serve
Try deleting objects from UI
=> Editor users are able to delete objects for an org

components/automate-cli/cmd/chef-automate/automateClusterCtlUtil.go, scripts/bundle_creation.sh, terraform/a2ha-terraform/Makefile, terraform/a2ha-terraform/deployment-makefile/Makefile
In Automate HA, the user who creates a bundle (including frontend and backend) wants to see the latest version timestamp in the bundle name. With the current change, when they create the bundle using the non-airgap method, the name will contain the timestamp (or build version) of the latest build instead of the downloaded time's timestamp.
Note: 
- Latest build version is obtained by the 'chef-automate info' command is used.
- Applicable but both internet and non-internet environments.
Observations:
- On running deploy/upgrade commands, the name of the bundles inside transfer_files are appended with the latest release version (timestamp)
Method | Result
-- | --
Airgap - Deploy | Working as expected
Airgap - Upgrade | Working as expected
Non-airgap - Deploy | Working as expected
Non-airgap …
=> Align bundle name to its timestamp/build-version

components/automate-cli/cmd/chef-automate/config.go, components/automate-cli/cmd/chef-automate/deploy.go, components/automate-cli/cmd/chef-automate/provisionInfraHa.go, components/automate-cli/cmd/chef-automate/upgrade.go
For Automate HA as a product, the user wants to add the -y argument enabled for all the Automate HA command in order to avoid explicit input of -y during the various commands execution for agreeing to License and user concern. A new flag is been added for the following subcommands and arguments. 
- provision-infra
- deploy
- upgrade
- patch
Name: yes
Short-hand: y
Type: boolean (default: false)
Description: Bypass the prompt for the user agreeing to continue
1. Above code changes don't affect the workflow Automate as a standalone product (find the observation below).
2. However deploy command in Automate/AutomateHA have a pre-existing flag to bypass user prompt(--accept-terms-and-mlsa). Both --yes/-y and …
=> Added new flags for accepting MSLA from user

terraform/a2ha-terraform/modules/automate/files/config.toml.erb, terraform/a2ha-terraform/modules/automate/inputs.tf, terraform/a2ha-terraform/modules/automate/main.tf, terraform/a2ha-terraform/modules/automate/templates/connector.toml.tpl, terraform/a2ha-terraform/modules/elasticsearch/inputs.tf, terraform/a2ha-terraform/modules/elasticsearch/main.tf, terraform/a2ha-terraform/modules/elasticsearch/templates/efs_backup.sh, terraform/a2ha-terraform/reference_architectures/deployment/main.tf, terraform/a2ha-terraform/reference_architectures/deployment/variables.tf
For Automate HA as a product, users want to configure automated backup with respect to the configuration in config.toml. 
When `backup_config` is set to `s3`, the s3 service will be mounted to the Elasticsearch node during deployment. Similarly when `backup_config` is set to `efs`, then efs will be mounted. This will be mounted during deployment itself and thus user no longer has to patch the backup config.
Note: 
- When s3 is selected for backup_config, `s3_bucketName` needs to be uncommented
- Value of `s3_bucketName` can be changed as the user desire. 
- After creation, s3_bucketName will also includes a random string for unique bucket name. (Eg: if `s3_bucketName = "chef-automate-ha"`, then bucket name could be …
=> Add backup config with deployment for AWS rebase

components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.spec.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.ts
issue: https://chefio.atlassian.net/browse/KINETICS-63
As an automate user, the user should be able to download the compliance report in JSON/CSV format using the chrome browser
https://github.com/chef/automate/issues/5727
I have added changes to the buffer format to download the report with the buffer type.
```
go-to compliance page --> click to download icon --> download dialog will be open, we have 2 options for downloading the file (Download JSON and Download CSV ) click on any of one link.
if you don't have much data, add the sample data first using the below command
chef_load_compliance_scans -D1 -N5000 -M1 -T500
``` …
=> Fixed 0-byte file with Chrome/Edge for CSV/JSON Download of Compliance Reports

components/automate-ui/src/app/page-components/data-feed-table/data-feed-table.component.spec.ts, components/automate-ui/src/app/page-components/data-feed-table/data-feed-table.component.ts, components/automate-ui/src/app/pages/data-feed-create/data-feed-create.component.spec.ts, components/automate-ui/src/app/pages/data-feed-create/data-feed-create.component.ts, components/automate-ui/src/app/pages/data-feed-details/data-feed-details.component.spec.ts, components/automate-ui/src/app/pages/data-feed-details/data-feed-details.component.ts, components/automate-ui/src/app/pages/data-feed/data-feed.component.spec.ts
Track the Data feeds actions using telemetry track event. The following actions should be tracked:- create, delete and edit Data feeds.
https://chefio.atlassian.net/browse/KINETICS-51
Data feeds actions are tracked using telemetry track event.
STEP 2
Go To Settings tab -> click Data Feeds from sidebar -> you can create, edit and delete data-feeds -> For each actions, you can observe the telemetry track event in Network tab(inspect …
=> Telemetry coverage for Data feeds

components/automate-ui/src/app/pages/+compliance/+profile/+profile-overview/profile-overview.component.html, components/automate-ui/src/app/pages/+compliance/+profile/+profile-overview/profile-overview.component.scss, components/automate-ui/src/app/pages/+compliance/+profile/+profile-overview/profile-overview.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+profile/+profile-overview/profile-overview.component.ts
Add search-button in profile page under compliance tab and send telemetry for profile searches.
https://chefio.atlassian.net/browse/KINETICS-61
Added search-button in profile page and send telemetry for profile searches.
STEP 2
Go To Compliance -> Profiles -> You can see a search-button is added with search box -> type the search text and click the search-button -> you get the filtered list of profiles.
With occasional exceptions, all PRs **from Progress employees** must …
=> Send telemetry for profile searches and add search button

components/automate-ui/src/app/pages/automate-settings/automate-settings.component.ts
Track the Data Lifecycle actions using telemetry track event.
https://chefio.atlassian.net/browse/KINETICS-52
Data Lifecycle actions are tracked using telemetry track event.
STEP 2
Go To Settings tab -> click Data Lifecycle from sidebar -> you can edit and save data-lifecycle -> For each actions, you can observe the telemetry track event in Network tab(inspect the element window).
API URL - …
=> Telemetry coverage for Data Lifecycle

.bldr.toml, components/automate-dex/habitat/plan.sh, components/automate-gateway/gateway/server.go, components/automate-load-balancer/habitat/config/nginx.conf, components/automate-ui/habitat/config/nginx.conf, components/session-service/server/server.go, lib/httputils/hsts.go
Added HSTS response headers in some services listed by customer. These services are:
- 2000 automate-gateway
- 10115 session-service
- 10161 automate-ui (nginx: master)
- 10117 dex (related PR: https://github.com/chef/dex-1/pull/45)
- ~~10143 backup-gateway (minio)~~
Note: Fix for MinIO service is dependent on upcoming refresh of [core/minio](https://github.com/chef-base-plans/minio) package which is planned for the current quarter (Refer to PR: https://github.com/chef-base-plans/minio/pull/5 and https://github.com/minio/minio/pull/12256).
Also removed HSTS from load balancer for above services due to duplicate HSTS headers.
Related issue: https://github.com/chef/automate/issues/5698
Customer bug: https://github.com/chef/customer-bugs/issues/471
All above 4 services running on ports …
=> Kinetics 62 enable strict transport security header for all the service endpoints

components/automate-ui/src/app/modules/desktop/desktop-detail/desktop-detail.component.html, components/automate-ui/src/app/modules/desktop/desktop-detail/desktop-detail.component.scss, components/automate-ui/src/app/modules/desktop/desktop-detail/desktop-detail.component.ts
Signed-off-by: rishichawda <rishichawda@users.noreply.github.com>
The Check-in history in node details on `/desktop` dashboard has a toggle for switching between the periods which looks like a dropdown. Updated it to be a dropdown as intended. Along with that, there are a couple of minor changes to the same container to be semantically make more sense (main wrapper (the "heading component" is now a flex box, dropdown isn't fixed width, both drop downs are wrapped in their own space rather than just thrown in into the main container)
resolve #6207 
*Please add a note next to any checkbox above if you are NOT …
=> use dropdown for checkin history period

components/automate-ui/src/app/pages/+compliance/+node-credentials/create-node-credential-modal/create-node-credential-modal.component.html, components/automate-ui/src/app/pages/+compliance/+node-credentials/create-node-credential-modal/create-node-credential-modal.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+node-credentials/create-node-credential-modal/create-node-credential-modal.component.ts, components/automate-ui/src/app/pages/+compliance/+node-credentials/node-credential-details/node-credential-details.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+node-credentials/node-credential-details/node-credential-details.component.ts, components/automate-ui/src/app/pages/+compliance/+node-credentials/node-credentials-list/node-credential-list.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+node-credentials/node-credentials-list/node-credential-list.component.ts, components/automate-ui/src/app/pages/integrations/add/integrations-add.component.spec.ts, components/automate-ui/src/app/pages/integrations/add/integrations-add.component.ts, components/automate-ui/src/app/pages/integrations/detail/integrations-detail.component.ts, components/automate-ui/src/app/pages/integrations/edit/integrations-edit.component.ts, components/automate-ui/src/app/pages/integrations/list/integrations-list.component.spec.ts, components/automate-ui/src/app/pages/integrations/list/integrations-list.component.ts
Signed-off-by: venkatesh-r-r <Venkatesh.Rengasamy@progress.com>
Telemetry coverage for node management under Settings tab in Automate-ui.
https://chefio.atlassian.net/browse/KINETICS-77
Actions in node management pages are tracked using telemetry track event.
STEP 2
Go To Settings -> You can see Node Management section -> Click on Node Integrations or Credentials -> you can search, create, edit & delete both node Integrations & Credentials  -> For each actions, you can observe the telemetry track …
=> Telemetry coverage for Node management in Settings tab

terraform/test-environments/scenarios/airgapped_single_local_fresh_install.tf, terraform/test-environments/scenarios/airgapped_single_local_inplace_upgrade.tf, terraform/test-environments/scenarios/chef-server_performance_test_single_local_inplace_upgrade.tf, terraform/test-environments/scenarios/common.tf, terraform/test-environments/scenarios/inspec_target_rhel7.tf, terraform/test-environments/scenarios/performance_test_single_local_inplace_upgrade.tf, terraform/test-environments/scenarios/s3_websites.tf, terraform/test-environments/scenarios/single_hardened_local_fresh_install.tf, terraform/test-environments/scenarios/single_local_all_fresh_install.tf, terraform/test-environments/scenarios/single_local_all_inplace_upgrade.tf, terraform/test-environments/scenarios/single_local_desktop_fresh_install.tf, terraform/test-environments/scenarios/single_local_fresh_install.tf, terraform/test-environments/scenarios/single_local_inplace_upgrade.tf
With repeating policy on, the deployed environments need to have the tags for long running and sleep
The sleep is applied for Monday to Saturday from 11pm to 7am and Sunday full day
- The deployed environments should have the tags
=> Fix terraform deploy

components/infra-proxy-service/server/orgs.go, components/infra-proxy-service/storage/postgres/automate_infra_server_users.go, components/infra-proxy-service/storage/storage.go
Remove the users association with org while deleting orgs from automate
https://chefio.atlassian.net/browse/STALWART-119
I have added changes in Delete org API to remove the users association with org
Removed the users entry from 'org_users' table for given org
Checked whether users exist for org or not, if exist then removed it
```
rebuild components/infra-proxy-service/
```
Steps to test:
Request
```curl -sSkH "api-token: $(get_admin_token)" 'https://a2-dev.test/apis/iam/v2/users/{USERNAME}'```
Response
```
{"org":{"id":"admin-org","name":"admin-org","admin_user":"","credential_id":"","server_id":"test","projects":["test_admin-org"]}}
```
All PRs **from Progress …
=> Remove the users association with org while deleting orgs from automate

components/infra-proxy-service/storage/postgres/migrations.go
So as an automate user, if I confirm/cancel the migration then the last migration id should always be save/update for the server.
- Migration Id should always be fetched
- Migration status should always be there available 
- rebuild components/infra-proxy-service/
- Run the following commands:
curl 'https://a2-dev.test/api/v0/infra/servers/test'  H 'accept: application/json, text/plain, */*' \
-H 'authorization: Bearer <Token>
=> Migration ID is missing on server details api response

terraform/test-environments/scenarios/s3_websites.tf
Deploy pipelines are failing after adding additional tags to s3 websites
- Deploy pipeline should not show the error
- 
=> Removed additional tags for s3 websites

.expeditor/verify_private.pipeline.yml
=> Disabling a1-migration and airgap a1-migration pipelines

components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.html, components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/org-users/org-users.component.ts
As an automate user,  I can reset the user key under the server users tab.
https://chefio.atlassian.net/browse/STALWART-122
I have added changes to reset the user key under the server user tab.
=> Add reset user key under the server users tab

components/authz-service/storage/postgres/project.go, components/infra-proxy-service/migrations/pipeline/utility.go
During migration a project shouldn't be created if it already exists in the db.
During migration a project shouldn't be created if it already exists in the db.
Run the migration pipeline when the project is already created.
=> not create a project if the project already exists during migration

components/automate-cli/cmd/chef-automate/migration_pg.go
need to read the /hab path in case of it mount to some other location
this changes tried to read the /hab path, either it return /hab OR /<>/hab 
SHIELD-45
=> read the hab path in case of /hab mount 

.expeditor/config.yml, .expeditor/create-upload-airgap-bundle.sh, .expeditor/promote-hab-pkgs-and-cli.sh, .expeditor/upload-files.sh, components/docs-chef-io/content/automate/airgapped_installation.md
Signed-off-by: Sahiba Goyal <sgoyal@progress.com>
=> Creating and Uploading airgap bundle

components/automate-backend-deployment/habitat/hooks/install, components/automate-cli/cmd/chef-automate/automateClusterCtlUtil.go, components/automate-cli/cmd/chef-automate/automateHAAwsDeployment.go, components/automate-cli/cmd/chef-automate/automateHADeployExistingInfra.go, components/automate-cli/cmd/chef-automate/upgrade.go, components/automate-cli/cmd/chef-automate/workspaceUpgrade.go, test/lib/credentials.rb
While doing chef-automate upgrade we need to upgrade ha workspace in case airgap bundle have available updates for automate-ha-deployment package, we have included this feature in chef-automate upgrade run command,
also we have introduced a new command to manually upgrade workspace if needed, command will be chef-automate workspace-upgrade <automate-X.X.XX.aib>
=> Automate ha deployment workspace upgrade

components/automate-backend-deployment/README.md, components/automate-cluster-ctl/readme, test/lib/credentials.rb
after cert rotation with admin-dn and node-dn es-sidecar was complaining for as it is not proper, This fix will will solve this problem.
=> Fixing admin-dn and node-dn for openserarch cert rotations

components/automate-ui/package-lock.json, components/automate-ui/package.json
=> "Bump minimist from 1.2.5 to 1.2.6 in /components/automate-ui"

components/compliance-service/reporting/relaxting/suggestions.go, components/config-mgmt-service/backend/elastic/suggestions.go
As an Automate user when I type a node name to search for in the infra runs tab or compliance, it will return only an exact match. In the compliance tab, it's working fine but in the case of client run, it's showing a list of all the nodes.
https://chefio.atlassian.net/browse/STALWART-123
https://github.com/chef/customer-bugs/issues/675
I have added some changes to the elastic search query to make this search consistent.
to test these changes, you need to add the sample data first
```
chef_load_nodes
chef_load_compliance_nodes
after adding the data you need to rebuild the config management service 
rebuild components/config-mgmt-service/
```
With occasional exceptions, all PRs **from Progress employees** must tick …
=> added changes to fix the client run search

components/automate-deployment/pkg/usermgmt/client/client_test.go, components/local-user-service/users/dex/dex_test.go
Signed-off-by: Sunanda-Boorla <sboorla@progress.com>
To Solve Security Issue in SonarCloud on Hardcoded Password. I have written a function (getPassword()) that returns a password. This password is assigned to another variable.
**https://chefio.atlassian.net/jira/software/c/projects/SHIELD/boards/365?modal=detail&selectedIssue=SHIELD-57**
Solved Security Issue in SonarCloud on Hardcoded Password by writing a function.
go test client.go client_test.go -v
=> Password fix on sonarcloud

api/config/esgateway/config_request.go, api/config/esgateway/config_request_test.go, components/es-sidecar-service/habitat/config/config.toml, components/es-sidecar-service/pkg/elastic/snapshot.go
Signed-off-by: Vipin Yadav <vipin.yadav@progress.com>
- Variable changed from aws_es to aws_os in config/esgateway go file
- Also made changes in es-sidecar-service config.toml to use os settings.
- As AWS OpenSearch returns "Your request: '/_recovery' is not allowed." for "/_recovery"  api.
Modified api call from  "/_recovery" to "/_all/_recovery" to get snapshot recovery status during OpenSearch recovery operations 
1. First build the following packages:-
a. es-sidecar-service
b. automate-deployment
c. automate-gateway
d.automate-cli
2. provide required info in config:-
[global.v1.external.opensearch]
enable = true
nodes = ["node_endpoint"]
[global.v1.external.opensearch.auth]
scheme = "aws_os"          
[global.v1.external.opensearch.auth.aws_os]
username = "username"
password = …
=> Managed OS backup/restore fixes

components/automate-deployment/pkg/majorupgradechecklist/v4.go, components/automate-deployment/pkg/majorupgradechecklist/v4_test.go, components/automate-es-gateway/habitat/hooks/run
Automate should check if indexes below version 6 are present before upgrading to automate v4. If they are present we should throw an error.
https://chefio.atlassian.net/jira/software/c/projects/SHIELD/boards/365?modal=detail&selectedIssue=SHIELD-55
Before upgrading to automate 4.x, we should check and throw an error if elasticsearch index are below version 6.
- `rebuild components/automate-cli`
- install automate `3.0.49` on a instance
- Create an es5 instance, create some indices, disable sharding using curl command(refer elastic docs)and copy the index data to `/hab/svc/automate-elasticsearch/data`
Disable Sharding:
`curl -X PUT "localhost:9200/_cluster/settings?pretty" -H 'Content-Type: application/json' -d'
{
"persistent": {
"cluster.routing.allocation.enable": "primaries"
}
}
'
`
- …
=> Validate all indexes are of version 6 before upgrade of Elasticsearch in major upgrade to 4.x

components/automate-backend-deployment/README.md, terraform/a2ha-terraform/modules/aws_output/main.tf
The PR contains the changes to scale the AWS infra after the setup is provisioned or deployed.
In order to properly scale the setup, we need to perform the following steps:
- Remove aws.auto.tfvars from /hab/a2_deploy_workspace/terraform and /hab/a2_deploy_workspace/terraform/destroy/aws/ 
- Modify /hab/a2_deploy_workspace/terraform/.tf_arch from "deployment" to "aws"
- Modify the instance count in config.toml
- Provision the setup (This will create or destroy the resources):
chef-automate provision-infra config.toml
- Redeploy the cluster
chef-automate deploy config.toml
Below are the scenarios that have been tested on a simple HA setup (1 instance each for Automate and Server and 3 for opensearch and PG):
- Scale up the Automate instance count to 2
- Scale up the Server count to 2
- Add …
=> Changes for scaling the aws infra

components/automate-cli/cmd/chef-automate/automateClusterCtlUtil.go, components/automate-cli/cmd/chef-automate/automateHAAwsDeployment.go, components/automate-cli/cmd/chef-automate/automateHADeployExistingInfra.go, components/automate-cli/cmd/chef-automate/deploy.go, components/automate-cli/cmd/chef-automate/genA2haRbTmpl.go, components/automate-cli/cmd/chef-automate/initConfigHa.go, components/automate-cli/cmd/chef-automate/initConfigHaTmpl.go, components/automate-cli/cmd/chef-automate/provisionInfraHa.go, components/automate-cli/cmd/chef-automate/workspaceUpgrade.go, components/automate-deployment/pkg/bootstrap/bootstrap-ha.go, components/automate-deployment/pkg/bootstrap/bootstrap.go, components/automate-deployment/pkg/client/deployer.go, components/automate-deployment/pkg/constants/constants.go, components/automate-deployment/pkg/target/local_target.go, components/automate-deployment/pkg/target/mock_target.go, components/automate-deployment/pkg/target/target.go
This PR contains the following changes :
- Attributes specific to saas are added in automate-cli so that while generating config.toml they are included. They are commented out as deprecated by default. These attributes are consumed only when using saas specific cluster-ctl and backend deployment packages. They don't have any effect on the HA cluster setup
- Flag "saas" is added to the provision-infra command. If this flag is passed, the Saas backed deployment package is installed while provisioning the infra. If the flag is not passed, it is defaulted to false and the current flow of installing automate-ha-deployment carries on.
Command for infra setup for saas:  chef-automate provision-infra config.toml --saas
With occasional exceptions, all PRs **from …
=> Kratos 97 saa s cluster setup process

api/config/opensearch/config_request.go, components/automate-opensearch/habitat/config/jvm.options, components/automate-opensearch/habitat/default.toml
Change the default value for the config 
OSHeapPortion: .5
InitiatingHeapOccupancyPercent : 15 %
indicies.breaker.total_limit : 95%
=> update the automate-opensearch config

components/automate-backend-deployment/README.md, components/automate-cluster-ctl/readme, terraform/a2ha-terraform/destroy/aws/main.tf, terraform/a2ha-terraform/modules/aws/inputs.tf, terraform/a2ha-terraform/modules/aws/main.tf, terraform/a2ha-terraform/modules/aws/security.tf, terraform/a2ha-terraform/reference_architectures/aws/main.tf
In this PR, following changes are made
- Port 443 and 80 are removed from existing security groups and a new security group is added with ports 443 and 80, and this SG is added only to all frontend nodes. (443 and 80 are not required for backend nodes)
- Port 22 accessibility is now restricted from 0.0.0.0/0. Only Bastion server can access it
NA
=> Added new security group for port 443 AND 80 and port 22 restrictions

components/docs-chef-io/content/automate/major_upgrade_4.x.md
It is seen from the testing that OpenSearch does not work properly when the heap size is not set to 50% of the memory capacity. This needs to be notified to users as a warning.
- The public document should show the notification in the Upgrade 4.x page
=> Adding warning for OpenSearch heap size

components/automate-deployment/pkg/preflight/checks.go, components/automate-deployment/pkg/preflight/preflight.go, components/automate-deployment/pkg/preflight/preflight_test.go, components/automate-deployment/pkg/preflight/test_probe.go
SELinux is enabled by default on Centos and Redhat systems. When installing automate, there is no preflight check performed to see if SELinux is set to permissive or disabled which is a requirement for the install to success. What this leads to is a install which seems to succeed but actually the habitat supervisor fails to start properly. The leads to a weird state because you cannot run the deploy command again due to the `is_a2_deployed` check failing. The user must figure out the issue and restart the hab supervisor themselves.
#4719 
https://chefio.atlassian.net/browse/SHIELD-51
Automate installation needs to be successfull once SELinux is Disabled.
1.Create centos 8.
2. Run rebuild components/automate-deployment and rebuild components/automate-cli services .
3. Create an airgap …
=> Chef-automate installation on Selinux status change

components/compliance-service/ingest/ingestic/mappings/comp-control-rep-date.go, components/compliance-service/ingest/ingestic/mappings/mappings.go
Added the mapping for new control based index structure
https://chefio.atlassian.net/jira/software/c/projects/STALWART/boards/361?modal=detail&selectedIssue=STALWART-163
Mapping has been added and as soon as we add data into the control structure it will be reflected.
```
```
=> adding the new control index mapping

components/automate-backend-deployment/README.md, components/automate-cluster-ctl/readme, terraform/a2ha-terraform/reference_architectures/aws/main.tf
In this PR, accessibility of all nodes is limited to the bastion server
NA
=> CIRD block restriction fix

components/automate-cli/cmd/chef-automate/haValidateInfra.go
Hiding vaildate ha infrastructure command.
=> hiding validate infrastructer command

components/compliance-service/cmd/compliance-service/cmd/run.go, components/compliance-service/compliance.go, components/compliance-service/config/types.go, components/compliance-service/ingest/pipeline/compliance.go, components/compliance-service/ingest/pipeline/processor/control_worker.go, components/compliance-service/ingest/pipeline/processor/control_worker_test.go, components/compliance-service/ingest/pipeline/publisher/compliance.go, components/compliance-service/ingest/server/compliance.go, components/compliance-service/integration_test/global_test.go, components/compliance-service/integration_test/suite_test.go
Created a new asynchronous function which will get the report uuid at the time of inserting the report into the database and update the new index.
https://chefio.atlassian.net/browse/STALWART-164
A connection with cereal manager is implemented which will have a new workflow now.
```
```
=> Adding Asychronous function for new control-index

components/compliance-service/ingest/ingestic/ingestic.go, components/compliance-service/integration_lcr_test/suite_test.go
We had to make the code changes to set all the datLatest flag to false for all the indices before 24 hours.
- Test upgrade scenario from older version
- Only the latest report should have day_latest flag  true
- This is applicable for new data as well as old data after upgrade
- All Exceptions are Handled Properly
- Ensure information are logged and should not have unnecessary data.
- Test coverage for the new feature is done to at least 70%
- Smoke Test done.
- PR has 2 approvers.
- All Code Review Comments are Resolved.
Run the following command :
./automate-load-test -url https://a2-dev.test/api/v0/events/data-collector -token <token> -numberOfElement=200 -concurrency=20 -data=compliance -status=failure …
=> Setting day_latest to false

components/automate-es-gateway/habitat/config/nginx.conf, components/docs-chef-io/content/automate/install.md, components/docs-chef-io/content/automate/opensearch.md
We have added docs to configure opensearch connection with HTTP
=> Added config for opensearch over http

components/docs-chef-io/content/automate/backup.md, components/docs-chef-io/content/automate/ha_backup_restore.md, components/docs-chef-io/content/automate/ha_backup_restore_prerequisites.md, components/docs-chef-io/content/automate/managed_services.md, terraform/a2ha-terraform/modules/automate/files/config.toml.erb
S3 uploads during backup does not support `s3.<region>.amazonaws.com` anymore now the format should be `s3.amazonaws.com`. The region is not required anymore.
=> updated docs for s3 backup

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profiles/reporting-profiles.component.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/report-data.service.ts
Signed-off-by: Sunanda-Boorla <sboorla@progress.com>
Removed this.isEmpty(data.items) as this was showing profiles data empty and replaced with this.isZero(data.total) to show profiles data in compliance report. Code is modified in order to show complete profiles.
https://chefio.atlassian.net/jira/software/c/projects/MADROX/boards/363?modal=detail&selectedIssue=MADROX-227
- If we click passed nodes, skipped nodes or waived nodes, then it should display profiles data. 
- The bar containing total, passed, failed profiles should be still there
- The message for no data list should contain the type of filter selected
rebuild …
=> Show profiles data in compliance report

components/automate-ui/src/app/modules/infra-proxy/client-details/client-details.component.html, components/automate-ui/src/app/modules/infra-proxy/client-details/client-details.component.scss, components/automate-ui/src/app/modules/infra-proxy/client-details/client-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/cookbook-details/cookbook-details.component.html, components/automate-ui/src/app/modules/infra-proxy/cookbook-details/cookbook-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/data-bags-details/data-bags-details.component.html, components/automate-ui/src/app/modules/infra-proxy/data-bags-details/data-bags-details.component.scss, components/automate-ui/src/app/modules/infra-proxy/data-bags-details/data-bags-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/environment-details/environment-details.component.html, components/automate-ui/src/app/modules/infra-proxy/environment-details/environment-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/infra-node-details/infra-node-details.component.html, components/automate-ui/src/app/modules/infra-proxy/infra-node-details/infra-node-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/infra-role-details/infra-role-details.component.html, components/automate-ui/src/app/modules/infra-proxy/infra-role-details/infra-role-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/org-details/org-details.component.html, components/automate-ui/src/app/modules/infra-proxy/org-details/org-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/policy-file-details/policy-file-details.component.html, components/automate-ui/src/app/modules/infra-proxy/policy-file-details/policy-file-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/policy-group-details/policy-group-details.component.html, components/automate-ui/src/app/modules/infra-proxy/policy-group-details/policy-group-details.component.ts
When navigating in Automate under Infrastructure / Chef Infra Servers the Organization gets lost from the breadcrumb navigation. So I have added the code so that the Org should stay visible and clickable in the breadcrumbs.
https://chefio.atlassian.net/browse/KINETICS-170
https://chefio.atlassian.net/browse/KINETICS-145
After changing the code, now Organization is visible and clickable in the breadcrumbs for all the required tabs and clicking the organisation in the breadcrumb in Chef Infra Server take the user to the cookbook tab.
After going to my branch run these commands:
- hab studio enter
- build components/automate-ui-devproxy/
- start_automate_ui_background
- rebuild components/automate-ui/
**All PRs** must …
=> Added Organization in Breadcrumb Nav Bar

components/automate-backend-deployment/habitat/hooks/install
In this PR, during AWS deployment, when the workspace is upgrading, tfstate file of AWS provisioning is copied into terraform folder instead of the deployment tfstate file. With this when the upgrade command is running, it destroys the infrastructure itself (destruction happens only when AWS_region is provided to terraform provider). To rectify it, some of the logic is altered so that it will copy the tfstate file appropriately from the old workspace to the new workspace. 
Changes:
- tfstate files are copied individually in all places
- secret.key is also copied into workspace
**Before fix:**
Scenario | Observation | Test
-- | -- | --
AWS - upgrade | tfstate file of both deployment and aws provision is copied in in terraform …
=> Workspace upgrade copying Missing files

components/automate-cli/cmd/chef-automate/upgrade.go, components/automate-cli/cmd/chef-automate/workspaceUpgrade.go
The upgrades were failing for SaaS cluster because the deployment package name is different from HA and therefore it wasn't able to upgrade the workspace.
To resolve this, I have added a new hidden flag (--saas) in the upgrade command which will ensure that the correct package names are being used.
Upgrade command for HA: upgrade run --airgap-bundle automate-4.2.27.aib --upgrade-frontends
Upgrade command for SaaS: upgrade run --airgap-bundle automate-4.2.27.aib --upgrade-frontends --saas
Have tested out the upgrades for SaaS
**Known issue**
- With workspace upgrade, the terraform.tfstate file is not copied properly due to which the terraform plan execution fails during the upgrade.
Temporary Solution: Copy the terraform.tfstate file from /hab/workspace_<>/terraform to …
=> Changes in upgrade command for SaaS

components/infra-proxy-service/server/nodes.go
Infra Server Node deletion was not deleting clients. The message on node deletion although claims to delete the corresponding client too.
https://chefio.atlassian.net/browse/STALWART-196
- Connect Infra Server to Infra Server View
- Search for a node under Nodes tab
- Search for the same name in the Clients tab. You should find the client in the client tab.
- Delete the node from the Nodes tab
- After deletion, the clients tab should not return the client name
- rebuild components/infra-proxy-service
- Use server ec2-18-223-220-58.us-east-2.compute.amazonaws.com
- admin kallol
*Please add a …
=> Delete Client on Node Deletion of Infra Server View

components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, terraform/a2ha-terraform/How-to-destroy-infra.md
In Automate HA, when destroy command is run from AWS-destroy architecture, it was also destroying EFS file system and the backup data is lost. In this PR, EFS state from .tfstate file is removed so that the same will not be destroyed when the infra is removed.
https://chefio.atlassian.net/browse/MADROX-260
It's dev done that tested in AWS infrastructure
=> Adding steps to destroy infrastructure without destroying EFS

components/compliance-service/reporting/constants.go, components/compliance-service/reporting/relaxting/assets.go, components/compliance-service/reporting/relaxting/assets_test.go, components/compliance-service/reporting/relaxting/es_types.go
Added queries for open search which will get the total asset count with filters
https://chefio.atlassian.net/jira/software/c/projects/STALWART/boards/361?modal=detail&selectedIssue=STALWART-180
The query is fetching from comp-run-info index.
```
```
=> adding queries for asset count api

components/docs-chef-io/content/automate/ha_security_firewall.md
TCP port 9683 should have been 9638 for the habitat gossip ports.
=> Fix typo for tcp port 9638 firewall documentation

components/automate-deployment/pkg/majorupgradechecklist/v3.go, components/automate-deployment/pkg/majorupgradechecklist/v4.go
=> Changing S3 backup URL prompt text and refactoring

components/docs-chef-io/content/automate/ha_existing_a2ha_to_automate_ha.md
As an automate user when we migrate from  A2HA to Automat HA then I should be able to find equivalent command of A2HA in automate HA docs.
https://chefio.atlassian.net/browse/MADROX-301
=> docs migration A2HA to automate HA equivalent command addition

terraform/a2ha-terraform/modules/automate/templates/provision.sh.tpl, terraform/a2ha-terraform/reference_architectures/deployment/main.tf, terraform/a2ha-terraform/reference_architectures/existing_nodes/main.tf
Need to add the  dependency between the terraform module. As of today they are running async, will cause an upgrade failure. 
How to test the changes 
build the package : 
rebuild components/automate-backend-deployment/
push the package to the your origin and create a bundle via customer manifest.json
Do the deployment with custom package.
=> Fix for Automate HA upgrade via adding the terrafrom module deps

components/automate-cli/cmd/chef-automate/migration_pg.go, components/automate-cli/pkg/status/error.go, components/automate-deployment/pkg/majorupgradechecklist/upgrade_utils.go, components/automate-deployment/pkg/majorupgradechecklist/v3.go, components/automate-deployment/pkg/majorupgradechecklist/v4.go, lib/io/fileutils/fileutils.go
```
A= find free space in hab
B= find es dir size
if flag is given and dir != "hab", 
C = find new flag dir free space;
C should be greater than (B + 10% of B);
and A should be greater than 5 GB
if no flag;
A should be greater than 5+(B + 10% of B)GB
```
=> Disk space check moved to start of upgrade

.bldr.toml, components/automate-deployment/pkg/services/internal/generated/gen.go, products.meta
Made changesin product.meta and gen go for knife ec backup changes.
https://chefio.atlassian.net/jira/software/c/projects/STALWART/boards/361?modal=detail&selectedIssue=STALWART-205
Now knife ec backup should be in manifest file and in airgap bundle
create airgap bundle and run the commands
=> Adding products.meta and gen.go for knife ec backup in airgap bundle

components/docs-chef-io/content/automate/airgapped_installation.md, components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md, components/docs-chef-io/content/automate/ha_upgrade_introduction.md
Update the airgap bundle notice to read 
`Chef Automate bundles are available for 365 days from the release of a version.
However, the milestone release bundles are available for download forever.`
- The netlify preview link should show the expiry date to be 365 days instead of 60 days
=> Update airgap bundle expiry days

components/docs-chef-io/content/automate/managed_services.md
Adding resolver documentation in managed services as well
https://chefio.atlassian.net/browse/STALWART-218
Added documentation
Screenshots attached
See the preview changes
https://user-images.githubusercontent.com/91940132/191680485-1c2a71f0-5f01-4843-8c4b-8b98fed751b2.png
https://user-images.githubusercontent.com/91940132/191682076-bd161640-7af4-4c5a-9dc0-bf04899da933.png
=> Adding resolver documentation

components/compliance-service/ingest/server/compliance.go
Compliance report ingestions were getting failed when properties had duplicate empty values. 
https://chefio.atlassian.net/browse/IN-835
=> Handled duplicate empty key errors on report ingestion

components/automate-ui/src/app/helpers/auth/regex.ts, components/automate-ui/src/app/modules/infra-proxy/clients/clients.component.ts, components/automate-ui/src/app/modules/infra-proxy/infra-nodes/infra-nodes.component.ts
Issue: https://chefio.atlassian.net/browse/KINETICS-214
updated the regular expression to allow the search string that contains dot(.) while node and client search.
The end user should be able to search for node names and client names with dot(.) combinations.  
ex: test-123-45.test-test.test.test.com
From automate UI, link external infra server.
Goto Nodes tab under the organizations. 
Search for Node name with a string having a dot(.)
It should display the search results
=> enabling dot match regex

terraform/a2ha-terraform/modules/automate/files/config.toml.erb, terraform/a2ha-terraform/modules/automate/inputs.tf, terraform/a2ha-terraform/reference_architectures/deployment/main.tf
=> Adding fix for AWS deployment error with S3 Bucket Access & secret Keys

components/compliance-service/ingest/ingestic/ingestic.go, components/compliance-service/migrations/cereal_interface.go, components/compliance-service/migrations/cererl_interface_test.go, components/compliance-service/migrations/migration_workflow.go, components/compliance-service/migrations/upgrades.go
Added the upgrade time for upgrade process, now the reports will be picked where the flag was disabled.
https://chefio.atlassian.net/browse/KINETICS-238
Now the report will be extracted from given time.
=> adding upgrade time for upgrade process

components/compliance-service/reporting/relaxting/reports.go, components/compliance-service/reporting/relaxting/stats.go
Signed-off-by: Abdul-Az <aazeez@progress.com>
https://chefio.atlassian.net/browse/KINETICS-237
If date range filter is passed GetStatsSummaryControls will extract the data from control index else it will behave like old way.
=> control report with date range logic update

components/automate-cli/cmd/chef-automate/automateHAAwsDeployment.go, components/automate-cli/cmd/chef-automate/automateHADeployExistingInfra.go, components/automate-cli/cmd/chef-automate/genA2haRbTmpl.go, components/automate-cli/cmd/chef-automate/initConfigHa.go, components/automate-cli/cmd/chef-automate/initConfigHaTmpl.go, components/automate-cli/cmd/chef-automate/migration_pg.go, components/automate-cli/cmd/chef-automate/migrator/migratorv4/migrationscript.go, components/automate-cluster-ctl/lib/cluster/config.rb, components/automate-cluster-ctl/templates/terraform.tfvars.erb, components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_cert_deployment.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
=> Change config property for custom certs

components/automate-cli/cmd/chef-automate/certRotate.go, components/automate-cli/cmd/chef-automate/config.go, terraform/a2ha-terraform/modules/aws/outputs.tf, terraform/a2ha-terraform/modules/vsphere/outputs.tf
SanjuPal01 <ssanju@progress.com>
Added the cert rotate command for HA service. Now user has to pass the certificate paths to cert-rotate cmd and it will rotate the certificates of all automate and chef-server nodes
https://chefio.atlassian.net/browse/KINETICS-234
https://chefio.atlassian.net/browse/KINETICS-230
sahiba3108/automate-cli/0.1.0/20221029071324
`chef-automate cert-rotate --a2 --private-cert certs/private.cert --public-cert certs/public.cert` 
(You can also use --automate flag instead of a2)
This will rotate the public and private cert of all automate …
=> Add cert rotate command for HA Service

components/automate-cli/cmd/chef-automate/certRotate.go, components/automate-cli/cmd/chef-automate/config.go, components/automate-cli/cmd/chef-automate/configTemplate.go
Signed-off-by: “SanjuPal01” <sanju.sanju@progress.com>
"Sahiba3108" <sgoyal@progress.com>
Added the cert rotate command for HA service. Now user has to pass the certificate paths to cert-rotate cmd and it will rotate the certificates of all postgres nodes.
https://chefio.atlassian.net/browse/KINETICS-235
ssanju/automate-cli/0.1.0/20221102131051
`chef-automate cert-rotate --public-cert client.pem --private-cert client-key.pem --root-ca root-ca.pem --pg`
(You can also use --postgres flag instead of pg)
This will rotate the public, private and root cert of all pg nodes.
With …
=> Postgres Cert Rotate Command

components/automate-cli/cmd/chef-automate/cleanup.go, components/automate-cli/cmd/chef-automate/sshAutomateHA.go, components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, terraform/a2ha-terraform/reference_architectures/aws/outputs.tf, terraform/a2ha-terraform/reference_architectures/deployment/outputs.tf
In this PR, Cleanup script for AWS provisioning is added
Commands available:
- --aws-deployment
Example:
`chef-automate cleanup --aws-deployment --force`
Jira Ticket: https://chefio.atlassian.net/browse/MADROX-354
- Use following CLI package to create chef-autoomate utility
- Use the following 'HA Deployment' package to create the airgap-bundle for provisioning
CLI package: `arvinth/automate-cli/0.1.0/20221103103437`
Backend-deployment packages: `arvinth/automate-ha-deployment/0.1.0/20221102173230`
*Please add a note next to …
=> Adding clean up logic for AWS provisioning

components/automate-cli/cmd/chef-automate/config.go
As an Automate HA user, after running `config patch` from the bastion server, the user needs to know to get success message with the mentioning of node IP after the patch output from remote node
https://chefio.atlassian.net/browse/MADROX-321
=> Printing success message after patching from bastion server

terraform/a2ha-terraform/modules/automate/templates/provision.sh.tpl
sudo chef-automate upgrade status 
return that 
✔ Chef Automate upgraded to airgap bundle version: 4.3.22
Find out what's new in version (4.3.22) by visiting
=> update the grep msg for automate ha upgrade for FE

components/automate-cli/cmd/chef-automate/automateHADeployExistingInfra.go, components/automate-cli/cmd/chef-automate/certRotate.go, components/automate-cli/cmd/chef-automate/config.go, components/automate-cli/cmd/chef-automate/configTemplate.go
SanjuPal01 <sanju.sanju@progress.com>
Added the cert rotate command for HA service. Now user has to pass the certificate paths to cert-rotate cmd and it will rotate the certificates of all opensearch nodes.
https://chefio.atlassian.net/browse/KINETICS-231
sahiba3108/automate-cli/0.1.0/20221111124650
`chef-automate cert-rotate --public-cert node1.pem --private-cert node1-key.pem --root-ca root-ca.pem --admin-cert admin.pem --admin-key admin-key.pem --os`
(You can also use --opensearch flag instead of os)
This will rotate the public, private, root, admin cert and …
=> cert rotate cmd for OS

components/automate-cli/cmd/chef-automate/certRotate.go
SanjuPal01 <sanju.sanju@progress.com>
I want to rotate my certificates for the Chef Infra Server node from the Bastion host using Automate CLI.
https://chefio.atlassian.net/browse/KINETICS-229
sahiba3108/automate-cli/0.1.0/20221114070730
`chef-automate cert-rotate --public-cert node1.pem --private-cert node1-key.pem  --ip <ip> --cs`
(You can also use --chefserver flag instead of cs)
This will rotate the public and private cert of a particular node.
All …
=> cert rotate for each chef server node

components/automate-cli/cmd/chef-automate/certRotate.go
Signed-off-by: Abdul-Az <aazeez@progress.com>
https://chefio.atlassian.net/browse/KINETICS-236
chef-automate cert-rotate --pg --root-ca "<>" --private-cert "<>" --public-cert "<>" --node ”<>”
This will rotate the certificate in the given Postgres node.
chef-automate cert-rotate --pg --root-ca "<>" --private-cert "<>" --public-cert "<>" --node ”<>”
Note: root-ca is ignored when --node flag is provided
Install this pkg in your bastion host:
hab pkg install aazeez/automate-cli/0.1.0/20221114103738 -bf
chef-automate cert-rotate --public-cert client.pem --private-cert client-key.pem --root-ca root-ca.pem --pg --node ""
(You can also use --postgres flag …
=> added check for node flag

components/automate-cli/cmd/chef-automate/gather-logs.go
Signed-off-by: SahithiMy <sahithi.mylangam@progress.com>
Changed the code for chef-automate gather-logs from sending gather-logs if there is any faulty/inactive nodes.
https://chefio.atlassian.net/browse/STALWART-228
chef-automate gather-logs for frontend and backend nodes
For Frontend nodes
- if hab is not installed returns error and continues with next node
- if hab-sup is not running it returns error and continues with next node
- if deployment-service is not running it will gather logs.
For backend nodes
- if hab is not installed returns error and continues with next node
- if hab-sup is not running it returns error and continues with next node
sahithimy/automate-cli/0.1.0/20221114080320
chef-automate gather-logs …
=> chef-automate gather-logs for faulty nodes

components/automate-cli/cmd/chef-automate/certRotate.go
Signed-off-by: “SanjuPal01” <sanju.sanju@progress.com>
"Sahiba3108" <sgoyal@progress.com>
I want to rotate my certificates for the Opensearch node from the Bastion host using Automate CLI.
https://chefio.atlassian.net/browse/KINETICS-232
ssanju/automate-cli/0.1.0/20221115071143
prerequisite:
`chef-automate cert-rotate --public-cert node1.pem --private-cert node1-key.pem --root-ca root-ca.pem --admin-cert admin.pem --admin-key admin-key.pem --os`
the above command will rotate certificates to whole cluster and also update the root-ca in frontend nodes to maintain the connection.
Now if you want to apply some …
=> Rotating the certs for each OS Node

components/automate-deployment/pkg/server/automate_config.go, components/automate-deployment/pkg/server/automate_config_test.go
The code is basically changed to allow user to change log-rotate configurations and rsyslog path.
The Video:
https://user-images.githubusercontent.com/36985548/201336685-3be0c884-b1a0-464c-aa39-7d3f2b76203e.mov
- the user should be able to change log-rotate parameters like:
- no of rotated file
- size of files
- path pointing to the files etc
`rebuild components/automate-deployment/`
=> Setup logrotate params:

components/automate-cli/cmd/chef-automate/centerliazed_log.go, components/automate-cli/cmd/chef-automate/centerliazed_log_test.go, components/automate-cli/cmd/chef-automate/config.go, components/automate-cli/cmd/chef-automate/config_test.go, components/automate-cli/cmd/chef-automate/logtoml.toml, components/automate-cli/cmd/chef-automate/sshAutomateHA.go
Added the config for adding centralised logging open-seach and postgresql nodes.
https://chefio.atlassian.net/browse/STALWART-233
Added the logic for checking existing and requesting config for database and patch only when its changed.
Added the logic for having centralised logs for open-search and postgresql nodes.
If any of the config is changed it will patch accordingly to rsyslog and logrotate and existing config will be set in a file under /hab/a2_deploy_workspace/ 
If the config has not given any values, it will take for default values.
deploy che-automate HA.
Add the build into the chef-automate HA instance.
Patch the following config using 
for postgresql : chef-automate config patch log1.toml --postgresql
opensearch : chef-automate config patch …
=> Centralised logging for postgress and opensearch

components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
=> Adding missed out config in Docs

components/automate-cli/cmd/chef-automate/certRotate.go, components/automate-cli/cmd/chef-automate/certRotate_test.go, components/automate-cli/cmd/chef-automate/sshUtils.go, components/docs-chef-io/content/automate/ha_cert_rotation.md, lib/io/fileutils/fileutils.go, lib/io/fileutils/mockFileUtils.go
Added support for remote certs in Automate HA.
https://github.com/chef/automate/pull/7526
https://chefio.atlassian.net/browse/SHIELD-173
- Cert rotate command should accept the remote path for certificate flag values.
- Each flag value should accept either a remote path or a local path(but not both at the same time).
- The remote path should be in one of the associated nodes of HA cluster.
----------------------------
----------------------------
---------------------------- …
=> Added support for remote certs

components/automate-cli/cmd/chef-automate/config.go
In Automate HA, the user should be able to run the config show from the bastion server. This PR includes changes that will fetch all the config from all the services.
For all backend nodes, the config will be fetched from each individual node and will be shown.
Arg/ Flag | Duplicate | Shorthand
-- | -- | --
--automate | --a2 | -a
--chef_server | --cs | -c
--postgresql | --pg | -p
--opensearch | --os | -o
Jira Ticket: https://chefio.atlassian.net/browse/MADROX-386
It's dev done …
=> Config show for each nodes from Bastion server

components/automate-cli/cmd/chef-automate/config.go, components/automate-cluster-ctl/templates/terraform.tfvars.erb, components/docs-chef-io/content/automate/ha_patching.md
For Automate HA as a product, when the use tried to patch some configuration, especially certificates, via `chef-automate config patch --[pg/os] file.toml`, it overwrites the certs in all nodes in the backend clusers, which causes an issue when the nodes are using unique certificates. So, in this PR, the cert values are deliberately removed before patching via config patch.
For OS node, TLS and for PG node, SSL is removed before patching.
Jira Ticket: https://chefio.atlassian.net/browse/MADROX-391
It's dev done and tested.
=> Restricting Cert rotation via `patch` command

components/automate-cli/cmd/chef-automate/backup.go, components/automate-cli/cmd/chef-automate/chef-automate.go
When we ran restore it was failing with error
`
BackupRestoreError: Unable to restore backup: Restoring deployment-service database failed: command hab pkg exec chef/deployment-service/0.1.0/20221206141953 deployment-service restoredb failed with error '✗✗✗
✗✗✗ stream did not contain valid UTF-8
✗✗✗
': exit status 1
`
reason was cobra don't support hooks chaining for child commands, so parent hook was not getting executed.
https://chefio.atlassian.net/browse/MADROX-402
Dev tested
then use build cli for restore
*Please add a note next to any …
=> Fixing restore failing 

components/automate-cli/cmd/chef-automate/backup.go, components/automate-cli/cmd/chef-automate/backup_test.go, components/automate-cli/cmd/chef-automate/pullAndGenerateConfig.go
- Fixes for on upgrade fresh object storage config were not getting copied.
- message in the backup command form bastion should contain the subcommand name triggered 
build and install CLI
patch new object storage config in automate-ha deployment
upgrade, after upgrade new object-storage config should be freshly patched one
run backup and restore it should run
=> reading object storage config from a2 hosts

components/automate-cli/cmd/chef-automate/upgrade.go
https://chefio.atlassian.net/browse/KINETICS-284
Use the new automate-cli and upgrade from 4.2.47 to 4.4.0
It Won't prompt the end user confirmation for workspace upgrade and it considers the workspace upgrade as true
=> Disable prompting the workspace upgrade

components/automate-cli/cmd/chef-automate/backup.go
An Automate user should get notified properly when they try to take EFS backup of Automate HA deployed in these scenarios:
- On Prem deployment with AWS managed DB 
- AWS deployment
- The command should indicate that EFS backup is not supported with AWS managed DB.
- The backup command should not error out for On Prem deployment with AWS managed DB to EFS. A corresponding message should be shown informing the reason for failure.
- The backup command should not error out for AWS deployment to EFS. A corresponding message should be shown informing the reason for failure.
- The backup command should work for all the other different types of deployments in Automate HA even when backed up to EFS.
- The backup command should work for AWS …
=> Displaying unsupported config

components/automate-cli/cmd/chef-automate/automateHAAwsDeployment.go
As an automate user, when I am doing automate HA deployment with managed services, I should not be forced to enter ebs volumes for pg and os, as it is no longer required.
https://chefio.atlassian.net/browse/KINETICS-295
I have made the required changes, and now you can skip ebs volume configurations in automate HA deployment with managed services.
Install this cli: 
- sahiba3108/automate-cli/0.1.0/20230110063253
Video Link: https://progresssoftware-my.sharepoint.com/:v:/g/personal/sgoyal_progr …
=> ebs volume config is not mandatory in automate ha-managed

components/automate-cli/cmd/chef-automate/config.go, components/automate-cli/cmd/chef-automate/config_test.go
Signed-off-by: prasad927 <Prasad.Chaudhari@progress.com>
Fix for config show cmd when Automate-HA on-prem deployment  is self-managed.
https://chefio.atlassian.net/browse/SHIELD-197
https://progresssoftware.sharepoint.com/:i:/s/ChefCoreC/Ef3W9i6EGbdBmxJpxIQmPIsB2IaA8h_mvcfEX4bcawlRBw?e=mvuk6b
[SHIELD-197]: https://chefio.atlassian.net/browse/SHIELD-197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added warn message in config show cmd for self managed deployment

components/automate-cs-bookshelf/habitat/config/sys.config, components/automate-cs-bookshelf/habitat/plan.sh, components/automate-cs-nginx/habitat/plan.sh, components/automate-cs-oc-bifrost/habitat/plan.sh, components/automate-cs-oc-erchef/habitat/plan.sh
Signed-off-by: “SanjuPal01” <sanju.sanju@progress.com>
https://chefio.atlassian.net/browse/KINETICS-245
=> Chef-server upgrade

components/automate-cli/cmd/chef-automate/automateClusterCtlUtil.go, components/automate-cli/cmd/chef-automate/automateHAAwsDeployment.go, components/automate-cli/cmd/chef-automate/automateHADeployExistingInfra.go, components/automate-cli/cmd/chef-automate/ha_node_add_aws.go, components/automate-cli/cmd/chef-automate/ha_node_add_aws_test.go, components/automate-cli/cmd/chef-automate/ha_node_add_onprem.go, components/automate-cli/cmd/chef-automate/ha_node_add_onprem_test.go, components/automate-cli/cmd/chef-automate/ha_node_delete_onprem.go, components/automate-cli/cmd/chef-automate/ha_node_delete_onprem_test.go, components/automate-cli/cmd/chef-automate/ha_node_operations_utils.go, components/automate-cli/cmd/chef-automate/initConfigHaExistingNode.go, lib/io/fileutils/fileutils.go, lib/io/fileutils/mockFileUtils.go
During deploy or add node HA root_ca should be optional for automate in config.toml
https://chefio.atlassian.net/browse/SHIELD-194
https://chefio.atlassian.net/browse/SHIELD-196
=> Made root_ca optional for automate

components/compliance-service/reporting/util/zip.go
Logic added to copy zip file by bytes and not whole at a time, which can consume the memory of the system.
https://chefio.atlassian.net/browse/IN-897
https://chefio.atlassian.net/browse/STALWART-291
Now the file is being copied zip by zip
```
rebuild components/compliance_service
```
Upload a zip profile under upload profiles page
=> Copying file by buffer to protect the attack

components/docs-chef-io/content/automate/ha_existing_a2ha_to_automate_ha.md, components/docs-chef-io/content/automate/ha_inplace_migration.md, components/docs-chef-io/content/automate/ha_inplace_upgrade.md
As and old A2HA customer I need to upgrade to latest version of Automate HA, but I want to use same cluster of A2HA
https://chefio.atlassian.net/browse/MADROX-264
Doc Tested on dev env
=> A2HA to Automate HA In-place upgrade docs

components/docs-chef-io/content/automate/ha_backup_restore_aws_s3.md, components/docs-chef-io/content/automate/ha_disaster_recovery_setup_AWS.md, components/docs-chef-io/content/automate/ha_upgrade_introduction.md
Created a Docs Page where the Process to Upgrade AMI for AWS Deployment is shown with Backup and Restore method
https://chefio.atlassian.net/browse/MADROX-421
Documentation where the Process to Upgrade AMI for AWS Deployment via Backup and Restore method.
=> Documentation of Process to Upgrade AMI for AWS Deployment 

components/automate-cli/cmd/chef-automate/certRotate.go
Allow to fetch and apply certificates with root user read only access
If the user is trying to fetch a certificate from a root or local location with only read permission for the root, the certificate rotate command will fail to fetch the certificate
`chef-automate cert-rotate --public-cert <public_cert> --private-cert <private_cert> --root-ca <root_ca>`
In order to be able to get contents even if its readonly we will prefer executing commands over ssh to get the contents rather than doing scp
https://chefio.atlassian.net/browse/SHIELD-224
=> Allow to fetch and apply certificates with root user read only access

components/compliance-service/ingest/ingestic/ingestic.go, components/docs-chef-io/content/automate/enhanced_compliance_report.md
Day latest will be mark for one day now rather than 90 days which is causing memory to shoot in opensearch 1.3.7
https://chefio.atlassian.net/browse/STALWART-336
Day latest false is marked for yesterday only.
```
```
Ingest the data in compliance service
=> Changing the logic from 90 to one day

components/automate-backend-deployment/habitat/hooks/install
As an automate user when I upgrade the workspace directory, then my configuration from the destroyed directory is not getting copied to the new workspace, fixes for the same
https://chefio.atlassian.net/browse/MADROX-454
Dev Tested
`jayvikramsharma/automate-ha-deployment/0.1.0/20230208171023`
build component/automate-backend-deployment
=> Workspace upgrade fix

components/automate-ui/src/app/page-components/resource-item/resource-item.component.html, components/automate-ui/src/app/page-components/resource-item/resource-item.component.ts
Signed-off-by: Ghanavishmathi Macharla <gmacharl@progress.com>
Fixed the issue of Node error log data in the Automate UI.
Minor change in resource-item component .html and .ts file to view the node error log data properly.
https://chefio.atlassian.net/browse/KINETICS-254
- Code changes in resource-item component
- After changes verified the UI
Issue (before code changes): https://progresssoftware-my.sharepoint.com/:v:/r/personal/ssanju_progress_com/Documents/Chef/Client%20Run%20report%20view,%20search%20by%20filter%20and%20download/Backtrac …
=> fixed the error log issue

components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.ts
As an Automate User, I should be able to download the mid-size reports of compliance nodes, right now if we ingested 2k nodes with the medium-size reports. The download functionality got failed.
https://chefio.atlassian.net/browse/STALWART-285
I have added some changes to download the report in any size without failing the download also the page is not going to break if the file size the large.
```
STEP 1
STEP 2
For adding data we need to add the data from the `automate-load-test` repo
use the below command to add the data
$ cd automate-load-test
$ ./automate-load-test -url https://a2-dev.test/api/v0/events/data-collector -token copy_you_hab_admin_token_here numberOfElement=2000 -concurrency=100 -data=compliance -status=success …
```
=> fixed for unable to download medium size report in compliance

components/automate-cli/cmd/chef-automate/automateClusterCtlUtil.go, components/automate-cli/cmd/chef-automate/automateHAAwsDeployment.go, components/automate-cli/cmd/chef-automate/deployHa.go, components/automate-cli/cmd/chef-automate/gather-logs.go, components/automate-cli/cmd/chef-automate/ha_node_operations_utils.go, components/automate-cli/cmd/chef-automate/testHA.go, components/automate-cli/cmd/chef-automate/upgrade.go
Changed the code for gather-logs, where we are getting gather-logs abruptly stops and does not exit gracefully.
https://chefio.atlassian.net/browse/STALWART-345
Modified the code for gather-logs which stops abruptly.
`hab pkg install sahithimy/automate-cli/0.1.0/20230216052302 -bf`
`chef-automate gather-logs`
https://user-images.githubusercontent.com/98326242/220012219-4e7a14ca-7983-43e7-9c76-32127eeb3928.mov
=> Modified the code for gather-logs

components/automate-ui/package-lock.json, components/automate-ui/package.json
The latest possible version that can be installed is 1.2.7 because of the following conflicting dependency:
sass-lint@1.13.1 requires minimist@1.1.x via gonzales-pe-sl@4.2.3
The earliest fixed version is 1.2.7.
https://github.com/chef/automate/security/dependabot/295
https://chefio.atlassian.net/browse/STALWART-334
I have updated the `minimist` version to 1.2.7
=> Bump minimist version from 1.2.6 to 1.2.7 in automate UI

components/automate-cli/cmd/chef-automate/cliUtils.go, components/automate-cli/cmd/chef-automate/cliUtils_test.go, components/automate-cli/cmd/chef-automate/config.go, components/automate-cli/cmd/chef-automate/iam.go, components/automate-cli/cmd/chef-automate/sshUtils.go
Support `iam` commands from Automate HA Bastion Node. The `iam` commands include the following sub-commands.
- chef-automate `iam` version
- chef-automate `iam` token create <name>
- chef-automate `iam` admin-access restore <password>
https://chefio.atlassian.net/browse/SHIELD-216
=> Support `iam` commands from Automate HA Bastion Node

components/automate-cli/cmd/chef-automate/certRotate.go, components/automate-cli/cmd/chef-automate/certRotate_test.go, components/automate-cli/cmd/chef-automate/ha_cert_show.go
Signed-off-by: prasad927 <Prasad.Chaudhari@progress.com>
https://chefio.atlassian.net/browse/SHIELD-229
https://progresssoftware.sharepoint.com/:i:/s/ChefCoreC/ES634qGMPVdNkv0GWobHu1sBzWC25gfBCn_uEEZLa3fiJg?e=J1iVYR
https://progresssoftware.sharepoint.com/:i:/s/ChefCoreC/Ebnpo0P4nzxPh663KgIjBcEBCnJhQHg17Qf_uqUZC3LZaQ?e=Jqly8L
https://progresssoftware.sharepoint.com/:i:/s/ChefCoreC/EUh_OJHkqkBFr8PHlGQVkagBBSscyUGVt-DJQs-PlKxuoA?e=QsX8uB
https://progresssoftware.sharepoint.com/:i:/s/ChefCoreC/ERnaeJCeERVNiYaeXTXMPt4BrmNEBrUEU2veNoPu8eIPhg?e=N …
=> SHIELD-229-make-cert-rotate-idempotent

components/automate-ui/src/app/modules/infra-proxy/client-details/client-details.component.html, components/automate-ui/src/app/modules/infra-proxy/cookbook-details/cookbook-details.component.html, components/automate-ui/src/app/modules/infra-proxy/data-bags-details/data-bags-details.component.html, components/automate-ui/src/app/modules/infra-proxy/environment-details/environment-details.component.html, components/automate-ui/src/app/modules/infra-proxy/infra-node-details/infra-node-details.component.html, components/automate-ui/src/app/modules/infra-proxy/infra-role-details/infra-role-details.component.html, components/automate-ui/src/app/modules/infra-proxy/org-details/org-details.component.html, components/automate-ui/src/app/modules/infra-proxy/policy-file-details/policy-file-details.component.html, components/automate-ui/src/app/modules/infra-proxy/policy-group-details/policy-group-details.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.ts
As an Automate User, When I navigate under Infrastructure / Chef Infra Servers / Organization,  the Chef Infra Server Name gets lost from the breadcrumb navigation.
https://chefio.atlassian.net/browse/KINETICS-147
I have added some UI changes in the infra proxy module to display the chef server name with a link.
```
STEP 1
STEP 2
--> need to add server first
--> click to server --> you can see the list of org's ---> click to specific org --> you can see the org details page 
check the breadcrumb like the screenshot.
```
All PRs **from Progress employees** …
=> Fixed for chef Automate navigation loses the chef infra server name from breadcrumb nav bar.

components/config-mgmt-service/integration_test/suggestions_test.go, components/ingest-service/backend/converge.go
Updated Node struct to accept empty error properties in converge.go to update node data in case of success runs.
https://chefio.atlassian.net/browse/IN-898
[CHEF-358](https://chefio.atlassian.net/browse/CHEF-358)
- Error suggestion not coming for success client runs list and Error filter does not give success client runs.
```
rebuild components/ingest-service
```
- Add a failure client run data in infrastructure. Check error suggestion.
- For the same node id,  push success client run.
- verify error suggestion if error shows.
*Please add a note next to any checkbox above if you are NOT …
=> IN-898: Fixed infra client run search error suggestion issue

components/automate-ui/src/app/entities/api-tokens/api-token.effects.ts, components/automate-ui/src/app/entities/api-tokens/api-token.requests.ts
The project assigned name is Changed automatically, when we toggle from active to inactive status and back to active status in automate API-token.
https://chefio.atlassian.net/browse/SHIELD-204
=> The project assigned name is Changed automatically, when we toggle from active to inactive status and back to active status in automate API-token

components/automate-deployment/pkg/client/automate_config.go
Signed-off-by: Sahiba3108 (sgoyal@progress.com)
I want to reconfigure Automate storage location for OpenSearch backup.
https://chefio.atlassian.net/browse/KINETICS-300
Reconfigured Automate storage location for OpenSearch backup.
Use these packages while creating an Airgap bundle:
- sahiba3108/automate-cli/0.1.0/20230224065051
- sahiba3108/deployment-service/0.1.0/20230224073758
Video Link: [https://progresssoftware-my.sharepoint.com/✌️/g/personal/sgoyal_progress_com/EVawQAsYtB5Lh5Whzfi0Fq8B1dinNDFvxtsOGIvufDE-fQ?e=wIgb74](https://progresss …
=> reconfigure backup location

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/reporting-overview.component.spec.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.spec.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.ts
On first switch to Compliance tab, graph was not populating points for past 10 days, as it should by default. It was only showing for 1 day.
The reason was that api was not being hit with correct start date on first visit. Start date was being calculated correctly on switching tabs( nodes/profiles/controls).
Also, found that the start date was being incorrectly sent for other sections such as node status, node failures.. It should always be one day data and not past n days
https://chefio.atlassian.net/browse/IN-864
https://chefio.atlassian.net/browse/CHEF-359
fixed the start date to be sent correctly for the API calls.
On first visit to Compliance Tab , graph should be loaded for past 10 days by default.
With occasional exceptions, all PRs **from Progress …
=> fix compliance graph not showing data of past n days  (IN-864)

components/automate-ui/src/app/entities/api-tokens/api-token.requests.ts, components/automate-ui/src/app/entities/notification_rules/notification_rule.model.ts, components/automate-ui/src/app/pages/data-feed-create/data-feed-create.component.ts, components/automate-ui/src/app/pages/notification-details/notification-details.component.ts
As an Automate User, I can able to edit notification more than once.
https://chefio.atlassian.net/browse/SHIELD-192
I have added some code changes for assigning a type to an object in case of the object is not loading with a specific type.
```
STEP 1
STEP 2
--> need to click on settings tab -> on left side navigation click to notification --> create a new notification ---> you can see the list of notifications ---> click to any notification --> change the name or something else and click to save button.
```
All PRs **from Progress employees** should tick …
=> fixed issue for the edit notification

components/automate-ui/src/app/helpers/datetime/datetime.ts, components/automate-ui/src/app/page-components/event-feed-guitar-strings/event-feed-guitar-strings.component.html
Signed-off-by: Agam Mathur agmathur@progress.com
Changed the pipe from our custom datetime pipe to @angular/common DatePipe. This resolved the bug that we were seeing where our custom filter was showing the previous day date as per the selected date format.
On debugging, I found that we were passing the current date as the end-date but our custom filter was showing the previous day date, due to which there was the mismatch between the label of the graph vs the actual log date. This bug was resolved when I used the Angular DatePipe and since, there is a difference between the format used by our custom pipe and Angular pipe, I changed the date format as well, so that the output format remains the same.
https://chefio.atlassian.net/browse/MADROX-416
https://angular.io/api/common/DatePipe
The …
=> MADROX-416: Event feed date selection.

components/docs-chef-io/content/automate/backup.md
After creating backup in s3, if user tries to create backup in filesystem, then backup was not creating in filesystem. So we fix the configurations.
=> backup doc fix

components/automate-cli/cmd/chef-automate/certRotate.go, components/docs-chef-io/content/automate/ha_cert_rotation.md
As we add timeout in ssh util due to these changes current cert rotate feature have high chance to get timeout error (specially when we rotate cert of backend)  with current default timeout i.e 150 sec thats why with this code changes i added flag for timeout and also set default timeout for cert rotate to 180 sec.
https://progresssoftware.sharepoint.com/:i:/s/ChefCoreC/Ebal7NNouvdCr9cwpL3ah7IB4JZVlvIf5RcWhDtU1oTnqw?e=QlyZet
https://deploy-preview-7755--chef-automate.netlify.app/automate/ha_cert_rotation/
=> Increased timeout for cert rotate

components/automate-cli/cmd/chef-automate/automateHADeployExistingInfra.go, components/automate-cli/cmd/chef-automate/genA2haRbTmpl.go, terraform/a2ha-terraform/modules/opensearch/templates/opensearch_user.toml.tpl
Opensearch cluster will have 3 or more than 3 nodes at any given time and for these nodes can either have same certs with same CN or they can have different certs with different CN. 
The problem with different CN is that the nodes were not able to communicate with each other, resulting in the failure of service.
PR contains the changes that will ensure that all the nodes will have a complete list of all the node's CN as part of the DN which will ensure that the nodes are able to communicate with each other.
https://chefio.atlassian.net/browse/CHEF-1037
Opensearch cluster with multiple nodes having separate certs and different CN should be up an running
All services should be in healthy state
- Rebuild the automate-cli, automate-ha-cluster-ctl and automate-ha-deployment packages.
- …
=> Changes for creating a OS nodes DN list

.gitignore, components/automate-cli/cmd/chef-automate/automateClusterCtlUtil.go, components/automate-cli/cmd/chef-automate/automateConstants.go, components/automate-cli/cmd/chef-automate/constants.go, components/automate-cli/cmd/chef-automate/genA2haRbTmpl.go, components/automate-cli/cmd/chef-automate/initConfigHa.go, components/automate-cli/cmd/chef-automate/initConfigHaTmpl.go, components/automate-cli/cmd/chef-automate/sshUtils.go, components/automate-cluster-ctl/lib/cluster/config.rb, components/automate-cluster-ctl/libexec/cluster-deploy, components/automate-cluster-ctl/libexec/cluster-provision, components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md, terraform/a2ha-terraform/modules/postgresql/main.tf, terraform/a2ha-terraform/modules/system/main.tf, terraform/a2ha-terraform/modules/system_hardening/main.tf
Added support for sudo password for HA deployment.
https://chefio.atlassian.net/browse/CHEF-789
https://chefio.atlassian.net/browse/CHEF-794
https://chefio.atlassian.net/browse/CHEF-357
https://chefio.atlassian.net/browse/IN-956
https://chefio.atlassian.net/browse/CHEF-791
https://chefio.atlassian.net/browse/CHEF-795
A user should be able to give input of Sudo password to the deployment flow.
- Rebuild `automate-cli` (`rebuild components/automate-cli/`) or can use (`akrishna/automate-cli/0.1.0/20230324092019`), `automate-ha-cluster-ctl` (`rebuild components/automate-cluster-ctl/`) or can use (`akrishna/automate-ha-cluster-ctl/0.1.0/20230323055913`), and `automate-ha-deployment`(`rebuild components/automate-backend-deployment/`) or can use …
=> Take input of Sudo Password for Deployment

components/automate-ui/src/app/modules/infra-proxy/org-details/org-details.component.html, components/automate-ui/src/app/page-components/client-runs-table/client-runs-table.component.html, components/automate-ui/src/app/pages/+compliance/+profile/+profile-details/profile-details.component.html, components/automate-ui/src/app/pages/+compliance/+profile/+profile-overview/profile-overview.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-controls/reporting-controls.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-nodes/reporting-nodes.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profile/reporting-profile.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-profiles/reporting-profiles.component.html, components/automate-ui/src/app/pages/+compliance/+scanner/containers/job-scans-list/job-scans-list.component.html, components/automate-ui/src/app/pages/+compliance/+scanner/containers/jobs-list/jobs-list.component.html, components/automate-ui/src/app/pages/+compliance/+scanner/containers/nodes-list/nodes-list.component.html, components/automate-ui/src/app/pages/event-feed/event-feed.component.html, components/automate-ui/src/app/pages/node-details/node-details.component.html, components/automate-ui/src/app/ui.component.html, components/automate-ui/src/app/ui.component.scss
scroll to top floating button issue solved.
https://chefio.atlassian.net/browse/CHEF-1547
1. For local setup just take a branch of code and run it on local machine.
2. For Ec2 you can just deploy it and check changes.
https://user-images.githubusercontent.com/54974312/227217782-9593d955-fac0-4b18-b3d0-14a6b49ed346.mov
=> floating button scroll to top issue solved

components/automate-cluster-ctl/libexec/cluster-deploy, components/automate-cluster-ctl/libexec/cluster-provision
Added nil check for sudo password variable.
https://github.com/chef/automate/pull/7774
Rebuild automate-ha-cluster-ctl (rebuild components/automate-cluster-ctl/) or can use (akrishna/automate-ha-cluster-ctl/0.1.0/20230405123959) and automate-ha-deployment(rebuild components/automate-backend-deployment/) or can use (akrishna/automate-ha-deployment/0.1.0/20230405131647).
=> Added nil check for sudo password variable

components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md
Need to update the config path for the opensearch/elasticsearch snapshots to match the path from the backups. 
Otherwise, we'll get errors about being unable to create the appropriate snapshot repositories.
=> Add missing config change for opensearch snapshot path

components/automate-cli/cmd/chef-automate/config.toml, components/automate-cli/cmd/chef-automate/genA2haRbTmpl.go, components/automate-cli/cmd/chef-automate/pullAndGenerateConfig.go, components/automate-cli/cmd/chef-automate/sshUtils.go, components/automate-cli/pkg/testfiles/aws/config.toml, components/automate-cli/pkg/testfiles/onprem/config.toml, components/automate-cluster-ctl/libexec/cluster-gather-logs, components/automate-cluster-ctl/libexec/cluster-status, components/automate-cluster-ctl/libexec/cluster-test, components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md, components/docs-chef-io/content/automate/ha_chef_backend_to_automate_ha.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md, components/docs-chef-io/content/automate/ha_sudo_password.md
Added sudo_password support for HA cmd in ruby
https://chefio.atlassian.net/browse/CHEF-795
https://github.com/chef/automate/pull/7774
- Rebuild `automate-cli` (`rebuild components/automate-cli/`) or can use (`akrishna/automate-cli/0.1.0/20230412082516`), `automate-ha-cluster-ctl` (`rebuild components/automate-cluster-ctl/`) or can use (`akrishna/automate-ha-cluster-ctl/0.1.0/20230411133555`), and `automate-ha-deployment`(`rebuild components/automate-backend-deployment/`) or can use (`akrishna/automate-ha-deployment/0.1.0/20230411141141`).
- Upload the above packages `hab pkg upload <PATH_TO_PACKAGE_HART_FILE>`.
- Create an airgap bundle with new packages `sudo ./chef-automate airgap bundle create -m latest_semver.json --channel dev`. Update this …
=> Take input of Sudo Password for CLI Commands

components/automate-cli/cmd/chef-automate/cliUtils.go, components/automate-cli/cmd/chef-automate/cmdUtils.go, components/automate-cli/cmd/chef-automate/cmdUtils_test.go, components/automate-cli/cmd/chef-automate/config.go, components/automate-cli/cmd/chef-automate/pre_flight_check.go, components/automate-cli/cmd/chef-automate/sshUtils.go, components/automate-cli/cmd/chef-automate/status.go, components/automate-cli/cmd/chef-automate/summary.go, components/automate-cli/cmd/chef-automate/summary_test.go, components/automate-cli/pkg/testfiles/a2ha_habitat.auto.tfvars, components/automate-deployment/pkg/a1upgrade/preflight.go, components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
get status summary for HA deployment
There are 3 ways, user can get status summary
1. Get status summary for ( automate, chef-server, open-search, postgresql ) nodes at-once
2. Get status summary by ip address
3. Get status summary only by (automate, chef-server, open-search, postgresql) 
> [root@ip-127-0-0-1 ec2-user]# chef-automate status summary -h
> Retrieve Chef Automate status node summary for HA deployment
> 
> Usage:
>   chef-automate status summary [flags]
> 
> Flags:
> Shorthand | Flags | Details | Type
> -- | -- | -- | --
>   -a |--automate                | Get only automate Status | bool
>   -c |--chef-server             | Get only chef server Status | bool
>   -o |--opensearch              | Get only opensearch Status | bool
>   -p |--postgresql              | Get only …
=> Chef 713 status summary command

components/automate-cli/cmd/chef-automate/start_linx.go, components/automate-cli/cmd/chef-automate/start_linx_test.go
Should able to run chef-automate start on bastion system of Automate HA cluster, should see output relevant to Automate HA infrastructure:
https://chefio.atlassian.net/browse/CHEF-711
Start services in all nodes with the flags
Start service in a given node
Start services in given type of node (either all OS or PG or Automate Server or Infra Server)
`build components/automate-cli/`
`chef-automate start --a2 --cs`
https://user-images.githubusercontent.com/98326242/231832973-eb395aac-4dd2-48d1-a8d4-cafaef149f7f.mov
=> Chef-711 Start Command

components/automate-cli/cmd/chef-automate/genA2haRbTmpl.go, components/automate-cli/cmd/chef-automate/haValidationScriptTmpl.go, components/automate-cli/cmd/chef-automate/initConfigHa.go, components/automate-cli/cmd/chef-automate/initConfigHaTmpl.go, components/automate-cli/cmd/chef-automate/pullAndGenerateConfig.go, components/automate-cluster-ctl/lib/cluster/config.rb, components/automate-cluster-ctl/templates/terraform.tfvars.erb, terraform/a2ha-terraform/modules/system/inputs.tf, terraform/a2ha-terraform/modules/system/main.tf, terraform/a2ha-terraform/reference_architectures/deployment/main.tf, terraform/a2ha-terraform/reference_architectures/deployment/outputs.tf, terraform/a2ha-terraform/reference_architectures/deployment/variables.tf, terraform/a2ha-terraform/reference_architectures/existing_nodes/main.tf, terraform/a2ha-terraform/reference_architectures/existing_nodes/outputs.tf, terraform/a2ha-terraform/reference_architectures/existing_nodes/variables.tf
https://chefio.atlassian.net/browse/CHEF-2054
Initialised Automate HA On Prem infra
added custom groupname on all the automate HA nodes
`sudo groupadd aazeez`
`sudo usermod -a -G aazeez ec2-user`
- Rebuild automate-cli (`rebuild components/automate-cli`/) or can use (`aazeez/automate-cli/0.1.0/20230414122935`), automate-ha-cluster-ctl (`rebuild components/automate-cluster-ctl`/) or can use (aazeez/automate-ha-cluster-ctl/0.1.0/20230413171357`), and automate-ha-deployment(`rebuild components/automate-backend-deployment`/) or can use (`aazeez/automate-ha-deployment/0.1.0/20230413175551`).
- Upload the above packages hab pkg upload <PATH_TO_PACKAGE_HART_FILE>.
- Create an airgap bundle with new packages sudo ./chef-automate airgap bundle create -m latest_semver.json --channel dev. Update …
=> ssh_group_name added

components/automate-cli/cmd/chef-automate/certRotate.go
In the HA cluster, custom certs can be enabled on the OS nodes where different certs can be set for each node with a different CN. To preserve the behaviour after cert rotation as well, the certs should be rotated node wise and all the nodes should be aware of each other's new CN.
PR contains the changes to ensure that all the OS are aware of each others CN post cert-rotation as well.
https://chefio.atlassian.net/browse/CHEF-1024
- Should be able to rotate the Root cert, the admin cert and the respective nodes cert.
- Should be able to rotate the certs with different CN on each node
- Checkout this branch
- rebuild components/automate-ci and upload the hab pkg
- Install the new cli in the bastion machine
- Execute the cert-rotate commands as per the doc
With …
=> Rotate certs on OS nodes with different CN

components/automate-ui/src/app/helpers/datetime/datetime.ts, components/automate-ui/src/app/page-components/event-feed-guitar-strings/event-feed-guitar-strings.component.html
Reverted unintended UI changes that were merged as a part of https://github.com/chef/automate/commit/272dd6ec53864591fb3329f0d807a1a75894cc37#diff-cd389b43fc737de0cac38b967ad6dedc5fb1d223c7ec03a4c018a8fc35fe353a 
https://chefio.atlassian.net/browse/CHEF-2700?atlOrigin=eyJpIjoiNGVkNjU4N2Y0NzkwNGIzNWE1YTM2M2RlZjY0MzdhMTAiLCJwIjoiaiJ9
https://github.com/chef/automate/pull/7756/files#diff-2534e18e2d525aa3852d64f7187519153738ff3bbac56885875fa3eb2c8281a9
=> CHEF-2700-issue-changes-required-in-ui-to-revert-unintended-pr-conflict-changes

components/docs-chef-io/content/automate/ha_chef_backend_to_automate_ha.md
Need to change the a parameter while connecting workstation with automate ha chef server
https://chefio.atlassian.net/browse/CHEF-2687
Changed the doc
Preview link.
=> Changes for chef-server fqdn

terraform/a2ha-terraform/reference_architectures/deployment/outputs_common.tf
When user set fqdn value as empty in config.toml, `chef-automate info` command is not should the URL for automate properly
Jira Ticket: https://chefio.atlassian.net/browse/CHEF-2690
**It is dev done and tested in:**
- Do a fresh deployment
- and use the pkg `arvinth/automate-ha-deployment/0.1.0/20230421075459`
=> Fixing Info command with empty `Automate URL` value

components/automate-ui/src/app/modules/token/token-details/api-token-details.component.ts
The project assigned name is changed when we update from active to inactive status and vice versa in the automate API-token.
https://chefio.atlassian.net/browse/CHEF-2688
https://github.com/chef/automate/pull/7720
Video: https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/Ef-r9bLRdHFDrA0dLELRebwBCqrwY7OYUPawHT93-dn8pA?e=e5OSnU
=> The project assigned name is changed when we update from active to inactive status and vice versa in the automate API-token.

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.ts
When there is a waived control present and we want to get the details of that control, no expire date, and the reason is showing in the UI.
https://chefio.atlassian.net/browse/CHEF-2782
Added changes to show the expire date, and the reason on waived controls.
```
STEP 1
STEP 2
to test this please add the test data
```
- [x ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
*Please add a note next to any …
=> Fixed waiver control information not showing in details for a control under nodes

components/automate-backend-deployment/README.md, terraform/a2ha-terraform/reference_architectures/deployment/variables.tf, terraform/a2ha-terraform/variables_common.tf
https://chefio.atlassian.net/browse/CHEF-2775
=> Common output file change to fix add node error

components/automate-backend-deployment/README.md, terraform/a2ha-terraform/modules/system/main.tf
Automate HA - AWS - While creating `tmp_path`, terraform should only modify the SSH User permission
Jira ticket: https://chefio.atlassian.net/browse/CHEF-2852
=> Creating 'tmp_path' and modifying only the SSH User permission

components/automate-cli/cmd/chef-automate/certRotate.go, components/automate-cli/cmd/chef-automate/certRotate_test.go
Please refer following tickets.
https://chefio.atlassian.net/browse/CHEF-2704
https://chefio.atlassian.net/browse/CHEF-2705
For Cluster
https://progresssoftware.sharepoint.com/:i:/s/ChefCoreC/EZu4jGaSyaRJiNMHjoB3N_8BR0ECysbYveh9ObAQU1i8FQ?e=7l2Crg
Node specific command for first time in cluster
https://progresssoftware.sharepoint.com/:i:/s/ChefCoreC/EfM60O9s5HpBjuIpCOJarREBw7nXEtRKfXIYMI5ZXVwnSA?e=ec6y8B
Node specific command for second time in cluster
https://progresssoftware.sharepoint.com/:i:/s/ChefCoreC/Efzv0zGyLcBBsVmMV0UBeX0B6ztbFEpkW …
=> Code changes to achieve idempotency with node flag in OS

components/automate-load-balancer/habitat/config/nginx.conf
Automate Load Balancer does not have any endpoint to get the Nginx stats although the corresponding module http_status is already added in the configuration.
This PR adds the api end point `/nginx_status` endpoint to the automate load balancer which can now expose the API metrics of Automate nodes.
The output can be:
```
Active connections: 1
server accepts handled requests
9 9 8
Reading: 0 Writing: 1 Waiting: 0
```
The data can be utilised by other metrics collector like Datadog and prometheus and show it in the dashboard
- No Issue created. An add hoc idea as part of this 
- The api should be reachable and should respond back when called in the Automate Node
- The api should not be reachable remotely
- `rebuild components/automate-load-balancer`
- `curl -k …
=> Adding Nginx Status API end point in automate loadbalancer nginx config

components/automate-backend-deployment/README.md, terraform/a2ha-terraform/modules/automate/templates/provision.sh.tpl, terraform/a2ha-terraform/modules/habitat/templates/install_hab.sh.tpl
couple of issue in the below PR 
- fix the warnings in the terraform logs 
- save_space function is not freeing up the old airgap bundle 
package link : punitmundra/automate-ha-deployment/0.1.0/20230428071313
=> Fix the warning in the terrafrom code while add-node,upgrade

components/automate-cli/pkg/verifyserver/constants/apiurlconstant.go, components/automate-cli/pkg/verifyserver/constants/nfsmountconstant.go, components/automate-cli/pkg/verifyserver/models/nfsmount.go, components/automate-cli/pkg/verifyserver/server/api/v1/handler.go, components/automate-cli/pkg/verifyserver/server/api/v1/nfsmount.go, components/automate-cli/pkg/verifyserver/server/api/v1/nfsmount_test.go, components/automate-cli/pkg/verifyserver/server/routes.go, components/automate-cli/pkg/verifyserver/server/server.go, components/automate-cli/pkg/verifyserver/services/nfsmountservice/nfsmountservice.go, components/automate-cli/pkg/verifyserver/services/nfsmountservice/nfsmountservice_test.go, components/automate-cli/pkg/verifyserver/services/nfsmountservice/nfsmountservicemock.go
Created  API  /api/v1/checks/nfs-mount. It will check for the given IPs NFS is mounted and shared for the given location or not.
https://chefio.atlassian.net/browse/CHEF-2272
Implemented this API as mentioned in the ticket and also followed the swagger.
=> NFS_Mount_API

components/automate-cli/pkg/verifyserver/models/status.go, components/automate-cli/pkg/verifyserver/server/api/v1/status.go, components/automate-cli/pkg/verifyserver/server/api/v1/status_test.go, components/automate-cli/pkg/verifyserver/services/statusservice/statusservice.go, components/automate-cli/pkg/verifyserver/services/statusservice/statusservice_test.go
Changed response body for status API.
https://chefio.atlassian.net/browse/CHEF-2127
https://github.com/chef/automate/pull/7868
=> Modified status api

components/docs-chef-io/content/automate/restore.md
As an Automate user, when the user is restoring a backup taken from a different (older) version on Automate, he should be able to restore without errors or terminating the services. As per the older documentation, when the user restores without the `--airgap-bundle`  flag, the command tries to restore the application along with its data, which breaks the application. 
Jira ticket(s):
1. https://chefio.atlassian.net/browse/CHEF-2597
=> Doc update

components/automate-cli/cmd/chef-automate/automateConfigUtils.go, components/automate-cli/cmd/chef-automate/automateConstants.go, components/automate-cli/cmd/chef-automate/certRotate.go, components/automate-cli/cmd/chef-automate/certRotate_test.go, components/automate-cli/cmd/chef-automate/cmdUtils.go, components/automate-cli/cmd/chef-automate/cmdUtils_test.go, components/automate-cli/cmd/chef-automate/constants.go, components/automate-cli/cmd/chef-automate/ha_cert_show.go, components/automate-cli/cmd/chef-automate/ha_node_add.go, components/automate-cli/cmd/chef-automate/ha_node_add_aws_test.go, components/automate-cli/cmd/chef-automate/ha_node_delete.go, components/automate-cli/cmd/chef-automate/ha_node_delete_aws.go, components/automate-cli/cmd/chef-automate/ha_node_delete_aws_test.go, components/automate-cli/cmd/chef-automate/ha_node_delete_onprem.go, components/automate-cli/cmd/chef-automate/ha_node_delete_onprem_test.go, components/automate-cli/cmd/chef-automate/ha_node_operations_utils.go, components/automate-cli/cmd/chef-automate/ha_node_operations_utils_test.go, components/automate-cli/pkg/testfiles/aws/config.toml, components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md, lib/platform/command/mock.go, lib/stringutils/strings.go, lib/stringutils/strings_test.go
Remove OpenSearch/Frontend node is not actually removing nodes from the cluster.
Document Change Preview: https://deploy-preview-7922--chef-automate.netlify.app/automate/ha_onprim_deployment_procedure/ and https://deploy-preview-7922--chef-automate.netlify.app/automate/ha_aws_deploy_steps/
https://chefio.atlassian.net/browse/CHEF-2251
=> Chef 2251 remove open search frontend node is not actually removing nodes from cluster

components/automate-cli/cmd/chef-automate/automateHAAwsDeployment.go, components/automate-cli/cmd/chef-automate/automateHADeployExistingInfra.go, components/automate-cluster-ctl/templates/terraform.tfvars.erb
Added the changes to make the OS instance count and OS instance type along with PG instance count and PG instance type as optional for the managed setup.
These changes are applicable for both AWS and Onprem setup
https://chefio.atlassian.net/browse/CHEF-3206
- AWS Managed setup should be successful without providing the OS and PG instance count and type
- Onprem Managed setup should be successful without providing the OS and PG instance count and type
https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/Eecj8a3gf95Pq0HukGrgmOIBc6spTJgeuU …
=> Changes to make OS and PG fields optional for managed setup

components/automate-cli/cmd/chef-automate/cmdUtils.go, components/automate-cli/cmd/chef-automate/cmdUtils_test.go, components/automate-cli/cmd/chef-automate/config.go, lib/stringutils/filepath.go, lib/stringutils/filepath_test.go
Introduced InputFilePrefix - to hold the formatted file name to be used everywhere
https://chefio.atlassian.net/browse/CHEF-3217
User should be able to patch config present in any folder path
Checkout the branch
use the package to test changes
=> Fix config copy issue

components/automate-cli/pkg/verifyserver/constants/firewall.go, components/automate-cli/pkg/verifyserver/models/batchcheck.go, components/automate-cli/pkg/verifyserver/models/firewall.go, components/automate-cli/pkg/verifyserver/server/api/v1/firewall.go, components/automate-cli/pkg/verifyserver/server/api/v1/firewall_test.go, components/automate-cli/pkg/verifyserver/server/api/v1/handler.go, components/automate-cli/pkg/verifyserver/server/api/v1/startMockServer.go, components/automate-cli/pkg/verifyserver/server/routes.go, components/automate-cli/pkg/verifyserver/server/server.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/batchcheckservice_test.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/firewallchecktrigger/firewallchecktrigger.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/sshuseraccesschecktrigger/sshuseraccesschecktrigger.go, components/automate-cli/pkg/verifyserver/services/firewallservice/firewallservice.go, components/automate-cli/pkg/verifyserver/services/firewallservice/firewallservice_test.go, components/automate-cli/pkg/verifyserver/services/firewallservice/firewallservicemock.go, components/automate-cli/pkg/verifyserver/services/startmockserverservice/startmockserverservice.go
As a user I need to check the port reachability between two nodes on given port and using a protocol from Bastion, so that I do not face any issues while doing Automate HA deployment regarding firewall setup and my set up is as per the Automate HA requirements.
https://chefio.atlassian.net/browse/CHEF-2296
- Install the following version of automate-cli or create a new automate-cli with this branch and install it
- `ssanju/automate-cli/0.1.0/20230605104431`
- start go-fiber server with `chef-automate verify server`
- From postman make the following request to the endpoint `http://localhost:7799/api/v1/checks/firewall`
- **POST Request**:
```
{
"source_node_ip": "",
"destination_node_ip": "",
"destination_service_port": "",
"destination_service_protocol": "",
"root_cert": ""
}
```
**All …
=> Firewall API

components/automate-cli/cmd/chef-automate/automateConstants.go, components/automate-cli/cmd/chef-automate/stop.go, components/automate-cli/cmd/chef-automate/stop_test.go, components/docs-chef-io/data/automate/cli_chef_automate/commands/chef-automate_stop.yaml
Added stop command for HA which can be run from bastion node to stop the services of automate, chef_server, postgresql, opensearch.
https://chefio.atlassian.net/browse/CHEF-712
Added stop command for HA which can be run from bastion node to stop the services of automate, chef_server, postgresql, opensearch. You can also provide any particular ip of which you want to stop the services.
Tested on Standalone Automate, Dev Mode and HA deployments.
Install this cli package: sahiba3108/automate-cli/0.1.0/20230615120402
Then you can run stop command. Some of the examples are:
- chef-automate stop --automate (This will stop the services of entire automate cluster)
- chef-automate stop --a2 --node 1.2.3.4 (This will stop the services of particular node of automate cluster)
- chef-automate stop …
=> add stop command

components/automate-cli/cmd/chef-automate/cmdUtils.go, components/automate-cli/cmd/chef-automate/cmdUtils_test.go, components/automate-cli/cmd/chef-automate/restart.go, components/automate-cli/cmd/chef-automate/restart_test.go, components/docs-chef-io/data/automate/cli_chef_automate/commands/chef-automate_restart-services.yaml
As a user of Automate HA, when I run following commands on bastion system of Automate HA cluster, I should see output relevant to Automate HA infrastructure:
chef-automate restart-services
https://chefio.atlassian.net/browse/CHEF-720
1. git checkout this branch
2. rebuild components/automate-cli and upload it to you origin
3. Install automate-cli on bastion\
5. Run chef-automate restart-services 
[Demo-video](https://progresssoftware-my.sharepoint.com/:v:/g/personal/btejaswi_progress_com/EdKhNQR7zadEqV_85PUb7nYB0_7AuvS-LJVS3KJzI_j_aA?e=VoBR …
=> Allowing Restart-Services from bastion

components/automate-cli/cmd/chef-automate/fetchAwsConfigDetails.go, components/automate-cli/cmd/chef-automate/fetchAwsConfigDetails_test.go
For AWS deployment, the config file doesn’t have the node's IP address. 
So the config validator should fetch the required details before validating the config and pass the required config to batch check API.
https://chefio.atlassian.net/browse/CHEF-3505
Fetch the Aws config Details like Private ips of Automate, Chef server, Pg, Os, Automate LB fqdn, Bucket name if we have used s3 as backup config from terraform file.
Invoke this fetchAwsConfigFromTerraform() method, it will return the config fetched from terraform file i.e. output.auto.tfvars
*Please add a note next to any checkbox above if you are NOT ticking …
=> fetch aws config details from terraform

components/automate-cli/pkg/verifyserver/services/mockserverservice/mockserverservice.go
We were getting `409 Conflict` when the mock server tried to start TCP and UDP servers on the common port 9638 of Postgresql Node.
Postgresql needs port 9638 for TCP and UDP.
https://docs.chef.io/automate/ha_on_premises_deployment_prerequisites/#firewall-checks
Before:
After:
=> Fixed mock server 409 conflict error

components/automate-backend-deployment/habitat/plan.sh, components/automate-cli/cmd/chef-automate/verify.go, components/automate-cli/cmd/chef-automate/verify_test.go, terraform/a2ha-terraform/modules/automate/files/config.toml.erb
Check if the automate-verify service is already running on Each Node, else add the automate-verify service to the systemd, and start the automate-verify service on each node, upgrading if needed.
Jira ticket: https://chefio.atlassian.net/browse/CHEF-3588
=> Check for automate-verify service in remote nodes before adding it to systemd in all remote nodes

components/automate-cli/pkg/verifyserver/services/batchcheckservice/batchcheckservice.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/batchcheckservice_test.go
The status api was getting called post bastion checks. It should be only called for remote checks.
https://chefio.atlassian.net/jira/software/c/projects/CHEF/boards/459?modal=detail&selectedIssue=CHEF-2159
1. Build cli with this branch
2. Use this cli to run chef-automate verify --config config.toml
=> Status api should be called for remote checks only

components/automate-cli/pkg/verifyserver/utils/fiberutils/logconfig.go, components/automate-cli/pkg/verifyserver/utils/fiberutils/logconfig_test.go
Initially req body for api's was printed in the log of the verify server.Now there is condition if an env variable "LOG_REQ_BODY" is set it true or not. 
- Checkout this branch and rebuild cli
- start verify server using command `chef-automate verify serve`
- Trigger any post api and see the logs
[Screenshot-1](https://progresssoftware.sharepoint.com/:i:/s/ChefCoreC/EVAOGf6cqTNFkVTQy2CW3kMBUa0vS7KACeD8fRlfud09BQ?e=lHG78x)
[Screenshot-2](https://progresssoftware.sharepoint.com/:i:/s/ChefCoreC/Eb0yKDzCbQdFvkEr5QVnfkcBQZd7ykIVmsqPpS_VmnAj0g?e= …
=> Changes for env var for req body in logs

components/automate-cli/cmd/chef-automate/verify.go, components/automate-cli/cmd/chef-automate/verify_test.go, components/automate-cli/pkg/verifyserver/models/batchcheck.go
Currently both s3-config and nfs-mount check are executed, but only one should execute based on backup_type in config. This PR is fixing this issue
https://chefio.atlassian.net/browse/CHEF-3816
1. Build automate-cli with with branch
2. Run chef-automate verify --config config.toml
=> [CHEF-3816]: Run either s3config or nfs-mount based on backup_type

components/automate-cli/cmd/chef-automate/verify.go, components/automate-cli/pkg/verifyserver/models/batchcheck.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/opensearchs3bucketaccesschecktrigger/opensearchs3bucketaccesscheck.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/opensearchs3bucketaccesschecktrigger/opensearchs3bucketaccesscheck_test.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/s3backupchecktrigger/s3backupconfigchecktrigger.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/s3backupchecktrigger/s3backupconfigchecktrigger_test.go
Currently External OS/PG check execute in every type of infra. These should be skipped if not for a valid infra type
https://chefio.atlassian.net/browse/CHEF-3834
1. Build automate-cli
2. run chef-automate verify --config config.toml
=> Chef 3834 - External OS/PG should be skipped when not valid

components/automate-cli/pkg/verifyserver/models/batchcheck.go, components/automate-cli/pkg/verifyserver/models/nfsmount.go, components/automate-cli/pkg/verifyserver/server/api/v1/nfsmount.go, components/automate-cli/pkg/verifyserver/server/api/v1/nfsmount_test.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/nfsmountbackupchecktrigger/nfsmountbackupcheck.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/nfsmountbackupchecktrigger/nfsmountbackupcheck_test.go, components/automate-cli/pkg/verifyserver/services/nfsmountservice/nfsmountservice.go, components/automate-cli/pkg/verifyserver/services/nfsmountservice/nfsmountservice_test.go
- The NFS Service was not giving the ideal response when one of instance was unmounted it was giving the error into a different variable whereas it should have given the error message into a checks response of the api 
- As we support the NFS backup in Onprem customer managed as well so added the condition around it as well 
- https://chefio.atlassian.net/browse/CHEF-3819
- The Response should come in the checks rather than giving the different response
- Checkout this Branch
- rebuild components/automate-cli
- create the Hab package and install it on your bastion 
- Run the cmd `chef-automate verify --config config.toml` …
=> Added the correct response type in NFS Mount Service Response

components/automate-cli/cmd/chef-automate/verify.go, components/automate-cli/cmd/chef-automate/verify_test.go, components/automate-cli/pkg/verifyserver/models/batchcheck.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/hardwareresourcechecktrigger/hardwareresourcecountchecktrigger.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/hardwareresourcechecktrigger/hardwareresourcecountchecktrigger_test.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/nfsmountbackupchecktrigger/nfsmountbackupcheck.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/nfsmountbackupchecktrigger/nfsmountbackupcheck_test.go, components/automate-cli/pkg/verifyserver/utils/checkutils/checkutil.go, components/automate-cli/pkg/verifyserver/utils/checkutils/checkutil_test.go, components/automate-cli/pkg/verifyserver/utils/httputils/httputil.go
- The UI was not giving the resolution message that were thrown from trigger or Handler funtions and there resolution in the how to resolve message
- the Hardware tigger and NFS mount where using same util it was giving the error response as string ( "400: Bad Request ) otherwise it should be the error that is coming from the Handlers , also refactored both the trigger files as well 
- https://chefio.atlassian.net/browse/CHEF-3796
- The response from the trigger is now shown in the How Resolve section 
- The Error given from the Handlers …
=> UI Fix to give the resolution message

components/automate-cli/pkg/verifyserver/models/batchcheck.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/opensearchs3bucketaccesschecktrigger/opensearchs3bucketaccesscheck.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/opensearchs3bucketaccesschecktrigger/opensearchs3bucketaccesscheck_test.go, components/automate-cli/pkg/verifyserver/services/opensearchbackupservice/opensearchs3backupmanaged.go
As a user when I was doing batch check for aws-opensearch-s3-access its failing with 500 error
The checks are failing because of the following errors:
- The request url have two http protocols.
- os_snapshot_user_access_key_id,`os_snapshot_user_secretkey` values are not mapping in the batch check.
- For this check the Os endpoint url should have ‘https' protocol.
https://chefio.atlassian.net/browse/CHEF-3836
Before this change
After this change
=> Fixing AWS OpenSearch S3 Bucket access check errors

components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/firewallchecktrigger/firewallchecktrigger.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/firewallchecktrigger/firewallchecktrigger_test.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/firewallchecktrigger/vars.go
this was a duplicate check as ssh-user check was doing the same
https://chefio.atlassian.net/browse/CHEF-3873
=> Changes for removing firewall check for port 22 from bastion to cluster

components/es-sidecar-service/habitat/config/config.toml
I added a check for `cfg.backups.backend` in the  es-sidecar-service config template so that if we have that configuration set globally it will respect it. Currently the conditional statement checks only checks for this configuration IF we are using the internal `automate-opensearch` service.
=> Make es-sidecar-service config respect cfg.backups.backend

components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/opensearchs3bucketaccesschecktrigger/opensearchs3bucketaccesscheck.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/opensearchs3bucketaccesschecktrigger/opensearchs3bucketaccesscheck_test.go
1. `aws-opensearch-s3-bucket-access` check should be skipped for Onprem customer managed setup
https://chefio.atlassian.net/browse/CHEF-3876
`aws-opensearch-s3-bucket-access` check  is now skipped for Onprem customer managed setup
1. git checkout this branch
2. rebuild components/automate-cli
3. install automate-cli on bastion
4. Run `chef-automate verify`
Skipping `aws-opensearch-s3-bucket-access` check:
Before this change: Failed `aws-opensearch-s3-bucket-access`
=> skipping aws-opensearch-s3-bucket-access check for Onprem customer-managed

components/automate-cli/pkg/verifyserver/constants/externalopensearch.go, components/automate-cli/pkg/verifyserver/server/api/v1/externalopensearch.go, components/automate-cli/pkg/verifyserver/server/api/v1/externalopensearch_test.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/externalopensearchchecktrigger/externalopensearchchecktrigger_test.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/externalpostgresqlchecktrigger/externalpostgresqlchecktrigger_test.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/firewallchecktrigger/firewallchecktrigger_test.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/fqdnchecktrigger/fqdncheck_test.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/opensearchs3bucketaccesschecktrigger/opensearchs3bucketaccesscheck_test.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/s3backupchecktrigger/s3backupconfigchecktrigger_test.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/softwareversionchecktrigger/softwareversionchecktrigger_test.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/systemresourcechecktrigger/systemresourceschecktrigger_test.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/systemuserchecktrigger/systemuserchecktrigger_test.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/triggerapi.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/triggerapi_test.go, components/automate-cli/pkg/verifyserver/services/externalopensearchservice/externalopensearch.go, components/automate-cli/pkg/verifyserver/services/externalopensearchservice/externalopensearchservice_test.go, components/automate-cli/pkg/verifyserver/services/externalopensearchservice/externalopensearchservicemock.go
- Removed the hardcoded value of port form the external opens each API check
- The domain url present in the request should have the port as the value for connection
- External running open search on a instance 
- External Postgres running on AWS
=> Removed the hardcoded aws port from the external opensearch check

components/automate-cli/cmd/chef-automate/deployedConfig.go, components/automate-cli/cmd/chef-automate/deployedConfig_test.go, components/automate-cli/pkg/verifyserver/models/batchcheck.go
- Efs was skipping in case of aws type setup
- Certbyip support for both pre-deployment and post-deployment 
https://chefio.atlassian.net/browse/CHEF-3737
When backup_config="" :-
When backup_config="efs"(pre-deployment) :-
When backup_config="efs"(post-deployment) :-
CertbyIp Pre-deployment:-
CertbyIp  Post-deployment:-
=> Fix for efs and Certbyip on aws type setup

components/automate-cli/cmd/chef-automate/pullAndGenerateConfig.go
If the deployment is done without any backup configuration then its trying to fetch snapshot role arn which is not required,Now it will only fetch the role-arn if the backup configuration is provided.
https://chefio.atlassian.net/browse/CHEF-3735
=> fetching the snapshot role-arn only if backup config is provided

components/automate-cli/cmd/chef-automate/pullAndGenerateConfig.go, components/automate-cli/cmd/chef-automate/pullAndGenerateConfig_test.go
https://chefio.atlassian.net/browse/CHEF-3779
**BEFORE THE CHANGE**
**AFTER THE CHANGE**
=> fix onprem determine bkp config

components/automate-dex/habitat/hooks/run
https://chefio.atlassian.net/browse/CHEF-3715
=> regenerating the automate-dex build

components/automate-cli/cmd/chef-automate/config.go
Config patch command was not throwing error is incorrect provided for patch for pg and os
https://chefio.atlassian.net/browse/CHEF-1464
- checkout this branch `CHEF-1464` and rebuild cli
- now use this cli on any HA setup where os and pg nodes are available 
- trying patch incorrect config on pg or os nodes
[Demo video](https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/EZqbhhQknM9Ih6Vsf_Atf1gB1K15SRpyltXYKCJIPfxwcA?e=os3KWl)
=> Changes to show error if incorrect config provided for patch

components/automate-cli/cmd/chef-automate/config.go
=> Removed unnecessary flags from oc-id-show-app for automate HA

components/automate-cli/pkg/verifysystemdcreate/systemdcreatesvc.go
As an Automate HA user when I have base binary with different name like `my-automate-build` or `chef-autoamte-linux` etc, then verify server was not able to start because to start server it was looking for file as `chef-automate` but copied file in /etc/automate-verify/ was different, with this fix command will copy binary with name of `chef-automate` only for any base binary name given
Dev tested
`cd component/automate-cli`
`make linux` or `make darwin`
=> re-naming chef-automate binary to chef-automate in etc verify

components/automate-cli/cmd/chef-automate/gather-logs.go
Modified the gather logs to capture logs from below location in chef managed postgres cluster
`/hab/svc/automate-ha-postgresql/var/pg_log`
https://chefio.atlassian.net/browse/CHEF-3363
Added  `/hab/svc/automate-ha-postgresql/var/pg_log`  to Postgresql cluster in gather-logs
`chef-automate gather-logs`
https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/EaVpTKYMTVNAsYIdQ4ESRgEB761RZB0LpQGJdAi8qtWB8A?e=Z7d7vZ
=> Gather logs should capture logs from different locations (PG)

components/automate-cli/cmd/chef-automate/status.go, components/automate-cli/cmd/chef-automate/summary.go, components/automate-cli/cmd/chef-automate/summary_test.go, dev/populate_chef_backend_data.sh
As an Automate HA user, along with the service status, the user should see follower node lag for Postgresql as well in the cluster status.
> Note:
>  For the leader node, "NA" will be shown
> Previously, the cumulative cluster status can be fetched in Bastion by the `chef-automate status` command. Now the same can be done by the `chef-automate status summary` command, whereas the `chef-automate status` will now show the service status(on node level) of each nodes (For reference, PFA in the 'Screenshot' column below)
Jira: https://chefio.atlassian.net/browse/CHEF-3561
*Please add a note next to any checkbox above …
=> Adding Lag for PG follower node in status summary command

terraform/a2ha-terraform/modules/aws/main.tf
We have an automate array like [a, b, c, d]
If we remove the node b, it deletes the node b, it deletes the node d and then it creates a fresh machine in place of node b
This is unexpected behaviour since we did not want to do anything to node d
https://chefio.atlassian.net/browse/CHEF-3630
`rebuild components/automate-backend-deployment` package 
OR
use this package: `ssanju/automate-ha-deployment/0.1.0/20230719095316`
Video Link: https://progresssoftware-my.sharepoint.com/:v:/g/personal/ssanju_progress_com/EdSY_F9H_BpHsVn7pP_nu_0BuJbdhLDNk …
=> AWS Remove Node Fix

components/automate-deployment/pkg/server/gather-logs.go, lib/platform/pg/conninfo.go, lib/platform/pg/exporter_test.go
In Standalone Automate when we trigger the chef-automate gathers-logs command it collect the logs. 
In case of Automate is using external database then it is not able to pull the basic details because it is using localhost instead of it have to user the external postgres url.
https://chefio.atlassian.net/browse/CHEF-1636
Now, chef-automate gathers-logs command collect the logs in case if we are using external postgresql.
Use the below pkg:
- sahiba3108/deployment-service/0.1.0/20230720103238
Video Link: …
=> chef-1636_gather_logs

components/automate-backend-deployment/README.md, terraform/a2ha-terraform/modules/aws/loadbalancing.tf, terraform/a2ha-terraform/modules/aws/main.tf, terraform/a2ha-terraform/modules/aws/outputs.tf
Made public subnet optional in config.toml
https://chefio.atlassian.net/browse/CHEF-3646
Use Package: `akrishna/automate-ha-deployment/0.1.0/20230718130731`
Demo: https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/EdNK_u6VKlJHo23cpq6GKwIBgbqSUH5M7v8bzYIpsw1tVg?e=cFbIec
=> Provision AWS LB should have an option to choose the Private subnet

components/automate-backend-opensearch/habitat/config/opensearch.yml, components/automate-backend-opensearch/habitat/default.toml, components/automate-cli/cmd/chef-automate/configTemplate.go, components/automate-cli/cmd/chef-automate/ha_node_operations_utils.go, components/automate-cli/cmd/chef-automate/ha_node_operations_utils_test.go, components/docs-chef-io/content/automate/ha_config.md, terraform/a2ha-terraform/modules/opensearch/templates/opensearch_user.toml.tpl
we need to support max_shard_per_node via patch command
https://chefio.atlassian.net/browse/CHEF-3647
Demo Video : [max_shard_per_node.mp4](https://progresssoftware-my.sharepoint.com/:v:/g/personal/smudassi_progress_com/ERC2DBU4NphLipjfmM-hsvMBwk4bOIv03vxCDTG42wX7hA?e=jhNXWY)
=> support max shard configuration via patch

lib/config/genconfig/awshaprovisionconfig.go, lib/config/genconfig/awshaprovisionconfig_test.go, lib/config/genconfig/hadeployconfig.go, lib/config/genconfig/hadeployconfig_test.go
1. When we select the top most prompt for enable custom cert as true then in case of aws managed it sets enabled_custom_cert as true which fails the provision. 
2. It makes the default value of instance type for all FE nodes to be m5.large
3. General UI fix 
This should help generate correct config in case of aws managed when enable custom cert is set true on top
1. cd automate/components/automate-cli
2. make darwin or make linux
3. sudo ./bin/darwin/chef-automate config gen config.toml or sudo ./bin/linux/chef-automate config gen config.toml
*Please add a note next to any checkbox above if you are NOT ticking …
=> [config-gen-managed-db-default]: Set enable custom cert false for aws managed 

components/automate-cli/cmd/chef-automate/pullAndGenerateConfig.go, components/automate-cli/cmd/chef-automate/pullAndGenerateConfig_test.go
In case of add node the common certs is fetching the private key from one ip and public key from the other ip so its causing error while adding a node with this change it will fetch both the keys from single ip
=> In pullAndGenerate fetching private and public keys from the same ip

components/automate-cli/pkg/verifyserver/models/batchcheck_test.go, components/automate-cli/pkg/verifyserver/models/testdata/HaOnPremFileSystem.toml, lib/config/hadeployconfiggetters.go
When the user choose 'file_system' for the backup config (create config with `config gen` command), it throws the following panic error
=> Fixing panic error when user choose 'file_system' for backup config

components/automate-deployment/habitat/plan.sh, components/docs-chef-io/content/automate/ha_aws_deployment_prerequisites.md, components/docs-chef-io/content/automate/ha_on_premises_deployment_prerequisites.md
5432 port was missing in Port usage definitions section
=> port 5432 in Port usage definitions

components/automate-cli/pkg/reportgenerator/usagegenerator.go
When es-gateway port is passed, the url should consider http protocol rather than https.
https://chefio.atlassian.net/browse/CHEF-4290
Now license usage will work as expected
```
chef-automate license complianceResourceRunCount -p 10144 -s 2023-07-31 -e 2023-07-31
```
https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/EUezEJW_HrZDh1lXWYSgtzABozkQM6_OGv0X2mtqQCG8RQ?e=7AmrHQ
=> Adding es-gateway url

components/automate-gateway/gateway/middleware/authz/authz.go
https://chefio.atlassian.net/browse/CHEF-5493
`
`
Current response
Response after code change
=> removed extra details from resp

components/automate-gateway/handler/notifications.go
https://chefio.atlassian.net/browse/CHEF-5489
Webhook error msg are customised 
`
rebuild components/automate-deployment
`
Current response
Response after code change
=> webhook notification error msg fix

components/automate-cli/cmd/chef-automate/service_versions.go, components/automate-cli/cmd/chef-automate/service_versions_test.go, components/docs-chef-io/data/automate/cli_chef_automate/commands/chef-automate_service-versions.yaml
Added service-versions command for HA which can be run from bastion node to get the service-versions of automate, chef_server, postgresql, opensearch.
https://chefio.atlassian.net/browse/CHEF-716
- Added service-versions command for particular node
- Added service-versions command for all the services(automate, chef server, Postgresql,opensearch)
- Added service-versions command for either of the nodes.
`build components/automate-cli`
Run command from the Bastion:
`chef-automate service-versions --a2`
AWS Managed Services …
=> service_versions command

components/automate-cli/cmd/chef-automate/applications.go, components/automate-cli/cmd/chef-automate/applications_test.go, components/automate-cli/cmd/chef-automate/cliUtils.go, components/automate-cli/cmd/chef-automate/cliUtils_test.go, components/automate-cli/cmd/chef-automate/iam.go, components/automate-cli/cmd/chef-automate/infrastructure.go, components/automate-cli/cmd/chef-automate/license.go, components/docs-chef-io/data/automate/cli_chef_automate/commands/chef-automate_applications.yaml, components/docs-chef-io/data/automate/cli_chef_automate/commands/chef-automate_applications_remove-svcs.yaml, components/docs-chef-io/data/automate/cli_chef_automate/commands/chef-automate_applications_show-svcs.yaml
Added applications command for HA which can be run from bastion node.
https://chefio.atlassian.net/browse/CHEF-726
Added applications command for HA which can be run from bastion node. 
applications command has 2 subcommands:
`show-svcs`: Show all the services or you can also use some flags to filter out the data
`remove-svcs`: This will remove the services based on the given flags.
Upload some data to Applications tab. 
Install this cli package: `ssanju/automate-cli/0.1.0/20230810092307`
Then you can run applications command. Some of the examples are:
`chef-automate applications show-svcs` (show all the services)
`chef-automate applications show-svcs --service-name nginx` (show service which is having service name as nginx)
`chef-automate applications remove-svcs --service-name nginx` …
=> Application Command

components/automate-cli/cmd/chef-automate/config.go
In dev branch, config patch command was giving nil pointer exception. This got fixed now.
https://chefio.atlassian.net/browse/CHEF-5716
Install this cli: hab pkg install sahiba3108/automate-cli/0.1.0/20230818064639 -bf
=> config patch command fix

components/automate-cli/cmd/chef-automate/verify.go, components/automate-cli/cmd/chef-automate/verify_test.go
Enchance the error message to say check 7799 port on all the remote machines
https://chefio.atlassian.net/browse/CHEF-5795
Now it will show all the nodes where port 7799 is not opened
Video Link:
Onprem with Chef Managed (Pre Deployment): https://progresssoftware-my.sharepoint.com/:v:/g/personal/ssanju_progress_com/EaPcntY1hL9IopmnD3-t-VQBwsQYq3lTm_LipuI5vJ5OZA?e=i6iWDm
Onprem with Chef Managed (Post Deployment): https://progresssoftware-my.sharepoint.com/:v:/g/personal/ssanju_progress_com/ETTg9DkbGjVNuWUyDykvMCcBasTkhH7YWyAdEQ9WPuXkEA?e=XT …
=> Showing error message if 7799 port is not opened on remote nodes

components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/sshuseraccesschecktrigger/sshuseraccesschecktrigger.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/sshuseraccesschecktrigger/sshuseraccesschecktrigger_test.go
In verify check changed chmod permissions to allow 600 as earlier it only allowed till 400 
https://chefio.atlassian.net/browse/CHEF-5660
Build automate-cli
bvtejaswi/automate-cli/0.1.0/20230821095409
=> In verify check changed chmod permissions to allow 600

components/automate-cli/pkg/verifyserver/constants/sshusercheck.go, components/automate-cli/pkg/verifyserver/services/sshusercheckservice/sshusercheckservice_test.go, lib/config/genconfig/awshaprovisionconfig.go, lib/config/genconfig/awshaprovisionconfig_test.go, lib/config/genconfig/hadeployconfig.go, lib/config/hadeployconfig.go, lib/pmt/prompt.go
**IAM role:**
- When the IAM role is attached to the bastion, the user should able to use IAM role instead of IAM User credentials
- prompt to create snapshot credentials
**Config gen update**
- Update the regex error with the sample pattern in the text label
- gen prompt should show that the subnet id should be added when the user chooses to provide to subnets
- Showing sample values in Label wherever necessary
Jira: https://chefio.atlassian.net/browse/CHEF-4734
https://chefio.atlassian.net/browse/CHEF-5511
[Demo …
=> Updating config-gen and error messages

components/automate-cli/cmd/chef-automate/ha_node_operations_utils.go
Removed config sync logic for OS which is not needed
https://chefio.atlassian.net/browse/CHEF-5662
After AWS Deployment did the following things:
-  Changed the max-shard-per-node value and patched to OS node
- Added new OS node
- New OS node has updated config
- upgarded with cli
- After upgradation it still has updated config
build components/automate-cli
[Demo-video](https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/ERz0gqXPFxBFtwD2wulL2HAB8cu49VaD1Z9_IqX-3M6QqA?e=hp89Uz)
=> Removed config sync logic for OS

components/automate-cli/cmd/chef-automate/deployedConfig.go, components/automate-cli/cmd/chef-automate/deployedConfig_test.go, components/automate-cli/cmd/chef-automate/initConfigHa.go, components/automate-cli/cmd/chef-automate/pullAndGenerateConfig.go, components/automate-cli/cmd/chef-automate/pullAndGenerateConfig_test.go
Now able to pull the latest GCS config in pull and generate.
https://chefio.atlassian.net/browse/CHEF-5620
https://chefio.atlassian.net/browse/CHEF-5625
Build the cli or use this cli: `ssanju/automate-cli/0.1.0/20230828052937`
Video Link: https://progresssoftware-my.sharepoint.com/:v:/g/personal/ssanju_progress_com/ETQ2B_TFat1Eh9R0ci3I3ZgBMGTmjIbk2Xs6fZXtUZgGmg?e=znhU8k
=> pull and generate gcs config

components/automate-cli/cmd/chef-automate/cleanup.go
When the cleanup command is triggered, it should not delete the hab deployment workspace
Jira: https://chefio.atlassian.net/browse/CHEF-2769
In case of error, command message won't be shown
=> Fixing cleanup command to ignore uninstalling hab workspace

components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/s3backupchecktrigger/s3backupconfigchecktrigger.go, components/automate-cli/pkg/verifyserver/services/s3configservice/s3configservice.go, components/automate-cli/pkg/verifyserver/services/s3configservice/s3configservice_test.go
When the user is configuring S3 as a backup in AWS, the verify command fails for S3-backup-check in the pre-deployment flow with the following error in the screenshot.
Reason:
While creating a new session in AWS the region is not taken. So the session created is not proper and unable to connect to the bucket, as it takes us-east-1 as the default region and the user bucket is in the ap-south-1 region.
**Other issue:**
- AWS-SDK expects the endpoint URL to be in the following pattern `https://s3.REGION.amazonaws.com`. For **https://s3.amazonaws.com** , it consider it as the bucket is in us-east-1 (default region)
To fix this, the endpoint URL is programmatically changed to the `https://s3.REGION.amazonaws.com` pattern which is only applicable to the AWS S3 bucket endpoint URL.
Jira ticket: …
=> Fixing bug -  to take region from input while making AWS connection

components/automate-ui/src/app/services/license-usage/license-usage.service.spec.ts
Updated test cases as per latest code change.
https://chefio.atlassian.net/browse/CHEF-4690
- [ x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ x] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).
- [x ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ x] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ x] Repeated code blocks eliminated? *(adapt and reuse …
=> CHEF-4690: Updated test cases as per latest code change.

components/automate-cli/cmd/chef-automate/certRotate.go, lib/config/genconfig/awshaprovisionconfig.go
When the config-gen is executing for AWS infra flow, it should ask the user to provide the public subnet 
Jira: https://chefio.atlassian.net/browse/CHEF-6155
Updated prompt message:
=> Updating config-gen prompt for providing public subnet

components/automate-cli/cmd/chef-automate/deployedConfig.go, components/automate-cli/cmd/chef-automate/deployedConfig_test.go, components/automate-cli/cmd/chef-automate/verify.go, components/automate-cli/cmd/chef-automate/verify_test.go
Now we are getting GCS config in post deployment.
https://chefio.atlassian.net/browse/CHEF-5625
Video Link: https://progresssoftware-my.sharepoint.com/:v:/g/personal/ssanju_progress_com/EV1Eb4lfF_5IlaLSvEvcZ7EBtPSw7dDYbUYDMp-P6KcK7A?e=oaIaob
=> GCS Post Verification

components/automate-backend-deployment/README.md, components/automate-cli/cmd/chef-automate/cliUtils.go, terraform/a2ha-terraform/modules/automate/templates/provision.sh.tpl
As an Automate HA user, when I use RHEL, the SELinux should set to permissive while deployment.
- Deploy will handle setting SELinux config to permissive during deployment for RHEL 8
- Same for Add node flow
Jira: https://chefio.atlassian.net/browse/CHEF-6159
=> SELinux should be permissive or disabled during deployment 

components/automate-cli/cmd/chef-automate/certRotate.go
increased default timeout for cert rotate previously it was 180 now updated to 600 as the services are not coming up with in 180
https://chefio.atlassian.net/browse/CHEF-6182
Tested rotating backend node without giving --wait-timeout flag
`bvtejaswi/automate-cli/0.1.0/20230905065139`
=> increased default timeout for cert rotate

components/automate-cli/cmd/chef-automate/automateClusterCtlUtil.go
removing duplicated hard-coded commands in deployment output
=> removing hardcoded commands in deployment output

components/automate-cli/cmd/chef-automate/certRotate.go
Earlier this error is coming in 5 nodes cluster deployment.
rebuild the cli or use this cli `ssanju/automate-cli/0.1.0/20230905100216`
=> Unique ips while rotating the certs

components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/s3backupchecktrigger/s3backupconfigchecktrigger.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/s3backupchecktrigger/s3backupconfigchecktrigger_test.go
AWS S3 backup check is skipped in the AWS Chef Managed if we set backup_config = "s3"
=> AWS S3 config check fix

components/automate-cli/cmd/chef-automate/pullAndGenerateConfig.go
In case of upgrade from old deployment when we are doing verify using verify command, it looks for port and it is failing, adding default port
=> adding default port value as 22 in case of blank port from tfvars

components/automate-cli/cmd/chef-automate/verify.go, lib/arrayutils/remove_duplicate.go, lib/arrayutils/remove_duplicate_test.go
As an Automate HA user, when I use 5 node cluster, it shows the error as follow:
This is because the IPs are repeated and and `systemd-service create` is executing twice at the same time. 
In this PR, the duplicate IP are removed so the verify will run without errors. 
Screenshot: https://progresssoftware.sharepoint.com/:i:/s/ChefCoreC/EcPSQyX-U11Es7dcKyucnl4BwTLEuKg9zOgVt5UN0BX6Aw?e=ql9ieM
Jira: https://chefio.atlassian.net/browse/CHEF-6207
For 5 node cluster (or minimum node cluster) …
=> Removing duplicate IPs for 5 node cluster

components/automate-cli/cmd/chef-automate/config.go, components/automate-cli/cmd/chef-automate/configTemplate.go, components/automate-cli/cmd/chef-automate/config_test.go, components/automate-cli/pkg/testfiles/aws/centralised_log.toml, components/automate-cli/pkg/testfiles/aws/invalid_pg.toml, components/automate-cli/pkg/testfiles/aws/pg.toml
While patching centralised logging after successful patch in the end its exiting with an error which is thrown from pg config patch flow ,to avoid this the changes were made to exit from the flow right after successful centralised log patch.
https://chefio.atlassian.net/browse/CHEF-6209
Tested config patch with following types of configs :
build automate-cli and install in bastion
[Demo video](https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/EQhPUhlr7dZMlEX5Zxsaw9sB620xEJaIj9Dd5DWVjyeHAQ?e=MjunbV)
[screen …
=> Centralised Logging throwing error invalid config for PG and OS in automate HA

components/automate-cli/cmd/chef-automate/restart.go, components/automate-cli/cmd/chef-automate/service_versions.go, components/automate-cli/cmd/chef-automate/service_versions_test.go, components/automate-cli/cmd/chef-automate/status.go, components/automate-cli/cmd/chef-automate/status_test.go
In some environment they are not allowing to set the env variable.
For `chef-automate status` and `chef-automate service-versions` command internally we are using env variable in a command `sudo HAB_LICENSE=accept-no-persist hab svc status` so to accept hab license we are making use of a new flag which will accept the license
In automate installation setting the HAB_LICENSE is required and it is mandatory, with out setting this env flag we can not install the standalone automate and automate-HA.
By doing this ticket we are just adding the support for the flag --accept-hab-licence for chef-automate status command. 
https://chefio.atlassian.net/browse/CHEF-6574
Tested with `chef-automate status` and `chef-automate service-versions` backend flags  …
=> Added new flag for status and service-versions command to accept hab license

components/automate-backend-deployment/habitat/bin/prepare-a2-deployment-workspace, components/automate-backend-deployment/habitat/hooks/install, components/automate-backend-deployment/habitat/plan.sh, components/automate-cluster-ctl/habitat/plan.sh, terraform/a2ha-terraform/destroy/aws/main.tf, terraform/a2ha-terraform/modules/airgap_bundle/inputs.tf, terraform/a2ha-terraform/modules/airgap_bundle/main.tf, terraform/a2ha-terraform/modules/aws/main.tf, terraform/a2ha-terraform/modules/aws/opensearch_snapshot_registry.tf, terraform/a2ha-terraform/modules/aws/outputs.tf, terraform/a2ha-terraform/modules/aws/security.tf, terraform/a2ha-terraform/modules/aws_metadata/output.tf, terraform/a2ha-terraform/modules/aws_output/main.tf, terraform/a2ha-terraform/modules/efs/main.tf, terraform/a2ha-terraform/modules/elasticsearch/main.tf, terraform/a2ha-terraform/modules/opensearch/inputs.tf, terraform/a2ha-terraform/modules/opensearch/main.tf, terraform/a2ha-terraform/modules/postgresql/inputs.tf, terraform/a2ha-terraform/modules/postgresql/main.tf, terraform/a2ha-terraform/modules/system/main.tf, terraform/a2ha-terraform/modules/vsphere/main.tf, terraform/a2ha-terraform/reference_architectures/aws/outputs.tf, terraform/a2ha-terraform/reference_architectures/aws/variables.tf, terraform/a2ha-terraform/reference_architectures/deployment/variables.tf
https://chefio.atlassian.net/browse/CHEF-7297
=> Terraform Upgrade in Automate HA

components/backup-gateway/habitat/plan.sh
Build the minio binary in backup-gateway 
=> CHEF-6969 Added minio into the backup gateway 

components/automate-cds/habitat/default.toml, components/automate-cds/server/root.go, components/automate-cds/server/server.go
When we were patching any log level, it was not considering that level and showing all logs. So fixed this issue
https://chefio.atlassian.net/browse/CHEF-7332
=> log level fix for automate-cds

components/docs-chef-io/content/automate/ha_backup_restore_aws_efs.md, components/docs-chef-io/content/automate/ha_backup_restore_aws_s3.md, components/docs-chef-io/content/automate/ha_backup_restore_file_system.md, components/docs-chef-io/content/automate/ha_backup_restore_object_storage.md
=> update the doc change for lcr not suppoted in Automate HA

components/automate-backend-deployment/habitat/plan.sh, components/automate-cli/cmd/chef-automate/initConfigHaTmpl.go, components/automate-cli/cmd/chef-automate/upgrade.go, terraform/a2ha-terraform/modules/automate/templates/provision.sh.tpl
When user upgrade the bundle to latest, some configuration belongs to Automate config which are updated are reverting back to initial values. In this PR, that is addressed
Jira ticket: https://chefio.atlassian.net/browse/CHEF-8418
In the below screenshot, when the deployment done, the original base path highlighted would be "elasticsearch", which lated updated to "opensearch".
After upgrade, the same value is intact
[Screenshot](https://progresssoftware.sharepoint.com/:i:/s/ChefCoreC/EZU33NVRF-dIvZs1doQ7iTEBEhfp5MceF8gRsqkXme_Ddw?e=ONBWpn)
=> Remvoing config patch for old configs in upgrade and add/remove node

components/automate-ui/src/app/types/types.ts
Node attributes displayed in the Infrastructure tab under the All view are not displaying values in proper precedence. For example, we have a cookbook that defines a default attribute value and the node has defined a normal attribute value which displays properly under the Default and Normal views, but under the All view, it is not showing the Normal value. 
https://chefio.atlassian.net/browse/CHEF-5829
I have added changes to fix this bug.
Set up a cookbook that defines a default attribute value and a node with a defined normal attribute value, and run the cookbook against the node. Look at the Infrastructure tab under the All view and by the rules of precedence, we would expect the All view to show the "normal" value.
With occasional exceptions, all PRs …
=> Attributes in Automate All view not showing normal precedence

components/automate-cs-ocid/habitat/config/tasks/oauth_application.rake, components/automate-cs-ocid/habitat/plan.sh
The oc-id component of the infra server has been upgraded to use ruby 3+ and rails 7+ in version `15.8.0`. This PR aims to upgrade the bundled ocid to use `15.8.0` from `15.4.0` in the `automate-cs-ocid` component of chef-automate.
1. The `do_build` block in ocid's `plan.sh` has been removed as part of this PR as intended since the tzinfo-data  gem has been packaged with the new ocid bundle 15.8.0 and is not required in this block anymore.
2. The changes in the [oauth_application.rake](https://github.com/chef/automate/pull/8248/files#diff-921e5bd864e753670926ffc22d3add4674f9aad090969c922fc365cd54198d04) is part of a security fix for [CVE-2020-10187](https://nvd.nist.gov/vuln/detail/CVE-2020-10187) 
All the following topologies of automate and automate HA and have verified with the new …
=> Upgrading to ocid 15.8.0 in Automate

components/automate-ui/src/app/modules/infra-proxy/infra-node-details/infra-node-details.component.html, components/automate-ui/src/app/modules/infra-proxy/infra-node-details/infra-node-details.component.scss, components/automate-ui/src/app/modules/infra-proxy/infra-node-details/infra-node-details.component.ts
We can insert HTML tags and links as chef tags and chef tag also accepts special characters and value input, meaning there is no proper whitelisting and input value validation.
https://chefio.atlassian.net/browse/CHEF-2850
=> validation for preventing special character in html tags 

components/automate-openjdk/habitat/plan.sh
Upgraded JDK version from 11.0.20+8 to 11.0.22+7
https://chefio.atlassian.net/browse/CHEF-10196
Upgraded JDK version from 11.0.20+8 to 11.0.22+7
rebuild components/automate-openjdk/
rebuild components/automate-backend-opensearch/
rebuild components/automate-backend-elasticsidecar/
rebuild components/automate-opensearch/
https://progresssoftware-my.sharepoint.com/:v:/g/personal/swatign_progress_com/EfngL2AYWl5JhYENGEAgYRUBn_lEWqyf7V6s5dWXYTX-nw?e=nbR72a
=> updated openjdk version 11.0.22.7

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.scss
Compliance ce/Reports tab, not able to scroll if the user wants to check the scan results
https://chefio.atlassian.net/browse/CHEF-2659
I have added CSS changes to fix this issue.
https://github.com/chef/automate/assets/12297653/9d49d12a-3f01-475f-932f-e065969c073b
=> Fixed UI Issue in Compliance/Reports tab, unable to scroll

components/automate-ui/src/app/page-components/search-bar/search-bar.component.ts
The search is not sensitive to the case, the fix can be seen in the recording below.
https://github.com/chef/automate/assets/141399313/1b2b86a7-042f-42d9-8d89-eeb189cd39b8
=> CHEF-5310: Added case insensitive match for search

components/docs-chef-io/Makefile
Switch Netlify to execute a bash script.
[CHEF-11081](https://chefio.atlassian.net/browse/CHEF-11081)
https://github.com/chef/chef-web-docs/pull/4255
[CHEF-11081]: https://chefio.atlassian.net/browse/CHEF-11081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update Netlify deploy script

components/automate-cli/cmd/chef-automate/migration_pg.go, components/automate-postgresql/habitat/plan.sh
changed done inside plan.sh file of automate-postgresql component. version changed from 13.5 to 13.14
changed postgres version from 13.5 to 13.14 
https://progresssoftware-my.sharepoint.com/:v:/g/personal/kparmar_progress_com/Ea8mvwya_DFEgjGIuwT-a7MBwQgfDBlqeyYLV4W9xCMDWQ?e=FcTOwV&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D
=> Changed Pg version

components/automate-ui/src/app/pages/+compliance/+reporting/reporting-searchbar/reporting-searchbar.component.ts, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.ts
As an Automate user, If your mouse is in the wrong position on the screen when you are trying to filter by nodes. You will always get the selected node from the list instead of your wildcard search.
https://chefio.atlassian.net/browse/CHEF-6423
I have added changes to prevent the mouse is clicking outside the suggestion list and the user can easily search the wildcard suggestion after typing in input.
https://github.com/chef/automate/assets/12297653/db2466ba-66b5-4e2f-a4bf-22a97afc7802
=> fixed for - Can't Easily Filter By Nodes When Doing a Wildcard Search in Automate

components/automate-ui/src/app/page-components/event-feed-guitar-strings/event-feed-guitar-strings.component.html, components/automate-ui/src/app/pages/event-feed/event-feed.component.spec.ts, components/automate-ui/src/app/pages/event-feed/event-feed.component.ts
Event Feed fails to show data after filtering, event feed date and timescale in Automate UI, show the difference of N-1 days.
https://chefio.atlassian.net/browse/CHEF-10006
I have added changes to fix the event feed data to show properly after filter apply.
=> Fixed event feed fails to show data after filtering, event feed date.

components/automate-cli/cmd/chef-automate/infrastructure.go, components/automate-cli/cmd/chef-automate/infrastructure_test.go, components/automate-cli/pkg/status/result.go
Now license status will be checked when a user is using infrastructure node-delete command.
https://chefio.atlassian.net/browse/CHEF-11900
License failure is responded back in case of no license applied
https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/EbxR7Zs6lR5HqlitmAZQzocB9fmT_a2id0B9SxCnrnvn9Q?e=MyDcoq
=> Infrastructure node cli license changes

components/chef-ui-library/src/index.html, components/chef-ui-library/src/sandbox.html
Minor changes to remove the polyfills CDN form chef-ui-library
=> CHEF-13723 Remove polyfills cdn from automate - chef-ui-library

components/automate-ui/src/app/modules/license/license-apply/license-apply.component.html, components/automate-ui/src/app/modules/license/license-apply/license-apply.component.scss, components/automate-ui/src/app/modules/license/license-apply/license-apply.component.ts, components/automate-ui/src/app/modules/license/license-lockout/license-lockout.component.html, components/automate-ui/src/app/modules/license/license-lockout/license-lockout.component.scss
Currently, in the “Welcome to Chef Automate” pop-up, we give users an option to either provide their details and get a new trial license or ask them to enter a license key if they have one.
https://chefio.atlassian.net/browse/CHEF-13463
I have added UI changes for the license welcome modal
https://github.com/user-attachments/assets/03fcc10d-72da-4767-8234-45cbe0b0f62d
=> UI changes for the apply license and welcome modal popup

components/compliance-service/api/stats/server/server.go, components/compliance-service/reporting/relaxting/stats.go, components/config-mgmt-service/backend/elastic/telemetry.go, components/config-mgmt-service/grpcserver/telemetry.go, components/license-control-service/licenseaudit/licenseauditworkflow.go, components/license-control-service/licenseaudit/licenseauditworkflow_test.go
Changing the days of license audit data to be 30 days. Now it will send all the unique nodes for last 30 days.
https://chefio.atlassian.net/browse/CHEF-11615
```
rebuild components/config-mgmt-service/
rebuild components/license-control-service
```
[CHEF-11615.mov](https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/EcTZJYOcNi5Eqqnvm0_m-u0B7_y9CI9_-Qt6UZ5vqNAdwQ?e=5czWkM&isSPOFile=1)
=> Adding license audit date as last 30 days

components/automate-backend-haproxy/habitat/config/haproxy.conf, components/automate-backend-haproxy/habitat/hooks/reconfigure, components/automate-cli/cmd/chef-automate/certRotate.go, components/automate-cli/cmd/chef-automate/ha_node_add.go, components/automate-cli/cmd/chef-automate/ha_node_add_aws.go, components/automate-cli/cmd/chef-automate/ha_node_add_aws_test.go, components/automate-cli/cmd/chef-automate/ha_node_add_onprem.go, components/automate-cli/cmd/chef-automate/ha_node_add_onprem_test.go, components/automate-cli/cmd/chef-automate/ha_node_add_test.go, components/automate-cli/cmd/chef-automate/ha_node_delete.go, components/automate-cli/cmd/chef-automate/ha_node_delete_aws.go, components/automate-cli/cmd/chef-automate/ha_node_delete_aws_test.go, components/automate-cli/cmd/chef-automate/ha_node_delete_onprem.go, components/automate-cli/cmd/chef-automate/ha_node_delete_onprem_test.go, components/automate-cli/cmd/chef-automate/ha_node_delete_test.go, components/automate-cli/cmd/chef-automate/ha_node_operations_utils.go, components/automate-cli/cmd/chef-automate/sshAutomateHA.go, components/automate-cli/cmd/chef-automate/summary_test.go, components/automate-ha-pgleaderchk/habitat/hooks/reconfigure
Added PostgreSQL nodes restart logic in the Add/Remove flow, in order to apply the newest HAProxy configuration. Currently the configuration is being updated, but due to the `reconfigure` hook we introduced for HAProxy, the service isn't getting restarted and is not using the latest configuration (thus routing traffic to outdated nodes). That's why we want to restart the habitat supervisor of all the PostgreSQL nodes, if a PostgreSQL node/s is added/removed.
=> Restart all the PostgreSQL nodes after Add/Remove command

components/automate-cli/cmd/chef-automate/helper.go, components/automate-cli/cmd/chef-automate/helper_test.go, components/automate-cli/cmd/chef-automate/iam.go, components/automate-cli/cmd/chef-automate/infrastructure_test.go, components/automate-cli/cmd/chef-automate/maintenance.go, components/automate-cli/cmd/chef-automate/start_linx.go, components/automate-cli/cmd/chef-automate/upgrade.go
=> backward compatibility

components/automate-ui/src/app/services/license-usage/license-usage.service.ts
Updated usage of days_since_last_post to set to static 30 days to align with analytics cli
Updated usage of days_since_last_post to set to static 30 days to align with analytics cli
- [x ] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ x] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).
- [x ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ x] Consistency checked? *(user notifications, user prompts, visual patterns, code …
=> Updated usage of days_since_last_post to set to static 30 days to align with analytics cli

components/automate-backend-deployment/README.md, terraform/a2ha-terraform/modules/postgresqlconfigsync/inputs.tf, terraform/a2ha-terraform/modules/postgresqlconfigsync/main.tf, terraform/a2ha-terraform/modules/postgresqlconfigsync/templates/postgres_configsync.sh.tpl, terraform/a2ha-terraform/reference_architectures/deployment/main.tf, terraform/a2ha-terraform/reference_architectures/existing_nodes/main.tf
Deployment will required the reload the config for haproxy and pg leader check. 
During deployment if all the node for the pg cluster won't we in sycn, then the haproxy config will not be in the sync. 
To make it sync we are using the stop start `hab-sup`, but that also doesn't guarantee that it will be execute in synchronous. i.e. the reason we are unload and load the service to reload the config into the memory 
=> Reload the HAProxy and PG leader check configuration post deployment for the backend nodes

components/automate-cli/cmd/chef-automate/automateConstants.go, components/automate-cli/cmd/chef-automate/certRotate.go, components/automate-cli/cmd/chef-automate/certRotateFromTemplate.go, components/automate-cli/cmd/chef-automate/certRotateHelper.go, components/automate-cli/cmd/chef-automate/certRotate_test.go, components/automate-cli/cmd/chef-automate/cliUtils.go, components/automate-cli/cmd/chef-automate/ha_node_operations_utils.go, components/automate-cli/pkg/remotescripts/pgPostCertRotate.go
in cert rotate command earlier postgres was getting in an error state because ha proxy was not loading the updated configuration. To resolve this we are reloading ha proxy / pgleadercheck and reloading postgres also since we need to update certs in postgres
=> reload ha proxy restart postgres

components/automate-cli/cmd/chef-automate/ha_cert_show_test.go, components/automate-cli/cmd/chef-automate/start_linx.go, components/automate-cli/cmd/chef-automate/start_linx_test.go, components/automate-cli/pkg/remotescripts/pgPostCertRotate.go, lib/io/fileutils/fileutils.go
Start command restarts pg and reloads haproxy 
=> bug fixed restart script ha

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.ts
Expected: I should be able to click on each control of a node report to see the results.
Actual: I can only do this for the reports which are within the 24hrs time. For any report that is past 24hrs, I am getting the below error when I click on the + sign beside each control, it gives me the error below:
e.g. Could not get control details: Not found for id: de71b89f-5314-4460-a217-0b321f07b85c
@vinay033's PR https://github.com/chef/automate/pull/7946 rebased with latest changes in `main` branch. 
Added changes to fetch the past control details.
```
STEP 1
```
*Please add a note next to any …
=> CHEF-2498 Fix for viewing control details in reports older than past 24 hours

components/compliance-service/inspec-agent/remote/remote.go, components/nodemanager-service/pgdb/filtering.go
Code that constructs a quoted string literal containing user-provided data needs to ensure that this data does not itself contain a quote. Otherwise the embedded data could (accidentally or intentionally) terminate the string literal early and thereby change the structure of the overall string, with potentially severe consequences.
https://chefio.atlassian.net/browse/CHEF-12177
=> checking string before passing

components/automate-ui/src/app/modules/license/license-apply/license-apply.component.html, components/automate-ui/src/app/modules/license/license-apply/license-apply.component.scss, components/automate-ui/src/app/modules/license/license-lockout/license-lockout.component.html, components/automate-ui/src/app/modules/license/license-lockout/license-lockout.component.scss
License input screen updated to match UX mockup
Tested on local setup for success and failure scenarios. 
Check the updated screen by running local development environment using habitat.
=> CHEF-14374 Updated license input pop-up per UX mockup

components/automate-backend-deployment/README.md
=> manual bump

components/compliance-service/reporting/util/csv.go, components/compliance-service/reporting/util/csv_test.go, components/docs-chef-io/content/automate/ha.md
The CSV was not having controls where results array was not populated. Now, thw controls are added in cvs
https://progresssoftware.atlassian.net/browse/CHEF-9601
CSV and json have the same number of records now
1. Add some compliance data
2. Generate CSV and json both via UI
3. Match the records
CSV and json file generated after the fix
[2024-9-18 (1).csv](https://github.com/user-attachments/files/17055843/2024-9-18.1.csv)
[2024-9-18_new.json](https://github.com/user-attachments/files/17055844/2024-9-18_new.json)
Demo video after fix :- …
=> Adding the logic for control without results

.expeditor/build.habitat.yml
=> Checking pipeline

components/automate-backend-deployment/habitat/cert.sh, components/automate-backend-deployment/habitat/plan.sh, components/automate-cli/cmd/chef-automate/automateConfigUtils.go, components/automate-cli/cmd/chef-automate/automateConstants.go, components/automate-cli/cmd/chef-automate/automateHAAwsDeployment.go, components/automate-cli/cmd/chef-automate/automateHADeployExistingInfra.go, ng.toml, terraform/a2ha-terraform/modules/opensearch/main.tf, terraform/a2ha-terraform/modules/postgresql/main.tf
https://progresssoftware.atlassian.net/browse/CHEF-12487
packages for testing:
- vivek-shankar/automate-ha-deployment/0.1.0/20241016112616
- vivek-shankar/automate-cli/0.1.0/20241016114018
Demo: https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/EboMQAaIlhdMo2W5yTO_MyQBkWu4qcy7zbjVgfK4sSub3Q?e=iVYfBh
=> CHEF-12487 certs added to backend deployment and trimspace to prevent restart

components/docs-chef-io/content/automate/ha_aws_deployment_prerequisites.md, components/docs-chef-io/content/automate/ha_backup_restore_aws_efs.md, components/docs-chef-io/content/automate/ha_chef_backend_to_automate_ha.md, components/docs-chef-io/content/automate/ha_disaster_recovery_setup.md, components/docs-chef-io/content/automate/ha_existing_a2ha_to_automate_ha.md, components/docs-chef-io/content/automate/ha_inplace_migration.md, components/docs-chef-io/content/automate/ha_on_premises_deployment_prerequisites.md, components/docs-chef-io/content/automate/reusable/md/opensearch_health_check.md
=> doc improvements 01

components/docs-chef-io/content/automate/invalid_login_attempts.md
Obvious fix. Document change.
The current images in the following doc page  are huge and would help to reduce them in size.
* https://docs.chef.io/automate/invalid_login_attempts
=> docs: resizing huge images in Automate invalid login attempts doc

.expeditor/verify.pipeline.yml, components/automate-backend-ctl/habitat/bin/knife, components/automate-backend-ctl/habitat/plan.sh, components/automate-backend-deployment/habitat/plan.sh, components/automate-backend-opensearch/habitat/config/sidecar, components/automate-backend-opensearch/habitat/plan.sh, components/automate-cluster-ctl/habitat/plan.sh, components/automate-cluster-ctl/libexec/automate-cluster-ctl, components/automate-cs-nginx/habitat/plan.sh, components/automate-cs-oc-erchef/habitat/hooks/run, scripts/credentials, scripts/gather-logs, scripts/smoke-test
package upgrade ruby
https://progresssoftware.atlassian.net/browse/CHEF-17460
inspec is commented in cluster-ctl because its pulling vulnerability affected ruby version 3.1.2
Automate team has to fix below issues:
- inspec with the vulnerable ruby(core/ruby31/3.1.2/20240107080752) is present in compliance service (we need inspec new build)
- erchef pulling ruby core/ruby30/3.0.6/20240107080023 in automate-cs-oc-service
=> Ruby Upgrade to 3.1.0 from 3.0.0

components/automate-cli/cmd/chef-automate/upgrade.go, components/automate-deployment/pkg/majorupgradechecklist/checklist_manager.go, components/automate-deployment/pkg/majorupgradechecklist/post_checklist_manager.go, components/automate-deployment/pkg/majorupgradechecklist/upgrade_utils.go, components/automate-deployment/pkg/majorupgradechecklist/v3.go, components/automate-deployment/pkg/majorupgradechecklist/v5.go
[https://progresssoftware.atlassian.net/browse/CHEF-17285](url)
Embedded PG:
External PG:
=> add checklist for v5 for postgres

.studio/common, .studio/deployment-service, .studiorc, components/automate-opensearch/habitat/config/opensearch.yml, components/automate-opensearch/habitat/config/securityconfig/internal_users.yml, components/automate-opensearch/habitat/hooks/post-run, components/automate-opensearch/habitat/plan.sh, components/config-mgmt-service/integration_test/suite_test.go, components/es-sidecar-service/integration_test/purge_test.go, components/es-sidecar-service/integration_test/suite_test.go, components/ingest-service/integration_test/suite_test.go
Added anew version of  opensearch which is 2.18
https://progresssoftware.atlassian.net/browse/CHEF-17471
https://progresssoftware.atlassian.net/browse/CHEF-12446
Automate all services all working fine after the upgrade
rebuild component/automate-opensearch
https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/EQbO7SSHsLpHoNA7xL4elRIBJtWYC1wTJh8PnV4-n9M8_g?e=8hTqOZ
=> New version of opensearch in automate

components/automate-backend-deployment/README.md, components/docs-chef-io/content/automate/ha_cert_rotation.md, components/docs-chef-io/content/automate/ha_cert_selfsign.md, terraform/a2ha-terraform/modules/automate/files/config.toml.erb
Fixed the issue of server_name coming empty in both automate and chefserver configs after upgrade. 
server_name comes under the opensearch.ssl section
**Automate Config Before Fix**
**Chef Config Before Fix**
**Automate Config After Fix**
**Chef Config After Fix**
=> Corrected server_name field value which was coming empty after upgrade

components/automate-backend-postgresql/habitat/config/functions.sh
Pg log folder create if not present
=> HA create pg log folder if not present

components/docs-chef-io/content/automate/troubleshooting.md
https://progresssoftware.atlassian.net/browse/CHEF-5783
Added a section in automate troubleshooting, for knife search issue.
=> Doc change: Added troubleshooting section for knife search

components/docs-chef-io/content/automate/restore.md
https://progresssoftware.atlassian.net/browse/CHEF-17894
=> Restore Doc Troubleshoot section update

components/automate-backend-deployment/habitat/plan.sh, components/automate-cli/pkg/verifyserver/services/softwareversionservice/softwareversionservice.go, terraform/a2ha-terraform/modules/automate/templates/provision.sh.tpl, terraform/a2ha-terraform/modules/opensearch/templates/provision.sh.tpl, terraform/a2ha-terraform/modules/postgresql/templates/provision.sh.tpl, terraform/a2ha-terraform/reference_architectures/existing_nodes/main.tf
getenforce and setenforce checks added. also module dependency added for bootstrap automate
=> getenforce and setenforce checks added. also module dependency added for bootstrap automate

.studio/applications-service, components/applications-service/pkg/storage/postgres/schema/sql/19_service_full_id_seq.up.sql
adding migration script to alter the data type of a sequence 
https://progresssoftware.atlassian.net/browse/CHEF-19124
adding migration script to alter the data type of a sequence 
To build:
build components/application-service/
To test:
a) chef-automate dev psql postgres
b) \l 
c) \c chef_applications_service
d) \dt
e) \ds
f) \d service_full
g) \d service_full_id_seq
Latest current:
After adding migration script:
=> adding migration script to alter the data type

components/automate-cs-ocid/habitat/config/tasks/set_pg_secrets.rb, components/automate-cs-ocid/habitat/hooks/run
=> [CHEF-18932] Changes to stop exposing credentials through plain text in oc-id

.studio/chef-server-collection, components/automate-cs-ocid/habitat/hooks/run, components/automate-cs-ocid/habitat/plan.sh
Fixing bundler config syntax change in bundler > v2.1
Ruby 3.0.1 came with Bundler 2.1.x (likely Bundler 2.1.4 or similar) where Bundler introduced several new features and improvements, one of which was syntactical change in the bundle config command.
With upgrade to Ruby 3.0.1 in Infra-server (ocid) 15.8.0 bundler doesn’t recognise this older command and ignores the local configuration and creates the ./bundle at the root which is the default bundler behaviour as we need to run automate as a root user.
This creates conflict with global environment variables like GEM_PATH and GEM_HOME.
*Please add a note next …
=> [CHEF-10965] Fixing bundler config syntax change in bundler > v2.1

components/automate-backend-ctl/habitat/lib/automate/backend/automate_config.rb, components/automate-backend-deployment/README.md, components/automate-cli/cmd/chef-automate/automateHAAwsDeployment.go, components/automate-cli/cmd/chef-automate/automateHADeployExistingInfra.go, components/automate-cli/cmd/chef-automate/decode_password.go, components/automate-cli/cmd/chef-automate/decode_password_test.go, components/automate-cli/cmd/chef-automate/encode_password.go, components/automate-cli/cmd/chef-automate/encode_password_test.go, components/automate-cli/cmd/chef-automate/pullAndGenerateConfig.go, components/automate-cli/pkg/testfiles/onprem/config_externaldb.toml, terraform/a2ha-terraform/modules/automate/files/config.toml.erb, terraform/a2ha-terraform/modules/automate/templates/provision.sh.tpl
Recording is attached in https://progresssoftware.atlassian.net/browse/CHEF-17454
=> Add code to encode,decode opensearch and postgres passwords

components/ingest-service/backend/client.go, components/ingest-service/backend/elastic/elastic.go, components/ingest-service/server/chef.go, components/ingest-service/storage/db.go, components/ingest-service/storage/db_test.go
Adding Generic Method to start the reindex process for given indexes
https://progresssoftware.atlassian.net/browse/CHEF-19083
Generic Method to start the reindex process for given indexes
Build ingest service
Build deployment service
Build cli
Run chef-automate reindex start
=> Generic Method to start the reindex process for given indexes

components/automate-cli/cmd/chef-automate/backup.go
Fixing restore issue as migration is skipped.
https://progresssoftware.atlassian.net/browse/CHEF-20217
[RestoreFailureAsMigrationIsSkipped.docx](https://github.com/user-attachments/files/19484912/RestoreFailureAsMigrationIsSkipped.docx)
=> [CHEF-20217] Fixing restore error as migration is skipped

components/ingest-service/server/chef.go, components/ingest-service/storage/db.go, components/ingest-service/storage/db_test.go
Monitor the task created for reindex from opensearch
https://progresssoftware.atlassian.net/browse/CHEF-19084
Monitor the task created for reindex from opensearch
=> Monitor the task created for reindex from opensearch

components/automate-cli/cmd/chef-automate/automateConstants.go, components/automate-cli/cmd/chef-automate/certRotate.go, components/automate-cli/cmd/chef-automate/certRotate_test.go, components/automate-cli/cmd/chef-automate/status.go, components/automate-cli/cmd/chef-automate/summary.go, components/automate-cli/cmd/chef-automate/verify.go, components/automate-cli/cmd/chef-automate/verify_test.go, components/automate-cli/cmd/chef-automate/version.go, components/automate-cli/cmd/chef-automate/version_test.go, lib/sshutils/mocksshutils.go, lib/sshutils/sshutils.go
Issues fixed:
- remove `cert-rotate` old cmd
- fix home path in verify. Automatically determines `$HOME `env, fallback to `/home/ssh-user` if `$HOME` not found or incorrect
- added maintenance mode status in `status summary` command
- Added airgap version for OS and PG in `chef-automate version` command
Showing that custom home directory is supported now
If version in backend is not latest or upgrade did not happen:
If version of backend services match up with the deployed version:
Maintenance mode in status summary command:
=> Remove cert-rotate old cmd and fix home path in verify and other issues

components/automate-ui/src/app/shared/utils/regex-utils.ts
FIx for Chef Tag is accepting html text, url, all special characters 
https://progresssoftware.atlassian.net/browse/CHEF-20911
Added validation to prevent invalid characters and links.
applicable
=> CHEF-20911 Fix to prevent invalid tags and characters for tags - updated

components/docs-chef-io/data/automate/cli_chef_automate/commands/chef-automate.yaml, components/docs-chef-io/data/automate/cli_chef_automate/commands/chef-automate_notice.yaml
=> update cli doc
