components/automate-cli/cmd/chef-automate/config.go
We are adding this prompt as patch command will deploy and upgrade bundles.if they are available in transfer file .So we are adding this prompt to intimate users
=> Adding prompt for patch command

components/compliance-service/ingest/ingestic/mappings/mappings.go, components/compliance-service/ingest/pipeline/publisher/compliance.go, components/ingest-service/backend/elastic/mappings/mappings.go, components/ingest-service/pipeline/chef_run.go
Found API failures while sending compliance data to Segment.
=> Reverting index creation

.expeditor/verify_private.pipeline.yml, integration/run_test, integration/services/common.sh, integration/tests/ha_chef_server.sh
The `ha chef server` and `ha cluster` pipelines were failing with docker runs.
- The verify private pipeline should pass
=> Fix verify private pipelines

.expeditor/buildkite/inspec.sh, terraform/test-environments/modules/chef_automate_install/main.tf
Automate deployment pipeline was failing.
The deployment pipeline should pass successfully.
=> Fix Automate deployment

components/automate-elasticsearch/habitat/plan.sh, components/automate-openjdk/habitat/plan.sh
=> Fixing pipeline issues

api/config/shared/global.go, api/config/ui/config_request.go
=> Fix BuildKite - [codegen] A2 protobufs

components/automate-ui/src/app/entities/servers/server.actions.ts, components/automate-ui/src/app/entities/servers/server.effects.ts, components/automate-ui/src/app/entities/servers/server.model.ts, components/automate-ui/src/app/entities/servers/server.requests.ts, components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.html, components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/update-web-uikey-slider/update-web-uikey-slider.component.html, components/automate-ui/src/app/modules/infra-proxy/update-web-uikey-slider/update-web-uikey-slider.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/update-web-uikey-slider/update-web-uikey-slider.component.ts, e2e/cypress/integration/ui/infra-proxy/chef-server-details.spec.ts
As an Automate User, I want to do update WebUI key in Automate UI.
https://github.com/chef/automate/issues/6277
I have added UI changes and API integration to update the webui key
```
STEP 1
STEP 2
--> need to add server first
--> open the server details page 
--> in meta box we have text `update`, using this we can update the WebUI key
``` …
=> Server details page  - UI should have the option to update the WebUI key

components/authz-service/storage/postgres/migration/sql/78_update_viewer_role_pols.up.sql, e2e/cypress/integration/api/iam/infra_viewer_actions.spec.ts
restart hab
Run below commands in hab
```
start_chef_server
infra_service_load_chef_repo
converge_policyfile_chef_client
compile_go_protobuf_component api
```
cd automate/e2e
npm install
Check for infra_viewer_actions.spec.ts if all test cases are passing
=> infra_viewer_actions added

.bldr.toml, HABITAT_PACKAGES, components/automate-deployment/pkg/services/internal/generated/gen.go, components/automate-netcat/habitat/plan.sh, products.meta
Adding automate-netcat components,as we want this package in airgap bundle to be there for offline installation while running validation script. 
=> automate netcat component

components/automate-backend-deployment/README.md
Just rebuild the pkg. 
No code change
=> rebuild the pkg automate-ha-deployment

components/automate-backend-deployment/README.md, components/automate-cluster-ctl/readme
Bump the automate-cluster-clt and automate-backend-deployment version together.
=> build the pkgs

components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.scss
Add common alignment while hover the dropdown items.
#6464
Added common alignment while hover the dropdown items.
inside hab,
create the config.toml file in /automate …
=> Dropdown items should have common alignment while hover the items

components/automate-backend-elasticsearch/habitat/cert.sh, components/automate-backend-postgresql/habitat/cert.sh, components/automate-backend-postgresql/habitat/plan.sh
Increase the validity of postgresql and elasticsearch certificates
=> Increasing validity for  pg certs

components/automate-cli/cmd/chef-automate/license.go, components/automate-cli/pkg/reportgenerator/usagegenerator.go
Signed-off-by: MadhviA <matroliy@progress.com>
This PR adds a new cli option under license.
The usages are:
- Get all the unique node counts running **Chef Compliance Scan** and reporting to Automate over a period of days
- Get all the Infra Client node reports generated by **Chef Compliance Scan** and reporting to Automate over a period of days
https://github.com/chef/automate/issues/6375
- The cli outcome should have the location of the generated CSV
- The CSV should give the details of the runs and nodes
```
chef_load_compliance_nodes 50 // Load 50 nodes
chef-automate license complianceUniqNodeRunReport -s 2021-12-21 -e 2021-12-24
chef-automate license complianceNodeRunReport -s 2021-12-21 -e 2021-12-24
```
**All PRs** …
=> Compliance command v1

components/automate-backend-ctl/README.md, components/automate-cluster-ctl/habitat/README.md, terraform/a2ha-terraform/modules/aws/main.tf
Add route_table creation in instance depends on. In case of route table is not created before the ec2 in that case there might be error occured. So need to fix it
=> fix: route table issue

components/automate-backend-deployment/habitat/plan.sh, components/automate-cluster-ctl/habitat/README.md
Fixed airgap bundle installation issue that was coming during the deployment with --airgap-bundle falg
=> fix: airgap bundle issue

components/automate-cli/cmd/chef-automate/license.go, components/automate-cli/pkg/reportgenerator/usagegenerator.go
Signed-off-by: MadhviA <matroliy@progress.com>
This PR adds a new cli option under license.
The usages are:
- Get all the unique resource counts running **Chef Compliance Scan** and reporting to Automate over a period of days
- Get all the Infra Client resource reports generated by **Chef Compliance Scan** and reporting to Automate over a period of days
https://github.com/chef/automate/issues/6375
- The cli outcome should have the location of the generated CSV
- The CSV should give the details of the runs and nodes
```
chef_load_compliance_nodes 50 // Load 50 nodes
chef-automate license complianceResourceRunCount -s 2022-01-04 -e 2022-01-12
chef-automate license complianceResourceRunReport -s 2022-01-04 -e 2022-01-12
``` …
=> Compliance command v2

components/automate-ui/src/app/modules/infra-proxy/client-details/client-details.component.html, components/automate-ui/src/app/modules/infra-proxy/clients/clients.component.html, components/automate-ui/src/app/modules/infra-proxy/create-client-modal/create-client-modal.component.html, components/automate-ui/src/app/modules/infra-proxy/reset-client-key/reset-client-key.component.html, e2e/cypress/integration/api/iam/infra_server_actions_integration.spec.ts, e2e/cypress/integration/ui/infra-proxy/infra-clients.spec.js
Need to add Infra-proxy client cypress should use the WebUI key
https://github.com/chef/automate/issues/4911
Added Infra-proxy client cypress should use the WebUI key
Please follow this link to run on your local environment.
=> Infra proxy client cypress tests

components/docs-chef-io/netlify.toml
Signed-off-by: Ian Maddaus <ian.maddaus@progress.com>
=> Bump hugo version to 0.91.2

components/automate-cli/cmd/chef-automate/automateClusterCtlUtil.go, components/automate-cli/cmd/chef-automate/upgrade.go, scripts/bundle_creation.sh
update the Desc : Fix for following issue
1. Logs are not tailing while upgrade.
2. For frontend flag we should not generate a2ha_manifest_auto_tf.vars 
(any way this is not a side effect, in current code we are generating ).
3. In current code with air-gap flag, bundle are downloading twice.
build components/automate-cli
hab pkg install results/<pkg_name>
chef-automate upgrade run --upgrade-frontends --airgap-bundle <path to airgap bundle>
chef-automate upgrade run --upgrade-frontends
=> fixing upgrade command 

components/docs-chef-io/content/automate/data_lifecycle.md
-s can obscure failures in the curl run.
-k should be used to avoid ssl verify for internal commands
Signed-off-by: Sean Horn <horn@progress.com>
N/A
Docs changes only
=> Do not obscure problems in response, ignore SSL

components/docs-chef-io/content/automate/saml.md
Automate currently only works with SP-initiated SAML logins and no other mode of SAML authentication.
Follow https://chef-software.ideas.aha.io/ideas/AUTO-I-59 for further updates
Signed-off-by: Sean Horn <horn@progress.com>
Update on SAML login accepted config
=> sp-initiated only SAML logins

components/docs-chef-io/config.toml, components/docs-chef-io/data/automate/api-static/00-meta.swagger.json, components/docs-chef-io/static/automate-api-docs/all-apis.swagger.json
Signed-off-by: Ian Maddaus <ian.maddaus@progress.com>
Replace master with main in the docs.
=> Change master to main in docs

components/docs-chef-io/archetypes/default.md, components/docs-chef-io/content/automate/desktop.md, components/docs-chef-io/content/automate/postgresql.md, components/docs-chef-io/content/automate/upgrade.md
=> Broken Links Updated

components/automate-gateway/gateway/middleware/auth_interceptor.go
As an Automate admin, I should be able to see all the actions done by any user on the chef server using infra proxy api.
https://github.com/chef/automate/issues/6284
I have added changes to audit the log for infra proxy API
example:
```
time="2022-01-25T15:53:20Z" level=info msg="Infra proxy server API logs" API info::="infra:infraServersOrgs:list" API params::="server_id:\"vinay\"" GrpcMethod::=GetOrgs Service::=chef.automate.api.infra_proxy.InfraProxy Time::="2022-01-25T15:53:20Z" User::="[team:local:admins user:local:admin]"
```
To check the logs you need to run `sl` command on a hab and check the infra proxy API to audit the log. 
All PRs **from Progress employees** should …
=> Changes to audit the log for infra proxy

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.ts, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.scss
Fix unit test errors in LCR pipeline.
Unit test errors are fixed in pipeline.
=> Fix unit test errors in LCR pipeline

e2e/cypress/integration/ui/compliance/large_compliance_report/large_compliance_report.spec.ts
Fix cypress lint errors in LCR pipeline.
Cypress lint errors are fixed in pipeline.
=> Fix cypress lint errors

components/infra-proxy-service/migrations/pipeline/phasetwomigration.go
Create a Demo pipeline for phase two.
Phase 2 pipeline added 
https://chefio.atlassian.net/jira/software/c/projects/STALWART/boards/361?modal=detail&selectedIssue=STALWART-29
Gat a demo pipeline ready which communicates using channels.
rebuild components/infra-proxy-service/
Testing will be done integrating with API.
=> Phase 2 migration pipeline

components/infra-proxy-service/migrations/pipeline/utility.go, components/infra-proxy-service/migrations/pipeline/utility_test.go
When a organisation is migrated from the chef server to automate, an IAM project needs to be linked with it. 
So added the call to project create service to create the project with the name of serverId_orgID, every time the organisation is stored in the database the project is created with the name having all the policies as editors, viewer, owner.
https://chefio.atlassian.net/jira/software/c/projects/STALWART/boards/361?modal=detail&selectedIssue=STALWART-39
Project is created and stored in database at the time of insertion of orgs
```
```
*Please add a …
=> Add projects for every org to be inserted in the database

components/automate-cli/cmd/chef-automate/upgrade.go, components/automate-deployment/pkg/converge/compiler.go, components/automate-deployment/pkg/server/server.go, components/automate-deployment/pkg/server/upgrade_status.go
=> fixing buildkite

components/report-manager-service/objstore/objstore.go, components/report-manager-service/server/server_test.go, components/report-manager-service/worker/worker.go, components/report-manager-service/worker/worker_test.go
Signed-off-by: Sahiba Goyal <sgoyal@progress.com>
=> Auto Delete after one Day

components/automate-deployment/pkg/majorupgradechecklist/v3.go
For upgrading automate from milestone version to Pg version, we need to show the pre and post checklist to the user with all steps and actions that the user must check or perform. This Pr contains changes that will show the pre and post checklist to the user on running the `chef-automate upgrade run --major` command. The checklists are different for external PG and embedded PG
- https://chefio.atlassian.net/browse/SHIELD-13?atlOrigin=eyJpIjoiNDhiYTFjNTk5ODA0NGZlMDllYzJmZDk1NTI4M2FkNjIiLCJwIjoiaiJ9
- https://chefio.atlassian.net/browse/SHIELD-14?atlOrigin=eyJpIjoiYzQ2OTEzOWRhZjdlNGRjYWJmMzE1MDYzYzg0ZTY3MjAiLCJwIjoiaiJ9
`rebuild components/automate-deployment`
`rebuild componets/automate-cli` …
=> Pre and post checklist for embedded and external PG

components/automate-deployment/pkg/server/server.go, components/automate-ui/src/app/ui.component.ts
=> Temp pipeline testing

components/automate-ui/src/app/modules/infra-proxy/create-infra-role-modal/create-infra-role-modal.component.ts, components/automate-ui/src/app/modules/infra-proxy/edit-infra-role-modal/edit-infra-role-modal.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/edit-infra-role-modal/edit-infra-role-modal.component.ts, components/automate-ui/src/app/modules/infra-proxy/infra-roles/infra-roles.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/infra-roles/infra-roles.component.ts
Track the Infra-server roles actions using telemetry track event. The following actions should be tracked:-  search, create, delete and edit roles.
https://chefio.atlassian.net/browse/KINETICS-23
Infra-server roles actions are tracked using telemetry track event.
STEP 2
Go To Infrastructure -> Chef Servers -> Click on any Chef Infra Server -> Click on Orgs name -> select Roles tab -> you can search, create, edit and delete roles -> For each …
=> Telemetry coverage for InfraServer Roles Tab

components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/chef-servers-list/chef-servers-list.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/chef-servers-list/chef-servers-list.component.ts
Track the popup actions of Add Chef Infra Server and Add Chef Org using telemetry track event.
https://chefio.atlassian.net/browse/KINETICS-24
Both popup actions are tracked using telemetry track event.
STEP 2
Steps for preview screen:- (Add Chef Infra Server button)
Go To Infrastructure -> Chef Servers ->  click Add Chef Infra Server button -> you can see the popup then create infraserver -> For create actions, you can observe the telemetry track event in Network …
=> Telemetry coverage for Add Chef Infra Server and Add Chef Org button

components/docs-chef-io/content/automate/ha_healthcheck.md
Signed-off-by: Deepa Kumaraswamy <dkumaras@progress.com>
=> health check commands

components/docs-chef-io/content/automate/ha_security_firewall.md
Signed-off-by: Deepa Kumaraswamy <dkumaras@progress.com>
=> sec n firwall settings

components/infra-proxy-service/migrations/migrations.go, components/infra-proxy-service/migrations/pipeline/phaseonemigration.go, components/infra-proxy-service/migrations/pipeline/phasetwomigration.go, components/infra-proxy-service/migrations/pipeline/utility.go, components/infra-proxy-service/migrations/server.go, components/infra-proxy-service/storage/postgres/migration/sql/06_user_management.up.sql
The following fields are added considering users storage in the DB.
- First name
- Last name
- Email
- Middle Name
- Display name
https://chefio.atlassian.net/jira/software/c/projects/STALWART/boards/361?modal=detail&selectedIssue=STALWART-55
Run the following commands and check the database
$ hab studio enter
$ start_all_services
=> Modify the existing users table with more entries

components/automate-ui/src/app/modules/infra-proxy/create-environment-modal/create-environment-modal.component.ts, components/automate-ui/src/app/modules/infra-proxy/edit-environment-attribute-modal/edit-environment-attribute-modal.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/edit-environment-attribute-modal/edit-environment-attribute-modal.component.ts, components/automate-ui/src/app/modules/infra-proxy/environments/environments.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/environments/environments.component.ts
Track the Infra-server environment actions using telemetry track event. The following actions should be tracked:- search, create, delete and edit environments.
https://chefio.atlassian.net/browse/KINETICS-25
Infra-server environments actions are tracked using telemetry track event.
STEP 2
Go To Infrastructure -> Chef Servers -> Click on any Chef Infra Server -> Click on Orgs name -> select Environments tab -> you can search, create, edit and …
=> Telemetry coverage for Chef Infra Server Environment tab

components/automate-ui/src/app/modules/infra-proxy/clients/clients.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/clients/clients.component.ts, components/automate-ui/src/app/modules/infra-proxy/create-client-modal/create-client-modal.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/create-client-modal/create-client-modal.component.ts, components/automate-ui/src/app/modules/infra-proxy/reset-client-key/reset-client-key.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/reset-client-key/reset-client-key.component.ts
Track the Infra-server clients actions using telemetry track event. The following actions should be tracked:- search, create, delete and edit clients.
https://chefio.atlassian.net/browse/KINETICS-26
Infra-server clients actions are tracked using telemetry track event.
STEP 2
Go To Infrastructure -> Chef Servers -> Click on any Chef Infra Server -> Click on Orgs name -> select Clients tab -> you can search, create, edit and delete clients -> …
=> Telemetry coverage for Chef Infra Server Clients tab

components/docs-chef-io/content/automate/ha.md, components/docs-chef-io/content/automate/ha_destroy.md, components/docs-chef-io/content/automate/ha_healthcheck.md, components/docs-chef-io/content/automate/ha_security_firewall.md, components/docs-chef-io/content/automate/ha_upgrade.md, components/docs-chef-io/content/automate/ha_validation.md
Signed-off-by: kagarmoe <kimberly.garmoe@progress.com>
These pages should not be published!
=> Set pages to drafts

components/automate-ui/src/app/modules/infra-proxy/edit-infra-node-attribute-modal/edit-infra-node-attribute-modal.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/edit-infra-node-attribute-modal/edit-infra-node-attribute-modal.component.ts, components/automate-ui/src/app/modules/infra-proxy/edit-infra-node-modal/edit-infra-node-modal.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/edit-infra-node-modal/edit-infra-node-modal.component.ts, components/automate-ui/src/app/modules/infra-proxy/infra-node-details/infra-node-details.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/infra-node-details/infra-node-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/infra-nodes/infra-nodes.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/infra-nodes/infra-nodes.component.ts, components/automate-ui/src/app/modules/infra-proxy/reset-node-key/reset-node-key.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/reset-node-key/reset-node-key.component.ts, components/automate-ui/src/app/modules/infra-proxy/update-node-tag-modal/update-node-tag-modal.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/update-node-tag-modal/update-node-tag-modal.component.ts
Track the Infra-server nodes actions using telemetry track event. The following actions should be tracked:- search,  delete and edit nodes.
https://chefio.atlassian.net/browse/KINETICS-32
Infra-server nodes actions are tracked using telemetry track event.
STEP 2
Go To Infrastructure -> Chef Servers -> Click on any Chef Infra Server -> Click on Orgs name -> select Nodes tab -> you can search, edit and delete nodes -> For each actions, you can …
=> Telemetry coverage for Chef Infra Server Nodes tab

components/automate-ui/src/app/entities/orgs/org.actions.ts, components/automate-ui/src/app/entities/orgs/org.effects.ts, components/automate-ui/src/app/entities/orgs/org.reducer.ts, components/automate-ui/src/app/entities/orgs/org.requests.ts, components/automate-ui/src/app/entities/orgs/org.selectors.ts, components/automate-ui/src/app/modules/infra-proxy/migration-slider/migration-slider.component.html, components/automate-ui/src/app/modules/infra-proxy/migration-slider/migration-slider.component.ts, e2e/cypress/integration/api/iam/infra_server_actions_integration.spec.ts
Signed-off-by: chaitali-mane [cmane@progress.com](mailto:cmane@progress.com)
As an Automate User, I want to preview user that are to be migrated.
1. Show user data in the preview screen modal.
2. Check new username is available in database or not, implementaion of API integration with UI.
https://chefio.atlassian.net/browse/STALWART-41
Added screen for preview user that are to be migrated.
1. Show user data in the preview screen modal.
2. Check new username is available in the database or not, implementation of API integration with UI.
```
STEP 2
and run the …
```
=> Conflicting user changes in Infra proxy

components/infra-proxy-service/migrations/pipeline/phaseonemigration.go, components/infra-proxy-service/migrations/pipeline/phasetwomigration.go, components/infra-proxy-service/migrations/pipeline/utility.go, components/infra-proxy-service/migrations/pipeline/utility_test.go, components/infra-proxy-service/pipeline/models.go, components/infra-proxy-service/storage/postgres/automate_infra_server_users.go, components/infra-proxy-service/storage/postgres/migration/sql/06_user_management.up.sql, components/infra-proxy-service/storage/storage.go, components/infra-proxy-service/storage/testDB/testDB.go
Added pipeline function to populate the org users association in db based on the actions.
https://chefio.atlassian.net/browse/STALWART-43
I have added pipeline function to populate the org users association in db based on the actions as insert, update or delete.
```
```
=> Pipeline function to populate org users association

components/infra-proxy-service/migrations/pipeline/phaseonemigration.go, components/infra-proxy-service/migrations/pipeline/phasetwomigration.go, components/infra-proxy-service/migrations/pipeline/utility.go, components/infra-proxy-service/migrations/pipeline/utility_test.go, components/infra-proxy-service/pipeline/models.go, components/infra-proxy-service/pipeline/utils.go, components/infra-proxy-service/server/automate_infra_server_users.go, components/infra-proxy-service/storage/postgres/automate_infra_server_users.go, components/infra-proxy-service/storage/storage.go, components/infra-proxy-service/storage/testDB/testDB.go
Populate users information in the Automate DB
- Insert User
- Update User
- Delete User
Insert, Update and Delete should work error free and must be tested.
rebuild components/infra-proxy-service/
then upload a file and confirm migration
=> Store Users

components/automate-ui/src/app/page-components/warning-banner/warning-banner.component.spec.ts
Code to fix automate-ui unit pipeline issue.
https://buildkite.com/chef-oss/chef-automate-main-verify/builds/19650
=> Fix automate UI pipeline issue

.expeditor/license_scout.sh, .expeditor/verify.pipeline.yml, components/notifications-service/habitat/plan.sh, components/notifications-service/server/mix.lock
=> License scout fix

components/automate-ui/src/app/entities/orgs/org.actions.ts, components/automate-ui/src/app/entities/orgs/org.effects.ts, components/automate-ui/src/app/entities/orgs/org.model.ts, components/automate-ui/src/app/entities/orgs/org.requests.ts, components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/migration-slider/migration-slider.component.html, components/automate-ui/src/app/modules/infra-proxy/migration-slider/migration-slider.component.ts
As an Automate admin, I want to migrate only some selected users based on the local user name I entered in case of conflicts.
https://chefio.atlassian.net/browse/STALWART-74
- Admin can select the multiple users using the checkbox
- Admin can select all users using the single checkbox
- Admin can change the username of the user in case of conflicts 
- Admin can click the on confirm preview button and send the API call with selected users data.
```STEP 1
STEP 2
```
Go To Infrastructure -> Chef …
=> Confirm preview button should send the changed and selected user details from UI.

components/automate-ui/src/app/modules/infra-proxy/cookbook-dependencies-details/cookbook-dependencies-details.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/cookbook-dependencies-details/cookbook-dependencies-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/cookbook-dependencies/cookbook-dependencies.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/cookbook-dependencies/cookbook-dependencies.component.ts, components/automate-ui/src/app/modules/infra-proxy/policy-groups/policy-groups.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/policy-groups/policy-groups.component.ts, components/automate-ui/src/app/modules/infra-proxy/revision-id/revision-id.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/revision-id/revision-id.component.ts
Track the Infra-server policy-groups actions using telemetry track event. 
https://chefio.atlassian.net/browse/KINETICS-35
Infra-server policy-groups actions are tracked using telemetry track event.
STEP 2
Go To Infrastructure -> Chef Servers -> Click on any Chef Infra Server -> Click on Orgs name -> select Policy Groups tab -> you can search, view policy-groups -> For each actions, you can observe the telemetry track event in …
=> Telemetry coverage for Chef Infra Server Policy Groups tab

components/automate-ui/src/app/modules/infra-proxy/policy-files/policy-files.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/policy-files/policy-files.component.ts
Track the Infra-server policy-files actions using telemetry track event.
https://chefio.atlassian.net/browse/KINETICS-34
Infra-server policy-files actions are tracked using telemetry track event.
STEP 2
Go To Infrastructure -> Chef Servers -> Click on any Chef Infra Server -> Click on Orgs name -> select Policy Files tab -> you can search, delete, view policy-files -> For each actions, you can observe the telemetry track event in …
=> Telemetry coverage for Chef Infra Server Policy Files tab

components/automate-deployment/pkg/airgap/install_bundle_test.go, components/automate-deployment/pkg/manifest/a2.go, components/automate-deployment/pkg/manifest/client/http.go, components/automate-deployment/pkg/manifest/parser/parser.go
run below commands from hab studio
rebuild components/automate-deployment
=> Fixing local automate setup

components/automate-cli/cmd/chef-automate/upgrade.go, components/automate-deployment/pkg/majorupgradechecklist/checklist_manager.go, components/automate-deployment/pkg/majorupgradechecklist/post_checklist_manager.go, components/automate-deployment/pkg/majorupgradechecklist/post_checklist_manager_test.go, components/automate-deployment/pkg/majorupgradechecklist/v3.go, components/automate-deployment/pkg/manifest/client/http.go, components/automate-deployment/pkg/manifest/provider.go, components/automate-deployment/pkg/server/server.go, integration/base.sh, integration/tests/upgrade.sh
=> cli milestone part-2

STATIC_ANALYSIS.md, scripts/get_secrets.sh, terraform/test-environments/modules/chef_automate_install/main.tf
=> fixing vault access

dev-docs/automate_license_usage.md, dev-docs/infra-server-testing.md
Tested the upload file API with different size of files
https://chefio.atlassian.net/browse/STALWART-71
I have tested the upload file API with different size of files as 10MB, 512MB, 1GB, 1.5GB & 2GB
and added the response time.
Some of the testing observations are
- The upload takes only one zip file at a time
- The upload allows only zip files
- The maximum size of zip file we can use is 1.5GB
```
rebuild components/infra-proxy-service/
```
Steps to test:
1. Ensure Chef Infra Server is running. If it is not start it with ```start_chef_server```
2. Add the chef-server test environment credentials and extract the SERVER IDs
Request
```curl --location --request POST 'https://a2-dev.test/api/v0/infra/servers/migrations/upload' \--header …
```
=> Testing observations of zip file upload

components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.html
Signed-off-by: Chaitali Mane <cmane@progress.com>
Users should not be allowed to add/connect organizations from Chef Automate UI.
https://chefio.atlassian.net/browse/STALWART-79
Users are allowed to add/connect organizations from Chef Automate UI.
```
STEP 2
```
On the chef-server details page, Button is not visible to users.
*Please add a note …
=> Disable add chef org button

ec2/README.md
Updated ec2 README file to use saml2aws instead of okta_aws to access to Chef's AWS accounts.
=> Updated EC2 README with saml2aws support.

components/automate-ui/src/app/page-components/profile/profile.component.ts, components/automate-ui/src/app/pages/signin/signin.component.ts, components/automate-ui/src/app/ui.component.ts
Show static Banner UI
Show static Banner UI
=> Show static Banner UI - automate-ui

components/automate-workflow-server/habitat/plan.sh
Build pipeline was failing for workflow server because of git protocol being used for dependency in rebar. We have overridden that to use HTTPS instead of GIT
=> fix workflow build pipeline

components/docs-chef-io/Makefile
Signed-off-by: Ian Maddaus <ian.maddaus@progress.com>
Updates the docs makefile to handle changes made to chef-web-docs.
=> Update docs makefile

.expeditor/config.yml
Signed-off-by: Michael Maslanka <maslanka@progress.com>
=> Fix version constraint on release branch

README.md
Signed-off-by: Michael Maslanka <maslanka@progress.com>
=> Dummy Change"

.expeditor/config.yml
Signed-off-by: Michael Maslanka <maslanka@progress.com>
=> remove ignore_labels

.expeditor/create-manifest.rb, .expeditor/promote-hab-pkgs-and-cli.sh, integration/base.sh, integration/tests/upgrade_acceptance_master.sh, integration/tests/upgrade_current_acceptance.sh, integration/tests/upgrade_current_master.sh, integration/tests/upgrade_current_master_habdev.sh, scripts/verify_build.sh
Fixing the build pipelines along with some upgrade pipelines
=> fixing pipeline for build in semver changes

.expeditor/create-manifest.rb, .expeditor/promote-hab-pkgs-and-cli.sh, components/applications-load-gen/habitat/plan.sh
=> Update to use version/schema 2 in manifests

.expeditor/create-manifest.rb, components/applications-load-gen/habitat/plan.sh
=> Fix create-manifest

components/automate-postgresql/habitat/plan.sh
Dummy change to trigger post promote pipeline
=> dummy change

terraform/a2ha-terraform/modules/automate/templates/provision.sh.tpl, terraform/test-environments/modules/chef_automate_install/templates/install_chef_automate_cli.sh.tpl
=> fix terraform error

components/automate-cli/cmd/chef-automate/migration_pg.go
=> pipeline fix initdb script

components/automate-cli/cmd/chef-automate/migration_pg.go
=> changed sh to bash in migrate cmd

components/automate-postgresql/habitat/plan.sh, components/automate-ui/src/app/ui.component.ts, terraform/test-environments/modules/chef_automate_install/templates/install_chef_automate_cli.sh.tpl
=> revert terraform changes

components/automate-cli/cmd/chef-automate/migration_pg.go, components/automate-deployment/habitat/plan.sh, terraform/test-environments/modules/chef_automate_install/templates/install_chef_automate_cli.sh.tpl
=> Major upgrade for inplace auto upgrade

components/automate-cli/cmd/chef-automate/migration_pg.go, components/automate-deployment/habitat/plan.sh, components/automate-deployment/pkg/majorupgradechecklist/post_checklist_manager_test.go, components/automate-platform-tools/habitat/plan.sh
=> verify_pipeline_fix (automate cli and deployment)

components/automate-deployment/pkg/server/upgrade_status.go, components/automate-deployment/pkg/server/upgrade_status_test.go
=> omit services to be displayed from status command

.expeditor/publish-release-notes.sh, .expeditor/push-git-tag.sh
=> modified git tag for release

components/automate-deployment/habitat/plan.sh
=> touch deployment service

components/docs-chef-io/content/automate/major_upgrade.md
=> Minor Changes to the Major Upgrade 3.x

components/automate-ui/src/app/modules/desktop/desktop-detail/desktop-detail.component.html, components/automate-ui/src/app/modules/desktop/desktop-detail/desktop-detail.component.ts
Signed-off-by: rishichawda <rishichawda@users.noreply.github.com>
While investigating an unrelated issue, I found a piece of code that raised alarms since it was modifying objects from the  rather than returning a new one. As a best practice, we avoid mutating objects in javascript. Along with that, the getter was being used inside a directive which means it is called indefinitely. I've fixed these two issues by 
- using [trackByFunction](https://angular.io/api/core/TrackByFunction) to avoid multiple (basically infinite) render cycles. 
- return a new history object instead of modifying the original in bucket array. (I'm not sure if this was being intentionally done and there's no comment either so I'm assuming it wasn't)
With occasional exceptions, all PRs …
=> fix infinite render loop in checkin history component

components/automate-ui/src/app/components/pending-edits-bar/pending-edits-bar.component.spec.ts, components/automate-ui/src/app/components/pending-edits-bar/pending-edits-bar.component.ts, components/automate-ui/src/app/modules/policy/add-members/policy-add-members.component.ts, components/automate-ui/src/app/modules/policy/add-members/policy-add-members.spec.ts, components/automate-ui/src/app/modules/policy/details/policy-details.component.ts, components/automate-ui/src/app/modules/policy/list/policy-list.component.spec.ts, components/automate-ui/src/app/modules/policy/list/policy-list.component.ts, components/automate-ui/src/app/modules/roles/list/roles-list.component.spec.ts, components/automate-ui/src/app/modules/roles/list/roles-list.component.ts, components/automate-ui/src/app/pages/project/details/project-details.component.spec.ts, components/automate-ui/src/app/pages/project/details/project-details.component.ts, components/automate-ui/src/app/pages/project/list/project-list.component.spec.ts, components/automate-ui/src/app/pages/project/list/project-list.component.ts, components/automate-ui/src/app/pages/project/rules/project-rules.component.spec.ts, components/automate-ui/src/app/pages/project/rules/project-rules.component.ts
Signed-off-by: venkatesh-r-r <Venkatesh.Rengasamy@progress.com>
Telemetry coverage for access management under Settings tab in Automate-ui.
https://chefio.atlassian.net/browse/KINETICS-76
Actions in access management pages are tracked using telemetry track event.
STEP 2
Go To Settings -> You can see Access Management section -> Click on Policies or Roles or Projects -> you can search, create, edit & delete policies, roles and projects -> For each actions, you can observe the telemetry track event in …
=> Telemetry Coverage for Access Management in Automate-ui

components/automate-ui/src/app/modules/team/team-details/team-details.component.spec.ts, components/automate-ui/src/app/modules/team/team-details/team-details.component.ts, components/automate-ui/src/app/modules/team/team-management/team-management.component.spec.ts, components/automate-ui/src/app/modules/team/team-management/team-management.component.ts, components/automate-ui/src/app/modules/token/token-details/api-token-details.component.spec.ts, components/automate-ui/src/app/modules/token/token-details/api-token-details.component.ts, components/automate-ui/src/app/modules/token/token-list/api-token-list.component.spec.ts, components/automate-ui/src/app/modules/token/token-list/api-token-list.component.ts, components/automate-ui/src/app/modules/user/user-details/user-details.component.html, components/automate-ui/src/app/modules/user/user-details/user-details.component.ts, components/automate-ui/src/app/modules/user/user-management/user-management.component.spec.ts, components/automate-ui/src/app/modules/user/user-management/user-management.component.ts, components/automate-ui/src/app/page-components/create-user-modal/create-user-modal.component.spec.ts, components/automate-ui/src/app/page-components/create-user-modal/create-user-modal.component.ts
Signed-off-by: venkatesh-r-r <Venkatesh.Rengasamy@progress.com>
Telemetry Coverage for identity under Settings in Automate-ui
https://chefio.atlassian.net/browse/KINETICS-53
Actions in identity pages are tracked using telemetry track event.
STEP 2
Go To Settings -> You can see IDENTITY section -> Click on Users or Teams or API  tokens -> you can search, create, edit and delete users, teams, api token -> For each actions, you can observe the telemetry track event in Network tab(inspect the element …
=> Telemetry Coverage for identity under Settings in Automate-ui

.expeditor/announce-acceptance.sh, .expeditor/announce-release.sh, .expeditor/publish-release-notes.sh, .studio/deployment-service, .studio/tooling, HOW_THE_PIPELINE_WORKS.md, README.md, RELEASE_PROCESS.md, Vagrantfile, components/authn-service/DESIGN.md, components/authz-service/README.md, components/automate-deployment/docs/backup_plan.md, components/automate-deployment/docs/how-to-add-a-service.md, components/automate-deployment/scripts/generate_owca_manifest.rb, components/automate-deployment/tools/upgrade-test-scaffold/upgrade-test-scaffold.go, components/docs-chef-io/content/automate/data_collection.md, components/docs-chef-io/content/automate/log_management.md, components/release-mgmt-dashboard/src/app/app.component.ts, dev-docs/a2-manifest-urls.md, ec2/README.md, scripts/git_difference_expression.rb, scripts/verify_build.sh, tools/hab-dep-graph/main.go
=> announcement and release notes changes

components/nodemanager-service/tests/aws_ec2_nodes_integration_test.go
=> fix nodemanager integration

components/automate-backend-deployment/README.md, components/automate-backend-postgresql/habitat/README.md, components/automate-cluster-ctl/readme, components/docs-chef-io/content/automate/ha_architecture_reference.md, integration/services/ha_backend/init.sh, terraform/a2ha-terraform/destroy/aws/main.tf, terraform/a2ha-terraform/reference_architectures/aws/outputs.tf, test/lib/backend_utils.rb
I has pipeline fixes for postgresql13 and some terraform changes which were required for destroy terraform
=> Pipeline fixes

components/automate-deployment/pkg/majorupgradechecklist/checklist_manager.go, components/automate-deployment/pkg/majorupgradechecklist/upgrade_utils.go, components/automate-deployment/pkg/majorupgradechecklist/v3.go, components/automate-deployment/pkg/majorupgradechecklist/v4.go
https://chefio.atlassian.net/browse/MADROX-136
=> pre and post checklist for open search release

terraform/a2ha-terraform/modules/efs/main.tf, terraform/a2ha-terraform/reference_architectures/existing_nodes/main.tf
Some terraform fixes for warnings and path creation
=> terraform fixes

terraform/a2ha-terraform/reference_architectures/deployment/main.tf
Signed-off-by: shanmugapriya-tr <shanmugapriya.tiruchengoderamanathan@progress.com>
Fixing terraform script to access the modules in right way since we have introduced count. 
=> Setup managed services - Terraform fix

components/automate-cli/cmd/chef-automate/migration_pg.go
Migration command for es to os migration 
chef-automate post-major-upgrade migrate --data=es
TODO: Need to update the PR
=> Migration es

.expeditor/config.yml
Pull inspection version 5.x 
- Compliance profile pan file  should be updated for 5.x release of inspec
=> pull inspec 5.x version

.expeditor/publish-release-notes.sh
Multiple sections were deleted from release notes. So this PR is to fix the missing sections.
=> Fixing Release Notes template

components/automate-cli/cmd/chef-automate/upgrade.go, components/automate-deployment/pkg/majorupgradechecklist/checklist_manager.go, components/automate-deployment/pkg/majorupgradechecklist/post_checklist_manager.go, components/automate-deployment/pkg/majorupgradechecklist/post_checklist_manager_test.go, components/automate-deployment/pkg/majorupgradechecklist/v3.go, components/automate-deployment/pkg/majorupgradechecklist/v4.go, components/automate-deployment/pkg/server/server.go
=> add isExternalDB

.github/workflows/build.yml
workflow was pointing to master. need to change it to main
=> fix workflow 

components/automate-ui/src/app/page-components/attributes/attributes.component.spec.ts, components/automate-ui/src/app/page-components/attributes/attributes.component.ts, components/automate-ui/src/app/page-components/run-history/run-history.component.spec.ts, components/automate-ui/src/app/page-components/run-history/run-history.component.ts, components/automate-ui/src/app/pages/client-runs/client-runs.component.ts, components/automate-ui/src/app/pages/node-details/node-details.component.ts
Signed-off-by: venkatesh-r-r <Venkatesh.Rengasamy@progress.com>
Add telemetry coverage for Client runs
https://chefio.atlassian.net/browse/KINETICS-81
Infra-server client runs actions are tracked using telemetry track event.
STEP 2
Go To Infrastructure -> Client Runs -> You can search, list and delete nodes -> For each actions, you can observe the telemetry track event in Network tab(inspect the element window).
API URL - https://telemetry-acceptance.chef.io/events
With …
=> Add telemetry coverage for Client runs

components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/sync-org-users-slider/sync-org-users-slider.component.spec.ts, components/automate-ui/src/app/modules/infra-proxy/sync-org-users-slider/sync-org-users-slider.component.ts
Telemetry coverage for Infra Server migration flow.
https://chefio.atlassian.net/browse/KINETICS-112
track events are covered in Infra Server migration flow.
STEP 2
Go To Infrastructure -> Chef Servers -> Click on any Chef Infra Server -> Click on Sync Org and Users -> Upload the zip file -> you can see Click to preview link -> click on it then confirm or cancel migration. For each actions, you can observe the telemetry track event in Network …
=> Telemetry coverage for InfraServer migration flow

.expeditor/buildkite/builder_test.sh, .expeditor/buildkite/inspec.sh, .expeditor/buildkite/terraform.sh, .expeditor/config.yml, .expeditor/deploy-dev.pipeline.yml, terraform/test-environments/Makefile, terraform/test-environments/scenarios/s3_websites.tf
As part of cost optimisation, we do not want to deploy the dev instances. This change skips all the dev instances
- The deploy/dev pipeline should only deploy limited instances and skip inspec and bldr test
=> Skip dev deploy instance

README.md
=> dummy changes for release bump

integration/helpers/deployment.sh, integration/tests/manual_upgrade.sh
=> fixing open search pipelines

components/automate-backend-opensearch/Makefile, components/automate-deployment/README.md
=> Bump version [DUMMY-CHANGES]

components/automate-backend-deployment/README.md, components/automate-cluster-ctl/readme, terraform/a2ha-terraform/destroy/aws/main.tf, terraform/a2ha-terraform/modules/system/main.tf, terraform/a2ha-terraform/reference_architectures/deployment/main.tf
1. In Automate HA as a product, when the user runs the deploy command, tmp_path is not created and shows a permission denied error. In this PR that bug is fixed.
Note: Added dependency to the module, that will create/check if folder is created before transfering files into it
2. Variable name mismatch while destroying the AWS infra - Fixed
NA
=> Error on creation of tmp path | AWS - Deploy

components/compliance-service/reporting/relaxting/reports.go
Signed-off-by: Yashvi Jain <91940132+YashviJain01@users.noreply.github.com>
Control List items can be searched over a date range now. The API is amended at the backend.
https://chefio.atlassian.net/jira/software/c/projects/STALWART/boards/361?selectedIssue=STALWART-128
Date range parameter has been added.
```
curl --location --request POST 'https://automate.example.com/api/v0/compliance/reporting/controls' \
--header 'api-token: ${get_admin_token}' \
--data-raw '{
"filters": [
{
"type": "start_time",
"values": [
"starttime"
]
},
{
"type": "end_time",
"values": [
"endtime"
]
}
]
}'
```
All PRs **from Progress employees** should tick these …
=> Adding date range to control API

components/automate-backend-opensearch/Makefile, components/automate-deployment/pkg/services/internal/generated/gen.go, components/automate-opensearch/habitat/hooks/post-run, integration/helpers/deployment.sh, integration/tests/manual_upgrade.sh, integration/tests/v2_to_v3_upgrade.sh, products.meta
=> fix pipeline update for upgrade 

components/automate-ui/src/app/modules/infra-proxy/infra-node-details/infra-node-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/update-node-tag-modal/update-node-tag-modal.component.ts, components/automate-ui/src/app/pages/+compliance/+scanner/containers/nodes-add/nodes-add.component.scss, sonar-project.properties
=> Fixing sonar cloud issues

integration/helpers/ssl_tests.sh
=> fixing security pipeline

components/automate-cs-bookshelf/habitat/plan.sh, components/automate-cs-nginx/habitat/plan.sh, components/automate-cs-oc-bifrost/habitat/plan.sh, components/automate-cs-oc-erchef/habitat/plan.sh
…pdate
Signed-off-by: jan shahid shaik <jashaik@progress.com>
=> Updated chef server version for fixing the chef-server-ctl password update issue

components/automate-ui/src/app/ui.component.ts
=> disabling the banner

components/automate-cs-bookshelf/habitat/plan.sh, components/automate-cs-nginx/habitat/plan.sh, components/automate-cs-oc-bifrost/habitat/plan.sh, components/automate-cs-oc-erchef/habitat/plan.sh
Signed-off-by: jan shahid shaik <jashaik@progress.com>
=> Updated chef version with chef 17.10

components/automate-deployment/habitat/plan.sh, terraform/test-environments/modules/chef_automate_install/main.tf, terraform/test-environments/modules/chef_automate_install/templates/install_chef_automate_cli.sh.tpl
=> update the terrafrom code for dev pipeline

components/automate-cs-bookshelf/habitat/plan.sh, components/automate-cs-nginx/habitat/plan.sh, components/automate-cs-oc-bifrost/habitat/plan.sh, components/automate-cs-oc-erchef/habitat/plan.sh
Signed-off-by: jan shahid shaik <jashaik@progress.com>
=> Version update for chef server

components/docs-chef-io/content/automate/major_upgrade.md
=> Warning Message on Major Upgrade page

components/automate-cli/cmd/chef-automate/init_config.go, components/event-feed-service/pkg/persistence/feed-elastic.go, integration/base.sh, integration/tests/backup.sh
=> Fixing backup build pipeline

components/docs-chef-io/content/automate/opensearch_external_upgrade.md
=> update the ’ -> '

components/compliance-service/reporting/relaxting/nodes.go
Signed-off-by: Yashvi Jain <91940132+YashviJain01@users.noreply.github.com>
Search Nodes API can be run on a date range now and it will return the unique nodes with latest status.
https://chefio.atlassian.net/jira/software/c/projects/STALWART/boards/361?modal=detail&selectedIssue=STALWART-131
Now filters for both start date and end date filters can be applied on this call, if start date is null only the data for end date will be returned.
```
curl --location --request POST 'https://a2-dev.test/api/v0/compliance/reporting/nodes/search' \
--header 'api-token: ${get_admin_token}' \
--data-raw '{
"filters": [
{
"type": "start_time",
"values": [
"{start_time}"
]
},
{
"type": "end_time",
"values": [
"${end_time}"
]
}
],
"page": 1,
"per_page": 100, …
```
=> Date range for Nodes API

components/automate-ui/src/app/entities/orgs/org.actions.ts, components/automate-ui/src/app/entities/orgs/org.model.ts, components/automate-ui/src/app/entities/orgs/org.reducer.ts, components/automate-ui/src/app/entities/orgs/org.requests.ts, components/automate-ui/src/app/entities/orgs/org.selectors.ts, components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.html, components/automate-ui/src/app/modules/infra-proxy/chef-server-details/chef-server-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/migration-slider/migration-slider.component.html, components/automate-ui/src/app/modules/infra-proxy/migration-slider/migration-slider.component.ts
- when I see the conflicting user on the preview screen and if I change the name that time we don't have any check available for existing users. at the time of changing the name, should be a check available for whether the name already exists or not.
- The confirm preview screen needs to wait till there are no conflicting users in the selected list
- The confirm preview screen should highlight the conflicting users on clicking the confirm button
https://chefio.atlassian.net/browse/STALWART-118
https://chefio.atlassian.net/browse/STALWART-112
I have added changes to fix the migration slider screen(preview screen)
All PRs **from Progress …
=> Fixed issues on preview screen for conflicting users and confirm preview not allow on some cases

components/docs-chef-io/content/automate/backup.md, components/docs-chef-io/content/automate/elasticsearch.md, components/docs-chef-io/content/automate/install.md, components/docs-chef-io/content/automate/major_upgrade_4.x.md, components/docs-chef-io/content/automate/opensearch_external_upgrade.md, components/docs-chef-io/content/automate/troubleshooting.md
=> doc fix and change for external os

api/config/deployment/init_config_template.go, api/config/shared/global.proto
Removing elasticsearch heap config from init config generated config.toml file
=> Removing elasticsearch heap memory config from init-config

components/docs-chef-io/content/automate/major_upgrade_4.x.md
=> Added the announcement

components/automate-ui/src/app/services/http/http-client-auth.interceptor.ts, components/infra-proxy-service/migrations/migrations.go, components/infra-proxy-service/migrations/pipeline/utility.go, components/infra-proxy-service/storage/postgres/automate_infra_server_users.go, components/infra-proxy-service/storage/storage.go, components/infra-proxy-service/storage/testDB/testDB.go, components/infra-proxy-service/storage/testDB/testMigrationsDB.go
The Project Id doesn't support special chars. so the idea was to remove special chars from project id and name using regex before inserting them to the db
- rebuild components/infra-proxy-service/
- create a lengthy server with id > 48 chars
- try uploading a backup file
- and click confirm migrations 
=> Remove special char from project names

components/automate-backend-deployment/README.md, components/automate-cli/cmd/chef-automate/automateHADeployExistingInfra.go, components/automate-cli/cmd/chef-automate/genA2haRbTmpl.go, components/automate-cli/cmd/chef-automate/initConfigHa.go, components/automate-cli/cmd/chef-automate/initConfigHaTmpl.go, components/automate-cluster-ctl/lib/cluster/config.rb, components/automate-cluster-ctl/readme, components/automate-cluster-ctl/templates/terraform.tfvars.erb, terraform/a2ha-terraform/reference_architectures/existing_nodes/main.tf, terraform/a2ha-terraform/reference_architectures/existing_nodes/outputs.tf, terraform/a2ha-terraform/reference_architectures/existing_nodes/variables.tf
Signed-off-by: rajkumar <rajan.kumar@progress.com> and  Arvinth C <54614142+ArvinthC3000@users.noreply.github.com>
=> Fix for onprem deployment 

integration/base.sh
=> fixing opensearch rutime variable issue for upgrade

components/automate-ui/src/app/entities/download-reports/download-reports.service.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.spec.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.ts
=> resolving 0-byte issue

components/automate-ui/src/app/entities/download-reports/download-reports.service.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.spec.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.ts, components/compliance-service/integration_test/reporting_server_list_suggestions_test.go
=> Resolving 0-byte-issue for LCR

components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.ts
=> Telemetry coverage for LCR flow

components/docs-chef-io/content/automate/opensearch.md
=> UpDate the note for OpenSearch

components/docs-chef-io/content/automate/major_upgrade_4.x.md
=> Updated the Major Upgrade 4.0.x Page

components/automate-backend-deployment/README.md, components/automate-cluster-ctl/readme, inspec/automate-frontend-chef-server-smoke/controls/base.rb, terraform/a2ha-terraform/reference_architectures/deployment/outputs.tf, terraform/a2ha-terraform/reference_architectures/existing_nodes/outputs.tf
In this PR, some of the output information related to the Opensearch such as the following are modified
- Fixed bug on running the ssh command
- Added ssh info of Opensearch nodes in output block after deployment completed
- Removed the OpenSearch public IP column in the info command as public IP will not be configured in on-prem
- Removed the Kibana dashboard link 
NA
It's is dev done and tested
**Output after deployment:**
**chef-automate info**
=> Bug fixs on Opensearch output

components/automate-backend-opensearch/habitat/config/opensearch.yml, components/automate-backend-opensearch/habitat/default.toml, test/lib/credentials.rb
This PR is to rotate certificates for opensearch in automate HA
and also made some opensearch security configuration settings configurable though default.toml
command to rotate certificates for opensearch
add your certificates in cert/*.pem
and
./scripts/credentials set ssl --oser-ssl
=> Cert rotation backend opensearch

components/automate-backend-elasticsidecar/habitat/config/elastic_sidecar.toml, components/automate-deployment/pkg/backup/spec.go, components/automate-deployment/pkg/backup/spec_test.go, components/automate-deployment/pkg/converge/compiler.go, components/automate-deployment/pkg/converge/converger.go, components/automate-deployment/pkg/converge/stop_mitigation.go, components/automate-deployment/pkg/deployment/deployment.go, components/automate-deployment/pkg/server/upgrade_status.go, components/automate-deployment/pkg/server/upgrade_status_test.go, terraform/a2ha-terraform/modules/automate/templates/provision.sh.tpl
=> update automate-elasticsearch to automate-opensearch

components/automate-cli/cmd/chef-automate/migration_pg.go, components/automate-deployment/habitat/plan.sh, components/automate-postgresql/habitat/plan.sh
We are updating the pg 13 version in migration_pg.go file to the latest postgresql13 version
=> migration_pg version updated

components/docs-chef-io/netlify.toml
Signed-off-by: Ian Maddaus <ian.maddaus@progress.com>
I'm removing the Hugo version specified in the Netlify config file because it's easier to specify and update it in the Netlify Web UI. 
Also, the current version specified has a bug in it which is making builds fail due to some recent work I've been doing.
=> Remove hugo version and go version from netlify config.

.expeditor/promote-hab-pkgs-and-cli.sh
Promotion of airpagged bundle from dev to acceptance was failing
- promotion should work
=> Promote airgapped bundle for current promotion only

components/automate-backend-deployment/README.md, components/automate-backend-deployment/habitat/plan.sh, components/automate-backend-elasticsidecar/habitat/plan.sh, components/automate-cluster-ctl/habitat/plan.sh, components/automate-cluster-ctl/readme
In this PR, terraform core version is pinned as updated terraform in habitat has breaking change. 
Note for internal testing:
- Make sure to give some time (10 to 20 mins) after the changes are built into the cluster package as the deployment package usually takes some time to build to avoid dependency version mismatch
NA
It's dev done and tested in the non-airgap AWS environment
=> Added pinned terraform package version

components/applications-service/cmd/applications-publisher/main.go
Signed-off-by: Sathvikreddy14 <creddy@progress.com>
To reduce the cognitive complexity, I have written a function called errorCondition to check whether any method is throwing an error or not and used that method in main file
https://chefio.atlassian.net/jira/software/c/projects/SHIELD/boards/365?modal=detail&selectedIssue=SHIELD-58&assignee=62297cd2f1e55c0070f29689&assignee=UNASSIGNED_USER_ID
Reduced the cognitive complexity, by writing a function called errorCondition
Made changes in code in components/applications-service/cmd/applications-publisher/main.go
*Please add a note next to any checkbox above if you …
=> reducing cognitive complexity

components/docs-chef-io/content/automate/elasticsearch.md, components/docs-chef-io/content/automate/major_upgrade.md, components/docs-chef-io/content/automate/major_upgrade_4.x.md, components/docs-chef-io/content/automate/opensearch_external_upgrade.md
https://chefio.atlassian.net/jira/software/c/projects/SHIELD/boards/365?modal=detail&selectedIssue=SHIELD-52
=> minor doc correction in upgrade page

components/automate-ui/src/app/entities/download-reports/download-reports.service.ts, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.ts
=> UI-notifications for LCR

components/automate-ui/package-lock.json, components/chef-ui-library/package-lock.json
Fixing pipeline issues occurred because of the version change in package-json file
The code changes are there on package-lock.json
```
rebuild components/chef-ui-library
```
=> Revert package json files

components/automate-cs-oc-erchef/habitat/config/sys.config
Signed-off-by: jan shahid shaik <jashaik@progress.com>
=> changed the ping modules for opensearch

components/automate-backend-opensearch/habitat/config/jvm.options, components/automate-backend-opensearch/habitat/config/opensearch.yml, components/automate-backend-opensearch/habitat/default.toml
In this PR, hard-coded values are changed as config driven and the values are taken from default.toml for automate-backend-opensearch module
Jira Ticket: https://chefio.atlassian.net/browse/MADROX-214
It's dev done and tested in On-prem non-airgap infra
=> Changing static values to config driven

components/automate-backend-opensearch/habitat/default.toml
In this PR, max and min heap size is set to 2 GB.
NA
=> Fixing config mismatch - Heap size change

components/automate-openjdk/habitat/plan.sh
To fix CVEs:
- [CVE-2022-21349](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-21349)
- [CVE-2022-21291](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-21291)
- https://openjdk.java.net/groups/vulnerability/advisories/2022-04-19
https://chefio.atlassian.net/browse/SHIELD-63
=> upgrade JDK to jdk-11.0.15+10

components/automate-backend-deployment/README.md, components/automate-cli/cmd/chef-automate/automateClusterCtlUtil.go, components/automate-cluster-ctl/readme
Bug fix - Added missing extension for the aib file inside transfer files
=> Adding missing extension inside transfer file

components/docs-chef-io/content/automate/ha_chef_backend_to_automate_ha.md
In this PR, some of the Chef-backend to Automate HA migration commands have been updated.
=> Updated Chef-backend to Automate HA migration commands

components/automate-backend-deployment/README.md, components/automate-backend-opensearch/habitat/cert.sh, components/automate-backend-opensearch/habitat/plan.sh, components/automate-cluster-ctl/readme, terraform/a2ha-terraform/modules/opensearch/templates/provision.sh.tpl
=> Reapply the old ha-opensearch config

.expeditor/build.habitat.yml, components/automate-backend-deployment/README.md, components/automate-backend-opensearch/habitat/default.toml
Read the automate-ha-opensearch cert from the vault, while creating the hab pkg in the build pipeline 
=> add cert for hab pkg build in pipeline

.expeditor/build.habitat.yml
=> Indentation fix

components/docs-chef-io/content/automate/performance_benchmarking.md
Signed-off-by: Vaibhav Gadre <vaibhavukandrao.gadre@progress.com>
Performance Benchmarking doc added
=> Performance Benchmarking doc added

components/automate-backend-postgresql/habitat/cert.sh, terraform/a2ha-terraform/modules/opensearch/templates/provision.sh.tpl
Read the Automate-ha-postgres certs from the vault 
=> read the pg certs from the vault

components/automate-backend-opensearch/habitat/cert.sh, components/automate-backend-postgresql/habitat/cert.sh
=> bump the external db packages

components/compliance-service/reporting/relaxting/nodes.go, components/compliance-service/reporting/relaxting/profiles.go, components/compliance-service/reporting/relaxting/reports.go, components/compliance-service/reporting/relaxting/stats.go, components/compliance-service/reporting/relaxting/trend.go, components/compliance-service/reporting/relaxting/util.go, components/compliance-service/reporting/relaxting/util_test.go
In this PR, there is a fix to show old scan report, previously it use to latest scan report because of this old scan report was shown empty
https://chefio.atlassian.net/browse/SHIELD-54
You need to see old san report after click on report as shown in below video
```
➜  automate git:(SHIELD-54/show_older_scan_job_report_fix) t_fix) hab studio enter
[158][default:/src:130]# start_all_services
......
......
......
[158][default:/src:130]# rebuild components/compliance-service/
[158][default:/src:130]# rebuild components/automate-deployment/
run 2 scan jobs an try to see the data
```
All PRs **from Progress employees** should tick these …
=> show older scan job report

components/automate-backend-opensearch/habitat/plan.sh, components/automate-opensearch/habitat/plan.sh
The run hooks use `#!{{pkgPathFor "core/bash"}}` which will return an empty string if we don't include the dep for bash causing it to put `#!/bin/bash` which may or may not be a system package instead of the hab version we are expecting.
=> Add core/bash dep for opensearch hab packages

components/docs-chef-io/content/automate/managed_services.md
Signed-off-by: Vaibhav Gadre <vaibhavukandrao.gadre@progress.com>
Standalone Automate with AWS managed services PostgreSQL/OpenSearch Backup/restore document
=> Standalone Automate with AWS managed services PostgreSQL/OpenSearch Backup/restore document

components/automate-backend-deployment/README.md, components/automate-cluster-ctl/readme, terraform/a2ha-terraform/modules/aws/security.tf
=> Missed out security group fix

components/automate-cli/cmd/chef-automate/provisionInfraHa.go
Signed-off-by: shanmugapriya-tr <shanmugapriya.tiruchengoderamanathan@progress.com>
Marking the flag saas hidden so that it doesn't appear on help command
=> Hide saas flag

components/docs-chef-io/content/automate/managed_services.md
=> fix hugo lint errors

terraform/a2ha-terraform/modules/automate/files/config.toml.erb, terraform/a2ha-terraform/modules/opensearch/templates/efs_backup.sh
In this PR, some of the file paths in config and plan files are mismatching, and backup with EFS was failing. Those are updated.
=> [WIP] Fix for EFS file path

components/docs-chef-io/content/automate/opensearch.md
=> doc update - 1.0

components/docs-chef-io/content/automate/ha.md, components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md, components/docs-chef-io/content/automate/ha_aws_bastion.md, components/docs-chef-io/content/automate/ha_aws_cert_mngr.md, components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md, components/docs-chef-io/content/automate/ha_common.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md, components/docs-chef-io/content/automate/ha_platform_support.md
This PR is created to make the changes to the Chef Automate HA section after peer review.
- https://docs.chef.io/automate/ha/
=> feedback changes updated

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.ts
=> resolving overlapping issue in UI

components/docs-chef-io/data/automate/api-static/07-report-manager-export.swagger.json, components/docs-chef-io/static/automate-api-docs/all-apis.swagger.json
Add modified swagger file for all api
=> Adding modified all-apis  swagger file

components/docs-chef-io/content/automate/large_compliance_report.md
=> lcr update for ha docs

components/compliance-service/cmd/compliance-service/cmd/run.go, components/compliance-service/compliance.go, components/compliance-service/config/types.go, components/compliance-service/ingest/pipeline/compliance.go, components/compliance-service/ingest/pipeline/processor/control_worker.go, components/compliance-service/ingest/pipeline/processor/control_worker_test.go, components/compliance-service/ingest/pipeline/publisher/compliance.go, components/compliance-service/ingest/server/compliance.go, components/compliance-service/integration_test/global_test.go, components/compliance-service/integration_test/suite_test.go
Created a new asynchronous function which will get the report uuid at the time of inserting the report into the database and update the new index.
https://chefio.atlassian.net/browse/STALWART-164
A connection with cereal manager is implemented which will have a new workflow now.
```
```
=> Adding the commit again

components/compliance-service/reporting/relaxting/reports.go, components/compliance-service/reporting/relaxting/reports_test.go
Signed-off-by: SahithiMy <sahithi.mylangam@progress.com>
=> Fixed testing errors

components/authz-service/storage/postgres/migration/sql/78_update_roles.up.sql, components/authz-service/storage/postgres/migration/sql/README.md, components/docs-chef-io/content/automate/iam_actions.md
=> adding lcr permissions for viewer and editor

.studio/compliance-service, components/compliance-service/ingest/ingestic/ingestic.go, components/compliance-service/ingest/ingestic/project_update.go, components/compliance-service/ingest/pipeline/processor/control_worker.go, components/compliance-service/ingest/pipeline/processor/parse_struct.go, components/compliance-service/ingest/pipeline/processor/parse_struct_test.go, components/compliance-service/ingest/pipeline/publisher/compliance.go, components/compliance-service/integration_lcr_test/global_test.go, components/compliance-service/integration_lcr_test/reporting_inject_lcr_test.go, components/compliance-service/integration_lcr_test/suite_test.go, components/compliance-service/integration_test/reporting_server_list_profiles_test.go, components/compliance-service/integration_test/reporting_server_list_suggestions_test.go, components/compliance-service/integration_test/stats_server_read_summary_test.go, components/compliance-service/reporting/relaxting/es_types.go, components/compliance-service/reporting/relaxting/profiles.go, components/compliance-service/reporting/relaxting/reports.go, components/compliance-service/reporting/relaxting/reports_test.go, components/compliance-service/reporting/relaxting/stats.go
Added workflow function which will update or insert data into bulk to new control index.
https://chefio.atlassian.net/jira/software/c/projects/STALWART/boards/361?modal=detail&selectedIssue=STALWART-167
Data is being added to the new control index structure
```
```
The data will be added to new index
- [X} All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).
*Please add a note next to …
=> Changes for add data to new control index

components/automate-deployment/pkg/manifest/provider.go
Need to add Proxy config for the custom transport so it can automatically pull in any proxy environment variables set by the user.
Fixes #7120 
=> Set ProxyFromEnvironment method for the transport

integration/helpers/s3.sh
This will fix the S3 Backup Integration Test Pipeline.
=> fix the endpoint of s3 bucket in Integration test

components/compliance-service/ingest/ingestic/ingestic.go, components/compliance-service/reporting/relaxting/indices.go
Signed-off-by: SahithiMy <sahithi.mylangam@progress.com>
Changed previous day latest to false for control index report 
https://chefio.atlassian.net/jira/software/c/projects/STALWART/boards/361?modal=detail&selectedIssue=STALWART-166
Changed the day latest for control index structure
=> changes for previous day latest

.expeditor/publish-release-notes.sh
The release notes Upgrade journey does not talk about the 3.0.49 to 4.0.x version by default.
- The pending release notes wiki should have 3.0.49 to 4.0.x declaration
=> Updating release notes for 4.0.x major upgrade

components/docs-chef-io/content/automate/node_bootstarp_ha.md
In this documentation PR, Bootstrapping for node in HA is detailed along with troubleshooting
Jira Ticket: https://chefio.atlassian.net/browse/MADROX-237
=> [Doc] Adding HA node bootstrapping document

components/docs-chef-io/content/automate/ha_restore.md
Public doc for restore in automate ha need to be little enhanced, added some notes with example, also added some explained content.
https://chefio.atlassian.net/browse/MADROX-239
=> Enhancing restore docs and added some notes with example

components/docs-chef-io/content/automate/ha_backup_restore_prerequisites.md, components/docs-chef-io/content/automate/ha_node_bootstraping.md
In this PR, a new section of Configuring Automate to register the snapshot locations with OpenSearch is detailed with some modifications on EFS backup.
Jira ticket: https://chefio.atlassian.net/browse/MADROX-240
It is dev done and tested
=> Added doc steps for EFS configuration

components/compliance-service/cmd/compliance-service/cmd/run.go, components/compliance-service/ingest/ingestic/mappings/comp-control-rep-date.go, components/compliance-service/ingest/pipeline/processor/parse_struct.go, components/compliance-service/ingest/pipeline/processor/parse_struct_test.go, components/compliance-service/reporting/relaxting/es_types.go, components/compliance-service/reporting/relaxting/reports.go, components/compliance-service/reporting/relaxting/reports_test.go, components/compliance-service/reporting/relaxting/util.go, components/compliance-service/reporting/relaxting/util_test.go
Added the node status to point it to the new control index. Node status in the control items API is from new control index now. 
https://chefio.atlassian.net/browse/STALWART-171
The new control index structure now can handle the filters at the node level to support the filtering from the UI side.
- Rebuild compliance service using ``` rebuild components/compliance-service ```
- Add some data from hab using ```chef_load_compliance_scans -D1 -N20 -M20 -T20```
- The API can used to fetch the data 
```
curl --location --request POST 'https://a2-dev.test/api/v0/compliance/reporting/controls' \
--header 'api-token: ${get_admin_token}' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--data-raw '{
"filters": [
{
"type": "start_time",
"values": [ …
```
=> Adding node status from new control index in control List API

components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md, components/docs-chef-io/content/automate/ha_backup_restore_prerequisites.md
Signed-off-by: Sathvikreddy14 <creddy@progress.com>
In this PR, I have added Process for Migration of Automate to Automate HA using S3 Bucket and TroubleShooting process if Restore fails
Jira Ticket: https://chefio.atlassian.net/browse/MADROX-246
It has been tested 
=> Added Migration from Automate to Automate HA using S3

components/compliance-service/ingest/ingestic/ingestic.go, components/compliance-service/integration_test/compliance_reporting_test.go, components/compliance-service/migrations/migrations.go, components/compliance-service/reporting/relaxting/es_types.go
=> Temp branch

.expeditor/push-git-tag.sh
test if removal of -released from tag name works for hab-build
=> test if removal of -released from tag name works for hab-build

.expeditor/publish-release-notes.sh
The release notes do not have the External Chef Service supported versions.
- The pending release notes should have the version
=> Adding Supported Product Versions in the release notes

components/compliance-service/ingest/ingestic/mappings/comp-control-rep-date.go, components/compliance-service/ingest/pipeline/processor/parse_struct.go, components/compliance-service/ingest/pipeline/processor/parse_struct_test.go, components/compliance-service/reporting/relaxting/es_types.go, components/compliance-service/reporting/relaxting/filters.go, components/compliance-service/reporting/relaxting/filters_test.go, components/compliance-service/reporting/relaxting/reports.go, components/compliance-service/reporting/relaxting/stats.go, components/compliance-service/reporting/relaxting/stats_test.go, components/compliance-service/reporting/relaxting/util.go
The control summary api which gives the counts of failed, Passed, skipped and waived controls is now getting data from new control index. Which will also take care of the filtering process
https://chefio.atlassian.net/jira/software/c/projects/STALWART/boards/361?modal=detail&selectedIssue=STALWART-170
Control summary is getting the correct number of counts over a date range now.
Upload some data into compliance.
Use below curl command
```
curl --location --request POST 'https://a2-dev.test/api/v0/compliance/reporting/stats/summary' \
--header 'api-token: {get_admin_token}' \
--data-raw '{"type":"controls"}'
```
With occasional exceptions, all PRs **from Progress …
=> Control Summary From New Control Index

components/session-service/server/server.go
Created /token Api in Automate Session Service
https://chefio.atlassian.net/browse/KINETICS-167
/token Api created in Automate session service that takes code as query params and returns IdToken, tokenType, expiresIn, refreshToken in response.
- hab studio enter
- build components/automate-ui-devproxy/
- start_automate_ui_background
- rebuild components/session-service/
- rebuild components/automate-dex/
- Make some changes in /callback Api so that it will not run. For eg: in func callbackHandler comment the Line no: 327 and write code := "" , save the code and again rebuild the session service.
- Now Signin in automate UI. Go to network tab, select the signin api and copy the code.
- In Postman, give the url: …
=> Created /token Api in Automate Session Service

components/automate-dex/habitat/plan.sh, components/session-service/oidc/oidc.go, components/session-service/server/server.go, components/session-service/server/server_test.go
Signed-off-by: SanjuPal01 <sanju.sanju@progress.com>
Created New Refresh API. When you hit this API with valid refresh token you will get new Refresh Token and ID token with new Expiry Time.
https://chefio.atlassian.net/browse/KINETICS-168
`rebuild components/automate-dex`
`rebuild components/session-service`
EndPoint: `https://automate-url/session/refresh_api`
```
{
"refresh_token": "ChlyN2g1cXdtanY0ZmRmcT.....2bHFrbmkyaHdvcXh0dfNWI0M2pxbnFy",
"grant_type": "refresh_token"
}
```
pass the refresh-token and grant-type as Body Parameter.
While making the call to this api also make sure to pass Authorization token. 
You can get the Authorization token from the request header of refresh API.
With occasional exceptions, all PRs **from Progress employees** must tick …
=> New Refresh API

components/automate-cli/cmd/chef-automate/genA2haRbTmpl.go
=> default port in inner config template incase not provided in config.toml

components/compliance-service/reporting/relaxting/reports.go, components/compliance-service/reporting/relaxting/reports_test.go
=> handling special char for control id search

components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md, components/docs-chef-io/content/automate/ha_chef_backend_to_automate_ha.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
Docs changes for custom ssh port changes.
https://chefio.atlassian.net/browse/MADROX-258
=> docs changes for custom ssh port support

components/docs-chef-io/content/automate/airgapped_installation.md, components/docs-chef-io/content/automate/major_upgrade.md
Automate aib bundles are set to expire in 30 days. These bundles expiry needs to be extended to 60 days.
Also the milestone release bundles will be exception to this.
We need modification in the document in every places to keep the customer expectation correct.
=> Update docs for AIB bundle

.expeditor/push-git-tag.sh
Automate release is getting erred out while pushing the git tag.
=> Modified script to update git tag name

components/automate-backend-deployment/habitat/hooks/install
code refactoring for workspace upgrade
=> removing duplicate line for copying destroy dir from terraform

components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.ts
Changed the startDate and endDate date interval as same day.
https://chefio.atlassian.net/browse/STALWART-135
Changed the code for startDate should be same day of endDate
rebuild components/automate-ui/
=> Changing Date Interval in UI

components/compliance-service/reporting/relaxting/suggestions.go
=> Enabling suggestions for case insensitive match

components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md, components/docs-chef-io/content/automate/ha_existing_a2ha_to_automate_ha.md, components/docs-chef-io/content/automate/ha_platform_support.md, components/docs-chef-io/content/automate/ha_security_firewall.md, components/docs-chef-io/content/automate/major_upgrade_4.x.md
=> Change the version for Migration In HA Docs

components/automate-deployment/habitat/plan.sh
=> bump the version

components/compliance-service/ingest/ingestic/mappings/comp-run-info.go
Adding mapping fix, appending data properly.
Mapping and settings properly ingested
add some data into compliance using ``` chef_load_compliance_scans ```
comp-2-run-info should have proper mappings and settings
=> Resolving issue for mapping

components/docs-chef-io/content/automate/backup.md, components/docs-chef-io/content/automate/ha_backup_restore.md, components/docs-chef-io/content/automate/ha_backup_restore_prerequisites.md
=> doc update for endpoint attribute for automate bkp and restore

components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.ts
Signed-off-by: VivekSharma2607 <sharmavishu760@gmail.com>
Needed to fix the bug for the Overview Tab of Compliance reporting
- Once the summary also returns the 24 hours interval for the nodes Data
- rebuild components/automate-ui 
=> Updated the overview tab for Compliance Reporting

components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-overview/reporting-overview.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.component.spec.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.spec.ts, components/automate-ui/src/app/pages/+compliance/shared/reporting/stats.service.ts
=> Yashvi/lint UI

components/report-manager-service/worker/worker_test.go
=> Error correction

components/docs-chef-io/content/automate/ha_backup_restore_prerequisites.md
=> update the conf path in prerequisite section 

components/docs-chef-io/content/automate/major_upgrade_4.x.md
Troubleshooting added for minor upgrade for error: minimum compatible version not found
=> Added upgrade troubleshooting step

components/compliance-service/ingest/ingestic/mappings/comp-run-info.go
Reverted the comp-run-info mapping
rebuild compliance service
=> Reverted the comp-run-info index

components/compliance-service/compliance.go, components/compliance-service/reporting/relaxting/assets.go, components/compliance-service/reporting/relaxting/util.go
Fetch assets count based on config data
- By default assets should be fetched for 60 days
- If config values says 35 then assets should be fetched for 35 days
- 
`rebuild components/compliance-service/`
=> Changed hardcoded value to config value

components/docs-chef-io/content/automate/ha_existing_a2ha_to_automate_ha.md, components/docs-chef-io/content/automate/ha_platform_support.md
=> update the migration docs

components/automate-gateway/gateway/services.go, components/compliance-service/cmd/compliance-service/cmd/run.go, components/compliance-service/ingest/ingestic/ingestic.go, components/compliance-service/ingest/pipeline/compliance.go, components/compliance-service/ingest/pipeline/processor/control_worker.go, components/compliance-service/ingest/pipeline/processor/parse_struct.go, components/compliance-service/ingest/pipeline/processor/summary.go, components/compliance-service/ingest/pipeline/publisher/compliance.go, components/compliance-service/migrations/migration_workflow.go
=> Ingestion fix

components/automate-cli/cmd/chef-automate/status.go, components/automate-cli/cmd/chef-automate/upgrade.go, components/automate-cli/pkg/status/error.go, components/docs-chef-io/content/automate/major_upgrade_4.x.md
https://chefio.atlassian.net/browse/MADROX-304
=> restart service by killing PID of deployment svc

components/automate-deployment/pkg/majorupgradechecklist/searchengine_setting_migration.go, components/automate-deployment/pkg/majorupgradechecklist/v4.go, components/automate-deployment/pkg/majorupgradechecklist/v4_test.go
=> delete stale indexes

components/automate-cli/cmd/chef-automate/migration_pg.go, components/automate-cli/cmd/chef-automate/upgrade.go, components/automate-cli/pkg/status/error.go, components/automate-deployment/pkg/majorupgradechecklist/checklist_manager.go, components/automate-deployment/pkg/majorupgradechecklist/searchengine_setting_migration.go, components/automate-deployment/pkg/majorupgradechecklist/v3.go, components/automate-deployment/pkg/majorupgradechecklist/v4.go
=> total shards validation

components/automate-deployment/pkg/client/automate_config.go, components/automate-deployment/pkg/majorupgradechecklist/v3.go, components/automate-deployment/pkg/majorupgradechecklist/v4.go
Signed-off-by: Arvinth C <arvinth.chandrasekaran@progress.com> and Sathvikreddy14 <creddy@progress.com>
In this PR, 
- when the user is upgraded from 3.x version to 4.x version, and if the backup is configured with the S3 bucket, the endpoint should be validated if that includes the regional pattern. This change will ensure that the endpoint is global (`https://s3.amazonaws.com`) instead of regional (`https://s3.<region>.amazonaws.com`)
- when the user is patching backup config with s3 backup, this change will throw an error if the endpoint is regional
Jira Ticket: https://chefio.atlassian.net/browse/SHIELD-138
It's dev done …
=> Added prompt to get acknowledgement from user for updating s3 url

components/automate-deployment/pkg/majorupgradechecklist/v4.go, components/automate-deployment/pkg/majorupgradechecklist/v4_test.go
=> check version before deleting old automate indices

components/automate-cli/cmd/chef-automate/migration_pg.go, components/automate-deployment/pkg/majorupgradechecklist/upgrade_utils.go, components/automate-deployment/pkg/majorupgradechecklist/v3.go
Created common util for disk space validation
https://chefio.atlassian.net/browse/MADROX-281
=> Created common util for disk-space-validation

components/automate-cli/cmd/chef-automate/upgrade.go, components/automate-deployment/pkg/majorupgradechecklist/checklist_manager.go, components/automate-deployment/pkg/majorupgradechecklist/opensearch_settings_template.go, components/automate-deployment/pkg/majorupgradechecklist/searchengine_setting_migration.go, components/automate-deployment/pkg/majorupgradechecklist/v3.go, components/automate-deployment/pkg/majorupgradechecklist/v4.go
=> individual error message for each failed settings

components/automate-cli/cmd/chef-automate/migration_pg.go
=> Fixing build kite

components/docs-chef-io/content/automate/ha_security_firewall.md
=> ha_security_firewall doc update

components/docs-chef-io/content/automate/loadbalancer_configuration.md
=> SHIELD-140 added ha proxy lb config in ha

components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
For Automate HA as a product, the user needs a pre-filled get-started configuration in the document page with the minimum modification to setup their test environment for their AWS/On-prem infra
https://chefio.atlassian.net/browse/MADROX-293
On-Premise deployment:
AWS deployment:
=> Adding sample config

components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
Signed-off-by: Sathvikreddy14 <creddy@progress.com>
As an Automate user, we need to have clear understanding of sudo_password field in config file and mention what authentication we are supporting currently.
https://chefio.atlassian.net/browse/MADROX-294
=> Docs Information on sudo password in config

components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md, components/docs-chef-io/content/automate/ha_upgrade_introduction.md
Signed-off-by: prasad927 <Prasad.Chaudhari@progress.com>
Fix URL which are not working due to Bundle not being available now for download like:
https://packages.chef.io/airgap_bundle/current/automate/4.0.91.aib 
https://chefio.atlassian.net/browse/SHIELD-141
=> changed 4.0.91.aib to <version>.aib in url

components/docs-chef-io/content/automate/ha_chef_backend_to_automate_ha.md
As an Automate HA user migrated from Chef-Backend infra server, I and pretty much familiar with chef workstation,
Automate HA also support workstation, Docs related to how to setup and use will be great help
https://chefio.atlassian.net/browse/MADROX-302
=> adding docs for Automate HA usage from workstation

components/config-mgmt-service/backend/elastic/suggestions.go
https://chefio.atlassian.net/browse/KINETICS-213
Node Names having capital letters should show in suggestions when searched from the infrastructure tab
1. Checkout the code
2. From hab studio, rebuild config management service
`rebuild components/config-mgmt-service`
3. Load some client-run data using the chef-load tool, with node_name_prefix having some capital letters.
4. log in to automate and search for node name on the infrastructure tab
Before change
After change
=> Enabling suggestions for case insensitive match for node name

components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
Add docs for the below questions  
* How can I add additional node/nodes to Chef Automate or Chef Infra Frontend(FE) to the exiting setup?
* How can I add additional node/nodes to OpenSearch and PostgreSQL cluster(Backend cluster)?
* If one of my FE node either Chef Automate or Chef Infra goes into bad state, how can I remove that single node from the cluster?
=> How to add more node to the existing deployed cluster for OnPrem Deployment

components/automate-cli/cmd/chef-automate/config.toml, components/automate-cli/cmd/chef-automate/genA2haRbTmpl.go, components/automate-cli/cmd/chef-automate/initConfigHa.go, components/automate-cli/cmd/chef-automate/initConfigHaTmpl.go, components/automate-cluster-ctl/lib/cluster/config.rb, components/automate-cluster-ctl/lib/cluster/config/generator.rb, components/automate-cluster-ctl/templates/terraform.tfvars.erb, terraform/a2ha-terraform/destroy/aws/main.tf, terraform/a2ha-terraform/modules/aws/inputs.tf, terraform/a2ha-terraform/modules/aws/main.tf, terraform/a2ha-terraform/reference_architectures/aws/main.tf, terraform/a2ha-terraform/reference_architectures/aws/variables.tf, terraform/a2ha-terraform/reference_architectures/deployment/variables.tf
Signed-off-by: SanjuPal01 <sanju.sanju@progress.com>
Give the Delete on termination Functionality. Now user can set the delete on termination value from the config file itself.
https://chefio.atlassian.net/browse/KINETICS-204
Create the Airgap Bundle by including 
```
"ssanju/automate-ha-cluster-ctl/0.1.0/20220920094521",
"ssanju/automate-ha-deployment/0.1.0/20220920095959",
```
Add `delete_on_termination = false` on `config.toml`
Install the updated cli using the below command:
- `hab pkg install -bf ssanju/automate-cli/0.1.0/20220920101605`
The Below commands are for provisioning the infrastructure and deployment.
- `chef-automate provision-infra config.toml --airgap-bundle <airgap-bundle> `
- `chef-automate deploy config.toml --airgap-bundle <airgap-bundle>` …
=> Delete on Termination

components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
=> Update the Add node page for the HA onprem deplyment

components/docs-chef-io/content/automate/backup.md, components/docs-chef-io/content/automate/ha_backup_restore.md
https://chefio.atlassian.net/browse/MADROX-291
=> Doc: AWS S3 Backup permissions of default bucket

components/automate-cli/cmd/chef-automate/upgrade.go
Handled use cases post upgrade status command.
=> Handled use cases post upgrade status command

components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md, components/docs-chef-io/content/automate/ha_existing_a2ha_to_automate_ha.md, components/docs-chef-io/content/automate/install.md, components/docs-chef-io/content/automate/managed_services.md, components/docs-chef-io/content/automate/opensearch.md, components/docs-chef-io/content/automate/postgresql.md, components/docs-chef-io/layouts/shortcodes/automate/char-warn.md, components/docs-chef-io/layouts/shortcodes/automate/chars-notallowed.md
The idea was to update the documentation adding the special characters not allowed for setting passwords for OpenSearch and Postgres db.
Update the documents every where we have config.toml for OpenSearch and Postgres db config.
Please test the changes at https://deploy-preview-7432--chef-automate.netlify.app/automate/opensearch/
https://user-images.githubusercontent.com/36985548/192173579-6287fcdf-c9f4-499c-98bf-c5c9b9d67f0d.mov
=> Found the chars not allowed for passwords

components/automate-cli/cmd/chef-automate/upgrade.go
Created opensearch_config.toml file during upgrade.
=> SHIELD-146 created opensearch_config.toml file during upgrade.

terraform/a2ha-terraform/modules/opensearch/inputs.tf, terraform/a2ha-terraform/modules/opensearch/templates/provision.sh.tpl
Bug fix
https://chefio.atlassian.net/browse/MADROX-318
Dev tested
=> [WIP]Bug fix for variable passing in On-Prem backup config in OS node

components/automate-deployment/pkg/backup/bucket.go, components/automate-deployment/pkg/backup/location_spec.go, components/automate-deployment/pkg/backup/metadata.go, components/automate-deployment/pkg/backup/runner.go, components/automate-deployment/pkg/backup/spec.go
Ignoring the response of metadata.json lookup for the restore 
=> Add restore service list for chef-automate bkp restore

components/automate-cli/cmd/chef-automate/migrator/migratorv4/cleanupdata.go
Fixing clean up command not deleting files
=> fix cleanup command

components/docs-chef-io/content/automate/ha_disaster_recovery_setup.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
=> Documentation’s Update for the Automate HA Docs

components/automate-cli/cmd/chef-automate/migrator/migratorv4/migratorV4.go, components/automate-cli/cmd/chef-automate/upgrade.go, components/automate-deployment/pkg/inspector/upgradeinspectorv4/diskspace.go, components/automate-deployment/pkg/inspector/upgradeinspectorv4/diskspace_test.go, components/automate-deployment/pkg/inspector/upgradeinspectorv4/upgradeInspectorV4.go, components/automate-deployment/pkg/inspector/upgradeinspectorv4/upgradeInspectorV4_test.go
=> SHIELD-158 Added text change

components/automate-cli/cmd/chef-automate/migration_pg.go, components/automate-cli/cmd/chef-automate/migrator/migrator.go, components/automate-cli/cmd/chef-automate/migrator/migratorv4/cleanupdata.go, components/automate-cli/cmd/chef-automate/migrator/migratorv4/cleanupdata_test.go, components/automate-cli/cmd/chef-automate/migrator/migratorv4/migratorV4.go, components/automate-cli/cmd/chef-automate/upgrade.go, components/automate-cli/cmd/chef-automate/upgrade_test.go, components/automate-deployment/pkg/inspector/upgradeinspectorv4/diskspace.go, components/automate-deployment/pkg/inspector/upgradeinspectorv4/diskspace_test.go, components/automate-deployment/pkg/inspector/upgradeinspectorv4/enablemaintenance.go, components/automate-deployment/pkg/inspector/upgradeinspectorv4/plandowntime.go, components/automate-deployment/pkg/inspector/upgradeinspectorv4/plandowntime_test.go, components/automate-deployment/pkg/inspector/upgradeinspectorv4/takebackup.go, components/automate-deployment/pkg/inspector/upgradeinspectorv4/takebackup_test.go, components/automate-deployment/pkg/inspector/upgradeinspectorv4/upgradeInspectorV4.go, components/automate-deployment/pkg/inspector/upgradeinspectorv4/upgradeInspectorV4_test.go, components/automate-deployment/pkg/majorupgradechecklist/post_checklist_manager.go, components/automate-deployment/pkg/majorupgradechecklist/post_checklist_manager_test.go, components/automate-deployment/pkg/majorupgradechecklist/upgrade_utils.go, components/automate-deployment/pkg/majorupgradechecklist/v4.go, components/automate-deployment/pkg/server/server.go
Feedback and change request from CFT and Will Fisher on Upgrade 4.x CLI changes
https://chefio.atlassian.net/browse/SHIELD-158
=> SHIELD-158 Feedback and change request from CFT and Will Fisher on Upgrade 4.x CLI changes

components/automate-cli/cmd/chef-automate/migrator/migratorv4/migratorV4.go, components/automate-cli/cmd/chef-automate/upgrade.go, components/automate-deployment/pkg/inspector/upgradeinspectorv4/diskspace.go, components/automate-deployment/pkg/inspector/upgradeinspectorv4/diskspace_test.go, components/automate-deployment/pkg/inspector/upgradeinspectorv4/upgradeInspectorV4_test.go, components/docs-chef-io/content/automate/major_upgrade_4.x.md, components/docs-chef-io/content/automate/opensearch.md
Bug fix for Automate CLI and doc changes.
=> bug fix for automate cli

components/docs-chef-io/content/automate/major_upgrade_4.x.md
=> 4.x docs changes

components/compliance-service/ingest/ingestic/ingestic.go, components/compliance-service/migrations/migration_workflow.go, components/compliance-service/reporting/relaxting/es_types.go
Added the logic for below two corner cases:
- If node1 data is in upgrade migration process, while node1 data is ingested, the ingestion record will be considered for the control index
- If node1 data is in upgrade migration process, while node1 data is ingested, the ingestion record will be considered for the comp run info index
https://chefio.atlassian.net/browse/STALWART-244
Add some data into compliance service and upgrade to this branch.
=> Adding smart logic for upgrade and ingestion in parallel

components/automate-backend-ctl/habitat/lib/automate/backend/service_config.rb, components/automate-cli/cmd/chef-automate/config.go, components/automate-cli/cmd/chef-automate/configTemplate.go, components/automate-cli/cmd/chef-automate/sshAutomateHA.go, components/docs-chef-io/content/automate/ha_patching.md, go.mod, go.sum, terraform/a2ha-terraform/modules/aws/outputs.tf, terraform/a2ha-terraform/modules/vsphere/outputs.tf
- **[Not INCLUDED]update /etc/chef-automate/config**
- **Doc added**
- **Applying on top of applied configs by getting applied toml**
In Automate HA, when users need to add/modify existing config, they need to ssh into appropriate nodes to patch the config. Now the same can be done from the Provisioning host which avoids SSH into other nodes individually
chef-automate config patch FLAG <PATH/TO/TOML>
- --fe, --frontend
- --opensearch, -o
- --postgresql, -p
chef-automate config patch --fe /home/ubuntu/automate_config.toml
chef-automate config patch -o /home/ubuntu/os_config.toml
Custom packages to use:
CLI for bastion server: `arvinth/automate-cli/0.1.0/20221023180617`
In Manifest to create bundle: …
=> Adding patch config changes in bastion

components/automate-knife-ec-backup/habitat/plan.sh
=> update the version for knife-ec-backup in chef-automate airgap bundle 

components/automate-cli/cmd/chef-automate/certRotate.go, components/automate-cli/cmd/chef-automate/sshAutomateHA.go, terraform/a2ha-terraform/modules/aws/outputs.tf, terraform/a2ha-terraform/modules/vsphere/outputs.tf
SanjuPal01 <ssanju@progress.com>
Added the cert rotate command for HA service. Now user has to pass the certificate paths to cert-rotate cmd and it will rotate the certificates of all automate and postgres nodes
https://chefio.atlassian.net/browse/KINETICS-234
https://chefio.atlassian.net/browse/KINETICS-235
sahiba3108/automate-ha-deployment/0.1.0/20221019125201
ssanju/automate-cli/0.1.0/20221020101212
`chef-automate cert-rotate --a2 --private-cert certs/private.cert --public-cert certs/public.cert` 
(You can also use --automate flag instead of a2)
This will rotate the public and private cert of all automate nodes. …
=> Kinetics 234/cert rotate

components/automate-cli/cmd/chef-automate/cleanup.go, components/automate-cli/cmd/chef-automate/config.go, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md, components/docs-chef-io/content/automate/ha_patching.md
cleanup script to clean the on-prem instance of all the Automate HA related Applications
https://chefio.atlassian.net/browse/MADROX-355
=> Need a cleanup script to clean the instance of all the Automate HA related Applications

components/automate-cli/cmd/chef-automate/config.go
=> Removing temp file after copying it to remote

components/automate-cli/cmd/chef-automate/certRotate.go
Signed-off-by: “SanjuPal01” <sanju.sanju@progress.com>
=> Updating Cert Rotate

components/automate-cli/cmd/chef-automate/initConfigHaTmpl.go, components/docs-chef-io/content/automate/ha_backup_restore_aws_efs.md, components/docs-chef-io/content/automate/ha_backup_restore_aws_s3.md, components/docs-chef-io/content/automate/ha_backup_restore_file_system.md, components/docs-chef-io/content/automate/ha_backup_restore_object_storage.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
As an Automate HA user, I want to use public documentation to run the chef-automate config patch command from the bastion host to add backup and restore configs so that I can patch it to all the frontend & backend nodes of Automate HA.
Jira ticket: https://chefio.atlassian.net/browse/MADROX-378
=> [Doc]Updating Documentation for `config patch` config

components/docs-chef-io/content/automate/ha_backup_restore_aws_efs.md, components/docs-chef-io/content/automate/ha_backup_restore_file_system.md, components/docs-chef-io/content/automate/ha_backup_restore_object_storage.md
=> Removing unsupported character

.expeditor/verify.pipeline.yml, scripts/install_hab_pkg.sh
Signed-off-by: Sathvikreddy14 <creddy@progress.com>
As an Automate developer, we need to fix the unit[OPA] pipeline in [[chef/automate:main] verify] which is failing. We are cleaning up the space in /bin/ before running the scripts.
The unit[OPA] pipeline is now passing in Buildkite.
=> Unit[OPA] Pipeline fix

components/automate-cli/cmd/chef-automate/certRotate.go, components/automate-cli/cmd/chef-automate/certRotate_test.go
Signed-off-by: prasad927 <Prasad.Chaudhari@progress.com>
https://chefio.atlassian.net/browse/SHIELD-173
=> increased unit test coverage

components/automate-cli/cmd/chef-automate/cleanup.go
=> Removing /bin/hab on backend nodes with cleanup command

components/automate-backend-deployment/habitat/plan.sh
=> Fixing Backend deloyment pkg as it doesnt pulling latest change 

components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
=> Added a warning to not modify the workspace path in docs

components/automate-backend-deployment/README.md, components/automate-cli/cmd/chef-automate/config.go, components/automate-cli/cmd/chef-automate/configTemplate.go, components/automate-cli/cmd/chef-automate/sshUtils.go, components/docs-chef-io/content/automate/ha_patching.md
In this PR
1. Added new flags for 'automate' node and 'chef_server' node. 
- Usage `chef-automate config patch --chef_server cs.toml`
- Flags available
Arg/ Flag | Duplicate | Shorthand
-- | -- | --
--automate | --a2 | -a
--chef_server | --cs | -c
--frontend | --fe | -f
--postgresql | --pg | -p
--opensearch | --os | -o
2. Removed unnecessary logs in common ssh utilities
3. Changed `config patch` logic from getting **all config** to getting only **applied configs** while patching to the backend node.
Jira ticket : 
It is dev done and tested
=> Add flag for automate and chefserver flag in config patch command

api/config/cs_nginx/config_request.go, terraform/a2ha-terraform/modules/automate/files/config.toml.erb
Signed-off-by: SahithiMy <sahithi.mylangam@progress.com>
Added configuration nginx service for embedded chef server and automate HA chef server. Changed the default config values in cs_nginx.
https://chefio.atlassian.net/browse/STALWART-261
Configs can be patched in automate standalone and automate HA using config files.
rebuild components/automate-cs-nginx/
To see the changes 
cat /hab/svc/automate-cs-nginx/config/nginx.conf
cat /hab/svc/automate-cs-nginx/config/chef_https.conf
*Please add a note next to any checkbox above if you are NOT …
=> Added config for cs_nginx

components/automate-cli/cmd/chef-automate/automateConfigUtils.go, components/automate-cli/cmd/chef-automate/automateConstants.go, components/automate-cli/cmd/chef-automate/automateHADeployExistingInfra.go, components/automate-cli/cmd/chef-automate/certRotate.go, components/automate-cli/cmd/chef-automate/config.go, components/automate-cli/cmd/chef-automate/initConfigHa.go, components/automate-cli/cmd/chef-automate/pullAndGenerateConfig.go, components/automate-cli/cmd/chef-automate/pullAndGenerateConfig_test.go, components/automate-cli/cmd/chef-automate/upgrade.go
As an automate user I may want to upgrade, but I have also rotated my certificates, after update I want to have all my certificates are getting used in upgraded Automate  HA.
We are pulling all the certificates from individual nodes, and refreshing config before upgrade
https://chefio.atlassian.net/browse/MADROX-379
Dev tested, 
=> Jay/madrox 379 - dedicated path for upgrade

components/license-control-service/pkg/storage/storage.go, terraform/a2ha-terraform/modules/automate/inputs.tf, terraform/a2ha-terraform/modules/aws/inputs.tf, terraform/a2ha-terraform/modules/elasticsearch/inputs.tf, terraform/a2ha-terraform/modules/habitat/inputs.tf, terraform/a2ha-terraform/modules/opensearch/inputs.tf, terraform/a2ha-terraform/modules/postgresql/inputs.tf, terraform/a2ha-terraform/modules/system/inputs.tf, terraform/a2ha-terraform/modules/system_hardening/inputs.tf, terraform/a2ha-terraform/variables_common.tf
In cleanup command we still have for /var/automate-ha : this will work with old pkg.
=> Change Dir structure from /var/automate-ha to /hab/var/automate-ha

components/automate-cli/cmd/chef-automate/migrator/migratorv4/patchopensearch.go, components/automate-cli/cmd/chef-automate/migrator/migratorv4/patchopensearch_test.go, lib/majorupgrade_utils/utils.go
Max minimum shards set to 2500 with buffer of 1000
this is required for opensearch
https://chefio.atlassian.net/browse/SHIELD-174?atlOrigin=eyJpIjoiZDFhYWFhMWJjNGEwNGVmMjkwY2QxZGI0NmNmNThlMTUiLCJwIjoiaiJ9
=> Max minimum shards set to 2500 with buffer of 1000

components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
=> Docs change ha troubleshooting

components/automate-backend-deployment/habitat/hooks/install, components/automate-backend-deployment/habitat/plan.sh, components/automate-cli/cmd/chef-automate/pullAndGenerateConfig.go, terraform/a2ha-terraform/modules/habitat/templates/install_hab.sh.tpl
=> copying the config.toml from old workspace to new workspace

components/automate-cli/cmd/chef-automate/certRotate.go, components/automate-cli/cmd/chef-automate/certRotate_test.go, components/automate-cli/cmd/chef-automate/sshUtils.go
- Added validation to check whether the remote IP address is part of the HA cluster.
- Added 30 seconds time out in SCP command.
https://chefio.atlassian.net/browse/SHIELD-173
https://github.com/chef/automate/pull/7536
1. The remote path should be in one of the associated nodes of the HA cluster.
2. SCP should time out in 30 seconds rather than waiting indefinitely.
https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/Efdahs8WrbFFvGoh_7PXZ-8BTHi4Vh-TYT3Qbrs-Vp8RSA?e=L7OoVw
=> Cert rotate remote path fix

components/automate-backend-ctl/README.md, components/automate-backend-deployment/README.md
=> Bumping automate HA Backend-ctl for upgrade scenario 

components/automate-cli/cmd/chef-automate/certRotate.go
=> temp change to trigger the build for Habitat packages

components/automate-cli/cmd/chef-automate/backup.go, components/automate-cli/cmd/chef-automate/sshUtils.go
=> Handling boolean in backup command and added debug logs

components/docs-chef-io/content/automate/chef_infra_in_chef_automate.md
Signed-off-by: dishanktiwari2501 <dtiwari@progress.com>
- The documentation needs to be added to public docs.
- The document should talk about:
- The Settings
- The default value in standalone
- The default value in HA
- A two-liner example of how to patch
- https://chefio.atlassian.net/browse/STALWART-264
=> Chef Server settings with Default Values

components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
=> correcting the onprem deployment cleanup flag

components/automate-backend-deployment/README.md, components/automate-cli/cmd/chef-automate/config.go, components/automate-cli/cmd/chef-automate/initConfigHaTmpl.go, components/automate-cluster-ctl/templates/terraform.tfvars.erb, terraform/a2ha-terraform/modules/opensearch/main.tf, terraform/a2ha-terraform/modules/opensearch/templates/opensearch_user.toml.tpl
=> Fixing variable name

components/automate-openjdk/habitat/plan.sh
Issue: https://chefio.atlassian.net/browse/KINETICS-222
=> upgrading openJDK to 11.0.17

components/automate-backend-opensearch/habitat/plan.sh, components/automate-opensearch/habitat/plan.sh
Issue: https://chefio.atlassian.net/browse/KINETICS-222
```
rebuild components/automate-opensearch/
```
All the services should be up and running. 
Then load some compliance data
`chef_load_compliance_scans -N10 -D4 -M3 -T1000`
There should not be any errors. 
Following scenarios are tested with Standalone automate with Open Search 1.3.6
Automate
Compliance:
Client Run:
Login to UI and test Compliance flow.
=> upgrading open-search to 1.3.6

components/automate-cli/cmd/chef-automate/automateConstants.go, components/automate-cli/cmd/chef-automate/automateHAAwsDeployment.go, components/automate-cli/cmd/chef-automate/initConfigHa.go, components/automate-cli/cmd/chef-automate/pullAndGenerateConfig.go, components/automate-cli/cmd/chef-automate/pullAndGenerateConfig_test.go, components/automate-cli/cmd/chef-automate/upgrade.go, components/automate-cli/pkg/testfiles/aws.auto.tfvars
while upgrading AWS deployment with a command, it should pull the config from FE and BE which prevents Patching the stale template config.
https://chefio.atlassian.net/browse/MADROX-392
**Tested with scenarios**
- Upgraded with Aws Deployment when /hab/a2_deploy_workspace/config.toml exists , with below command
> chef-automate upgrade run --airgap-bundle latest.aib
- Upgraded with Aws Managed Services Deployment when /hab/a2_deploy_workspace/config.toml exists, with below command
> chef-automate upgrade run --airgap-bundle latest.aib --upgrade-frontends
- Upgraded with Aws Deployment when /hab/a2_deploy_workspace/config.toml  doesnot exists , with below command
> chef-automate upgrade run --airgap-bundle latest.aib
- Upgraded with Aws Managed Services Deployment when …
=> Dedicated path for AWS upgrade 

components/automate-deployment/pkg/services/internal/generated/gen.go, products.meta
=> Remove the pkg automate-elasticsearch

.expeditor/verify_private.pipeline.yml, integration/helpers/backup.sh
=> Fix backup to s3 integration test

components/automate-deployment/pkg/services/internal/generated/gen.go, products.meta
=> Add automate-elasticsearch package again 

components/automate-deployment/habitat/plan.sh
=> Bump the minor version

api/config/cs_nginx/config_request.go, api/config/erchef/config_request.go, components/automate-cs-oc-erchef/habitat/config/sys.config, components/docs-chef-io/content/automate/centralizing_log.md, components/docs-chef-io/content/automate/chef_infra_in_chef_automate.md, terraform/a2ha-terraform/modules/automate/files/config.toml.erb
Resolving the issue with default values for HA and document for centralised logging and chef infra config.
https://chefio.atlassian.net/browse/STALWART-300
https://chefio.atlassian.net/browse/STALWART-300
```
rebuild components/automate-cs-oc-erchef/
rebuild components/automate-cs-nginx/
```
=> Resolving default values and documents

components/automate-cli/cmd/chef-automate/config.go, components/automate-cluster-ctl/libexec/cluster-status
https://chefio.atlassian.net/browse/KINETICS-278
https://chefio.atlassian.net/browse/KINETICS-280
use the generated hab file and prepare the custom airgap bundle
use the custom airgap bundle and do the HA deployment with 2 automate nodes and 2 cs nodes
run `chef-automate config show --a2`
This should list the configuration of both automate nodes
`chef-automate config show --cs`
This should list the configuration of both server nodes
run `chef-automate status`
This should IP Address as a column header
*Please add a …
=> update to show the config for all frontend nodes

components/automate-cli/cmd/chef-automate/ha_cert_show.go, components/automate-cli/cmd/chef-automate/ha_cert_show_test.go, components/automate-cli/cmd/chef-automate/ha_node_operations_utils.go, components/automate-cli/cmd/chef-automate/initConfigHa.go, components/automate-cli/cmd/chef-automate/pullAndGenerateConfig.go, components/automate-cli/cmd/chef-automate/upgrade.go
Fix for cert show command.
https://chefio.atlassian.net/browse/MADROX-410
https://chefio.atlassian.net/browse/MADROX-411
=> Cert Show Fix

components/docs-chef-io/content/automate/chef_infra_in_chef_automate.md, terraform/a2ha-terraform/modules/automate/files/config.toml.erb
=> Changing the default value for worker processes

components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
=> update the msg for the node to be remove for backend node.

components/automate-deployment/pkg/server/automate_config.go
error for centralised log resolved, when we were patching cert rotate commands.
https://chefio.atlassian.net/browse/STALWART-303
```
rebuild components/automate-deployment
```
=> Adding changes for centeralised logging

components/docs-chef-io/content/automate/ha_backup_restore_aws_efs.md, components/docs-chef-io/content/automate/ha_backup_restore_aws_s3.md, components/docs-chef-io/content/automate/ha_backup_restore_file_system.md, components/docs-chef-io/content/automate/ha_backup_restore_object_storage.md
=> Backup restore doc changes

components/automate-cli/cmd/chef-automate/initConfigHaTmpl.go
When we do aws managed services deployment then manage_rds_certificate field had incorrect value, root cause found out that this value was coming from template generated at init-config-level
**Steps to reproduce** 
- Deploy Automate HA AWS with managed services
- check config.toml and a2ha.rb in /hab/a2_deploy_workspace dir
- search for field managed_rds_certificate it will have some invalid characters like this "<cert content>"
https://chefio.atlassian.net/browse/MADROX-408
Dev Verified
- CLI need to re-build
- use newly build cli to deploy automate ha aws with managed services
- initial config.toml generated with init-config-ha aws should not have default value for field manage_rds_certificate
- it should be blank by default.
- now …
=> correcting aws manage rds certificate template

components/infra-proxy-service/integration_test/nodes_test.go, components/infra-proxy-service/server/nodes.go
Infra Server View throwing error while fetching cookbooks for Policies
When accessing some Chef Infra servers, we get a message displayed "Could not get node run list: Cannot load environment <policy_groupname>". This is occurring when accessing nodes with policy files.
Bug issue: https://chefio.atlassian.net/jira/software/c/projects/STALWART/boards/361?modal=detail&selectedIssue=STALWART-289
- The corresponding integration test needs to be written first
- The test should error in the beginning
- The changes need to be made in the code
- Write unit tests for the code related to Node data
- Write unit tests for the new code 
- After the change, the integration test need to be passing
- The unit test coverage of the new code should be more than 60%
`rebuild components/infra-proxy-service/` …
=> Stalwart 289

components/infra-proxy-service/integration_test/clients_test.go, components/infra-proxy-service/integration_test/cookbooks_test.go, components/infra-proxy-service/integration_test/databags_test.go, components/infra-proxy-service/integration_test/environments_test.go, components/infra-proxy-service/integration_test/orgs_test.go, components/infra-proxy-service/integration_test/roles_test.go, components/infra-proxy-service/server/nodes.go
Fixed integration test cases for infra proxy service and added new ones
https://chefio.atlassian.net/browse/STALWART-292
Infra proxy service has more integration test coverage now
run below command
```
hab studio run "source scripts/verify_studio_init.sh && start_deployment_service && chef-automate dev deployinate && infra_service_integration"
```
=> Integration test cases for infra proxy service

components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
Doc change for ha add node by ips
=> Doc change for ha add node by ips

components/automate-cli/cmd/chef-automate/cleanup.go
=> update the symbolic link logic in cleanup command

components/automate-cli/cmd/chef-automate/automateHAAwsDeployment.go, components/automate-cli/cmd/chef-automate/cleanup.go, components/automate-cli/cmd/chef-automate/initConfigHaTmpl.go, terraform/a2ha-terraform/modules/aws/main.tf, terraform/a2ha-terraform/modules/s3/inputs.tf, terraform/a2ha-terraform/modules/s3/main.tf, terraform/a2ha-terraform/modules/s3/templates/createS3Bucket.sh, terraform/a2ha-terraform/reference_architectures/aws/main.tf
Signed-off-by: Tejaswi B <bondila.venkatatejaswi@progress.com>
For Automate HA as a product, when the user gives an existing bucket name in the config, it should be added to the configuration. 
Other changes:
- Adding names to Volumes
- Making delete_on_termination configurable
- Updating cleanup scenarios
Note:
1. On Provisioning, terraform will not add a random string at the end of the bucket name
2. S3 Bucket name is mandatory
Jira Ticket: https://chefio.atlassian.net/browse/MADROX-427
Use the following deployment package for testing:
`arvinth/automate-ha-deployment/0.1.0/20230120181343`
All PRs **from Progress …
=> Creating S3 bucket on condition

components/automate-cli/cmd/chef-automate/backup.go
https://chefio.atlassian.net/browse/SHIELD-228
=> cli output improvements

components/automate-backend-opensearch/habitat/plan.sh, components/automate-opensearch/habitat/plan.sh
I have upgraded the opensearch version from 1.3.6 to 1.3.7
https://chefio.atlassian.net/browse/KINETICS-298
For Standalone Automate
- rebuild components/automate-opensearch/
For Automate HA
- build components/automate-backend-opensearch
=> Upgrading opensearch version from 1.3.6 to 1.3.7

components/automate-backend-deployment/README.md
Package version bump with backend-deployment component changes
=> Package bump

components/automate-cli/cmd/chef-automate/backup.go
when we trigger restore command from bastion it could not restore when any frontend services are unhealthy, so stopped the services `sudo systemctl stop chef-automate` instead of `sudo chef-automate stop`
https://chefio.atlassian.net/browse/MADROX-432
You can use the following cli to test the changes
bvtejaswi/automate-cli/0.1.0/20230127053546
=> Fixing Restore Bug 

components/automate-cli/cmd/chef-automate/ha_node_delete_aws.go, components/automate-cli/cmd/chef-automate/ha_node_delete_onprem.go, components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
https://chefio.atlassian.net/browse/MADROX-448
=> fix for remove node in managed services

components/docs-chef-io/content/automate/ha_backup_restore_aws_efs.md, components/docs-chef-io/content/automate/ha_backup_restore_aws_s3.md, components/docs-chef-io/content/automate/ha_backup_restore_file_system.md, components/docs-chef-io/content/automate/ha_backup_restore_object_storage.md
=> HA Documentation Fix [4.5.20]

components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md
=> update the subnet and AZ requirement

components/automate-cli/cmd/chef-automate/initConfigHaAws.go, components/docs-chef-io/content/automate/datafeed.md
https://chefio.atlassian.net/browse/SHIELD-236
=> Doc improvement for `updated_nodes_only` in data feed

components/automate-deployment/habitat/plan.sh, components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md, components/docs-chef-io/content/automate/loadbalancer_configuration.md
Documentation Update for AWS Deployment Non-Managed Services
https://chefio.atlassian.net/browse/SHIELD-237
=> Documentation Update for AWS Deployment Non-Managed Services

components/automate-cli/cmd/chef-automate/ha_node_operations_utils.go
`arvinth/automate-cli/0.1.0/20230210195330`
=> Removing s3 resource from state file

components/automate-deployment/habitat/plan.sh, components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md, components/docs-chef-io/content/automate/managed_services.md
=> updated managed service prerequisite docs section

components/automate-ui/package-lock.json, components/automate-ui/package.json
=> angular2-template-loader dependency removed

components/automate-ui/src/app/entities/client-runs/client-runs.requests.ts
Signed-off-by: Agam Mathur <agmathur@progress.com>
Changed the response type from string to Blob. This resolved the Chrome bug of downloading zero byte file when there are more than 15,000 nodes. I have tested the solution with more than 60,000 nodes which downloaded a file of size 3.35GB.
https://chefio.atlassian.net/browse/KINETICS-260
We should be able to download JSON type report in Chrome with more than 15,000 nodes.
Run a EC2 instance with more than 15,000 nodes, checkout the branch and run below commands:
- [ x] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dc …
=> KINETICS-260: JSON type report download in Chrome.

components/automate-ui/src/app/page-components/run-history/run-history.component.ts, components/config-mgmt-service/grpcserver/cfg_mgmt.go, components/config-mgmt-service/grpcserver/nodes.go
Made changes in two APIS (GetRuns, cfgmgmt) to accept UTC time format as well. Updated frontend function change to send data with API with respect to selected dropdown.
https://chefio.atlassian.net/browse/KINETICS-255
https://user-images.githubusercontent.com/54974312/218706459-656846c7-60d1-4979-b11f-96738a85aa02.mov
=> Changes added for last 24 hour node history bug

components/docs-chef-io/content/automate/centralizing_log.md
As an Automate user, I want to refer to the public document to understand all the different frequently asked questions related to centralised logging.
- Add FAQs into the centralised log page.
- Check the preview link
=> Added FAQs

components/automate-ui/package-lock.json, components/automate-ui/package.json
Signed-off-by: Vaibhav Gadre <vaibhavukandrao.gadre@progress.com>
Fix for thee dependant critical issue reported here: https://github.com/chef/automate/security/dependabot/370
The vulnerable package "socket.io-parser" is dependency of socket.io which is dependency of karma package in devDependencies.
So to fix this internal dependency karma is updated from 6.2.0 to 6.3.20 which updates the ocket.io-parser from 4.0.4 to 4.2.2.
https://chefio.atlassian.net/browse/STALWART-295
- socket.io-parser security vulnerability is fixed by updating package.json.
- After update verified the basic UI functionalities
*Please …
=> Bump karma package from 6.2.0 to 6.3.20  in /components/automate-ui

components/automate-ui/src/app/pages/data-feed-create/data-feed-create.component.ts
https://chefio.atlassian.net/browse/SHIELD-222
=> fixed s3 invalid inputs error message

components/automate-cli/cmd/chef-automate/initConfigHaTmpl.go, components/automate-cli/pkg/testfiles/onprem/config.toml, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
https://chefio.atlassian.net/browse/SHIELD-233
=> onprem mode changes

components/automate-cli/cmd/chef-automate/backup.go, components/automate-cli/cmd/chef-automate/sshUtils.go, lib/stringutils/strings.go
https://chefio.atlassian.net/browse/SHIELD-195
=> fix restore command cli output

components/automate-cli/cmd/chef-automate/sshUtils.go
Fixed timeout incase of ssh config override
=> Fixed timeout incase of ssh config override

components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md, components/docs-chef-io/content/automate/ha_troubleshooting.md, terraform/a2ha-terraform/modules/opensearch/templates/provision.sh.tpl
In case of failure while executing deploy / upgrade command we have to add steps in FAQ section to troubleshoot by themselves.
https://chefio.atlassian.net/browse/MADROX-442
https://deploy-preview-7746--chef-automate.netlify.app/
=> Need to add FAQ for sysctl command is missing

components/docs-chef-io/content/automate/ha_chef_backend_to_automate_ha.md
=> updating infra server to ha migration

components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md, components/docs-chef-io/content/automate/ha_existing_a2ha_to_automate_ha.md, components/docs-chef-io/content/automate/ha_inplace_migration.md
=> Update Docs for Migration 

components/automate-cli/cmd/chef-automate/automateConstants.go, components/automate-cli/cmd/chef-automate/cmdUtils.go, components/automate-cli/cmd/chef-automate/cmdUtils_test.go, components/automate-cli/cmd/chef-automate/config.go, components/automate-cli/cmd/chef-automate/constants.go
In Automate HA, currently commands run in consecutive manner on frontend and backend nodes.So a Utility is created to run commands concurrently on nodes.
Flags for Nodes:-
Arg/ Flag | Duplicate | Shorthand
-- | -- | --
--frontend | --fe | -f
--automate | --a2 | -a
--chef_server | --cs | -c
--postgresql | --pg | -p
--opensearch | --os | -o
Jira Ticket :- https://chefio.atlassian.net/browse/CHEF-1015
- Created a common Utility to run commands concurrently on nodes like automate,chef-server,etc.
- Made changes for `chef-automate config show` and `chef-automate config patch` commands for using this utility
Scenarios Tested:-
- config show for all nodes
- config show with output file for all nodes
- config patch for all nodes
- config show and patch for managed services
- Checkout this Branch …
=> Utility for concurrently running commands on nodes in HA

components/docs-chef-io/content/automate/ha_existing_a2ha_to_automate_ha.md
=> update the migration steps

components/notifications-service/habitat/plan.sh
=> Fixed notification service not building on habitat pipeline

components/automate-ui/package-lock.json, components/automate-ui/package.json
The latest possible version that can be installed is 0.2.3 because of the following conflicting dependency:
The earliest fixed version is for JSON-schema 0.4.0.
https://github.com/chef/automate/security/dependabot/80
I have updated a package to bump the `jsprim` version to > 2.0.2
- [-] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [-] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).
*Please add a note next to any checkbox above if you are …
=> update dependency packages to fix the  json-schema package

components/docs-chef-io/content/automate/ha_inplace_migration.md
Fixing missing code block for example command output
=> Update A2HA Inplace Migration to Automate HA docs

components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md, components/docs-chef-io/content/automate/ha_inplace_migration.md
=> Update Migration Page for Automate to Automate HA 

components/automate-cli/cmd/chef-automate/automateConstants.go, components/automate-cli/cmd/chef-automate/cmdUtils.go, components/automate-cli/cmd/chef-automate/pre_flight_check.go, components/automate-cli/cmd/chef-automate/pre_flight_check_test.go, components/automate-cli/cmd/chef-automate/sshUtils.go
Made changes to support chef-automate preflight-check command from bastion. The following commands are supported from bastion :
```
chef-automate preflight-check --ha-deployment-config <path to your config.toml on bastion> --automate
chef-automate preflight-check --ha-deployment-config <path to your config.toml on bastion> --a2
chef-automate preflight-check --ha-deployment-config <path to your config.toml on bastion> -a
chef-automate preflight-check --ha-deployment-config <path to your config.toml on bastion> --chef_server
chef-automate preflight-check --ha-deployment-config <path to your config.toml on bastion> --cs
chef-automate preflight-check --ha-deployment-config <path to your config.toml on bastion> -c
chef-automate preflight-check --ha-deployment-config <path to your config.toml …
```
=> CHEF-721: Preflight-check from bastion

components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md
=> Minimum Version for Automate Migration

components/docs-chef-io/content/automate/backup.md
After creating backup in s3, if user tries to create backup in filesystem, then backup was not creating in filesystem. So we fix the configurations.
https://chefio.atlassian.net/browse/CHEF-2224
=> backup doc fix

components/docs-chef-io/content/automate/ha_existing_a2ha_to_automate_ha.md, components/docs-chef-io/content/automate/ha_inplace_migration.md
Add documentation for verify migration 
CHEF-208 and CHEF-351
=> Add instruction for validating migration data

components/automate-backend-deployment/README.md, components/automate-backend-deployment/habitat/hooks/install, components/automate-cli/cmd/chef-automate/genA2haRbTmpl.go, components/automate-cli/cmd/chef-automate/ha_node_operations_utils.go, components/automate-cli/cmd/chef-automate/initConfigHa.go, components/automate-cli/cmd/chef-automate/pullAndGenerateConfig.go, components/automate-cli/cmd/chef-automate/sshAutomateHA.go, components/automate-cli/pkg/testfiles/terraform.tfvars, components/automate-cluster-ctl/lib/cluster/config.rb, components/automate-cluster-ctl/readme, components/automate-cluster-ctl/templates/terraform.tfvars.erb, terraform/a2ha-terraform/destroy/aws/main.tf, terraform/a2ha-terraform/modules/aws/main.tf, terraform/a2ha-terraform/modules/aws/outputs.tf, terraform/a2ha-terraform/modules/aws_output/files/output.tfvars.tpl, terraform/a2ha-terraform/modules/aws_output/inputs.tf, terraform/a2ha-terraform/modules/aws_output/main.tf, terraform/a2ha-terraform/modules/s3/main.tf, terraform/a2ha-terraform/modules/vsphere/outputs.tf, terraform/a2ha-terraform/reference_architectures/aws/main.tf, terraform/a2ha-terraform/reference_architectures/aws/variables.tf, terraform/a2ha-terraform/reference_architectures/deployment/outputs.tf, terraform/a2ha-terraform/reference_architectures/deployment/variables.tf, terraform/a2ha-terraform/reference_architectures/existing_nodes/outputs.tf, terraform/a2ha-terraform/reference_architectures/existing_nodes/variables.tf, terraform/a2ha-terraform/terraform.tfvars.example, terraform/a2ha-terraform/variables_common.tf
Removed unused variables from Terraform scripts and declared already using variables to avoid Warning or Error related to Unused or Unset Terraform Variables.
https://chefio.atlassian.net/browse/MADROX-437
- Tested Onprem deployment with chef managed, AWS managed and self managed services and also  AWS deployment with chef managed and AWS managed services
In all of the above scenarios the testing flow is as following:
1. Deployed with 4.2.59 version( for onprem aws and self managed the deployment is done with 4.4.10)
2. Upgraded to 4.5.34 version.
3. Added and removed  a2 and cs nodes.
4. Then upgraded to latest dev.
5. Added and Removed a node again.
Onprem Deployment output without changes …
=> Remove unused variables from Terraform Scripts which are shown as Warnings in output

components/automate-cli/cmd/chef-automate/pullAndGenerateConfig.go
Updating FQDN in config.toml in for existing infra pull and generating config
April fix for Smoke testing
https://chefio.atlassian.net/browse/CHEF-2747
Dev tested
rebuild cli
=> updating fqdn in generated config.toml

components/docs-chef-io/content/automate/centralizing_log.md
Added correct steps to add monitor
Added the step
=> Centralised logging doc correction

.github/workflows/build.yml, sonar-project.properties
=> Updating git workflow for SonarQube integration

components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, terraform/a2ha-terraform/reference_architectures/deployment/outputs_common.tf
In the current doc for AWS provisioning and deployment, it is mentioned to leave the FQDN empty. That needs to be updated. 
Jira ticket: https://chefio.atlassian.net/browse/CHEF-2689
=> Updating doc

components/automate-cli/cmd/chef-automate/summary.go, components/automate-cli/cmd/chef-automate/summary_test.go
https://chefio.atlassian.net/browse/CHEF-1645
Setup HA deployment 
1. In install this pkg in bastion `smudassi/automate-cli/0.1.0/20230421122019`
2. Run `chef-automate status summary --node "127.0.0.1" -acp`
now you should see error message properly formatted 
=> bug fix: display proper error message

sonar-project.properties
=> Adding test files in exclusions

components/automate-cli/pkg/verifyserver/server/api/v1/status_test.go
=> fix unit test chef-2127

components/automate-cli/pkg/verifyserver/README.md, components/automate-cli/pkg/verifyserver/services/statusservice/statusservice_test.go
=> CHEF-2127_add_readme

components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
Issue: https://chefio.atlassian.net/browse/CHEF-2995
=> Adding the missing doc link

components/automate-cli/pkg/verifyserver/constants/apiurlconstant.go, components/automate-cli/pkg/verifyserver/constants/checkconstant.go, components/automate-cli/pkg/verifyserver/models/batchcheck.go, components/automate-cli/pkg/verifyserver/server/server.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/hardwareresourcechecktrigger/hardwareresourcecountchecktrigger.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/hardwareresourcechecktrigger/hardwareresourcecountchecktrigger_test.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/hardwareresourcecountchecktrigger.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/hardwareresourcecountchecktrigger_test.go, components/automate-cli/pkg/verifyserver/utils/httputils/httputil.go, components/automate-cli/pkg/verifyserver/utils/httputils/httputil_test.go
Implemented the Hardware Resource count check Interface for Batch API. 
https://chefio.atlassian.net/browse/CHEF-2869
- Implement the interface defined in  https://chefio.atlassian.net/browse/CHEF-2602
- The interface implementation should be for all the Bastion checks:
- Hardware resource check - Call the API on Bastion
- The check implementation should create the request body from the Run parameter
- The response structure from the APIs should be formatted as per the need
=> CHEF-2869 : Hardware resurce Count check

components/docs-chef-io/data/automate/cli_chef_automate/commands/chef-automate_gather-logs.yaml, components/docs-chef-io/data/automate/cli_chef_automate/commands/chef-automate_preflight-check.yaml
Modified preflight-check and gather-logs doc for bastion support.
=> Updated ha cli doc to for bastion support

components/automate-cs-ocid/habitat/config/tasks/set_webui_key.rb, components/automate-cs-ocid/habitat/hooks/run, components/automate-cs-ocid/habitat/plan.sh
=> Dynamically set webui key from erchef to ocid

api/config/ocid/config_request.pb.go, api/config/ocid/config_request.proto, components/automate-cs-ocid/habitat/config/automate_config_templates/set_chef_server_config.toml, components/automate-cs-ocid/habitat/config/scripts/set_env_vars.sh, components/automate-cs-ocid/habitat/config/scripts/set_webui_key.sh, components/automate-cs-ocid/habitat/config/tasks/set_env_vars.rb, components/automate-cs-ocid/habitat/config/tasks/set_webui_key.rb, components/automate-cs-ocid/habitat/default.toml, components/automate-cs-ocid/habitat/hooks/run
- Setting environment configuration for ocid component.
=> Configure environment variables for ocid component

components/automate-cli/pkg/verifyserver/constants/mockserverconstants.go, components/automate-cli/pkg/verifyserver/models/startMockServer.go, components/automate-cli/pkg/verifyserver/server/api/v1/handler.go, components/automate-cli/pkg/verifyserver/server/api/v1/startMockServer.go, components/automate-cli/pkg/verifyserver/server/api/v1/startMockServer_test.go, components/automate-cli/pkg/verifyserver/server/routes.go, components/automate-cli/pkg/verifyserver/server/server.go, components/automate-cli/pkg/verifyserver/services/startmockserverservice/mockserversservice.go, components/automate-cli/pkg/verifyserver/services/startmockserverservice/startmockserverservice.go, components/automate-cli/pkg/verifyserver/services/startmockserverservice/startmockserverservice_test.go, tools/credscan/credscan.go
As a user, I need to run a mock server on the selected node with a given port, protocol, and certificate because I want to test if the mock server can start on the given port of the selected node and is accessible.
Jira Ticket: https://chefio.atlassian.net/browse/CHEF-2047
It is dev done and tested
- Install the following version of automate-cli or create a new automate-cli with this branch and install it
- `arvinth/automate-cli/0.1.0/20230518084039`
- start go-fiber server with `chef-automate verify server`
- From postman make the following request to the endpoint `http://localhost:7799/api/v1/start/mock-server`
- **Request**:
For TCP server:
``` json
{
"port": 8000,
"protocol": "tcp"
}
```
For UDP server
```json
{
"port": 8001,
"protocol": "udp"
}
```
For HTTPS server:
```json
{
"port": …
```
=> Start mock server

dev/san_validator.sh
https://chefio.atlassian.net/browse/CHEF-3090
=> adding san validator script

components/automate-ui/src/app/modules/infra-proxy/create-environment-modal/create-environment-modal.component.html, components/automate-ui/src/app/modules/infra-proxy/infra-node-details/infra-node-details.component.html, components/automate-ui/src/app/modules/infra-proxy/infra-node-details/infra-node-details.component.ts, components/automate-ui/src/app/modules/infra-proxy/policy-group-details/policy-group-details.component.html
As a automate user, if we have a policy group available for the infra node, we have set the default environment.
https://chefio.atlassian.net/browse/CHEF-3214
Added changes to set the default environment if the policy group is available.
```
STEP 1
STEP 2
to test this please add the test data
Go to infra servers ---> click to server --> see the list of orgs --> click to org --> click on nodes tab --> click to any of node which have dev environment.
```
- [x ] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, …
=> fixed the runlist tab not loading on infra node details page

.envrc, components/automate-cs-nginx/habitat/config/ocid-external.conf, components/automate-cs-ocid/habitat/default.toml, components/automate-cs-ocid/habitat/hooks/health-check, components/automate-cs-ocid/habitat/hooks/run, components/automate-load-balancer/habitat/config/automate-cs-nginx-location.conf
=> Chef 2424/configure nginx and unicorn

components/automate-cli/pkg/verifyserver/constants/externalpostgresqlconstants.go, components/automate-cli/pkg/verifyserver/models/externalpostgresql.go, components/automate-cli/pkg/verifyserver/server/api/v1/externalpostgresql.go, components/automate-cli/pkg/verifyserver/server/api/v1/externalpostgresql_test.go, components/automate-cli/pkg/verifyserver/server/api/v1/handler.go, components/automate-cli/pkg/verifyserver/server/routes.go, components/automate-cli/pkg/verifyserver/server/server.go, components/automate-cli/pkg/verifyserver/services/externalpostgresqlservice/externalpostgresqlservice.go, components/automate-cli/pkg/verifyserver/services/externalpostgresqlservice/externalpostgresqlservice_test.go, components/automate-cli/pkg/verifyserver/services/externalpostgresqlservice/mockexternalpostgresqlservice.go, components/automate-cli/pkg/verifyserver/utils/db/db.go, components/automate-cli/pkg/verifyserver/utils/db/db_test.go, components/automate-cli/pkg/verifyserver/utils/db/mockdb.go, go.sum, lib/io/fileutils/fileutils.go, lib/io/fileutils/fileutils_test.go, lib/io/fileutils/mockFileUtils.go
Added implementation for validating external Postgres connectivity and infrastructure set by checking its connection. 
https://chefio.atlassian.net/browse/CHEF-2183
This API will return if the external postgresql connectivity is success or not.
Rebuild automate-cli
Hit the api on http://localhost:7799/api/v1/checks/external-postgresql
Sample Request
{
"postgresql_instance_url": "A.B.C.D:7432",
"postgresql_superuser_username": "postgres",
"postgresql_superuser_password": "Progress123",
"postgresql_dbuser_username": "postgres",
"postgresql_dbuser_password": "Progress123",
"postgresql_root_cert": "----- BEGIN CERTIFICATE ------"
}
All PRs **from Progress employees** should tick these …
=> Validation for External postgresql

dev/san_validator.sh
=> update to san_validator

components/automate-cli/pkg/verifyserver/models/batchcheck.go, components/automate-cli/pkg/verifyserver/server/server.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/certificatechecktrigger/certificatechecktrigger.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/certificatechecktrigger/certificatechecktrigger_test.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/firewallchecktrigger/firewallchecktrigger.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/firewallchecktrigger/firewallchecktrigger_test.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/hardwareresourcechecktrigger/hardwareresourcecountchecktrigger_test.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/softwareversionchecktrigger/softwareversionchecktrigger_test.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/sshuseraccesschecktrigger/sshuseraccesschecktrigger_test.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/systemresourcechecktrigger/systemresourceschecktrigger_test.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/systemuserchecktrigger/systemuserchecktrigger_test.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/triggerapi.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/triggerapi_test.go
Fixed issues so that we can get correct response from Batch Check API
Now triggers are getting in the correct way and getting errors in correct way
```
make verify-server
```
```
curl --location 'http://127.0.0.1:7799/api/v1/checks/batch-checks' \
--data-raw '{
"config": {},
"checks": [
"firewall"
]
}'
```
=> Fix Issues with Trigger errors

components/automate-cli/cmd/chef-automate/cliUtils.go
Printing error msg in case iam command fails 
https://chefio.atlassian.net/browse/CHEF-715
[screenshot](https://progresssoftware.sharepoint.com/:i:/s/ChefCoreC/EbEUJTYgljtPjD43WB4cKDcBdumaUfPhA3pwwrV0yvpvJQ?e=ts9QwW)
[demo](https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/EehufdqZ5xVMn86zz2KFqW4BfTZ6baKlidbRt4SmgazvLQ?e=Rh4Mpb)
=> Changes for iam commands

components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
Curl command for automate cli for automate ha onprem was not working properly.Screenshots are added for the error as well as correct output
https://progresssoftware.sharepoint.com/:i:/s/ChefCoreC/ETtoOX7CXHZLvX0SQeXcX0UBTa6BOSodzc7fkwlDyljMYw?e=zJegll
https://progresssoftware.sharepoint.com/:i:/s/ChefCoreC/ETpAQnPukx1DsYoDyLPUUSIBXIBzun3beyU3cSQ7T_XxZw?e=TJENDK
https://progresssoftware.sharepoint.com/:i:/s/ChefCoreC/Ec3fICaDi7dEoiqmkdH1LugBULHrDLnqG6u6W2kHSjiQeA?e=TRjUWf
=> Doc script fix for curl command for automate cli used in automate-ha onprem doc

components/docs-chef-io/content/automate/backup.md, components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md, components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md, components/docs-chef-io/content/automate/managed_services.md
https://chefio.atlassian.net/browse/CHEF-3216
=> Doc Changes for subnet and session_token

components/automate-cli/pkg/verifyserver/constants/nfsmountconstant.go, components/automate-cli/pkg/verifyserver/models/nfsmount.go, components/automate-cli/pkg/verifyserver/server/api/v1/handler.go, components/automate-cli/pkg/verifyserver/server/api/v1/nfsmount.go, components/automate-cli/pkg/verifyserver/server/api/v1/nfsmount_test.go, components/automate-cli/pkg/verifyserver/server/routes.go, components/automate-cli/pkg/verifyserver/server/server.go, components/automate-cli/pkg/verifyserver/services/nfsmountservice/nfsmountservice.go, components/automate-cli/pkg/verifyserver/services/nfsmountservice/nfsmountservice_test.go, components/automate-cli/pkg/verifyserver/services/nfsmountservice/nfsmountservicemock.go, lib/systemresource/mocksystemresource.go, lib/systemresource/systemresource.go, lib/systemresource/systemresource_test.go
In this Pr we trying to get mount location using df -h
https://chefio.atlassian.net/browse/CHEF-2234
1. run `hab studio enter` locally
2. rebuild `components/automate-cli`
3. get bin from pkg to src `cp /hab/pkgs/smudassi/automate-cli/0.1.0/<time stamp>/bin/chef-automate .`
4. upload binary file into ec2 instance
5. make sure to setup nfs on ec2 instance
6. run `chef-automate verify serve`
7. open new terminal ssh into your instance
8. run the curl request
`curl --location --request POST 'http://localhost:7799/api/v1/fetch/nfs-mount-loc' --header 'Content-Type: application/json' --data-raw '{
"mount_location": "/mnt/nfs"
}' | jq`
All PRs **from Progress employees** should tick …
=> Fetch mount location

components/automate-cs-ocid/habitat/hooks/run
Fixed the issues for null oauth application in run hook
=> Fix the run hook for null values

components/docs-chef-io/content/automate/major_upgrade_4.x.md, components/docs-chef-io/content/automate/upgrade.md, components/docs-chef-io/content/automate/upgrade_san_certificates.md
=> update the correct version number on public docs

components/automate-cli/cmd/chef-automate/gather-logs.go, components/automate-cli/cmd/chef-automate/pre_flight_check.go
Added fix for preflight & gather logs command available on bastion doc fix 
=> Command available from bastion doc fix

components/automate-cli/pkg/verifyserver/models/batchcheck.go, components/automate-cli/pkg/verifyserver/models/batchcheck_test.go, components/automate-cli/pkg/verifyserver/server/api/v1/sshusercheck.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/sshuseraccesschecktrigger/sshuseraccesschecktrigger.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/triggerapi.go, components/automate-cli/pkg/verifyserver/services/sshusercheckservice/sshusercheckservice.go, components/automate-cli/pkg/verifyserver/services/sshusercheckservice/sshusercheckservice_test.go
Added the SSH port functionality to SSH User Trigger API
- The batch check api should be able to run ssh user check to all the nodes with ssh_port as the input in the request body
- The response when calling batch check to check the SSH User Access 
- Demo Video explaining the fixes made 
https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/ER2gDAJbiQ9Psc8oBzNJIoUBnEE8Adm9zYhkBOu5oL7anA?e=7xQQe7
=> Added the ssh port to the SSH User Check trigger

components/automate-cli/pkg/verifyserver/services/opensearchbackupservice/opensearchs3backupmanaged_test.go
Added the assert statements in the remaining testcases
https://chefio.atlassian.net/browse/CHEF-3474
- All the testcases should have assert
=> Changes in the test cases to add assert

components/automate-opensearch/habitat/hooks/init, components/docs-chef-io/content/automate/ha_cert_selfsign.md
Issue: https://chefio.atlassian.net/browse/CHEF-3576
=> fixed the error in generating the client.pem in init hook of open search

components/automate-cli/cmd/chef-automate/cmdUtils.go, components/automate-cli/cmd/chef-automate/cmdUtils_test.go
chef-automate status summary command was not showing proper output for some scenarios 
1. when services are in critical state on frontend nodes
2. when services are stopped on frontend nodes
https://chefio.atlassian.net/browse/CHEF-3211
- checkout this branch and rebuild automate-cli
- on new ha cluster run `chef-automate status summary` command
[Screenshot-1](https://progresssoftware.sharepoint.com/:i:/s/ChefCoreC/ET2b-tO_wbRKvY-AyMB_wlIBRYCKdFeeCfrtnefKgk7AVQ?e=EknWoH)
[Screenshot-2](https://progresssoftware.sharepoint.com/:i:/s/ChefCoreC …
=> Fix for status summary

components/automate-cli/cmd/chef-automate/verify.go
Split verify cmd method.
https://chefio.atlassian.net/browse/CHEF-2053
=> split verify cmd method

components/automate-cli/pkg/verifyserver/services/batchcheckservice/batchcheckservice.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/batchcheckservice_test.go
Issue: https://chefio.atlassian.net/browse/CHEF-3564
=> Added Deployment state in Config

components/docs-chef-io/content/automate/ha_backup_restore_file_system.md, components/docs-chef-io/content/automate/ha_config.md, components/docs-chef-io/content/automate/ha_existing_a2ha_to_automate_ha.md, components/docs-chef-io/content/automate/ha_on_premises_deployment_prerequisites.md
Fix 404 link Automate Documentation
* https://chefio.atlassian.net/browse/CHEF-3001
- [ x All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).
=> 404 Link Fixes in Automate Docs

.expeditor/verify_private.pipeline.yml, .studio/chef-server-collection, integration/tests/testing_ocid_config_patch.sh
=> Chef 3749 - Add additional Integration tests

components/automate-cli/cmd/chef-automate/verify.go, components/automate-cli/pkg/verifyserver/models/batchcheck.go, lib/reporting/helperForVerification.go, lib/reporting/reporting.go
Certificates for node by ips in case of aws deployment.
Added ip's in order.
https://chefio.atlassian.net/browse/CHEF-3820
Now we are able to see certs
=> Adding ips for aws certs and sorting the IPS in print response

components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/firewallchecktrigger/firewallchecktrigger.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/firewallchecktrigger/firewallchecktrigger_test.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/firewallchecktrigger/vars.go
https://progresssoftware.sharepoint.com/:i:/s/ChefCoreC/Ebsd4HeQ2mJOt86BAk2Y97sBAyX0v5NSHva35LdFybHxCg?e=b6ZtQn
https://progresssoftware.sharepoint.com/:i:/s/ChefCoreC/EY6nrzGpZOdHmes7TiTfHlwBA4tvjY9qAmQzM-mUPJQ0tQ?e=6X2rmb
Bastion to DB's Ports removal
https://progresssoftware.sharepoint.com/:i:/s/ChefCoreC/EXT9jWoIqVhGq4B7UeS_vJ8BMkfdX7NZ1Sqm7yhYaZDfqQ?e=vHb3B8
https://progresssoftware.sharepoint.com/:i:/s/ChefCoreC/ESEoosmiPNVAs9HWgW8-jkMBYk_0zoZzaHaiEmtolWwRvw?e=sfRxwa
=> firewall output fix

components/automate-cli/cmd/chef-automate/automateHAAwsDeployment.go, components/automate-cli/cmd/chef-automate/automateHADeployExistingInfra.go, components/automate-cli/cmd/chef-automate/initConfigHa.go, components/automate-cli/cmd/chef-automate/initConfigHaTmpl.go, terraform/a2ha-terraform/modules/automate/files/config.toml.erb
As a automate HA developer, i want to accept chef-server fqdn and lb_root-ca as input in config.toml. These changes should be available for all kinds of deployment topologies.
Also make automate root_ca independent from custom_certs_enabled flag.
https://chefio.atlassian.net/browse/CHEF-3631
Checkout to this branch and build `automate-cli` and `automate-backend-deployment`(automate-ha-deployment).
OR
you can use these packages: 
`ssanju/automate-cli/0.1.0/20230630064113`
`ssanju/automate-ha-deployment/0.1.0/20230628074623`
=> Chef server fqdn and LB added in config.toml

components/automate-cli/cmd/chef-automate/verify.go, components/automate-cli/cmd/chef-automate/verify_test.go, components/automate-cli/pkg/verifyserver/constants/certificatevalidation.go, components/automate-cli/pkg/verifyserver/services/certificatevalidation/certificatevalidation.go, components/automate-cli/pkg/verifyserver/services/certificatevalidation/certificatevalidation_test.go
=> Modified resolution msg

api/config/ocid/config_request.go
=> Add validation logic for OCID redirect uri

components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/firewallchecktrigger/firewallchecktrigger.go
Changed udp port check to not trigger if deployment state is post-deployment
https://chefio.atlassian.net/browse/CHEF-3884
Pre-deployment :-
Post-deployment :-
=> Changes to make udp port check for pre-deployment

components/automate-cli/cmd/chef-automate/fetchAwsConfigDetails.go
When we run verify after post-deployment and post workspace upgrade (part of Automate HA upgrade) there might be a chance that output.auto.tfvars file will not be available in the reference_architectures/deployment directory, the same file will available in terraform directory, doing the changes to pick the file from terraform directory in case it is not found in reference_architectures/deployment. 
Tested
Autoatme Cli build
https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/Ebc6bqleTz9E …
=> checking for output.auto.tfvars in terraform dir in case of not available in referance arch dir

api/config/esgateway/config_request.proto, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/nfsmountbackupchecktrigger/nfsmountbackupcheck.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/opensearchs3bucketaccesschecktrigger/opensearchs3bucketaccesscheck.go, lib/config/hadeployconfigverify.go, lib/config/hadeployconfigverify_test.go, lib/config/helper.go, lib/config/helper_test.go
https://chefio.atlassian.net/browse/CHEF-2160
Back up Config made optional for both AWS and Existing Infra, it's checked only if it's provided else it's skipped
HA AWS Managed Screenshots
=> backup_config optional fix

components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/fqdnchecktrigger/fqdncheck.go, components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/fqdnchecktrigger/fqdncheck_test.go
=> Added Certificate check in FQDN

components/automate-cli/cmd/chef-automate/initConfigHaTmpl.go, components/automate-cli/cmd/chef-automate/verify.go
As an Automate HA user, when I generate a new config for AWS, I should see the minimum required EBS volume for each instance in the examples.
=> Updating example in AWS config template

.bldr.toml, .studio/chef-server-collection
=> OCID Integration fix pipeline

components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md
=> Updating notes in AWS managed to configure FQDN

components/docs-chef-io/content/automate/ha_chef_backend_to_automate_ha.md
Replace links in Automate docs from chef.io/downloads/tools/<something> with chef.io/downloads.
https://chefio.atlassian.net/browse/CHEF-3451
=> CHEF-3451 Replace download links

components/docs-chef-io/Makefile
This will clean up the netlify builds a bit when there are pages getting deleted. See for example: #8020
=> Clean up Netlify build previews

components/automate-cli/cmd/chef-automate/config.go, components/docs-chef-io/data/automate/cli_chef_automate/commands/chef-automate_config.yaml, components/docs-chef-io/data/automate/cli_chef_automate/commands/chef-automate_config_oc-id-show-app.yaml
=> [DONT MERGE] Chef 4348/oc id show app docs

components/automate-deployment/pkg/backup/spec.go
=> Backup configuration created for OCID

components/automate-cli/cmd/chef-automate/certRotate.go, components/automate-cli/cmd/chef-automate/certRotate_test.go
=> Deleting the created file in testcase and added test cases which are good to have

components/docs-chef-io/content/automate/ha_performance_benchmarks.md
=> Add ha performance benchmarks page

components/docs-chef-io/content/automate/ha_aws_cert_mngr.md, components/docs-chef-io/content/automate/ha_troubleshooting.md
=> Hugo fix quotes

components/automate-cli/cmd/chef-automate/ha_node_operations_utils.go
when adding new node it's showing "Unknown Error: No Ips Found" error.
Now we are not getting the above error
Use this CLI: `ssanju/automate-cli/0.1.0/20230725083727`
Or build `components/automate-cli`
=> Add Node Fix

components/automate-cli/cmd/chef-automate/certRotate.go
For backend nodes it was not getting the script commands to patch with this fix it would get the commands to patch
https://chefio.atlassian.net/browse/CHEF-4636
bvtejaswi/automate-cli/0.1.0/20230725071936
=> In cert rotate adding correct param for copyAndExecute()

components/automate-cli/cmd/chef-automate/automateHAAwsDeployment.go
https://chefio.atlassian.net/browse/CHEF-4757
=> fix error during provision

components/automate-cli/cmd/chef-automate/certRotate_test.go, components/automate-cli/cmd/chef-automate/cleanup.go, components/automate-cli/cmd/chef-automate/ha_node_operations_utils.go
- Removing the node paran in sync config after adding/removing the node
- Updating clean-up command to remove /var/tmp/*.aib* file in on-prem setup
Jira tickets: 
https://chefio.atlassian.net/browse/CHEF-4948
https://chefio.atlassian.net/browse/CHEF-4802
https://chefio.atlassian.net/browse/CHEF-5141
=> Removing nodes for BE while sync config and updating cleanup command

components/automate-cli/cmd/chef-automate/automateHAAwsDeployment.go, components/automate-cli/cmd/chef-automate/ha_node_add_aws.go, components/automate-cli/cmd/chef-automate/ha_node_add_aws_test.go, components/automate-cli/cmd/chef-automate/ha_node_delete_aws.go, components/automate-cli/cmd/chef-automate/ha_node_operations_utils.go
https://chefio.atlassian.net/browse/CHEF-5125
=> add certs for new node

components/automate-cs-ocid/habitat/hooks/run, components/automate-cs-ocid/habitat/plan.sh
- https://teams.microsoft.com/l/message/19:fa1759429b834b268aeb2d5055d1bcf3@thread.v2/1690983547067?context=%7B%22contextType%22%3A%22chat%22%7D
- https://teams.microsoft.com/l/message/19:fa1759429b834b268aeb2d5055d1bcf3@thread.v2/1690970073716?context=%7B%22contextType%22%3A%22chat%22%7D
=> OCID airgap installation fix for tzinfo-data

components/automate-cli/cmd/chef-automate/genA2haRbTmpl.go
When the backup_config is empty while deployment in On-Prem, terraform throws following error
This issue is fixed. **Find attachment of successful deployment in screenshot section**
=> When backup_mount is not passed, terraform throws error

components/automate-deployment/habitat/plan.sh, components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
=> update the doc for the config verification

components/compliance-service/reporting/relaxting/filters_test.go, components/compliance-service/reporting/relaxting/reports.go, components/compliance-service/reporting/relaxting/reports_test.go
Day_latest flag was causing issue in the trends api as a date range was passed. If we put data for the same nodes on daily basis the graph should reflect changes
https://chefio.atlassian.net/browse/CHEF-1693
Now the graph is available
```
Add data for the same nodes on various days using below:-
./automate-load-test -url https://<automate-url>/api/v0/events/data-collector -token <admin-token> -numberOfElement=10 -concurrency=5 -data=compliance -status=success -i/-o output.json
```
=> Removing the check for day_latest flag in case of date range

components/compliance-service/dao/pgdb/jobs.go
https://chefio.atlassian.net/browse/CHEF-5498
Removed DB details from  API response
```
```
Current response
Response after code change.
=> pg error response fix

components/automate-gateway/gateway/services.go
https://chefio.atlassian.net/browse/CHEF-5496
`
`
Modified Responses
=> compliance error response fix

components/automate-openjdk/habitat/plan.sh
https://chefio.atlassian.net/jira/software/c/projects/CHEF/boards/482?modal=detail&selectedIssue=CHEF-3619
=> upgrade the version of OpenJDK

components/automate-backend-deployment/README.md, terraform/a2ha-terraform/reference_architectures/deployment/main.tf
Jira: https://chefio.atlassian.net/browse/CHEF-4734
=> snapshot values created during provisioning is not taken by default 

components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md
Jira: https://chefio.atlassian.net/browse/CHEF-5508
=> [Doc]Note on IAM role

components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md, components/docs-chef-io/content/automate/ha_config_gen.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
=> update the alternate command instead of config gen

components/automate-cli/cmd/chef-automate/applications.go
As of now the response of application command output was not aligned properly.
This PR is to make the cli output align properly.
https://chefio.atlassian.net/browse/CHEF-5782
build the automate cli and upload some data on applications tab
run the below commands:
`chef-automate applications show-svcs` (show all the services)
`chef-automate applications show-svcs --service-name nginx` (show service which is having service name as nginx)
`chef-automate applications remove-svcs --service-name nginx` (show service which is having service name as nginx and wait for your confirmation prompt to remove it)
`chef-automate applications remove-svcs --service-name nginx -y` (show service which is having service name as nginx and delete it directly)
`chef-automate applications remove-svcs --all` (show …
=> Application Command Output Alignment

components/docs-chef-io/content/automate/ha_aws_deployment_prerequisites.md, components/docs-chef-io/content/automate/ha_on_premises_deployment_prerequisites.md
Modified available space memory and added missing ports
https://chefio.atlassian.net/browse/CHEF-5773
=> Docs change based on the tesco feed back

components/automate-cli/pkg/verifyserver/models/batchcheck.go
=> gcs values for batch check

components/automate-openjdk/habitat/plan.sh
=> OpenJDK Version update to 11.0.20

components/docs-chef-io/content/automate/ha.md
=> adding the performance details to ha overview doc

components/authn-service/server/authenticators.go, lib/logger/zap.go
When we are patching warning as log level, still we were getting info level logs.
https://chefio.atlassian.net/browse/CHEF-1692
When we are patching warning log level, then we are not getting info logs.
Use this pkg: sahiba3108/authn-service/0.1.0/20230828074314
Video Link: https://progresssoftware-my.sharepoint.com/:v:/g/personal/sgoyal_progress_com/EZkCLREqzrlNgfDsJ3o_Q6ABjQyJL-eErapb-AkTh49XLA?e=dgam4x
=> authn-service-log-fix

components/automate-backend-deployment/README.md, terraform/a2ha-terraform/modules/opensearch/inputs.tf, terraform/a2ha-terraform/modules/opensearch/main.tf
=> add the condition in the in opensearch module

components/automate-cli/pkg/verifyserver/services/batchcheckservice/trigger/firewallchecktrigger/firewallchecktrigger_test.go, components/license-control-service/habitat/config/config.toml, components/license-control-service/habitat/default.toml, components/license-control-service/licenseaudit/licenseauditworkflow.go, components/license-control-service/licenseaudit/licenseauditworkflow_test.go, components/license-control-service/pkg/server/config.go, components/license-control-service/pkg/server/grpc.go
Add the license audit scheduler parameter in config.
https://chefio.atlassian.net/browse/CHEF-5804
Now the schedule can be changed for testing purpose from the config itself.
The steps are mentioned in the demo video
```
components/license-control-service/
cd /hab/pkgs/<origin>/license-control-service/<pkg-path>/
add change in default.toml
```
https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/EUqlG7DK50RDm4UinQ1oNEEBN_HnMvfESD7tu4blm9xINQ?e=q9jX3N
After hour support:-
=> Adding config parameters like url, interval and frequency

components/automate-ui/src/app/pages/signin/signin.component.spec.ts, components/automate-ui/src/app/services/license-usage/license-usage.service.spec.ts
Added test cases for LicenseUsageService.
https://chefio.atlassian.net/browse/CHEF-4690
Write unit test cases for LicenseUsageService.
=> CHEF-4690: Added test cases for LicenseUsageService.

components/automate-cli/cmd/chef-automate/config.go, lib/config/genconfig/genconfig.go
UX Requested changes to Config Gen CLI Messages
https://chefio.atlassian.net/browse/CHEF-5967
1. Change to Welcome Message:
1. Change to Conclusion Message:
=> config gen changes to messages

lib/config/genconfig/awshaprovisionconfig.go, lib/config/genconfig/hadeployconfig.go, lib/pmt/prompt.go
Customised the Error Messages for the Regex Pattern Errors.
https://chefio.atlassian.net/browse/CHEF-5967
=> Config gen err msgs

components/automate-cli/cmd/chef-automate/pullAndGenerateConfig.go, components/automate-cli/cmd/chef-automate/pullAndGenerateConfig_test.go
Now able to pull the latest GCS config in pull and generate.
https://chefio.atlassian.net/browse/CHEF-5620
Build the cli or use this cli: ssanju/automate-cli/0.1.0/20230828052937
Video Link: https://progresssoftware-my.sharepoint.com/:v:/g/personal/ssanju_progress_com/ETQ2B_TFat1Eh9R0ci3I3ZgBMGTmjIbk2Xs6fZXtUZgGmg?e=znhU8k
=> GCS_Pull_and_Generate_Changes

components/license-control-service/habitat/default.toml, components/license-control-service/licenseaudit/licenseauditworkflow.go, components/license-control-service/licenseaudit/licenseauditworkflow_test.go
Adding blank url for prod url along with the logic if the url is blank it will not append to the string . If the url has some value it will append with -u flag for license-audit command.
https://chefio.atlassian.net/browse/CHEF-6047
Added the logic now command is formed properly. This is to be done as prod url is not finalised yet, and it can vary.
```
rebuild component/license-control-service
```
https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/Eaw0KDMTXChIg5e-wWIID-4BpaF7H0YJ99qfx0PV3wbQsA?e=3z02jN
=> Adding changes for blank url

components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_healthcheck.md, components/docs-chef-io/content/automate/supermarket_with_automate_ha.md
Jira: https://chefio.atlassian.net/browse/CHEF-5789
=> Doc update for AWS cleanup and misc. changes

components/automate-ui/src/app/app.module.ts, components/automate-ui/src/app/pages/+compliance/+scanner/scanner.routing.ts, components/automate-ui/src/app/pages/+compliance/compliance.routing.ts, components/automate-ui/src/app/services/mfe-session/mfe-session.service.spec.ts, components/automate-ui/src/app/services/mfe-session/mfe-session.service.ts
MFE session service added to stop routing when user is moving to mfe. Updated routing module of compliance where required.
https://chefio.atlassian.net/browse/CHEF-3417
For user experience when user is moving to mfe we have to stop the internal routing of automate. 
1. For local setup just take a branch of code and run it on local machine.
2. When you add manually  (example - "mfe_urls" :  ["/compliance/scan-jobs/jobs"]) to local storage then automate route stops there working for added url.
*Please add a note next to any checkbox above if you are NOT ticking …
=> Mfe session service created

components/automate-cli/cmd/chef-automate/certRotate.go, components/automate-cli/cmd/chef-automate/certRotate_test.go, components/automate-cli/cmd/chef-automate/constants.go, components/automate-cli/cmd/chef-automate/verify.go, components/automate-cli/cmd/chef-automate/verify_test.go, lib/sshutils/mocksshutils.go, lib/sshutils/sshutils.go, lib/sshutils/sshutils_test.go
While testing we find out that cert-rotate is failing due to file path location to copy files is /home and cert-rotate is looking files in /tmp
https://chefio.atlassian.net/browse/CHEF-6152
=> configurable copy to remote

components/automate-backend-deployment/habitat/plan.sh, components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md, components/docs-chef-io/content/automate/ha_config_gen.md
updated init-config-ha commands and config gen example in docs
https://chefio.atlassian.net/browse/CHEF-6183
=> updated commands and config gen example in docs

components/docs-chef-io/content/automate/ha_add_nodes_to_the_deployment.md
Here [https://docs.chef.io/automate/ha_add_nodes_to_the_deployment/#add-more-nodes-in-aws-deployment-with-aws-managed-database](url) in case of aws managed, we are talking about pg and os as well. But that should not be here.
=> add node doc fix

components/docs-chef-io/content/automate/ha_aws_deployment_prerequisites.md, components/docs-chef-io/content/automate/ha_on_premises_deployment_prerequisites.md, components/docs-chef-io/content/automate/loadbalancer_configuration.md
Docs changes for pre-requisites
https://chefio.atlassian.net/browse/CHEF-5875
=> added notes in pre-requisites

components/docs-chef-io/content/automate/ha.md, components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_aws_deployment_prerequisites.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md, components/docs-chef-io/content/automate/ha_config_gen.md, components/docs-chef-io/content/automate/ha_healthcheck.md, components/docs-chef-io/content/automate/ha_on_premises_deployment_prerequisites.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md, components/docs-chef-io/content/automate/ha_onprim_deployment_with_aws_managed_deployment.md, components/docs-chef-io/content/automate/ha_onprim_deployment_with_customer_managed_deployment.md, components/docs-chef-io/content/automate/ha_troubleshooting.md
=> update the --skip-verify flag in the deployment page 

components/automate-cli/cmd/chef-automate/ha_node_operations_utils.go, components/automate-cli/cmd/chef-automate/sshAutomateHA.go, components/docs-chef-io/content/automate/ha_add_nodes_to_the_deployment.md
=> Note of minimum node add-node config 

components/docs-chef-io/content/automate/airgapped_installation.md, components/docs-chef-io/content/automate/applications_dashboard.md, components/docs-chef-io/content/automate/architectural_overview.md, components/docs-chef-io/content/automate/chef_infra_external_cookbooks_in_chef_automate.md, components/docs-chef-io/content/automate/config_opensearch.md, components/docs-chef-io/content/automate/config_postgresql.md, components/docs-chef-io/content/automate/desktop.md, components/docs-chef-io/content/automate/ha.md, components/docs-chef-io/content/automate/ha_add_nodes_to_the_deployment.md, components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md, components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_aws_deployment_prerequisites.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md, components/docs-chef-io/content/automate/ha_backup_restore_aws_s3.md, components/docs-chef-io/content/automate/ha_backup_restore_object_storage.md, components/docs-chef-io/content/automate/ha_config.md, components/docs-chef-io/content/automate/ha_config_gen.md, components/docs-chef-io/content/automate/ha_disaster_recovery_setup.md, components/docs-chef-io/content/automate/ha_disaster_recovery_setup_AWS.md, components/docs-chef-io/content/automate/ha_faqs.md, components/docs-chef-io/content/automate/ha_node_bootstraping.md, components/docs-chef-io/content/automate/ha_on_premises_deployment_prerequisites.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md, components/docs-chef-io/content/automate/ha_onprim_deployment_with_aws_managed_deployment.md, components/docs-chef-io/content/automate/ha_onprim_deployment_with_customer_managed_deployment.md, components/docs-chef-io/content/automate/ha_remove_single_node_from_cluster.md, components/docs-chef-io/content/automate/ha_upgrade_introduction.md, components/docs-chef-io/content/automate/ha_verification_check.md, components/docs-chef-io/content/automate/major_upgrade.md, components/docs-chef-io/content/automate/supermarket_with_automate_ha.md
=> remove the duplicate entry

components/automate-deployment/habitat/plan.sh
=> patch bump for release

lib/config/hadeployconfigverify.go, lib/config/hadeployconfigverify_test.go
https://chefio.atlassian.net/browse/CHEF-6367
=> validation fix

lib/config/genconfig/hadeployconfig.go
As a user when I use config gen it should prompt only supported backup configurations based on the type of deployment chosen.
https://chefio.atlassian.net/browse/CHEF-6369
onprem-aws-managed:
onprem-chef-managed:
=> Improving config gen backup configuration prompts based on deployment type

components/docs-chef-io/content/automate/users.md
=> add the policy msg in user creation

components/automate-backend-deployment/habitat/hooks/install
While adding node in post upgrade scenario in aws with chef-managed deployment, i was getting error in add node command. So fixed that issue
Use this pkg: sahiba3108/automate-ha-deployment/0.1.0/20230915101314
=> copied metdata_token.txt to new workspace

components/automate-backend-deployment/habitat/plan.sh, terraform/a2ha-terraform/modules/automate/files/config.toml.erb, terraform/a2ha-terraform/reference_architectures/existing_nodes/main.tf
sometime add node for opensearch is failing due to keystore script execute before open search is ready, so we have added dependency of open seach module to keystore module
https://chefio.atlassian.net/browse/CHEF-6431
=> making keystore dependend on opensearch

components/automate-cli/cmd/chef-automate/pullAndGenerateConfig.go
Earlier we are dependent on config.toml which is present in workspace but for old customers it won't be there. hence changed that logic.
After code changes ran this command on 4.2.20 (before running the upgrade command manually removed the workspace config.toml):
CLI: ssanju/automate-cli/0.1.0/20230915121820
=> Chef_server LB Fix

components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md, components/docs-chef-io/content/automate/ha_disaster_recovery_setup.md, components/docs-chef-io/content/automate/ha_faqs.md, components/docs-chef-io/content/automate/ha_on_premises_deployment_prerequisites.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md, components/docs-chef-io/content/automate/ha_onprim_deployment_with_aws_managed_deployment.md, components/docs-chef-io/content/automate/ha_onprim_deployment_with_customer_managed_deployment.md, components/docs-chef-io/content/automate/ha_remove_single_node_from_cluster.md
=> Updating docs for LB and provisioning sections for On-Prem

components/automate-backend-deployment/habitat/plan.sh, components/automate-deployment/habitat/plan.sh, components/docs-chef-io/content/automate/datafeed.md, components/docs-chef-io/content/automate/ha_backup_restore_object_storage.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
=> Updating curl and toml for GCS

components/automate-cli/cmd/chef-automate/constants.go, components/automate-cli/cmd/chef-automate/version.go, components/automate-cli/cmd/chef-automate/version_test.go
`chef-automate version` giving the version details only for remote nodes but not for bastion, by which users could not check bastion cli version .With these changes it will provide the bastion cli version details too
https://chefio.atlassian.net/browse/CHEF-6755
[chef-automate version (all nodes)](https://progresssoftware.sharepoint.com/:i:/s/ChefCoreC/ETBT0unRmu9EjGhQ8PSVY3cBYjraj1wF9xrCIXCykSNp7Q?e=YjI6vD)
[chef-automate version -b](https://progresssoftware.sharepoint.com/:i:/s/ChefCoreC/EbVHIB8nb5tEsuPeL7GdrJEBSDXeRh3NOQrpta8qIIcOnQ?e=PN …
=> Allowing to print bastion cli version with chef-automate version command

components/automate-backend-deployment/habitat/plan.sh, components/automate-backend-elasticsearch/habitat/plan.sh, components/automate-cluster-ctl/habitat/plan.sh, components/automate-es-gateway/habitat/plan.sh, components/automate-load-balancer/habitat/plan.sh
https://chefio.atlassian.net/browse/CHEF-4157
=> upgrading the openssl 

components/automate-ui/src/app/services/license-usage/license-usage.service.ts
License usage service updated with required change.
https://chefio.atlassian.net/browse/CHEF-4688
=> required changes added

integration/helpers/ssl_filters.jq
=> Test Security Pipeline

components/automate-ui/package.json
Upgraded moment to latest
https://chefio.atlassian.net/browse/CHEF-7054
=> Upgraded moment to latest

components/automate-deployment/habitat/plan.sh, components/docs-chef-io/content/automate/ha_cert_rotation.md
=> [Doc]Adding note for PG cert-rotate on node level

components/automate-ui/src/app/modules/infra-proxy/select-box/src/lib/select-box.component.ts, components/automate-ui/src/app/page-components/delta-viewer/delta-viewer.component.ts
Removed bypass security and added sanitizatier
https://chefio.atlassian.net/browse/CHEF-4439
=> Removed bypass security and added sanitization in it

components/automate-backend-deployment/habitat/plan.sh, components/automate-cluster-ctl/habitat/plan.sh
=> dummy commits to automate-backend-deployment and automate-cluster-ctl

components/docs-chef-io/content/automate/ha_chef_backend_to_automate_ha.md
We're replacing all links to `www.chef.io/downloads/tools/{something}` to just `www.chef.io/downloads`
=> Correct link in documentation

components/automate-backend-deployment/habitat/plan.sh, components/automate-cluster-ctl/habitat/plan.sh, components/local-user-service/users/dex/dex_test.go, components/session-service/server/server_functional_test.go, go.mod
https://chefio.atlassian.net/browse/CHEF-6950
=> dex pkg upgrade

components/automate-ui/src/app/services/chef-session/chef-session.service.ts
https://chefio.atlassian.net/browse/CHEF-1707
=> state uri fix

components/automate-backend-opensearch/habitat/plan.sh, components/automate-opensearch/habitat/plan.sh
upgraded opensearch version from 1.3.7 to 1.3.14
https://chefio.atlassian.net/browse/CHEF-3196
upgraded opensearch version from 1.3.7 to 1.3.14
rebuild components/automate-backend-opensearch/
rebuild components/automate-opensearch/
rebuild  components/automate-ha-elasticsidecar/
https://progresssoftware-my.sharepoint.com/:v:/g/personal/aaishwar_progress_com/EX3th4MTljNIlpMMNzgOp5UBKkR8FP5iL2QYkSKsn6rp_A?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI …
=> modified plan.sh

components/docs-chef-io/content/automate/_index.md, components/docs-chef-io/content/automate/get_started.md
- Move the existing landing page to /automate/get_started/
- Add new landing page that explains the benefits of Automate.
See page: https://deploy-preview-7987--chef-automate.netlify.app/automate/
=> Add landing overview page to docs

components/automate-ui/src/app/services/license-usage/license-usage.service.ts, components/automate-ui/src/app/services/telemetry/telemetry.service.ts
- [ x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ x] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).
- [ x] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named methods, meaningful variable names, etc.)*
- [ x] Consistency checked? *(user notifications, user prompts, visual patterns, code patterns, variable names)*
- [ x] Repeated code blocks eliminated? *(adapt and reuse existing components, blocks, functions, etc.)*
- [ x] Spelling, grammar, typos checked? *(at a …
=> Updated Pendo init changes

components/license-control-service/migrations/003_deployment_type.down.sql, components/license-control-service/migrations/003_deployment_type.up.sql
Changes to add SaaS Standard deployment type
=> Added SAAS Standard deployment type

components/docs-chef-io/content/automate/ha_cert_rotation.md
Signed-off-by: Matt Gough <matt.gough@progress.com>
Updated the ha_cert_rotation.md document to clarify the prerequisites for certificates and their formats. This change is made based upon customer anguish.
https://docs.chef.io/automate/ha_on_premises_deployment_prerequisites/#certificates
=> clarify certificate format in ha_cert_rotation.md

components/nodemanager-service/habitat/hooks/run
Added the trigger_migration function in the skip_migration flag. 
Does not have any impact on the functionality of the existing service or product. 
NO Behaviour change
=> Added missed entry in the run hook for node-manager service 

components/docs-chef-io/layouts/shortcodes/automate/char-warn.md
=> [Doc] remove the like keyword to avoid the ambiguity

components/docs-chef-io/content/automate/ha.md
=> Fixed document content

components/docs-chef-io/content/automate/ha.md
=> spell fix for ha.md

components/infra-proxy-service/habitat/plan.sh
=> Adding dummy commit

components/automate-ui/src/app/services/license-usage/license-usage.service.ts, components/automate-ui/src/app/services/telemetry/telemetry.service.ts
he count apis fetch the count only for the first call. Pendo was triggering dedicated call to fetch the counts and it was always sending zero. The change is made to use either the License Usage Service count data (in case of login use case) or use the data from count api used to fetch 'days_since_last_post'.
- [ x] I have read the [CONTRIBUTING document](https://github.com/chef/automate/blob/master/CONTRIBUTING.md).
- [ x] All commits signed-off for the [Developer Certification of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).
- [ x] Is the code clear? *(complicated code or lots of comments--subdivide and use well-named …
=> Added fix for Pendo node count data to set value from first call to count apis

components/docs-chef-io/content/automate/monitoring-alerting-centralized-logging-integration.md
=> Monitoring Alerting and Centralized Logging Integration Page

components/docs-chef-io/content/automate/ha.md, components/docs-chef-io/content/automate/ha_backup_restore_file_system.md, components/docs-chef-io/content/automate/ha_healthcheck.md
=> fix the typo for the ha.md document 

components/local-user-service/habitat/plan.sh
=> Adding dummy commit in local-user-service

components/automate-deployment/pkg/server/automate_config.go
Regenerating automate.log file after it deleted from the specified path 
https://chefio.atlassian.net/jira/software/c/projects/CHEF/boards/482?assignee=60746df1115da6006f1580da&assignee=712020%3Ad2c1e267-ff0f-4938-9184-e58d1eb78a2d&selectedIssue=CHEF-10976
Regenerating automate.log file after it deleted from the specified path
https://progresssoftware-my.sharepoint.com/personal/swatign_progress_com/_layouts/15/stream.aspx?id=%2Fpers …
=> Regenerating log files in specified location

components/automate-backend-deployment/README.md, components/automate-cli/cmd/chef-automate/certRotate.go, components/automate-cli/cmd/chef-automate/certRotate_test.go, components/automate-cli/cmd/chef-automate/cmdUtils.go, components/automate-cli/cmd/chef-automate/deployedConfig.go, components/automate-cli/cmd/chef-automate/deployedConfig_test.go, components/automate-cli/cmd/chef-automate/ha_cert_show.go, components/automate-cli/cmd/chef-automate/ha_cert_show_test.go, components/automate-cli/cmd/chef-automate/ha_node_add.go, components/automate-cli/cmd/chef-automate/ha_node_add_aws.go, components/automate-cli/cmd/chef-automate/ha_node_add_aws_test.go, components/automate-cli/cmd/chef-automate/ha_node_add_onprem.go, components/automate-cli/cmd/chef-automate/ha_node_add_onprem_test.go, components/automate-cli/cmd/chef-automate/ha_node_delete.go, components/automate-cli/cmd/chef-automate/ha_node_delete_aws.go, components/automate-cli/cmd/chef-automate/ha_node_delete_aws_test.go, components/automate-cli/cmd/chef-automate/ha_node_delete_onprem.go, components/automate-cli/cmd/chef-automate/ha_node_delete_onprem_test.go, components/automate-cli/cmd/chef-automate/ha_node_operations_utils.go, components/automate-cli/cmd/chef-automate/ha_node_operations_utils_test.go, components/automate-cli/cmd/chef-automate/mock_ha_node_operations_utils.go, components/automate-cli/cmd/chef-automate/pullAndGenerateConfig.go, components/automate-cli/cmd/chef-automate/pullAndGenerateConfig_test.go, components/automate-cli/cmd/chef-automate/upgrade.go, terraform/a2ha-terraform/modules/automate/templates/provision.sh.tpl
https://chefio.atlassian.net/browse/CHEF-10130
https://chefio.atlassian.net/browse/CHEF-10247
dev tested
build automate/cli
Demo Video
[Remove node automate on-prem](https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/EegM0x8vYD5Bmyifvcqop5wBIahx9-VYHBYLNcWLeUTiXw?e=1wLhPU)
[Add node automate on-prem](https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/EYbtcekw4shCuOV3n3Joi7kBTTddXrxAV7haI9SJtAZCcA?e=4J4OFe)
[Add node postgresql on-prem](https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/EZhb8Q6WQPZCrfTd4aw2fhoBM1XlpNPZ93NUIVhA …
=> Removing unreachable nodes

lib/io/fileutils/fileutils.go
I've added troubleshooting information to the 'invalid cross-device link' issue for better experience of the user.
https://chefio.atlassian.net/browse/CHEF-10698
=> Add troubleshooting information to the 'invalid cross-device link' issue

components/docs-chef-io/content/automate/ha_troubleshooting.md
Added troubleshooting documentation for invalid cross-device link issue.
https://chefio.atlassian.net/browse/CHEF-10698
=> Add troubleshooting documentation for invalid cross-device link issue

components/docs-chef-io/content/automate/security_best_practices.md
https://chefio.atlassian.net/browse/CHEF-7272
https://chefio.atlassian.net/browse/CHEF-12393
Added DOC changes.
=> Doc added for the - AutoComplete not Disabled

.expeditor/verify_private.pipeline.yml, components/automate-cli/cmd/chef-automate/airgap.go, components/automate-cli/cmd/chef-automate/config.go, components/automate-cli/cmd/chef-automate/deploy.go, components/automate-cli/cmd/chef-automate/gather-logs.go, components/automate-cli/cmd/chef-automate/ha_node_add_onprem_test.go, components/automate-cli/cmd/chef-automate/helper.go, components/automate-cli/cmd/chef-automate/init_config.go, components/automate-cli/cmd/chef-automate/license.go, components/automate-cli/cmd/chef-automate/restart.go, components/automate-cli/cmd/chef-automate/service_versions.go, components/automate-cli/cmd/chef-automate/sshUtils.go, components/automate-cli/cmd/chef-automate/start_linx.go, components/automate-cli/cmd/chef-automate/status.go, components/automate-cli/cmd/chef-automate/stop.go, components/automate-cli/cmd/chef-automate/system_logs.go, components/automate-cli/cmd/chef-automate/uninstall.go, components/automate-cli/cmd/chef-automate/version.go
=> Check for automate node in HA

components/automate-cli/cmd/chef-automate/certRotate.go, components/automate-cli/cmd/chef-automate/certRotate_test.go, components/automate-cli/cmd/chef-automate/ha_node_operations_utils.go, components/automate-cli/cmd/chef-automate/mock_ha_node_operations_utils.go, components/automate-cli/cmd/chef-automate/summary.go
To reduce total time taken for certificate rotation using certificate rotation templates, we have reduce timeout for turning maintenance mode on or off, also we have change the sequence of restarting PG nodes on order of first follower node will be restarted once follower node is healthy then only leader node will be restarted, It should possibly solve two problems, first one is split brain on add and remove node, and second one is data loss in leader node re-election.
https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/ERmL6yE6Q7NNi0IZ …
=> Jay/chef 11760-certificate rotation refactoring

components/authz-service/storage/postgres/postgres.go
=> Authz service restart will be in CRICTICAL state in Automate HA, post restart for A2 Node 

components/automate-backend-elasticsidecar/habitat/bin/elastic_sidecar.rb
=> Remove the func call insert_dashboards, which is not required

components/automate-ui/package-lock.json, components/automate-ui/src/app/entities/license/license.effects.ts, components/automate-ui/src/app/entities/license/license.model.ts, components/automate-ui/src/app/modules/license/license-apply/license-apply.component.html, components/automate-ui/src/app/modules/license/license-apply/license-apply.component.scss, components/automate-ui/src/app/modules/license/license-apply/license-apply.component.ts, components/automate-ui/src/app/modules/license/license-notifications/license-notifications.component.html
Chef 12685: Grace period UI message changes
=> CHEF-12685: Grace period UI message changes

components/automate-cli/cmd/chef-automate/helper.go
=> empty commit to bump the version

components/automate-cli/cmd/chef-automate/infrastructure_test.go, components/automate-gateway/gateway/middleware/license_interceptor.go, go.mod
Adding 'chef-automate iam admin-access restore' command as an exception
=> Adding restore license as an expection for license inforcement

components/automate-cli/cmd/chef-automate/config.go
=> whitelist config gen

components/automate-cli/cmd/chef-automate/config.go, components/automate-cli/cmd/chef-automate/helper.go
=> whitelist-ha-commands

components/automate-cli/cmd/chef-automate/config.go, components/automate-cli/cmd/chef-automate/start_linx.go
=> white listing the start command

components/automate-cli/cmd/chef-automate/config.go, components/automate-cli/cmd/chef-automate/provisionInfraHa.go, components/automate-cli/cmd/chef-automate/version.go
=> whitelist ha commands

components/automate-cli/cmd/chef-automate/helper.go
=> update warning to error

components/automate-cli/cmd/chef-automate/backup.go, components/automate-cli/cmd/chef-automate/helper.go
=> Backup create cmd (license enforcement fix)

components/automate-cli/cmd/chef-automate/restart.go, components/automate-cli/cmd/chef-automate/sshAutomateHA.go
=> whitelist commands for HA

components/automate-backend-deployment/README.md, terraform/a2ha-terraform/modules/postgresqlconfigsync/README.md, terraform/a2ha-terraform/modules/postgresqlconfigsync/inputs.tf, terraform/a2ha-terraform/modules/postgresqlconfigsync/main.tf, terraform/a2ha-terraform/modules/postgresqlconfigsync/templates/postgres_configsync.sh.tpl, terraform/a2ha-terraform/modules/postgresqlconfigsync/versions.tf, terraform/a2ha-terraform/reference_architectures/deployment/main.tf, terraform/a2ha-terraform/reference_architectures/existing_nodes/main.tf
=> add pg restart in deployment flow

components/automate-cli/cmd/chef-automate/backup.go
=> License enforcement on backup commands except restore

components/automate-backend-deployment/README.md, components/automate-cli/cmd/chef-automate/certRotateFromTemplate.go, components/automate-cli/cmd/chef-automate/certRotate_test.go, terraform/a2ha-terraform/modules/postgresqlconfigsync/inputs.tf
=> pipeline fix

components/automate-pg-gateway/habitat/config/haproxy.conf
https://chefio.atlassian.net/browse/CHEF-14568
=> adding health check in pg gateway

components/automate-gateway/gateway/middleware/license_interceptor.go
=> Adding context as a background

components/automate-cli/cmd/chef-automate/upgrade.go
=> update the cli check

components/automate-cluster-ctl/Gemfile
=> Ruby Incompatibility pipeline fix

components/compliance-service/ingest/pipeline/processor/reports_project_tagger.go, components/compliance-service/ingest/pipeline/processor/reports_project_tagger_test.go, components/compliance-service/ingest/pipeline/publisher/node_manager_publisher.go, components/compliance-service/ingest/pipeline/publisher/node_manager_publisher_test.go
=> Compliance fix

lib/grpc/grpctest/uptodate.go
=> automate-gateway pipeline fix

components/automate-gateway/eventfeed/event_guitar_strings_test.go, components/automate-gateway/eventfeed/events_test.go, components/automate-gateway/gateway/datacollector_internal_test.go, components/automate-gateway/gateway/helpers_internal_test.go, lib/grpc/grpctest/uptodate.go
=> Gateway pipeline fix

.expeditor/verify_private.pipeline.yml, .license_scout.yml, components/license-control-service/pkg/storage/storage.go, components/license-control-service/pkg/storage/storage_test.go, integration/helpers/testing.sh, scripts/repo_health.sh
=> License scout fix 2

components/automate-backend-deployment/README.md, components/automate-cli/habitat/plan.sh, components/automate-cs-nginx/habitat/hooks/health-check, components/automate-cs-oc-erchef/habitat/hooks/health-check, components/automate-deployment/habitat/hooks/health-check, components/automate-es-gateway/habitat/hooks/health-check, components/automate-pg-gateway/habitat/hooks/health-check
=> manual bump multi services

components/automate-pg-gateway/habitat/config/haproxy.conf, components/automate-pg-gateway/habitat/default.toml
we can patch the config to change the max_conn
```[pg_gateway]
[pg_gateway.v1]
[pg_gateway.v1.sys]
max_connections = 351
```      
=> config bug fix pg-gateway fo HA

components/automate-ui/src/app/modules/license/license-lockout/license-lockout.component.html
The trial form URL that is opened when user clicks on 'I don't have a license' link is now appended with UTM query params to help with categorising source in analytics.
=> CHEF-15860 Update trial form URL to include utm query param tags

components/automate-ui/habitat/plan.sh
=> No-op change to force semver update in manifest for automate-ui

components/authn-service/habitat/plan.sh
=> Bump Minor Version

components/docs-chef-io/content/automate/major_upgrade.md
https://progresssoftware.atlassian.net/browse/CHEF-15879
=> Remove Automate HA warning

components/docs-chef-io/content/automate/chef_infra_server.md
https://chefio.atlassian.net/browse/CHEF-15021
=> Adding the Chef Infra Server view to Chef Automate UI Article Link

components/automate-deployment/habitat/plan.sh, components/docs-chef-io/content/automate/ha.md, components/docs-chef-io/content/automate/ha_add_nodes_to_the_deployment.md, components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md, components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_aws_deployment_prerequisites.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md, components/docs-chef-io/content/automate/ha_cert_rotation.md, components/docs-chef-io/content/automate/ha_cert_selfsign.md, components/docs-chef-io/content/automate/ha_chef_backend_to_automate_ha.md, components/docs-chef-io/content/automate/ha_disaster_recovery_setup.md, components/docs-chef-io/content/automate/ha_faqs.md, components/docs-chef-io/content/automate/ha_on_premises_deployment_prerequisites.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md, components/docs-chef-io/content/automate/ha_onprim_deployment_with_aws_managed_deployment.md, components/docs-chef-io/content/automate/ha_onprim_deployment_with_customer_managed_deployment.md
https://progresssoftware.atlassian.net/browse/CHEF-14792
=> Azure feedback for Automate HA  Deployment - phase 1

.expeditor/verify.pipeline.yml, components/automate-cli/cmd/chef-automate/automateHADeployExistingInfra.go, terraform/a2ha-terraform/modules/automate/templates/script/semver.sh, terraform/a2ha-terraform/modules/automate/templates/script/test_semver.sh
=> typo fix for certificate template script in Automate HA 

.expeditor/create-manifest.rb, components/automate-deployment/pkg/services/internal/generated/gen.go, products.meta
removed data-lifecycle component from manifest
removed data-lifecycle component from manifest
components/automate-deployment/
components/automate-cli/
components/automate-gateway/
=> removed data-life-cycle from the products.meta

.expeditor/build.habitat.yml
=> GOPROXY added in hab builder

components/docs-chef-io/content/automate/airgapped_installation.md, components/docs-chef-io/content/automate/configuration.md, components/docs-chef-io/content/automate/get_started.md, components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md, components/docs-chef-io/content/automate/ha_chef_backend_to_automate_ha.md, components/docs-chef-io/content/automate/ha_common.md, components/docs-chef-io/content/automate/ha_node_bootstraping.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md, components/docs-chef-io/content/automate/ha_upgrade_introduction.md, components/docs-chef-io/content/automate/infra_server.md, components/docs-chef-io/content/automate/install.md, components/docs-chef-io/content/automate/major_upgrade.md, components/docs-chef-io/content/automate/major_upgrade_4.x.md, components/docs-chef-io/content/automate/managed_services.md, components/docs-chef-io/content/automate/migrate.md, components/docs-chef-io/content/automate/node_integrations.md, components/docs-chef-io/content/automate/on_prem_builder.md, components/docs-chef-io/content/automate/restore.md
https://progresssoftware.atlassian.net/browse/CHEF-15020
=> Remove references to packages.chef.io

components/automate-scaffolding-go/lib/scaffolding-go.sh
=> adding GOPROXY and GOSUBMDB in script

components/automate-backend-deployment/habitat/plan.sh, components/automate-cli/habitat/plan.sh
=> dummy pr to bump dev version

api/config/deployment/init_config.go, components/automate-cli/cmd/chef-automate/migration_pg.go, components/config-mgmt-service/grpcserver/rollouts.go, lib/io/fileutils/access_linux.go, lib/platform/command/command.go
Correcting Integer conversion type 
https://progresssoftware.atlassian.net/browse/CHEF-12180
Correcting Integer conversion type 
rebuild components/config-mgmt-service/
=> Correcting Integer conversion type 

components/automate-ui/package.json
Fixed pipeline issue
https://progresssoftware.atlassian.net/browse/CHEF-16820
I have updated some changes
=> Fix failing unit tests run - Chef Automate verify pipeline

terraform/a2ha-terraform/modules/habitat/templates/install_hab.sh.tpl
update artifact path for hab upgrade detection
=> update artifact path for hab upgrade detection

components/automate-cs-bookshelf/habitat/plan.sh, components/automate-cs-nginx/habitat/plan.sh, components/automate-cs-oc-bifrost/habitat/plan.sh, components/automate-cs-oc-erchef/habitat/plan.sh, components/automate-cs-ocid/habitat/plan.sh, integration/base.sh, integration/tests/chef_server.sh, integration/tests/chef_server_only.sh, integration/tests/ha_chef_server.sh
=> Updated 15.10.21 chef-server release in automate

components/automate-cli/cmd/chef-automate/automateHAAwsDeployment.go, components/automate-cli/cmd/chef-automate/automateHADeployExistingInfra.go, components/automate-cli/cmd/chef-automate/genA2haRbTmpl.go
=> fix base path default for onprem

components/docs-chef-io/content/automate/centralize_logs.md, components/docs-chef-io/content/automate/chef_automate_license.md, components/docs-chef-io/content/automate/infra_server.md
=> Chef Server License documentation

components/local-user-service/users/dex/dex.go, components/local-user-service/users/dex/dex_test.go, go.mod, go.sum
https://progresssoftware.atlassian.net/browse/CHEF-17459
=> dex upgrade

components/automate-ui/src/app/app.module.ts, components/automate-ui/src/app/page-components/selectbox/selectbox.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+node-credentials/node-credentials-list/node-credential-list.component.spec.ts, components/automate-ui/src/app/pages/+compliance/+node-credentials/node-credentials.module.ts, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.html, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.component.scss, components/automate-ui/src/app/pages/+compliance/+reporting/+reporting-node/reporting-node.module.ts, components/automate-ui/src/app/pages/+compliance/+reporting/reporting.module.ts, components/automate-ui/src/app/pages/+compliance/+scanner/scanner.module.ts
Chef Automate UI not responding when clicking on "+" symbol to show test results
https://progresssoftware.atlassian.net/browse/CHEF-12090
I have added changes to fix this
[Chef-Automate-comp.webm](https://github.com/user-attachments/assets/2c3e4639-b7fe-41e1-81fa-d843c4968881)
=> Fixed Chef Automate UI not responding when clicking on "+" symbol to show test results

components/automate-backend-postgresql/habitat/plan.sh, components/automate-cli/cmd/chef-automate/certRotate_test.go, components/automate-cli/cmd/chef-automate/migration_pg.go, components/automate-postgresql/habitat/plan.sh, components/docs-chef-io/content/automate/create_amazon_rds.md, components/docs-chef-io/content/automate/ha_aws_deployment_prerequisites.md, components/docs-chef-io/content/automate/ha_on_premises_deployment_prerequisites.md, components/pg-sidecar-service/habitat/plan.sh
Updated postgresql package version to 13.18
**Automate HA Airgapped Deployment**
**Automate Standalone Airgapped Deployment**
=> [CHEF-17462] Updated postgresql package version to 13.18

components/automate-cli/cmd/chef-automate/reindexing.go
https://progresssoftware.atlassian.net/jira/software/c/projects/CHEF/boards/1682?selectedIssue=CHEF-17282
The reindexing has been added to cli, hence users can run reindexing manually or in case of error while upgrading from version 3.x.x to 4.x.x.
Install Automate v3.x.x
Feed data into automate
Upgrade to Automate v4.x.x
Run the command `chef-automate reindex`
Demo Vid: https://progresssoftware.sharepoint.com/:v:/s/ChefCoreC/EUCGh6t8XAZElVRCaH26uAkBCAmkVa_sl_Gcw1O2tTc7-A?e=ESJutJ
=> Reindex command for elasticsearch/opensearch 

components/docs-chef-io/content/automate/create_amazon_rds.md
Updated Postgres Engine version to 13.18-R1
=> Updated postgres engine version to 13.18-R1

components/automate-deployment/pkg/target/local_target.go, components/automate-deployment/pkg/target/local_target_test.go
=> hab version with release added

components/event-service/nats/server.go, go.mod, go.sum
upgrading github.com/nats-io/nats-streaming-server from 0.24.3 to 0.24.6
github.com/nats-io/nats-streaming-server from 0.24.3 to 0.24.6
=> Nats streaming server 0.24.6

go.mod
=> replace cmd added

components/automate-cs-bookshelf/habitat/plan.sh, components/automate-cs-nginx/habitat/plan.sh, components/automate-cs-oc-bifrost/habitat/plan.sh, components/automate-cs-oc-erchef/habitat/hooks/run, components/automate-cs-oc-erchef/habitat/plan.sh, components/automate-cs-ocid/habitat/plan.sh
=> updating chef-server components ruby version to 3.1.

components/automate-backend-opensearch/habitat/plan.sh, components/automate-opensearch/habitat/plan.sh
https://progresssoftware.atlassian.net/browse/CHEF-15568
=> Upgrade opensearch

.license_scout.yml, components/trial-license-service/pkg/license/license.go, components/trial-license-service/pkg/server/server_internal_test.go, go.mod, go.sum, lib/license/reader.go
To fix the following dependabot issue:
https://github.com/chef/automate/security/dependabot/652
=> migrate from github.com/dgrijalva/jwt-go to github.com/golang-jwt/jwt

components/automate-backend-postgresql/habitat/config/functions.sh
644 perm for pg log in ha
Jira: https://progresssoftware.atlassian.net/browse/CHEF-16266
=> 644 perm for pg log in ha

components/automate-backend-postgresql/habitat/config/functions.sh
=> change perm to 744

components/automate-cs-bookshelf/habitat/plan.sh, components/automate-cs-nginx/habitat/plan.sh, components/automate-cs-oc-bifrost/habitat/plan.sh, components/automate-cs-oc-erchef/habitat/plan.sh, components/automate-cs-ocid/habitat/plan.sh
=> Updated chef-server components version to 15.10.27 .

components/automate-backend-deployment/habitat/plan.sh
=> pin automate-backend-deployment deps

components/automate-cs-nginx/habitat/plan.sh
=> pin cs-nginx pkg

components/automate-backend-deployment/habitat/plan.sh, terraform/a2ha-terraform/reference_architectures/deployment/main.tf
=> add backend deps on bootstrap automate in aws deployment

.license_scout.yml, .studio/protobuf
=> adding buff check breaking

components/automate-load-balancer/habitat/config/nginx.conf
https://progresssoftware.atlassian.net/browse/CHEF-14756
=> Changing the Nginx rules for `dex` 

components/automate-backend-deployment/habitat/plan.sh, components/automate-cli/cmd/chef-automate/genA2haRbTmpl.go, components/automate-cli/cmd/chef-automate/initConfigHa.go, components/automate-cluster-ctl/lib/cluster/config.rb
=> add chef aws tags

components/pg-sidecar-service/habitat/plan.sh
=> Hardcoding the versions for pgclient and postgres in es side car

components/pg-sidecar-service/habitat/plan.sh
=> Adding the fix for habitat build

.studio/common
=> Fixing fallback channel

components/automate-cli/cmd/chef-automate/genA2haRbTmpl.go, components/automate-cluster-ctl/lib/cluster/config.rb
=> added tags for provisioned instances

e2e/package-lock.json, e2e/package.json
Prototype pollution in lodash
Note: Cypress test cases fail as they are not up-to-date. This will be addressed separately
https://progresssoftware.atlassian.net/browse/CHEF-12490
=> CHEF-12490 Prototype pollution in lodash

.license_scout.yml, go.mod, go.sum, protovendor/go.mod, protovendor/go.sum, scripts/revendor.sh
upgrading github.com/golang/glog version from 1.2.2 to 1.2.4
https://github.com/chef/automate/security/dependabot/746
https://github.com/chef/automate/security/dependabot/747
upgrading github.com/golang/glog version from 1.2.2 to 1.2.4
=> upgrading github.com/golang/glog version from 1.2.2 to 1.2.4

dev-docs/DEV_ENVIRONMENT.md, integration/run_test
=> updating the vault address

components/docs-chef-io/content/automate/backup.md, components/license-control-service/pkg/server/server_test.go
=> Line removed from backup doc

components/docs-chef-io/content/automate/ha_aws_deployment_prerequisites.md, components/docs-chef-io/content/automate/ha_on_premises_deployment_prerequisites.md
=> Add the firewall changes 

components/docs-chef-io/content/automate/configuration.md
=> fixing netlify

components/docs-chef-io/content/automate/restore.md
=> doc correction

components/ingest-service/backend/client.go, components/ingest-service/backend/elastic/migration.go, components/ingest-service/server/chef.go, components/ingest-service/storage/db.go, components/ingest-service/storage/db_test.go
Added GetAliases method to get aliases for indexes.
https://progresssoftware.atlassian.net/browse/CHEF-19077
`build components/ingest service`
`build components/automate-deployment/`
`build components/automate-cli`
Run `chef-automate reindex start`
=> Get the aliases for all the indexes eligible

components/ingest-service/backend/client.go, components/ingest-service/backend/elastic/migration.go, components/ingest-service/server/chef.go
https://progresssoftware.atlassian.net/jira/software/c/projects/CHEF/boards/1682?selectedIssue=CHEF-19079
- Build ingest service
- Build deployment service
- Build cli
- Run `chef-automate reindex start`
=> Creating new indices

components/ingest-service/server/chef.go
=> Seperate version check

components/ingest-service/server/chef.go
=> updating the structure as per the flow

components/ingest-service/server/chef.go, components/ingest-service/server/constants.go, components/ingest-service/storage/db.go, components/ingest-service/storage/db_test.go
https://progresssoftware.atlassian.net/browse/CHEF-19085
=> Adding the create or update stage and status function

components/automate-deployment/pkg/airgap/install_bundle_test.go, components/automate-deployment/pkg/server/automate_config.go, components/automate-deployment/pkg/server/automate_config_test.go
This PR fixes the following Issue:
https://progresssoftware.atlassian.net/browse/CHEF-18817
=> Fixing the maintenance mode issue

components/ingest-service/server/chef.go
=> Adding the overall status

components/docs-chef-io/content/automate/ha_aws_deploy_steps.md, components/docs-chef-io/content/automate/ha_aws_managed_deploy_steps.md, components/docs-chef-io/content/automate/ha_disaster_recovery_setup.md, components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md, components/docs-chef-io/content/automate/ha_onprim_deployment_with_aws_managed_deployment.md, components/docs-chef-io/content/automate/ha_onprim_deployment_with_customer_managed_deployment.md
Added note for correct directory structure and user permissions that is expected by the verify config command
https://progresssoftware.atlassian.net/browse/CHEF-20302
https://progresssoftware.atlassian.net/browse/CHEF-20511
=> Added note for correct directory structure and user permissions for verify config command

components/automate-backend-ctl/habitat/bin/knife, components/automate-backend-ctl/habitat/plan.sh
- Build automate_backend_ctl to use packages from LTS
- Upgrade ruby version to ruby3_4 in automate_backend_ctl component
=> [CHEF-12442] Build automate_backend_ctl to use packages from LTS and upgrade ruby version to ruby3_4

components/automate-backend-ctl/habitat/bin/knife, components/automate-backend-ctl/habitat/plan.sh
=> Revert "[CHEF-12442] Build automate_backend_ctl to use packages from LTS and upgrade ruby version to ruby3_4"

components/docs-chef-io/content/automate/servicenow_incident_creation.md, components/docs-chef-io/content/automate/servicenow_integration.md
https://progresssoftware.atlassian.net/browse/CHEF-18352
=> snow doc update compatibility

components/automate-backend-elasticsidecar/cmd/automate-backend-elasticsidecar/commands/elastic_sidecar.go
=> fix elasticsidecar connection leak issue

components/automate-cli/cmd/chef-automate/reindex.go, components/ingest-service/server/chef.go, components/ingest-service/storage/db.go
=> added heartbeat and heartbeatThreshold

components/docs-chef-io/content/automate/servicenow_incident_creation.md, components/docs-chef-io/content/automate/servicenow_integration.md
update compatibility to reflect yokohama for service now apps
https://progresssoftware.atlassian.net/browse/CHEF-20070
=> update compatibility to reflect yokohama for service now apps

components/automate-backend-deployment/README.md, terraform/a2ha-terraform/modules/automate/files/config.toml.erb
Add condition for hardcoded values so that these values dont get reverted to default values after an upgrade
=> Add condition for hardcoded values so that these values dont get reverted to default values after an upgrade

components/automate-cs-ocid/habitat/plan.sh
Upgrading ocid version to  15.10.36
=> Upgrading ocid version to  15.10.36

components/automate-cli/cmd/chef-automate/reindex.go
=> update to the reindex command

components/docs-chef-io/content/automate/servicenow_incident_creation.md, components/docs-chef-io/content/automate/servicenow_integration.md
=> Revert "update compatibility to reflect yokohama for service now apps"

components/ingest-service/server/chef.go, components/ingest-service/server/constants.go, components/ingest-service/storage/db.go
=> some edge case tracked

components/automate-cli/cmd/chef-automate/certRotateFromTemplate.go
=> Correct log statements

components/automate-cli/cmd/chef-automate/certRotate.go
=> trim space in cert rotate cli

components/docs-chef-io/content/automate/ha_onprim_deployment_procedure.md
=> doc change for 5 node cluster 

components/automate-backend-opensearch/habitat/plan.sh, components/automate-backend-postgresql/habitat/plan.sh
=> Pull latest opensearch and postgres certificates from vault

components/automate-backend-deployment/README.md
Update deployment package so that latest certificates are pulled from the vault
=> Update deployment package so that latest certificates are pulled from the vault

components/docs-chef-io/content/automate/ha_cert_selfsign.md
=> update the script

components/automate-pg-gateway/habitat/plan.sh, components/pg-sidecar-service/habitat/plan.sh
=> migrating pg-gateway to LTS channel

components/automate-load-balancer/habitat/plan.sh
=> unpinning the openssl in Automate Load Balancer

components/docs-chef-io/content/automate/ha_troubleshooting.md
- https://progresssoftware.atlassian.net/browse/CHEF-22829
=> Remove server name from troubleshooting

components/docs-chef-io/content/automate/reusable/md/restore_troubleshooting.md
Update troubleshooting for backup and restore
=> Update troubleshooting for backup and restore

components/trial-license-service/pkg/license/license.go, components/trial-license-service/pkg/server/server_internal_test.go, go.mod, go.sum, lib/license/reader.go
Fixes the following the dependabot issues:
https://github.com/chef/automate/security/dependabot/774
https://github.com/chef/automate/security/dependabot/810
=> upgrade golang-jwt

go.mod
=> fixing dependabot issues

components/docs-chef-io/content/automate/ha_automate_to_automate_ha.md, components/docs-chef-io/content/automate/ha_existing_a2ha_to_automate_ha.md, components/docs-chef-io/content/automate/ha_inplace_migration.md
=> doc improvement

components/automate-deployment/habitat/plan.sh
=> migrating deployment service and openjdk to LTS channel
